### PR TITLE
[Pal] Move x86_64 specific header files and code into Pal/include/arch/x86_64

### PR DESCRIPTION
**Pull request by stefanberger**
This is a first cautious step to move x86_64 specific header files and some code into Pal/include/arch/x86_64/. I have tested this so far primarily with the non-SGX build but detected one build error with SGX that was resolved by fixing a Makefile.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1462)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please (especially curious about `syscall` on SGX pipeline, failed last time but couldn't reproduce locally)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
