### PR TITLE
Fix filesystem and unskip tests

### PR DESCRIPTION
**Pull request by pwmarcz**
Due to an unfortunate accident, the FS tests `LibOS/shim/test/fs` are silently skipped on Jenkins, and filesystem refactor (#2333) got merged with some bugs. This branch fixes these bugs and un-skips the tests.

This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)

### CODE REVIEW

**Review by woju — APPROVED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: 3 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 444 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_gU-yYDSMmxkwDIbTh:-M_gU-yYDSMmxkwDIbTi:b3mhkt6) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/LibOS/shim/src/fs/shim_namei.c#L444)):*
> ```C
>     /* O_CREAT on a normal file triggers creat(), which needs a handle */
>     if ((flags & O_CREAT) && !(flags & O_DIRECTORY))
>         assert(hdl);
> ```

Are you sure this should be an assert? Is this flag combination checked in all callsites?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[.ci/lib/stage-test.jenkinsfile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_t0vUJCgmC8tNE8BVh:-M_t0vUJCgmC8tNE8BVi:b-swh87p) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/.ci/lib/stage-test.jenkinsfile#L58)):*
> ```
>                     make ${MAKEOPTS} sgx-tokens
>                 fi
>                 python3 -m pytest -v --junit-xml fs.xml test_fs.py test_tmpfs.py test_pf.py
> ```

What is the difference between the old `make test` and this new one? Did you just get rid of the Makefile dependency, or was here a bug?
___
*[LibOS/shim/test/fs/Makefile, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_t0gTf1ApAdKglGdji:-M_t0gTg9XbvwtbD1MoZ:baacjl0) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/LibOS/shim/test/fs/Makefile#L24)):*
> ```Makefile
> 	truncate
> 
> all_manifests = $(addsuffix .manifest,$(execs))
> ```

Why is this change important?
___
*[Scripts/regression.py, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_t0lxpA7xJ_JoBm1ul:-M_t0lxpA7xJ_JoBm1um:b-a8tjr6) ([raw file](https://github.com/oscarlab/graphene/blob/adf6269218dfa80aed276d57121a98e7b13b0f4e/Scripts/regression.py#L78)):*
> ```Python
>             self.skipTest('loader ({}) not found'.format(self.loader_path))
>         if not self.libpal_path.exists():
>             self.skipTest('libpal ({}) not found'.format(self.libpal_path))
> ```

Ouch, this was bad...

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_tqg3HDho5YUBhdvZY:-M_tqg3HDho5YUBhdvZZ:b-vkemoi) (no related file):*
Further complaints about the state of matters should go to @woju :) But seriously, let's not spend too much energy on beating the Makefiles into shape - this change doesn't introduce any new hacks, just brings `fs` tests in line with `regression` tests.

---
___
*[.ci/lib/stage-test.jenkinsfile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_t0vUJCgmC8tNE8BVh:-M_toJ7I4IizXp1_2Oty:bdxnx2u) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/.ci/lib/stage-test.jenkinsfile#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the difference between the old `make test` and this new one? Did you just get rid of the Makefile dependency, or was here a bug?
</blockquote></details>

`make test` uses the `run-pytest` wrapper which overrides various environment variables for running Graphene from inside the repo (using `graphene/Runtime/`, etc.)

As I understand, this wrapper is becoming obsolete, and this way of running no longer works in our CI setup. Previously, that was masked by `self.skip(...)`, now `make test` here would fail loudly.
___
*[LibOS/shim/src/fs/shim_namei.c, line 444 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_gU-yYDSMmxkwDIbTh:-M_tpQPa3Pc358a255ns:bxbou6x) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/LibOS/shim/src/fs/shim_namei.c#L444)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are you sure this should be an assert? Is this flag combination checked in all callsites?
</blockquote></details>

The only time we call `open_namei` without `hdl` is in our implementation of `mkdir`, and that call has flags hardcoded to `O_CREAT | O_EXCL | O_DIRECTORY`.

It's looking more and more like `mkdir` should simply use a separate function. But for now, my priority is to fix the bug.
___
*[LibOS/shim/test/fs/Makefile, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2377#-M_t0gTf1ApAdKglGdji:-M_tpr__BHlOHwluXBRe:b-n2u4gm) ([raw file](https://github.com/oscarlab/graphene/blob/319bccc3fae6f7dd44b870d68169941a9e8af971/LibOS/shim/test/fs/Makefile#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this change important?
</blockquote></details>

Because `all_manifests` is a magic name used in `Scripts/Makefile.Test` :(

Without it, `make` did not build the required manifests, so running the tests through `python -m pytest` failed. `make test` still worked because it had the dependency.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2377)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
