### PR TITLE
[Documentation] Add README.md and change requirements.txt

### PR DESCRIPTION
**Pull request by dayeol**
## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dayeol and @dimakuv)

___
*[Documentation/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1730#-MDqQwRdArT8qTjbTiAm:-MFSlxB56oWNXTXpeSI9:bkj8e5l) ([raw file](https://github.com/oscarlab/graphene/blob/1bfa8345b77919f7ad610278ad71ac31fa775de1/Documentation/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole content is already (partially) described in `Documentation/howto-doc.rst`. Look in this file under section `Building documentation`.

I suggest to add only the two first lines from your document (`sudo apt ...` and `pip3 install ...`) to `howto-doc.rst`.
</blockquote></details>

+1 to what Dima said, let's just update howto-doc.rst instead
___
*[Documentation/requirements.txt, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1730#-MFSkmBA-6c1o_kGXO2Z:-MFSkmBB50G_qy1w4w0U:bav8ise) ([raw file](https://github.com/oscarlab/graphene/blob/1bfa8345b77919f7ad610278ad71ac31fa775de1/Documentation/requirements.txt#L2)):*
> ```
> sphinx==1.8.0
> breathe<4.13.0
> ```

@woju: Could you verify this?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dayeol, @dimakuv, and @mkow)

___
*[Documentation/requirements.txt, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1730#-MFSkmBA-6c1o_kGXO2Z:-MGDa7_gBMky9dqmN_vT:b-nqfbff) ([raw file](https://github.com/oscarlab/graphene/blob/1bfa8345b77919f7ad610278ad71ac31fa775de1/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Could you verify this?
</blockquote></details>

I suppose this is because breathe-4.13.0 is the last version to support sphinx<2.0, but to be sure I'd confirm the rationale with the original author.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dayeol, @dimakuv, and @mkow)

___
*[Documentation/requirements.txt, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1730#-MFSkmBA-6c1o_kGXO2Z:-MGDagUF58Y6wNUMan11:b-lnyb8h) ([raw file](https://github.com/oscarlab/graphene/blob/1bfa8345b77919f7ad610278ad71ac31fa775de1/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I suppose this is because breathe-4.13.0 is the last version to support sphinx<2.0, but to be sure I'd confirm the rationale with the original author.
</blockquote></details>

https://github.com/michaeljones/breathe#change-log

**Review by mkow — COMMENTED** [review]
@dayeol Hi, will you have time to finish this PR? There's not too much work left, would be nice to merge it.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730#-:-MGDjdGL9heUm2FezieG:b7tn6r2)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dayeol and @dimakuv)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dayeol)

___
*[Documentation/howto-doc.rst, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/1730#-MGFBbFnAcNJNraAv7B8:-MGFBbFoBBnlH2LW-_uV:b-2yw0ol) ([raw file](https://github.com/oscarlab/graphene/blob/6a3ab9e4e5e6302fbe2cd55487d886ebeed1be94/Documentation/howto-doc.rst#L44)):*
> ```reStructuredText
> ----------------------
> 
> To build documentation, change directory to ``Documentation``, install prerequisites, and use ``make``,
> ```

Please wrap reST at 80 chars per line (see https://graphene.readthedocs.io/en/latest/devel/howto-doc.html#preferred-rest-style)
___
*[Documentation/howto-doc.rst, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/1730#-MGFCyxxEf2qhcjcKpSZ:-MGFCyxxEf2qhcjcKpS_:b-9agjs5) ([raw file](https://github.com/oscarlab/graphene/blob/6a3ab9e4e5e6302fbe2cd55487d886ebeed1be94/Documentation/howto-doc.rst#L65)):*
> ```reStructuredText
>    man _build/man/pal_loader.1
> 
> You can also run a local web server to preview the HTML output.
> ```

This isn't actually needed, simpler way which also works: `firefox Documentation/_build/html/index.html` (should work for other browsers too)
___
*[Documentation/howto-doc.rst, line 71 at r2](https://reviewable.io/reviews/oscarlab/graphene/1730#-MGFD9hsC0PwEicNAHyp:-MGFD9hsC0PwEicNAHyq:baku06u) ([raw file](https://github.com/oscarlab/graphene/blob/6a3ab9e4e5e6302fbe2cd55487d886ebeed1be94/Documentation/howto-doc.rst#L71)):*
> ```reStructuredText
>    python -m SimpleHTTPServer
> 
> Check your documentation by opening the following url in your browser::
> ```

`url` -> `URL`

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dayeol)

___
*[Documentation/requirements.txt, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1730#-MFSkmBA-6c1o_kGXO2Z:-MGIvWoH7B8LyKLCZtAj:b-yxjsfy) ([raw file](https://github.com/oscarlab/graphene/blob/1bfa8345b77919f7ad610278ad71ac31fa775de1/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@dayeol  Do you remember why you had to add this?

@woju What is special about Sphinx 1.8? Why exactly this version?
</blockquote></details>

Distro support.

In ubuntu, >1.8 will be in 20.10 and in LTS only in 22.04; that's two years from now (https://packages.ubuntu.com/search?keywords=python3%2Dsphinx&searchon=all&suite=all&section=all).

In debian, it will be in 11 (bullseye), probably summer/fall 2021 (https://packages.debian.org/search?keywords=python3%2Dsphinx).

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dayeol)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1730)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
