### PR TITLE
LibOS: code clean up of shim_signal.c

### PR DESCRIPTION
**Pull request by yamahata**
this patch cleans up shim_signal.c without logic change.
- remove unnecessary goto
  In this file, goto is abused unnecessarily.
- remove unnecessary macro
  Two macros, is_internal, internal_fault can be inline function.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/302)

### CODE REVIEW

**Comment by donporter** [comment]
Retest this please

**Comment by donporter** [comment]
Retest this please

**Comment by donporter** [comment]
Large mmap unit test failed on SGX.  Let's try this one more time.

**Comment by donporter** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
