### PR TITLE
Add XGBoost example

### PR DESCRIPTION
**Pull request by masdevas**
## Description of the changes
Hi, this PR contains XGBoost(https://github.com/dmlc/xgboost) example with Graphene + SGX.

## How to test this PR?
For testing you should prepare conda environment that contains "pandas", "numpy" and "xgboost" libraries.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1835)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1835)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @masdevas)

___
*[Examples/xgboost/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3P-vs2HKgH8M6zktD:-MI3P-vs2HKgH8M6zktE:b9wjpa1) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L1)):*
> ```Makefile
> # Use one of the following commands to build the manifest for Python3:
> ```

`Python3` -> `XGBoost`
___
*[Examples/xgboost/Makefile, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3P5JO5pocPq88RiiL:-MI3P5JO5pocPq88RiiM:bij4jhd) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L15)):*
> ```Makefile
> include ../../Scripts/Makefile.python
> 
> PYTHONHOME 		:= $(CONDAPATH)/lib/$(PYTHONVERSION)
> ```

If `CONDAPATH` was not specified by the user, then all this logic breaks. Please add a check that `CONDAPATH` is set. Alternatively, set `CONDAPATH` here to some default value (if there is one on Ubuntu).
___
*[Examples/xgboost/Makefile, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3QZ1H3Z4WSY3rATlB:-MI3QZ1H3Z4WSY3rATlC:bt8g3j4) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L17)):*
> ```Makefile
> PYTHONHOME 		:= $(CONDAPATH)/lib/$(PYTHONVERSION)
> PYTHONEXEC 		:= $(CONDAPATH)/bin/$(PYTHONVERSION)
> USRLIB 			:= /usr/lib/$(PYTHONVERSION)
> ```

Why do you have this `USRLIB`? It's a system-wide directory, in contrast to all other directories (which are Conda). And you only use it for one `_hashlib` library of Python. I suggest to check if (1) `_hashlib` library is needed at all, and (2) if needed, install and use `_hashlib` under Conda.
___
*[Examples/xgboost/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3PHRx37zoMbNRQ4rY:-MI3PHRyC2H9xRzr0Ocu:b4cj4s6) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L18)):*
> ```Makefile
> PYTHONEXEC 		:= $(CONDAPATH)/bin/$(PYTHONVERSION)
> USRLIB 			:= /usr/lib/$(PYTHONVERSION)
> PYTHONDISTHOME 	:= $(PYTHONHOME)/site-packages
> ```

Could you please use spaces instead of tabs for these variable declarations?
___
*[Examples/xgboost/Makefile, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3PVS89ezBKBYKL1w2:-MI3PVS89ezBKBYKL1w3:b-z8nymr) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L32)):*
> ```Makefile
> all: python.manifest pal_loader
> ifeq ($(SGX),1)
> all: python.manifest.sgx python.token python.sig
> ```

I know you simply copy-pasted it from another example, but this could be simplified to: `all: python.token`
___
*[Examples/xgboost/Makefile, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Pe_EBLs-91rQk3O3:-MI3Pe_EBLs-91rQk3O4:bplgcss) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L53)):*
> ```Makefile
> 	  $(PYTHONHOME)/lib-dynload/_bz2.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so \
> 	  $(PYTHONHOME)/lib-dynload/_lzma.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so \
> 	  $(PYTHONHOME)/lib-dynload/_json.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so
> ```

I know it may be annoying, but could you verify that all these libraries are needed for your XGBoost script? You could just remove each line one by one and rebuild to test it.
___
*[Examples/xgboost/Makefile, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Pt-C1kdHHm70-jJo:-MI3Pt-C1kdHHm70-jJp:bsamspy) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L60)):*
> ```Makefile
> 	  "sgx.trusted_files.bz2 = file:$(PYTHONHOME)/lib-dynload/_bz2.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so\\\\n" \
> 	  "sgx.trusted_files.lzma = file:$(PYTHONHOME)/lib-dynload/_lzma.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so\\\\n" \
> 	  "sgx.trusted_files.json = file:$(PYTHONHOME)/lib-dynload/_json.cpython-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG).so\\\\n"
> ```

ditto (verify that all these libraries are needed)
___
*[Examples/xgboost/Makefile, line 133 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3RFvU4z3SE_-cEQUj:-MI3RFvU4z3SE_-cEQUk:bjlolny) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L133)):*
> ```Makefile
> 	@grep -q "Success 2/3" OUTPUT_TEST
> 	@grep -q "Success 3/3" OUTPUT_TEST
> 	@rm OUTPUT_TEST
> ```

I don't think this `check` target works correctly. You don't have "Success X/3" lines in your XGBoost script.
___
*[Examples/xgboost/Makefile, line 137 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3RN6QDBESDEnICxXU:-MI3RN6QDBESDEnICxXV:b9ca9al) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L137)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) *.manifest *.manifest.sgx *.token *.sig pal_loader OUTPUT* *.PID
> ```

I don't think you need `OUTPUT*` and `*.PID` files here.
___
*[Examples/xgboost/Makefile, line 138 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3RUmBDvjcRlOYb23H:-MI3RUmBDvjcRlOYb23I:b-s0bphs) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/Makefile#L138)):*
> ```Makefile
> clean:
> 	$(RM) *.manifest *.manifest.sgx *.token *.sig pal_loader OUTPUT* *.PID
> 	$(RM) -r scripts/__pycache__
> ```

You don't have `scripts/` subdir. Remove this line.
___
*[Examples/xgboost/python.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Rbk3BUqxHAVHWOOV:-MI3Rbk3BUqxHAVHWOOW:b9rles9) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L1)):*
> ```
> # Python3 manifest example
> ```

It's actually `XGBoost` example.
___
*[Examples/xgboost/python.manifest.template, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Ro98Dku8H9tuC22P:-MI3Ro98Dku8H9tuC22Q:broienv) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L94)):*
> ```
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libnssdns = file:$(GRAPHENEDIR)/Runtime/libnss_dns.so.2
> sgx.trusted_files.libresolve = file:$(GRAPHENEDIR)/Runtime/libresolv.so.2
> ```

Feels like the last two libraries are not needed.
___
*[Examples/xgboost/python.manifest.template, line 99 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Rs47Bi-Mp87hChR0:-MI3Rs47Bi-Mp87hChR1:bw6zgrt) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L99)):*
> ```
> sgx.trusted_files.libexpat = file:$(ARCH_LIBDIR)/libexpat.so.1
> sgx.trusted_files.libnssfiles = file:$(ARCH_LIBDIR)/libnss_files.so.2
> sgx.trusted_files.libnssmdns4 = file:$(ARCH_LIBDIR)/libnss_mdns4_minimal.so.2
> ```

Feels like these three libraries are not needed.
___
*[Examples/xgboost/python.manifest.template, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3S2H9CMxDkbOS9czG:-MI3S2H9CMxDkbOS9czH:b-cm5nkq) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L102)):*
> ```
> $(PYTHON_TRUSTED_LIBS)
> 
> sgx.trusted_files.xgboost = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/site-packages/xgboost/lib/libxgboost.so
> ```

`$(CONDAPATH)/lib/$(PYTHONVERSION)` is the same as `$(PYTHONHOME)`, please use the latter.

Or even so: `$(CONDAPATH)/lib/$(PYTHONVERSION)/site-packages` is the same as `$(PYTHONDISTHOME)`, so please use the latter here.
___
*[Examples/xgboost/python.manifest.template, line 122 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3SXc30lfWH0nWrEVK:-MI3SXc30lfWH0nWrEVL:bv6xywm) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L122)):*
> ```
> sgx.trusted_files.python18 = file:$(PYTHONHOME)/sysconfig.py
> sgx.trusted_files.python19 = file:/usr/lib/$(PYTHONVERSION)/sitecustomize.py
> sgx.trusted_files.python20 = file:/usr/lib/python3/dist-packages/apport_python_hook.py
> ```

Why do you use system-wide `/usr/lib` python scripts here? Cannot you use the ones from Conda?
___
*[Examples/xgboost/python.manifest.template, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3SfHI3kh7BHJ5SnqL:-MI3SfHI3kh7BHJ5SnqM:b-qwyk7j) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L126)):*
> ```
> 
> # User scripts
> sgx.trusted_files.user01 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/lib-dynload/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so
> ```

`$(CONDAPATH)/lib/$(PYTHONVERSION)` is the same as `$(PYTHONHOME)`, please use the latter.

Here and below.
___
*[Examples/xgboost/python.manifest.template, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3SiwKAx_poOnR7j5x:-MI3SiwKAx_poOnR7j5y:bvb33te) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L126)):*
> ```
> 
> # User scripts
> sgx.trusted_files.user01 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/lib-dynload/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so
> ```

Please don't use the hard-coded `-36m-x86_64-linux-gnu`. Instead use `-$(PYTHONSHORTVERSION)m-$(PYTHON_ARCH_LONG)` (and add these env variables to sed in the Makefile).

Here and below.
___
*[Examples/xgboost/python.manifest.template, line 138 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3SzGn8AARPXEhMawa:-MI3SzGn8AARPXEhMawb:b-jrmucj) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L138)):*
> ```
> sgx.trusted_files.user11 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/lib-dynload/_bisect.cpython-36m-x86_64-linux-gnu.so
> sgx.trusted_files.user12 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/lib-dynload/_random.cpython-36m-x86_64-linux-gnu.so
> sgx.trusted_files.user13 = file:/usr/lib/x86_64-linux-gnu/libssl.so.1.1
> ```

Please don't use system-wide `/usr/lib`. Also, are you sure you need `libssl` in this example?
___
*[Examples/xgboost/python.manifest.template, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3T3cW2WMNW8oqX_8o:-MI3T3cW2WMNW8oqX_8p:b9x68hw) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L140)):*
> ```
> sgx.trusted_files.user13 = file:/usr/lib/x86_64-linux-gnu/libssl.so.1.1
> sgx.trusted_files.user14 = file:$(CONDAPATH)/lib/libffi.so.7
> sgx.trusted_files.user15 = file:/usr/lib/x86_64-linux-gnu/libffi.so.7
> ```

This is a duplicate, you already have it under Conda.
___
*[Examples/xgboost/python.manifest.template, line 143 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TBdN2VvOMohDZw5Z:-MI3TBdN2VvOMohDZw5_:b4o1ebf) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L143)):*
> ```
> sgx.trusted_files.user16 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/site-packages/scipy.libs/libopenblasp-r0-085ca80a.3.9.so
> sgx.trusted_files.user17 = file:$(CONDAPATH)/lib/libgcc_s.so.1
> sgx.trusted_files.user18 = file:$(CONDAPATH)/lib/libgcc_s.so.1
> ```

What are these two files? They are the same file. But I'm sure you can just remove these two lines.
___
*[Examples/xgboost/python.manifest.template, line 144 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3THn3-75CNXasPTXg:-MI3THn3-75CNXasPTXh:by069ew) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L144)):*
> ```
> sgx.trusted_files.user17 = file:$(CONDAPATH)/lib/libgcc_s.so.1
> sgx.trusted_files.user18 = file:$(CONDAPATH)/lib/libgcc_s.so.1
> sgx.trusted_files.user19 = file:$(CONDAPATH)/lib/libz.so.1
> ```

I'm pretty sure you can just remove this line.
___
*[Examples/xgboost/python.manifest.template, line 145 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TJo38mLjx3HwsXg7:-MI3TJo38mLjx3HwsXg8:by069ew) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L145)):*
> ```
> sgx.trusted_files.user18 = file:$(CONDAPATH)/lib/libgcc_s.so.1
> sgx.trusted_files.user19 = file:$(CONDAPATH)/lib/libz.so.1
> sgx.trusted_files.user20 = file:$(CONDAPATH)/lib/libstdc++.so.6
> ```

I'm pretty sure you can just remove this line.
___
*[Examples/xgboost/python.manifest.template, line 148 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TNrA2r36D9R0Oft0:-MI3TNrA2r36D9R0Oft1:be0noc8) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L148)):*
> ```
> 
> sgx.trusted_files.dataset05 = file:data/iris_test.csv
> sgx.trusted_files.dataset06 = file:data/iris_train.csv
> ```

Minor, but why `dataset05/06` instead of starting with `01`?
___
*[Examples/xgboost/python.manifest.template, line 155 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TWp16LHexGtI3gA1:-MI3TWp16LHexGtI3gA2:bgnj5kp) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L155)):*
> ```
> sgx.trusted_files.cpp = file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
> sgx.trusted_files.gcc = file:/lib/x86_64-linux-gnu/libgcc_s.so.1
> sgx.trusted_files.OpenMP = file:$(CONDAPATH)/lib/libgomp.so.1
> ```

Why from Conda and not from system-wide? These are normal libraries.
___
*[Examples/xgboost/python.manifest.template, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Tf4M0uZUhzQXddY5:-MI3Tf4M0uZUhzQXddY6:bgnj5kp) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L157)):*
> ```
> sgx.trusted_files.OpenMP = file:$(CONDAPATH)/lib/libgomp.so.1
> sgx.trusted_files.crypto = file:/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
> sgx.trusted_files.crypto2 = file:$(CONDAPATH)/lib/libcrypto.so.1.1
> ```

Why from Conda and not from system-wide? These are normal libraries.
___
*[Examples/xgboost/python.manifest.template, line 160 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TjLs1qP9toKs6j5f:-MI3TjLs1qP9toKs6j5g:b-y3ldc9) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L160)):*
> ```
> sgx.trusted_files.fstab = file:/etc/fstab
> 
> sgx.allowed_files.scripts = file:scripts
> ```

Please remove, you don't have `scripts/`
___
*[Examples/xgboost/python.manifest.template, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3TmabBxNg3SkCdhar:-MI3TmabBxNg3SkCdhas:btyzsb9) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L163)):*
> ```
> sgx.allowed_files.pythonpackages1 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/lib-dynload/
> sgx.allowed_files.pythonpackages2 = file:$(CONDAPATH)/lib/$(PYTHONVERSION)/site-packages/
> sgx.allowed_files.pythonhome = file:$(PYTHONHOME)
> ```

These three allowed directories are quite dangerous (`sgx.allowed_files` is insecure). Please remove them, you already have their required contents under `sgx.trusted_files`.
___
*[Examples/xgboost/python.manifest.template, line 177 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3U1MKBMuCe1CEVdv6:-MI3U1MKBMuCe1CEVdv7:b-6zcyh7) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/python.manifest.template#L177)):*
> ```
> sgx.allowed_files.gaiconf   = file:/etc/gai.conf
> sgx.allowed_files.hostconf  = file:/etc/host.conf
> sgx.allowed_files.resolv    = file:/etc/resolv.conf
> ```

I have a feeling all these NSS files are not needed. Please verify.
___
*[Examples/xgboost/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3NqB83Fqsib-YnQLZ:-MI3NqB83Fqsib-YnQL_:b-is3g4e) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/README.md#L1)):*
> ```Markdown
> # Python example
> ```

It's not a Python example. Please replace with `XGBoost`.
___
*[Examples/xgboost/README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Nvw_D77afSSypWbt:-MI3Nvw_D77afSSypWbu:b-jycmmg) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/README.md#L8)):*
> ```Markdown
> # Generating the manifest
> 
> ## Installing prerequisites
> ```

In this section, could you also add commands on how to install Conda, Pandas, NumPy, and XGBoost? This way we could easily test this PR.
___
*[Examples/xgboost/README.md, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3OCLS2EgYC8F7fMsb:-MI3OCLS2EgYC8F7fMsc:b-dsku2q) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/README.md#L13)):*
> ```Markdown
> command to install the required utility packages (Ubuntu-specific):
> 
>     sudo apt-get install libnss-mdns
> ```

Is this really necessary? `libnss` is typically for internet-facing services and for DNS. Does XGBoost really require this?
___
*[Examples/xgboost/README.md, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3ONDh6zdJ49gym9bX:-MI3ONDh6zdJ49gym9bY:b5m8gn7) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/README.md#L27)):*
> ```Markdown
> Please specify conda environment and python version:
> ```
> make PYTHONVERSION=python3.6 CONDAPATH=<path-to-conda-dir>/miniconda3/envs/my_env SGX=1
> ```

I see that you have `3.6` hard-coded in the manifest. I think you should use an environment variable in the manifest, to be able to use other versions of Python.
___
*[Examples/xgboost/README.md, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3Ogd3-ugqnTgFUkUb:-MI3Ogd47hkJwqgWvEKs:b5m1hp0) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/README.md#L32)):*
> ```Markdown
> # Run XGBoost with Graphene
> 
> Here's an example of running Python scripts under Graphene:
> ```

`Python` -> `XGBoost`
___
*[Examples/xgboost/xgboost_example_airline.py, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI3OrRE9ep3HMT-c3sD:-MI3OrRE9ep3HMT-c3sE:b-tma5oa) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/xgboost_example_airline.py#L54)):*
> ```Python
>     accuracy = np.sum(test_result == test_y.to_numpy().reshape(-1)) / test_result.shape[0]
>     print("Accuracy:", accuracy)
>     print("Example succeed!!")
> ```

Slightly broken English, please replace with `Example succeeded!`

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1835)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @masdevas)

___
*[Examples/xgboost/xgboost_example_airline.py, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI_9aJo9R8ZT2-J6Mjg:-MI_9aJo9R8ZT2-J6Mjh:bee54ho) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/xgboost_example_airline.py#L52)):*
> ```Python
> 
>     test_result = np.argmax(test_result, axis=1)
>     accuracy = np.sum(test_result == test_y.to_numpy().reshape(-1)) / test_result.shape[0]
> ```

please guarding this expression with ``` if  (test_result.shape[0] != 0)  {...```
___
*[Examples/xgboost/xgboost_example_airline.py, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI_9waqE0e61fiRjd4X:-MI_9waqE0e61fiRjd4Y:b-j8oqcs) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/xgboost_example_airline.py#L54)):*
> ```Python
>     accuracy = np.sum(test_result == test_y.to_numpy().reshape(-1)) / test_result.shape[0]
>     print("Accuracy:", accuracy)
>     print("Example succeed!!")
> ```

I prefer to put ``` print("Example succeed!!") ``` under a condition like ``` if (accuracy < ACCURACY_LIMIT)  {...```

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1835)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @masdevas)

___
*[Examples/xgboost/data/iris_test.csv, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1835#-MI_AxM38ZyLZ6iYVhw0:-MI_AxM38ZyLZ6iYVhw1:b-ded5s2) ([raw file](https://github.com/oscarlab/graphene/blob/3ff9e3c2b74951d7f12552fa68933eea8609f0a4/Examples/xgboost/data/iris_test.csv#L1)):*
> ```CSV
> 6.7,3.1,4.4,1.4,1.0
> ```

Please make sure the license of those data files, if cannot ensure,  you can use the way to download it when building it instead.

**Comment by dimakuv** [comment]
The original author didn't respond to the review, and we decided to keep the current set of examples to the minimum, so I'm closing this PR.

**Pull request closed without merging**
