### PR TITLE
Fix compilation issues for the FreeBSD port

### PR DESCRIPTION
**Pull request by chiache**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

This PR simply fixes the compilation of Graphene on FreeBSD (for the stable release). We will need more PRs for fixing the execution issues. 

## How to test this PR? 

This PR requires FreeBSD 11/12. To test, simple run `gmake` (instead of `make`) in the root of the repository.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/865)

### CODE REVIEW

**Comment by woachk** [comment]
@mkow db_exception2.c was a quick port of the Linux exceptions implementation to FreeBSD of mine, so yeah it currently has a lot of Linux references. I'm planning to split exception support later because of Darwin using Mach exception handling as a priority.

**Comment by woachk** [comment]
`  [ db_pipes.o ]
db_pipes.c:51:17: warning: address of array 'pal_sec.pipe_prefix' will always evaluate to 'true'
      [-Wpointer-bool-conversion]
    if (pal_sec.pipe_prefix)
    ~~  ~~~~~~~~^~~~~~~~~~~
fatal error: error in backend: A @@ version cannot be undefined
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /home/ares/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/db_pipes-1c9569.c
clang: note: diagnostic msg: /tmp/db_pipes-1c9569.sh
clang: note: diagnostic msg: 

********************
gmake[3]: *** [Makefile:35: db_pipes.o] Error 70
gmake[3]: Leaving directory '/usr/home/ares/graphene/Pal/src/host/FreeBSD'
gmake[2]: *** [Makefile:99: host/FreeBSD/libpal-FreeBSD.a] Error 2
gmake[2]: Leaving directory '/usr/home/ares/graphene/Pal/src'
gmake[1]: *** [Makefile:19: all] Error 2
gmake[1]: Leaving directory '/usr/home/ares/graphene/Pal'
gmake: *** [Makefile:8: all] Error 2
`

Not buildable in its current form, even after some tiny fixes for db_files.

**Comment by woachk** [comment]
Alright gcc does build it.

**Comment by woachk** [comment]
error: versioned symbol r_debug@@PAL must be defined
Alright.

**Comment by mkow** [comment]
This PR is outdated, closing (see #1246).

**Pull request closed without merging**
