### PR TITLE
[PAL+LibOS] Drop atomic wrappers

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

This series of patches drops all atomic inline wrapper functions and applies the atomic built-ins at their previous locations using the same memory order parameters.

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1601)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please (run 1/5; let's do several to be sure)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (`test_090_sighandler_reset ` LibOS test failed)

**Comment by dimakuv** [comment]
Jenkins, test this please (run 2/5; previous run failed one pipeline: Jenkins-SGX-18.04)

**Comment by dimakuv** [comment]
Jenkins, test this please (run 3/5; previous run was completely successful)

**Comment by dimakuv** [comment]
Jenkins, test this please (run 4/5; previous run was completely successful)

**Comment by mkow** [comment]
Jenkins, test this please (run 5/5; previous run was completely successful)

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (very weird failures on LTP, 8 tests failed with outputs like `nanosleep() slept for too long`, can't reproduce locally)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (success, but let's run it a few times more to be sure)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (success, but let's run it a few times more to be sure)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (success, but let's run it a few times more to be sure)

**Pull request merged**
