### PR TITLE
[LibOS] Have all syscall functions return long

### PR DESCRIPTION
**Pull request by stefanberger**
This patch is a split off from @boryspoplawski signal rework patch #2071 and supposed to clear out the weeds. I don't mind NOT being the git-author of this patch, so please change it.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)

### CODE REVIEW

**Comment by stefanberger** [comment]
@boryspoplawski This would help me quite a bit I think.

**Comment by stefanberger** [comment]
This patch only changes the return types to longs, no name changes to function related to rt-signal.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQo0qTM-DTFWVw_qvuH:-MQo0qTM-DTFWVw_qvuI:bne5gau) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/src/sys/shim_sigaction.c#L156)):*
> ```C
>     return 0;
> }
> ```

Accidentally deleted newline?

**Comment by mkow** [comment]
Jenkins, test this please

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQo0qTM-DTFWVw_qvuH:-MQo2Gyh3JaPVvuGRsvU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/src/sys/shim_sigaction.c#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Accidentally deleted newline?
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, test this please

**Review by yamahata — DISMISSED** [review]
> Reviewed 29 of 30 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 29 of 30 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/include/shim_table.h, line 368 at r2](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQpZXc24KzjuxneSGae:-MQpZXc34Q2Gp1rI44zS:b3ct7qg) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/include/shim_table.h#L368)):*
> ```objc
> int shim_do_poll(struct pollfd* fds, nfds_t nfds, int timeout);
> off_t shim_do_lseek(int fd, off_t offset, int origin);
> void* shim_do_mmap(void* addr, size_t length, int prot, int flags, int fd, off_t offset);
> ```

Why do we have `shim_do_mmap`, `shim_do_brk` and `shim_do_mremap` returning `void*` and not long? I don't mind this but what is the rationale for this?
___
*[LibOS/shim/src/sys/shim_open.c, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQp_bZnBSG88jef3Nj4:-MQp_bZo2lGeeW2g12ux:b-htms3n) ([raw file](https://github.com/oscarlab/graphene/blob/2d7259f95da658580b321adf78b731bd11370ab2/LibOS/shim/src/sys/shim_open.c#L24)):*
> ```C
> #include "stat.h"
> 
> int do_handle_read(struct shim_handle* hdl, void* buf, int count) {
> ```

We have all these internal functions with `int` types (`int count`, yikes!), but this is for another PR...

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_table.h, line 368 at r2](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQpZXc24KzjuxneSGae:-MQrALOi2FNk1viPLtmS:b-ajtkc) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/include/shim_table.h#L368)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have `shim_do_mmap`, `shim_do_brk` and `shim_do_mremap` returning `void*` and not long? I don't mind this but what is the rationale for this?
</blockquote></details>

I guess because of the different retval semantic (there's no "negative means failure") there, but on Linux they are also `long`.
___
*[LibOS/shim/src/sys/shim_open.c, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQp_bZnBSG88jef3Nj4:-MQrAahJBojULFFqT5u9:b-z94vva) ([raw file](https://github.com/oscarlab/graphene/blob/2d7259f95da658580b321adf78b731bd11370ab2/LibOS/shim/src/sys/shim_open.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have all these internal functions with `int` types (`int count`, yikes!), but this is for another PR...
</blockquote></details>

+1 to fixing this, but separately.

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQrAnpS07_QOy1Odxn0:-MQrAnpS07_QOy1Odxn1:b-9xi6b6) (no related file):*
@stefanberger One small request: Could you prefix your PR branches with `stefanberger/` in the future? This makes it easier for us to pull them without trashing our local "branch namespace" ;) Now I have to use `--track` and also more complicated syntax for `push` if I want to have it prefixed locally.

---

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (internet connection lost)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (internet connection lost, common Jenkins you can do it)

**Comment by stefanberger** [comment]
> @stefanberger One small request: Could you prefix your PR branches with `stefanberger/` in the future? This makes it easier for us to pull them without trashing our local "branch namespace" ;) Now I have to use `--track` and also more complicated syntax for `push` if I want to have it prefixed locally.

@mkow Yes, I will do. I typically do that anyway.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2074#-MQrAnpS07_QOy1Odxn0:-MQrFpP-4eUky8fv1ncb:bda1q79) (no related file):*
> @mkow Yes, I will do. I typically do that anyway.

Thanks!

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 29 of 30 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2074)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
