### PR TITLE
[GLIBC] Patches for 2.23 and 2.27

### PR DESCRIPTION
**Pull request by chiache**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

This PR upstreams the GLIBC patches for 2.23 and 2.27. Users can select the GLIBC version with `make GLIBC_VERSION=xxx`. The PR works with both Ubuntu 16.04 and 18.04.

## How to test this PR? 

Default glibc version is updated to 2.27. Just run the regression tests as usual.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/809)

### CODE REVIEW

**Comment by chiache** [comment]
Rerun test please.

**Comment by chiache** [comment]
Run test please.

**Comment by chiache** [comment]
Test this please.

**Comment by chiache** [comment]
Requires #885, too.

**Comment by chiache** [comment]
Jenkins, test this please.

**Comment by dimakuv** [comment]
@chiache , Jenkins failed with:
```
+ cd Pal/ipc/linux
+ make
make -C /lib/modules/4.4.0-157-generic/build M=/home/jenkins/workspace/graphene/Pal/ipc/linux modules
make[1]: *** /lib/modules/4.4.0-157-generic/build: No such file or directory.  Stop.
Makefile:13: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by dimakuv** [comment]
@chiache Jenkins build failed with:
```
+ cd Pal/ipc/linux
+ make
make -C /lib/modules/4.4.0-157-generic/build M=/home/jenkins/workspace/graphene/Pal/ipc/linux modules
make[1]: *** /lib/modules/4.4.0-157-generic/build: No such file or directory.  Stop.
Makefile:13: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by donporter** [comment]
This is an unrelated failure.  #927 is an attempt to fix this.

**Comment by dimakuv** [comment]
> This is an unrelated failure. #927 is an attempt to fix this.

Thanks, Don. I was also investigating along these lines. Will restarting this job help? (In the hope that it will be scheduled on another Jenkins machine with correct Linux headers.)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (out-of-sync Linux headers required for IPC module build; see above)

**Comment by donporter** [comment]
It may, unless there was some upgrade that caused every worker to get out of date.  In which case, rebooting can be a hack

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (same error; was scheduled on the same unfortunate machine `slave-waldorf`)

**Pull request merged**
