### PR TITLE
Runtime/Makefile: all goal should be default

### PR DESCRIPTION
**Pull request by yamahata**
Since clean rule is first target, just "make" means "make clean" as default goal.
This is a surprise. usually "make" means "make all".
So move all rule to the first target.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/366)

### CODE REVIEW

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
