### PR TITLE
Replace realpath with Python code

### PR DESCRIPTION
**Pull request by adombeck**
I replaced the use of `realpath` in `LibOS/shim/test/Makefile` with some equivalent Python code, because `realpath` is not installed by default in Ubuntu 14.04 *and* the package that is available in 14.04 does not support the used `--relative-to` option.

I also fixed the `ls.manifest.template` and minor stuff in the readme.

### CODE REVIEW

**Comment by chiache** [comment]
Thanks for the patch!

**Comment by adombeck** [comment]
You're welcome :)

**Comment by adombeck** [comment]
Your usage of realpath suggests you are running Graphene on a system different from Ubuntu 14.04. Could you tell me what system you use? I would love to use something newer without breaking SGX (which is currently only supported on Ubuntu 14.04).

**Comment by chiache** [comment]
I am currently developing on 16.04. However, the Graphene library OS is
supposed to be backward-compatible to older Ubuntu versions. We certainly
appreciate any bug reports on other Ubuntu.

Tsai, Chia-che (Jerry) <chiache.tsai@gmail.com>

**Comment by adombeck** [comment]
Do the SGX SDK and driver work out of the box on 16.04? That would be great!

**Comment by chiache** [comment]
It does: https://github.com/01org/linux-sgx/issues/11

Tsai, Chia-che (Jerry) <chiache.tsai@gmail.com>

**Comment by adombeck** [comment]
Great, thanks!

**Pull request merged**
