### PR TITLE
[Pal/Linux-SGX] Cleanups for pal-sgx-get-token

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Cleanups

## How to test this PR? 
Before the patches applied:
```
# cat cat .output.sgx_get_token.helloworld 
Attributes:
    mrenclave: 88e5c9a136b219dbec49c3b260adfb9a2b160476c05ccb726a80b956ac44fd9a
    isvprodid: 0
    isvsvn:    0
    flags:     0600000000000000
    xfrms:     0300000000000000
    miscs:     00000000
    miscmask:  00000000
    modulus:   190e2d49ccda2097efa00061aa028d1e...
    exponent:  3
    signature: 98424dd3393c31b6f1bc36a39d88572a...
```

After the patches applied:
```
Attributes:
    mrenclave: 88e5c9a136b219dbec49c3b260adfb9a2b160476c05ccb726a80b956ac44fd9a
    isvprodid: 0
    isvsvn:    0
    flags:     0600000000000000
    xfrms:     0300000000000000
    miscs:     00000000
    miscmask:  00000000
    modulus:   190e2d49ccda2097efa00061aa028d1e...
    exponent:  3
    signature: 98424dd3393c31b6f1bc36a39d88572a...
    date:      2019.9.25
```

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1020)

### CODE REVIEW

**Comment by jiazhang0** [comment]
@yamahata Updated. The support of showing signing date in pal-sgx-sign is addressed by https://github.com/oscarlab/graphene/pull/1021.

**Comment by jiazhang0** [comment]
@mkow Fixed. Will fix the date format for pal-sgx-sign.

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Pull request merged**
