### PR TITLE
[LibOS] Fix clean failure

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1173)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX please (`openmp` LibOS test failed)

**Comment by jiazhang0** [comment]
Squashed and updated.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
