### PR TITLE
[Docs] Describe using perf and other profiling tools

### PR DESCRIPTION
**Pull request by pwmarcz**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Documentation/devel/performance.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLDFMr5EicZhBNgsFDx:-MLDFMr6A5YuCGOkyAF_:b3gw495) ([raw file](https://github.com/oscarlab/graphene/blob/4c7c8bd8412b872be92ac34003c05a7f81ddb1f9/Documentation/devel/performance.rst#L22)):*
> ```reStructuredText
> ----------------------------------------------
> 
> See also :ref:`perf` below for installing ``perf``.
> ```

Somehow this ref was not recognized by Sphinx:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/devel/performance.rst::Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
Makefile:22: recipe for target 'html' failed
```

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/performance.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLDFMr5EicZhBNgsFDx:-MLDSnWrB8zO-7Wd1jMm:b-e51fjq) ([raw file](https://github.com/oscarlab/graphene/blob/4c7c8bd8412b872be92ac34003c05a7f81ddb1f9/Documentation/devel/performance.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Somehow this ref was not recognized by Sphinx:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/devel/performance.rst::Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
Makefile:22: recipe for target 'html' failed
```
</blockquote></details>

I thought so too, but it turned out to actually be a broken link below ("Callgrind").

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/performance.rst, line 509 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLE8CDZA-ejQDNWqlFt:-MLE8CD_3gqkP-e76AXg:b9w6die) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L509)):*
> ```reStructuredText
> * Intel VTune Profiler (TODO)
> * ``strace -c`` will display Linux system call statistics
> * Valgrind (with `Callgrind <https://valgrind.org/docs/manual/cl-manual.html>`__)
> ```

Ah, lol :)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/devel/performance.rst, line 433 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEJjuU6_wZjHHoXz5U:-MLEJjuV3m8Lh1lyRUMr:b89traj) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L433)):*
> ```reStructuredText
> 2. Run ``perf``. It will complain about not having a kernel-specific package,
>    such as ``linux-tools-4-15.0-122-generic``.
> 3. Install the kernel-specific package.
> ```

Please use `#.` for numbered lists (ditto below)
___
*[Documentation/devel/performance.rst, line 468 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELckb2_q00ZNagCu4:-MLELckb2_q00ZNagCu5:b-uhftt2) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L468)):*
> ```
> 5. Copy the built ``perf`` binary somewhere to your ``PATH``, for instance,
>    ``/usr/local/bin``.
> ```

Hmm, no `make install` available? Manually copying looks hacky and may be missing some additional files.
___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLELr0u-IBRhxbHZM-4:b-qtz7kf) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
> ```
> Unfortunately, in SGX mode, it will not account
> correctly for the code inside the enclave.
> ```

Do you know why maybe?
___
*[Documentation/devel/performance.rst, line 496 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEKe3M9XXz9AkyP2vu:-MLEKe3M9XXz9AkyP2vv:b-4szr8o) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L496)):*
> ```reStructuredText
>   function).
> 
> Futher reading
> ```

`Futher` -> `Further`
___
*[Documentation/devel/performance.rst, line 514 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEL2XZEVll8uCtbPbj:-MLEL2XZEVll8uCtbPbk:b-vn28en) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L514)):*
> ```reStructuredText
>   * `pie elf loaded at 0x108000
>     <https://bugs.kde.org/show_bug.cgi?id=290061>`__ - prevents loading non-PIE
>     binaries properly
> ```

This is actually a problem with Graphene, Valigrind is perfectly allowed to do this (if I understood the problem correctly). Please link to #1919 here.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Documentation/devel/performance.rst, line 468 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELckb2_q00ZNagCu4:-MLEOkU634Ay5QJF-5-a:b-vsr1qf) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L468)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> 5. Copy the built ``perf`` binary somewhere to your ``PATH``, for instance,
>    ``/usr/local/bin``.
> ```

Hmm, no `make install` available? Manually copying looks hacky and may be missing some additional files.
</blockquote></details>

Good point. I will recommend something like `sudo make install DESTDIR=/usr/local`.
___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLENx6m4n-VFTVviINL:b-niemox) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Unfortunately, in SGX mode, it will not account
> correctly for the code inside the enclave.
> ```

Do you know why maybe?
</blockquote></details>

Not sure. Here is an example report:
```
    60.63%  pal-Linux-SGX  [intel_sgx]             [k] sgx_ioc_enclave_add_pages
     9.58%  pal-Linux-SGX  [intel_sgx]             [k] sgx_free_epc_page
     5.06%  pal-Linux-SGX  [kernel.kallsyms]       [k] _raw_spin_lock
     1.61%  pal-Linux-SGX  [kernel.kallsyms]       [k] __handle_mm_fault
     1.24%  pal-Linux-SGX  [kernel.kallsyms]       [k] mem_cgroup_throttle_swaprate
     1.17%  pal-Linux-SGX  [kernel.kallsyms]       [k] get_page_from_freelist
```
___
*[Documentation/devel/performance.rst, line 514 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEL2XZEVll8uCtbPbj:-MLEO0X08ievkmUrC_Vg:b-3k97w4) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L514)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is actually a problem with Graphene, Valigrind is perfectly allowed to do this (if I understood the problem correctly). Please link to #1919 here.
</blockquote></details>

That's not the whole story. Even if we solve the problem with Graphene (by correctly detecting the free memory area), we still will not be able to load a non-PIE binary at e.g. `0x40000` because it will overlap libpal.so.

I will add a link here and try to make the situation more clear.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLEVy967EEUwqPlQJ1V:b-e88r5q) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Not sure. Here is an example report:
```
    60.63%  pal-Linux-SGX  [intel_sgx]             [k] sgx_ioc_enclave_add_pages
     9.58%  pal-Linux-SGX  [intel_sgx]             [k] sgx_free_epc_page
     5.06%  pal-Linux-SGX  [kernel.kallsyms]       [k] _raw_spin_lock
     1.61%  pal-Linux-SGX  [kernel.kallsyms]       [k] __handle_mm_fault
     1.24%  pal-Linux-SGX  [kernel.kallsyms]       [k] mem_cgroup_throttle_swaprate
     1.17%  pal-Linux-SGX  [kernel.kallsyms]       [k] get_page_from_freelist
```
</blockquote></details>

What was the workload there? This looks likely, loading enclaves is really slow and may easily dominate running time.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/devel/performance.rst, line 433 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEJjuU6_wZjHHoXz5U:-MLI9di76TiOQJyJEpPc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use `#.` for numbered lists (ditto below)
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 468 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELckb2_q00ZNagCu4:-MLI9gVf0X6xFDDwuWXc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L468)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good point. I will recommend something like `sudo make install DESTDIR=/usr/local`.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLIAfyL6f1in0E39sZF:b-m2tho4) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What was the workload there? This looks likely, loading enclaves is really slow and may easily dominate running time.
</blockquote></details>

The workload is `python -c 'for i in range(10**9): pass'`, and the loop takes most of the time (about 40 seconds). The 60% doesn't depend on length on the loop so I think time spent inside enclave is simply not accounted for.

Recording with `perf record -e cpu-clock` [1] shows something that looks more accurate, but not at all helpful:

```
+   94.95%  pal-Linux-SGX  pal-sgx            [.] async_exit_pointer
+    2.70%  pal-Linux-SGX  [intel_sgx]        [k] sgx_ioc_enclave_add_pages
+    0.65%  pal-Linux-SGX  [intel_sgx]        [k] sgx_free_epc_page
     0.20%  pal-Linux-SGX  [kernel.kallsyms]  [k] _raw_spin_lock
     0.15%  pal-Linux-SGX  [kernel.kallsyms]  [k] __handle_mm_fault
     0.15%  pal-Linux-SGX  [kernel.kallsyms]  [k] down_read
     0.10%  pal-Linux-SGX  [kernel.kallsyms]  [k] __lock_text_start
     0.10%  pal-Linux-SGX  [kernel.kallsyms]  [k] handle_mm_fault
```

95% sounds about right for time spent in the Python loop (as opposed to startup) Unfortunately the call graph for `async_exit_pointer` doesn't show anything outside or inside, and the annotated code is:

```
       |   async_exit_pointer:
       |   # increment per-thread AEX counter for stats
       |   lock incq %gs:PAL_TCB_URTS_AEX_CNT
100.00 |     lock incq %gs:0x30
```

It looks like `perf` looks at the IP/stack after exiting the enclave during an interrupt, and possibly doesn't support sampling the state inside enclave. I found [some discussion here](https://community.intel.com/t5/Intel-Software-Guard-Extensions/Profiling-enclaves-in-debug-mode/td-p/1114215) but it's unclear to me if it means `perf` can be made to work with SGX. I would guess some kernel support is needed for that.

I mentioned the ``-e cpu-clock`` option here, but of course it's not particularly useful.

[1] The default is `cpu-cycles`. The difference is that `cpu-cycles` is a hardware event and `cpu-clock` is a software event, and I guess the first one is not triggered when inside enclave.
___
*[Documentation/devel/performance.rst, line 496 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEKe3M9XXz9AkyP2vu:-MLIEpBiBj7o48-IWzux:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L496)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Futher` -> `Further`
</blockquote></details>

Fixed.
___
*[Documentation/devel/performance.rst, line 514 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEL2XZEVll8uCtbPbj:-MLIHP6g1okwXZOtHF5l:b-82bcb7) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L514)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's not the whole story. Even if we solve the problem with Graphene (by correctly detecting the free memory area), we still will not be able to load a non-PIE binary at e.g. `0x40000` because it will overlap libpal.so.

I will add a link here and try to make the situation more clear.
</blockquote></details>

I replaced the summary here with a link to Github issue.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLIRpISDVvFRJfT4heP:bykd922) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The workload is `python -c 'for i in range(10**9): pass'`, and the loop takes most of the time (about 40 seconds). The 60% doesn't depend on length on the loop so I think time spent inside enclave is simply not accounted for.

Recording with `perf record -e cpu-clock` [1] shows something that looks more accurate, but not at all helpful:

```
+   94.95%  pal-Linux-SGX  pal-sgx            [.] async_exit_pointer
+    2.70%  pal-Linux-SGX  [intel_sgx]        [k] sgx_ioc_enclave_add_pages
+    0.65%  pal-Linux-SGX  [intel_sgx]        [k] sgx_free_epc_page
     0.20%  pal-Linux-SGX  [kernel.kallsyms]  [k] _raw_spin_lock
     0.15%  pal-Linux-SGX  [kernel.kallsyms]  [k] __handle_mm_fault
     0.15%  pal-Linux-SGX  [kernel.kallsyms]  [k] down_read
     0.10%  pal-Linux-SGX  [kernel.kallsyms]  [k] __lock_text_start
     0.10%  pal-Linux-SGX  [kernel.kallsyms]  [k] handle_mm_fault
```

95% sounds about right for time spent in the Python loop (as opposed to startup) Unfortunately the call graph for `async_exit_pointer` doesn't show anything outside or inside, and the annotated code is:

```
       |   async_exit_pointer:
       |   # increment per-thread AEX counter for stats
       |   lock incq %gs:PAL_TCB_URTS_AEX_CNT
100.00 |     lock incq %gs:0x30
```

It looks like `perf` looks at the IP/stack after exiting the enclave during an interrupt, and possibly doesn't support sampling the state inside enclave. I found [some discussion here](https://community.intel.com/t5/Intel-Software-Guard-Extensions/Profiling-enclaves-in-debug-mode/td-p/1114215) but it's unclear to me if it means `perf` can be made to work with SGX. I would guess some kernel support is needed for that.

I mentioned the ``-e cpu-clock`` option here, but of course it's not particularly useful.

[1] The default is `cpu-cycles`. The difference is that `cpu-cycles` is a hardware event and `cpu-clock` is a software event, and I guess the first one is not triggered when inside enclave.
</blockquote></details>

@pwmarcz I already added this logic of enabling TCS.DBGOPTIN in Graphene, see https://github.com/oscarlab/graphene/blob/eb0e72662516b05c19adaf3c032b723cf2a5ea14/Pal/src/host/Linux-SGX/sgx_main.c#L578-L606. But this logic only works if manifest contains `sgx.enable_stats = 1`.

Please add this to your Python manifest and try perf again. I'm very curious to see how it works (I never tested the function call stacks, I only tested aggregated performance counters).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLJ7p-h1iepjT3hv03a:b-dy8nm1) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz I already added this logic of enabling TCS.DBGOPTIN in Graphene, see https://github.com/oscarlab/graphene/blob/eb0e72662516b05c19adaf3c032b723cf2a5ea14/Pal/src/host/Linux-SGX/sgx_main.c#L578-L606. But this logic only works if manifest contains `sgx.enable_stats = 1`.

Please add this to your Python manifest and try perf again. I'm very curious to see how it works (I never tested the function call stacks, I only tested aggregated performance counters).
</blockquote></details>

No change, unfortunately. I see the stats printed by Graphene, but `perf report` still shows 95% in `async_exit_pointer` and no stack.

GDB integration needed a helper function (`ptrace` wrapper) to peek inside the enclave. I guess that means the kernel doesn't do that by itself. Maybe something similar to GDB integration would help here, but I'm not sure how much work is done inside the kernel, and I suspect it's more than in the case of GDB.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLJO8_E-Xe4Xzd7Mz9l:br4boui) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No change, unfortunately. I see the stats printed by Graphene, but `perf report` still shows 95% in `async_exit_pointer` and no stack.

GDB integration needed a helper function (`ptrace` wrapper) to peek inside the enclave. I guess that means the kernel doesn't do that by itself. Maybe something similar to GDB integration would help here, but I'm not sure how much work is done inside the kernel, and I suspect it's more than in the case of GDB.
</blockquote></details>

Yeah, I think it needs a similar plugin to our GDB one.
___
*[Documentation/devel/performance.rst, line 514 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLEL2XZEVll8uCtbPbj:-MLJONND-107VM52MKb2:br06oxv) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L514)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I replaced the summary here with a link to Github issue.
</blockquote></details>

Looks good, thanks.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`sigsuspend01` LTP test failed)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLMR3ccCT_CYq4guNJq:b-cofb9h) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I think it needs a similar plugin to our GDB one.
</blockquote></details>

Yes, a wrapper around `ptrace` or smth similar (to poke inside the enclave via `EDBGWR` and `EDBGWR` instructions) would make sense. Ok.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLNoj3V0_m-WqjKXyh6:b5hkg69) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, a wrapper around `ptrace` or smth similar (to poke inside the enclave via `EDBGWR` and `EDBGWR` instructions) would make sense. Ok.
</blockquote></details>

Unfortunately as far as I can see `perf` doesn't do `ptrace` or raw memory access, but receives structured events via FD received from `perf_event_open`, so the kernel would need to be patched instead. I might be wrong though, there is a lot of things happening in `perf`.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Documentation/devel/performance.rst, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/1934#-MLELr0u-IBRhxbHZM-3:-MLYLvgT4shstifEf3AE:b-5qwwmi) ([raw file](https://github.com/oscarlab/graphene/blob/116a86b59f7912c121f55ecf4d80364223bb15bb/Documentation/devel/performance.rst#L482)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unfortunately as far as I can see `perf` doesn't do `ptrace` or raw memory access, but receives structured events via FD received from `perf_event_open`, so the kernel would need to be patched instead. I might be wrong though, there is a lot of things happening in `perf`.
</blockquote></details>

This is good and bad. May be good because this may mean that it will start to work with the SGX in-tree patchset, which probably patches all such places in the kernel. @pwmarcz: I have access to a machine with SGX+in-tree patchset applied, I can give you access if you want to try.

**Comment by mkow** [comment]
Jenkins, retest Jenkins please (`sigsuspend01` from LTP failed, known issue)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
