### PR TITLE
[LibOS] Rename vdso.c to vdso-x86_64.c

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

The  VDSO is different per architecture either by the functions exported or by their name, so put the x86_64-specific vdso into an architecture-specific file.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTfDp3TCFTMGZ85X9G5:-MTfDp3TCFTMGZ85X9G6:b-cxygkw) (no related file):*
@stefanberger Jenkins failed with:
```
make[3]: Entering directory '/home/jenkins/workspace/graphene/LibOS/shim/src'
  [ shim_arch_prctl-x86_64.o ]
<snip>
  [ utils/strobjs.o ]
make[3]: *** No rule to make target 'vdso/vdso.o', needed by 'vdso/vdso.so.dbg'.  Stop.
```

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTfDp3TCFTMGZ85X9G5:-MTfJzn42f0gFx9GO8GO:b-yvz302) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger Jenkins failed with:
```
make[3]: Entering directory '/home/jenkins/workspace/graphene/LibOS/shim/src'
  [ shim_arch_prctl-x86_64.o ]
<snip>
  [ utils/strobjs.o ]
make[3]: *** No rule to make target 'vdso/vdso.o', needed by 'vdso/vdso.so.dbg'.  Stop.
```
</blockquote></details>

It built before for me. I made some more changes.

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTfDp3TCFTMGZ85X9G5:-MTfKeYcD6C_CCBIODVW:b-896fix) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

It built before for me. I made some more changes.
</blockquote></details>

Done.

---

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by stefanberger — COMMENTED** [review]
I pushed again fixing my Signed-off-by: to match my author line. I guess the github DCO is also looking for Signed-off-by: lines in the fixups.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162#-:-MTfokkRCO7SPeBEaybQ:bm0sp7k)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

**Review by stefanberger — COMMENTED** [review]
I did not add this to my fixup commit, though, just the 1st one.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162#-:-MTfourSBCgwGC-PqQQN:b-rnnxjt)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
Yeah, that's enough, it just needs to be present in all commits after final squash+rebase.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162#-:-MTg5Zj414i94J2bwLys:bxtbjt2)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTg5jFNBuIddc5uZxxa:-MTg5jFOA-hYbaicEeMx:b-qk66ub) (no related file):*
Could you move the files to arch-specific directory instead of appending arch suffixes?
We should move to that convention in the whole repo soon (when it won't conflict with other changes).

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTg5jFNBuIddc5uZxxa:-MTgAbXV0pThrEePHr4M:biw4fxc) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you move the files to arch-specific directory instead of appending arch suffixes?
We should move to that convention in the whole repo soon (when it won't conflict with other changes).
</blockquote></details>

Moved them to the already-existing arch-specific directory now.

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2162#-MTg5jFNBuIddc5uZxxa:-MTgAjb9BBRH--FW7rKD:b-896fix) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Moved them to the already-existing arch-specific directory now.
</blockquote></details>

Done.

---

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by yamahata — DISMISSED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (`apps.LTP.waitpid05` failed, this is something which started to appear recently, unrelated to this PR)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2162)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
