### PR TITLE
[meson] Detect corner case of Python's platlib path

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

See docstring in the committed script.

## How to test this PR? 

1. Install graphene using default `--prefix` of `/usr/local` (i.e., don't specify `--prefix` at all) on different distros. `graphene-manifest` should work without munging neither `$PATH` nor `$PYTHONPATH`.
2. Install graphene using `--prefix=/usr`. Also should work.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[Scripts/get-python-platlib.py, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1mTFq71DL9p-pgowM:-M_1mTFq71DL9p-pgowN:b-nt43pr) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L23)):*
> ```Python
> 
> - ``sysconfig`` - Debian doesn't touch this, so it returns wrong values
> - ``import('python')`` or ``import('python3')`` in meson - uses ``sysconfig``
> ```

`meson` -> `Meson`, ditto for the whole PR
___
*[Scripts/get-python-platlib.py, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1o70Y-gTL4inVG3cx:-M_1o70Y-gTL4inVG3cy:b-168nqc) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L66)):*
> ```Python
>     is_debian = 'deb_system' in distutils.command.install.INSTALL_SCHEMES
> 
>     # this takes care of / at the end, thought not /usr/../usr/local
> ```

I'd wrap `/` in backticks, looks like a part of the sentence now.
___
*[Scripts/get-python-platlib.py, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oEIs-NB_GEt6QfWh:-M_1oEIs-NB_GEt6QfWi:bw1ij5i) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L66)):*
> ```Python
>     is_debian = 'deb_system' in distutils.command.install.INSTALL_SCHEMES
> 
>     # this takes care of / at the end, thought not /usr/../usr/local
> ```

`thought` -> `though`
___
*[Scripts/get-python-platlib.py, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oRFs7BGN8XR5dcpN:-M_1oRFs7BGN8XR5dcpO:bqsa2wc) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L73)):*
> ```
> sys.version[:3]
> ```

I know that in practice it doesn't matter, but please use the proper splitting with `.split()`.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[Scripts/get-python-platlib.py, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1mTFq71DL9p-pgowM:-M_1wECg7gG_MCgsX0GH:bsext6) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson`, ditto for the whole PR
</blockquote></details>

Done. This was the only such case.
___
*[Scripts/get-python-platlib.py, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1o70Y-gTL4inVG3cx:-M_1wHy_8PPYVk5di2WH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd wrap `/` in backticks, looks like a part of the sentence now.
</blockquote></details>

Done.
___
*[Scripts/get-python-platlib.py, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oEIs-NB_GEt6QfWh:-M_1wIMw1N1Plj9rEV35:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`thought` -> `though`
</blockquote></details>

Done.
___
*[Scripts/get-python-platlib.py, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oRFs7BGN8XR5dcpN:-M_1wJLeBsV38MfUVygD:b-aoajgy) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> sys.version[:3]
> ```

I know that in practice it doesn't matter, but please use the proper splitting with `.split()`.
</blockquote></details>

It will matter in 3.10, which is already released. Thanks for the catch.

**Comment by woju** [comment]
___
*[Scripts/get-python-platlib.py, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oRFs7BGN8XR5dcpN:-M_1y2qG8iinJ8eVDwbQ:b-nwkqa7) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It will matter in 3.10, which is already released. Thanks for the catch.
</blockquote></details>

I mean, it's in beta. Distros have already started packaging.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Scripts/get-python-platlib.py, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2353#-M_1oRFs7BGN8XR5dcpN:-M_25wk52fHVzzixF0q0:b2eqcz7) ([raw file](https://github.com/oscarlab/graphene/blob/4f2191bebaf4921d66face334964bd44fa4c6e6a/Scripts/get-python-platlib.py#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I mean, it's in beta. Distros have already started packaging.
</blockquote></details>

Ah, right :)

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2353)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
