### PR TITLE
[meson] Compile Pal/Skeleton

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This is another PR in the meson series. I want to merge this before SGX (#2411), because then it will be easier to untangle some Makefile mess around `/Pal/**Linux-SGX/tools/common` vs `/common` vs `LibOS/shim/test/*`.

## How to test this PR? 

```sh
make -C Pal/src PAL_HOST=Skeleton
meson build -Dskeleton=enabled
```
Tests won't run, because everything fails by desing, though `libpal.so` is installed (you can link against it, and if skeleton is enabled, LibOS is linked against it, because should compiles fastest).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Pal/src/host/Linux/meson.build, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOBDM4ubzKH6nSUNk:-MbDOBDM4ubzKH6nSUNl:be2ybfv) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Linux/meson.build#L32)):*
> ```Meson
>     meson.current_source_dir(), 'arch', host_machine.cpu_family(), 'pal.lds')
> 
> pal_direct_map = custom_target('pal.map[direct]',
> ```

What is this change? Is it some Meson feature? I don't understand how to interpret this.

**Review by dimakuv — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOiqm56g0OqHG8ALe:-MbDOiqm56g0OqHG8ALf:b16w2oz) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/.ci/lib/stage-build-nosgx.jenkinsfile#L4)):*
> ```
>     sh '''
>         make ${MAKEOPTS}
>         make ${MAKEOPTS} -C Pal/src PAL_HOST=Skeleton
> ```

Shouldn't you remove this?
___
*[Pal/src/host/Skeleton/meson.build, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOvoL0fI1TjsQ9KMW:-MbDOvoL0fI1TjsQ9KMX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L4)):*
> ```Meson
>     meson.current_source_dir(), 'arch', host_machine.cpu_family(), 'pal.lds')
> 
> pal_skeleton_map = custom_target('pal.map[skeleton]',
> ```

ditto

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOiqm56g0OqHG8ALe:-MbDX-jF7U5mE_jHpJpk:b-s3w64e) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/.ci/lib/stage-build-nosgx.jenkinsfile#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you remove this?
</blockquote></details>

Nope, again, `graphene-lib`. But it's the last time, I promise. :)
___
*[Pal/src/host/Linux/meson.build, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOBDM4ubzKH6nSUNk:-MbDX8JS1M41LyyvERNw:bs5w3fk) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Linux/meson.build#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this change? Is it some Meson feature? I don't understand how to interpret this.
</blockquote></details>

Because meson in Ubuntu 18.04 can't have two targets with the same name, even in different directories. This limitation was fixed in 0.46 (https://mesonbuild.com/Release-notes-for-0-46-0.html#relaxing-of-target-name-requirements), one release after bionic's 0.45.

What this target name means is complicated. In custom_target it means nothing, so we can change to whatever we like (`/` is prohibited). But in `shared_library` and `static_library` it's used to infer the filename, and in the case of libraries the limitation really prohibits same filenames, accounting for `lib` prefix and `.so`/`.a suffix, which is why `foreach target_type : ['shared_library', 'static_library']` still works. I only had to change `pal` to `pal-skeleton`, and I'll have to do something similar when porting SGX.

Other option would be to require meson 0.46, which would mean users on bionic will have to install meson from pip.
___
*[Pal/src/host/Skeleton/meson.build, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDOvoL0fI1TjsQ9KMW:-MbDZ2TwDBDc1-mQklkh:bkedcw0) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Yes, it's the same thing, just to have a different name.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Skeleton/meson.build, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbD_NBbDUNtaRFzx9cG:-MbD_NBbDUNtaRFzx9cH:bl4g3o7) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L45)):*
> ```Meson
> 
>             # in Skeleton, every single parameter is unused
>             '-Wno-unused-parameter',
> ```

@dimakuv I went for warning suppression (because this was the low-effort solution, you know, velocity, jira, etc.), but if you'd like `UNUSED()` everywhere, I could do it.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Pal/src/host/Skeleton/meson.build, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbD_NBbDUNtaRFzx9cG:-MbDaH4E7tZ84qBEepAM:b-1w13tz) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L45)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@dimakuv I went for warning suppression (because this was the low-effort solution, you know, velocity, jira, etc.), but if you'd like `UNUSED()` everywhere, I could do it.
</blockquote></details>

I think we can leave `-Wno-unused-parameter`, I thought that we use `UNUSED()` in Skeleton, but seems we just passed this option to make it simpler.
___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDa6B2EzZYeSgUDNey:brr1gwr) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
> ```Meson
>         ],
> 
>         install: true,
> ```

Why installing this? It's a "fake" PAL, meant as a copy-paste template for developing new PALs. The building is just to ensure that it compiles correctly.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Skeleton/meson.build, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbD_NBbDUNtaRFzx9cG:-MbDb1eJ7agXhLbpsAsn:b-vzr84j) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we can leave `-Wno-unused-parameter`, I thought that we use `UNUSED()` in Skeleton, but seems we just passed this option to make it simpler.
</blockquote></details>

No, we didn't pass this option, and I think we didn't have enough `-W` options for this to trigger. Jenkins certainly did compile `PAL_HOST=Skeleton` without `WERROR=`.
___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDaj775z6XcSHJ_RGN:bwdyttr) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why installing this? It's a "fake" PAL, meant as a copy-paste template for developing new PALs. The building is just to ensure that it compiles correctly.
</blockquote></details>

We don't really need this in skeleton, but after copy-paste it's needed, right?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Pal/src/host/Skeleton/meson.build, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbD_NBbDUNtaRFzx9cG:-MbDeRCb7-EIatBmUKta:bygpchc) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L45)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, we didn't pass this option, and I think we didn't have enough `-W` options for this to trigger. Jenkins certainly did compile `PAL_HOST=Skeleton` without `WERROR=`.
</blockquote></details>

Huh, that was bad :)
___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDeD-_3PttTKYhUnZm:b5gl098) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We don't really need this in skeleton, but after copy-paste it's needed, right?
</blockquote></details>

Yup, but I assume that the build script will need to drastically change either way. I'd just prefer to not install a component which doesn't work at all and is here just to be compiled.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDegQ40-bu8zjwgBy-:bmhcd0q) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, but I assume that the build script will need to drastically change either way. I'd just prefer to not install a component which doesn't work at all and is here just to be compiled.
</blockquote></details>

No, the change won't be drastic. I just copied one from `../Linux` and changed `direct` to `skeleton`. Some arch adjustments, `-Wno-unused-arguments` and it worked.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDgb_93nBgrog2_j7b:bjz5ji9) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, the change won't be drastic. I just copied one from `../Linux` and changed `direct` to `skeleton`. Some arch adjustments, `-Wno-unused-arguments` and it worked.
</blockquote></details>

Still, this leaves a non-functional component installed, which is bad from the users perspective. Maybe then just comment out these two lines and say that this should be re-added to installation when creating a new PAL?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDqy9RE7_xbJQer-_o:b-1helrj) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still, this leaves a non-functional component installed, which is bad from the users perspective. Maybe then just comment out these two lines and say that this should be re-added to installation when creating a new PAL?
</blockquote></details>

No, why it's bad? If the `-D` option is enabled, then I don't see why that's bad. This option is disabled by default, so unless user explicitly enables this, nothing will happen. If you want to bulid, but not really install, you can always `rm` this in packaging script (and this is a routine thing to do, as build scripts in most projects install ton of unnecessary things).

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbDt7SnBCrPUKnp216x:b-7nbybv) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, why it's bad? If the `-D` option is enabled, then I don't see why that's bad. This option is disabled by default, so unless user explicitly enables this, nothing will happen. If you want to bulid, but not really install, you can always `rm` this in packaging script (and this is a routine thing to do, as build scripts in most projects install ton of unnecessary things).
</blockquote></details>

Hmm, just feels wrong to me to install stub binaries which can't work in any useful way.

Anyways, I'm unblocking as enabling this manually is required, but let's also wait for @dimakuv and @boryspoplawski to weigh in.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbE5nbi2EGNeCvgpXYO:bw8d1s7) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, just feels wrong to me to install stub binaries which can't work in any useful way.

Anyways, I'm unblocking as enabling this manually is required, but let's also wait for @dimakuv and @boryspoplawski to weigh in.
</blockquote></details>

If the default is not to enable (and as consequence not to build and install), then I like the current version.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Skeleton/meson.build, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbD_NBbDUNtaRFzx9cG:-MbFVibX6P4Qt7vsSXqi:b2cmytu) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, that was bad :)
</blockquote></details>

LGTM from my side.
___
*[Pal/src/host/Skeleton/meson.build, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2418#-MbDa6B2EzZYeSgUDNex:-MbFVoh62QO1dktIVhyR:b-w9j06n) ([raw file](https://github.com/oscarlab/graphene/blob/d0cd95ec87575b715d76443d513ea7ab98f3686a/Pal/src/host/Skeleton/meson.build#L67)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If the default is not to enable (and as consequence not to build and install), then I like the current version.
</blockquote></details>

LGTM from my side, same reasoning as Borys.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`test-direct / apps.LTP.sigrelse01` timed out, first time I see it; unrelated)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2418)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
