### PR TITLE
[LibOS] Fix compilation errors with -Wunused-parameter

### PR DESCRIPTION
**Pull request by donporter**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Fix compilation issues with -Wunused-parameters

## How to test this PR? 

make WERROR=1

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/793)

### CODE REVIEW

**Comment by dimakuv** [comment]
- Jenkins-Debug fails with this:
```sh
[ shim_debug.o ]
In file included from shim_debug.c:27:0:
shim_debug.c: In function 'cp_gdb_map':
../include/shim_checkpoint.h:139:42: error: unused parameter 'obj' [-Werror=unused-parameter]
     struct shim_cp_store * store, void * obj, size_t size, void ** objp
                                          ^
../include/shim_checkpoint.h:144:45: note: in expansion of macro 'CP_FUNC_ARGS'
 #define DEFINE_CP_FUNC(name) int cp_##name (CP_FUNC_ARGS)
                                             ^
../include/shim_checkpoint.h:270:5: note: in expansion of macro 'DEFINE_CP_FUNC'
     DEFINE_CP_FUNC(name)                                            \
     ^
shim_debug.c:140:1: note: in expansion of macro 'BEGIN_CP_FUNC'
 BEGIN_CP_FUNC(gdb_map)
```

- Jenkins-SGX and Jenkins fail on LibOS regression tests

**Comment by donporter** [comment]
Retest Jenkins-SGX please.  large mmap timed out

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by dimakuv** [comment]
Retest Jenkins please

**Pull request merged**
