### PR TITLE
[Examples] Clean up all examples

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

- Redundant comments are removed from all manifest files except Redis.
- Mentions of deprecated Ubuntu 16.04 are removed from all examples.
- All readme files are now `README.md`.
- Simplified/removed misc manifest options in some examples.
- Removed useless Capnproto and Node.js Express Server

## How to test this PR? 

CI is enough. I tested a couple examples manually. But there should be zero actual changes.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)

### CODE REVIEW

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 47 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf7Vq7GD_r24cpkmr9f:b-2j8z08) (no related file):*
Do we need the "We tested on Ubuntu 18.04 with <software> version <version>"? Does this refer to manual sanity checks that someone did once?

I think what's important is that (most of) examples run on CI, and that's the configuration we can claim to support: Ubuntu 18.04 and 20.04, with the latest version of software available there (at least for the software installed from the repo). And that's something we could mention in a README for all examples, not in individual files.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7WtKd1rXEtmR8Z9ad:-Mf7WtKd1rXEtmR8Z9ae:bph4j3a) (no related file):*
Just checking: do we want the README files to be wrapped at 100 columns? That's consistent with everything else, and with what the Emacs settings say, but not with `Documentation/`.

---
___
*[Examples/README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7ZG5D-cFJleG9eteJ:-Mf7ZG5D-cFJleG9eteK:bcgpvlh) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/README.md#L8)):*
> ```Markdown
> please see the README.md in each subdirectory.
> 
> We recommend to look at the (extensively commented) Redis example to get an idea
> ```

This is good advice for understanding Graphene, but as a result people will copy the Redis example with all its comments etc. This might be not what we want users to do, and definitely not what we ourselves want to do when preparing new "official" examples.

I like having one official "template" project that we recommend to start from, but I'd prefer it to be the same as the rest. Maybe the comments and explanations could live in a documentation page, in a separate manifest file, or even in this README?
___
*[Examples/curl/README.md, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7VKTRB2WcYPjE2TGX:-Mf7VKTRB2WcYPjE2TGY:bsx8zmp) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/curl/README.md#L6)):*
> ```Markdown
> Graphene. We tested it with curl 7.58.0 on Ubuntu 18.04. This example uses curl
> installed on the system instead of compiling from source as some of the other
> examples do.  The Makefile and the template manifest contain comments to
> ```

The manifest does not contain comments anymore, right?

Also, I think we don't put double spaces after period.
___
*[Examples/memcached/Makefile, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7XB2t9td9Yg3TxTfJ:-Mf7XB2t9td9Yg3TxTfK:b-n5nw1g) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/memcached/Makefile#L61)):*
> ```Makefile
> 
> # The template file contains almost all necessary information to run Memcached under Graphene /
> # Graphene-SGX. We create memcached.manifest (to be run under non-SGX Graphene) by simply replacing
> ```

Thanks for removing "simply"! I try to avoid these too, after I've read [this](https://css-tricks.com/words-avoid-educational-writing/) some time ago.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: 33 of 68 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf7jh4YEUfjynEYH8_w:b-s8l7vr) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Do we need the "We tested on Ubuntu 18.04 with <software> version <version>"? Does this refer to manual sanity checks that someone did once?

I think what's important is that (most of) examples run on CI, and that's the configuration we can claim to support: Ubuntu 18.04 and 20.04, with the latest version of software available there (at least for the software installed from the repo). And that's something we could mention in a README for all examples, not in individual files.
</blockquote></details>

OK, I agree that these sentences do not add any value. I will remove them.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7WtKd1rXEtmR8Z9ad:-Mf7k3KSA2jtZg_69-Yb:b-bqiyp8) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Just checking: do we want the README files to be wrapped at 100 columns? That's consistent with everything else, and with what the Emacs settings say, but not with `Documentation/`.
</blockquote></details>

The README files (and actually all such user-text files) must be wrapped at 80 chars. This is Woju's recommendation. The reasoning is that to read text, it is better to have it "single-column" (the less words in one line the better). But for the code, we have 100 chars because overwise there are too many expression breaks.

We may have some README-like files wrapped to 100 chars, this should ideally be re-wrapped to 80 chars. I tried my best to stick to 80 chars in this PR.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7tWZt3Tn-4hGyKLQ_:-Mf7tWZt3Tn-4hGyKLQa:bdnxvd8) (no related file):*
Blocking myself: during final rebase, add that:
- Re-wrapped all READMEs to 80 chars and removed redundant info
- Removed redundant comments from all Makefiles (other than Redis)

---
___
*[Examples/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7qTDe39V0SrShn4Z3:-Mf7qTDe39V0SrShn4Z4:bimmfha) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/README.md#L1)):*
> ```Markdown
> # Example Integrations
> ```

FYI: I noticed that this README had strange wrap limit, so re-wrapped to 80 chars.
___
*[Examples/README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7ZG5D-cFJleG9eteJ:-Mf7kgCD5_Vt0TiHSYwu:bnvqy63) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/README.md#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is good advice for understanding Graphene, but as a result people will copy the Redis example with all its comments etc. This might be not what we want users to do, and definitely not what we ourselves want to do when preparing new "official" examples.

I like having one official "template" project that we recommend to start from, but I'd prefer it to be the same as the rest. Maybe the comments and explanations could live in a documentation page, in a separate manifest file, or even in this README?
</blockquote></details>

But we already have https://graphene.readthedocs.io/en/latest/manifest-syntax.html for explanations. I also dislike "abstract" examples, so I wouldn't want to add a separate manifest file/section in this README.

I added a few words saying that "don't copy these comments in your manifest files".
___
*[Examples/curl/README.md, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7VKTRB2WcYPjE2TGX:-Mf7mX5_Coegv-SwwM6Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/curl/README.md#L6)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The manifest does not contain comments anymore, right?

Also, I think we don't put double spaces after period.


</blockquote></details>

Done.

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7WtKd1rXEtmR8Z9ad:-Mf85USSCt8DhdTuo8Gw:b-6fl1rz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The README files (and actually all such user-text files) must be wrapped at 80 chars. This is Woju's recommendation. The reasoning is that to read text, it is better to have it "single-column" (the less words in one line the better). But for the code, we have 100 chars because overwise there are too many expression breaks.

We may have some README-like files wrapped to 100 chars, this should ideally be re-wrapped to 80 chars. I tried my best to stick to 80 chars in this PR.
</blockquote></details>

OK. Adding that to Emacs config: PR #2568

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf86dQ30Gp5ww4h4uIm:b5fpu0d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I agree that these sentences do not add any value. I will remove them.
</blockquote></details>

That looks better, but can you also remove them from the manifest templates? A lot of them begin with "This manifest was prepared and tested on Ubuntu 18.04".

---
___
*[Examples/README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7ZG5D-cFJleG9eteJ:-Mf85mPL8dITR4SHAweS:b-yfng3k) ([raw file](https://github.com/oscarlab/graphene/blob/07a49b06380e403200e33208aa0686e8248c0122/Examples/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we already have https://graphene.readthedocs.io/en/latest/manifest-syntax.html for explanations. I also dislike "abstract" examples, so I wouldn't want to add a separate manifest file/section in this README.

I added a few words saying that "don't copy these comments in your manifest files".
</blockquote></details>

OK, that helps.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf8APPz09SK82LvqdZI:bujx9ta) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That looks better, but can you also remove them from the manifest templates? A lot of them begin with "This manifest was prepared and tested on Ubuntu 18.04".
</blockquote></details>

But I did... See my last fixup commit.

---

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf8Ea5Q5B1FqmD6Yt9V:b2jdlgm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But I did... See my last fixup commit.
</blockquote></details>

The last commit I see is bff01a6de6f97d6191ba66a3578ec203eb4d057d, and `git grep "prepared and tested"` still shows the manifest templates for me.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: 46 of 68 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf8IzSs6V8ROamGlaZh:bdg7se7) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The last commit I see is bff01a6de6f97d6191ba66a3578ec203eb4d057d, and `git grep "prepared and tested"` still shows the manifest templates for me.
</blockquote></details>

Done. Sorry, misunderstood you. We were talking about READMEs, so I only removed in READMEs. Now also removed in manifests.

---

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7Vq7GD_r24cpkmr9e:-Mf8KZ9O0SDpri407bma:bwuz6lv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Sorry, misunderstood you. We were talking about READMEs, so I only removed in READMEs. Now also removed in manifests.
</blockquote></details>

Good to see all this gone!

---

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (timeout on `apps.LTP.writev07`, unrelated)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 11 of 47 files at r1, 35 of 35 files at r2, 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7tWZt3Tn-4hGyKLQ_:-MfFfq016tZoYziTQ1W0:bgqvdgj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: during final rebase, add that:
- Re-wrapped all READMEs to 80 chars and removed redundant info
- Removed redundant comments from all Makefiles (other than Redis)
</blockquote></details>

And that you removed 2 examples

---
___
*[Examples/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFf375BIC-iLb2Er__:-MfFf375BIC-iLb2Er_a:bwe176) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/README.md#L12)):*
> ```Markdown
> how to write the README, Makefile and manifest files. If you take this example
> as a template, we recommend to remove the comments from your copies as they only
> add noise.
> ```

This is completely missing the context IMO :) What you say here is about the case when someone wants to create and commit a new example to the repo, while the examples are mostly for the users which just try to use Graphene for their workloads.
___
*[Examples/README.md, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFl8DS59d-5iujvwNO:-MfFl8DS59d-5iujvwNP:b-vk64rl) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/README.md#L13)):*
> ```Markdown
> as a template, we recommend to remove the comments from your copies as they only
> add noise.
> ```

Could you mention that most of the examples use oversimplified configuration which is not secure? (e.g. specifying many security-critical files as `allowed_files`)
___
*[Examples/README.md, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFl2V_7TkdPqkivGva:-MfFl2V_7TkdPqkivGvb:bwk2ykc) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/README.md#L14)):*
> ```Markdown
> add noise.
> 
> ## How to Contribute?
> ```

We'll need to update this, but we can do this after repo migration.
___
*[Examples/bash/Makefile, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFgbSsEPjOXocfJBu8:-MfFgbStCsaF_U3LHq_i:be5pvp3) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/bash/Makefile#L8)):*
> ```Makefile
> # - make SGX=1 DEBUG=1
> #
> # Use `make clean` to remove Graphene-generated files.
> ```

This should actually be moved to the readme in all examples, I think.
___
*[Examples/blender/blender.manifest.template, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFguZ26J78DaPpdqUe:-MfFguZ26J78DaPpdqUf:b-dz8ius) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/blender/blender.manifest.template#L1)):*
> ```
> # INSECURE!!!
> ```

These should actually stay IMO. They are example-specific and important for the people which will use it.
___
*[Examples/memcached/memcached.manifest.template, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFkaz76-IHpOTE3ZOw:-MfFkaz89tKr9uvILpxm:b-cr9kpd) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/memcached/memcached.manifest.template#L104)):*
> ```
> # typical Memcached workloads.
> #
> # NOTE: Memcached does not fail explicitly when enclave memory is exhausted.
> ```

This may be important and is example-specific.
___
*[Examples/ra-tls-secret-prov/README.md, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFqL_XAeLHzzi80pm2:-MfFqL_XAeLHzzi80pm3:bbw1wal) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/ra-tls-secret-prov/README.md#L11)):*
> ```Markdown
> `Pal/src/host/Linux-SGX/tools/ra-tls`. Additionally, mbedTLS libraries are
> required. For ECDSA/DCAP attestation, the DCAP software infrastructure must be
> installed and working correctly on the host.
> ```

it was already there, but I think it should be `work` instead of `working`
___
*[Examples/memcached/README.md, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFlgO89qj9-3J4klls:-MfFlgO89qj9-3J4kllt:bbvy6e9) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/memcached/README.md#L41)):*
> ```
> host-OS username
> ```

Hmm, this is a very questionable wording :) Graphene emulates Linux, so it shouldn't be this way and may be surprising to the reader. And here it's this way because we have very limited uid/gid emulation in usermode and hack-around this limitation in this example's configuration by mounting host's `/etc/passwd`.
___
*[Examples/redis/README.md, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFquGX1qL6fVblVPuM:-MfFquGX1qL6fVblVPuN:b-icyg3c) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/redis/README.md#L10)):*
> ```Markdown
> and requirements for applications running under Graphene-SGX. If using these
> files as templates for your own applications, please remove the comments in your
> copies as they only add noise.
> ```

This isn't required and sounds a bit weird to say. If someone is customizing the configuration for their own application then it's obvious that they can drop the comments.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: 48 of 69 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7tWZt3Tn-4hGyKLQ_:-MfHByBc783JpnXeFU41:bf760fh) (no related file):*
> And that you removed 2 examples

This is a separate (first) commit in this PR: https://github.com/oscarlab/graphene/commit/139726971344e479d2485402560954a34bd03fc1

---
___
*[Examples/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFf375BIC-iLb2Er__:-MfHCl6z-HCrS46A9ms7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/README.md#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is completely missing the context IMO :) What you say here is about the case when someone wants to create and commit a new example to the repo, while the examples are mostly for the users which just try to use Graphene for their workloads.
</blockquote></details>

Done.
___
*[Examples/README.md, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFl8DS59d-5iujvwNO:-MfHDRdACYF_RsZblbXT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/README.md#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you mention that most of the examples use oversimplified configuration which is not secure? (e.g. specifying many security-critical files as `allowed_files`)
</blockquote></details>

Done.
___
*[Examples/bash/Makefile, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFgbSsEPjOXocfJBu8:-MfHETty0KpTy1K_WAqV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/bash/Makefile#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should actually be moved to the readme in all examples, I think.
</blockquote></details>

Done.
___
*[Examples/blender/blender.manifest.template, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFguZ26J78DaPpdqUe:-MfHEoA98S5NGPaVEsrM:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/blender/blender.manifest.template#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These should actually stay IMO. They are example-specific and important for the people which will use it.
</blockquote></details>

Done
___
*[Examples/memcached/memcached.manifest.template, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFkaz76-IHpOTE3ZOw:-MfHFN5Y7EMHznLKTyyy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/memcached/memcached.manifest.template#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This may be important and is example-specific.
</blockquote></details>

Done.
___
*[Examples/ra-tls-secret-prov/README.md, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFqL_XAeLHzzi80pm2:-MfHGBFXEgkYI0FobRHQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/ra-tls-secret-prov/README.md#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

it was already there, but I think it should be `work` instead of `working`
</blockquote></details>

Done.
___
*[Examples/memcached/README.md, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFlgO89qj9-3J4klls:-MfHG-C26LZui-qRn5Nr:b-rsurvm) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/memcached/README.md#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> host-OS username
> ```

Hmm, this is a very questionable wording :) Graphene emulates Linux, so it shouldn't be this way and may be surprising to the reader. And here it's this way because we have very limited uid/gid emulation in usermode and hack-around this limitation in this example's configuration by mounting host's `/etc/passwd`.
</blockquote></details>

Done. Hopefully this wording is less confusing.
___
*[Examples/redis/README.md, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2566#-MfFquGX1qL6fVblVPuM:-MfHGYRkD9Ec7vh0lbP0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5580877db065d377eb93912d5e2b0ec1f61c9b38/Examples/redis/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This isn't required and sounds a bit weird to say. If someone is customizing the configuration for their own application then it's obvious that they can drop the comments.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 21 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7tWZt3Tn-4hGyKLQ_:-MfJB2-O8eWFbGedb9C0:b-myadbf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> And that you removed 2 examples

This is a separate (first) commit in this PR: https://github.com/oscarlab/graphene/commit/139726971344e479d2485402560954a34bd03fc1
</blockquote></details>

Ah, I missed it.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2566#-Mf7tWZt3Tn-4hGyKLQ_:-MfKEUr96zExGAkFEI63:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I missed it.
</blockquote></details>

Done.

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (another series of timeouts on random LTP tests, unrelated to this PR but worrying, we need to debug this)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2566)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
