### PR TITLE
Updated GSC Readme

### PR DESCRIPTION
**Pull request by Kushg02**
## Affected components

- [x] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Added instructions for setting up Dockerfile before converting to a GSC image. 

Included a list of common errors and their respective resolutions

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/835)

### CODE REVIEW

**Comment by Kushg02** [comment]
> Nice write-up, thanks!
Glad to be of help :)

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Pull request merged**
