### PR TITLE
[PAL/Linux-SGX] The header files got sorted in db_thread.c

### PR DESCRIPTION
**Pull request by bigdata-memory**
## Description of the changes
The order of header files in db_thread.c is not well organized,
It got sorted to comply with GSGX code style.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1625)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by bigdata-memory** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1625#-MB0ZW6-8r54PJOUDUmk:-MB1KnDw579AHdKuBEX0:b9ekl4v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.
</blockquote></details>

I have updated my Github profile info, and force-pushed this commit for your check, thanks.

---

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
