### PR TITLE
[Docs] Update copyright years range

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just a simple fixup, the footnote on RTD was quite outdated.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2469)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, retest Jenkins-20.04 please (`apps.LTP.fsync02` timed out, known issue)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2469)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2469)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2469)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
