### PR TITLE
Various allocator bugfixes

### PR DESCRIPTION
**Pull request by mkow**

### CODE REVIEW

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by mkow** [comment]
btw. Isn't this bot broken? ;)

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
The bot should be working now, although it may not be happy with an external repository.

**Comment by neilbd** [comment]
test this once

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
ok to test

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by neilbd** [comment]
ok to test

**Comment by neilbd** [comment]
test this once

**Comment by neilbd** [comment]
test this please

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Re-run with tip of this branch (12/5)
Only going to test SGX, as Jenkins now tests the Linux host.

---
- [x] Describe the testing setup:
  - [x] **Code version:** branch omeg/master
  - [x] **Linux kernel version:** 4.4.0-98-generic
  - [x] **Ubuntu version:** 16.04.03 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@cdf563
  - [x] **SGX driver version:** 01org/linux-sgx-driver@e3e42d4
---
- [x] **PAL**
  - [x] **Linux+SGX host**
    - [x] **Compilation:** passed
    - [ ] **Regression tests:** 
---
- [x] **Library OS**
    - [x] **Compilation:** passed
    - [x] **Linux-SGX host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** Not fully supported yet
---
- [ ] **Applications**
    - [x] **Linux-SGX host**
      - [ ] **LMBench:** lat_proc shell gets a segmentation fault.  lat_tcp, bw_tcp 127.0.0.1 gets permission denied messages in connect; bw_pipe has an occasional failure with the signal queue overflowing (same problems observed on master), an occasional vma assertion blows.  - generally, pretty flaky on SGX, but not necessarily different than master.
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** Fails with memory allocation issue (same on master)
      - [ ] **Apache:**
      - [ ] **Python:**

**Pull request merged**
