### PR TITLE
[Pal] Clean up GDB configuration

### PR DESCRIPTION
**Pull request by pwmarcz**
See #1814 for discussion of specific GDB options.

## Description of the changes 

- Extract parts that are common for all hosts
- Remove some outdated/unnecessary options, we should now be
  closer to default configuration
- Disable libthread_db loading (does not work and crashes GDB 9.2)
- Disable pagination when loading debug maps   

## How to test this PR? 

* Try running some programs with GDB (under Linux and Linux-SGX).

* There are some smoke tests for GDB integration in `LibOS/shim/test/regression` (runnable with `~/graphene/Scripts/run-pytest -k TC_50_GDB`).

* Install with Meson and check if the `gdb_integration/common` directory is copied over properly:

```sh
meson build -Ddirect=enabled
DESTDIR=$PWD/install ninja -C build install
find install/
```

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2129#-MSSvgWq5rO4CzGEILZt:-MSSvgWr14OIB436jwVn:bmypoqy) (no related file):*
Is it intended that I still get `warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.`? (this is on openmp LibOS regression binary)

---

**Review by woju — APPROVED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2129#-MSSvgWq5rO4CzGEILZt:-MSTJ0jQ6lZyx9Hlu6Gc:b259m3i) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is it intended that I still get `warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.`? (this is on openmp LibOS regression binary)
</blockquote></details>

Yes, I think this is unavoidable - GDB really wants to load that `libthread_db` as soon as it sees a library that might need it (usually that's `libpthread`, in this case too), and we don't want it to because it actually breaks with Graphene.

---
___
*[Pal/gdb_integration/graphene.gdb, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2129#-MSTJo0EBRxziXwxr1y6:-MSTJo0EBRxziXwxr1y7:b-wccijc) ([raw file](https://github.com/oscarlab/graphene/blob/0feae4837d36e12159335168b00cdacb3cd5a88d/Pal/gdb_integration/graphene.gdb#L31)):*
> ```GDB
> # particularly annoying in Graphene, because checkpoint data is sent between processes just after
> # forking.
> set schedule-multiple on
> ```

I found out why these two options were necessary :)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/gdb_integration/graphene.gdb, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2129#-MSTJo0EBRxziXwxr1y6:-MSU21PT-q7Xojg7XH_F:bnljx7a) ([raw file](https://github.com/oscarlab/graphene/blob/0feae4837d36e12159335168b00cdacb3cd5a88d/Pal/gdb_integration/graphene.gdb#L31)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I found out why these two options were necessary :)
</blockquote></details>

Cool! Thanks for adding explanations.

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-apps please (`enclave EINIT failed - Invalid measurement`, probably a bug in Make dependencies in Examples/redis, known issue)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2129)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
