### PR TITLE
[Pal/lib] Remove `list-test`, move `path.c`, refactor crypto code

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

One more PR in the series of `Pal/lib` refactoring.

Three commits here:

- `[Pal/lib] Remove unused list-test.c`

-  `[Pal/lib] Move Pal/lib/graphene/path.c to Pal/lib/path.c`. This is to get rid of the `graphene/` subdir. All Graphene-specific utility files are stored under `Pal/lib/` by convention.

- `[Pal/lib] Remove redundant functionality from crypto`. This commit simplifies the crypto code:
    - `rng-arch.h` header and its `get_rand64()` are replaced with `_DkRandomBitsRead()` and subsequently removed.
    - `lib_Base64Encode()` and `lib_Base64Decode()` are replaced with their mbedTLS counterparts and subsequently removed.
    - All mbedTLS wrappers are amalgamated in a single `mbedtls_adapter.c`.
    - `pal_crypto.h` header is renamed to `crypto.h` (it has nothing to do with PAL code).

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_R9TcSAV2aYnqDgc4h:-M_UUhUC-FaTHgQ_95Uj:b-hh9zep) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How does this work? Isn't the resulting object file `.o` included in LibOS binary? Wouldn't that cause LibOS to use PAL internal interface?
(seems to be an existing issue)
</blockquote></details>

Good question. But not, LibOS will not use `_DkRandomBitsRead()` because this function is only called from mbedTLS wrappers. LibOS doesn't use these wrappers (in particular, the file `mbedtls_adapter.o`). So during the final linking step, when LibOS sources are linked against static `graphene-lib.a`, the linker notices that mbedTLS wrappers are not used and removes all that stuff. So in the end, the `libsysdb.so` library doesn't have any references to `_DkRandomBitsRead()`.

I verified it by manually inspecting the symbols and relocations in the resulting libraries.

This is a pretty bad design decision though... I don't know yet how to fix it. I could keep it as-is for now. (Maybe it's not too bad, after all it's just a callback that the actual user of this helper lib needs to provide.)

**Review by yamahata — DISMISSED** [review]
> Reviewed 16 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_R9TcSAV2aYnqDgc4h:-M_VFNO86do2-r9ykwdt:bi0r3i0) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good question. But not, LibOS will not use `_DkRandomBitsRead()` because this function is only called from mbedTLS wrappers. LibOS doesn't use these wrappers (in particular, the file `mbedtls_adapter.o`). So during the final linking step, when LibOS sources are linked against static `graphene-lib.a`, the linker notices that mbedTLS wrappers are not used and removes all that stuff. So in the end, the `libsysdb.so` library doesn't have any references to `_DkRandomBitsRead()`.

I verified it by manually inspecting the symbols and relocations in the resulting libraries.

This is a pretty bad design decision though... I don't know yet how to fix it. I could keep it as-is for now. (Maybe it's not too bad, after all it's just a callback that the actual user of this helper lib needs to provide.)
</blockquote></details>

Please add a comment about it then (GH issue, in code, wherever).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_R9TcSAV2aYnqDgc4h:-M_VlQ3YEPME7ZIcDBys:bl04ln4) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment about it then (GH issue, in code, wherever).
</blockquote></details>

Done. https://github.com/oscarlab/graphene/issues/2371

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 16 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_VxLQZ-yGViEzCxXto:-M_VxLQZ-yGViEzCxXtp:b-rt6rxy) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L3)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2017 Fortanix, Inc. */
> /* Copyright (C) 2019, Texas A&M University. */
> ```

Could you drop the comma and the period to unify with other places?
___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 439 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3UkM4Q14lEm5va96:-M_W3UkM4Q14lEm5va97:b-kef8tc) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L439)):*
> ```C
>      * haven't implemented that yet. */
>     ret = mbedtls_mpi_read_string(&context->P, 16 /* radix */, MBEDTLS_DHM_RFC3526_MODP_2048_P);
>     if (ret < 0)
> ```

You changed all `!=` to `<`, but I think mbedtls returns positive error codes?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3yw24KqtzChFdG3S:-M_W3yw24KqtzChFdG3T:b-hqzcs7) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/attestation.c#L175)):*
> ```C
>     ret = mbedtls_base64_decode(ias_sig, ias_sig_size, &ias_sig_size, ias_sig_b64,
>                                 ias_sig_b64_size);
>     if (ret < 0) {
> ```

not `!=`?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 289 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W4-dG7OL8vVvbRZY5:-M_W4-dG7OL8vVvbRZY6:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/attestation.c#L289)):*
> ```C
>     ret = mbedtls_base64_decode(report_quote, quote_size, &quote_size, (uint8_t*)node->valuestring,
>                                 strlen(node->valuestring));
>     if (ret < 0) {
> ```

ditto
___
*[Pal/src/host/Linux-SGX/tools/common/ias.c, line 353 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W42LBEeB4IzZkWo2x:-M_W42LC3KZuqZqK9uZv:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/ias.c#L353)):*
> ```C
>         ret = mbedtls_base64_decode(*sigrl, *sigrl_size, sigrl_size, (uint8_t*)ias_resp->data,
>                                     strlen(ias_resp->data));
>         if (ret < 0 || !*sigrl_size) {
> ```

ditto
___
*[Pal/src/host/Linux-SGX/tools/common/ias.c, line 397 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3tKv5dz8FbNFjtYb:-M_W3tKv5dz8FbNFjtYc:b-hqzcs7) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/ias.c#L397)):*
> ```C
>     ret = mbedtls_base64_encode((uint8_t*)quote_b64, quote_b64_size, &quote_b64_size, quote,
>                                 quote_size);
>     if (ret < 0) {
> ```

not `!=`?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: 18 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_VxLQZ-yGViEzCxXto:-M_e3F5iBftebbpJbovq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you drop the comma and the period to unify with other places?
</blockquote></details>

Done.
___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 439 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3UkM4Q14lEm5va96:-M_e2M8a1hAd3P_NY5jD:b-w3s4d2) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L439)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You changed all `!=` to `<`, but I think mbedtls returns positive error codes?
</blockquote></details>

Why do you think so? MbedTLS returns negative error codes on failures. See e.g. https://tls.mbed.org/api/error_8h.html.

(There are a couple legitimate cases where we check mbedTLS functions via `ret != 0` because we don't want positive values sometimes, but these do not denote errors)

Btw, I don't know why the old code contained this `!= 0`. I think this was just a very old convention in the Graphene code.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3yw24KqtzChFdG3S:-M_e2eP3Bjm8FXCefm7P:bm462se) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/attestation.c#L175)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not `!=`?
</blockquote></details>

ditto. See e.g. https://tls.mbed.org/api/base64_8h.html#a1e8abeb72a244acb346fc4ac3083886c
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 289 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W4-dG7OL8vVvbRZY5:-M_e2ffP42g_mSPpDjyp:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/attestation.c#L289)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/tools/common/ias.c, line 353 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W42LBEeB4IzZkWo2x:-M_e2mRf1H0XhRpUMuyO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/ias.c#L353)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/tools/common/ias.c, line 397 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3tKv5dz8FbNFjtYb:-M_e2n2b6ZDLDkCfvlc9:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/src/host/Linux-SGX/tools/common/ias.c#L397)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not `!=`?
</blockquote></details>

ditto

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/lib/crypto/adapters/mbedtls_adapter.c, line 439 at r2](https://reviewable.io/reviews/oscarlab/graphene/2367#-M_W3UkM4Q14lEm5va96:-M_eSXpHBntbgwJvqGaN:b-mosj21) ([raw file](https://github.com/oscarlab/graphene/blob/48fbae1fe8e2869adeb9e17b2bf8103dd96b37c8/Pal/lib/crypto/adapters/mbedtls_adapter.c#L439)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you think so? MbedTLS returns negative error codes on failures. See e.g. https://tls.mbed.org/api/error_8h.html.

(There are a couple legitimate cases where we check mbedTLS functions via `ret != 0` because we don't want positive values sometimes, but these do not denote errors)

Btw, I don't know why the old code contained this `!= 0`. I think this was just a very old convention in the Graphene code.
</blockquote></details>

Oh, my bad. I saw that all the old code uses `!= 0` specifically for mbed TLS, then I checked their `mbedtls__ecode.h` and saw things like `#define 	MBEDTLS_ERR_CMAC_BASE   ( MBEDTLS_ECODE_AESDRV_BASE | 0xf00)` so I concluded that it's indeed positive :)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`kill11` LTP test failed)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2367)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
