### PR TITLE
more makefile cleanup

### PR DESCRIPTION
**Pull request by yamahata**
## Affected components

- [x] README and global configuration
- [x] Linux PAL
- [x] SGX PAL
- [x] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Corresponding PR is https://github.com/oscarlab/graphene-tests/pull/67

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/976)

### CODE REVIEW

**Comment by dimakuv** [comment]
Oops, some LibOS regression tests failed on all pipelines.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins please. (Internal memory fault at vma with test_000_spinlock)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. (test_libos.TC_02_OpenMP testMethod=test_000_simple_for_loop timeout)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-Debug-18.04 please.  (apps.LTP.recv01 timeout)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. (test_libos.TC_01_Bootstrap.test_200_exec assertion error)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. (large-mmap returned non-zero exit status 1)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please.  test_200_exec assertion error.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please.  (test_403_signalexit_multithread timeout)

**Comment by yamahata** [comment]
Jenkins, retest this please.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX-18.04 please. test_000_simple_for_loop timeout

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-Debug please.  test_401_exit_group timeout

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX-18.04-apps please. source forge 502 bad gate way during downloading lmbench

**Comment by yamahata** [comment]
source forge 502 bad gate way during downloading lmbench. source forge 502 bad gateway when downloading lmbench.

**Pull request merged**
