### PR TITLE
[LibOS] Add missing `sigsetsize` arg in rt_sigprocmask handler

### LINKED ISSUE #2253: Syscall signature mismatch b/w Linux and Graphene for rt_sigprocmask syscall
## Description of the problem
In Graphene OS, the syscall signature between Linux implementation for syscall doesn't match the signature inside Graphene. It is missing fourth argument which is size.

Linux:
int rt_sigprocmask(int how, const kernel_sigset_t *set, kernel_sigset_t *oldset, size_t sigsetsize);

Graphene:
long shim_do_rt_sigprocmask(int how, const __sigset_t* set, __sigset_t* oldset)

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Seems we had an incorrect signature of `rt_sigprocmask` (I guess copied from glibc instead of Linux?).
Kudos to @anjalirx-intel for finding this.

Fixes #2253.

## How to test this PR? 

CI (one new LTP test was enabled)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsErC0Z2z4eNkn9H2:-MWBsErC0Z2z4eNkn9H3:b-7vxniq) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/shim_parser.c#L103)):*
> ```C
>                            parse_signum, parse_pointer_arg, parse_pointer_arg, parse_pointer_arg}},
>     [__NR_rt_sigprocmask] = {.slow = false, .name = "rt_sigprocmask", .parser = {parse_long_arg,
>                              parse_sigprocmask_how, parse_sigmask, parse_sigmask, parse_long_arg}},
> ```

`parse_pointer_arg` (I know, naming here sucks) as this is unsigned.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsbr6-wXH452zzUiC:-MWBsbr6-wXH452zzUiD:b8zl2ib) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/sys/shim_sigaction.c#L89)):*
> ```C
>     __sigset_t old;
> 
>     if (sigsetsize != sizeof(sigset_t))
> ```

`__sigset_t` or more preferably `*set`.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: 2 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_parser.c, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsErC0Z2z4eNkn9H2:-MWC27jh6jPWQx4zhmIR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/shim_parser.c#L103)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`parse_pointer_arg` (I know, naming here sucks) as this is unsigned.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsbr6-wXH452zzUiC:-MWC2HVAESoGQh5plUL_:b-xpp310) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/sys/shim_sigaction.c#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`__sigset_t` or more preferably `*set`.
</blockquote></details>

Done. But I slightly prefer `__sigset_t` here, because it's for both args and this structure is hardcoded in the interface.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsbr6-wXH452zzUiC:-MWC4JTj0KeZmWL3_biK:bo93j66) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/sys/shim_sigaction.c#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done. But I slightly prefer `__sigset_t` here, because it's for both args and this structure is hardcoded in the interface.
</blockquote></details>

It's not really hardcoded in interface, we might change it's name when we clean up headers (e.g. pull all of them into Graphene).
New e.g. name `__kernel_sigset_t`, `sigset_t`....

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsbr6-wXH452zzUiC:-MWC4hhHCU6SZ5SJ4ziW:bvonchi) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/sys/shim_sigaction.c#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not really hardcoded in interface, we might change it's name when we clean up headers (e.g. pull all of them into Graphene).
New e.g. name `__kernel_sigset_t`, `sigset_t`....
</blockquote></details>

Additionally: the fact that both args are of the same type is hardcoded in the interface.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2257#-MWBsbr6-wXH452zzUiC:-MWC9LDM0Bws96_pL3PE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/51bc79a6fa2be9369578a0531e72c4d1ab425d72/LibOS/shim/src/sys/shim_sigaction.c#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Additionally: the fact that both args are of the same type is hardcoded in the interface.
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (`apps.LTP.writev07` timed out, I couldn't reproduce in 1k runs, maybe some random Jenkins lag?)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2257)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
