### PR TITLE
Fix sgx driver build failure

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1087)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by jiazhang0** [comment]
@dimakuv I see Jenkins-SGX-18.04 seems to get failure. Not sure what happens though.

**Comment by dimakuv** [comment]
@jiazhang0 The fact that Jenkins-SGX-18.04 fails is normal. This is not because of your PR but due to lingering issues with this particular pipeline. Just ignore this pipeline.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Pull request merged**
