### PR TITLE
Add tests for invalid protected files

### PR DESCRIPTION
**Pull request by omeg**
~~*This PR depends on #1325, wait for that to be merged for easier reviewing*~~

*UPDATE: PR is rebased by Dmitrii Kuvaiskii to the most recent master.*

## Description of the changes 
This PR updates the `pf_tamper` utility to the new protected file format. Tests for invalid/corrupted PFs are now enabled.

## How to test this PR? 
Run LibOS FS tests. (They are ran by default in our Jenkins, including this new "invalid" test.)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene/1512#-MPiQe-y40VYq2bs7C1J:-MPiQe-z0v-pbZTNBkHx:bzhqusy) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L80)):*
> ```C
>     uint32_t output_len; // in bits
> } kdf_input_t;
> #pragma pack(pop)
> ```

FYI: This was moved to `protected_files_format.h` since it is shared with other source files.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1512#-MPiRj2q7slGYo9FYAst:-MPiRj2q7slGYo9FYAsu:bji63pr) (no related file):*
FYI: This PR is rebased to the latest master and is ready for review. I fixed a couple issues, now the "invalid PF" tests pass.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[LibOS/shim/test/fs/test_pf.py, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ8wHfYBGFYgJKo0vtE:-MQ8wHfYBGFYgJKo0vtF:b17id74) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/LibOS/shim/test/fs/test_pf.py#L204)):*
> ```Python
>             os.mkdir(invalid_dir)
> 
>         # files below should work normally (benign modifications); currently none
> ```

Do we ever plan to have such "benign modifications"? Not sure if it's worth to support such a currently non-existent case.
___
*[LibOS/shim/test/fs/test_pf.py, line 229 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ928ne0s5flRxAyISH:-MQ928ne0s5flRxAyISI:b-oq8zw9) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/LibOS/shim/test/fs/test_pf.py#L229)):*
> ```Python
>                     self.assertEqual(exc.returncode, 0)
>                 else:
>                     self.assertNotEqual(exc.returncode, 0)
> ```

I think we should also detect crashes as failures (which are likely, as we're throwing corrupted files into our parser)
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ8zwEQA6zK_KaoJCSm:-MQ8zwER--HpyZMwfY8Q:b-b6p74a) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L17)):*
> ```C
> 
>    You should have received a copy of the GNU Lesser General Public License
>    along with this program.  If not, see <http://www.gnu.org/licenses/>.  */
> ```

Please convert this to SPDX and reformat the copyright comment.
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 23 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ9-gF9ESLJuax12RQg:-MQ9-gF9ESLJuax12RQh:bfur1f3) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L23)):*
> ```C
> #include <stdlib.h>
> #include <unistd.h>
> #include <sys/mman.h>
> ```

please sort
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 99 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ90b-X7ITeapw106Cq:-MQ90b-Y3nS392G-5iJ_:b-4mjv69) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L99)):*
> ```C
> - Node 98: MHT
> - Node 99-195: data
> - ...
> ```

Please add leading `* ` to match the comment style we use in other places.
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 213 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ92QtoD_1t1eoV1oNB:-MQ92QtoD_1t1eoV1oNC:bkx5p4f) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L213)):*
> ```C
>     // after data_nodes_crypto[0].gmac
>     truncate_file("trunc_mht_4", PF_NODE_SIZE + PF_KEY_SIZE + PF_MAC_SIZE);
> #define DATA_CRYPTO_SIZE FIELD_SIZEOF(mht_node_t, data_nodes_crypto)
> ```

this should be parenthesized
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 265 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ92mK20Svvkrq5hrLp:-MQ92mK20Svvkrq5hrLq:b-2y6s2h) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L265)):*
> ```C
> 
> static void pf_decrypt(const void* encrypted, size_t size, const pf_key_t* key, const pf_mac_t* mac,
>                 void* decrypted, const char* msg) {
> ```

please fix alignment
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 438 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ94qSd8fyutH-7vkX4:-MQ94qSd8fyutH-7vkX5:b-hwirug) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L438)):*
> ```C
> }
> 
> int main(int argc, char *argv[]) {
> ```

`char *` -> `char* `
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 522 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ95MMNEG1HVhNR2XrS:-MQ95MMNEG1HVhNR2XrT:b-cus9w1) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L522)):*
> ```C
>     tamper_modify();
> 
> out:
> ```

I think we can skip the cleanup, as we're in `main()`.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/fs/test_pf.py, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ8wHfYBGFYgJKo0vtE:-MQBUlpm8q4NlFl2oTge:be6v8ah) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/LibOS/shim/test/fs/test_pf.py#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we ever plan to have such "benign modifications"? Not sure if it's worth to support such a currently non-existent case.
</blockquote></details>

Done. Removed this logic.
___
*[LibOS/shim/test/fs/test_pf.py, line 229 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ928ne0s5flRxAyISH:-MQBXb_k6kUsb7cBYT_8:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/LibOS/shim/test/fs/test_pf.py#L229)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we should also detect crashes as failures (which are likely, as we're throwing corrupted files into our parser)
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ8zwEQA6zK_KaoJCSm:-MQBXsr6DAHyX3o__RN2:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please convert this to SPDX and reformat the copyright comment.
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 23 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ9-gF9ESLJuax12RQg:-MQBXy4_BsnBt6gBHN-q:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 99 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ90b-X7ITeapw106Cq:-MQBZ0VT8yvLnXNlKU1P:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add leading `* ` to match the comment style we use in other places.
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 164 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQBck_a7cvm38wDfva_:-MQBck_a7cvm38wDfvaa:b-yc91ck) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L164)):*
> ```C
>     pf_mac_t   metadata_gmac;
> } metadata_plain_t;
> */
> ```

FYI: I decided to remove these "helper" comments (these were copy-pasted by Rafal from the corresponding PF header file, just to remember the struct layout)
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 213 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ92QtoD_1t1eoV1oNB:-MQBaXyTA1_cLc2WPCTU:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be parenthesized
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 235 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQBcx6k-suwwT8__L2K:-MQBcx6k-suwwT8__L2L:bjufegg) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L235)):*
> ```C
>     truncate_file("trunc_data_3", 3 * PF_NODE_SIZE + PF_NODE_SIZE / 2);
> 
>     // TODO: other MHTs?
> ```

FYI: this was to remind us that we only test PF nodes 0..3. But I think this is already enough, it doesn't merit a TODO.
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 265 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ92mK20Svvkrq5hrLp:-MQBaj0B8gx_wSuHh5uH:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L265)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 438 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ94qSd8fyutH-7vkX4:-MQBan5v5sU83q0t78lR:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L438)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`char *` -> `char* `
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 522 at r3](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQ95MMNEG1HVhNR2XrS:-MQBbSfa281ju9sBCMir:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1e507a45280d653e0c9b847e667f7ef248784a44/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we can skip the cleanup, as we're in `main()`.
</blockquote></details>

Done

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[LibOS/shim/test/fs/test_pf.py, line 222 at r4](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQCEDzu251Fr0NL0Wij:-MQCEDzw0b7DL_nOG8WE:b-9olfa6) ([raw file](https://github.com/oscarlab/graphene/blob/cadcb1cf0090dc5ecd08d10a9e9505152ac2ca44/LibOS/shim/test/fs/test_pf.py#L222)):*
> ```Python
>                 self.__pf_crypt(args)
>             except subprocess.CalledProcessError as exc:
>                 # decrypt of invalid file must fail with -1 (wrapped to 255)
> ```

`decrypt` -> `decryption`

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/fs/test_pf.py, line 222 at r4](https://reviewable.io/reviews/oscarlab/graphene/1512#-MQCEDzu251Fr0NL0Wij:-MQDpzWZEvIBdK11mVqa:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/cadcb1cf0090dc5ecd08d10a9e9505152ac2ca44/LibOS/shim/test/fs/test_pf.py#L222)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`decrypt` -> `decryption`
</blockquote></details>

Done

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
