### PR TITLE
[Pal] Add a pytest test harness for the test cases in Pal/test

### PR DESCRIPTION
**Pull request by stefanberger**
Add a pytest test harness for being able to run the test cases in Pal/test from command line.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1397)

### CODE REVIEW

**Comment by stefanberger** [comment]
I am porting Graphene to PowerPC64 and these test helped me a LOT!

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (`test_libos.TC_01_Bootstrap.test_601_multi_pthread_exitless` timed out, `test_libos.TC_40_FileSystem.test_010_path` ended with `Command '['proc-path']' returned non-zero exit status 139`. No idea what's the latter failure...)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX please (`multithread_exitless` LibOS test timed out)

**Pull request merged**
