### PR TITLE
 Enabled two-step signing support in graphene.

### PR DESCRIPTION
**Pull request by ying2liu**
Currently, graphene only supports one-step signing. The two-step signing is
necessary because the ISV’s private key is typically not present on the build
platform. This patch enables two-step signing support in graphene.

The first step: Generate the signing material file.

The signing material is signed at the signing facility using the private key.
The signature file is taken back to the building system.

The second step: Sign the enclave file using the signature file and public key.

Add three parameters in sgx_sig.py:
--mode "gendata" is for two-step signing to generate the signing material;
              "catsig" is for two-step signing to sign the enclave file using 
                            the signature file and public key;
              "sign" is for one-step signing to sign the enclave file;
              The default mode is "sign", therefore one-step signing will be used 
              if mode is not specified.

--sig  the signature file for the enclave signing material.
--unsign the enclave signing material generated by "gendata".

Change-Id: I5d45ed10f06043b2c71a91a7da138b43bb1f36df

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2528)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-MeO_v0F7L0naN3UhGOL:b-lfvj7b) (no related file):*
The commit message is badly formatted, contains old/renamed fields and commands, and is generally too long. Please fix the commit message (I suggest to remove the "example commands" completely and rephrase the new `mode` parameter).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOaB0MDZffhZArFilR:-MeOaB0MDZffhZArFilS:balesjd) (no related file):*
Generally, thanks for the PR, but we first need to refactor the whole `sgx_sign.py` mess.

The problem is that this Python script currently does three independent things:
1. Generate the `.manifest.sgx` file
2. Create the final sigstruct (`.sig`) file, including the signature and pubkey parameters
3. Generate dependencies (`.d`) for Makefiles (!!!)

Soon we will be able to remove item 3 (because we won't have Makefiles). But items 1 and 2 must be separated in two Python scripts, and we could still have a "glue" Python script with this interface (to not change the user-facing interface).

After this refactoring, the two-step signing process can be added. @woju @mkow Does this sound reasonable to you?

---
___
*[python/graphenelibos/sgx_sign.py, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOZvdV8RGsJmAZ7pq7:-MeOZvdV8RGsJmAZ7pq8:b-c14clm) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L582)):*
> ```Python
>     sign_buffer = bytearray(128 + 128)
> 
>     def dump_sig_struct(buffer, fields, title):
> ```

Why do we need this function? If printing sigstruct fields is really needed, shouldn't we have a separate Python tool (script) solely for this purpose?
___
*[python/graphenelibos/sgx_sign.py, line 622 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_BDH9anjpDA4DNj8:-MeO_BDH9anjpDA4DNj9:b-2qnveh) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L622)):*
> ```Python
>             return content
>         signature = read_bin_file(args['sig'])
>         signature = signature[::-1]
> ```

Why is this line needed?
___
*[python/graphenelibos/sgx_sign.py, line 847 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_ViyESJ38YvTKM0d:-MeO_ViyESJ38YvTKM0e:b-s00lnx) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L847)):*
> ```Python
>         comment = '# DO NOT MODIFY. THIS FILE WAS AUTO-GENERATED.\n\n'
>         manifest_data = bytes(comment + manifest_data_str, 'utf-8')
>         manifest_data += b'\0' # in-memory manifest needs NULL-termination
> ```

What's the point of this else branch? Isn't it doing the same as the other branch?
___
*[python/graphenelibos/sgx_sign.py, line 864 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_bub0__83bzBuPZH:-MeO_bub0__83bzBuPZI:bbml8lf) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L864)):*
> ```Python
>     # Generate sigstruct
>     if (args['mode'] == 'gendata'):
>         # it is verified that dataout exists
> ```

What is `dataout`? Who verifies it? I don't understand this comment

**Review by ying2liu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-MeR3e0X8eptkgtNaDog:b8krioo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The commit message is badly formatted, contains old/renamed fields and commands, and is generally too long. Please fix the commit message (I suggest to remove the "example commands" completely and rephrase the new `mode` parameter).
</blockquote></details>

I will remove the example commands and  update the commit message.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOaB0MDZffhZArFilR:-MeR3nOH--MO9UJFKNvw:b-f03ao6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Generally, thanks for the PR, but we first need to refactor the whole `sgx_sign.py` mess.

The problem is that this Python script currently does three independent things:
1. Generate the `.manifest.sgx` file
2. Create the final sigstruct (`.sig`) file, including the signature and pubkey parameters
3. Generate dependencies (`.d`) for Makefiles (!!!)

Soon we will be able to remove item 3 (because we won't have Makefiles). But items 1 and 2 must be separated in two Python scripts, and we could still have a "glue" Python script with this interface (to not change the user-facing interface).

After this refactoring, the two-step signing process can be added. @woju @mkow Does this sound reasonable to you?
</blockquote></details>

The two-step signing patch doesn't change sgx_sign.py design. It won't have any impact on the refactoring process. But if we hold the patch after refactoring sgx_sign.py, maybe we have to redo two_step signing.

---
___
*[python/graphenelibos/sgx_sign.py, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOZvdV8RGsJmAZ7pq7:-MeR2uq_3tQeZMvZOAIn:bi5c27j) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L582)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this function? If printing sigstruct fields is really needed, shouldn't we have a separate Python tool (script) solely for this purpose?
</blockquote></details>

This function is for debug purpose only. I will remove it.
___
*[python/graphenelibos/sgx_sign.py, line 622 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_BDH9anjpDA4DNj8:-MeQqlXa4vh7OsCDQsaB:b-ta5mgq) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L622)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this line needed?
</blockquote></details>

This line reads the signature file of the signing material and reverse the string.
___
*[python/graphenelibos/sgx_sign.py, line 847 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_ViyESJ38YvTKM0d:-MeQo6TVDF2qHXbnuqMW:b-r3cb7y) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L847)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this else branch? Isn't it doing the same as the other branch?
</blockquote></details>

The else condition is for "gendata", which doesn't have .manifest.sgx output.
___
*[python/graphenelibos/sgx_sign.py, line 864 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_bub0__83bzBuPZH:-MeQndZ19I8HJqEzwo8X:b-8ui0hi) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L864)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `dataout`? Who verifies it? I don't understand this comment
</blockquote></details>

This is an old comment. I will remove it.

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @ying2liu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOaB0MDZffhZArFilR:-MeSCa8O6u5UMK3u22kk:bge7cm2) (no related file):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

The two-step signing patch doesn't change sgx_sign.py design. It won't have any impact on the refactoring process. But if we hold the patch after refactoring sgx_sign.py, maybe we have to redo two_step signing.
</blockquote></details>

`.d` are also used by meson/ninja (arranged by meson and parsed by ninja), so they migh be useful. And if not in meson, someone might choose to build enclaves using make and not meson, so we shouldn't remove that option.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeSCsmLA2Tqv7CGtsAm:-MeSCsmLA2Tqv7CGtsAn:bqejixj) (no related file):*
NAK `--mode`, those should really be different CLI tools. They can always share a common import if there would be a need for common code. Or at least make them subcommands, with click it's almost the same to write.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeSDOBm1y_IA2dmDb6q:-MeSDOBnAT7nnaSXmOi_:bmxy59g) (no related file):*
I've seen the presentation and I've to say I'm not impressed. I really prefer incremental manifests over this approach, as the incremental is both simpler and more general.

---

**Review by ying2liu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOaB0MDZffhZArFilR:-MeSQ340-qpXjosR1gBQ:b9g922h) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`.d` are also used by meson/ninja (arranged by meson and parsed by ninja), so they migh be useful. And if not in meson, someone might choose to build enclaves using make and not meson, so we shouldn't remove that option.
</blockquote></details>

I didn't touch .d file.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeSCsmLA2Tqv7CGtsAm:-MeSM4sl3Mma_DSVHW3d:b-mxgyeq) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

NAK `--mode`, those should really be different CLI tools. They can always share a common import if there would be a need for common code. Or at least make them subcommands, with click it's almost the same to write.
</blockquote></details>

Did you mean that you prefer three different commands for gendata, catsig and sign? My goal is to share the common code as much as possible to avoid accidentally breaking anything.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeSDOBm1y_IA2dmDb6q:-MeSLWBlCGdX3TRpkO9d:b-4pt8fe) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I've seen the presentation and I've to say I'm not impressed. I really prefer incremental manifests over this approach, as the incremental is both simpler and more general.
</blockquote></details>

what is incremental manifest? Could you please clarify that for me?

---
___
*[python/graphenelibos/sgx_sign.py, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOZvdV8RGsJmAZ7pq7:-MeRhbQP3XsYX0Xbb4hi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L582)):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

This function is for debug purpose only. I will remove it.
</blockquote></details>

Done.

**Review by ying2liu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-MeSXj4RDD6jiDhtHlfi:b-896fix) (no related file):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

I will remove the example commands and  update the commit message.
</blockquote></details>

Done.

---
___
*[python/graphenelibos/sgx_sign.py, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeOZvdV8RGsJmAZ7pq7:-MeSXdJN89bjZceGrDzb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L582)):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 622 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_BDH9anjpDA4DNj8:-MeSXfCUCrFwOA1maD9d:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L622)):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

This line reads the signature file of the signing material and reverse the string.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 847 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_ViyESJ38YvTKM0d:-MeSXbC3DVCeP6KVkThA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L847)):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

The else condition is for "gendata", which doesn't have .manifest.sgx output.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 864 at r1](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_bub0__83bzBuPZH:-MeSXZG2068CbVr-Ph4S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9814006ed4cfb2724ae4428a815b0bb1f5ab167d/python/graphenelibos/sgx_sign.py#L864)):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

This is an old comment. I will remove it.
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeSCsmLA2Tqv7CGtsAm:-MeVjfZgAqIQPlYtr05J:b-u95hbi) (no related file):*
I agree with @woju that we should make these subcommands (but not separate CLI tools). Also, I see no problem in splitting this one huge messy file into three files, and then having one more Python file which imports these three and has the CLI.

> to avoid accidentally breaking anything.

I understand this, but this `sgx_sign.py` is old and bad. It's time to refactor it.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-Me_tRWW645ENBexxKtU:b-1djfgx) (no related file):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please clean up the whole PR, it's a mess.
You should proofread things before publishing, the PR description is completely unreadable (just open it on GitHub and see yourself).

---

**Review by ying2liu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-MesHlDp9ToCP9KywEZW:bh2fjgc) (no related file):*
> 46e4599:  Enable two-step signing support in graphene.
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> 
>     The first step: Generate the signing material.
> 
>     At the signing facility, sign the file containing the enclave signing
>     material using the private key and take the resulting signature file
>     back to the build system.
> 
>     The second step: Sign the enclave file using the signature file and public key.
> 
>     Added three input parameters in sgx_sig.py:
>     --mode "gendata" is for two-step signing to generate the enclave signing material;
>            "catsig" is for two-step signing to sign the enclave file using the signature file and public key;
>            "sign" is for one-step signing to sign the enclave file;
>            The default mode is "sign", so the default signing method is one-step signing.
> 
>     --sig  the signature file for the enclave signing material.
>     --unsign the enclave signing material generated by "gendata".
</details>


 Currently, graphene only supports one-step signing. The two-step signing is 
	  necessary because the ISV’s private key is typically not present on the build 
	  platform. This patch enables two-step signing support in graphene.

    The first step: Generate the signing material file.
    
    The signing material is signed at the signing facility using the private key.
    The signature file is taken back to the building system.
    
    The second step: Sign the enclave file using the signature file and public key.

    Added three parameters in sgx_sig.py:
    --mode "gendata" is for two-step signing to generate the signing material;
           "catsig" is for two-step signing to sign the enclave file using 
           the signature file and public key;
           "sign" is for one-step signing to sign the enclave file;
           The default mode is "sign", therefore one-step signing will be used 
           if mode is not specified.

    --sig  the signature file for the enclave signing material.
    --unsign the enclave signing material generated by "gendata".
    

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-Mex_GwPB0ERt0-QWFNl:b42naiq) (no related file):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

> 46e4599:  Enable two-step signing support in graphene.
> 
>     The first step: Generate the signing material.
> 
>     At the signing facility, sign the file containing the enclave signing
>     material using the private key and take the resulting signature file
>     back to the build system.
> 
>     The second step: Sign the enclave file using the signature file and public key.
> 
>     Added three input parameters in sgx_sig.py:
>     --mode "gendata" is for two-step signing to generate the enclave signing material;
>            "catsig" is for two-step signing to sign the enclave file using the signature file and public key;
>            "sign" is for one-step signing to sign the enclave file;
>            The default mode is "sign", so the default signing method is one-step signing.
> 
>     --sig  the signature file for the enclave signing material.
>     --unsign the enclave signing material generated by "gendata".


 Currently, graphene only supports one-step signing. The two-step signing is 
	  necessary because the ISV’s private key is typically not present on the build 
	  platform. This patch enables two-step signing support in graphene.

    The first step: Generate the signing material file.
    
    The signing material is signed at the signing facility using the private key.
    The signature file is taken back to the building system.
    
    The second step: Sign the enclave file using the signature file and public key.

    Added three parameters in sgx_sig.py:
    --mode "gendata" is for two-step signing to generate the signing material;
           "catsig" is for two-step signing to sign the enclave file using 
           the signature file and public key;
           "sign" is for one-step signing to sign the enclave file;
           The default mode is "sign", therefore one-step signing will be used 
           if mode is not specified.

    --sig  the signature file for the enclave signing material.
    --unsign the enclave signing material generated by "gendata".
    
</blockquote></details>

But why did you add the re-worked description here instead of changing the PR description itself? This is what Michal asked for. The PR description can be edited via GitHub's "Edit" button.

---

**Review by ying2liu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2528)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2528#-MeO_v0F7L0naN3UhGOK:-Mf-ZjOMCYXYKlAXeKMX:b-cz3knz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why did you add the re-worked description here instead of changing the PR description itself? This is what Michal asked for. The PR description can be edited via GitHub's "Edit" button.
</blockquote></details>

Sorry for the misunderstanding. I have changed the PR description.

---

**Comment by mkow** [comment]
This was superseded by https://github.com/gramineproject/gramine/pull/72, closing.

**Pull request closed without merging**
