### PR TITLE
[Pal/Linux-SGX] fix file_map() to not call ocall_mmap_untrusted() unn…

### PR DESCRIPTION
**Pull request by yamahata**
…ecessary

Some how file_map() is unnecessarily convoluted. sort it out.

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1324)

### CODE REVIEW

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 336 at r4](https://reviewable.io/reviews/oscarlab/graphene/1324#-MFXui-M8Z3V40Ke2jkr:-MFXui-N31VDtE3tNOJf:boivtj7) ([raw file](https://github.com/oscarlab/graphene/blob/d71d023dccf5a5333725c3253c81c934e8461e1b/Pal/src/host/Linux-SGX/enclave_ocalls.c#L336)):*
> ```C
>     }
> 
>     unsigned int done = 0;
> ```

```size_t done = 0;```

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 338 at r4](https://reviewable.io/reviews/oscarlab/graphene/1324#-MFXusvMCHPXwHwndbs9:-MFXusvMCHPXwHwndbsA:b-qfsb84) ([raw file](https://github.com/oscarlab/graphene/blob/d71d023dccf5a5333725c3253c81c934e8461e1b/Pal/src/host/Linux-SGX/enclave_ocalls.c#L338)):*
> ```C
>     unsigned int done = 0;
>     while (done < count) {
>         unsigned int copy = MIN(count - done, mmap_size);
> ```

```size_t copy = MIN(count - done, mmap_size);```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1324)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 336 at r4](https://reviewable.io/reviews/oscarlab/graphene/1324#-MFXui-M8Z3V40Ke2jkr:-MF_JPem3wvO1KQoI4q6:bzfwzh9) ([raw file](https://github.com/oscarlab/graphene/blob/d71d023dccf5a5333725c3253c81c934e8461e1b/Pal/src/host/Linux-SGX/enclave_ocalls.c#L336)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

```size_t done = 0;```
</blockquote></details>

(Some background: this PR was based on an older master which has `unsigned int count` in the function signature. Now it was fixed to have `size_t count`, so the size type needs to be changed here after rebase.)

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1324)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 234 at r4](https://reviewable.io/reviews/oscarlab/graphene/1324#-MHN58m90ymksqVCcO15:-MHN58m90ymksqVCcO16:be6oeyx) ([raw file](https://github.com/oscarlab/graphene/blob/d71d023dccf5a5333725c3253c81c934e8461e1b/Pal/src/host/Linux-SGX/db_files.c#L234)):*
> ```C
>             return unix_to_pal_error(ERRNO(ret));
>         }
>         if (map_size - ret > 0) {
> ```

I think it should return an error instead of setting remaining unfilled memory as 0 in this branch.

**Pull request closed without merging**
