### PR TITLE
[PAL] Fix initialization of variables sock_options in db_sockets.c (issue #674)

### PR DESCRIPTION
**Pull request by martinschmatz**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [X] Linux-SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Fixes (only partially) #674: Initializing variable `sock_options `to all zero, except `sock_options.reuseaddr`, which is initialized to 1. This for `tcp_connect`, `tcp_listen`, and `tcp_accept`, `udp_bind`, and `udp_connect `in `Pal/src/host/Linux-SGX/db_sockets.c`

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/776)

### CODE REVIEW

**Comment by martinschmatz** [comment]
OK, just so that I'm sure I understand what's proposed, here a reasoning for `tcp_connect(...)` (in `db_sockets.c`) as just one of the to-be-addressed items: 

1) `struct sockopt sock_options` remains uninitialized in `tcp_connect(...)` (in `db_sockets.c`)
2) The variable `sock_options` is then used in the call of `ocall_sock_connect`(...), which can be found in `enclave_ocalls.c`
3) in this `ocall_sock_connect(...)` function, the actual ocall is executed as `sgx_ocall(OCALL_SOCK_CONNECT, ms)` which is translated - via `sgx_ocall_fn_t ocall_table[OCALL_NR]` - to a call to `sgx_ocall_sock_connect(...)` found in `sgx_enclave.c`
4) `sgx_ocall_sock_connect(...) `is calling `sock_getopt(...)` which is therefore a potential interception point for doing the memset(0) and setting reuseaddr = 1.
5) Finally, back in ocall_soc_connect(..), the line `*sockopt = ms->ms_sockopt;` closes the procedure by updating `sockopt` with the initialized values

Because all of sgx_ocall_sock_XXXX (with XXXX = [connect | accept | listen]) are using a call to `sock_getopt(...)`, this is the place to intercept. 

Is the above description and reasoning of what is proposed correct? 

If so, how about INLINE_SYSCALLs to setsockopt that are made _before_ we ever reach sock_getopt? Will the setting of options changed via such syscalls remain unaffected by an initialization in `sock_getopt` (today and in the future when i.e. when `__do_setsockopt` is more fully implemented to for example include `SOL_IPV6`)?

**Comment by martinschmatz** [comment]
What I meant was that there are some `sockopt` actions triggered _before_ the code hits the `sock_getopt()` line. My question is: What happens with any changes made to the sockopts when the zeroing happens afterwards. 
As far as I could see, while such early sockopt actions are triggered, they are not actually implemented in the related 'catcher', hence nothing would actually be changed. But that might nevertheless mean that in the future, there could be a problem.  

Anyway: I'll follow your original suggestions to clean-up my PR to initialize the various `sock_options` variable a little bit and re-submit. I consider it anyway good practice to do such initialization right where the variable comes to life....

**Comment by martinschmatz** [comment]
@mkow 
Changed PR description as requested to exactly state "Fixes #674" so GitHub can parse it and automatically close the issue after mering this PR.

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (I'm not sure what failed, the logs has already got garbage-collected)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (OOM in `test_libos.TC_30_Syscall.test_52_large_mmap`, weird. Let's see if this happens more regularly)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (success, but I'll rerun Jenkins-SGX a few times to be sure it's stable)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (`test_libos.TC_00_Bootstrap.test_201_fork_and_exec` failed)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (success)

**Pull request closed without merging**
