### PR TITLE
Deprecate Ubuntu 16.04 LTS (xenial)

### PR DESCRIPTION
**Pull request by woju**
Ubuntu 16.04 goes EOL at the end of April 2021. We can remove the support for it.

Apart from CI pipelines, what else can we remove?

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnazo8pBNQCEVFKly:-MWfnazo8pBNQCEVFKlz:b-o2da95) (no related file):*
> [Ci]

Should be `[CI]`.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MWfnpPrC_bAu57OiM00:b-dmxant) (no related file):*
> Apart from CI pipelines, what else can we remove?

TODOlist:

- Update docs (just grep for 16.04)
- A lot of includes can be untangled (16.04 had old, buggy system headers) - grep for "16.04" around includes.
- https://github.com/oscarlab/graphene/blob/1f52e431262bab3769cbecbaeaff471dcdb6ef4e/python/graphenelibos/sgx_sign.py#L164-L165
- https://github.com/oscarlab/graphene/blob/1f52e431262bab3769cbecbaeaff471dcdb6ef4e/Examples/python-scipy/python.manifest.template#L90-L91
- Rewrite format strings in all Python scripts to f-strings (but that should be a separate PR).

There's probably much more to clean up in the C code which I forgot about, but I hope we'll recall such places gradually over time.

---

**Review by dimakuv — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MWhM5NL5E3IbQoNbmdu:brt1huv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Apart from CI pipelines, what else can we remove?

TODOlist:

- Update docs (just grep for 16.04)
- A lot of includes can be untangled (16.04 had old, buggy system headers) - grep for "16.04" around includes.
- https://github.com/oscarlab/graphene/blob/1f52e431262bab3769cbecbaeaff471dcdb6ef4e/python/graphenelibos/sgx_sign.py#L164-L165
- https://github.com/oscarlab/graphene/blob/1f52e431262bab3769cbecbaeaff471dcdb6ef4e/Examples/python-scipy/python.manifest.template#L90-L91
- Rewrite format strings in all Python scripts to f-strings (but that should be a separate PR).

There's probably much more to clean up in the C code which I forgot about, but I hope we'll recall such places gradually over time.
</blockquote></details>

You can also grep for `[Ubuntu16.04]` -- this pattern is used to add Ubuntu16.04-specific files to our Examples.

---

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MWhR_jb8PdrmtsBmeEa:b-aahzl5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can also grep for `[Ubuntu16.04]` -- this pattern is used to add Ubuntu16.04-specific files to our Examples.
</blockquote></details>

Well, just grep whole repo for `16.04`, there's not a lot of those.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MWhQvmu7eD6CqNaKkUc:b9ci0ln) (no related file):*
A lot of bugs triggered only on 16.04, so it would be good to have it on CI, but we don't want to keep EOLed ubuntu...
Let's just hope 20.04 brings more diversity and it will be enough.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 6 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnazo8pBNQCEVFKly:-MWkkbir-3DgjAYVH12E:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [Ci]

Should be `[CI]`.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MWipsrU0WHEBV5BSy8X:b8pxe5l) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A lot of bugs triggered only on 16.04, so it would be good to have it on CI, but we don't want to keep EOLed ubuntu...
Let's just hope 20.04 brings more diversity and it will be enough.
</blockquote></details>

If you like diversity, Ubuntu 18.04 vs 20.04 doesn't seem very different. I'd advise some RPM-based distro, like OpenSUSE or Rocky Linux when it's released in Q2. (Fedora is too unstable, CentOS was supposed to be stable, but recently it turned out it's not stable after all). I think this would be much easier after converting to meson.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 6 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MWykcOI5kjsAajMs_qo:bcejfg4) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you like diversity, Ubuntu 18.04 vs 20.04 doesn't seem very different. I'd advise some RPM-based distro, like OpenSUSE or Rocky Linux when it's released in Q2. (Fedora is too unstable, CentOS was supposed to be stable, but recently it turned out it's not stable after all). I think this would be much easier after converting to meson.
</blockquote></details>

I don't think that it matters that much: afaik the only thing that matters is compiler (gcc) version on the host (this depends on distro) and glibc version (we provide that, so distro does not matter).

---

**Review by dimakuv — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0q9qL-DqYLr2NIQfw:-MX0q9qL-DqYLr2NIQfx:bd3qnum) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L318)):*
> ```Python
> 
>     if len(matching) != 1:
>         raise KeyError(f'Could not find exactly one MemoryArea {desc!r}')
> ```

What is this `desc!r`?
___
*[python/graphenelibos/sgx_sign.py, line 481 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0qPx4-e9fEgvqlU8f:-MX0qPx4-e9fEgvqlU8g:b-wc7pet) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L481)):*
> ```Python
>             desc += ' measured'
> 
>         print(f'    {addr:016x}-{addr+size:016x} [{type}:{prot}] {desc}')
> ```

It should be `type_`

**Review by yamahata — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)

**Review by pwmarcz — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MXDHxjz992jgVBRunrh:b14as49) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, just grep whole repo for `16.04`, there's not a lot of those.
</blockquote></details>

I'm really looking forward to this change!

* Also grep for `3.5` for Python 3.5

* `Makefile.python` has `PYTHONVERSION=python3.5` as default. By the way, could this autodetect the system version (maybe by `readlink /usr/bin/python3`)? It was super annoying to constantly trip on this under Ubuntu 18.04, and whatever you put there as default, either Ubuntu 18.04 or Ubuntu 20.04 users are going to be annoyed.

* I just added a hack in `api.h` for Ubuntu 16, search for `glibc 2.23` (we don't *patch* glibc 2.23 anymore, but that's the version on 16.04 hosts).

---
___
*[python/graphenelibos/sgx_sign.py, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0q9qL-DqYLr2NIQfw:-MXDKS-RER0DWWxQALrL:bm2jdl9) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L318)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `desc!r`?
</blockquote></details>

This means `repr(desc)` (so that `desc` is printed quoted).

**Comment by woju** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXD_kkQCD3QLTNP8xZQ:b-rxv29t) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think that it matters that much: afaik the only thing that matters is compiler (gcc) version on the host (this depends on distro) and glibc version (we provide that, so distro does not matter).
</blockquote></details>

For the graphene proper, yes. For `Examples/` it's a little different, as there might be different paths to random things (like `/lib` vs `/lib64`).

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MXD_JQ03CQEhB416bYi:bgb36cf) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm really looking forward to this change!

* Also grep for `3.5` for Python 3.5

* `Makefile.python` has `PYTHONVERSION=python3.5` as default. By the way, could this autodetect the system version (maybe by `readlink /usr/bin/python3`)? It was super annoying to constantly trip on this under Ubuntu 18.04, and whatever you put there as default, either Ubuntu 18.04 or Ubuntu 20.04 users are going to be annoyed.

* I just added a hack in `api.h` for Ubuntu 16, search for `glibc 2.23` (we don't *patch* glibc 2.23 anymore, but that's the version on 16.04 hosts).
</blockquote></details>

`Makefile.python` is going away in #2288, and yes, Python version is being autodetected to the system-wide instance.

---
___
*[python/graphenelibos/sgx_sign.py, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0q9qL-DqYLr2NIQfw:-MX4mY_bCjR8Tfr5vTEL:b-sql9lp) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L318)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `desc!r`?
</blockquote></details>

`!r` means `repr()`. This is called "conversion", and there is also `!s` for `str()`. Conversion field is not to be confused with `:` field, which is "format spec" like `:20s`,`:#016x` or `:.0f`. See also: https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals.

`'"{}"'.format(str(variable))` (like previous version) is discouraged in Python because what if the variable contains `"`. We have `repr()` (or if you already are inside `format()`, even shorter `'{!r}'.format(...)`), which is easy to use and takes care of the nasty cases.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXDcqwk4STm4uIILgTf:b-wzlhmh) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For the graphene proper, yes. For `Examples/` it's a little different, as there might be different paths to random things (like `/lib` vs `/lib64`).
</blockquote></details>

How does different host path on some distros help with discovering Graphene bugs?

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 7 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWfnpPrC_bAu57OiM0-:-MXEDEzr3xNB0C5yTixg:b-9ywetk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`Makefile.python` is going away in #2288, and yes, Python version is being autodetected to the system-wide instance.
</blockquote></details>

I grepped for `3.5` and `2.23`. The hack from _FORTIFY_SOURCE is being reverted, but I'll leave Python 3.5 for now, because it will conflict with #2288 anyway.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXDk9aN7nsUcFWdss4b:b-209yhy) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How does different host path on some distros help with discovering Graphene bugs?
</blockquote></details>

Different paths affect manifest (sgx.{trusted,allowed}_files, fs.mount, entrypoint, ...). For example in #2288 I've removed a workaround for difference between debian and fedora (https://github.com/oscarlab/graphene/pull/2288/files#diff-84484e3d3895f6205484999f80813874e31d1d696f43149d5832e8b38f78d7fbL5-L15), and I've no tests for this

---
___
*[python/graphenelibos/sgx_sign.py, line 481 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0qPx4-e9fEgvqlU8f:-MXE7Lf_4ezO2UfPMGVp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L481)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It should be `type_`
</blockquote></details>

Done.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 7 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXEMxg82U2-BrUnI2nm:b-maupoa) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Different paths affect manifest (sgx.{trusted,allowed}_files, fs.mount, entrypoint, ...). For example in #2288 I've removed a workaround for difference between debian and fedora (https://github.com/oscarlab/graphene/pull/2288/files#diff-84484e3d3895f6205484999f80813874e31d1d696f43149d5832e8b38f78d7fbL5-L15), and I've no tests for this
</blockquote></details>

Again, what does that have to do with bugs in Graphene?

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 7 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXEf0gG0X0SMTdvlv81:b46qrk6) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Again, what does that have to do with bugs in Graphene?
</blockquote></details>

What do you mean by "Graphene"? If you limit it to Pal+LibOS, then as I already said, nothing. The problem is, our git repo contains also Examples, manifests and Makefiles. That's different story.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: 7 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2273#-MWhQvmt0XpXCi10BsYQ:-MXGrKF-9WkkbB4iGnUr:bnljvwv) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

What do you mean by "Graphene"? If you limit it to Pal+LibOS, then as I already said, nothing. The problem is, our git repo contains also Examples, manifests and Makefiles. That's different story.
</blockquote></details>

Are we still talking about having diversified hosts to increase code coverage? I do not consider an example not working due to wrong path in manifest a bug in Graphene. I get it - different distros can have different paths, that can be a pita to test, but that doesnt seem to be connected to finding bugs in any way.
I guess my comment was just a "it's a pitty that..." from the begining - closing this as there is nothing to discuss.

---

**Review by dimakuv — COMMENTED** [review]
> Reviewed 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[python/graphenelibos/sgx_sign.py, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/2273#-MX0q9qL-DqYLr2NIQfw:-MY46qhC5VlS7FdI6vGC:b-1hyf4m) ([raw file](https://github.com/oscarlab/graphene/blob/07545df6be76a4c62a38c861a4d4ef5f2479cca8/python/graphenelibos/sgx_sign.py#L318)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`!r` means `repr()`. This is called "conversion", and there is also `!s` for `str()`. Conversion field is not to be confused with `:` field, which is "format spec" like `:20s`,`:#016x` or `:.0f`. See also: https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals.

`'"{}"'.format(str(variable))` (like previous version) is discouraged in Python because what if the variable contains `"`. We have `repr()` (or if you already are inside `format()`, even shorter `'{!r}'.format(...)`), which is easy to use and takes care of the nasty cases.
</blockquote></details>

Thanks for explanations! Python changed a lot...

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 5 of 13 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2273)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
