### PR TITLE
Miscellaneous reference counting and epoll fixes

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Miscellaneous fixes, mostly in ref-counting and epoll areas. Refer to each commit message for the description

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (Example/gcc failed on hello.c with some null pointer deref in malloc (libpal.so); could not reproduce locally)

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/fs/shim_fs.c, line 493 at r6](https://reviewable.io/reviews/oscarlab/graphene/1763#-MEy9KUEEMvUpXktyZB0:-MEy9KUF5Gjz08TgOny-:b-h7wsu4) ([raw file](https://github.com/oscarlab/graphene/blob/be9975c1f3562ac39579cccd1959aaaa57b5ab50/LibOS/shim/src/fs/shim_fs.c#L493)):*
> ```C
> void get_mount(struct shim_mount* mount) {
>     __UNUSED(mount);
>     //REF_INC(mount->ref_count);
> ```

Would be better to show some debug message in case this function got visited.

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/fs/shim_fs.c, line 498 at r6](https://reviewable.io/reviews/oscarlab/graphene/1763#-MEy9blC-kY4OdlDDJWj:-MEy9blC-kY4OdlDDJWk:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/be9975c1f3562ac39579cccd1959aaaa57b5ab50/LibOS/shim/src/fs/shim_fs.c#L498)):*
> ```C
> void put_mount(struct shim_mount* mount) {
>     __UNUSED(mount);
>     //REF_DEC(mount->ref_count);
> ```

ditto

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 546 at r6](https://reviewable.io/reviews/oscarlab/graphene/1763#-MEyBOBoE6kB8Jfss2yK:-MEyBOBoE6kB8Jfss2yL:bi4sc57) ([raw file](https://github.com/oscarlab/graphene/blob/be9975c1f3562ac39579cccd1959aaaa57b5ab50/LibOS/shim/src/bookkeep/shim_handle.c#L546)):*
> ```C
>     handle_map->fd_size = size;
>     if (!create_lock(&handle_map->lock)) {
>         free(handle_map);
> ```

looks memory leak here, pls adding the following line before it to fixup.
```free(handle_map->map)```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, 6 of 6 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3Isjd5dGEfZ9Rp0KM:-MF3Isjd5dGEfZ9Rp0KN:b1i7xih) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L1)):*
>  [LibOS] Remove double checkpointing of thread->handle_map
> 
> Checkpointing `thread` checkpoints `thread->handle_map` automatically.

The commit message doesn't mention this change - should the change go into a separate commit or the commit message should be expanded?
___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3LYJQ1rcB0YrAhnWU:-MF3LYJQ1rcB0YrAhnWV:b-8sl7sl) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L40)):*
> ```C
>     } else if (pid == 0) {
>         char* arg[] = { argv[0], "xxx", NULL };
>         execv(argv[0], arg);
> ```

if this `execv` fails the whole test still succeeds

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3Isjd5dGEfZ9Rp0KM:-MF5Nvvz0OhY4CK-ueXh:bupgm6a) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  [LibOS] Remove double checkpointing of thread->handle_map
> 
> Checkpointing `thread` checkpoints `thread->handle_map` automatically.

The commit message doesn't mention this change - should the change go into a separate commit or the commit message should be expanded?
</blockquote></details>

This just adds a new test, that checks the buggy behavior fixed by the rest of the commit. Imo this does not deserve to be mentioned in the commit message.
___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3LYJQ1rcB0YrAhnWU:-MF5QpD87s1RwAkp7v_s:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

if this `execv` fails the whole test still succeeds
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r9, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3Isjd5dGEfZ9Rp0KM:-MF5jisdATYKZg36dhFU:b-i7jxd4) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This just adds a new test, that checks the buggy behavior fixed by the rest of the commit. Imo this does not deserve to be mentioned in the commit message.
</blockquote></details>

We usually mentioned such things in the commit message body. But I won't block on this.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)* status: 0 of 16 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/pipe_ocloexec.c, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1763#-MF3Isjd5dGEfZ9Rp0KM:-MF5rCvv19Jbj3B8O1g7:bnxb2po) ([raw file](https://github.com/oscarlab/graphene/blob/48401bee77cfab3c45fa643822e413b4871a463b/LibOS/shim/test/regression/pipe_ocloexec.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We usually mentioned such things in the commit message body. But I won't block on this.
</blockquote></details>

I've split the commit into two parts.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 3 files at r13, 5 of 7 files at r14, 2 of 2 files at r15, 4 of 4 files at r16, 3 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1763)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Pull request merged**
