### PR TITLE
Update tests in ltp.cfg which fail due to /proc access issues

### PR DESCRIPTION
**Pull request by jinengandhi-intel**
## Description of the changes 

Modified the tests in ltp.cfg which fail to access some file in /proc path. Few tests were already analyzed previously and had the right comments about the proc path it opens, this PR covers the tests which didn't have any such comments.
 

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2072#-MQlvFyaCdsE5xuO_P5p:-MQlvFybA3IASb4Ms51y:b6xvcs3) ([raw file](https://github.com/oscarlab/graphene/blob/42f545cd73c7bd94d375e85ef0d6f8a9c2f802e9/LibOS/shim/test/ltp/ltp.cfg#L174)):*
> ```INI
> 
> # no CLONE_NEWNET
> # opens /proc/sys/net/ipv4/conf/lo/tag
> ```

To be more precise, could you add "which we don't emulate"? Right now it's not clear why this opening is a problem.
Same to other "opens" lines here.

**Comment by jinengandhi-intel** [comment]
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)
> 
> _[LibOS/shim/test/ltp/ltp.cfg, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2072#-MQlvFyaCdsE5xuO_P5p:-MQlvFybA3IASb4Ms51y:b6xvcs3) ([raw file](https://github.com/oscarlab/graphene/blob/42f545cd73c7bd94d375e85ef0d6f8a9c2f802e9/LibOS/shim/test/ltp/ltp.cfg#L174)):_
> 
> > ```ini
> > # no CLONE_NEWNET
> > # opens /proc/sys/net/ipv4/conf/lo/tag
> > ```
> 
> To be more precise, could you add "which we don't emulate"? Right now it's not clear why this opening is a problem.
> Same to other "opens" lines here.

Michal I am not able to understand your comment. The original issue was for all the tests that are failing as we don't emulate the paths at /proc. The complete list of paths that are currently not emulated and result in test failures is already mentioned in the issue: https://github.com/oscarlab/graphene/issues/2068

Next you had asked me to specifically report which test requires which /proc path and that is what this PR is doing.

All we need is to add /proc paths which the LTP tests are using so that they don't fail with the "Failed to open file error" but proceed to actually running the test.

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2072#-MQlvFyaCdsE5xuO_P5p:-MQmBJma3NA8pTqJSRc1:bglfds4) ([raw file](https://github.com/oscarlab/graphene/blob/42f545cd73c7bd94d375e85ef0d6f8a9c2f802e9/LibOS/shim/test/ltp/ltp.cfg#L174)):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

Michal I am not able to understand your comment. The original issue was for all the tests that are failing as we don't emulate the paths at /proc. The complete list of paths that are currently not emulated and result in test failures is already mentioned in the issue: https://github.com/oscarlab/graphene/issues/2068

Next you had asked me to specifically report which test requires which /proc path and that is what this PR is doing.

All we need is to add /proc paths which the LTP tests are using so that they don't fail with the "Failed to open file error" but proceed to actually running the test.  
</blockquote></details>

To further add, adding all the necessary proc paths is increasing the pass rate by 12 tests and the rest proceed along and fail with logical test errors, which we again need to analyze and resolve if required.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2072#-MQlvFyaCdsE5xuO_P5p:-MQmS1or8IYLIAEdI0_l:bjggoqe) ([raw file](https://github.com/oscarlab/graphene/blob/42f545cd73c7bd94d375e85ef0d6f8a9c2f802e9/LibOS/shim/test/ltp/ltp.cfg#L174)):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

To further add, adding all the necessary proc paths is increasing the pass rate by 12 tests and the rest proceed along and fail with logical test errors, which we again need to analyze and resolve if required.  
</blockquote></details>

I mean replacing "opens /proc/sys/net/ipv4/conf/lo/tag" with "opens /proc/sys/net/ipv4/conf/lo/tag, which we don't emulate".

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2072)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2072#-MQlvFyaCdsE5xuO_P5p:-MSUasKmCktc-dMs5adJ:bzccvd3) ([raw file](https://github.com/oscarlab/graphene/blob/42f545cd73c7bd94d375e85ef0d6f8a9c2f802e9/LibOS/shim/test/ltp/ltp.cfg#L174)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean replacing "opens /proc/sys/net/ipv4/conf/lo/tag" with "opens /proc/sys/net/ipv4/conf/lo/tag, which we don't emulate".
</blockquote></details>

@jinengandhi-intel: Any updates on this?

**Comment by jinengandhi-intel** [comment]
We will relook at this once the FS related changes are merged to the master.

**Pull request closed without merging**
