### PR TITLE
[PAL] Remove `PAL_ERROR_ENDOFSTREAM`

### LINKED ISSUE #2078: [LibOS] fork() returns positive pid when child process fails to receive checkpoint
## Description of the problem
When very big enclave calls fork, sometimes it fail during sending/receiving checkpoint.

Using commit several months ago, the thread which calls fork() prints log `failed sending checkpoint (ret = -22)` and `return from shim_vfork(...) = -22`. Child process prints log `failed restoring checkpoint at vma (-22)`.

Now  child process prints log `failed restoring checkpoint at vma (-22)` but parent doesn't print any error log, fork() also return positive pid.

The case is 32G enclave running Java. Java uses Processbuilder(), it calls fork() then execve(). Here is a snap of log by `egrep "vfork|execve|checkpoint"`
```
[P2875:T2:java] ---- start time: 9481 ms shim_vfork() ... vfork
[P2875:T2:java] vfork was called by the application, implemented as an alias to fork in Graphene
[P2875:T2:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2875:T2:java] complete checkpointing data
[P2875:T2:java] checkpoint of 661152 bytes created
[P2931:java] checkpoint mapped at 0xfdffa0000-0xfe00416a0
[P2931:java] read checkpoint of 661152 bytes from parent
[P2931:java] restored memory from checkpoint
[P2931:java] restoring checkpoint at 0xfdffa0000 rebased from 0xfdffa0000
[P2931:T37:java] successfully restored checkpoint at 0xfdffa0000 - 0xfe00416a0
[P2875:T2:java] ---- end time: 113284 ms return from shim_vfork(...) = 37
[P2931:T37:java] ---- start time: 0 ms shim_execve("//setsid",[setsid,bash,-c,echo $$,],[LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu:/usr//lib/x86_64-linux-gnu:/opt/jdk8:/opt/jdk8/lib/amd64/jli,PATH=/:/opt/jdk8/bin:/usr/sbin:/usr/bin:/sbin:/bin,]) ... execv[P2931:T37:java] e
[P2931:T37:java] execve() in a new process
[P2931:T37:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2931:T37:java] complete checkpointing data
[P2931:T37:java] checkpoint of 27432 bytes created
[P2933:setsid] checkpoint mapped at 0xb26f000-0xb275b28
[P2933:setsid] read checkpoint of 27432 bytes from parent
[P2933:setsid] restored memory from checkpoint
[P2933:setsid] restoring checkpoint at 0x0b26f000 rebased from 0xfe03df000
[P2931:T37:setsid] successfully restored checkpoint at 0x0b26f000 - 0x0b275b28
[P2931:T37:java] Temporary process 2931 is exiting after emulating execve (by forking new process to replace this one); will wait for forked process to exit...
[P2875:T73:java] ---- start time: 391583 ms shim_vfork() ... vfork
[P2875:T73:java] vfork was called by the application, implemented as an alias to fork in Graphene
[P2875:T73:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2758 -> 0xfdff21268 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2a58 -> 0xfdff21bc8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2158 -> 0xfdff222f0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3058 -> 0xfdff22a18 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff34d8 -> 0xfdff23140 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3958 -> 0xfdff23868 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3dd8 -> 0xfdff23f90 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff4258 -> 0xfdff246b8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff46d8 -> 0xfdff24de0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff4b58 -> 0xfdff25740 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f290d8 -> 0xfdff25e68 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f29558 -> 0xfdff26590 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f299d8 -> 0xfdff26cb8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f29e58 -> 0xfdff273e0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2a2d8 -> 0xfdff27b08 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2a758 -> 0xfdff28230 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2bad8 -> 0xfdff29b20 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2bf58 -> 0xfdff2a248 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2c3d8 -> 0xfdff2a970 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2c858 -> 0xfdff2b098 (base = 0xfdfe54000)
[P2875:T73:java] complete checkpointing data
[P2875:T73:java] checkpoint of 958080 bytes created
[P3013:java] checkpoint mapped at 0xfdfe54000-0xfdff3de80
[P3013:java] read checkpoint of 958080 bytes from parent
[P3013:java] restored memory from checkpoint
[P3013:java] restoring checkpoint at 0xfdfe54000 rebased from 0xfdfe54000
[P3013:java] failed restoring checkpoint at vma (-22)
[P3013:java] Error during shim_init() in receive_checkpoint_and_restore (-22)
[P2875:T73:java] ---- end time: 519935 ms return from shim_vfork(...) = 74
```
First successful fork from `[P2875:T2:java]` created `[P2931:java]`, whose pid is 37.
Second failed fork from `[P2875:T73:java]` created `[P3013:java]`. It failed to receive checkpoint, but parent still returns 74.

I also added more log to catch this error. It come from `read_exact` in shim_checkpoint.c. `read` over socket returns EINVAL.

I also added time stamp to track fork time. I can send you the full log if necessary.

### LINKED ISSUE #2131: [LibOS] Incorrect behavior of recv() with MSG_PEEK flag on ended stream
## Description of the problem
behavior of `recv()` with `MSG_PEEK` flag on ended stream are incorrect on Graphene.

## Steps to reproduce
duplicate the three line in `tcp_msg_peek.c` to recv() with PSG_PEEK twice.
https://github.com/oscarlab/graphene/blob/cf0bfdf67a44473a6a463a48d96ad339dd8173ee/LibOS/shim/test/regression/tcp_msg_peek.c#L177-L179
Run this test without and with Graphene.

## Expected results
```
./tcp_msg_peek
[server] client is connected...
[server] done
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving without MSG_PEEK: Hello from server!
[client] checking how many bytes are left unread: 0
[client] done
```

## Actual results
```
 ./pal_loader tcp_msg_peek
[server] client is connected...
[server] done
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving 0 bytes with MSG_PEEK: [client] receiving without MSG_PEEK: [client] checking how many bytes are left unread: 0
[client] done
```
 ## Additional information
This root cause of this issue is pal error code `PAL_ERROR_ENDOFSTREAM` is not handled correctly at
https://github.com/oscarlab/graphene/blob/cf0bfdf67a44473a6a463a48d96ad339dd8173ee/LibOS/shim/src/sys/shim_socket.c#L1319-L1327

It's similar to #2078.  Maybe we need to review all `DkStreamRead` usage.

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
`PAL_ERROR_ENDOFSTREAM` was and error returned e.g. on end-of-file. Now
such case is denoted by returning `0` instead. All the previous code did
was just if around `PAL_ERROR_ENDOFSTREAM` everywhere and change it to
`0` and PAL actually just checked for `0` being returned from its
internal (including host-specific) functions and change it to
`PAL_ERROR_ENDOFSTREAM`.

Closes #2137
Fixes #2078, fixes #2131

Thanks to @llly for finding and debugging the issue.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MTwXTOF09hU2_ngZGN6:-MTwXTOGEs2gWR1WWdEp:b-t28lhg) (no related file):*
> `PAL_ERROR_ENDOFSTREAM` was and error returned

Typo? (`and` -> `an`)

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MTwXTOF09hU2_ngZGN6:-MTwklExCOQZhzGDk8u8:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `PAL_ERROR_ENDOFSTREAM` was and error returned

Typo? (`and` -> `an`)
</blockquote></details>

Done.

---

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by llly** [comment]
Does this PR resolve same issue in #2137 and close #2137?
Is yes, please also review the files that changed in that PR. Some loop logic 
```
    while (bytes < size) {
        PAL_NUM x = DkStreamRead(handle, 0, size - bytes, (char*)buf + bytes, NULL, 0);
        if (x == PAL_STREAM_ERROR) {
            /* more error handling*/
            return -err;
        }
        bytes += x;
    }
```
causes dead loop since 0 instead of `PAL_STREAM_ERROR`  is returned in this PR.

see
https://github.com/oscarlab/graphene/blob/ab4db92639677d25ae72552dbcc1760145d8226a/Pal/src/db_streams.c#L324-L329

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU81f6D6mK2fQYudWt-:-MU81f6D6mK2fQYudWt0:bfbvv99) (no related file):*
+1 to @llly's request. This PR does *not* fix #2137, but is related to it. @boryspoplawski Could you incorporate the changes from that PR in this one (I guess it will be simpler than to merge two PRs)?

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 1 unresolved discussion (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU81f6D6mK2fQYudWt-:-MU8nUJ9EMXQ6L6fZkFh:b-mhn863) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @llly's request. This PR does *not* fix #2137, but is related to it. @boryspoplawski Could you incorporate the changes from that PR in this one (I guess it will be simpler than to merge two PRs)?
</blockquote></details>

Well, I can add another commit here, but tbh those changes look unrelated.

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 1 unresolved discussion (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU81f6D6mK2fQYudWt-:-MU8qFgZ14glmQRpUnRp:bi7hqvk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I can add another commit here, but tbh those changes look unrelated.
</blockquote></details>

I would prefer to add a commit to this PR. It's just gonna be quicker this way.

---

**Review by boryspoplawski — COMMENTED** [review]
@llly it did not resolve the same issue, but I've fixed it now, as requested.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176#-:-MU9AN8ND4pe7vd3cVv8:bc16mpm)* status: 14 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @llly, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU81f6D6mK2fQYudWt-:-MU9ATR4CfcXulMGT-oT:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to add a commit to this PR. It's just gonna be quicker this way.
</blockquote></details>

Done.

---

**Review by dimakuv — DISMISSED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU81f6D6mK2fQYudWt-:-MU9CHo07CEFuAcHW3dR:bf48ck4) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Now also `shim_socket.c` doesn't need changes because it naturally covers the `pal_ret == 0` case, nice!

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_internal.h, line 298 at r3](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU9GTOr9DKvYjFdznn_:-MU9GTOr9DKvYjFdznna:b-6fhxpg) ([raw file](https://github.com/oscarlab/graphene/blob/c7602e06168bfe160cf6fa246cd3229cd8785320/LibOS/shim/include/shim_internal.h#L298)):*
> ```objc
>             return -err;
>         } else if (n == 0) {
>             /* This should not happen, since we polled above  ... */
> ```

No spaces after "above" (please also fix the previous comment which you copied here)
___
*[LibOS/shim/test/regression/tcp_msg_peek.c, line 182 at r3](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU9HtbA8msYjAtw5Q1l:-MU9HtbA8msYjAtw5Q1m:bfutn6j) ([raw file](https://github.com/oscarlab/graphene/blob/c7602e06168bfe160cf6fa246cd3229cd8785320/LibOS/shim/test/regression/tcp_msg_peek.c#L182)):*
> ```C
> 
>     printf("[client] receiving with MSG_PEEK again: ");
>     count = client_recv(server_socket, buffer, sizeof(buffer), MSG_WAITALL | MSG_DONTWAIT | MSG_PEEK);
> ```

please wrap

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: 18 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 298 at r3](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU9GTOr9DKvYjFdznn_:-MU9lge91yUq2dCtU9Ke:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c7602e06168bfe160cf6fa246cd3229cd8785320/LibOS/shim/include/shim_internal.h#L298)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No spaces after "above" (please also fix the previous comment which you copied here)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_msg_peek.c, line 182 at r3](https://reviewable.io/reviews/oscarlab/graphene/2176#-MU9HtbA8msYjAtw5Q1l:-MU9lhCRAXh3GvndEAyf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c7602e06168bfe160cf6fa246cd3229cd8785320/LibOS/shim/test/regression/tcp_msg_peek.c#L182)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 6 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2176)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
