### PR TITLE
[Documentation] Add PyTorch tutorial

### PR DESCRIPTION
**Pull request by dayeol**
## Description of the changes 

Add "Tutorials" section in Documentation and add PyTorch Machine Learning tutorial.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1731)

### CODE REVIEW

**Comment by dimakuv** [comment]
___
*[Documentation/conf.py, line 51 at r2](https://reviewable.io/reviews/oscarlab/graphene/1731#-MEO3c3S4Z6b5YfT-dfk:-MEOKTdN50ElWYXmmZTD:bwjwlnd) ([raw file](https://github.com/oscarlab/graphene/blob/4bdc4711a7b14c77b8aa34fa60d761f177389050/Documentation/conf.py#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the purpose of this new option?
</blockquote></details>

This option was needed for a single `ref:` reference to a plain title. I'm removing that reference, so we don't need this option here too.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dayeol** [comment]
Thank you for taking this over. Looks great!

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1731)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dayeol)

___
*[Documentation/tutorials/pytorch/index.rst, line 48 at r5](https://reviewable.io/reviews/oscarlab/graphene/1731#-MEcgUfa0d9pJST269XG:-MFX46rSDOOoE92Iqw2l:bfhqmln) ([raw file](https://github.com/oscarlab/graphene/blob/0c228ef3d2b8196be0b8eaa8194f7e6a8b21830b/Documentation/tutorials/pytorch/index.rst#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not done?
___
*[Documentation/tutorials/pytorch/index.rst, line 239 at r5](https://reviewable.io/reviews/oscarlab/graphene/1731#-MEcwCAOEQw10285H3m5:-MFX4jJv5NwwmXDUktJG:b32vhw) ([raw file](https://github.com/oscarlab/graphene/blob/0c228ef3d2b8196be0b8eaa8194f7e6a8b21830b/Documentation/tutorials/pytorch/index.rst#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. This was actually American-style "sentence in brackets", but I also prefer Russian/Polish version.
</blockquote></details>

:)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1731)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dayeol)

___
*[Documentation/tutorials/pytorch/index.rst, line 48 at r5](https://reviewable.io/reviews/oscarlab/graphene/1731#-MEcgUfa0d9pJST269XG:-MF_Ft4m2A2n2QQYJAbu:bl0i47z) ([raw file](https://github.com/oscarlab/graphene/blob/0c228ef3d2b8196be0b8eaa8194f7e6a8b21830b/Documentation/tutorials/pytorch/index.rst#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought that was just a prelude to your next comment ("can you increase fonts") :) Yes, I have the sources, this is a pptx file (MS Power Point). Do you want to add this file here?
</blockquote></details>

Ouch. Hoped you used something better ;) Is there a way to export a single image from PowerPoint to some portable format? (e.g. svg)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1731)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/tutorials/pytorch/index.rst, line 48 at r5](https://reviewable.io/reviews/oscarlab/graphene/1731#-MEcgUfa0d9pJST269XG:-MFbW0gGCX6rGfTifOAN:b1lzchj) ([raw file](https://github.com/oscarlab/graphene/blob/0c228ef3d2b8196be0b8eaa8194f7e6a8b21830b/Documentation/tutorials/pytorch/index.rst#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Now I understood you. So we should enforce SVG format in our documentation (if possible).
</blockquote></details>

Anything which is possible to edit later (without pinging you personally to do the change) should do the work. Also, files in vector formats are much smaller than raster.
Anyways, looks good now :)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1731)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
