### PR TITLE
Properly report the remaining time on the last alarm (fix #93)

### LINKED ISSUE #93: alarm() does not cancel/reset outstanding alarms
https://github.com/oscarlab/graphene/blob/26eae52106d87418e161aafc6199ebbcc9cfe149/LibOS/shim/src/sys/shim_alarm.c#L46

The current implementation does not handle the case where installing a new alarm cancels a previous alarm nor does it indicate whether there was a previous alarm (via the return value). This breaks, for example, libresolv, which uses alarms to detect DNS query timeouts (I believe, haven't looked into the source of libresolv).

### PR DESCRIPTION
**Pull request by donporter**
The alarm system call was not properly returning the number of seconds remaining on the last alarm.  This patch fixes that, addressing issue #93).  

The alarm03, alarm05, and alarm06 LTP tests are good unit tests for this issue - add them to the list expected to pass.

### CODE REVIEW

**Comment by donporter** [comment]
Run with tip of this branch (11/19)

---
- [x] Describe the testing setup:
  - [x] **Code version:** branch fix-93
  - [x] **Linux kernel version:** 4.4.0-98-generic
  - [x] **Ubuntu version:** 16.04.03 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@cdf563
  - [x] **SGX driver version:** 01org/linux-sgx-driver@e3e42d4
---
- [x] **PAL**
  - [x] **Linux host**
    - [ ] **Compilation:** passed
    - [ ] **Regression tests:** all passed
  - [x] **Linux+SGX host**
    - [ ] **Compilation:** passed
    - [ ] **Regression tests:** 
---
- [x] **Library OS**
    - [ ] **Compilation:** passed
    - [ ] **Linux host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** 
    - [ ] **Linux-SGX host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** Not fully supported yet
---
- [ ] **Applications**
    - [x] **Linux host**
      - [ ] **LMBench:** 
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** 
      - [ ] **Apache:** 
      - [ ] **Python:** 
    - [ ] **Linux-SGX host**
      - [ ] **LMBench:** lat_proc shell gets a segmentation fault.  lat_tcp, bw_tcp 127.0.0.1 gets permission denied messages in connect; bw_pipe has an occasional failure with the signal queue overflowing (same problems observed on master), an occasional vma assertion blows.  - generally, pretty flaky on SGX, but not necessarily different than master.
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** Fails with memory allocation issue (same on master)
      - [ ] **Apache:**
      - [ ] **Python:**

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by donporter** [comment]
ok to test

**Comment by donporter** [comment]
Run with tip of this branch (12/10) - SGX only

---
- [x] Describe the testing setup:
  - [x] **Linux kernel version:** 4.4.0-98-generic
  - [x] **Ubuntu version:** 16.04.03 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@cdf563
  - [x] **SGX driver version:** 01org/linux-sgx-driver@e3e42d4
---
- [x] **PAL**
  - [x] **Linux+SGX host**
    - [x] **Compilation:** passed
    - [ ] **Regression tests:** 
---
- [x] **Library OS**
    - [x] **Compilation:** passed
    - [ ] **Linux-SGX host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** Not fully supported yet
---
- [ ] **Applications**
    - [ ] **Linux-SGX host**
      - [ ] **LMBench:** 
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** 
      - [ ] **Apache:**
      - [ ] **Python:**

**Pull request merged**
