### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by yamahata**
This patch series is a collection of various minor fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/271)

### CODE REVIEW

**Comment by chiache** [comment]
@yamahata First of all, thanks for the fixes! We appreciate your contribution to the project.

Before we start reviewing, I would like to ask you to add some more explanations to the pull requests. What are the problems it is fixing? How does it fix them?

**Comment by yamahata** [comment]
@chiache the each commit includes commit message which explains the issue (and fixes). 
I sites here for your convenience. They are almost obvious fixes.
-  Linux-SGX: sgx_framework.c doesn't compile
   => trivial compilation fix
- LibOS/shim/src/fs/shim_namei.c: comparison pointer with char
  compiler warning. obvious fix
- sys/shim_epoll.c: warning: redefined symbo
  trivial compilation fix
- shim_types.h: __kernel_timespec, __kernel_itimerspec
   doesn't compile with linux 4.18.0+. ifdef magic with linux kernel version
- LibOS/shim/src/ipc/shim_ipc_nsimpl.h: add missing accounting of nowned/noffered
  added proper accounting
- ipc/shim_ipc_nsimpl.h: __discover_ns: missing lock
  lock added.
- lookup_and_alloc_client(): race condition
  removed unnecessary unlock/lock
- atomic.h: add atomic_inc_return, atomic_add_return
  added atomic_inc/add_return and used it.
- LibOS/shim/src/shim_checkpoint.c: retry DkStreamRead/DkStreamWrite
  added retry logic.

**Comment by donporter** [comment]
At a high level, this is may be better split into multiple, smaller PRs - one per issue.  But I'll still go ahead and review the changes.

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Just to confirm, the plan is that you are going to/have opened new PRs for each individual issue?

**Comment by yamahata** [comment]
As I created small PRs for each patch, this PR becomes unnecessary.

**Pull request closed without merging**
