### PR TITLE
update sgx install doc link

### PR DESCRIPTION
**Pull request by rahulunair**
Signed-off-by: Unnikrishnan Nair, Rahul <rahulunair@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2240)

### CODE REVIEW

**Comment by rahulunair** [comment]
created a new PR for #2216, with the updates as required from review

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2240)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @rahulunair)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2240#-MVrc8Py3DSy-O_M39us:-MVrc8Py3DSy-O_M39ut:bcadchb) (no related file):*
The commit message will need an update to conform to our conventions (see https://graphene.readthedocs.io/en/latest/devel/contributing.html), but we can do this ourselves when rebasing.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2240)* status: all files reviewed, 1 unresolved discussion (waiting on @rahulunair)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2240)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2240)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
