### PR TITLE
[Pal/Linux] Move pal_linux_defs.h under Pal/Linux and remove its macros

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, `pal_linux_defs.h` was located in a common include dir, though it was only used by Linux PAL (Linux-SGX PAL has its own and very different version of this header). This PR moves this header under `Pal/Linux` and performs a cleanup of its macros without logic changes.

A couple other tiny cleanups is done as part of this PR:
- moving x86-64 non-SGX instruction wrappers into `cpu.h`,
- renaming `USER_ADDRESS_LOWEST` to `DEFAULT_HEAP_MIN` for consistency with Linux-SGX,
- removing redundant `_DkSystemTimeQueryEarly()`,
- increasing `THREAD_STACK_SIZE` from 8KB to 64KB (to be on the safe side).

Closes #1479.

## How to test this PR? 

All tests must pass, no logical changes.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/include/arch/x86_64/cpu.h, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA5otT1xB4avXbqy0x:-MPA5otT1xB4avXbqy0y:bmda1nj) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/include/arch/x86_64/cpu.h#L64)):*
> ```objc
>     __asm__ volatile(
>         ".byte 0xf3, 0x48, 0x0f, 0xae, 0xd7\n" /* WRFSBASE %RDI */
>         :: "D"(addr));
> ```

Please add a "memory" clobber here.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 223 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA9Bea6MWLJzmGB_UI:-MPA9Bea6MWLJzmGB_UJ:b-2ovu22) ([raw file](https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/Pal/src/host/Linux/db_main-x86_64.c#L223)):*
> ```C
> 
> #if USE_ARCH_RDRAND == 1
> int _DkRandomBitsRead(void* buffer, size_t size) {
> ```

Does it mean we do not use `rdrand()` anymore (on non-SGX Linux Pal)?
UPDATE: Ok, we never did.
___
*[Pal/src/host/Linux/pal_linux_defs.h, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA8XBq1NJIhUi2nN2L:-MPA8XBq1NJIhUi2nN2M:b-17paap) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/src/host/Linux/pal_linux_defs.h#L5)):*
> ```objc
> 
> /* default heap base cannot start at zero (modern OSes do not allow this) */
> #define DEFAULT_HEAP_MIN 0x10000
> ```

Tbh I don't like the name - heap is so overloaded name. (Is it brk? Is it what `malloc` returns? Is it just all memory?)
___
*[Pal/src/host/Linux/pal_linux_defs.h, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPAAD6c6rR0-hshPxxD:-MPAAD6c6rR0-hshPxxE:bre68z1) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/src/host/Linux/pal_linux_defs.h#L7)):*
> ```objc
> #define DEFAULT_HEAP_MIN 0x10000
> 
> #define THREAD_STACK_SIZE (PRESET_PAGESIZE * 16) /* 64KB user stack */
> ```

What's the point of increasing the stack size? Did something fail due to it?
Note this stack is almost never used - user app provides it's own stack on clone and the initial thread allocates it's stack too.

**Review by yamahata — APPROVED** [review]
except Borys comment, it looks good to me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037#-:-MPAtjnw3c5mhRcSkTU5:b7rrcar)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Review by yamahata — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: 12 of 21 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/include/shim_defs.h, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPE3pkfBq7gz-JGfmDB:-MPE3pkfBq7gz-JGfmDC:b-ij69s8) ([raw file](https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/LibOS/shim/include/shim_defs.h#L7)):*
> ```objc
> 
> #define DEFAULT_HEAP_MIN_SIZE  (256 * 1024 * 1024) /* 256MB */
> #define DEFAULT_MEM_MAX_NPAGES (1024 * 1024)       /* 4GB */
> ```

FYI: Accidentally stumbled on these two unused macros, decided to remove them as well (as a separate commit)
___
*[Pal/include/arch/x86_64/cpu.h, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA5otT1xB4avXbqy0x:-MPDzVtg-DBCotovnV0F:bt787j2) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/include/arch/x86_64/cpu.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a "memory" clobber here.
</blockquote></details>

Done in both WRFSBASE and RDFSBASE (also see how Linux does it: https://lore.kernel.org/lkml/20181023184234.14025-1-chang.seok.bae@intel.com/T/ and https://lkml.org/lkml/2020/8/4/208). Good catch, thanks.
___
*[Pal/src/host/Linux/pal_linux_defs.h, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA8XBq1NJIhUi2nN2L:-MPE-YNYEuaMNWA0soFf:b-s5c9t) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/src/host/Linux/pal_linux_defs.h#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Tbh I don't like the name - heap is so overloaded name. (Is it brk? Is it what `malloc` returns? Is it just all memory?)
</blockquote></details>

Ok. I changed to `MMAP_MIN_ADDR` (same name as the Linux kernel tunable https://wiki.debian.org/mmap_min_addr). I also changed it in Linux-SGX PAL (that's where I took this `DEFAULT_HEAP_MIN` originally).
___
*[Pal/src/host/Linux/pal_linux_defs.h, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPAAD6c6rR0-hshPxxD:-MPDzvSZ3eb63wdfnvuy:b-7p3qgn) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/src/host/Linux/pal_linux_defs.h#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of increasing the stack size? Did something fail due to it?
Note this stack is almost never used - user app provides it's own stack on clone and the initial thread allocates it's stack too.
</blockquote></details>

Nothing failed due to it, but we'd like to be on the safe side. And it just looks weird that the user-stack size is less than the alternate-stack size, so I made them at least the same. Doesn't hurt. I would prefer to keep it like this.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/arch/x86_64/cpu.h, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA5otT1xB4avXbqy0x:-MPELPBgB5y6oPuCZwFt:b-zgncbm) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/include/arch/x86_64/cpu.h#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done in both WRFSBASE and RDFSBASE (also see how Linux does it: https://lore.kernel.org/lkml/20181023184234.14025-1-chang.seok.bae@intel.com/T/ and https://lkml.org/lkml/2020/8/4/208). Good catch, thanks.
</blockquote></details>

Tbh I'm not convinced that we need "memory" clobber in rdfsbase, but I'm willing to accept the negligible cost of it :)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

**Review by mkow — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 4 of 9 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[Pal/include/arch/x86_64/cpu.h, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2037#-MPA5otT1xB4avXbqy0x:-MPFP36lBpBK1KZjk-Zg:b-hpgre3) ([raw file](https://github.com/oscarlab/graphene/blob/22d13fc50aff75fbfb9fc5cbc60526bc00ec4d15/Pal/include/arch/x86_64/cpu.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Tbh I'm not convinced that we need "memory" clobber in rdfsbase, but I'm willing to accept the negligible cost of it :)
</blockquote></details>

Definitely not needed there, but whatever.

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2037)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
