### PR TITLE
[LibOS] Implement getrandom syscall

### LINKED ISSUE #1829: Implement getrandom syscall
## Description of the problem

TensorFlow uses `getrandom()`, would be nice to have + it's trivial to implement.

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Fixes #1829.

## How to test this PR? 

LTP tests enabled in this PR should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-V2be6Kk-wnkHQnyO:-MI-V2be6Kk-wnkHQnyP:b-e0rvaz) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
> ```objc
>  * build machine.
>  */
> #ifndef __NR_copy_file_range
> ```

Why do you start with exactly this syscall (326)? Why are these needed in Graphene?
___
*[LibOS/shim/src/sys/shim_getrandom.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-XB1V5kNrTl7vRBPP:-MI-XB1V5kNrTl7vRBPQ:b-fbze29) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L28)):*
> ```C
>     int ret = DkRandomBitsRead(buf, count);
>     if (ret < 0)
>         return -convert_pal_errno(-ret);
> ```

I'm not sure we want to return an error code from Pal. Maybe just `-EINVAL`?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-iobl9spQNCEn2HIW:-MI-iobm3gJBEU2nepT7:b82f67m) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
> ```objc
>  * build machine.
>  */
> #ifndef __NR_copy_file_range
> ```

These defines should go into arch dependent file.
___
*[LibOS/shim/src/sys/shim_getrandom.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-wZ_fABcfeXvilsUt:-MI-wZ_fABcfeXvilsUu:b-2av7vp) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L26)):*
> ```C
>         return -EFAULT;
> 
>     int ret = DkRandomBitsRead(buf, count);
> ```

This can block on Pal-Linux if `USE_ARCH_RD_RAND` is not defined, which might conflict with `GRND_NONBLOCK`.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: 4 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-V2be6Kk-wnkHQnyO:-MI05LPX6S-4ncBiagSV:b-6o8o97) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you start with exactly this syscall (326)? Why are these needed in Graphene?
</blockquote></details>

Because this is the first one missing on Ubuntu 16.04 (which we still declare to support). I'd like to finally start migrating the headers to our repo, this is getting increasingly annoying.
___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-iobl9spQNCEn2HIW:-MI067r03QWGEp-of1VG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These defines should go into arch dependent file.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_getrandom.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-wZ_fABcfeXvilsUt:-MI07nEy9MJvA-G9Ey8J:b-v7gdry) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This can block on Pal-Linux if `USE_ARCH_RD_RAND` is not defined, which might conflict with `GRND_NONBLOCK`.
</blockquote></details>

It reads from `/dev/urandom`, so in practice it can't block. Also, current PAL API doesn't even support non-blocking random read, so I'd rather leave this as is.
___
*[LibOS/shim/src/sys/shim_getrandom.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-XB1V5kNrTl7vRBPP:-MI07WGR2gxFSGhun0f2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure we want to return an error code from Pal. Maybe just `-EINVAL`?
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_getrandom.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-wZ_fABcfeXvilsUt:-MI1Y3UZEm2jf4F2aZZc:b-dtylxo) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It reads from `/dev/urandom`, so in practice it can't block. Also, current PAL API doesn't even support non-blocking random read, so I'd rather leave this as is.
</blockquote></details>

In theory it can block (e.g. on a vm, without some random source forwarded from host, entropy poll initialization might take some time).
I'm not blocking on this, but maybe add a comment about it (that in practice it does not happen and we dont really care)?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_getrandom.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-wZ_fABcfeXvilsUt:-MI1aO1Q68Q-LF88JqXQ:b-y2yw10) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/src/sys/shim_getrandom.c#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In theory it can block (e.g. on a vm, without some random source forwarded from host, entropy poll initialization might take some time).
I'm not blocking on this, but maybe add a comment about it (that in practice it does not happen and we dont really care)?
</blockquote></details>

Sure, added a comment.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-V2be6Kk-wnkHQnyO:-MI35_aYD7r0-WFqb8yq:b-urhenv) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because this is the first one missing on Ubuntu 16.04 (which we still declare to support). I'd like to finally start migrating the headers to our repo, this is getting increasingly annoying.
</blockquote></details>

OK. That's hacky, but since we're migrating to in-Graphene headers, ok for now.
___
*[LibOS/shim/include/shim_table.h, line 544 at r3](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI36EETBCfT0u4Cc6Tt:-MI36EETBCfT0u4Cc6Tu:b-d6a94i) ([raw file](https://github.com/oscarlab/graphene/blob/94b2ed09a19d4f2493046a278332b0c3c9c5054f/LibOS/shim/include/shim_table.h#L544)):*
> ```objc
> #define GRND_NONBLOCK 0x0001
> #define GRND_RANDOM   0x0002
> #define GRND_INSECURE 0x0004
> ```

I don't think these macros belong in this header. But not blocking since we want to migrate to in-Graphene ones.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_table.h, line 546 at r1](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI-V2be6Kk-wnkHQnyO:-MI39qmq8Uh2gyhfBG7I:bvn2yhv) ([raw file](https://github.com/oscarlab/graphene/blob/7050380fb3ad0b4a6061d91a80fe205ec2086710/LibOS/shim/include/shim_table.h#L546)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. That's hacky, but since we're migrating to in-Graphene headers, ok for now.
</blockquote></details>

Yeah, but the only non-hacky solution is to finally create our own headers for everything. This will also resolve the annoying conflicts in header defines we have now (which trigger when you try to sort includes in some files)
___
*[LibOS/shim/include/shim_table.h, line 544 at r3](https://reviewable.io/reviews/oscarlab/graphene/1838#-MI36EETBCfT0u4Cc6Tt:-MI3A6Lw8zmEAz8yo9o7:b-m5xvfz) ([raw file](https://github.com/oscarlab/graphene/blob/94b2ed09a19d4f2493046a278332b0c3c9c5054f/LibOS/shim/include/shim_table.h#L544)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think these macros belong in this header. But not blocking since we want to migrate to in-Graphene ones.
</blockquote></details>

Yup, we'll move them later anyways.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1838)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
