### PR TITLE
[Pal/Linux-SGX] Remove SGX_DBG

### PR DESCRIPTION
**Pull request by pwmarcz**
Replace the old SGX_DBG macro with new subsystem (log_* inside
enclave, urts_log_* outside enclave).

Adjust log levels of some messages, and remove some unnecessary
ones.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_6k3L5VxS6Y1-TngW:-MR_6k3L5VxS6Y1-TngX:b-6qyuki) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_files.c#L94)):*
> ```C
>         if (pf_mode & PF_FILE_MODE_WRITE) {
>             if (pf->writable_fd >= 0) {
>                 log_debug("file_open(%s): disallowing concurrent writable handle\n", path);
> ```

This was a bug. Should be `log_error`.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 331 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_6tCW8MO-tyZYWJfe:-MR_6tCW8MO-tyZYWJff:b214vse) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_files.c#L331)):*
> ```C
>     assert(WITHIN_MASK(prot, PAL_PROT_MASK));
>     if ((prot & PAL_PROT_READ) && (prot & PAL_PROT_WRITE)) {
>         log_info("pf_file_map(PF fd %d): trying to map with R+W access\n", fd);
> ```

`log_error`
___
*[Pal/src/host/Linux-SGX/db_process.c, line 282 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_7OzV3c_FDxkEvIev:-MR_7OzW8FSIpGfqWyzM:b-cw0fdo) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_process.c#L282)):*
> ```C
> noreturn void _DkProcessExit(int exitcode) {
>     if (exitcode)
>         log_info("DkProcessExit: Returning exit code %d\n", exitcode);
> ```

I would prefer `debug`
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_9phi2ScM3eMNeLFd:-MR_9phi2ScM3eMNeLFe:butgrvv) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_enclave.c#L40)):*
> ```C
> 
>     if (ms->ms_exitcode != (int)((uint8_t)ms->ms_exitcode)) {
>         urts_log_error("Saturation error in exit code %d, getting rounded down to %u\n",
> ```

I think we should have `info` or `debug` here... I suggest `debug`.
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_A9Jb3_9xWgPLEy43:-MR_A9Jb3_9xWgPLEy44:b52la0u) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_graphene.c#L11)):*
> ```C
> #include "pal_error.h"
> #include "sgx_internal.h"
> #include "sgx_log.h"
> ```

But it is not used here?

**Review by yamahata — DISMISSED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: 20 of 24 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_6k3L5VxS6Y1-TngW:-MRdYQ6c2fh-9uJt9coC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_files.c#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was a bug. Should be `log_error`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 331 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_6tCW8MO-tyZYWJfe:-MRdaDes1csI1pbDuR1p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_files.c#L331)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`log_error`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_process.c, line 282 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_7OzV3c_FDxkEvIev:-MRdYYta0cuTk22uhyHV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/db_process.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer `debug`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_9phi2ScM3eMNeLFd:-MRd_3tf90XnYc9XMMCf:bkxqxbj) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_enclave.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we should have `info` or `debug` here... I suggest `debug`.
</blockquote></details>

Done.

What's the reason for this, though? Why don't we pass the whole exit code to Linux, or do `& 0xFF`?
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_A9Jb3_9xWgPLEy43:-MRdYjWY7ChQm-8WOVQ1:b7bukjk) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_graphene.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But it is not used here?
</blockquote></details>

Right. It does need the header for `pal_printf`, though, after I removed the include from `pal_linux.h`. Fixed.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_9phi2ScM3eMNeLFd:-MReZpT0CBvc9fEwYP_W:b-8cafxw) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_enclave.c#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.

What's the reason for this, though? Why don't we pass the whole exit code to Linux, or do `& 0xFF`?
</blockquote></details>

Isn't it what Linux expects? This is what shells do I think? To be honest, I don't remember why this. @mkow ?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2109#-MR_9phi2ScM3eMNeLFd:-MRertB187uPIGhHnc98:bjxsqon) ([raw file](https://github.com/oscarlab/graphene/blob/d9238e9f5e58ab4788f140b2f58f6dcd6b57dbac/Pal/src/host/Linux-SGX/sgx_enclave.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it what Linux expects? This is what shells do I think? To be honest, I don't remember why this. @mkow ?
</blockquote></details>

This looks like just a debug warning,. I've fixed all calls of `DkProcessExit` recently, but it might be good to keep it, to catch bugs. Otoh it might be a better idea to just add an assert...

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 17 of 24 files at r1, 3 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 293 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuDI6F4Vk8CarIZviE:-MRuDI6F4Vk8CarIZviF:buz06mq) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/enclave_pages.c#L293)):*
> ```C
>             if (!new) {
>                 log_error("*** Cannot create split VMA during freeing of address %p ***\n",
>                           addr);
> ```

this can be unwrapped now
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 447 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuE3Ex2VyD6Zkjso1D:-MRuE3Ey9Oh-i1uQ-9AF:b-2y6s2h) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/enclave_pf.c#L447)):*
> ```C
>     pf_lock();
>     log_debug("Registered %u protected directories and %u protected files\n",
>             HASH_COUNT(g_protected_dirs), HASH_COUNT(g_protected_files));
> ```

please fix alignment
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRuIXuy7eODuNZzXIeD:bgimkin) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
> ```C
>     urts_log_info("    ssa_frame_size: %d\n",       secs->ssa_frame_size);
>     urts_log_info("    isv_prod_id:    0x%08x\n",   secs->isv_prod_id);
>     urts_log_info("    isv_svn:        0x%08x\n",   secs->isv_svn);
> ```

What do you all think about moving this stuff to "debug"? "info" is more like "errors + warnings", and this enclave printing is pretty loud (and rarely useful). Same for similar info printed above and below.

Actually, wouldn't it be better to use error/warn/debug/trace levels? This info vs debug is quite confusing to me (i.e. what's the difference between them).
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 263 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIv_T3go8r4hTYFly:-MRuIv_T3go8r4hTYFlz:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L263)):*
> ```C
>         urts_log_info("adding page  to enclave: %p [%s:%s] (%s)%s\n", addr, t, p, comment, m);
>     else
>         urts_log_info("adding pages to enclave: %p-%p [%s:%s] (%s)%s\n", addr, addr + size, t, p,
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 480 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuLYJc3G1aPVAes53e:-MRuLYJc3G1aPVAes53f:b-rdm3zq) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_main.c#L480)):*
> ```C
>         MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0);
>     if (IS_ERR_P(dbg)) {
>         urts_log_error("Cannot allocate debug information (GDB will not work)\n");
> ```

this is rather a warning? (I'd say errors are mostly irrecoverable and we cannot continue after them, which is not the case here?)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: 17 of 31 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 293 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuDI6F4Vk8CarIZviE:-MRyF5e-9SvWRmOrqqhb:bey5gi5) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/enclave_pages.c#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this can be unwrapped now
</blockquote></details>

You mean remove the ASCII art? Done.
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 447 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuE3Ex2VyD6Zkjso1D:-MRyFLyG2seylcbIv6zC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/enclave_pf.c#L447)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRyIRfJ622YDQoaMBAs:b-ea8ts0) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
Moved to debug.

>Actually, wouldn't it be better to use error/warn/debug/trace levels? This info vs debug is quite confusing to me (i.e. what's the difference between them).

I like it. We seem to be using `info` for warnings anyway.

This way `debug` is for all the stuff disabled by default, `trace` for hiding the particularly noisy messages, and `warning` for problems.

Done.

Follow-up: do you think `warning` should be on by default?
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 263 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIv_T3go8r4hTYFly:-MRyIuvPElZZG3ODmSDj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L263)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 480 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuLYJc3G1aPVAes53e:-MRyJ-p28EwmAQO-CVvl:bfvmsj2) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_main.c#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is rather a warning? (I'd say errors are mostly irrecoverable and we cannot continue after them, which is not the case here?)
</blockquote></details>

Yes. Changed.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_exception.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRyZp5KE3jtMicIECe9:-MRyZp5LAvnyZNR_gcjN:blqakmb) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_exception.c#L116)):*
> ```C
>     static int first = 0;
>     if (__atomic_exchange_n(&first, 1, __ATOMIC_RELAXED) == 0) {
>         log_warning("WARNING: all RDTSC/RDTSCP instructions are emulated (imprecisely) via "
> ```

Can we actually fix all warning messages to follow one format? Right now we have prefixes `WARNING:`, `Warning:`, `[Warning]` and so on.

I suggest to use `Warning: ` everywhere.
___
*[Pal/src/host/Linux-SGX/db_memory.c, line 86 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRy_7vg-gZATiTcaqjc:-MRy_7vg-gZATiTcaqjd:b-5txpxz) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_memory.c#L86)):*
> ```C
>     if (__atomic_compare_exchange_n(&at_cnt.counter, &t, 1, /*weak=*/false, __ATOMIC_SEQ_CST,
>                                     __ATOMIC_RELAXED))
>         log_debug("[Warning] DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL\n");
> ```

Why is it not `log_warning`?
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRy__sUDB7amLJrB4Px:bb96dvg) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Moved to debug.

>Actually, wouldn't it be better to use error/warn/debug/trace levels? This info vs debug is quite confusing to me (i.e. what's the difference between them).

I like it. We seem to be using `info` for warnings anyway.

This way `debug` is for all the stuff disabled by default, `trace` for hiding the particularly noisy messages, and `warning` for problems.

Done.

Follow-up: do you think `warning` should be on by default?
</blockquote></details>

I would keep `error` by default (in non-DEBUG builds). We have quite a few warnings; this is annoying when you want to see only the app output.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 480 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuLYJc3G1aPVAes53e:-MRy_z8DCv_1unJz95Jw:beyqs49) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_main.c#L480)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. Changed.
</blockquote></details>

If you will add the `Warning:` prefix everywhere, please also add in these places.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRysj9Z-n6H3emBgrwL:-MRysj9Z-n6H3emBgrwM:b-ugoxa3) (no related file):*
You left "info" in three places: busybox.manifest.template, memcached.manifest.template, redis-server.manifest.template. Please fix :)

---
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRyZp5KE3jtMicIECe9:-MRytpuK6vICe-cXoYgF:b2v39gk) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_exception.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we actually fix all warning messages to follow one format? Right now we have prefixes `WARNING:`, `Warning:`, `[Warning]` and so on.

I suggest to use `Warning: ` everywhere.
</blockquote></details>

I'd move this "Warning: " to the `log_*` itself. We should add all such stuff there and then remove from all the invocations. But maybe in a separate PR?
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 293 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuDI6F4Vk8CarIZviE:-MRyu9TR52HPIvWZKYpX:bhfz91) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/enclave_pages.c#L293)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You mean remove the ASCII art? Done.
</blockquote></details>

I meant just line wrapping (it fit into 100 chars), but removing the ascii-art is also good, for consistency.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRyuVNk9sa-9bWlfk1P:bqhu60i) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would keep `error` by default (in non-DEBUG builds). We have quite a few warnings; this is annoying when you want to see only the app output.
</blockquote></details>

Thanks!

I'm not sure about the defaults. For sure warnings should be disabled in release builds, as they may leak too much information, but in debug builds they could be nice. But then, we'd have different defaults in both... So, no strong preference from my side.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRysj9Z-n6H3emBgrwL:-MRzEf9E8YVjjN2c3HOv:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You left "info" in three places: busybox.manifest.template, memcached.manifest.template, redis-server.manifest.template. Please fix :)
</blockquote></details>

Done.

---
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRyZp5KE3jtMicIECe9:-MRz9yL-8set68k8F3qT:bn5eino) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_exception.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd move this "Warning: " to the `log_*` itself. We should add all such stuff there and then remove from all the invocations. But maybe in a separate PR?
</blockquote></details>

How about:

```
#define log_error(fmt...)    _log(PAL_LOG_WARNING, "[error] " fmt...)
#define log_warning(fmt...)  _log(PAL_LOG_WARNING, "[warning] " fmt...)
```

But I'd leave that for a later PR. It would be good to give a similar treatment to LibOS first (go through messages, adjust levels, learn more in the process).

For now, I changed the `log_warning` messages to `Warning:` to improve the situation a bit.
___
*[Pal/src/host/Linux-SGX/db_memory.c, line 86 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRy_7vg-gZATiTcaqjc:-MRzBvNyE9_II7f7XhqV:by3h6li) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_memory.c#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is it not `log_warning`?
</blockquote></details>

Translated from `DBG_M` which contained mostly debug info. But yes, it makes sense to be a warning. Changed.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRzCinL4EeIU4oriGRY:bqjc9un) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thanks!

I'm not sure about the defaults. For sure warnings should be disabled in release builds, as they may leak too much information, but in debug builds they could be nice. But then, we'd have different defaults in both... So, no strong preference from my side.
</blockquote></details>

If the log level is configurable by default, I'd rather keep the default the same in DEBUG and non-DEBUG builds. It gets too confusing otherwise. So let's keep it at `error`.

However, what about warnings such as `WARNING: Using insecure argv source`? That sounds pretty important. Should they be at `error` level?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_exception.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRyZp5KE3jtMicIECe9:-MRzHphm3iTWgcY8SLiO:b-tey3ci) ([raw file](https://github.com/oscarlab/graphene/blob/06171f54042f66ceb0077bcdc9075069781d3c62/Pal/src/host/Linux-SGX/db_exception.c#L116)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

How about:

```
#define log_error(fmt...)    _log(PAL_LOG_WARNING, "[error] " fmt...)
#define log_warning(fmt...)  _log(PAL_LOG_WARNING, "[warning] " fmt...)
```

But I'd leave that for a later PR. It would be good to give a similar treatment to LibOS first (go through messages, adjust levels, learn more in the process).

For now, I changed the `log_warning` messages to `Warning:` to improve the situation a bit.
</blockquote></details>

The proposal looks good to me.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRzI5j-4Ar9N-mf-RIq:bfllu4k) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If the log level is configurable by default, I'd rather keep the default the same in DEBUG and non-DEBUG builds. It gets too confusing otherwise. So let's keep it at `error`.

However, what about warnings such as `WARNING: Using insecure argv source`? That sounds pretty important. Should they be at `error` level?
</blockquote></details>

Good question. I'd raise them to `error` level, as they are something which should be noticed especially on release builds.
Also, it's currently printed with `printf` in PAL, could you fix it?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: 33 of 34 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2109#-MRuIXuy7eODuNZzXIeC:-MRzO6Yp49GtLYcdQJ4A:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/68230a2409c40068260ceb664ab5b78b5ba24359/Pal/src/host/Linux-SGX/sgx_framework.c#L205)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good question. I'd raise them to `error` level, as they are something which should be noticed especially on release builds.
Also, it's currently printed with `printf` in PAL, could you fix it?
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 4 files at r3, 9 of 14 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2109)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (httpd build failed, weird...)

**Pull request merged**
