### PR TITLE
Improving handle polling semantics

### PR DESCRIPTION
**Pull request by chiache**
This PR addresses the performance issues of #228. The existing PAL call DkObjectsWaitAny() is too restrictive for specifying the polling events and being unable to return multiple simultaneous events. The new DkObjectsWaitEvents() accepts additional arguments to specific and return various events (signal, read, write, and error).

For incremental development, the old DkObjectsWaitAny() is kept for compatibility against the library OS. Eventually we will replace the API with DkObjectsWaitEvents().

This PR is not complete yet; remaining to-dos:
- Reimplement epoll_wait() using DkObjectsWaitEvents()
- Evaluate performance improvements
- Writing a regression test for DkObjectsWaitEvents()

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/229)

### CODE REVIEW

**Comment by donporter** [comment]
This seems like a nice improvement, to better capture the common polling requirements and make this more natural.

There are a couple of implicit design decisions I flagged that I think would benefit from a maintainer-level discussion.

**Comment by thomasknauth** [comment]
I am unsure on how to proceed. I have re-implemented shim_do_epoll_wait() using the newly added PAL call DkObjectsWaitEvents(). I currently do not have a small test case though, since the code sort of works on some branch or even on master after applying a queued up PR.

In general, I feel the situation is becoming unsustainable with the sheer amount of pending PRs. We've repeatedly stumbled upon problems only to discover someone else already reported them or there might even already be a pending PR fixing it. Interaction of pending PRs is another worrisome problem.

I'm inclined to submit my code as is, just so it does not get lost. In my case, it fixes an issue I saw when running redis-benchmark on Graphene's DkObjectWaitEvents branch. Coming up with a smaller scale test case is possible, but would require more work on my end. Given the issues outlined above, I am reluctant to do so at this point.

**Comment by donporter** [comment]
I'm a bit confused.  Was this submitted to the wrong PR?

Your concern is definitely appreciated about the backlog of PRs - we are working on it.  

I think we can be reasonable about test cases if they really are hard to come up with, but a lot of times they are not.  I think if no one, author or reviewer, can describe how to write a simple unit test, then we should accept the PR as is.

**Comment by thomasknauth** [comment]
@donporter, possibly the wrong PR. I've just submitted #434. Still learning about the workflows. Wasn't sure if I could tack on my changes to this existing PR.

**Comment by donporter** [comment]
I know you had a comment on #197 about this, and, ironically, I was holding up merge of that until we resolved that discussion.  Would you be ok with merging #197?

In general, your fixes would need to be in a separate PR.  A single PR should address one issue, and be from one author.

But I appreciate you reaching out and helping.

**Comment by thomasknauth** [comment]
I did reply on #197 yesterday. Yes, please go ahead and close it.

**Pull request closed without merging**
