### PR TITLE
[LibOS] Fix incorrect use of LISTP macros in Async helper thread

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The Async helper thread traverses through the `async_event` list of scheduled events and copies the triggered events in the `triggered` list. Theoretically, each event may be present in both lists at the same time, so the event struct must have two `LIST_TYPE` fields. However, there was a bug: both lists were described by a single `list` field. In cases where the event's `list` was rewired to the `triggered` list, it suddenly disappeared from the `async_event` list, which led to a hang of Graphene.

## How to test this PR? 

All tests must pass. Try running Nginx and then doing Ctrl-C: without this PR it hangs, with this PR it terminates gracefully.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test timed out, cannot reproduce locally, maybe an issue with too-small-timeout value in Jenkins)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_async.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2028#-MOasKI499HvkXaNrNjw:-MOasKI57IQKkj9bRA2B:b-wpjd2g) ([raw file](https://github.com/oscarlab/graphene/blob/4263f00423626580adf49100672c7d5f50d8997b/LibOS/shim/src/shim_async.c#L314)):*
> ```C
>                     if (tmp->object == pals[i]) {
>                         debug("Async IO event triggered at %lu\n", now);
>                         LISTP_ADD_TAIL(tmp, &triggered, triggered_list);
> ```

Shouldn't this remove `tmp` from `async_list`?

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_async.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2028#-MOasKI499HvkXaNrNjw:-MOb4B73Ak55p8YXkcMo:b-mu8kxu) ([raw file](https://github.com/oscarlab/graphene/blob/4263f00423626580adf49100672c7d5f50d8997b/LibOS/shim/src/shim_async.c#L314)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this remove `tmp` from `async_list`?
</blockquote></details>

No, "async IO events" are `FIOASYNC` thingies: it is to send the `SIGIO` signal to the application each time something happens (polled) on a particular FD. See also `LibOS/shim/src/sys/shim_ioctl.c` and `signal_io()` there.

So these events must *not* be removed here. They are *not* one-off but repeat until `ioctl(fd, FIOASYNC, /*disable*/0)`. Of course it doesn't really work well, but it's for another PR. Actually, I think you wrote this:
https://github.com/oscarlab/graphene/blob/a72662ffb22e632064ab9d9776f790c9c6d55e79/LibOS/shim/src/sys/shim_ioctl.c#L20

:)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/shim_async.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2028#-MOasKI499HvkXaNrNjw:-MOb6COTDwSTxd663gBO:b-yjv12x) ([raw file](https://github.com/oscarlab/graphene/blob/4263f00423626580adf49100672c7d5f50d8997b/LibOS/shim/src/shim_async.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, "async IO events" are `FIOASYNC` thingies: it is to send the `SIGIO` signal to the application each time something happens (polled) on a particular FD. See also `LibOS/shim/src/sys/shim_ioctl.c` and `signal_io()` there.

So these events must *not* be removed here. They are *not* one-off but repeat until `ioctl(fd, FIOASYNC, /*disable*/0)`. Of course it doesn't really work well, but it's for another PR. Actually, I think you wrote this:
https://github.com/oscarlab/graphene/blob/a72662ffb22e632064ab9d9776f790c9c6d55e79/LibOS/shim/src/sys/shim_ioctl.c#L20

:)
</blockquote></details>

All right, makes sense

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2028)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
