### PR TITLE
[Doc] Add DCO and related text

### PR DESCRIPTION
**Pull request by donporter**
## Description of the changes 

Per our discussions around the technical charter, adding a DCO to the project, and related documentation to CONTRIBUTING.rst.  Feedback on exact phrasing welcome; I am also not totally confident I linked a local file correctly in rst.

## How to test this PR? 

Documentation only.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[CONTRIBUTING.rst, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCLpSt90J2uQUE5log:-MHCLpSt90J2uQUE5loh:b-629mhy) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L77)):*
> ```
> indicating that the contributions to this project are covered by the `project Developer
> ```

Hmm, I think wording here is a slightly imprecise - I'd say instead something like "indicating that the author(s) are agreeing to [...]". The exact meaning of the sign-off is that _they_ are agreeing to something and IMO it should be explicitly stated.
___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MHCNLpuCkCuWw-JW_MN:brxuwhu) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
> ```reStructuredText
> #. Be signed-off by the author of the PR in git (i.e., using the ``git commit -s``, indicating
>    that the contributions to this project are covered by the `project Developer
>    Certificate of Origin <DCO.txt>`__
> ```

This link doesn't work, it redirects me to devel/DCO.txt. I think the DCO.txt should be moved there anyway, as it is relevant only for developers.
___
*[CONTRIBUTING.rst, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCLyD17mgNVfVZFIdn:-MHCLyD2EVOM9tGICaQM:b-k4r5yl) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L114)):*
> Be signed off

You wrote `signed-off` above. I'm not sure which one is more correct in English, but please unify :)

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

___
*[CONTRIBUTING.rst, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCLpSt90J2uQUE5log:-MHIN1G_0T8LN_5LiHyS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> indicating that the contributions to this project are covered by the `project Developer
> ```

Hmm, I think wording here is a slightly imprecise - I'd say instead something like "indicating that the author(s) are agreeing to [...]". The exact meaning of the sign-off is that _they_ are agreeing to something and IMO it should be explicitly stated.
</blockquote></details>

Done.
___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MHIN1kX2ukvqpD8hWEm:b-c0vlg6) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This link doesn't work, it redirects me to devel/DCO.txt. I think the DCO.txt should be moved there anyway, as it is relevant only for developers.
</blockquote></details>

Done.  Thanks for the pointer for the "right" place to put this.
___
*[CONTRIBUTING.rst, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCLyD17mgNVfVZFIdn:-MHIN5rRBisqlZT4BAq8:b-ictry8) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Be signed off

You wrote `signed-off` above. I'm not sure which one is more correct in English, but please unify :)
</blockquote></details>

Done.  Neither is particularly great (passive voice generally discouraged), but I think verb-ifying the git command is probably clearest.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MIKNP4VELgt8HepAJHr:bvooju) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Done.  Thanks for the pointer for the "right" place to put this.
</blockquote></details>

I just noticed that despite this link works on RTD, it doesn't work on GitHub. @woju: how should we fix this?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MIKsQ66DlGcA7B6tMJV:b-w7z9ka) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just noticed that despite this link works on RTD, it doesn't work on GitHub. @woju: how should we fix this?
</blockquote></details>

Are you looking at broken link at https://github.com/oscarlab/graphene/blob/bf89a92679c5e407972758b92ad86a5bce2df576/CONTRIBUTING.rst?
This is because at that commit there is apparently no `DCO.txt` in the repo: https://github.com/oscarlab/graphene/tree/bf89a92679c5e407972758b92ad86a5bce2df576/.

If you want this link to work both in github and RTD, this is not trivial. Probably this should be `DCO.rst` in the root directory (sibling to `CONTRIBUTING.rst`) and then symlinked in Documentation/devel and included in toctree somewhere.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MIL8gn32MuVTGwVxqbU:b-mzim24) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
> This is because at that commit there is apparently no DCO.txt in the repo: https://github.com/oscarlab/graphene/tree/bf89a92679c5e407972758b92ad86a5bce2df576/.

It is in the repo, but in Documentation/devel/. The issue is that RTD and GitHub use different root for resolving relative paths.

> Probably this should be DCO.rst in the root directory (sibling to CONTRIBUTING.rst) and then symlinked in Documentation/devel and included in toctree somewhere.

I'd keep it in .txt, to be 1-1 with the original. But yeah, using symlinks should solve the problem (although it's a bit hacky).

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MIP4XVJ6NCd45I8kJCp:b-ma634g) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
> It is in the repo, but in Documentation/devel/. The issue is that RTD and GitHub use different root for resolving relative paths.

Nope, this is because of `.. include:` in `Documentation/devel/contributing.rst`. If you include, you get what you deserve.

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MIV0rea9GvKPKugEGTe:b-i9g7ul) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> It is in the repo, but in Documentation/devel/. The issue is that RTD and GitHub use different root for resolving relative paths.

Nope, this is because of `.. include:` in `Documentation/devel/contributing.rst`. If you include, you get what you deserve.
</blockquote></details>

I think I fixed this issue with the symlink suggestion.  Thank you.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 2 unresolved discussions (waiting on @donporter and @mkow)

___
*[Documentation/devel/DCO.rst, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/1816#-MIZBLgF8eOn13r5koF2:-MIZBLgG5SOvp4ktS7wU:bx5oss2) ([raw file](https://github.com/oscarlab/graphene/blob/6cd300c4af1764382991db441269d7c915b8d1b9/Documentation/devel/DCO.rst#L1)):*
> ```reStructuredText
> DCO.rst
> ```

huh, does this really work? isn't this an infinite symlink loop?

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @mkow)

___
*[Documentation/devel/DCO.rst, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/1816#-MIZBLgF8eOn13r5koF2:-MIdGV27CRQzB-zmDT6q:b-wlb0z0) ([raw file](https://github.com/oscarlab/graphene/blob/6cd300c4af1764382991db441269d7c915b8d1b9/Documentation/devel/DCO.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

huh, does this really work? isn't this an infinite symlink loop?
</blockquote></details>

No.  It was broken.  Now that I can build the docs, I was able to test it :)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv, @donporter, and @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MR6s88h-YcTNVEWGLmi:b73g2iq) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I think I fixed this issue with the symlink suggestion.  Thank you.
</blockquote></details>

Right now it doesn't work in html (sphinx renders dead link). This is not trivial, I'll work on some solution.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MRKhYsU9rQlytnN7TIm:bud4vy5) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Right now it doesn't work in html (sphinx renders dead link). This is not trivial, I'll work on some solution.
</blockquote></details>

Now it's broken in Sphinx, leads to a directory listing instead of the rendered file.

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MRKwpJMC9Qrob_ne_y9:b-gc9jvu) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it's broken in Sphinx, leads to a directory listing instead of the rendered file.
</blockquote></details>

Only in `file://`. Over `http[s]://` we take advantage of the automatic `/` redirect implemented in most HTTP servers. That's why `DCO/` is a directory and not a file.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MRL1Fo5B5Ugfj72iKTY:b-sveobl) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Only in `file://`. Over `http[s]://` we take advantage of the automatic `/` redirect implemented in most HTTP servers. That's why `DCO/` is a directory and not a file.
</blockquote></details>

Oh, that's hacky. Could you/Don document it in a comment here?

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv and @mkow)

___
*[CONTRIBUTING.rst, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1816#-MHCNLpt2q-d4q_KpmeU:-MRaq1UB0JvMsLVh_t3J:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/e9e0a14ef04add09abdd5a46a7030bc6cb9eedb5/CONTRIBUTING.rst#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, that's hacky. Could you/Don document it in a comment here?
</blockquote></details>

Done

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
