### PR TITLE
[CI] Add /dev/kmsg device to docker

### PR DESCRIPTION
**Pull request by woju**
This is needed for testing arbitrary /dev passthrough.

Needed for #1959.

@dimakuv

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1992)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1992)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1992)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1992)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1992)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
