### PR TITLE
Fix memory leak in __map_elf_object

### LINKED ISSUE #473: new_phdr leaks in __map_elf_object()
`new_phdr` seems to leak if it gets assigned to `phdr` here:
https://github.com/oscarlab/graphene/blob/05c495c369ffb66fca5d1d3b451f825a101993be/LibOS/shim/src/elf/shim_rtld.c#L413

See this discussion: https://reviewable.io/reviews/oscarlab/graphene/353#-LT-YPkUEa37AdynyeoY

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Fixes #473

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/823)

### CODE REVIEW

**Comment by mkow** [comment]
Test this please

**Comment by dimakuv** [comment]
Retest Jenkins-Debug please (`clone03` LTP test failed)

**Comment by mkow** [comment]
Test this please

**Comment by mkow** [comment]
Retest Jenkins please (`kill03,1` failed)

**Comment by mkow** [comment]
Retest Jenkins-SGX please (timeout on `Large File Support`)

**Comment by mkow** [comment]
Retest Jenkins please (`kill01,1` and `kill03,1` failed)

**Pull request merged**
