### PR TITLE
[LibOS] shim_namei.c: Fix input absolute path error

### PR DESCRIPTION
**Pull request by zhangckid**
If input absolute path, it will get wrong my_dent.

Signed-off-by: Zhang Chen <chen.zhang@intel.com>

Please fill in the following form before submitting this PR and ensure that your code follows our [coding style guideline](../blob/master/CODESTYLE.md).

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)

This issue looks like a typo, missing parentheses after the "else".
If input absolute path, it will get wrong value of my_dent.

## How to test this PR? (if applicable)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/477)

### CODE REVIEW

**Comment by mkow** [comment]
Side note: when we enable enforced code formatting such fails should be very easy to spot.

**Comment by zhangckid** [comment]
Hi Don,

It's fine for me to add the unit test.
Can we design the unit test like that?
1. Create a .c file and manifest file in LibOS/shim/test/regression for example path.c.
2. mount one absolute path and one relative path in the manifest.
3. read the file in path.c.

If yes, I will send another patch for it.

By the way, do you think the LibOS/shim/test/regression/shared_object.c is redundant ?
The bootstrap_pie.c has include the -fPIC args in makefile. 

Thanks

**Comment by donporter** [comment]
That works for me.  Thanks!

I don't think shared_object is redundant, in that it currently is tickling an intermittent failure :).

**Comment by zhangckid** [comment]
Hi @donporter 
I have add the proc-path test case, please review~

**Comment by donporter** [comment]
@zhangckid Please go ahead and squash this into a single commit.  I think this PR is ready to merge otherwise.

**Comment by zhangckid** [comment]
Hi @mkow ,
I have addressed your comments, please review again.

**Comment by zhangckid** [comment]
Hi @donporter ,

Make sense. I have removed it.

**Comment by mkow** [comment]
Test this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
