### PR TITLE
[Pal/FreeBSD] specify loaded address of exec in child process

### PR DESCRIPTION
**Pull request by yamahata**
This is the FreeBSD version of https://reviewable.io/reviews/oscarlab/graphene/372
I haven't tested this PR.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

Please fill in the following form before submitting this PR and ensure that your code follows our [coding style guideline](../blob/master/CODESTYLE.md).

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [x] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? (if applicable)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/636)

### CODE REVIEW

**Comment by dimakuv** [comment]
+1 for dropping FreeBSD.

**Comment by mkow** [comment]
Related issue: #256.

**Comment by dimakuv** [comment]
Closing this PR due to no active support of FreeBSD for now.

**Comment by donporter** [comment]
@chiache Do you want to take this one over?

**Pull request closed without merging**
