### PR TITLE
[Tools/gsc] More resilient naming options for GSC

### PR DESCRIPTION
**Pull request by dayeol**
Currently, GSC generates two images: signed and non-signed,
whose names are determined automatically by adding the prefix "gsc-" and
the postfix "-unsigned", respectively.
This is less flexible, not very consistent (if you include tag
name), and also could not work in some cases if the image has a repository.
Instead of mixing prefix and postfix scheme, we add postfix to the image
name excluding the tag.
Also, we let users to set the name of the output image with '--name' or '-o' flag.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1666)

### CODE REVIEW

**Comment by dimakuv** [comment]
Looks good to me, but summoning @vahldiek to review this PR.

**Comment by dimakuv** [comment]
@vahldiek Do you think this PR is still valid? Or should we close it? I guess @dayeol won't be available to finish this PR...

**Comment by vahldiek** [comment]
Its valid in the sense that there might be someone out there who prefers to name images. So far I've not gotten this request directly. Given that this PR is a bit old, I'm not sure how much sense it makes, since it needs serious rebase.

**Comment by dimakuv** [comment]
Thank you @vahldiek. It looks like this PR is (a) quite outdated and (b) doesn't have a particular use case. Let's close it.

**Pull request closed without merging**
