### PR TITLE
[Pal/Linux-SGX] optimize sgx pages allocation

### PR DESCRIPTION
**Pull request by yamahata**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1332)

### CODE REVIEW

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1332#-MFXvi3r6Ar1c9Psajx6:-MFXvi3r6Ar1c9Psajx7:b-w3hjz9) ([raw file](https://github.com/oscarlab/graphene/blob/faa3425a767c0d9ebd3f0a91236038fc91249de0/Pal/src/host/Linux-SGX/enclave_pages.c#L72)):*
> ```C
> }
> 
> struct heap_vma* cache = NULL;
> ```

shared global variable cache may needs to be guarded with volatile, atom operations or locker.

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/1332#-MFXw2Zc29ZPirkvXxKM:-MFXw2Zc29ZPirkvXxKN:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/faa3425a767c0d9ebd3f0a91236038fc91249de0/Pal/src/host/Linux-SGX/enclave_pages.c#L185)):*
> ```C
> 
>     atomic_add(size / g_page_size, &alloced_pages);
>     cache = vma;
> ```

ditto

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 290 at r1](https://reviewable.io/reviews/oscarlab/graphene/1332#-MFXw_M80AxzTnIpoZKn:-MFXw_M80AxzTnIpoZKo:b-3xdmd1) ([raw file](https://github.com/oscarlab/graphene/blob/faa3425a767c0d9ebd3f0a91236038fc91249de0/Pal/src/host/Linux-SGX/enclave_pages.c#L290)):*
> ```C
> 
>     SGX_DBG(DBG_M, "free %ld bytes at %p\n", size, addr);
> ```

```assert(addr != NULL);```

**Comment by bigdata-memory** [comment]
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 318 at r1](https://reviewable.io/reviews/oscarlab/graphene/1332#-MFXxdEA2F1g0AsEmprU:-MFXxdEB8rt3lC1Wh9V9:bhwcu0p) ([raw file](https://github.com/oscarlab/graphene/blob/faa3425a767c0d9ebd3f0a91236038fc91249de0/Pal/src/host/Linux-SGX/enclave_pages.c#L318)):*
> ```C
>                 LISTP_DEL(vma, &heap_vma_list, list);
>                 free(vma);
>                 if (cache == vma)
> ```

moving this right before the ```free(vma)``` to avoid the dangling pointer to be used, the better way is to use mutex for protecting the shared cached vma from contending

**Comment by dimakuv** [comment]
I am closing this PR because it is very stale and because the benefit of this optimization (the cache of `free_vmas`) is dubious. I recently did a lot of performance testing of Graphene-SGX and noticed that the VMAs in the Linux-SGX PAL are very small in size -- maybe 10-50 VMAs on very large workloads of several GBs. Thus, I see no benefit in trying to improve the logic of finding suitable VMAs or speeding up VMA traversals.

In my experiments, SGX VMA allocation was never a bottleneck.

**Pull request closed without merging**
