### PR TITLE
[Pal/Linux-SGX] Allow only known leaves/subleaves in CPUID emulation

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously Linux-SGX PAL allowed all CPUID leaves. For security, we want to explicitly allow only known CPUID leaves and fail on everything unknown.

This PR also simplifies the logic of the cache for CPUID entries.

This PR also contains a commit to add Intel PKRU feature to XFRM of our SGX PAL (needed because we sanitize CPUID values).

## How to test this PR? 

The previous version of CPUID emulation forced Graphene to run single-threaded with newer versions of PyTorch and MKL-DNN. That's because PyTorch (or MKL-DNN library?) deduced the topology not from `/proc` or `/sys` but directly by querying CPUID values.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: 0 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1983#-MMVqnC8AfkLovc8NCbO:-MMVqnC9-vZXyezRzzUk:btow2s0) (no related file):*
Heh, I pushed from another machine that has another git-author by default. I'll need to change the name/email to mine in the rebase.

---
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 153 at r1](https://reviewable.io/reviews/oscarlab/graphene/1983#-MMVr45K9olktSlESFf2:-MMVr45K9olktSlESFf3:b-pn43ac) ([raw file](https://github.com/oscarlab/graphene/blob/3330238e7f5ceeb078453eb53612744f9bf74aa7/Pal/src/host/Linux-SGX/db_misc.c#L153)):*
> ```C
>         chosen = &pal_cpuid_cache[pal_cpuid_cache_top++];
>     } else {
>         unsigned int oldest_clock = pal_cpuid_cache[0].recently;
> ```

Removed this logic of LRU replacement. I can't imagine any real-world app using more than 64 different CPU leaves.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 265 at r1](https://reviewable.io/reviews/oscarlab/graphene/1983#-MMVrGT9Di5BKIMM7pKT:-MMVrGT9Di5BKIMM7pKU:b-bvxtsm) ([raw file](https://github.com/oscarlab/graphene/blob/3330238e7f5ceeb078453eb53612744f9bf74aa7/Pal/src/host/Linux-SGX/enclave_ocalls.c#L265)):*
> ```C
>     int retval = 0;
>     ms_ocall_cpuid_t* ms;
>     bool bypass_exitless = false;
> ```

Removed this premature optimization, we cache most CPUID values anyway.

**Review by yamahata — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 290 at r1](https://reviewable.io/reviews/oscarlab/graphene/1983#-MMWWFhdCpAiR7qys6EY:-MMWWFhdCpAiR7qys6EZ:bupxao8) ([raw file](https://github.com/oscarlab/graphene/blob/8bd5173f0d4d3fc3a923e86521c986b0630e2ae0/Pal/src/host/Linux-SGX/db_misc.c#L290)):*
> ```C
> };
> 
> static struct cpuid_leaf cpuid_known_leaves[] = {
> ```

nitpick: const

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 285 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_4ciC4pxgEPbYTJdq:-MQ_4ciC4pxgEPbYTJdr:bwcirg1) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L285)):*
> ```C
> 
> struct cpuid_leaf {
>     unsigned int idx;
> ```

What's this index? CPUID leaf? If so, then why not calling it "leaf"?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 286 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_3SC46wyDeBd_Q6In:-MQ_3SC46wyDeBd_Q6Io:b-kdjsul) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L286)):*
> ```
> then must explicitly zero it out
> ```

Seems the subject is missing? Who is zeroing this, user of this struct or CPU?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 287 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_3cm65teEqrpOi8x3:-MQ_3cm65teEqrpOi8x4:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L287)):*
> ```C
>     unsigned int idx;
>     bool zero_subleaf; /* if subleaf is not used, then must explicitly zero it out */
>     bool cache;        /* if leaf is constant on all cores, then can add to cache */
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 293 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbC7456wjyHJhIwary:-MQbC7456wjyHJhIwarz:b-g4xhcv) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L293)):*
> ```C
>     {.idx = 0x00, .zero_subleaf = true,  .cache = true},  /* Highest Func Param and Manufacturer */
>     {.idx = 0x01, .zero_subleaf = true,  .cache = false}, /* Processor Info and Feature Bits */
>     {.idx = 0x02, .zero_subleaf = true,  .cache = true},  /* Cache and TLB Descriptor */
> ```

Is this actually constant on all cores? What about multisocket systems? Actually, ditto to all the values here, doesn't this caching break on multisocket?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 309 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbmagZAqq_zXLFsw-X:-MQbmagZAqq_zXLFsw-Y:b-y42qj7) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L309)):*
> ```C
>     {.idx = 0x15, .zero_subleaf = true, .cache = true},   /* Time Stamp Counter/Core Clock */
>     {.idx = 0x16, .zero_subleaf = true, .cache = true},   /* Processor Frequency Information */
>     {.idx = 0x17, .zero_subleaf = false, .cache = true},  /* System-On-Chip Vendor Attribute */
> ```

missing leaf 0x18?
___
*[python/graphenelibos/sgx_get_token.py, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbrnwADjMSRuhyZj7L:-MQbrnwADjMSRuhyZj7M:b-8vej5) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/python/graphenelibos/sgx_get_token.py#L28)):*
> ```Python
>         offs.SGX_XFRM_AVX512:   "avx512f",
>         offs.SGX_XFRM_MPX:      "mpx",
>         offs.SGX_XFRM_PKRU:     "pku",
> ```

not "pkru"? (missing "r"?)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: 9 of 10 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 285 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_4ciC4pxgEPbYTJdq:-MQqxHPGCJcq0V-XxWua:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L285)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's this index? CPUID leaf? If so, then why not calling it "leaf"?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 286 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_3SC46wyDeBd_Q6In:-MQqxnVs96SmEnY-3NL7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L286)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> then must explicitly zero it out
> ```

Seems the subject is missing? Who is zeroing this, user of this struct or CPU?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 287 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQ_3cm65teEqrpOi8x3:-MQqyIf85udm1F9iKsEa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L287)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 293 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbC7456wjyHJhIwary:-MQqyNP76QwATDwZOgu9:bcc7o7j) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this actually constant on all cores? What about multisocket systems? Actually, ditto to all the values here, doesn't this caching break on multisocket?
</blockquote></details>

It is on constant across all cores and sockets on systems that I looked at. I am not aware of different-core 2-socket systems on Intel.

Even if the values differ across cores/sockets, does it matter for Graphene and the app running in it? There will be slightly wrong info on the CPU cache, TLB, etc., but this is insane for an application to tweak its threads depending on where it runs. I don't think it's worth supporting "non-constant-cpu-info" on most CPU leaves.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 309 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbmagZAqq_zXLFsw-X:-MQr26nn2ZiQOyPnoFIZ:b-ac95ho) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing leaf 0x18?
</blockquote></details>

Done. My Intel SDM was too old :)
___
*[python/graphenelibos/sgx_get_token.py, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbrnwADjMSRuhyZj7L:-MQqwax8Cbz8gJj2OfB-:bxha50a) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/python/graphenelibos/sgx_get_token.py#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not "pkru"? (missing "r"?)
</blockquote></details>

No, this is correct. The `r` is missing in the output of cpuinfo:
```
root@icelake:~# grep -rIw pkru /proc/cpuinfo | wc -l
0
root@icelake:~# grep -rIw pku /proc/cpuinfo | wc -l
12
```

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 293 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbC7456wjyHJhIwary:-MQtH0Fp6oJZgTuOnqOs:bssfd5h) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L293)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It is on constant across all cores and sockets on systems that I looked at. I am not aware of different-core 2-socket systems on Intel.

Even if the values differ across cores/sockets, does it matter for Graphene and the app running in it? There will be slightly wrong info on the CPU cache, TLB, etc., but this is insane for an application to tweak its threads depending on where it runs. I don't think it's worth supporting "non-constant-cpu-info" on most CPU leaves.
</blockquote></details>

I'd expect it to rather just do "check where I'm running and adjust stuff", on each thread it's running. But I'm not sure if anything is doing that.

Anyways, unblocking. I also don't know any such systems, but I think in theory they are possible, so we may hit some issues with them in the future.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 309 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbmagZAqq_zXLFsw-X:-MQtHVW06DPp_RJFNtPw:b-u1na8r) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/Pal/src/host/Linux-SGX/db_misc.c#L309)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. My Intel SDM was too old :)
</blockquote></details>

Time for an update! :)
___
*[python/graphenelibos/sgx_get_token.py, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1983#-MQbrnwADjMSRuhyZj7L:-MQtHhlD82C2qDlNNtVu:bu78usp) ([raw file](https://github.com/oscarlab/graphene/blob/9569926b63a9be92f06b0e159cf163544cb6a853/python/graphenelibos/sgx_get_token.py#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, this is correct. The `r` is missing in the output of cpuinfo:
```
root@icelake:~# grep -rIw pkru /proc/cpuinfo | wc -l
0
root@icelake:~# grep -rIw pku /proc/cpuinfo | wc -l
12
```
</blockquote></details>

Huh 0o

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1983)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
