### PR TITLE
[Testing - DO NOT MERGE] fsgsbase testing

### PR DESCRIPTION
**Pull request by donporter**
## Description of the changes 

This is a cleaner version of #1555 with what should be the remaining changes for Jenkins to run on a patched FSGSBASE kernel.

These changes should not be merged as they are now; I will factor out any changes in separate PRs.

## How to test this PR? 

Just run a Jenkins pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1647)

### CODE REVIEW

**Comment by donporter** [comment]
Jenkins, retest SGX please.  aesmd not running on uncledeadly

**Comment by donporter** [comment]
Jenkins, test Jenkins-SGX please.

**Comment by donporter** [comment]
Jenkins, test Jenkinx-SGX-apps please.

**Comment by donporter** [comment]
Jenkins, test Jenkinx-SGX-18.04-apps please.

**Comment by donporter** [comment]
Jenkins, test Jenkins-SGX-18.04-apps please.

**Comment by donporter** [comment]
Jenkins, test Jenkins-SGX-18.04-apps please.

**Comment by donporter** [comment]
Jenkins, test Jenkins-SGX-18.04 please.

**Comment by donporter** [comment]
Jenkins, test Jenkins-SGX-apps please.

**Comment by donporter** [comment]
Retest this please.  Worker had gsgx loaded.

**Comment by dimakuv** [comment]
This PR is not needed any more. We successfully tested `fsgsbase`.

**Pull request closed without merging**
