### PR TITLE
[Pal/Linux-SGX] Update Diffie-Hellman parameters to use modp3072 group

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

It was recommended to us to update from modp2048 Diffie-Hellman group (group 14) to modp3072 group (group 15). It is a trivial update.

## How to test this PR? 

All tests should pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 909 at r1](https://reviewable.io/reviews/oscarlab/graphene/2429#-MbekvIB9BWb7lS6vEGr:-MbekvICB0bmGLyJ3UMR:b-zi0dq0) ([raw file](https://github.com/oscarlab/graphene/blob/a95ed123fa6052a597e525eafd34d044761d8141/Pal/src/host/Linux-SGX/enclave_framework.c#L909)):*
> ```C
> int _DkStreamKeyExchange(PAL_HANDLE stream, PAL_SESSION_KEY* key) {
>     uint8_t pub[DH_SIZE]   __attribute__((aligned(DH_SIZE)));
>     uint8_t agree[DH_SIZE] __attribute__((aligned(DH_SIZE)));
> ```

FYI: these `aligned` attributes were not needed, so simply removed.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
