### PR TITLE
Fix numeric base confusion in pid printing

### PR DESCRIPTION
**Pull request by mkow**
Fixes the pid printing bug mentioned in #100.

### CODE REVIEW

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Merging because default is an orphaned Jenkins job, and travis is really obviated by Jenkins now.  In other words, both of these are merge booboos.

**Pull request merged**
