### PR TITLE
[Docs] Mention "Fixes #xyz" in GitHub's PR template

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

A small tweak suggested by @bigdata-memory.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1824)

### CODE REVIEW

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1824)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1824#-MHq5gLy4lIsNbAprJrV:-MHq5gM-CjrDivE6RTYc:b-ih3c54) (no related file):*
How on earth this PR failed on jenkins ...

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1824)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1824#-MHq5gLy4lIsNbAprJrV:-MHq98n_42gEUXGWXI4j:b-d1yafp) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How on earth this PR failed on jenkins ...
</blockquote></details>

LTP timeout again :)

---

**Review by donporter — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1824)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by donporter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1824)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
