### PR TITLE
Pytest

### PR DESCRIPTION
**Pull request by woju**
## Affected components

- [ ] README and global configuration
- [x] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Test reorganisation. `pytest` is used in place of custom runner. Test results are aggregated in JUnit-XML file for consumption in Jenkins, which should generate nice report of which tests exactly failed and were fixed in which commits.

## How to test this PR? 
Run `Jenkinsfile`s.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/833)

### CODE REVIEW

**Comment by woju** [comment]
Cc: @mkow

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
@woju, please fix this failure of Jenkins & Jenkins-Debug pipelines:
```
=================================== FAILURES ===================================
_________________________ TC_30_Syscall.test_030_fopen _________________________

self = <test.TC_30_Syscall testMethod=test_030_fopen>

    def test_030_fopen(self):
        stdout, stderr = self.run_binary(['fopen_cornercases'])

        # fopen corner cases
>       self.assertIn('Successfully read from file: Hello world', stdout)
E       AssertionError: 'Successfully read from file: Hello world' not found in 'filepath = tmp/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (len = 258)\nSuccessfully read from file: Hello World\n'

test.py:152: AssertionError
```

**Comment by dimakuv** [comment]
@woju, please fix this errors in Jenkins-SGX pipeline (*20 seconds is not enough for 8GB enclave, did you forget to add the timeout for this test?*):
```
_____________________ TC_01_Bootstrap.test_120_8gb_enclave _____________________

self = <test.TC_01_Bootstrap testMethod=test_120_8gb_enclave>

    @unittest.skipUnless(HAS_SGX, 'this test requires SGX')
    def test_120_8gb_enclave(self):
        manifest = self.get_manifest('Bootstrap6')
>       stdout, stderr = self.run_binary([manifest])

test.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../Scripts/regression.py:43: in run_binary
    self.fail('timeout ({} s) expired'.format(timeout))
E   AssertionError: timeout (20 s) expired
```

And this (*there is no such binary which must return an error so the script must treat this error code as correct return result*):

```
___________ TC_01_Bootstrap.test_140_missing_executable_and_manifest ___________

self = <test.TC_01_Bootstrap testMethod=test_140_missing_executable_and_manifest>

    def test_140_missing_executable_and_manifest(self):
>       stdout, stderr = self.run_binary(['fakenews'])

test.py:141:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.TC_01_Bootstrap testMethod=test_140_missing_executable_and_manifest>
args = ['fakenews'], timeout = 20, kwds = {}
loader = '/home/jenkins/jenkins_slave/workspace/graphene-sgx/Pal/regression/../../Runtime/pal-Linux-SGX'
process = <subprocess.Popen object at 0x7f30540cd9e8>, stdout = b''
stderr = b'Executable not found\nUSAGE: /home/jenkins/jenkins_slave/workspace/graphene-sgx/Pal/regression/../../Runtime/pal-Linux-SGX [executable|manifest] args ...\n'

    def run_binary(self, args, *, timeout=None, **kwds):
        ... blablabla ...
            if process.returncode:
                raise subprocess.CalledProcessError(
>                   process.returncode, args, stdout, stderr)
E               subprocess.CalledProcessError: Command '['fakenews']' returned non-zero exit status 234

../../Scripts/regression.py:47: CalledProcessError

```

And this (*not sure what happens here*):
```
____________________ TC_40_AVXDisable.test_000_avx_disable _____________________

self = <test.TC_40_AVXDisable testMethod=test_000_avx_disable>

    def test_000_avx_disable(self):
        # Disable AVX bit in XFRM
        stdout, stderr = self.run_binary(['AvxDisable'])
>       self.assertIn('Illegal instruction executed in enclave', stderr)
E       AssertionError: 'Illegal instruction executed in enclave' not found in ''

test.py:620: AssertionError
```

**Comment by dimakuv** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
@woju , please fix the build issue:
```
make pal-regression.xml
make[1]: Entering directory '/home/jenkins/workspace/graphene-debug/Pal/regression'
make[1]: *** No rule to make target 'test.py', needed by 'pal-regression.xml'.  Stop.
make[1]: Leaving directory '/home/jenkins/workspace/graphene-debug/Pal/regression'
Makefile:82: recipe for target 'regression' failed
make: *** [regression] Error 2
```

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Still fails. Problems:

`graphene` pipeline:
```
=================================== FAILURES ===================================
___________ TC_01_Bootstrap.test_140_missing_executable_and_manifest ___________

self = <test_pal.TC_01_Bootstrap testMethod=test_140_missing_executable_and_manifest>

    def test_140_missing_executable_and_manifest(self):
        try:
            self.run_binary(['fakenews'])
>           self.fail('expected non-zero returncode')
E           AssertionError: expected non-zero returncode

test_pal.py:143: AssertionError
========= 1 failed, 32 passed, 4 skipped, 15 xfailed in 12.25 seconds ==========
Makefile:86: recipe for target 'pal-regression.xml' failed
make[1]: *** [pal-regression.xml] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/graphene/Pal/regression'
Makefile:82: recipe for target 'regression' failed
make: *** [regression] Error 2
```

and

```
Recording test results
[Pipeline] junit
Recording test results
No test report files were found. Configuration error?
Error when executing always post condition:
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
```

`graphene-debug` pipeline: same as above

`graphene-sgx` pipeline:

```
=================================== FAILURES ===================================
___________ TC_01_Bootstrap.test_140_missing_executable_and_manifest ___________

self = <test_pal.TC_01_Bootstrap testMethod=test_140_missing_executable_and_manifest>

    def test_140_missing_executable_and_manifest(self):
        try:
            self.run_binary(['fakenews'])
            self.fail('expected non-zero returncode')
        except subprocess.CalledProcessError as e:
>           self.assertIn('USAGE: ', e.stderr)
E           TypeError: a bytes-like object is required, not 'str'

test_pal.py:145: TypeError
```

**Comment by woju** [comment]
Jenkins, retest this please.

**Comment by mkow** [comment]
SGX works now, but the other two fails exactly the same way as before.

**Comment by woju** [comment]
Jenkins, retest this please.

**Comment by woju** [comment]
Just pushed the branch rebased on current master. Let's see what Jenkins thinks about it.

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (timeout on `test_libos.TC_00_Bootstrap.test_202_vfork_and_exec`)

**Pull request merged**
