### PR TITLE
[Pal, LibOS] Fix compilation errors in Ubuntu 18.04

### PR DESCRIPTION
**Pull request by chiache**
## Affected components

- [ ] README and global configuration
- [x] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

This code is tested to pass compilation on both 18.04 on 16.04. Will test with Jenkins 18.04 later.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/792)

### CODE REVIEW

**Comment by dimakuv** [comment]
Retest Jenkins please

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by chiache** [comment]
Retest Jenkins-SGX please

**Comment by dimakuv** [comment]
Retest Jenkins-SGX (this starts to get suspicious, random failures on Pal/LibOS regression tests...)

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Pull request merged**
