### PR TITLE
[LibOS] Small random IPC cleanups

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Just stuff that was annoying to work with in other PRs. For description about changes refer to specific commit messages.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1912)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1912)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1912)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 210 at r1](https://reviewable.io/reviews/oscarlab/graphene/1912#-MKEPOJX77idl7Ctn5sk:-MKEPOJX77idl7Ctn5sl:b-96bhbi) ([raw file](https://github.com/oscarlab/graphene/blob/87764296ff964700f287464038c2447f4b23c54e/LibOS/shim/include/shim_ipc.h#L210)):*
> ```objc
> } __attribute__((packed));
> 
> int ipc_lease_send(void);
> ```

Now some of these IPC messages and functions have weird names. For example, `ipc_lease_send` should be renamed to smth like `ipc_request_range_send()`. This is for a future PR...
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1054 at r1](https://reviewable.io/reviews/oscarlab/graphene/1912#-MKERAVrBgs1JtnAuwg8:-MKERAVrBgs1JtnAuwg9:b9nne3d) ([raw file](https://github.com/oscarlab/graphene/blob/87764296ff964700f287464038c2447f4b23c54e/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1054)):*
> ```C
>             void** priv = obj ? obj->private : NULL;
>             if (priv)
>                 *priv = NULL;
> ```

These three lines are technically not needed because `ipc_lease_send()` sets the private field of the message to NULL (there is not private data to update). I'll remove it during final rebase.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1063 at r1](https://reviewable.io/reviews/oscarlab/graphene/1912#-MKERaJ0-5K-kAfBKKOs:-MKERaJ19Fej5fKCjx0x:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/87764296ff964700f287464038c2447f4b23c54e/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1063)):*
> ```C
>                 void** priv = obj->private;
>                 if (priv)
>                     *priv = NULL;
> ```

ditto
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1078 at r1](https://reviewable.io/reviews/oscarlab/graphene/1912#-MKERsvoAHQWTkzIvNZT:-MKERsvoAHQWTkzIvNZU:batkit0) ([raw file](https://github.com/oscarlab/graphene/blob/87764296ff964700f287464038c2447f4b23c54e/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1078)):*
> ```C
> 
> /* TODO: unused */
> int ipc_renew_send(IDTYPE base, IDTYPE size) {
> ```

Now that we don't have leases, this `renew` IPC message is totally useless.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1912)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1078 at r1](https://reviewable.io/reviews/oscarlab/graphene/1912#-MKERsvoAHQWTkzIvNZT:-MKESoHn9f9meBvdgljC:b-8lsuhn) ([raw file](https://github.com/oscarlab/graphene/blob/87764296ff964700f287464038c2447f4b23c54e/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1078)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we don't have leases, this `renew` IPC message is totally useless.
</blockquote></details>

OK, actually let's do it in a follow up PR.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1912)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
