### PR TITLE
[LibOS] Remove unused code

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This PR removes some unused code from LibOS, the biggest part of which being the support for "inline" binaries linked directly against LibOS.

Some funny thing this PR removes is `POINTER_TYPE()` macro, which was supposed to check if a type is a pointer type, but implemented the check based only on the first 2 characters of the type name (?!?). This resulted in e.g. `void` being treated as a pointer, but `int*` as a non-pointer type. The only code which depended on this was in unused shim/test/inline directory, which actually ignored all syscall return values, basically putting all the work of `POINTER_TYPE()` and `EXPORT_SHIM_SYSCALL()` in vain.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
So far shim/test/inlne includes small test cases which haven't tested for long time.
+1 for removing it.

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822#-:-MHOg2I2329LznHjqQ2C:bokoy34)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX57e0AIoBTAz54a2g:-MHX57e0AIoBTAz54a2h:b-bw3upw) ([raw file](https://github.com/oscarlab/graphene/blob/f7aca7e962cc7566a2273908a8ba435e2591ca10/LibOS/shim/include/shim_internal.h#L11)):*
> ```objc
> #define _SHIM_INTERNAL_H_
> 
> #ifndef IN_SHIM
> ```

Why did you remove this ifdef?
___
*[LibOS/shim/include/shim_internal.h, line 329 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX5ubVCyXhUpGyCD1l:-MHX5ubVCyXhUpGyCD1m:b-htq19o) ([raw file](https://github.com/oscarlab/graphene/blob/f1ef94ac2a9f112bdf796a4d705b89d93275db0e/LibOS/shim/include/shim_internal.h#L329)):*
> ```objc
> 
> /* Some SHIM internal errno */
> #define ENOTLINK     143 /* the path is not a link */
> ```

This could be removed: it is used in one place only, where we actually could just use `EINVAL`.
___
*[LibOS/shim/include/shim_internal.h, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX5cNZ6uil2rjzqeh5:-MHX5cNZ6uil2rjzqeh6:bvuf3q7) ([raw file](https://github.com/oscarlab/graphene/blob/f1ef94ac2a9f112bdf796a4d705b89d93275db0e/LibOS/shim/include/shim_internal.h#L330)):*
> ```objc
> /* Some SHIM internal errno */
> #define ENOTLINK     143 /* the path is not a link */
> #define ESKIPPED     144 /* skip looking up current path */
> ```

`ESKIPPED` is not used anywhere (except some asserts), please remove it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: 15 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX57e0AIoBTAz54a2g:-MHXIdli54Xt5N2dywOi:b5q6n9z) ([raw file](https://github.com/oscarlab/graphene/blob/f7aca7e962cc7566a2273908a8ba435e2591ca10/LibOS/shim/include/shim_internal.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove this ifdef?
</blockquote></details>

Because now we don't have any place which uses shim headers outside of shim. But I left the preprocessor define for the shared code (in Pal/lib), which in some cases needs to be able to tell where it's included from.
Also, other shim includes don't have such an ifdef.
___
*[LibOS/shim/include/shim_internal.h, line 329 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX5ubVCyXhUpGyCD1l:-MHXJ3pH7w4GYotT3kV9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f1ef94ac2a9f112bdf796a4d705b89d93275db0e/LibOS/shim/include/shim_internal.h#L329)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This could be removed: it is used in one place only, where we actually could just use `EINVAL`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX5cNZ6uil2rjzqeh5:-MHXJ47m5ico0HqP7Zm2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f1ef94ac2a9f112bdf796a4d705b89d93275db0e/LibOS/shim/include/shim_internal.h#L330)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`ESKIPPED` is not used anywhere (except some asserts), please remove it.
</blockquote></details>

Done.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_internal.h, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX57e0AIoBTAz54a2g:-MHXRqM2AG1ULcmkAMkL:b-di6swg) ([raw file](https://github.com/oscarlab/graphene/blob/f7aca7e962cc7566a2273908a8ba435e2591ca10/LibOS/shim/include/shim_internal.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo this was a good assert/sanity check. E.g. `spinlock.h` includes this file based on `IN_SHIM` being defined or not - would be good to have an assert, so that this doesn't get included in Pal accidentally.
</blockquote></details>

What about other shim headers? Should we guard them all? To be honest, instead of guarding it this way I'd rather just don't add shim includes to the include path for PAL (except for pal lib).

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_internal.h, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX57e0AIoBTAz54a2g:-MHXt5bU2fRaha5SW3LL:b1kivms) ([raw file](https://github.com/oscarlab/graphene/blob/f7aca7e962cc7566a2273908a8ba435e2591ca10/LibOS/shim/include/shim_internal.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about other shim headers? Should we guard them all? To be honest, instead of guarding it this way I'd rather just don't add shim includes to the include path for PAL (except for pal lib).
</blockquote></details>

Only case I wanted to assert for was when such header is included in another one, which is shared between Pal and LibOS (e.g. spinlocks) - this should be annotated in all such headers that are shared. 
Resolving for now, as I do not consider this to be such a big deal.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_internal.h, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/1822#-MHX57e0AIoBTAz54a2g:-MHXuki49ItdIO8tsAv6:b4dg20i) ([raw file](https://github.com/oscarlab/graphene/blob/f7aca7e962cc7566a2273908a8ba435e2591ca10/LibOS/shim/include/shim_internal.h#L11)):*
> this should be annotated in all such headers that are shared.

But we don't know which LibOS headers are supposed to be shared for such libraries. I don't see why only some of them should have an assert.

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1822)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
