### PR TITLE
[LibOS] Add readlinkat syscall implementation

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Add readlinkat syscall implementation

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_table.h, line 479 at r1](https://reviewable.io/reviews/oscarlab/graphene/1796#-MGPv3UA5AShpEwV4edh:-MGPv3UBDHLfOAeLqDLl:ba90r0b) ([raw file](https://github.com/oscarlab/graphene/blob/6d16931ac066a162457a84fa362042994758dbe9/LibOS/shim/include/shim_table.h#L479)):*
> ```objc
> int shim_do_newfstatat(int dirfd, const char* pathname, struct stat* statbuf, int flags);
> int shim_do_unlinkat(int dfd, const char* pathname, int flag);
> int shim_do_readlinkat(int dirfd, const char* file, char* buf, size_t bufsize);
> ```

the original syscall (unfortunately) takes `bufsize` as `int`: https://elixir.bootlin.com/linux/v5.8.6/source/fs/stat.c#L443

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1796#-MGPw4bT6B9beG_a7x3p:-MGPw4bT6B9beG_a7x3q:bhbz8mz) (no related file):*
Do readlinkat* tests from LTP work now maybe? If not, could you add a comment in ltp.cfg why they are still not passing?

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1796#-MGPw4bT6B9beG_a7x3p:-MGQ4rsBAVrl12i4K2ke:bqu3k76) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do readlinkat* tests from LTP work now maybe? If not, could you add a comment in ltp.cfg why they are still not passing?
</blockquote></details>

They do not work, because `symlink*` syscalls are not implemented - at least that's one reason, no idea if they would work if it was implemented. I'm not sure if that's worth a comment there, but I could add it, if you think otherwise.

---
___
*[LibOS/shim/include/shim_table.h, line 479 at r1](https://reviewable.io/reviews/oscarlab/graphene/1796#-MGPv3UA5AShpEwV4edh:-MGQ58n06erjqP0Sqrt4:b-3bdbwm) ([raw file](https://github.com/oscarlab/graphene/blob/6d16931ac066a162457a84fa362042994758dbe9/LibOS/shim/include/shim_table.h#L479)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

the original syscall (unfortunately) takes `bufsize` as `int`: https://elixir.bootlin.com/linux/v5.8.6/source/fs/stat.c#L443
</blockquote></details>

Jeez...
Then I guess I should change `symlink` signature as well (I just copied it and added first argument) ...

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: 1 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/include/shim_table.h, line 479 at r1](https://reviewable.io/reviews/oscarlab/graphene/1796#-MGPv3UA5AShpEwV4edh:-MGQ7_VCAq9DOKlB9VM8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6d16931ac066a162457a84fa362042994758dbe9/LibOS/shim/include/shim_table.h#L479)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Jeez...
Then I guess I should change `symlink` signature as well (I just copied it and added first argument) ...
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1796)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
