### PR TITLE
Misc jenkins fixes 2020.11

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

- do not run LTP under SGX
- misc refactor (no functional change)
- run meson build stage

This is step 0 of the meson transition (the last one when meson is optional, building and testing without meson is fully supported). But the next one would be to test what meson installs, at which point the meson will be officially recommended.

## How to test this PR? 

jenkins build

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)

### CODE REVIEW

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: 0 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[meson.build, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNQU5iK2q_YCqE35kzJ:-MNQU5iLA05BvdUZ6vky:b-yecpe6) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/meson.build#L16)):*
> ```Meson
>     # https://wiki.ubuntu.com/Releases
>     # https://wiki.debian.org/DebianReleases#Production_Releases
>     meson_version: '>=0.45',
> ```

This is the version from bionic (18.04). On distros with older versions you need to install from pip3 (see dockerfile for xenial), which is easy, because meson promises to have no dependencies apart from ninja.

It is also tempting to also skip bionic and settle on 0.49 from buster (Debian 10), which would, among other things, allow some of those that I reverted:
- joining paths with `/`;
- `option(type: 'feature')`, which is convenient for packaging, but not really necessary;
- a better `import('python')` module, not `python3` which is deprecated (but still supported).

This is mostly relevant for average developer. There will be a point in time at which we'd all have to change our workflow and add meson to our dev setups. The question is, where we'd have to get meson from, distro's repo or pip. If most of the developers use 18.04, I wouldn't want to require them to install code from unsigned pypi packages.

This issue has also some remote relevance to possible packages maintained in distributions, because distros generally require that all build dependencies are also packaged (i.e., not downloaded from pip). But the earliest opportunity to be included in distro would be bullseye (Debian 11) and hirsute (Ubuntu 21.04). Both of them have currently 0.56. And it is very optimistic to assume we'd actually manage to get into distros until then.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 14 of 20 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[meson.build, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNQU5iK2q_YCqE35kzJ:-MNSpMTb2z6E8uZYkbwB:b-vysk0a) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/meson.build#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is the version from bionic (18.04). On distros with older versions you need to install from pip3 (see dockerfile for xenial), which is easy, because meson promises to have no dependencies apart from ninja.

It is also tempting to also skip bionic and settle on 0.49 from buster (Debian 10), which would, among other things, allow some of those that I reverted:
- joining paths with `/`;
- `option(type: 'feature')`, which is convenient for packaging, but not really necessary;
- a better `import('python')` module, not `python3` which is deprecated (but still supported).

This is mostly relevant for average developer. There will be a point in time at which we'd all have to change our workflow and add meson to our dev setups. The question is, where we'd have to get meson from, distro's repo or pip. If most of the developers use 18.04, I wouldn't want to require them to install code from unsigned pypi packages.

This issue has also some remote relevance to possible packages maintained in distributions, because distros generally require that all build dependencies are also packaged (i.e., not downloaded from pip). But the earliest opportunity to be included in distro would be bullseye (Debian 11) and hirsute (Ubuntu 21.04). Both of them have currently 0.56. And it is very optimistic to assume we'd actually manage to get into distros until then.
</blockquote></details>

Unfortunately, we are stuck with Ubuntu 18.04 for some time. So the current compromise is good.
___
*[.ci/lib/stage-test-regression.jenkinsfile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNSrJehEWFfMcBAD2Zz:-MNSrJehEWFfMcBAD2_-:b-53n9ie) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/.ci/lib/stage-test-regression.jenkinsfile#L9)):*
> ```
>             make ${MAKEOPTS} -C Pal/src/host/Linux-SGX/tools install \
>                 PREFIX=../../../../../../LibOS/shim/test/fs
>         fi
> ```

This is an artifact from the old Jenkins, maybe we should fix this now. Here, we ask to build and prepare all tests (`make .. test` and `make .. sgx-tokens`). But below, in each test directory, we perform the same actions again. That's why I even had to add a bogus `make clean && make all` to the `LibOS/shim/test/regression` case.

Let's finally remove this duplication. Basically, we'll need to move `RA_CLIENT_SPID` in this target and only keep `make regression`/`make test` in the other targets.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[meson.build, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNQU5iK2q_YCqE35kzJ:-MNStQxv7c8u7_2W1S7U:b2q9306) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unfortunately, we are stuck with Ubuntu 18.04 for some time. So the current compromise is good.
</blockquote></details>

OK, no problem. I'll leave the asciiart table for future reference. We'll need it in about 4 months when we'll hopefully deprecate xenial.
___
*[.ci/lib/stage-test-regression.jenkinsfile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNSrJehEWFfMcBAD2Zz:-MNSstHP1qmpLhxZ4pNZ:b-317xny) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/.ci/lib/stage-test-regression.jenkinsfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is an artifact from the old Jenkins, maybe we should fix this now. Here, we ask to build and prepare all tests (`make .. test` and `make .. sgx-tokens`). But below, in each test directory, we perform the same actions again. That's why I even had to add a bogus `make clean && make all` to the `LibOS/shim/test/regression` case.

Let's finally remove this duplication. Basically, we'll need to move `RA_CLIENT_SPID` in this target and only keep `make regression`/`make test` in the other targets.
</blockquote></details>

Should `make -C */tools install` remain?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[.ci/lib/stage-test-regression.jenkinsfile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNSrJehEWFfMcBAD2Zz:-MNSuCaW9ANpeLHiCsnm:by3jgh1) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/.ci/lib/stage-test-regression.jenkinsfile#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Should `make -C */tools install` remain?
</blockquote></details>

Yes, this should remain (unless you want to fix this hacky way of building dependencies required for this particular test).

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[.ci/lib/stage-test-regression.jenkinsfile, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNSrJehEWFfMcBAD2Zz:-MNSxCFK0wItlk09a-Qm:ble8exu) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/.ci/lib/stage-test-regression.jenkinsfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this should remain (unless you want to fix this hacky way of building dependencies required for this particular test).
</blockquote></details>

Thanks for the warning. Yeah, not now.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 12 of 20 files at r1, 8 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[meson.build, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNQU5iK2q_YCqE35kzJ:-MNTTZeOBAd5KNCMVOw7:b-eah1hd) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/meson.build#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, no problem. I'll leave the asciiart table for future reference. We'll need it in about 4 months when we'll hopefully deprecate xenial.
</blockquote></details>

FYI: After we have proper packaging for Graphene I'd be completely fine with requiring very new distros for building and keeping the compatibility with older distros only in runtime. This way we could benefit from new compiler stuff (e.g. more&better sanitizers) and won't need to fight with old compiler bugs.
___
*[.ci/lib/stage-test-all-nosgx.jenkinsfile, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNTVFOy06gf3IRcxSPM:-MNTVFOy06gf3IRcxSPN:bdgbchp) ([raw file](https://github.com/oscarlab/graphene/blob/a3519716efc77c2e677f9640b58b90653c64e8f9/.ci/lib/stage-test-all-nosgx.jenkinsfile#L1)):*
> ```
> stage('test') {
> ```

The name of this file is now misleading, it's not "all", it's only LTP. Ditto for all "all"s.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: 12 of 23 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[meson.build, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNQU5iK2q_YCqE35kzJ:-MNXurWuCpIcOwsncOES:bi7w35c) ([raw file](https://github.com/oscarlab/graphene/blob/e7d81050d209507ae0a3b6e20927eecb4ad20a4a/meson.build#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: After we have proper packaging for Graphene I'd be completely fine with requiring very new distros for building and keeping the compatibility with older distros only in runtime. This way we could benefit from new compiler stuff (e.g. more&better sanitizers) and won't need to fight with old compiler bugs.
</blockquote></details>

No, developers need to have easy setup. As long as most of them use 18.04, we need to support distro packages from that.
___
*[.ci/lib/stage-test-all-nosgx.jenkinsfile, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNTVFOy06gf3IRcxSPM:-MNYdxTc00o8aFKY_ixe:b73gq3s) ([raw file](https://github.com/oscarlab/graphene/blob/a3519716efc77c2e677f9640b58b90653c64e8f9/.ci/lib/stage-test-all-nosgx.jenkinsfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The name of this file is now misleading, it's not "all", it's only LTP. Ditto for all "all"s.
</blockquote></details>

Renamed them to `test`, `test-direct` and `test-sgx`.

**Review by mkow — APPROVED** [review]
> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[.ci/lib/stage-test-all-nosgx.jenkinsfile, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNTVFOy06gf3IRcxSPM:-MNYp04o3N30SwVFqc-1:b89pq9f) ([raw file](https://github.com/oscarlab/graphene/blob/a3519716efc77c2e677f9640b58b90653c64e8f9/.ci/lib/stage-test-all-nosgx.jenkinsfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Renamed them to `test`, `test-direct` and `test-sgx`.
</blockquote></details>

I don't like the new names, e.g. "test-sgx" is testing only app examples on SGX, but the name sounds like this is the whole set of tests for SGX. But we can fix this later.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[.ci/lib/stage-test-all-nosgx.jenkinsfile, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNTVFOy06gf3IRcxSPM:-MNYpK0o8RFzgFNiKHJs:bh7g0t6) ([raw file](https://github.com/oscarlab/graphene/blob/a3519716efc77c2e677f9640b58b90653c64e8f9/.ci/lib/stage-test-all-nosgx.jenkinsfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like the new names, e.g. "test-sgx" is testing only app examples on SGX, but the name sounds like this is the whole set of tests for SGX. But we can fix this later.
</blockquote></details>

This is if we'd like to deduplicate it further, so the "apps" might not be applicable in the future.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[.ci/lib/stage-test-all-nosgx.jenkinsfile, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2003#-MNTVFOy06gf3IRcxSPM:-MN_QAUV61Mnqxn3pxUC:b22ubmh) ([raw file](https://github.com/oscarlab/graphene/blob/a3519716efc77c2e677f9640b58b90653c64e8f9/.ci/lib/stage-test-all-nosgx.jenkinsfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is if we'd like to deduplicate it further, so the "apps" might not be applicable in the future.
</blockquote></details>

But the reason for this split is just to minimize maximum of run times of all pipelines, not any logical split between SGX-specific tests and common part (i.e. the workload on SGX was arbitrarily halved).

**Review by dimakuv — APPROVED** [review]
> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2003)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
