### PR TITLE
Remove unnecessary locks used with xchg

### PR DESCRIPTION
**Pull request by mkow**

### CODE REVIEW

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by donporter** [comment]
Ok to test.

**Comment by donporter** [comment]
Hi @mkow .  Thanks for the patch.  Good eye.  

I will note that we are (probably) planning to retire xchg - see PR #83 .  xchg is only used in a few places, and could be replaced with other atomics.

Let's see how the code review on 83 goes, but if xchg survives. I do think your patch makes sense.

**Comment by mkow** [comment]
Sure, sounds like a good plan :)

**Comment by donporter** [comment]
I think this PR has been obviated.  But thanks for the help anyway.

**Pull request closed without merging**
