### PR TITLE
[LibOS] IPC kill messages and broadcast minor cleanup

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Described in commit messages.

## How to test this PR? 
New LibOS regression test added.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWkT5P5DbMnFY3SCO1U:-MWkT5P6Btva_tzcxusp:bae5gcb) (no related file):*
> [LibOS] Cleanup process killing via IPC

Should be "clean up" (verb)

---

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins please (killed by `SIGPWR` - known IPC issue)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx3h2u7iOe6XdaEmi2:-MWx3h2u7iOe6XdaEmi3:bjvmnvt) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L82)):*
> ```C
> 
> int ipc_kill_all(IDTYPE sender, int sig) {
>     return ipc_pid_kill_send(KILL_ALL, sender, /*dest_pid=*/0, /*target=*/0, sig);
> ```

In the commit message, you say:
```
Additionaly this commit fixes a bug: `KILL_ALL` IPC message sent id `0`
which actually did not kill any processes.
```

But in your new version, you still set `/*target=*/0`, which leads to `msgin->id = 0` in `ipc_pid_kill_send()`. So how is that that you fixed this bug?
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx1A4aDRGbUlQoczUA:-MWx1A4aDRGbUlQoczUB:btqf9sw) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L92)):*
> ```C
> 
>     if (msgin->signum == 0) {
>         /* If signal number is 0, then no signal is sent, but process existence is still checked. */
> ```

You moved this from `ipc_pid_kill_send()` to here `ipc_pid_kill_callback()`. So instead of "not sending a message to other processes", you "don't handle this signal" in the receiving process.

Thus, the comment is wrong now. Also, is this correct behavior? Is this what you intended to change?
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx1inQCeTiQZoLIVs8:-MWx1inQCeTiQZoLIVs9:b-17rttn) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L103)):*
> ```C
>             break;
>         case KILL_PROCESS:
>             assert(g_process.pid == msgin->id);
> ```

Does it make sense to have an assert here? After all, a malicious process could forge a KILL_PROCESS message to our good process, and now the good process just dies.
___
*[LibOS/shim/test/regression/kill_all.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx5mnwDFyU-VFQVGN6:-MWx5mnwDFyU-VFQVGN7:bjzb3f4) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

Wouldn't it be more interesting to create several children and grandchildren, and then do `kill(-1)` in one of the grandchildren? This would stress the "send KILL_ALL to leader process who then broadcasts it to all processes"?

You can also keep this test, and add one more test `kill_all_from_grandchild`.
___
*[LibOS/shim/test/regression/kill_all.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx4vJN9vESMVbVFc6f:-MWx4vJO0KRUUqqwPLNZ:bak5xb9) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L19)):*
> ```C
>             .tv_sec = 1,
>         };
>         if (nanosleep(&ts, NULL) < 0) {
> ```

Why not just use `sleep(1)`?
___
*[LibOS/shim/test/regression/kill_all.c, line 33 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx52CiBbH2um2x6RW3:-MWx52CiBbH2um2x6RW4:b-4xceam) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L33)):*
> ```C
>             err(1, "fork");
>         } else if (children[i] == 0) {
>             alarm(60 * N_CHILDREN);
> ```

What's the point of this?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWkT5P5DbMnFY3SCO1U:-MWx9Jc32AMomZBG3z8O:be6mdj4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [LibOS] Cleanup process killing via IPC

Should be "clean up" (verb)
</blockquote></details>

TODO: at rebase

---
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx3h2u7iOe6XdaEmi2:-MWx76SQ4r-6RvzKegwn:b-sitizr) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the commit message, you say:
```
Additionaly this commit fixes a bug: `KILL_ALL` IPC message sent id `0`
which actually did not kill any processes.
```

But in your new version, you still set `/*target=*/0`, which leads to `msgin->id = 0` in `ipc_pid_kill_send()`. So how is that that you fixed this bug?
</blockquote></details>

`KILL_ALL` actually kill all processes now :) `id` is not used for `KILL_ALL`, so we put `0` there. The bugfix happens in callback: we actually kill ourselves now, not blindly pass that `0`.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx1A4aDRGbUlQoczUA:-MWx7YQp8QLGTSbijhAV:b-igeqz2) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L92)):*
I understood `sent` in that comment as `sending a signal` - generic linux term - not as sending an IPC message - Graphene specific.
> is this correct behavior? 

I hope so. You cannot verify that the other process exists in the calling process (unless it's the IPC leader).
> Is this what you intended to change?

Yes it is what I wanted to change. The message return value is probably not checked atm, but I intend to change that.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx1inQCeTiQZoLIVs8:-MWx8Z1w0Pq4Y77xsV9d:b-ouebv2) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it make sense to have an assert here? After all, a malicious process could forge a KILL_PROCESS message to our good process, and now the good process just dies.
</blockquote></details>

If we have a malicious process inside Graphene instance we are doomed anyway.
___
*[LibOS/shim/test/regression/kill_all.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx5mnwDFyU-VFQVGN6:-MWx8kWc8lXfFDAiXo-C:b-u41cfd) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it be more interesting to create several children and grandchildren, and then do `kill(-1)` in one of the grandchildren? This would stress the "send KILL_ALL to leader process who then broadcasts it to all processes"?

You can also keep this test, and add one more test `kill_all_from_grandchild`.
</blockquote></details>

It would be, but then the IPC leader will die and everything will blow up. Graphene is not yet ready for such scenario.
___
*[LibOS/shim/test/regression/kill_all.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx4vJN9vESMVbVFc6f:-MWx8rNI11Gw5R8Efggy:b2c0tu2) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just use `sleep(1)`?
</blockquote></details>

Because `sleep` can be implemented using `SIGALRM` and we use `alarm` in this test.
___
*[LibOS/shim/test/regression/kill_all.c, line 33 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx52CiBbH2um2x6RW3:-MWx90RQA-oJsuDzdK5K:bv272bg) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this?
</blockquote></details>

If something freezes due to bugs in IPC, the testing suite will probably kill only the main process.
Scaling is done to avoid issues with SGX, where each `fork` takes time.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx3h2u7iOe6XdaEmi2:-MWxAeQE7Gdo93QDo4Bf:bpx8e9t) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`KILL_ALL` actually kill all processes now :) `id` is not used for `KILL_ALL`, so we put `0` there. The bugfix happens in callback: we actually kill ourselves now, not blindly pass that `0`.
</blockquote></details>

Ok, got it now. The bug fix was actually here: `do_kill_proc(msgin->sender, msgin->id, ...` -> `do_kill_proc(msgin->sender, g_process.pid, ...`.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx1inQCeTiQZoLIVs8:-MWxAqLC1PaTttwaO3Ib:b-ulgucd) ([raw file](https://github.com/oscarlab/graphene/blob/543f74b78b7c00268b39a795fe2cc1e343fe471b/LibOS/shim/src/ipc/shim_ipc_pid.c#L103)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If we have a malicious process inside Graphene instance we are doomed anyway.
</blockquote></details>

Ok, fair enough. We have all IPC TLS-protected, so yeah, the only way to get a forged KILL_PROCESS is if some Graphene process is malicious (what I meant in the original comment is a non-graphene malicious process).
___
*[LibOS/shim/test/regression/kill_all.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx5mnwDFyU-VFQVGN6:-MWxB9So429dkxknhKzj:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It would be, but then the IPC leader will die and everything will blow up. Graphene is not yet ready for such scenario.
</blockquote></details>

OK
___
*[LibOS/shim/test/regression/kill_all.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx4vJN9vESMVbVFc6f:-MWxBBYm5PuilpnMaL13:b-qs3iad) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because `sleep` can be implemented using `SIGALRM` and we use `alarm` in this test.
</blockquote></details>

OK, that's subtle. Maybe add a comment on this during rebase?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWkT5P5DbMnFY3SCO1U:-MWxEsgd1weVp4ckV1wF:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.

---
___
*[LibOS/shim/test/regression/kill_all.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2276#-MWx4vJN9vESMVbVFc6f:-MWxEOxy6nNv5OXNGfwl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d9cb5252d5a1c07919e8c4a24815b483344cc4a/LibOS/shim/test/regression/kill_all.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, that's subtle. Maybe add a comment on this during rebase?
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2276)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure everything is ok)

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure everything is ok)

**Pull request merged**
