### PR TITLE
Version v1.2-rc1

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This is the proposed commit for v1.2-rc1 tagging. Please validate the current state carefully and check if there aren't any blockers. If not, this will be the release candidate for 1.2.

There will also be a changelog, but this will be added to GitHub release notes when we publish it.

## How to test this PR? 

Run everything you know :)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2518)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2518)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2518)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2518#-Me0N0V08ZEUwRjB-7SP:-Me0N0V1BYp9Oyh0KdIj:b2kl2ip) (no related file):*
Blocking until @jinengandhi-intel's team validates this commit.

---

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2518)* status: all files reviewed, 1 unresolved discussion

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2518)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2518#-Me0N0V08ZEUwRjB-7SP:-Me605FM8PYuB4Sfpw21:b-fvasif) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until @jinengandhi-intel's team validates this commit.
</blockquote></details>

Jinen tested this commit on various configurations and confirmed that there are no unexpected problems there and we should be able to tag this as v1.2-rc1.

---

**Pull request merged**
