### PR TITLE
[Pal/lib] Add strncmp() and strspn() string manipulation funcs

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

These functions are required by the TOML C source code, which will be embedded into Graphene in a future PR.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-gsc please (Jenkins was restarted in the meantime)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/include/lib/api.h, line 129 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc21a06xOuQ0JbMGtn:-MJc21a06xOuQ0JbMGto:bw7pdfl) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/include/lib/api.h#L129)):*
> ```objc
> size_t strnlen(const char* str, size_t maxlen);
> size_t strlen(const char* str);
> int strncmp(const char *lhs, const char *rhs, size_t maxlen);
> ```

Please fix formatting
___
*[Pal/lib/string/strcmp.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc1_VZAWTaKQWHz36E:-MJc1_VZAWTaKQWHz36F:b204qjl) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strcmp.c#L13)):*
> ```C
> }
> 
> int strncmp(const char *lhs, const char *rhs, size_t maxlen) {
> ```

please fix formatting
___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJc0LM84rP7fEtS8uIr:b-kxg104) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
> ```C
>    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
>    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
>    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
> ```

Hmm, the original source doesn't have this huge boilerplate banner, do we really need it? See https://git.musl-libc.org/cgit/musl/tree/src/string/strspn.c.
___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc2BxlDPeSdTB3poQQ:-MJc2BxlDPeSdTB3poQR:b-7h4yxu) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
> ```C
>    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
>    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
>    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
> ```

Please add a note about the musl version you've taken this from.
___
*[Pal/lib/string/strspn.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0vwH666kceXV2fvN:-MJc0vwIE_8RCbQ-Yr5h:b-3ukmam) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L28)):*
> ```C
> 
> size_t strspn(const char* s, const char* c) {
>     const char *a = s;
> ```

`const char *a` -> `const char* a`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: 2 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/include/lib/api.h, line 129 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc21a06xOuQ0JbMGtn:-MJfCusj0ByJGVljvrMi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/include/lib/api.h#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix formatting
</blockquote></details>

Done.
___
*[Pal/lib/string/strcmp.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc1_VZAWTaKQWHz36E:-MJfD0YwCyQ2CA7j7dxM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strcmp.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix formatting
</blockquote></details>

Done.
___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJfD6VUDmQz-W_0TQGM:b6zyjpw) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, the original source doesn't have this huge boilerplate banner, do we really need it? See https://git.musl-libc.org/cgit/musl/tree/src/string/strspn.c.
</blockquote></details>

I copied their copyright top-level file: https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT. I think the copyright should stay in this file, no? Maybe in a shorter form though? Like this:
```
/* Adapted from musl v1.2.1. Copyright © 2005-2020 Rich Felker, et al. */
```
___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc2BxlDPeSdTB3poQQ:-MJfDqng63zlhSnG_6P3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a note about the musl version you've taken this from.
</blockquote></details>

Done.
___
*[Pal/lib/string/strspn.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0vwH666kceXV2fvN:-MJfDuW_8VrPjjoDSGXh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`const char *a` -> `const char* a`
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJfy8yHAm_NIg9oNqrS:b2h317y) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I copied their copyright top-level file: https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT. I think the copyright should stay in this file, no? Maybe in a shorter form though? Like this:
```
/* Adapted from musl v1.2.1. Copyright © 2005-2020 Rich Felker, et al. */
```
</blockquote></details>

Yup, the shorter is preferred, but please also add SPDX id to the top.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJgRoUG-QcF7xgkqUCA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, the shorter is preferred, but please also add SPDX id to the top.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJgTCHxEg1oFIrbaF5e:b64n3zz) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, but musl isn't on LGPL?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/lib/string/strspn.c, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1888#-MJc0LM84rP7fEtS8uIq:-MJgrwtaCFvr6GsigZag:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8339ae0fdf2acc9a45fcb61dccf417c5e444d550/Pal/lib/string/strspn.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but musl isn't on LGPL?
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1888)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Pull request merged**
