### PR TITLE
[Pal/Linux-SGX] Fix building with DEBUGOPT=1

### LINKED ISSUE #2456: Graphene SGX not building with DEBUGOPT=1
## Description of the problem

To collect the perf record for workloads I was trying to following the instructions in the Graphene docs for SGX profiling and there it mentions about building Graphene with SGX=1 and DEBUGOPT=1 flag but when I tried that on the latest Graphene I am getting build errors. Please find attached the build log with the error.
```
In file included from ../../../../common/include/api.h:440,
                 from ../../../include/pal_internal.h:14,
                 from elf-x86_64.h:11,
                 from sgx_profile.c:19:
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/features.h:424,
                 from /usr/include/errno.h:25,
                 from sgx_profile.c:14:
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
../../../../common/include/api_fortified.h:34:25: error: expected declaration specifiers or ‘...’ b
   34 | #define __api_bos0(ptr) __builtin_object_size(ptr, 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~
Makefile:116: recipe for target 'sgx_profile.o' failed
```
When I try to build the same for Graphene native, the build is successful. 

## Steps to reproduce

make SGX=1 DEBUGOPT=1 ISGX_DRIVER_PATH=""
[SGX_Debugopts.log](https://github.com/oscarlab/graphene/files/6667221/SGX_Debugopts.log)

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Fixes #2456.

## How to test this PR? 

Build with `SGX=1 DEBUGOPT=1` and test if profiling works.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)

### CODE REVIEW

**Review by jinengandhi-intel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1TFhZ7sT8RpSFxuZv:-Md1TFhZ7sT8RpSFxuZw:b-h4fz09) (no related file):*
I verified SGX profiling to work, both with your branch and after my proposed change.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1P-wR9wgQvgk_CrtX:-Md1P-wR9wgQvgk_CrtY:bq4bb7q) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5d022a901a11f47e3f01c809f687a70e7d872/Pal/src/host/Linux-SGX/sgx_profile.c#L13)):*
> ```C
> #ifdef DEBUG
> 
> #define USE_STDLIB
> ```

While technically we're not in no-stdlib setting here, we try not to include glibc headers, so `USE_STDLIB` should not be necessary. 

Actually, the problem seems to be with `"string.h"` below (it actually pulls in the glibc `<string.h>`... that looks like my mistake, sorry!)

I propose something like this (which compiles for me with `DEBUGOPT=1`):

```diff
-#define USE_STDLIB
-
-#include <assert.h>
-#include <errno.h>
+#include <asm/errno.h>
 #include <linux/limits.h>
 #include <stddef.h>
 
+#include "api.h"
 #include "cpu.h"
 #include "elf-x86_64.h"
 #include "elf/elf.h"
@@ -25,7 +23,6 @@
 #include "sgx_log.h"
 #include "sgx_tls.h"
 #include "spinlock.h"
-#include "string.h"
```

(`<assert.h>` and `<errno.h>` technically do not cause conflicts, but are not what we want).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2476#-MdGPdLeByD92sDITkO4:-MdGPdLf9hY0KXnPg5ig:b9nzy1) (no related file):*
> [Pal/Linux-SGX] Fix building with DEBUGOPT=1

Please add backticks in the commit message.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1P-wR9wgQvgk_CrtX:-MdGPuZp08b_lIbDTR__:b-5zlvfx) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5d022a901a11f47e3f01c809f687a70e7d872/Pal/src/host/Linux-SGX/sgx_profile.c#L13)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

While technically we're not in no-stdlib setting here, we try not to include glibc headers, so `USE_STDLIB` should not be necessary. 

Actually, the problem seems to be with `"string.h"` below (it actually pulls in the glibc `<string.h>`... that looks like my mistake, sorry!)

I propose something like this (which compiles for me with `DEBUGOPT=1`):

```diff
-#define USE_STDLIB
-
-#include <assert.h>
-#include <errno.h>
+#include <asm/errno.h>
 #include <linux/limits.h>
 #include <stddef.h>
 
+#include "api.h"
 #include "cpu.h"
 #include "elf-x86_64.h"
 #include "elf/elf.h"
@@ -25,7 +23,6 @@
 #include "sgx_log.h"
 #include "sgx_tls.h"
 #include "spinlock.h"
-#include "string.h"
```

(`<assert.h>` and `<errno.h>` technically do not cause conflicts, but are not what we want).
</blockquote></details>

+1 to Pawel's proposed change

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @jinengandhi-intel, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1TFhZ7sT8RpSFxuZv:-MdHm9o25c6Ht813q2t8:b-ucfknh) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I verified SGX profiling to work, both with your branch and after my proposed change.
</blockquote></details>

Thanks!

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2476#-MdGPdLeByD92sDITkO4:-MdHmBpQ2O8aogzUikEW:bk5odft) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> [Pal/Linux-SGX] Fix building with DEBUGOPT=1

Please add backticks in the commit message.
</blockquote></details>

Will do at rebase.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1P-wR9wgQvgk_CrtX:-MdHq7Qr7XSuuyTzXtYX:b-bzxwh1) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5d022a901a11f47e3f01c809f687a70e7d872/Pal/src/host/Linux-SGX/sgx_profile.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Pawel's proposed change
</blockquote></details>

We had a discussion with Paweł about how this should look like and ended up with a mixed version. The overall conclusion is that this will need a huge clean up anyways, which we'll do after woju's building rework (i.e. we should split api.h into utils and "graphene mini libc").

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2476#-Md1P-wR9wgQvgk_CrtX:-MdHqyegCPwo72twt2lM:b-x7w50u) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5d022a901a11f47e3f01c809f687a70e7d872/Pal/src/host/Linux-SGX/sgx_profile.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We had a discussion with Paweł about how this should look like and ended up with a mixed version. The overall conclusion is that this will need a huge clean up anyways, which we'll do after woju's building rework (i.e. we should split api.h into utils and "graphene mini libc").
</blockquote></details>

OK. I agree with splitting `api.h`, this is long overdue.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2476)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
