### PR TITLE
Improve errors in the loader

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Should help in cases like #2632 and #2633.

## How to test this PR? 

Try to run invalid/non-existent executables and check the errors printed.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2634)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2634)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2634)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2634)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2634)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
