### PR TITLE
[PR template] Move more text into comments

### PR DESCRIPTION
**Pull request by mkow**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes

Those are actually hints for the author of a PR, not for the later reader/reviewer, so they should be comments.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/701)

### CODE REVIEW

**Comment by dimakuv** [comment]
Retest Jenkins-Debug please

**Comment by dimakuv** [comment]
Retest Jenkins-SGX

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by mkow** [comment]
Retest Jenkins-SGX please (Jenkins DNS problems)

**Pull request merged**
