### PR TITLE
[Pal/Linux-SGX] Cleanups for pal-sgx-sign

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Cleanup

## How to test this PR? 
make SGX=1 clean
make SGX=1 -j32
make SGX_RUN=1 -j32
./pal_loader SGX helloworld

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1021)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by jiazhang0** [comment]
@mkow @yamahata Just drop the LE patch.

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
