### PR TITLE
[LibOS] Fix following the link in FS subsystem

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Found out that following a link was broken. Looks like it was a typo. Fixing the typo made my rework of `/proc` FS work.

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2015)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
Looks good, but I don't really understand all the code here. We need to rewrite it, it's unreadable...

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2015#-:-MNy1sDO-jHAqhAXuuIm:bfu1ci2)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_namei.c, line 376 at r1](https://reviewable.io/reviews/oscarlab/graphene/2015#-MNy1It2-2AVSvR1tcXe:-MNy1It2-2AVSvR1tcXf:b-ua5y2r) ([raw file](https://github.com/oscarlab/graphene/blob/d53729b20142275aa8728cef4aaca3ffbee4f88b/LibOS/shim/src/fs/shim_namei.c#L376)):*
> ```C
>                         /* FIXME: below logic assumes that target file is under chroot; this misses
>                          *        cases like `/dev/stdin` which is a link to `/proc/self/fd/0`
>                          *        (i.e., Graphene currently fails if target is under pseudo-FS) */
> ```

So, is this issue fixed now?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2015)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[LibOS/shim/src/fs/shim_namei.c, line 376 at r1](https://reviewable.io/reviews/oscarlab/graphene/2015#-MNy1It2-2AVSvR1tcXe:-MNy_Nj87mf66VUzYIll:bnpnqdd) ([raw file](https://github.com/oscarlab/graphene/blob/d53729b20142275aa8728cef4aaca3ffbee4f88b/LibOS/shim/src/fs/shim_namei.c#L376)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, is this issue fixed now?
</blockquote></details>

Yes. But for the particular example in the manifest, there is another bug that I fixed as part of the refactoring in https://github.com/oscarlab/graphene/pull/2016. I added "fixes #1387" in that other PR. But technically this issue of "target file always under chroot" is fixed in this PR.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2015)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2015)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
