### PR TITLE
changing ninja install command to ninja build install in cloud deployment documentation

### PR DESCRIPTION
**Pull request by codingwithblackcoffee**
## Description of the changes 
The previous cloud deployment stated that the installation command should be sudo ninja -C install instead of sudo ninja -C build install.

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2462)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2462)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @codingwithblackcoffee)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2462#-MchY6WY1ZLtumUlicKo:-MchY6WZ4fQn7ZEUgR2r:bckrilk) (no related file):*
Thanks for the PR!

Could you add a sign-off in the commit message? Just do `git commit --amend --signoff` and then force-push to github.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2462)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @codingwithblackcoffee)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2462#-Mci8d3s4kP3UqwG1FLb:-Mci8d3s4kP3UqwG1FLc:b-ssshml) (no related file):*
Please change your commit message to match our format (see commit history / our documentation for contributors). Additionally, please state what you changed/fixed, "update file_name" doesn't really say anything :)

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2462)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @codingwithblackcoffee)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2462#-MchY6WY1ZLtumUlicKo:-Mck80PyCBCMUiHWEEPs:b-lvll7x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for the PR!

Could you add a sign-off in the commit message? Just do `git commit --amend --signoff` and then force-push to github.
</blockquote></details>

The commit message is now wrong...

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2462)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @codingwithblackcoffee)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2462#-MchY6WY1ZLtumUlicKo:-MdGD1uA9AzTpjRZT8Di:b-fiqpzr) (no related file):*
> 64619611+codingwithblackcoffee@users.noreply.github.com

That's not a real email. We need some way of identifying the contributor, so please use a real email.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2462#-MdGDEZHDoT6SBKL6urx:-MdGDEZIAiJDhjahAZYF:bq3ei1f) (no related file):*
This PR now has 10 commits just to fix one line of docs... Could you please educate yourself about git and the git-rebase workflow, and re-submit this?

---

**Pull request closed without merging**
