### PR TITLE
[Pal-SGX] Remove redundant spinlocks implementation in sgx_thread.c

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
There was a redundant spinlocks implementation, used only in one file.
This PR removes it in favor of the one from `Pal/lib`

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1283)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (test_403_signalexit_multithread timedout)

**Comment by boryspoplawski** [comment]
Jenkins, retest  Jenkins-Debug-18.04 (apps.LTP.clock_nanosleep02 timedout)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (apps.LTP.clock_nanosleep02 timedout; forgot to be nice)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (`test_libos.TC_01_Bootstrap.test_200_exec` failed)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-apps please (`bw_tcp` from lmbench timed out)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-apps please (hmm, Jenkins didn't trigger on this last time?)

**Pull request merged**
