### PR TITLE
OCALL cleanup

### LINKED ISSUE #1109: [Pal/Linux-SGX] Clean up OCALLs
Graphene-SGX currently has 39 OCALLs. We must refactor them and clean up finally.

- [x] `ocall_print_string()` -- replace with `ocall_write(stderr)`
- [x] `ocall_map_untrusted()` and `ocall_unmap_untrusted()` -- rename to `mmap/munmap`
- [x] `ocall_alloc_untrusted()` -- replace with `ocall_mmap_untrusted()`
- [x] `ocall_wake_thread()` -- split into two: `ocall_resume_thread()` and `ocall_clone_thread()`
- [x] `ocall_sock_recv()` and `ocall_sock_recv_fd()` -- fuse into one: `ocall_recv()`
- [x] `ocall_sock_send()` and `ocall_sock_send_fd()` -- fuse into one: `ocall_send()`
- [x] `ocall_sock_listen()`/`ocall_sock_accept()`/`ocall_sock_connect()` -- remove `sock_` prefix
- [x] `ms_ocall_schedule_t` -- to remove, unused
- [x] `ocall_stat()` -- to remove, unused
- [ ] `sgx_enclave.c: __abort()` -- to remove? Update: this one is needed!

This should get rid of 4 OCALLs and add 1 OCALLs, and we'll end up with 36.

### PR DESCRIPTION
**Pull request by dimakuv**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Graphene-SGX currently has 39 OCALLs. This PR refactors them and cleans up.

- [x] `ocall_print_string()` -- replace with `ocall_write(stderr)`
- [x] `ocall_map_untrusted()` and `ocall_unmap_untrusted()` -- rename to `mmap/munmap`
- [x] `ocall_alloc_untrusted()` -- replace with `ocall_mmap_untrusted()`
- [x] `ocall_wake_thread()` -- split into two: `ocall_resume_thread()` and `ocall_clone_thread()`
- [x] `ocall_sock_recv()` and `ocall_sock_recv_fd()` -- fuse into one: `ocall_recv()`
- [x] `ocall_sock_send()` and `ocall_sock_send_fd()` -- fuse into one: `ocall_send()`
- [x] `ocall_sock_listen()`/`ocall_sock_accept()`/`ocall_sock_connect()` -- remove `sock_` prefix
- [x] `ms_ocall_schedule_t` -- to remove, unused
- [x] `ocall_stat()` -- to remove, unused

This PR gets rid of 4 OCALLs and adds 1 OCALL, and we end up with 36.

Closes #1109.

## How to test this PR? 

All tests must succeed.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1114)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`recv01` failed)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`recv01` failed)

**Comment by pangzi85480** [comment]
I found that since the commit[cf0f4c50796206a158f62704b4e2df2b9b9c7b6c] is merged, nginx run testcase failed.

SGX=1 ./pal_loader ./nginx.manifest -c conf/nginx-graphene.conf &
curl 127.0.0.1:8002

@dimakuv Do you have time to see what is probably causing it?

**Comment by dimakuv** [comment]
@pangzi85480 I tried it on the newest master (bae8baa2dd7e67b81f2af1b798d0b49d736ff539), I see no problems with Nginx. I ran it exactly as you specify in your comment. Everything seems to run smoothly (after the SGX enclave completely inits, of course, which takes ~30 seconds on my machine).

**Pull request merged**
