### PR TITLE
Change logging functions to always add an implicit newline

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Will make the `log_error()` censoring a bit simpler.

## How to test this PR? 

Grep code for the places I missed.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 106 of 106 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/regression/utils.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2486#-MdMzHoU0Ldb3yzJYih2:-MdMzHoV8d5ebJ76p0HQ:b-idrn4g) ([raw file](https://github.com/oscarlab/graphene/blob/326d894e4f62207c0be7a3e38937425781c95077/Pal/regression/utils.c#L12)):*
> ```C
> }
> 
> static void log_vprintf(const char* fmt, va_list ap, bool append_newline) {
> ```

But you don't use `append_newline` below

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: 105 of 106 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/regression/utils.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2486#-MdMzHoU0Ldb3yzJYih2:-MdN0ynA69VRsKG6x4nP:b-wwto7p) ([raw file](https://github.com/oscarlab/graphene/blob/326d894e4f62207c0be7a3e38937425781c95077/Pal/regression/utils.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you don't use `append_newline` below
</blockquote></details>

:facepalm:
I focused too much on verifying all callsites and missed this :)

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: 105 of 106 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2486#-MdN3rLc5D8nP_tLsSJd:-MdN3rLd7LX1yew4U6f5:b-wcsu0i) (no related file):*
>Grep code for the places I missed.

I searched for `\n"` and found:

* `DEBUG_RS("...\n")` in `shim_vma.c`
* `FATAL()` macros in sync code
*   `errstring = "only ET_DYN and ET_EXEC can be loaded\n";` in `shim_rtld.c`

There are also some multi-line logs, which is a bit bad (the subsequent lines end up without a prefix, right?), but that's for some other time.

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: 102 of 106 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2486#-MdN3rLc5D8nP_tLsSJd:-MdN6uPTAhatHBHXPfv0:b-usiigi) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Grep code for the places I missed.

I searched for `\n"` and found:

* `DEBUG_RS("...\n")` in `shim_vma.c`
* `FATAL()` macros in sync code
*   `errstring = "only ET_DYN and ET_EXEC can be loaded\n";` in `shim_rtld.c`

There are also some multi-line logs, which is a bit bad (the subsequent lines end up without a prefix, right?), but that's for some other time.
</blockquote></details>

Nice, I missed these! Thanks!

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by pwmarcz — DISMISSED** [review]
I did a quick pass with `git show --word-diff=color`, looks good.

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486#-:-MdNI4n-1EI_V05K_EyU:b3bf228)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
FYI: Jenkins-Debug-18.04 failed on some assert in IPC, which seems unrelated. CC: @boryspoplawski.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — COMMENTED** [review]
FWIW: Jenkins failed due to an unknown (not debugged) reason, but the assert that triggered in IPC code (after original issue) indeed showed a bug (#2487).

> Reviewed 10 of 106 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2486#-:-MdORtsj2MvJVka2hyhi:b-wdmnj4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
