### PR TITLE
Fix manifests for Bash

### PR DESCRIPTION
**Pull request by hanjae**
This PR fixes configuration errors when running Bash on SGX.

### CODE REVIEW

**Comment by donporter** [comment]
Nice fix.

Can you rebase to current master so that CI passes?

Also, would you mind adding some unit tests to our CI scripts for bash so that bash doesn't regress?

**Comment by donporter** [comment]
I'm a little confused about the wrong exec file commit; is that still active?

**Comment by hanjae** [comment]
@donporter No. I wanted to see it fails on Graphene-SGX Jenkins test with old wrong configuration. 
I'll fix it back after tests.

**Comment by hanjae** [comment]
This PR is ready to be merged

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Test this please

**Pull request merged**
