### PR TITLE
[LibOS] Completely rework LibOS VMA bookkeeping

### LINKED ISSUE #1028: How does VMA subsystem work in Graphene LibOS?
This is a question-issue to dump findings on the LibOS VMA logic.

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This commit completely reworks VMA subsystem along with its usages.
New version should be: cleaner (easier to maintain), faster (simple
tests show ~25% on memory heavy workloads) and allow for bookkeeping
requests from Pal.
It also fixes some bugs and inconsistencies found in the process and
changes brk and mmap/munmap implementations (at least partially).

Closes #1028 closes #1331

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1431)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (random Jenkins glitch ?)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (this is weird)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (LTP alarm02 timed out)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (lmbench internet connectivity)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX please (test_090_sighandler_reset failed with full signal queue).

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-18.04 please (failed to connect to docker sock)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX please (failed to connect to docker sock)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (failed to connect to docker sock)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Comment by boryspoplawski** [comment]
Jenkins, test this please (just making sure, 2/5)

**Comment by boryspoplawski** [comment]
Jenkins, test this please (just making sure, 3/5)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04-apps (lmbench download failed, unrelated)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04-apps please (forgot to be nice; lmbench download failed, unrelated)

**Comment by boryspoplawski** [comment]
Jenkins, test this please (just making sure, 4/5)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-apps please (lmbench download failed, unrelated)

**Comment by dimakuv** [comment]
Jenkins, test this please (just making sure, 5/5)

**Pull request merged**
