### PR TITLE
Reap zombies + miscellaneous fixes around exit calls

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This is a couple of simple commits stashed together (not to spam with PR, for easier merging - they are really simple).
For details check commit descriptions.

## How to test this PR? 
Normal tests + run some long living app spawning some temporary processes and observe lack of zombies.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug please (sendfile08 failed, known issue)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (landed on bobothebear, which is failing randomly today)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 293 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQygvXkDH65Fd3RP1Wt:-MQygvXkDH65Fd3RP1Wu:b-z31i0x) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux-SGX/db_main.c#L293)):*
> ```C
>     g_linux_state.uid = g_pal_sec.uid;
>     g_linux_state.gid = g_pal_sec.gid;
>     /* TODO: guard this from malicious host. Probably just fully randomize? */
> ```

Sounds like something which deserves an issue (because it's security-related, we shouldn't forget about it).

**Review by yamahata — DISMISSED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 25 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2083#-MR--63q34mKWu4QiL2D:-MR--63q34mKWu4QiL2E:bmvwxdt) (no related file):*
Please fix the first commit message, takes some time to understand what `ored` means:
`Previously Graphene ored process start time` -> `Previously Graphene ORed process start time` or `performed OR on process start time`

---
___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzyYDj2S9mrNmF0ZGX:-MQzyYDk4EUIG4HfZKo9:b-msxidw) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/ipc/shim_ipc_child.c#L32)):*
> ```C
>      */
>     if (mark_child_exited_by_vmid(vmid, /*uid=*/0, /*exit_code=*/0, SIGKILL)) {
>         debug("Child process (vmid: 0x%x) got disconnected\n", vmid & 0xffff);
> ```

Does it mean that we'll be finally able to see the exact same PIDs as Linux reports? This will be helpful when doing e.g. `strace -ff` and `loader.debug_type = inline` simultaneously, I won't need to map IDs anymore :)
___
*[Pal/src/host/Linux/db_exception.c, line 221 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzzNTs2ggjLXTk7NAb:-MQzzNTs2ggjLXTk7NAc:bjfb850) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux/db_exception.c#L221)):*
> ```C
>         goto err;
> 
>     ret = set_signal_handler(SIGCHLD, SIG_IGN);
> ```

Could you remind me why we couldn't do this before? Because we didn't have Michal's Big PR that removed the execve-in-new-process hack?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzziz34DHjeIsbheii:-MQzziz4CrYwrcUjyLj9:bcne9k9) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
> ```C
>     unmap_tcs();
>     INLINE_SYSCALL(munmap, 2, alt_stack, ALT_STACK_SIZE);
>     INLINE_SYSCALL(exit, 1, 0);
> ```

Just for uniformness, let's replace to `exit_group`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: 25 of 26 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2083#-MR--63q34mKWu4QiL2D:-MR0iOmr3d2cglg2aG8B:b32yv60) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix the first commit message, takes some time to understand what `ored` means:
`Previously Graphene ored process start time` -> `Previously Graphene ORed process start time` or `performed OR on process start time`
</blockquote></details>

Let's do in at the final rebase.

---
___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzyYDj2S9mrNmF0ZGX:-MR0iTDe3ZRWzg7GHmUO:b-b9i6sn) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/ipc/shim_ipc_child.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it mean that we'll be finally able to see the exact same PIDs as Linux reports? This will be helpful when doing e.g. `strace -ff` and `loader.debug_type = inline` simultaneously, I won't need to map IDs anymore :)
</blockquote></details>

Yes :)
Otoh that probably won't be the case on SGX when we fix it.
___
*[Pal/src/host/Linux/db_exception.c, line 221 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzzNTs2ggjLXTk7NAb:-MR0ibAZ77oeecHsfHQT:b-9tfja) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux/db_exception.c#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you remind me why we couldn't do this before? Because we didn't have Michal's Big PR that removed the execve-in-new-process hack?
</blockquote></details>

Yes, we had to wait in the intermediate execve process to obtain childs exit status. This was only needed if the execve was done in the very first Graphene process and the host wanted to wait for the child (e.g. interactive bash).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 293 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQygvXkDH65Fd3RP1Wt:-MR0j97i6o0tgF7n-akp:bv0jxid) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux-SGX/db_main.c#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds like something which deserves an issue (because it's security-related, we shouldn't forget about it).
</blockquote></details>

True, done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzziz34DHjeIsbheii:-MR0lrkcDynbfE0nZLal:b7v5s7n) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just for uniformness, let's replace to `exit_group`
</blockquote></details>

I've left this intentionally. If an enclave thread ever returns from ecall (I believe this cannot happen currently, but still, might in the future) we should not consider this a fatal error and kill every other thread.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Comment by dimakuv** [comment]
Jenkins, test this please (previous Jenkins run failed due to internal problems)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 26 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r1](https://reviewable.io/reviews/oscarlab/graphene/2083#-MQzziz34DHjeIsbheii:-MR46Rd6AzPvzO3_sfsQ:bv56fo0) ([raw file](https://github.com/oscarlab/graphene/blob/57cc58577a93ad5e8b500c16bee99f342b3586e9/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've left this intentionally. If an enclave thread ever returns from ecall (I believe this cannot happen currently, but still, might in the future) we should not consider this a fatal error and kill every other thread.
</blockquote></details>

OK, makes sense.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: 23 of 26 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2083#-MR--63q34mKWu4QiL2D:-MR5fbDE6pDYF4U16tje:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Let's do in at the final rebase.
</blockquote></details>

Done.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2083)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
