### PR TITLE
[PAL/Linux-SGX] Add external event sanitization

### LINKED ISSUE #598: [Linux-SGX PAL] Untrusted signal number during signal handling is not verified
Linux-SGX PAL retrieves the signal number (to decide which signal handler to invoke) based on `exit_info` argument passed to `_DkExceptionHandler()` (see [here](https://github.com/oscarlab/graphene/blob/4039813623ad88c710dfd80b79abcd583c325e50/Pal/src/host/Linux-SGX/db_exception.c#L191)).

This argument is initialized in `enclave_entry()` asm function. In particular, it consults trusted SGX struct SSA.GPRSGX.EXITINFO. If the VALID bit in this struct is set, then the passed `exit_info` argument is set to this field (and thus trusted). Otherwise the passed `exit_info` argument is taken from untrusted PAL (see `_DkTerminateSighandler()`).

1. We need to verify untrusted `exit_info` argument in `_DkExceptionHandler()`. Something like:
```c
    ...
    if (!ei.info.valid) {  /* case when we forward untrusted exit_info to LibOS */
        /* VERIFY HERE! */
        ... if exit_info not in (QUIT, SUSPEND, RESUME):  panic! ...
        event_num = exit_info;
        goto handle_event;
    }
   ...
```

2. Given that SIGINT, SIGCONT, and SIGTERM are untrusted, what kind of Iago attacks can happen? Analyze.

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Untrusted PAL can inject an external event (e.g. `PAL_EVENT_INTERRUPTED`). Such events need to be validated against a white list of valid events.

Fixes #598

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_exception.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2197#-MUfkfuq9ZtESJYymg8I:-MUfkfuq9ZtESJYymg8J:b-kks5qn) ([raw file](https://github.com/oscarlab/graphene/blob/1b4091292150b6b20d1352235c702741eb5539a3/Pal/src/host/Linux-SGX/db_exception.c#L190)):*
> ```C
>         switch (ei.info.vector) {
>             case SGX_EXCEPTION_VECTOR_BR:
>                 event_num = PAL_EVENT_NUM_BOUND;
> ```

`PAL_EVENT_NUM_BOUND` is not a valid event id. I've moved this case to the ignored group, but maybe we should exit the whole process on `BR` exception?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_exception.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2197#-MUfkfuq9ZtESJYymg8I:-MUh9F602Hb6UQ0edC38:b-olijhg) ([raw file](https://github.com/oscarlab/graphene/blob/1b4091292150b6b20d1352235c702741eb5539a3/Pal/src/host/Linux-SGX/db_exception.c#L190)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`PAL_EVENT_NUM_BOUND` is not a valid event id. I've moved this case to the ignored group, but maybe we should exit the whole process on `BR` exception?
</blockquote></details>

I would prefer to loudly fail on `#BR` exception. This will make it very clear to an app which uses the BOUND instruction/Intel MPX that Graphene doesn't support this. Maybe with a corresponding log error that `Graphene doesn't support #BR exceptions currently`.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_exception.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2197#-MUfkfuq9ZtESJYymg8I:-MUhkyj6B50hRdzIgkIN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1b4091292150b6b20d1352235c702741eb5539a3/Pal/src/host/Linux-SGX/db_exception.c#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to loudly fail on `#BR` exception. This will make it very clear to an app which uses the BOUND instruction/Intel MPX that Graphene doesn't support this. Maybe with a corresponding log error that `Graphene doesn't support #BR exceptions currently`.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2197)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
