### PR TITLE
[LibOS] fix sendfile to return EINVAL when out_fd has O_APPEND flag

### LINKED ISSUE #1967: [LibOS] wrong action of sendfile() when out_fd has the O_APPEND flag set
##  Description of the problem
According to sendfile() mannual `man sendfile`
```
SYNOPSIS
       ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);

ERRORS
       EINVAL out_fd has the O_APPEND flag set.  This is not currently supported by sendfile().
```
sendifle should return EINVAL when open out_fd with O_APPEND flag.
However current Graphene sendfile implementation doesn't check O_APPEND flag and tries to transfer data and transfers wrong data.

## Steps to reproduce
A sample `file.c`

```C
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/sendfile.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char** argv) {
    int in_fd = open(argv[1], O_RDONLY, 0600);
    if (in_fd < 0)
        return 1;

    int out_fd = open(argv[2], O_WRONLY | O_APPEND | O_CREAT, 0666);
    if (out_fd < 0)
        return 1;

    off_t offset = 0;
    size_t count = lseek(in_fd, 0, SEEK_END);
    if (count == (off_t)-1)
        perror("lseek");

    ssize_t size = sendfile(out_fd, in_fd, &offset, count);
    if (size < 0 )
        perror("sendfile");

    close(in_fd);
    close(out_fd);
}
```
run `SGX=1 ./pal_loader file test1 test2`   test1 is a regular file with 30 bytes.
-->

## Expected results
print
```
sendfile: Invalid argument
```
And `out_file` is 0 bytes length.
## Actual results
No error mesage, log is
```
[P5564:T1:file] ---- shim_openat(AT_FDCWD,"test1",O_RDONLY,0000) = 3
[P5564:T1:file] ---- shim_openat(AT_FDCWD,"test2",O_WRONLY|O_APPEND|O_CREAT,0666) = 4
[P5564:T1:file] ---- shim_lseek(3,0,SEEK_END) = 30
[P5564:T1:file] copy 30 bytes
[P5564:T1:file] ---- shim_sendfile(4,3,0x1796ee00,30) = 30
```
But test2 is 60 bytes length. 0 -30 Bytes is all 0s. 31-30 Bytes is same as test1.
## Additional information
I found this issue when trying to enable Spark. One Java function, maybe
```
        at java.lang.System.arraycopy(Native Method)
        at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:177)
```
firstly tries `sendfile`, then tries `mmap` /`write` to achieve better performance. `sendfile` is expected to return error in this case.
It's hard to locate this issue using Java because error is caught when using the output file in another place instead of when calling sendfile, though it looks simple in C code.

### PR DESCRIPTION
**Pull request by llly**
Current Graphene sendfile implementation doesn't check O_APPEND flag and tries to transfer data and transfers wrong data.

This commit updates sendfile to align with manual
 "EINVAL out_fd has the O_APPEND flag set.  This is not currently supported by sendfile()."

Also fixes not matched get_handle/put_handle. It can cause memory leak when only one of ofd/ifd is invalid.

fixes #1967

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1969#-MMFRKOx1PsB6Y87AVfU:-MMFRKOx1PsB6Y87AVfV:blz7aj0) (no related file):*
Minor, but we'll need to fix `shim_do_sendfile()` and its `handle_copy()` helper function... This PR is good, but there is more refactoring and error-checking to be done with these functions.

---

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1969#-MMG9hue3HEbkW_lap05:-MMG9hue3HEbkW_lap06:b-xzhlej) (no related file):*
Blocker for future me/Dima: we'll need to slightly reword the commit message when doing the final rebase.

---
___
*[LibOS/shim/src/sys/shim_fs.c, line 619 at r1](https://reviewable.io/reviews/oscarlab/graphene/1969#-MMGC1-ZB_pxBQlhF2vT:-MMGC1-ZB_pxBQlhF2vU:b-cuhlik) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0b3e4f54bee236be0e7f3845fed55c066f4ed/LibOS/shim/src/sys/shim_fs.c#L619)):*
> ```
> EINVAL out_fd has the O_APPEND flag set.
> ```

I don't understand this sentence, what were you trying to say here? Could you reword it?
Please also remove double space for consistency.
___
*[LibOS/shim/src/sys/shim_fs.c, line 619 at r1](https://reviewable.io/reviews/oscarlab/graphene/1969#-MMGVFWQBuMRwV8UVNSG:-MMGVFWQBuMRwV8UVNSH:b-m9ydj6) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0b3e4f54bee236be0e7f3845fed55c066f4ed/LibOS/shim/src/sys/shim_fs.c#L619)):*
> ```
> This is not currently supported by sendfile().
> ```

That's not the reason - I think we actually support it, but the Linux API requires returning EINVAL in this case. So, we fail here because that's what Linux API does.

**Review by yamahata — DISMISSED** [review]
expect comment wording, it looks good to me.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969#-:-MMHhzeoBXLTpC8N4ubl:b-9diuw4)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

**Comment by llly** [comment]
@mkow this comment is copied from `man sendfile`,

**Review by mkow — COMMENTED** [review]
@llly Which part exactly? Could you please reply in a proper Reviewable thread?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969#-:-MMJA4Wv8JaKSMI3efTv:b-rg6cya)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

**Review by llly — COMMENTED** [review]
`man sendfile`
```
NAME
       sendfile - transfer data between file descriptors

SYNOPSIS
       #include <sys/sendfile.h>

       ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);

ERRORS

       EINVAL out_fd has the O_APPEND flag set.  This is not currently supported by sendfile().
```

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969#-:-MMJnjs5C2j3p_NB4iV1:bb5e8q0)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly and @mkow)

___
*[LibOS/shim/src/sys/shim_fs.c, line 619 at r1](https://reviewable.io/reviews/oscarlab/graphene/1969#-MMGVFWQBuMRwV8UVNSG:-MMKNzBiBX065HuluvwQ:b-dfvu2y) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0b3e4f54bee236be0e7f3845fed55c066f4ed/LibOS/shim/src/sys/shim_fs.c#L619)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> This is not currently supported by sendfile().
> ```

That's not the reason - I think we actually support it, but the Linux API requires returning EINVAL in this case. So, we fail here because that's what Linux API does.
</blockquote></details>

I recommend to change like this:
```
int ret = -EINVAL;
if (hdlo->flags & O_APPEND) {
    /* Linux errors out if output fd has the O_APPEND flag set; comply with this behavior */
    goto out;
}
```

**Review by mkow — COMMENTED** [review]
@llly Please use Reviewable for the discussion, as asked above (and reply in the proper thread in the code diff)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969#-:-MMLTQ1h6y2TPDaSid2h:bmluoi)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly and @mkow)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly and @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @llly)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`sigsuspend01` LTP test failed; known issue)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (Internet connectivity)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (timeout on apache example? I guess because of the recently enabled debug output with DEBUG=1)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1969)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
