### PR TITLE
Update list.h to support additional list macros

### PR DESCRIPTION
**Pull request by sudharkrish**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [X] SGX PAL
- [X] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
These are changes to update list.h, to support additional features like size, and ability to sort list items. Changes are WIP and needs cleanup, submitting this PR, to get initial feedback.
Note: These updates were needed for protected-fs changes in PAL.

## How to test this PR? 
PAL regression testing

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1268)

### CODE REVIEW

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNO_Sh-ylV598WlNA_:-M-CPnNy1i35YXHIWAKG:btpnxle) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Please point to your PR which uses this PR.
> Without that, it's difficult to tell if this PR is really necessary or not.

Moving @yamahata  request to a blocking comment.
</blockquote></details>

@yamahata , this will be needed for protected-fs PR->1090, when it pulls in the updated SGX SDK's protected-fs, library(by replacing C++ STL list apis with C-based list implementation) into PAL.

---

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-Lz90bxO914d5I13H5HO:-M-CTeii73wJDFWJBy2w:b-reskbi) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L156)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>         int64_t size;         \
>         list_sort sort_fptr;  \
> ```

You can add new type instead of bloating the existing LISTP.
</blockquote></details>

These are additional attributes, that can enhance list, similar to some features supported by C++ STL list. Just for these additional features, creating a new type, will increase code-bloat due to duplicate code.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 147 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzCcknu-yNK09BwHg3k:-M-CWpsPAulwCPslw76V:b4tiaa1) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L147)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

and the typedef itself
</blockquote></details>

This is just for convenience.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNQYAx-iBcjD7jfB-I:-M-CX80k2uw20MvuvvoK:bsizr5c) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we need this as a member? I'd prefer to just have a "sort" function with a "comparator" argument, would be much easier do make it O(nlgn) this way.
</blockquote></details>

Not sure, about your suggestion, and how will that make it easier to make it O(nlgn). Can you elaborate.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNWLnp0d7VJWiDJqYd:-M-CXwYI34l8Nyq6OtKt:b26nkyw) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why do we need this field?
</blockquote></details>

Which field are you referring to.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 131 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNOjDT6imfu53cyAlS:-M-Hgsqv0F4v28r2QUit:b-e67hpc) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

space before `(`
</blockquote></details>

Code updated, comment not required.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 147 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzCcknu-yNK09BwHg3k:-M-I7Eon7kQO1wEfBniF:bczsrsi) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L147)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

this doesn’t depend on the type of NODE. 
something wrong. If you really want to define it, you need to twist type name and the type of argument.
const is desirable. and is the return value bool? not int for +- or 0?
</blockquote></details>

@yamahata Sorry, not following your comment.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 147 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzCcknu-yNK09BwHg3k:-M-R0McF8D6YtAx74w64:b8x0p1r) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L147)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

There are two issues.

- typedef
I meant something like this
#define LIST_SORT_FUNC_PTR_DECLARE(STRUCT_NAME) typedef bool (* STRUCT_NAME ## list_sort) (struct STRUCT_NAME* node1, struct STRUCT_NAME* node2)
I'm assuming you'd like to define typedef per STRUCT_NAME.
If you choose single typedef, you can simply typedef here without LIST_SORT_FUNC_PTR_DECLARE like
typedef bool (*list_sort)(void* node1, void* node2);

btw the name of "list_sort" is very confusing. It's actually comparator, not sorting function.

- return value: int instead of bool
  I scratch this part.
  In C, it's common to define compareter to return int
  In C++ STL, it's common to define comparator to return bool
  Here you'er immitating C++ list. So it's okay. 
</blockquote></details>

@yamahata I have removed macro->LIST_SORT_FUNC_PTR_DECLARE. The issue with having struct STRUCT_NAME inside the function declaration, is that if multiple files are including list.h with different type of list structures, then it results in compilation error, due to conflicting function declaration types for the function pointer.
So having a void type is generic, and avoids compilation error, when different types of list structures exist. Changed name of function to use compare, instead of sort.

**Comment by sudharkrish** [comment]
___
*[Pal/src/host/Linux-SGX/sgx-driver, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNWA2v5u3IBkR3IkGa:-M-ROPvs-4o0IsAHfyVU:b-5mt3k6) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/src/host/Linux-SGX/sgx-driver#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is this change here? Could you link to the related PR in this PR's description?
</blockquote></details>

@mkow This is an unrelated diff, due to some git submodule change, so please ignore this. Also, I have fixed as per some of your comments, and other comments from isaku. Can you take a look at the updated version.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 371 at r3](https://reviewable.io/reviews/oscarlab/graphene/1268#-M-VP_TI60EYNQGA-D1p:-M-Vxu6Q9bXT_9OQ63p5:bty0xcv) ([raw file](https://github.com/oscarlab/graphene/blob/e079767c6bde9eeafebfe70cf531694580fb93d7/Pal/lib/list.h#L371)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

 nitpick: unnnecesary code churn
</blockquote></details>

@yamahata , I think you are referring to code within macro->LISTP_FOR_EACH_ENTRY_SAFE. I have not modified this macro, this is existing code.

**Comment by sudharkrish** [comment]
@yamahata , can you let me know, if you are fine with the updates made to this PR.

**Comment by sudharkrish** [comment]
@mkow  can you let me know, if you are fine with the updates made to this PR.

**Comment by sudharkrish** [comment]
@omeg , please let me know, if you are fine with the updates made to this PR.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 371 at r3](https://reviewable.io/reviews/oscarlab/graphene/1268#-M-VP_TI60EYNQGA-D1p:-M-l-UN93yLKXPn6Arjj:b-hpdp09) ([raw file](https://github.com/oscarlab/graphene/blob/e079767c6bde9eeafebfe70cf531694580fb93d7/Pal/lib/list.h#L371)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

adding new blank line is unnecessary.
</blockquote></details>

@yamahata I have fixed additional comments from you. It will be easier if you can try to provide comments upfront. Anyway, hope I have addressed your comments. thanks.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNWLnp0d7VJWiDJqYd:-M1T9TeV5qmyHv5VM1fA:b8anl6c) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The one I placed my comment at ;) The `size` field.
</blockquote></details>

So that we can quickly retrieve the size of the list, instead of having to run a for-loop to find the size of a given list.

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNO_Sh-ylV598WlNA_:-M2BeND876LDWzKOoDQb:bsu7bqy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add tests to this PR then (testing all newly added interfaces). This is dead code right now and the fact that it mostly consists of macros makes the situation even worse - we don't even know whether it doesn't have syntax errors, because it gets removed by the preprocessor.
</blockquote></details>

@mkow Sure. I have posted a question on slack on where to add test code->If we need to add test code for Pal's list feature(https://github.com/oscarlab/graphene/blob/master/Pal/include/lib/list.h), do we update the test code here->( https://github.com/oscarlab/graphene/blob/master/Pal/lib/list-test.c)

---

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNQI9Q5lC5S2OzYFzH:-M2BejhE27dBGp93x7bm:bw1tqgp) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L174)):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

I am comfortable with heap sort. Will look into using heap-sort or something with nlogn complexity.
</blockquote></details>

@mkow I have uploaded changes to replace sorting algorithm for list, to use
    merge sort for better performance.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/1268#-M-EJvcE77J3wIaRhqDj:-M2Bf8_v1H7rHuSjT-U1:b-klwie3) ([raw file](https://github.com/oscarlab/graphene/blob/443033f9ffd7fb2d1f424dbeaa7878533f10917c/Pal/lib/list.h#L174)):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

It is a variant of selection sort.
</blockquote></details>

Done. Replaced with merge sort.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 257 at r4](https://reviewable.io/reviews/oscarlab/graphene/1268#-M1MHqmN4gtqo8mV0lwJ:-M2BfT8lAYX3ORC3r1PV:buwz80k) ([raw file](https://github.com/oscarlab/graphene/blob/fe960efcde519d0dbba7be93abf97e5425ba846e/Pal/lib/list.h#L257)):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

This check ->  LIST_ASSERT((HEAD)->size < MAX_SIZE), is a safety check, to prevent any integer overflow, before incrementing size.
</blockquote></details>

@mkow Removed size related changes. Adding support for size in list, can be a separate PR, based on discussion within graphene team.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 259 at r4](https://reviewable.io/reviews/oscarlab/graphene/1268#-M1MHQ2E7rur5bir6SBF:-M2BfdY063P90IHqR2CL:b-89rdvq) ([raw file](https://github.com/oscarlab/graphene/blob/fe960efcde519d0dbba7be93abf97e5425ba846e/Pal/lib/list.h#L259)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please write `(HEAD)->size++` here and below, it's more natural in C.
</blockquote></details>

Removed size related changes. Adding support for size in list, can be a separate PR, based on discussion within graphene team.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 269 at r4](https://reviewable.io/reviews/oscarlab/graphene/1268#-M1MI50y48-5H8SJGp2b:-M2BfgJb7O7N-S-sF4Lc:b-xoabnm) ([raw file](https://github.com/oscarlab/graphene/blob/fe960efcde519d0dbba7be93abf97e5425ba846e/Pal/lib/list.h#L269)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Please see my comment regarding removal of size related changes.

**Comment by sudharkrish** [comment]
___
*[Pal/lib/list.h, line 287 at r4](https://reviewable.io/reviews/oscarlab/graphene/1268#-M1MIDmv6Enle907F7w2:-M2BfmZdAUTWZqgLywJ2:bljssb0) ([raw file](https://github.com/oscarlab/graphene/blob/fe960efcde519d0dbba7be93abf97e5425ba846e/Pal/lib/list.h#L287)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Please see my comment regarding removal of size related changes.

**Comment by sudharkrish** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1268#-LzNO_Sh-ylV598WlNA_:-M2GoIIW2q6D-dPHsDph:b34oydd) (no related file):*
<details><summary><i>Previously, sudharkrish (Sudha Krishnakumar) wrote…</i></summary><blockquote>

@mkow Sure. I have posted a question on slack on where to add test code->If we need to add test code for Pal's list feature(https://github.com/oscarlab/graphene/blob/master/Pal/include/lib/list.h), do we update the test code here->( https://github.com/oscarlab/graphene/blob/master/Pal/lib/list-test.c)
</blockquote></details>

@mkow Added test code for sorting list nodes, and as part of that test code also testing new macros such as LISTP_GET_SIZE, and LISTP_CLEAR_AND_FREE_EACH_LIST_ITEM, in list-test.c

---

**Comment by mkow** [comment]
Closing. In the end it turned out that this wasn't required for protected files implementation.

**Pull request closed without merging**
