### PR TITLE
[LibOS] Fix alignment issued in sysfs implementation and test

### PR DESCRIPTION
**Pull request by stefanberger**
This is a split-off from the UBSAN PR.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2294#-MXcmtJx5gXPKTP4Es0v:-MXcmtJx5gXPKTP4Es0w:b7ngjaf) (no related file):*
I think there's a typo in the commit message: `issued` -> `issue`?

---
___
*[LibOS/shim/test/regression/sysfs_common.c, line 153 at r1](https://reviewable.io/reviews/oscarlab/graphene/2294#-MXcnDz33wsK6wXpbd9O:-MXcnDz33wsK6wXpbd9P:bju94lp) ([raw file](https://github.com/oscarlab/graphene/blob/7801e6a3b376f319950d6c6125a92a03b2bc2b55/LibOS/shim/test/regression/sysfs_common.c#L153)):*
> ```C
>             char* endp;
>             unsigned long nr = strtoul(dirent->d_name + 4,  &endp, 10);
>             if (nr != ULONG_MAX && endp != dirent64->d_name + 4 && *endp == '\0')
> ```

Wow, nice finding!

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2294#-MXcmtJx5gXPKTP4Es0v:-MXcqY971sdT25_1FHSx:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think there's a typo in the commit message: `issued` -> `issue`?
</blockquote></details>

Done.

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
@stefanberger: FYI: I fixed the email you used in your sign-off, it didn't match the commit ("@us.ibm.com" vs "@linux.ibm.com") and the DCO status check was failing because of this.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294#-:-MXiXBvW8C2XZxiLsG3H:b-d2pwqu)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (`apps.LTP.kill11` timed out, known issue)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2294)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
