### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just another bunch of little changes which has accumulated on my todolist.
FYI: the comment reformatting was motivated by Sublime Text wrongly autodetecting indentation in `pal_internal.h`. Reformatting to our official style fixes the problem.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[README.rst, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2125#-MS6vU5lBePrMa4hE9DB:-MS6vU5lBePrMa4hE9DC:b69cpz0) ([raw file](https://github.com/oscarlab/graphene/blob/595b2cb369d105fbd6975b34c52be413c9dae024/README.rst#L66)):*
> ```reStructuredText
> ======================================
> 
> See our `quick start guide <https://graphene.readthedocs.io/en/latest/manpages/gsc.html>`__.
> ```

GSC is not a quick start guide :) Replace with https://graphene.readthedocs.io/en/latest/quickstart.html

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[README.rst, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2125#-MS6vU5lBePrMa4hE9DB:-MS77mq_7889zitVhgaF:b-tuejzx) ([raw file](https://github.com/oscarlab/graphene/blob/595b2cb369d105fbd6975b34c52be413c9dae024/README.rst#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

GSC is not a quick start guide :) Replace with https://graphene.readthedocs.io/en/latest/quickstart.html
</blockquote></details>

Oops, good you noticed. Not sure how this happened...

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/pal_internal.h, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene/2125#-MSB80_A3glycPqRYJ49:-MSB7jNdA-lWuiSpmQuB:blpumfj) ([raw file](https://github.com/oscarlab/graphene/blob/44ed8d8b2de00dd7130cd3bc5a4d5e10b671c894/Pal/src/pal_internal.h#L55)):*
> ```objc
>     int (*delete)(PAL_HANDLE handle, int access);
> 
>     /* 'map' and 'unmap' will map or unmap the handle into memory space, it's not necessary mapped
> ```

Could you indent it by one empty line like that:
```
/*
 * abc ...
 */
```
not blocking on this.
___
*[Pal/src/pal_internal.h, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/2125#-MSB85YK20FoYKsS_HML:-MSB85YK20FoYKsS_HMM:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/44ed8d8b2de00dd7130cd3bc5a4d5e10b671c894/Pal/src/pal_internal.h#L128)):*
> ```objc
> #endif
> 
> /* failure notify. The rountine is called whenever a PAL call return error code. As the current
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: 9 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/pal_internal.h, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene/2125#-MSB80_A3glycPqRYJ49:-MSJEmKg6NxF3tiCNxYm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/44ed8d8b2de00dd7130cd3bc5a4d5e10b671c894/Pal/src/pal_internal.h#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you indent it by one empty line like that:
```
/*
 * abc ...
 */
```
not blocking on this.
</blockquote></details>

Done.
___
*[Pal/src/pal_internal.h, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/2125#-MSB85YK20FoYKsS_HML:-MSJEtci9bysl4_xiAGN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/44ed8d8b2de00dd7130cd3bc5a4d5e10b671c894/Pal/src/pal_internal.h#L128)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (`sendfile08` from LTP failed, known issue)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2125)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
