### PR TITLE
[Manifests] Use booleans in TOML

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Let's make our manifests more TOML-ish! :)

## How to test this PR? 

Please test if invalid entries are properly errored-out (because we don't have tests for these).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 68 of 68 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[common/src/string/toml_utils.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb0h8ze54d1BrrLISip:-Mb0h8zfEo_VqqhJ6xie:b-dihybx) ([raw file](https://github.com/oscarlab/graphene/blob/961ac4dc6b607aa90180a1f3d39d9bb1099e1649/common/src/string/toml_utils.c#L10)):*
> ```C
> 
> #include "api.h"
> #include "assert.h" // TODO: remove after warn() cleanup
> ```

What is wrong there? We don't even have `warn()` anymore.
___
*[Documentation/manifest-syntax.rst, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb0nxLCDWk_p-yeKm7u:-Mb0nxLCDWk_p-yeKm7v:b-cjqlj5) ([raw file](https://github.com/oscarlab/graphene/blob/961ac4dc6b607aa90180a1f3d39d9bb1099e1649/Documentation/manifest-syntax.rst#L84)):*
> ```reStructuredText
> ::
> 
>    loader.argv0_override = [true|false]
> ```

Wait what? This is not supposed to be a boolean but a string. Or you changed the semantics of this?

As a side note, I think we can safely remove this option now. I don't think there is any application that uses this.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: 66 of 68 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[common/src/string/toml_utils.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb0h8ze54d1BrrLISip:-Mb3np5i2VRRd2TMpl3g:biiwtbh) ([raw file](https://github.com/oscarlab/graphene/blob/961ac4dc6b607aa90180a1f3d39d9bb1099e1649/common/src/string/toml_utils.c#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is wrong there? We don't even have `warn()` anymore.
</blockquote></details>

Ah, forgot to drop this after rebase. Anyways, I dropped only the comment, because this file uses some asserts.
___
*[Documentation/manifest-syntax.rst, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb0nxLCDWk_p-yeKm7u:-Mb3oODq95aK2oZp49Y-:b-9is8dw) ([raw file](https://github.com/oscarlab/graphene/blob/961ac4dc6b607aa90180a1f3d39d9bb1099e1649/Documentation/manifest-syntax.rst#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait what? This is not supposed to be a boolean but a string. Or you changed the semantics of this?

As a side note, I think we can safely remove this option now. I don't think there is any application that uses this.
</blockquote></details>

Oops, I was too eager in replacing :)
I'd remove this option after adding more flexible argv/env override with TOML-ish syntax (i.e. not in this PR).
___
*[Documentation/manifest-syntax.rst, line 558 at r2](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb3q37q8EK1ZnyBTe6J:-Mb3q37q8EK1ZnyBTe6K:b-w543ph) ([raw file](https://github.com/oscarlab/graphene/blob/fc66c6c0c6023680b4f4d42a35ff4d7c9297fcdf/Documentation/manifest-syntax.rst#L558)):*
> ```reStructuredText
> 
> *Note:* this option is insecure and cannot be used with production enclaves
> (``sgx.debug = false``). If the production enclave is started with this option
> ```

FYI: I just reverted this change, I'm not sure what is actually correct here.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-18.04-apps please (Apache timed out, seems like a random slowdown?)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 66 of 68 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb74R409IOT-TfYfpt6:-Mb74R409IOT-TfYfpt7:b-pl5cjl) ([raw file](https://github.com/oscarlab/graphene/blob/fc66c6c0c6023680b4f4d42a35ff4d7c9297fcdf/Documentation/manifest-syntax.rst#L84)):*
> ```reStructuredText
> ::
> 
>    loader.argv0_override = [STRING]
> ```

Forgot to revert `"`.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: 67 of 68 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb74R409IOT-TfYfpt6:-Mb7JyDF1ymeqPAc0H8w:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fc66c6c0c6023680b4f4d42a35ff4d7c9297fcdf/Documentation/manifest-syntax.rst#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Forgot to revert `"`.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/manifest-syntax.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2407#-Mb74R409IOT-TfYfpt6:-Mb7LAN1-xe5ydVRp0x_:b20bcap) ([raw file](https://github.com/oscarlab/graphene/blob/fc66c6c0c6023680b4f4d42a35ff4d7c9297fcdf/Documentation/manifest-syntax.rst#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought it was supposed to be without `"` :) Anyway, looks good.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2407)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
