### PR TITLE
[PAL] Make test case work with PAGE_SIZE != 4096

### PR DESCRIPTION
**Pull request by stefanberger**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0SuwM-pLCPfliVpcm:-MR0SuwM-pLCPfliVpcn:b-pxnewk) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
> ```C
>         /* DEP 11/24/17: For SGX writecopy exercises a different path in the PAL */
>         void* mem2;
>         if (PAGE_SIZE == 4096) {
> ```

Shouldn't we use `sysconf()` like in that other test? AFAIR you said this constant has wrong value on PPC64?
___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR0Th787EO-QSs5RmbI:b-i4jdhm) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
> ```C
>         /* DEP 11/24/17: For SGX writecopy exercises a different path in the PAL */
>         void* mem2;
>         if (PAGE_SIZE == 4096) {
> ```

Why do we need this strange `if` here? I don't understand why this specific page size is special.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR0aYdK4v9t0g919Omw:b-kscmtc) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we need this strange `if` here? I don't understand why this specific page size is special.
</blockquote></details>

The offset here that's being mapped is 4096, so exactly one page. Iirc it doesn't work to do this with a 64k page.
___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0SuwM-pLCPfliVpcm:-MR0agZoCnq27USg78RE:be2ftbh) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we use `sysconf()` like in that other test? AFAIR you said this constant has wrong value on PPC64?
</blockquote></details>

We don't link with glibc, so I thought we wouldn't have it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0SuwM-pLCPfliVpcm:-MR0jyBl08QKjhjbg-bp:brym0li) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

We don't link with glibc, so I thought we wouldn't have it.
</blockquote></details>

Oh, right, I didn't notice this is a PAL regression test, not LibOS.
___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR0oFHf4BopgqHi105n:b3juzz3) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
> so exactly one page

But only on x86 in default settings. Shouldn't the offset be `PAGE_SIZE`, not such a hardcoded value? I think you wouldn't need these weird cases then?

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR1DwsqD9w46xIHI-JW:b-bkqetb) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> so exactly one page

But only on x86 in default settings. Shouldn't the offset be `PAGE_SIZE`, not such a hardcoded value? I think you wouldn't need these weird cases then?
</blockquote></details>

Further in the code below we are accessing the stream at offset 4096, which on x86 happens to be on the 2nd page but on ppc64 this is still on the first page:
 ```
         if (mem2) {
             memcpy(buffer3, mem2, 40);
             print_hex("Map Test 3 (4096th - 4136th): %s\n", buffer3, 40);
             memcpy(buffer3, mem2 + 200, 40);
             print_hex("Map Test 4 (4296th - 4336th): %s\n", buffer3, 40);
             DkStreamUnmap(mem2, PAGE_SIZE);
         } else {
             pal_printf("Map Test 3 & 4: Failed to map buffer\n");
         }
 ```

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR2C2co7fw-JyVM3X_m:b-x1eqz8) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Further in the code below we are accessing the stream at offset 4096, which on x86 happens to be on the 2nd page but on ppc64 this is still on the first page:
 ```
         if (mem2) {
             memcpy(buffer3, mem2, 40);
             print_hex("Map Test 3 (4096th - 4136th): %s\n", buffer3, 40);
             memcpy(buffer3, mem2 + 200, 40);
             print_hex("Map Test 4 (4296th - 4336th): %s\n", buffer3, 40);
             DkStreamUnmap(mem2, PAGE_SIZE);
         } else {
             pal_printf("Map Test 3 & 4: Failed to map buffer\n");
         }
 ```

</blockquote></details>

Then change both? ;) I mean, why not change/scale all sizes here proportionally?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR3wPHl2Hms1rSNYzYt:-MR3wPHl2Hms1rSNYzYu:bivb4ft) (no related file):*
This PR is strange. I don't see how it changes anything. You're still mmapping from file offset 4096... So it can as well stay hard-coded.

But if you want to change the logic to always offset to the second page, then you must modify the `print_hex()` strings as well, and the `test_pal.py:: test_100_file` test case.

Alternatively, we can simply remove the `Map Test 3` and `Map Test 4`. I don't know what they actually test...

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR5NpTm1fuR8kRQIfvR:b-9nqpiy) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then change both? ;) I mean, why not change/scale all sizes here proportionally?
</blockquote></details>

That would even cause changes in the python code then.
```
       # File Mapping
        self.assertIn(
            'Map Test 1 (0th - 40th): {}'.format(file_exist[0:40].hex()),
            stderr)
        self.assertIn(
            'Map Test 2 (200th - 240th): {}'.format(file_exist[200:240].hex()),
            stderr)
        self.assertIn(
            'Map Test 3 (4096th - 4136th): {}'.format(file_exist[4096:4136].hex()),
            stderr)
        self.assertIn(
            'Map Test 4 (4296th - 4336th): {}'.format(file_exist[4296:4336].hex()),
            stderr)
```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MR7YjprBgq1urpaJxrR:b-sfz12u) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

That would even cause changes in the python code then.
```
       # File Mapping
        self.assertIn(
            'Map Test 1 (0th - 40th): {}'.format(file_exist[0:40].hex()),
            stderr)
        self.assertIn(
            'Map Test 2 (200th - 240th): {}'.format(file_exist[200:240].hex()),
            stderr)
        self.assertIn(
            'Map Test 3 (4096th - 4136th): {}'.format(file_exist[4096:4136].hex()),
            stderr)
        self.assertIn(
            'Map Test 4 (4296th - 4336th): {}'.format(file_exist[4296:4336].hex()),
            stderr)
```
</blockquote></details>

Yeah, but the alternative is to make this test useless outside of x86, which doesn't sound like a good solution ;)

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR3wPHl2Hms1rSNYzYt:-MRWBHYP-3p08Zi1wPQw:b-9o515k) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR is strange. I don't see how it changes anything. You're still mmapping from file offset 4096... So it can as well stay hard-coded.

But if you want to change the logic to always offset to the second page, then you must modify the `print_hex()` strings as well, and the `test_pal.py:: test_100_file` test case.

Alternatively, we can simply remove the `Map Test 3` and `Map Test 4`. I don't know what they actually test...
</blockquote></details>

Then let me remove those... tomorrow, unless I hear otherwise.

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MRtxp3E9pen6ObOGMgT:bxdnzfi) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but the alternative is to make this test useless outside of x86, which doesn't sound like a good solution ;)
</blockquote></details>

I removed the Map Tests 3 and 4.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/regression/File.c, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2085#-MR0Th787EO-QSs5RmbH:-MRtz-69D1ZPrzeehrW1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/eef2c32a586c5766c535f279a9cf241e5a965e08/Pal/regression/File.c#L77)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I removed the Map Tests 3 and 4.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/regression/File.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2085#-MRuYEDc9PoHAyE1HneH:-MRuYEDc9PoHAyE1HneI:brri5f5) ([raw file](https://github.com/oscarlab/graphene/blob/6f4e9d289f7548166075e5c373966c1b3eda6f6d/Pal/regression/File.c#L10)):*
> ```C
> char buffer1[BUF_SIZE];
> char buffer2[BUF_SIZE];
> char buffer3[BUF_SIZE];
> ```

This is useless now.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/regression/File.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2085#-MRuYEDc9PoHAyE1HneH:-MRvKIGZ3rBUgSp4nb0h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6f4e9d289f7548166075e5c373966c1b3eda6f6d/Pal/regression/File.c#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is useless now.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (network still broken on leeroy)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (internet connectivity on `leeroy`)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (internet connectivity on leeroy)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2085)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
