### PR TITLE
[Pal/Linux-SGX] Restrict possible error codes on OCALL returns

### LINKED ISSUE #634: [Pal/Linux-SGX] On OCALL return, restrict possibly malicious return value to sane values
As part of OCALL hardening, on OCALL return, we must verify and restrict possibly malicious return value. In most cases, we should add checks on permissible error values.

The PR for this issue will depend on #554 -- it changes error codes from PAL codes to normal POSIX syscall error codes.

Special case OCALLs:
* CPUID: should check meaningful bit & leaf combinations?

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

As part of OCALL hardening, on OCALL return, we now verify and restrict possibly malicious return values. In most OCALL cases, we check against the set of permissible error codes (taken from corresponding syscall man pages and combined together for multi-syscall OCALLs).

Fixes #634.

## How to test this PR? 

All tests must pass. Must run several times to be sure.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest this please (first time was successful, running again just to check)

**Comment by dimakuv** [comment]
Jenkins, retest this please (Jenkins-Debug-18.04 timed out on `fcntl14` -- looks like legit timeout; Jenkins-SGX-20.04 failed on `test_libos.TC_80_Socket.test_022_poll_closed_fd`, known issue fixed by Borys's PR).

Note that all my local 200 runs of `fcntl14` succeeded, but the test is indeed pretty slow.

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (last time was successful, running again just to check)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOH85i7_dwj5aM2a9-:-MgOH85i7_dwj5aM2a90:b-qv4rs8) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L352)):*
> ```C
> 
>     if (retval < 0) {
>         retval = -EPERM; /* CPUID OCALL is not supposed to fail, but if it does, sanitize error */
> ```

If it cannot fail, then can we just `_DkProcessExit` here, since it's malicious host?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1708 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKN5J5DFKKGyj8NEE:-MgOKN5J5DFKKGyj8NEF:b-3qxvkn) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1708)):*
> ```C
> 
>     if (retval < 0) {
>         retval = -EPERM; /* DEBUG OCALLs are not supposed to fail, but if they do, sanitize error */
> ```

What's the point?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1740 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKQGJ9G9zIkKx88Iu:-MgOKQGJ9G9zIkKx88Iv:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1740)):*
> ```C
> 
>     if (retval < 0) {
>         retval = -EPERM; /* DEBUG OCALLs are not supposed to fail, but if they do, sanitize error */
> ```

ditto

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (last time was successful, running again just to check)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOH85i7_dwj5aM2a9-:-MgPcj_eETgTmb6Yonw_:b-uscw5n) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L352)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If it cannot fail, then can we just `_DkProcessExit` here, since it's malicious host?
</blockquote></details>

OK, fair enough.

But what about other cases in this PR? Technically, if `retval` is not in a set of allowed error codes, then it is a malicious host injecting some weird error code. Should we also fail instead of doing `retval = -EPERM`?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1708 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKN5J5DFKKGyj8NEE:-MgPdc6TDSkia3buBGJ_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1708)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1740 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKQGJ9G9zIkKx88Iu:-MgPdcXf7AMfhc5tEaWP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1740)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please (`writev07` and `fcntl14` timed out...)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOH85i7_dwj5aM2a9-:-MgR08Q23KasNRwOzzYg:bhcgd30) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, fair enough.

But what about other cases in this PR? Technically, if `retval` is not in a set of allowed error codes, then it is a malicious host injecting some weird error code. Should we also fail instead of doing `retval = -EPERM`?
</blockquote></details>

I was thinking about it, but the problem is we could have easily missed something. Also manpages do not list all possible errors.
On the other hand, we probably should check only for errors that can really happen, e.g. exclude invalid parameters error and such (i.e. assume that the invocation is always correct - otherwise it's a Graphene bug). The question would be: is Graphene ready for this? Is there no relying on errors to check stuff and no parameters passthrough from the user app?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1708 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKN5J5DFKKGyj8NEE:-MgR2xHv0eo4nhxHVgTn:bgx51vb) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1708)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant what's the point of this check - it's only in debug mode and by definition it's insecure...
But I guess we can have this, does not really matter.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 425 at r2](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgXTpwaCk01A2MuK0Fg:-MgXTpwaCk01A2MuK0Fh:b-47rn7c) ([raw file](https://github.com/oscarlab/graphene/blob/685fd76e30f9addd7756133e1780559d027af273/Pal/src/host/Linux-SGX/enclave_ocalls.c#L425)):*
> ```C
> 
>     if (retval < 0 && retval != -EBADF && retval != -EIO) {
>         retval = -EPERM;
> ```

Hmm, `EPERM` is not on the whitelist, but I'm not sure how to do this better.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOH85i7_dwj5aM2a9-:-MgdkShJ9g94NJ0wXZTQ:b4jy03m) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L352)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I was thinking about it, but the problem is we could have easily missed something. Also manpages do not list all possible errors.
On the other hand, we probably should check only for errors that can really happen, e.g. exclude invalid parameters error and such (i.e. assume that the invocation is always correct - otherwise it's a Graphene bug). The question would be: is Graphene ready for this? Is there no relying on errors to check stuff and no parameters passthrough from the user app?
</blockquote></details>

Yes, I understand your point about excluding error codes that correspond to invalid syscall parameters. I was also debating myself, but decided to opt for covering all "highly possible" Graphene invocations resulting in such error codes (e.g., I always allow `EINVAL` because it's easy to imagine how Graphene "probes" something bad).

Also, I removed "exotic" error codes that surely can never happen in Graphene. For example, I removed `EDQUOT`, `EOPNOTSUPP` on open, `ETXTBSY` and so on.

I agree that the sets of allowed error codes are not very strict and may miss some other codes (not documented in man pages). Any suggestions to make the sets better are welcome.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1708 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKN5J5DFKKGyj8NEE:-MgdmbMCCYg1YdGvmlMl:b6yc39c) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1708)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant what's the point of this check - it's only in debug mode and by definition it's insecure...
But I guess we can have this, does not really matter.
</blockquote></details>

Done. True, I simply removed this check.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1740 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOKQGJ9G9zIkKx88Iu:-MgdmemLBl4_mEdDppfe:b-d0uxhm) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1740)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (removed)
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 425 at r2](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgXTpwaCk01A2MuK0Fg:-MgdmBf6EqZu49hHLK5a:b7lphe9) ([raw file](https://github.com/oscarlab/graphene/blob/685fd76e30f9addd7756133e1780559d027af273/Pal/src/host/Linux-SGX/enclave_ocalls.c#L425)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, `EPERM` is not on the whitelist, but I'm not sure how to do this better.
</blockquote></details>

Yeah... We already use `EPERM` -- even for syscalls that are never supposed to return it -- as a catch-all error code for "something went wrong with this OCALL".

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2621#-MgOH85i7_dwj5aM2a9-:-MgeYcmf72B6H-qHm5l7:b-lqvy9h) ([raw file](https://github.com/oscarlab/graphene/blob/17802b52219dd3fa529396483e9811da7d974b28/Pal/src/host/Linux-SGX/enclave_ocalls.c#L352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I understand your point about excluding error codes that correspond to invalid syscall parameters. I was also debating myself, but decided to opt for covering all "highly possible" Graphene invocations resulting in such error codes (e.g., I always allow `EINVAL` because it's easy to imagine how Graphene "probes" something bad).

Also, I removed "exotic" error codes that surely can never happen in Graphene. For example, I removed `EDQUOT`, `EOPNOTSUPP` on open, `ETXTBSY` and so on.

I agree that the sets of allowed error codes are not very strict and may miss some other codes (not documented in man pages). Any suggestions to make the sets better are welcome.
</blockquote></details>

We should probably validate whether Graphene is really "probing" invalid/incorrect options/parameters and disallow that, but that's probably not so easy.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, retest this please (just to be sure)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2621)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
