### PR TITLE
[PAL] Move x86_64-specific PAL_CPU_INFO into pal-arch.h

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Move x86_64-specific PAL_CPU_INFO into pal-arch.h and move x86_64-specific code from db_main.c into db-main_x86_64.c.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1571)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this plesae

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Pull request merged**
