### PR TITLE
[Docs] Add some new info on performance tuning

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some new manifest options were added. Also, we now know that spreading across NUMA domains are quite bad for SGX.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/devel/performance.rst, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTkvuCTEu7fDahyrUB5:-MTkvuCTEu7fDahyrUB6:btptmb5) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L371)):*
> ```
>    Also, it is typically beneficial to disable hyper-threading
> ```

Is it, really? I don't think so... Per core performance is better, but if you compare the overall performance, you're just using less computing power,
___
*[Documentation/devel/performance.rst, line 392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTlXJp9-CyXjBTbk40s:-MTlXJp9-CyXjBTbk40t:byqaa1f) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L392)):*
> ```reStructuredText
> - ``sgx.preheat_enclave = 1`` -- pre-fault all enclave pages during enclave
>   initialization. This shifts the overhead of page faults on non-present enclave
>   pages from runtime to enclave startup time.
> ```

I'd also note here that this makes sense only if the whole enclave fits into EPC.
___
*[Documentation/devel/performance.rst, line 550 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTlXXs-1aDweey-hXBX:-MTlXXs-1aDweey-hXBY:b7z9wfq) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L550)):*
> ```reStructuredText
> 
> *Note*: The accuracy of this tool is unclear (though we had positive experiences
> using the tool). The SGX profiling works by measuring the value of instruction
> ```

`using the tool` -> `using the tool so far` (sounds better this way IMO)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/performance.rst, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTkvuCTEu7fDahyrUB5:-MTo0oJ87xGudxUdldSz:bl4xw31) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L371)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>    Also, it is typically beneficial to disable hyper-threading
> ```

Is it, really? I don't think so... Per core performance is better, but if you compare the overall performance, you're just using less computing power,
</blockquote></details>

Ok, removed this. Yes, this is not generally true, though we've seen many workloads that benefit from not using hyper-threading.
___
*[Documentation/devel/performance.rst, line 392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTlXJp9-CyXjBTbk40s:-MTo1GGZ5YvQ9avTd8jr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L392)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd also note here that this makes sense only if the whole enclave fits into EPC.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 550 at r1](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTlXXs-1aDweey-hXBX:-MTo1M8s8RNxk0ARtkEj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2d073a0d9b1df0d26ae5e317ddb3c642c8e5b054/Documentation/devel/performance.rst#L550)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`using the tool` -> `using the tool so far` (sounds better this way IMO)
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/performance.rst, line 391 at r2](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTp9XGGClcBfkpJEWlK:-MTp9XGH-ek7Pi8Y8ph0:b-3skfcf) ([raw file](https://github.com/oscarlab/graphene/blob/5d4eb118977d796c41c601946f797ffcf9178765/Documentation/devel/performance.rst#L391)):*
> ```reStructuredText
>   initialization. This shifts the overhead of page faults on non-present enclave
>   pages from runtime to enclave startup time. Using this option makes sense only
>   if the whole enclave memory fits into EPC.
> ```

Please link to glossary at "EPC"

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/performance.rst, line 391 at r2](https://reviewable.io/reviews/oscarlab/graphene/2167#-MTp9XGGClcBfkpJEWlK:-MTpVOQz9JrGwB-cD7X9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5d4eb118977d796c41c601946f797ffcf9178765/Documentation/devel/performance.rst#L391)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please link to glossary at "EPC"
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2167)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
