### PR TITLE
Update to mbedtls 2.16.3

### PR DESCRIPTION
**Pull request by thomasknauth**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Updates mbedtls to the more recent 2.16.3 (long term support!) version. This should be the most recent long-term support version of mbedtls.

Closes #1201.

Not sure I did the right thing here. Only the last two commits are specific to this PR. The others are inherited from #1201.

## How to test this PR? 

Regression still passes.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1206)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins fails with this:
```
cd crypto && tar -mxzf mbedtls-2.16.3.tar.gz
mv crypto/mbedtls-mbedtls-2.16.3 crypto/mbedtls
cp crypto/platform.h crypto/config.h crypto/mbedtls/include/mbedtls
cp: target 'crypto/mbedtls/include/mbedtls' is not a directory
Makefile:47: recipe for target 'crypto/mbedtls/CMakeLists.txt' failed
make[3]: *** [crypto/mbedtls/CMakeLists.txt] Error 1
make[3]: Leaving directory '/home/jenkins/workspace/graphene/Pal/lib'
Makefile:91: recipe for target 'graphene_lib_recurse' failed
make[2]: *** [graphene_lib_recurse] Error 2
```

**Comment by dimakuv** [comment]
All builds now fail with:
```
cd crypto/mbedtls && cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DENABLE_PROGRAMS=off -DENABLE_TESTING=off -DCMAKE_C_COMPILER=gcc .
/bin/sh: 1: cmake: not found
Makefile:58: recipe for target 'crypto/mbedtls/CMakeLists.txt' failed
make[3]: *** [crypto/mbedtls/CMakeLists.txt] Error 127
make[3]: Leaving directory '/home/jenkins/workspace/graphene/Pal/lib'
Makefile:91: recipe for target 'graphene_lib_recurse' failed
```

Apparently, Docker Ubuntu doesn't ship with cmake. Please add cmake installation to `Jenkinsfiles/ubuntu*` files.

**Comment by thomasknauth** [comment]
Please do not merge just yet. I'll remove the dependency on cmake. It is not actually needed.

**Comment by dimakuv** [comment]
Jenkins retest Jenkins please (`no space left on device` on the Jenkins machine, hm)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`no space left on device on the Jenkins machine, hm`)

**Pull request merged**
