### PR TITLE
[Pal,LibOS] Minor architecture cleanups

### PR DESCRIPTION
**Pull request by stefanberger**
This PR has some minor architecture cleanups.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/include/shim_internal.h, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene/1987#-MMhicoh1uCNz9iSsT0r:-MMhicoh1uCNz9iSsT0s:b69swxp) ([raw file](https://github.com/oscarlab/graphene/blob/8ff79072f5baf1331445eb0819968dade9c76d3e/LibOS/shim/include/shim_internal.h#L65)):*
> ```objc
>         DEBUG_BREAK_ON_FAILURE();                   \
>         /* Crash the process. */                    \
>         __asm__ volatile(                           \
> ```

Oops, sorry, we forgot again about not placing inline asm in non arch-specific headers :(

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1987)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
