### PR TITLE
[LibOS] optimize vma allocation

### PR DESCRIPTION
**Pull request by yamahata**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1331)

### CODE REVIEW

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-Debug-18.04 please. apps.LTP.sendto02  timeout

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. TC_01_Bootstrap.test_200_exec assertion error "00000..." not found

**Comment by yamahata** [comment]
Jenkins, retest Jenkins please. test_libos.TC_01_Bootstrap testMethod=test_401_exit_group timeout

**Comment by boryspoplawski** [comment]
This PR becomes unnecessary once #1431 is merged.

**Pull request closed without merging**
