### PR TITLE
[LibOS] Fix wait_event

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
They all lacked error checking and `wait_event` was completely broken.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibtDs460vlhcfOspo:-MLibtDs460vlhcfOspp:b-hodw0z) (no related file):*
Please add a more comprehensive commit message (that non-blocking pipe doesn't make sense in waiting for an event).

---
___
*[LibOS/shim/include/shim_internal.h, line 356 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibUxj104Qm58sG65F:-MLibUxj104Qm58sG65G:b-t06rjj) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L356)):*
> ```objc
> again: ;
>     char byte;
>     PAL_NUM n = DkStreamRead(e->event, 0, 1, &byte, NULL, 0);
> ```

For consistency, can we rename `n` -> `ret`?
___
*[LibOS/shim/include/shim_internal.h, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibcKF20F99RhOdJnI:-MLibcKGEmyhKlRlBunI:b-3dhq2n) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L390)):*
> ```objc
>         }
> 
>         /* Event if `revent` has `PAL_WAIT_ERROR` marked, let `DkSitreamRead` report the error
> ```

`Even`, `DkStreamRead()`

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_internal.h, line 327 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLiYD3e4Uom8dCyw6ZK:-MLiYD3e4Uom8dCyw6ZL:b-mrp5xw) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L327)):*
> ```objc
> }
> 
> static inline int set_event(AEVENTTYPE* e, size_t n) {
> ```

while you're rewriting this, could you document the semantics?
___
*[LibOS/shim/include/shim_internal.h, line 328 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLiYNd652Yt-Wf9jXS6:-MLiYNd652Yt-Wf9jXS7:bhquqee) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L328)):*
> ```objc
> 
> static inline int set_event(AEVENTTYPE* e, size_t n) {
>     if (!e->event) {
> ```

Why not an assert? No one should be calling this function on an uninitialized event.
___
*[LibOS/shim/include/shim_internal.h, line 350 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLieOH633Bwogar-btj:-MLieOH7CQl2pXEM6cpW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L350)):*
> ```objc
> 
> static inline int wait_event(AEVENTTYPE* e) {
>     if (!e->event) {
> ```

ditto
___
*[LibOS/shim/include/shim_internal.h, line 354 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLieLYG3JQbX_763x8H:-MLieLYH-ooye4bwSPrq:b-ikuhzl) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L354)):*
> ```objc
>     }
> 
> again: ;
> ```

please use a loop instead

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)* status: 5 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibtDs460vlhcfOspo:-MLiwr7aB3k4K3jT_nUa:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a more comprehensive commit message (that non-blocking pipe doesn't make sense in waiting for an event).
</blockquote></details>

Done.

---
___
*[LibOS/shim/include/shim_internal.h, line 327 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLiYD3e4Uom8dCyw6ZK:-MLiwsVJCyNoI3Zp3hHN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L327)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

while you're rewriting this, could you document the semantics?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 328 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLiYNd652Yt-Wf9jXS6:-MLiwtYR8i-W7NZD2zpf:b-f8sf1p) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L328)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not an assert? No one should be calling this function on an uninitialized event.
</blockquote></details>

Added a comment.
___
*[LibOS/shim/include/shim_internal.h, line 350 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLieOH633Bwogar-btj:-MLiwz83CircTXnfPgbd:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[LibOS/shim/include/shim_internal.h, line 354 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLieLYG3JQbX_763x8H:-MLiwzfyEbDHJfsKCeYL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L354)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please use a loop instead
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 356 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibUxj104Qm58sG65F:-MLix-SD95ASaJeZyiMa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L356)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For consistency, can we rename `n` -> `ret`?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/1953#-MLibcKF20F99RhOdJnI:-MLix0Eg8vGoSEq3mU4S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ab978a84a0a7bfe2ec8807f5921ca12e39fbd5e/LibOS/shim/include/shim_internal.h#L390)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Even`, `DkStreamRead()`
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1953)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
