### PR TITLE
LibOS: add check printf format

### PR DESCRIPTION
**Pull request by yamahata**
This patch adds printf format check and fixes most of found issues.
ADD_CP_ENTRY was given up due to type issue.
It requires to change function signature. So I didn't address it at
this time.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/380)

### CODE REVIEW

**Comment by donporter** [comment]
@yamahata I think this PR is ready to go.  Please squash into one commit.  Thanks!

**Comment by mkow** [comment]
@yamahata: We enabled `-Werror` in the meantime and this change stopped to build correctly. I think the best option would be to address the skipped `ADD_CP_ENTRY` in this PR, but I'm open to discussion if you have a better idea.

Build log:
```
In file included from bookkeep/shim_handle.c:26:0:
bookkeep/shim_handle.c: In function 'cp_handle':
../include/shim_internal.h:79:26: error: format '%d' expects argument of type 'int', but argument 2 has type 'long unsigned int' [-Werror=format=]
             debug_printf((fmt), ##__VA_ARGS__);                             \
                          ^
../include/shim_checkpoint.h:215:13: note: in expansion of macro 'debug'
             debug("ADD OFFSET(%d) >%ld\n", (size), store->offset);  \
             ^
bookkeep/shim_handle.c:792:15: note: in expansion of macro 'ADD_CP_OFFSET'
         off = ADD_CP_OFFSET(sizeof(struct shim_handle));
               ^
bookkeep/shim_handle.c: In function 'cp_fd_handle':
../include/shim_internal.h:79:26: error: format '%d' expects argument of type 'int', but argument 2 has type 'long unsigned int' [-Werror=format=]
             debug_printf((fmt), ##__VA_ARGS__);                             \
                          ^
../include/shim_checkpoint.h:215:13: note: in expansion of macro 'debug'
             debug("ADD OFFSET(%d) >%ld\n", (size), store->offset);  \
             ^
bookkeep/shim_handle.c:878:17: note: in expansion of macro 'ADD_CP_OFFSET'
     ptr_t off = ADD_CP_OFFSET(sizeof(struct shim_fd_handle));
                 ^
cc1: all warnings being treated as errors
```

**Comment by mkow** [comment]
@yamahata I just did the final rebase as we plan to merge this next.
I updated your commit message, as it contained a stale info about leaving ADD_CP_ENTRY unfixed and also fixed a conflict in shim_signal.c. Please verify if everything looks good now.

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
