### PR TITLE
[CI] Add download mirror

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 
We've experienced intermittent github.com outage, so add our own mirror.

## How to test this PR? 
CI should stop failing for network/DNS problems with github.com.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: 1 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[Examples/gcc/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtpOU4DpnOGNR_Drr3:-MRtpOU5BncsC_-aKayc:be3ouyy) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/gcc/Makefile#L12)):*
> ```Makefile
> GZIP_MIRRORS ?= \
> 	https://people.csail.mit.edu/smcc/projects/single-file-programs/gzip.c \
> 	https://packages.grapheneproject.io/distfiles/single-file-programs/bzip2.c
> ```

copy-paste error? should be `gzip.c`

**Review by mkow — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[Examples/ra-tls-mbedtls/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRts9SJ3OGCMLC1XcmB:-MRts9SJ3OGCMLC1XcmC:b-mx8px5) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-mbedtls/Makefile#L70)):*
> ```Makefile
> 
> $(MBEDTLS_SRC):
> 	../../Scripts/download --output $@ $(foreach mirror,$(MBEDTLS_URI),--url $(mirror)/$(MBEDTLS_SRC)) --sha256 $(MBEDTLS_CHECKSUM)
> ```

Why did you replace `GRAPHENEDIR` with `../../`?

Note that you didn't do this in some other places (e.g. GCC).
___
*[Examples/ra-tls-secret-prov/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtsNH3EkE7d1HwchyJ:-MRtsNH3EkE7d1HwchyK:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-secret-prov/Makefile#L69)):*
> ```Makefile
> 
> $(MBEDTLS_SRC):
> 	../../Scripts/download --output $@ $(foreach mirror,$(MBEDTLS_URI),--url $(mirror)/$(MBEDTLS_SRC)) --sha256 $(MBEDTLS_CHECKSUM)
> ```

ditto

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Examples/ra-tls-secret-prov/Makefile, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuSsDH7-hqfqhWjUc4:-MRuSsDH7-hqfqhWjUc5:bpgwxg1) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Examples/ra-tls-secret-prov/Makefile#L72)):*
> ```Makefile
> 
> $(MBEDCRYPTO_SRC):
> 	../../Scripts/download --output $@ $(foreach mirror,$(MBEDCRYPTO_URI),--url $(mirror)/$(MBEDCRYPTO_SRC)) --sha256 $(MBEDCRYPTO_CHECKSUM)
> ```

here as well
___
*[Pal/lib/Makefile, line 168 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuThe_-iXkVTO5Xm_E:-MRuThe_-iXkVTO5Xm_F:bbczi7h) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/lib/Makefile#L168)):*
> ```Makefile
> 
> ../include/lib/uthash.h:
> 	../../Scripts/download --output $@ --sha256 $(UTHASH_CHECKSUM) $(foreach mirror,$(UTHASH_URI), --url $(mirror))
> ```

NP: you sometimes add spaces after `,` in `foreach` and sometimes do not.
(not blocking)
___
*[Pal/src/host/Linux-SGX/tools/common/Makefile, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuU0LJC6CUee93vK7Z:-MRuU0LJC6CUee93vK7_:b-i62ms) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/src/host/Linux-SGX/tools/common/Makefile#L31)):*
> ```Makefile
> $(CJSON_SRC):
> 	$(DOWNLOAD_SCRIPT) --output $(CJSON_SRC) --url $(CJSON_URI)/$(CJSON_SRC) --sha256 $(CJSON_CHECKSUM) \
> 		--url https://packages.grapeneproject.io/distfiles/cJSON-$(CJSON_VERSION).tar.gz
> ```

Why hardcode 2nd url instead of adding it to the list and looping like in all other places?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Examples/gcc/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtpOU4DpnOGNR_Drr3:-MRurNUnAOcr0SSMciTf:bbq6832) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/gcc/Makefile#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

copy-paste error? should be `gzip.c`
</blockquote></details>

Yeah, it was.
___
*[Examples/ra-tls-mbedtls/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRts9SJ3OGCMLC1XcmB:-MRurPvK11D8wgsL_X2i:b-g3oskq) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-mbedtls/Makefile#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you replace `GRAPHENEDIR` with `../../`?

Note that you didn't do this in some other places (e.g. GCC).
</blockquote></details>

This was copy-pasted (possibly from `Pal/lib/Makefile`) and still works. Would you like me to revert to `$(GRAPHENEDIR)`?
___
*[Examples/ra-tls-secret-prov/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtsNH3EkE7d1HwchyJ:-MRurcM6CRlD67AtPNlB:bcaaprq) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-secret-prov/Makefile#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

copy-paste; revert?
___
*[Examples/ra-tls-secret-prov/Makefile, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuSsDH7-hqfqhWjUc4:-MRurdku-ZwyC_O0IbmW:b-ni8rrn) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Examples/ra-tls-secret-prov/Makefile#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here as well
</blockquote></details>

mhm; ?
___
*[Pal/lib/Makefile, line 168 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuThe_-iXkVTO5Xm_E:-MRurgNc2l9KFSt5o32g:bio8ebi) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/lib/Makefile#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: you sometimes add spaces after `,` in `foreach` and sometimes do not.
(not blocking)
</blockquote></details>

Uh, right.
___
*[Pal/src/host/Linux-SGX/tools/common/Makefile, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuU0LJC6CUee93vK7Z:-MRurjws6WWNUNFjqTMF:bs7xszm) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/src/host/Linux-SGX/tools/common/Makefile#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why hardcode 2nd url instead of adding it to the list and looping like in all other places?
</blockquote></details>

Because here `$(CJSON_SRC)` is unsuitable for looping (the original filename, as given by `Content-Disposition:` header, is different, and the mirror has it under the later name). Not sure why, and I didn't want to either investigate or change `CJSON_SRC`, because it is used elsewhere in the `Makefile`.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Examples/ra-tls-mbedtls/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRts9SJ3OGCMLC1XcmB:-MRuv5TA6OpuYUQdTTfU:bo6ompy) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-mbedtls/Makefile#L70)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This was copy-pasted (possibly from `Pal/lib/Makefile`) and still works. Would you like me to revert to `$(GRAPHENEDIR)`?
</blockquote></details>

Yes please.
___
*[Examples/ra-tls-secret-prov/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtsNH3EkE7d1HwchyJ:-MRuvCxTBx9YhD5wqRkI:b2nign6) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-secret-prov/Makefile#L69)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

copy-paste; revert?
</blockquote></details>

yes
___
*[Examples/ra-tls-secret-prov/Makefile, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuSsDH7-hqfqhWjUc4:-MRuvDUEAT_oJ0VOczdv:b2nign6) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Examples/ra-tls-secret-prov/Makefile#L72)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

mhm; ?
</blockquote></details>

yes
___
*[Pal/src/host/Linux-SGX/tools/common/Makefile, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuU0LJC6CUee93vK7Z:-MRuvzHb6eXM-fBQ3mJC:b-8r01bl) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/src/host/Linux-SGX/tools/common/Makefile#L31)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because here `$(CJSON_SRC)` is unsuitable for looping (the original filename, as given by `Content-Disposition:` header, is different, and the mirror has it under the later name). Not sure why, and I didn't want to either investigate or change `CJSON_SRC`, because it is used elsewhere in the `Makefile`.
</blockquote></details>

How about
```
CJSON_URI ?= \
    https://github.com/DaveGamble/cJSON/archive/$(CJSON_SRC) \
    2nd_url_here
```
and just use `foreach` like everywhere?
(we have a similar approach in `Examples/gcc/Makefile`

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[Examples/ra-tls-mbedtls/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRts9SJ3OGCMLC1XcmB:-MRv487k2PpNU7WYdjgR:b2nhswy) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-mbedtls/Makefile#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes please.
</blockquote></details>

Yes
___
*[Examples/ra-tls-secret-prov/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtsNH3EkE7d1HwchyJ:-MRv4A2mAzPgyeADGHag:b2nhswy) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-secret-prov/Makefile#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Yes
___
*[Examples/ra-tls-secret-prov/Makefile, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuSsDH7-hqfqhWjUc4:-MRv4CQ3BEz4PIDvWjlp:b2nhswy) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Examples/ra-tls-secret-prov/Makefile#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Yes

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: 2 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Examples/ra-tls-mbedtls/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRts9SJ3OGCMLC1XcmB:-MRzIn5h8znbuSg2Ws_B:b-zyolt) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-mbedtls/Makefile#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done (also below, which no-one pointed; total 4 lines fixed).

FYI in #2064 I may change this to something other, because I still don't know what will happen to GRAPHENEDIR. For now it doesn't matter and I'm happy to fix for consistency.
___
*[Examples/ra-tls-secret-prov/Makefile, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRtsNH3EkE7d1HwchyJ:-MRzIlAV7tPNNpvKX1rj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a284fbfbf1f0b17c86300a5f0ed840f3e51da686/Examples/ra-tls-secret-prov/Makefile#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.
___
*[Examples/ra-tls-secret-prov/Makefile, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuSsDH7-hqfqhWjUc4:-MRzIkXr48i4ymg2Sd9c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Examples/ra-tls-secret-prov/Makefile#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.
___
*[Pal/lib/Makefile, line 168 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuThe_-iXkVTO5Xm_E:-MRzIhwd6dMmlMp4sa6c:b1b7bz3) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/lib/Makefile#L168)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Uh, right.
</blockquote></details>

Fixed this.
___
*[Pal/src/host/Linux-SGX/tools/common/Makefile, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2119#-MRuU0LJC6CUee93vK7Z:-MRzIgOGA8uXBvNkR6tq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/24750cdafdd6d2ec8996995e9a1d3cf6fc61501d/Pal/src/host/Linux-SGX/tools/common/Makefile#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about
```
CJSON_URI ?= \
    https://github.com/DaveGamble/cJSON/archive/$(CJSON_SRC) \
    2nd_url_here
```
and just use `foreach` like everywhere?
(we have a similar approach in `Examples/gcc/Makefile`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
