### PR TITLE
[meson] Move clang-format from make

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This is another thing to move from make to meson.

## How to test this PR? 

Follow the new new reformat procedure, according to the change in documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2373)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2373)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`kill11` LTP test failed)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-20.04 please (`kill11` LTP test failed)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2373)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
