### PR TITLE
Sort out some x86_64 stuff from the meson build

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 
Sort out some x86_64-specific stuff in the meson build files.

## How to test this PR? 

Run the build.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC-nPyBo4D0Ok0Jt2l:-MfC-nPyBo4D0Ok0Jt2m:b5mqpj1) (no related file):*
You have too many emails :) The DCO checker complains on both commits:
```
Expected "Stefan Berger stefanb@linux.vnet.ibm.com", but got "Stefan Berger stefanb@linux.ibm.com".
Expected "Stefan Berger stefanb@linux.vnet.ibm.com", but got "Stefan Berger stefanb@linux.ibm.com".
```

Please fix either the commit author or the Signed-off-by message.

---
___
*[meson.build, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC0R8G3iMX_bB4mZUF:-MfC0R8G3iMX_bB4mZUG:b-f3w2tf) ([raw file](https://github.com/oscarlab/graphene/blob/a4eb2a20bd6eed053ff23e3a0c76ed3973cb6c46/meson.build#L80)):*
> ```Meson
>         '-mstack-protector-guard-offset=8',
>     ]
> endif
> ```

Why does it work? On a non-x86-64 machine, `cflags_custom_stack_protector` is not defined at all after this IF clause. So do we end up with `-fno-stack-protector` and nothing at all?

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC-nPyBo4D0Ok0Jt2l:-MfDAgH7ATAeK2esS8Ao:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have too many emails :) The DCO checker complains on both commits:
```
Expected "Stefan Berger stefanb@linux.vnet.ibm.com", but got "Stefan Berger stefanb@linux.ibm.com".
Expected "Stefan Berger stefanb@linux.vnet.ibm.com", but got "Stefan Berger stefanb@linux.ibm.com".
```

Please fix either the commit author or the Signed-off-by message.
</blockquote></details>

Done.

---
___
*[meson.build, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC0R8G3iMX_bB4mZUF:-MfDAi1DDXIrq0-zy1t-:b-yslolh) ([raw file](https://github.com/oscarlab/graphene/blob/a4eb2a20bd6eed053ff23e3a0c76ed3973cb6c46/meson.build#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why does it work? On a non-x86-64 machine, `cflags_custom_stack_protector` is not defined at all after this IF clause. So do we end up with `-fno-stack-protector` and nothing at all?
</blockquote></details>

I added the else branch I kept for ppc64 now as well.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/meson.build, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfXIkw20ziCdVJrW9N0:-MfXIkw20ziCdVJrW9N1:bukr4hw) ([raw file](https://github.com/oscarlab/graphene/blob/a499c753820e9f5cd98516fa13f382617927a032/LibOS/meson.build#L28)):*
> ```Meson
> if host_machine.cpu_family() == 'x86_64'
>     glibc_libs += 'glibc-build/elf/ld-linux-x86-64.so.2'
>     glibc_libs += 'glibc-build/mathvec/libmvec.so.1'
> ```

Interesting, so, this one doesn't exist at all outside x86?

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC-nPyBo4D0Ok0Jt2l:-MfDB5Cl2PagzvkFNdWg:b-896fix) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---
___
*[LibOS/meson.build, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfXIkw20ziCdVJrW9N0:-MfXLIPt6NascW_th0Z8:b-7t95e9) ([raw file](https://github.com/oscarlab/graphene/blob/a499c753820e9f5cd98516fa13f382617927a032/LibOS/meson.build#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Interesting, so, this one doesn't exist at all outside x86?
</blockquote></details>

It for sure doesn't get built as part of the glibc build but I also don't find it on my hard disk nor here in other arch packages than for amd64: https://packages.ubuntu.com/bionic/libc6

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2569#-MfC-nPyBo4D0Ok0Jt2l:-MfXgCj2DSq1p88xkm6E:b-o9ojry) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@stefanberger FYI: you don't have to post "Done." again in case your disposition was wrong on this discussion, you can change it without writing anything using that circular icon on the right.

---

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2569)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
