### PR TITLE
[LibOS] Fix type field in dirent struct

### PR DESCRIPTION
**Pull request by vijaydhanraj**
## Description of the changes 
Currently, in graphene, the type field in dirent struct is only updated for the parent directory and is set to DT_UNKNOWN type for its children. But APIs like sysconf(_SC_NPROCESSORS_CONF) rely on type field to identify the number of processors on the host by reading the number of cpuX directories and ensuring their type is set to DT_DIR. This patch addresses the issue by updating the dirent type appropriately even for child directories or files.

## Actual Results
```
/proc/., type=4
/proc/1, type=0
/proc/2, type=0
/proc/3, type=0
/proc/self, type=0
/proc/4, type=0
/proc/meminfo, type=0
/proc/cpuinfo, type=0
```
## Expected Results
```
/proc/., type=4
/proc/1, type=4
/proc/2, type=4
/proc/3, type=4
/proc/self, type=4
/proc/4, type=4
/proc/meminfo, type=8
/proc/cpuinfo, type=8
```
where `DT_DIR` is 4 and `DT_REG` is 8.

## How to test this PR? 
Slightly modified proc_common.c regression test to print out `dirent->d_type` to show the problem as well as the fix.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1944#-MLMbri960a4gjpqptXQ:-MLMbriA-lLns-Ir86jw:b8ennrc) (no related file):*
Could you update LibOS regression python script? Somewhere here:
https://github.com/oscarlab/graphene/blob/17b809bff35e8c5b5e92aa59920940d83301b8a2/LibOS/shim/test/regression/test_libos.py#L538-L544

Please add `, type = %d` to asserts, where `%d == DT_DIR/DT_REG`. It seems though that Python doesn't have constants for `DT_DIR` and `DT_REG`, so you'll have to declare them at the top of this script file. Like here: https://lists.gnu.org/archive/html/coreutils/2011-05/msg00047.html

---
___
*[LibOS/shim/src/fs/shim_namei.c, line 750 at r1](https://reviewable.io/reviews/oscarlab/graphene/1944#-MLMd-X02hY5vcYueAl9:-MLMd-X02hY5vcYueAlA:b-73m6vw) ([raw file](https://github.com/oscarlab/graphene/blob/0278d691f058b66c1fedac3a516467097515f0fb/LibOS/shim/src/fs/shim_namei.c#L750)):*
> ```C
> 
>         if (!(child->state & DENTRY_VALID)) {
>             set_dirent_type(&child->type, d->type);
> ```

Nice catch!

**Comment by vijaydhanraj** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1944#-MLMbri960a4gjpqptXQ:-MLPyW0J0jzzjUQOCmij:b-ra1awy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you update LibOS regression python script? Somewhere here:
https://github.com/oscarlab/graphene/blob/17b809bff35e8c5b5e92aa59920940d83301b8a2/LibOS/shim/test/regression/test_libos.py#L538-L544

Please add `, type = %d` to asserts, where `%d == DT_DIR/DT_REG`. It seems though that Python doesn't have constants for `DT_DIR` and `DT_REG`, so you'll have to declare them at the top of this script file. Like here: https://lists.gnu.org/archive/html/coreutils/2011-05/msg00047.html
</blockquote></details>

@dimakuv Tested this change and it seems to work fine. Is this ok?
```
diff --git a/LibOS/shim/test/regression/test_libos.py b/LibOS/shim/test/regression/test_libos.py
index 1666d8ea..857d2d2a 100644
--- a/LibOS/shim/test/regression/test_libos.py
+++ b/LibOS/shim/test/regression/test_libos.py
@@ -532,6 +532,7 @@ class TC_31_SyscallSGX(RegressionTestCase):

 class TC_40_FileSystem(RegressionTestCase):
     def test_000_proc(self):
+        (DT_DIR, DT_REG) = (4, 8,)
         stdout, _ = self.run_binary(['proc_common'])
         self.assertIn('/proc/1/..', stdout)
         self.assertIn('/proc/1/cwd', stdout)
@@ -545,14 +546,14 @@ class TC_40_FileSystem(RegressionTestCase):
         self.assertIn('/proc/self/root', stdout)
         self.assertIn('/proc/self/fd', stdout)
         self.assertIn('/proc/self/maps', stdout)
-        self.assertIn('/proc/.', stdout)
-        self.assertIn('/proc/1', stdout)
-        self.assertIn('/proc/2', stdout)
-        self.assertIn('/proc/3', stdout)
-        self.assertIn('/proc/4', stdout)
-        self.assertIn('/proc/self', stdout)
-        self.assertIn('/proc/meminfo', stdout)
-        self.assertIn('/proc/cpuinfo', stdout)
+        self.assertIn('/proc/., type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/1, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/2, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/3, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/4, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/self, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/meminfo, type: {0}'.format(DT_REG), stdout)
+        self.assertIn('/proc/cpuinfo, type: {0}'.format(DT_REG), stdout)
```

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1944#-MLMbri960a4gjpqptXQ:-MLR8tHZ8vOcpBw-m-24:beuvp91) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv Tested this change and it seems to work fine. Is this ok?
```
diff --git a/LibOS/shim/test/regression/test_libos.py b/LibOS/shim/test/regression/test_libos.py
index 1666d8ea..857d2d2a 100644
--- a/LibOS/shim/test/regression/test_libos.py
+++ b/LibOS/shim/test/regression/test_libos.py
@@ -532,6 +532,7 @@ class TC_31_SyscallSGX(RegressionTestCase):

 class TC_40_FileSystem(RegressionTestCase):
     def test_000_proc(self):
+        (DT_DIR, DT_REG) = (4, 8,)
         stdout, _ = self.run_binary(['proc_common'])
         self.assertIn('/proc/1/..', stdout)
         self.assertIn('/proc/1/cwd', stdout)
@@ -545,14 +546,14 @@ class TC_40_FileSystem(RegressionTestCase):
         self.assertIn('/proc/self/root', stdout)
         self.assertIn('/proc/self/fd', stdout)
         self.assertIn('/proc/self/maps', stdout)
-        self.assertIn('/proc/.', stdout)
-        self.assertIn('/proc/1', stdout)
-        self.assertIn('/proc/2', stdout)
-        self.assertIn('/proc/3', stdout)
-        self.assertIn('/proc/4', stdout)
-        self.assertIn('/proc/self', stdout)
-        self.assertIn('/proc/meminfo', stdout)
-        self.assertIn('/proc/cpuinfo', stdout)
+        self.assertIn('/proc/., type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/1, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/2, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/3, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/4, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/self, type: {0}'.format(DT_DIR), stdout)
+        self.assertIn('/proc/meminfo, type: {0}'.format(DT_REG), stdout)
+        self.assertIn('/proc/cpuinfo, type: {0}'.format(DT_REG), stdout)
```

</blockquote></details>

Yes, this looks good. Please update the PR.

---

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1944#-MLMbri960a4gjpqptXQ:-MLREWEO65IBTCe3LzM1:bkm950l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this looks good. Please update the PR.
</blockquote></details>

sure, I have updated the PR.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1944)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
