### PR TITLE
[Pal/lib] Add strtoll() and funcs from ctype.h for string manipulation

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

These functions are required by the TOML C source code, which will be embedded into Graphene in a future commit.

## How to test this PR? 

All tests must pass. TOML is coming soon.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1926)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1926)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1926)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-apps please (landed on a dying Jenkins worker)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1926)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1926)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
