### PR TITLE
[LibOS] Rename shim_process

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This PR renames `shim_process` to `shim_process_ipc_info` to better reflect it's purpose (+ I want to use `shim_process` in another PR) and removes unused `exit_code` field from it.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: 0 of 18 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_ipc.h, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYxrE76ibXOMM6bpMr:-MJYxrE806FYdRoDG3BR:b-v56waa) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/include/shim_ipc.h#L102)):*
> ```objc
> };
> 
> struct shim_process_ipc_info {
> ```

If somebody comes up with a better name please let me know
___
*[LibOS/shim/include/shim_ipc.h, line 110 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYxurC1c6ikx2-35a_:-MJYxurC1c6ikx2-35aa:bndnm9n) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/include/shim_ipc.h#L110)):*
> ```objc
> };
> 
> extern struct shim_process_ipc_info g_process_ipc_info;
> ```

ditto (better name)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYxrE76ibXOMM6bpMr:-MJYy4-m6YT3T5r3qc_8:b-6axrb5) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/include/shim_ipc.h#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If somebody comes up with a better name please let me know
</blockquote></details>

sounds good IMO
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYzoAZ8_fLl7fQy2Fm:-MJYzoAZ8_fLl7fQy2Fn:biiqlr5) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/src/ipc/shim_ipc_ranges.c#L675)):*
> ```C
>             if (need_locate && qstrempty(&g_process_ipc_info.ns->uri)) {
>                 /* not g_process_ipc_info.self but g_process_ipc_info.ns */
>                 bool is_self_ipc_info      = false;
> ```

please un-align, looks ugly

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYzoAZ8_fLl7fQy2Fm:-MJZ1nBMAFEhVD41vMo2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/src/ipc/shim_ipc_ranges.c#L675)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please un-align, looks ugly
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-18.04 please (fork11 from LTP timed out, known issue).

**Review by yamahata — DISMISSED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, 13 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 103 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaFcUn2erEmXbmJFD2:-MJaFcUn2erEmXbmJFD3:bjmrpt4) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/include/shim_ipc.h#L103)):*
> ```objc
> 
> struct shim_process_ipc_info {
>     IDTYPE vmid;
> ```

Since we're here: is this `vmid` field needed? It should be the same as `shim_process_ipc_info::self::vmid`. Not blocking though, as it is in many places.
___
*[LibOS/shim/src/shim_checkpoint.c, line 573 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaG6rN3b3lB3_LZ-Gi:-MJaG6rO3z2IzNKdsCXj:b58093c) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/shim_checkpoint.c#L573)):*
> ```C
>                                        struct shim_thread* thread, ...) {
>     int ret = 0;
>     struct shim_process_ipc_info* process = NULL;
> ```

Could we rename the variable itself? `process` -> `process_ipc_info`.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 189 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaHDaYB3pH8qXOCntK:-MJaHDaYB3pH8qXOCntL:bg6cr2) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L189)):*
> ```C
> }
> 
> struct shim_process_ipc_info* create_process_ipc_info(bool dup_cur_process) {
> ```

Can we rename `dup_cur_process` -> `is_execve`?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 190 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaH5_89mcWhBIRG0ha:-MJaH5_89mcWhBIRG0hb:b-l61adz) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L190)):*
> ```C
> 
> struct shim_process_ipc_info* create_process_ipc_info(bool dup_cur_process) {
>     struct shim_process_ipc_info* new_process = calloc(1, sizeof(*new_process));
> ```

Can we rename `new_process` -> `process_ipc_info` or `new_process_ipc_info`?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 249 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaHVbS2GHnSbNe7E4y:-MJaHVbS2GHnSbNe7E4z:b-6jcndy) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L249)):*
> ```C
> }
> 
> void free_process_ipc_info(struct shim_process_ipc_info* process) {
> ```

Please rename `process`- > `process_ipc_info`.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 375 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaIooX1ag7xBJrH38A:-MJaIooX1ag7xBJrH38B:b-xipbuu) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L375)):*
> ```C
> }
> 
> struct shim_ipc_info* create_ipc_info_cur_process(bool is_self_ipc_info) {
> ```

Now that we don't have `cur_process`, maybe rename to `create_ipc_info_and_port(bool use_vmid_as_port_name)`?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 397 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaJXNY0KJ_BXsno4pk:-MJaJXNY0KJ_BXsno4pl:bmi7439) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L397)):*
> ```C
> }
> 
> int get_ipc_info_cur_process(struct shim_ipc_info** info) {
> ```

I think this whole function can be removed. In reality, `g_process_ipc_info.self` always exists, and never really deleted during Graphene process lifetime, so this function invocation can be replaced with access to `g_process_ipc_info.self`.

This may be too intrusive and not in scope of this PR, so I can take off this comment. I just payed attention to this func because it has `cur_process` in its name.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 460 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaI1IQ857clUXqlCyV:-MJaI1IQ857clUXqlCyW:b-a79rbo) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L460)):*
> ```C
> 
>     struct shim_process_ipc_info* process     = (struct shim_process_ipc_info*)obj;
>     struct shim_process_ipc_info* new_process = NULL;
> ```

Could you rename these two to `process_ipc_info` and `new_process_ipc_info`?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 493 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaI9uO-vPj2ol-ne9y:-MJaI9uO-vPj2ol-ne9z:byp1ktf) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L493)):*
> ```C
> BEGIN_RS_FUNC(process_ipc_info) {
>     __UNUSED(offset);
>     struct shim_process_ipc_info* process = (void*)(base + GET_CP_FUNC_ENTRY());
> ```

Rename
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYzoAZ8_fLl7fQy2Fm:-MJaKez50Biy7BL9oQDK:b-s6fgul) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/src/ipc/shim_ipc_ranges.c#L675)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is no point in separate line to declare this bool variable...
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 721 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaKq7f9HC6-bgN2qqr:-MJaKq7gC-EG9gHDzCkK:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc_ranges.c#L721)):*
> ```C
>     }
> 
>     bool is_self_ipc_info = false; /* not g_process_ipc_info.self but g_process_ipc_info.ns */
> ```

ditto
___
*[LibOS/shim/src/sys/shim_exec.c, line 176 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLM2nDxnvIVyv2kS3:-MJaLM2nDxnvIVyv2kS4:bdmohqj) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_exec.c#L176)):*
> ```C
>  * process is new process which is forked and waits for checkpoint. */
> static int migrate_execve(struct shim_cp_store* cpstore, struct shim_thread* thread,
>                           struct shim_process_ipc_info* process, va_list ap) {
> ```

Could we rename `process` -> `process_ipc_info`
___
*[LibOS/shim/src/sys/shim_fork.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLPXNCyiCZyKHD6Zp:-MJaLPXNCyiCZyKHD6Zq:b-t5fvim) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_fork.c#L25)):*
> ```C
> #include "shim_thread.h"
> 
> static BEGIN_MIGRATION_DEF(fork, struct shim_thread* thread, struct shim_process_ipc_info* process) {
> ```

For uniformity, rename `process` -> `proc`
___
*[LibOS/shim/src/sys/shim_fork.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLYh6DqbAlBmcF83f:-MJaLYh6DqbAlBmcF83g:bdmohqj) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_fork.c#L41)):*
> ```C
> 
> int migrate_fork(struct shim_cp_store* store, struct shim_thread* thread,
>                  struct shim_process_ipc_info* process, va_list ap) {
> ```

Could we rename `process` -> `process_ipc_info`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: 11 of 18 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 103 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaFcUn2erEmXbmJFD2:-MJb2Voy3lcv0kVAOqX6:buscgrn) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/include/shim_ipc.h#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here: is this `vmid` field needed? It should be the same as `shim_process_ipc_info::self::vmid`. Not blocking though, as it is in many places.
</blockquote></details>

Not sure, but actually keeping it might be a good idea: to access `self` we need to hold the lock and, as you pointed out, this `vmid` field is used in a lot of places.
___
*[LibOS/shim/src/shim_checkpoint.c, line 573 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaG6rN3b3lB3_LZ-Gi:-MJb3b9F57tEO2OvklG5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/shim_checkpoint.c#L573)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we rename the variable itself? `process` -> `process_ipc_info`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 189 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaHDaYB3pH8qXOCntK:-MJb48dV0zILMu8iiNc7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename `dup_cur_process` -> `is_execve`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 190 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaH5_89mcWhBIRG0ha:-MJb4ti68Y1yTThlvVCn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename `new_process` -> `process_ipc_info` or `new_process_ipc_info`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 249 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaHVbS2GHnSbNe7E4y:-MJb502B7IsiJlAR1Yo6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `process`- > `process_ipc_info`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 375 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaIooX1ag7xBJrH38A:-MJb5q51ChWrNEDZK459:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L375)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we don't have `cur_process`, maybe rename to `create_ipc_info_and_port(bool use_vmid_as_port_name)`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 397 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaJXNY0KJ_BXsno4pk:-MJbBJsH8NKiWZjAYAf-:b6fbump) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L397)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this whole function can be removed. In reality, `g_process_ipc_info.self` always exists, and never really deleted during Graphene process lifetime, so this function invocation can be replaced with access to `g_process_ipc_info.self`.

This may be too intrusive and not in scope of this PR, so I can take off this comment. I just payed attention to this func because it has `cur_process` in its name.
</blockquote></details>

This would require checking that this field is never changed and safe to access without the `g_process_ipc_info.lock` lock. There's a lot of places in Graphene that access this field, so all of them should be updated too, I guess.
I would rather not do that in this PR
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 460 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaI1IQ857clUXqlCyV:-MJbCARm9Gfns7lQotzW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you rename these two to `process_ipc_info` and `new_process_ipc_info`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 493 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaI9uO-vPj2ol-ne9y:-MJbCQeQ3GfqI-6JVH-n:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L493)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJYzoAZ8_fLl7fQy2Fm:-MJbCyME7vjG0G2v7Ivp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f0758d20eec2f67fa819fec7a5f54d59213d77a/LibOS/shim/src/ipc/shim_ipc_ranges.c#L675)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no point in separate line to declare this bool variable...
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 721 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaKq7f9HC6-bgN2qqr:-MJbDJPu2YigkK2zW5FZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc_ranges.c#L721)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 176 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLM2nDxnvIVyv2kS3:-MJbDTysE66-zQ5AtMez:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_exec.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we rename `process` -> `process_ipc_info`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_fork.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLPXNCyiCZyKHD6Zp:-MJbDhgA0nP8S8OFI1cD:b-lgsxu5) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_fork.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity, rename `process` -> `proc`
</blockquote></details>

Done (`process_ipc_info`).
___
*[LibOS/shim/src/sys/shim_fork.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLYh6DqbAlBmcF83f:-MJbDtnz6PTUwTXB_mo8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_fork.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we rename `process` -> `process_ipc_info`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 103 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaFcUn2erEmXbmJFD2:-MJbFG0q2B-RJPDH-9Dh:bmctigb) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/include/shim_ipc.h#L103)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure, but actually keeping it might be a good idea: to access `self` we need to hold the lock and, as you pointed out, this `vmid` field is used in a lot of places.
</blockquote></details>

OK, true.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 397 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaJXNY0KJ_BXsno4pk:-MJbFkmj1EYexeZ4FN5r:b-nhwasd) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/ipc/shim_ipc.c#L397)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This would require checking that this field is never changed and safe to access without the `g_process_ipc_info.lock` lock. There's a lot of places in Graphene that access this field, so all of them should be updated too, I guess.
I would rather not do that in this PR
</blockquote></details>

OK, not for this PR.
___
*[LibOS/shim/src/sys/shim_exec.c, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJbG9LN7dZiSw5RgrtA:-MJbG9LO7XEMsFq3atgf:b-deeiu6) ([raw file](https://github.com/oscarlab/graphene/blob/4e5ded827db19f473d664bb01c33ebe4db1096f7/LibOS/shim/src/sys/shim_exec.c#L160)):*
> ```C
> }
> 
> static BEGIN_MIGRATION_DEF(execve, struct shim_thread* thread, struct shim_process_ipc_info* proc,
> ```

Since you changed in `shim_fork.c`, then please also change here: `proc` -> `process_ipc_info`.
___
*[LibOS/shim/src/sys/shim_fork.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJaLPXNCyiCZyKHD6Zp:-MJbGFJU8eNEvT_nQQrr:b-rromu1) ([raw file](https://github.com/oscarlab/graphene/blob/89fc1a402be7f40177a591339737d6bf9dc68f9b/LibOS/shim/src/sys/shim_fork.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done (`process_ipc_info`).
</blockquote></details>

OK. I wanted uniformity with the same migration function as in `shim_exec.c`, but this is also ok. See my other comment.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_exec.c, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/1887#-MJbG9LN7dZiSw5RgrtA:-MJbKI9aBZPH8RXH_8kC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e5ded827db19f473d664bb01c33ebe4db1096f7/LibOS/shim/src/sys/shim_exec.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since you changed in `shim_fork.c`, then please also change here: `proc` -> `process_ipc_info`.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1887)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (Jenkins was restarted when the job was running)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-gsc please (Jenkins was restarted while the job was still running)

**Pull request merged**
