### PR TITLE
[LibOS] test/apps: Allow SSL/TLS connections in Nginx

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR adds the ability to build and test Nginx with HTTPS enabled.

## How to test this PR? 

There is already a test of Nginx (but only with HTTP) in our Jenkins. Nginx-HTTPS doesn't work well with `ab` (Apache Benchmark), so I didn't include this test in Jenkins (I mean even the native version, without Graphene, because `ab` is terrible). However, one can try with `wrk` or `wrk2` -- it works perfectly well.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2030#-MQJ5WeoBEwo-fN4giXE:-MQJ5WeoBEwo-fN4giXF:b-3ek124) (no related file):*
I'd prefer to wait with merging this PR for #2050, to not complicate #2050 any further.

---
___
*[Examples/nginx/Makefile, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/2030#-MQJ4GXJ7hOM6RShOapP:-MQJ4GXKACFymnW7vUhs:b-dgydem) ([raw file](https://github.com/oscarlab/graphene/blob/cc4ca2e002d15e8f58c48320561eb7e1452ea09a/Examples/nginx/Makefile#L136)):*
> ```Makefile
> config: $(INSTALL_DIR)/conf/nginx-graphene.conf
> 
> $(INSTALL_DIR)/conf/nginx-graphene.conf: nginx-graphene.conf $(INSTALL_DIR)/sbin/nginx
> ```

Could you add `.template` suffix?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: 4 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2030#-MQJ5WeoBEwo-fN4giXE:-MQLwvK82WNPnKPPjUa1:b-k6ya3p) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to wait with merging this PR for #2050, to not complicate #2050 any further.
</blockquote></details>

Of course, no problem.

---
___
*[Examples/nginx/Makefile, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/2030#-MQJ4GXJ7hOM6RShOapP:-MQLzCOd6UqODd6iY9Gw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cc4ca2e002d15e8f58c48320561eb7e1452ea09a/Examples/nginx/Makefile#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add `.template` suffix?
</blockquote></details>

Done.

**Review by mkow — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: 2 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2030#-MQJ5WeoBEwo-fN4giXE:-MQvu2gl5KJHsMGaSZgF:bmbbs9t) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Of course, no problem.
</blockquote></details>

Done, rebased to the latest master containing 2050.

---

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-apps please (`Redis` failed to start in SGX mode, this is unrelated since Redis starts before Nginx, and this PR doesn't touch anything except Nginx; maybe SGX infrastructure fails on `bobothebear` worker)?

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2030)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
