### PR TITLE
[GSC] Fix a bug in apploader's arguments testing

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

I guess this has never worked?

CC: @vahldiek

## How to test this PR? 

Try to use `GSC_PAL` env.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1896)

### CODE REVIEW

**Comment by vahldiek** [comment]
Setting 'GSC_PAL' to 'Linux-SGX' is not part of GSC's Jenkins testing. So could very much be the case, that I never tried it. Thanks for catching it!

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1896)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
