### PR TITLE
[Pal/lib] Fix memory manager

### PR DESCRIPTION
**Pull request by yamahata**
fix memger and slabmgr. 
- concurrency bug. memory leak
- refactoring

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [x] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1347)

### CODE REVIEW

**Comment by bigdata-memory** [comment]
___
*[Pal/include/lib/memmgr.h, line 137 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXgAOa5QkA-G8niUeJ:-MFXgAOb2bNsQYo_SEFZ:bf36apt) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L137)):*
> ```objc
>     INIT_LISTP(&mgr->free_list);
> 
>     MEM_AREA area = (MEM_AREA)(mem + sizeof(*mgr));
> ```

The ```sizeof(MEM_MGR_TYPE)``` is preferable than de-referencing the 'mgr' just for retrieving its size.

**Comment by bigdata-memory** [comment]
___
*[Pal/include/lib/memmgr.h, line 150 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXi5c14JtGSffSw4es:-MFXi5c14JtGSffSw4et:b-rqxvo7) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L150)):*
> ```objc
> 
>     assert(size);
>     area = (MEM_AREA)system_malloc(sizeof(*area) + __SUM_OBJ_SIZE(size));
> ```

ditto.

**Comment by bigdata-memory** [comment]
___
*[Pal/include/lib/memmgr.h, line 165 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXlhfH19LGPhxlMaOI:-MFXlhfH19LGPhxlMaOJ:bkuzlfv) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L165)):*
> ```objc
>     MEM_AREA tmp, n;
> 
>     MEM_AREA last = LISTP_LAST_ENTRY(&mgr->area_list, MEM_AREA_TYPE, __list);
> ```

```assert(mgr!=NULL)```

**Comment by bigdata-memory** [comment]
___
*[Pal/include/lib/memmgr.h, line 179 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXn21F7828me6_zaId:-MFXn21F7828me6_zaIe:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L179)):*
> ```objc
> 
>     SYSTEM_LOCK();
>     while (mgr->obj == mgr->obj_limit && LISTP_EMPTY(&mgr->free_list)) {
> ```

ditto

**Comment by bigdata-memory** [comment]
___
*[Pal/include/lib/memmgr.h, line 190 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXsBkR6sg__VPIxhUz:-MFXsBkS0QwYeqGua3IK:b-t5jnqd) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L190)):*
> ```objc
> 
>         SYSTEM_UNLOCK();
>         if (!size)
> ```

moving it to the beginning of this function if it is not relevant to ```if (area) {```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1347)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @yamahata)

___
*[Pal/include/lib/memmgr.h, line 137 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXgAOa5QkA-G8niUeJ:-MF_I58e0nbpQl6alqWc:b9h2414) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L137)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

The ```sizeof(MEM_MGR_TYPE)``` is preferable than de-referencing the 'mgr' just for retrieving its size.
</blockquote></details>

Why would it be? `sizeof(*mgr)` is less error-prone when refactoring.
___
*[Pal/include/lib/memmgr.h, line 150 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXi5c14JtGSffSw4es:-MF_IQeN-ZSFamUqkhsm:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L150)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

ditto
___
*[Pal/include/lib/memmgr.h, line 165 at r2](https://reviewable.io/reviews/oscarlab/graphene/1347#-MFXlhfH19LGPhxlMaOI:-MF_Id2JCxwKFTvsYhcn:b-9t6r61) ([raw file](https://github.com/oscarlab/graphene/blob/ce1066f0e7345a5be01ef5a75d33e44c3f098bb3/Pal/include/lib/memmgr.h#L165)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

```assert(mgr!=NULL)```
</blockquote></details>

Why would we assert this? It's not a public API and in general we don't assert validity of all params in all functions, that would be too much hassle and performance overhead.

**Pull request closed without merging**
