### PR TITLE
Enable full GDB support for SGX mode

### PR DESCRIPTION
**Pull request by chiache**
This patch completes the GDB support for Graphene-SGX. The changes include:
- Implemented PTRACE_SETREGS and PTRACE_SETUSER in sgx_gdb.so
- Setting the DBGOPTIN flag (bit 0) in TCSs when enclave starts
- Wrapping waitpid() for GDB, to step into enclaves after breakpoints (detecting INT 3/0xcc injected at the breakpoints)
- Disabling "Displaced Stepping" in GDB, which will cause segfault when stepping

Sample output:
```
$ SGX=1 GDB=1 ./pal_loader helloworld

(output cut)

Breakpoint 1, ocall_write (fd=1, buf=0xffe9318, count=30) at enclave_ocalls.c:246
246	{
(gdb) n
250	    if (count > 4096) {
(gdb) display/i $pc
1: x/i $pc
=> 0xbd8759a <ocall_write+26>:	cmp    $0x1000,%edx
(gdb) si
248	    void * obuf = NULL;
1: x/i $pc
=> 0xbd875a0 <ocall_write+32>:	movq   $0x0,-0x38(%rbp)
(gdb) 
250	    if (count > 4096) {
1: x/i $pc
=> 0xbd875a8 <ocall_write+40>:	jbe    0xbd875cc <ocall_write+76>
```

### CODE REVIEW

**Comment by chiache** [comment]
Test this please.

**Comment by donporter** [comment]
Jenkins failed because futex_wait03 hanged.  I'm thinking this might need to move to the burgeoning flaky list (in the interest of getting a solid base of tests that pass reliably), unless there are more changes that might have caused this problem.

**Comment by chiache** [comment]
Test this please.

**Comment by donporter** [comment]
Test this please

**Comment by chiache** [comment]
Test this please.

**Comment by donporter** [comment]
Same issue with LTP test recv01

**Pull request merged**
