### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by rahulunair**
update to latest sgx install doc link, the previous link was for 2.10 and gives a 404 error

Signed-off-by: rahulunair@gmail.com

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216)* status: all files reviewed, 1 unresolved discussion (waiting on @rahulunair)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2216#-MVJTwRd84Z9E58_mNM6:-MVJTwRd84Z9E58_mNM7:bljcs47) (no related file):*
The commit message will need an update (see https://graphene.readthedocs.io/en/latest/devel/contributing.html), but we can do this ourselves when rebasing.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @rahulunair)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2216#-MVJUD2v44ZMH9PISgOy:-MVJUD2v44ZMH9PISgOz:b-7jyk5c) (no related file):*
@rahulunair: Your commit is missing a sign-off line, could you please fix it? We require all commits to be signed off by the contributors.

---

**Comment by rahulunair** [comment]
Thanks @mkow for the review, I have created a new PR, with the change and have signed the same at #2240

**Review by mkow — COMMENTED** [review]
You could just force push it here, no need to create a new PR for this ;)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2216#-:-MVrbqKa2C3pKrRCYmbl:bgk460r)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @rahulunair)

**Pull request closed without merging**
