### PR TITLE
[LibOS] Drop support for glibc 2.23

### PR DESCRIPTION
**Pull request by pwmarcz**
As discussed in #2086. glibc 2.23 requires many additional patches, is not built on Jenkins (we test Ubuntu 16 with glibc 2.27), and while using newer glibc with Ubuntu 16 may produce some incompatibilities, we're planning to drop Ubuntu 16 soon.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
Yay, finally! :)

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150#-:-MT5vvwc0Y-_iESm9Jji:bofhf5d)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2150#-MT6-pHT45n2jTYcj0kf:-MT6-pHU9u1N-dwepBU6:b-71asdz) (no related file):*
> ...and while using newer glibc with Ubuntu 16 may produce some incompatibilities...

FYI: I periodically use Ubuntu 16.04 for testing, development and debugging of Graphene with Glibc 2.27 (default). I haven't detected any issues with this Glibc version.

---

**Review by yamahata — DISMISSED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2150)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
