### PR TITLE
[Pal/Linux-SGX] Allocate program headers when reading ELFs

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

The code relied on the assumption that the program headers will fit within FILEBUF_SIZE bytes from beginning of file. This is usually true in practice, but is not guaranteed, and as a result Graphene could read outside of the allocated buffer.

Instead, we perform two reads: first for the ELF header, then for the program headers.

## How to test this PR? 

Existing tests should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2562#-Mf5aCwHE44Mp3UN6bT1:-Mf5aCwI9Tx9HKBycsqr:bwl795r) ([raw file](https://github.com/oscarlab/graphene/blob/962881c207775444083cea13dae753e931cde9b0/Pal/src/host/Linux-SGX/sgx_main.c#L61)):*
> ```C
>         return ret;
> 
>     return 0;
> ```

You can just return `ret` and remove the `if` above.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2562#-Mf5aCwHE44Mp3UN6bT1:-Mf7gBtk-fIB7LwxYAhX:b-bs1bxo) ([raw file](https://github.com/oscarlab/graphene/blob/962881c207775444083cea13dae753e931cde9b0/Pal/src/host/Linux-SGX/sgx_main.c#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You can just return `ret` and remove the `if` above.
</blockquote></details>

Right, `read_all` returns 0. Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2562)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-20.04 please (`apps.LTP.fsync02` timed out, unrelated to the PR)

**Pull request merged**
