### PR TITLE
Upgrade LTP to 20200930

### PR DESCRIPTION
**Pull request by pwmarcz**
Based on #1906.

Some interesting failures that can be investigated (marked with TODO).

Important also because the older LTP fails to compile with new GCC.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKo5yjsAnmqYQKTn7j8:-MKo5yjsAnmqYQKTn7j9:b-kd8sg0) ([raw file](https://github.com/oscarlab/graphene/blob/afa3651c9400dc2938c04ed485968c39fcc099e0/LibOS/shim/test/ltp/ltp.cfg#L9)):*
> ```INI
> # - tmpfs - tries to mount tmpfs
> # - copy child - tries to copy a child binary (X_child) to "."
> # - kernel config - tries to real kernel .config
> ```

`real` -> `read`

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKstsUh5aoKIdz1KLS2:-MKstsUiAEyMrLaSxocz:bm68csu) (no related file):*
@pwmarcz #1906 was merged. Could you rebase on recent master?

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: 8 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKstsUh5aoKIdz1KLS2:-MKtOuaD2J8ROO7YF72B:bh6vwsr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz #1906 was merged. Could you rebase on recent master?
</blockquote></details>

Done, and in line with the previous feedback, I removed the TODOs from comments.

---
___
*[LibOS/shim/test/ltp/ltp.cfg, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKo5yjsAnmqYQKTn7j8:-MKtOsx07D_XpRYAhPHu:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/afa3651c9400dc2938c04ed485968c39fcc099e0/LibOS/shim/test/ltp/ltp.cfg#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`real` -> `read`
</blockquote></details>

Fixed.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 940 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtXVUGDPa3TP18ZBSp:-MKtXVUGDPa3TP18ZBSq:b-dy4d2r) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L940)):*
> ```INI
> skip = yes
> 
> # looks for parted binary
> ```

What is `parted binary`?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2173 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtXkNv88ncX582PU4P:-MKtXkNv88ncX582PU4Q:b-1u20va) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L2173)):*
> ```INI
> 
> # EINVAL from native sendmsg()
> # also, shim_sendmmsg() has wrong vlen handling?
> ```

Could you make a separate issue on GitHub about this and expand a bit? This looks like a high-priority bug to fix.

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 7 of 18 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 940 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtXVUGDPa3TP18ZBSp:-MKtigLDBnDZhbINZYoP:bp6s3v) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L940)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `parted binary`?
</blockquote></details>

https://www.gnu.org/software/parted/
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2295 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtiy9C0ekmHtOHIh1i:-MKtiy9C0ekmHtOHIh1j:b-qs0xwv) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L2295)):*
> ```INI
> skip = yes
> 
> # runs sethostname("test_dom"), then gethostname() returns "test_domt". Off-by-one error?
> ```

Graphene error or LTP error? If our, this should be also made into issue.x

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 940 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtXVUGDPa3TP18ZBSp:-MKtuvt_8Rwg08lUPyoC:b-wnp5r8) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L940)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://www.gnu.org/software/parted/
</blockquote></details>

Added quotes so that it's more clear.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2173 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtXkNv88ncX582PU4P:-MKtqy2J4S7RlbToMMPV:b-xwxtl4) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L2173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you make a separate issue on GitHub about this and expand a bit? This looks like a high-priority bug to fix.
</blockquote></details>

Ticketed and linked in the file.

https://github.com/oscarlab/graphene/issues/1931
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2295 at r2](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKtiy9C0ekmHtOHIh1i:-MKtqyzv2NDRU69qDZLi:b-7tnngf) ([raw file](https://github.com/oscarlab/graphene/blob/2fbb875bde7afa3a2bf7b76ab1050634df626ae0/LibOS/shim/test/ltp/ltp.cfg#L2295)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Graphene error or LTP error? If our, this should be also made into issue.x
</blockquote></details>

Graphene error. Ticketed and linked in the file.

https://github.com/oscarlab/graphene/issues/1932

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 12 of 18 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 713 at r3](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKwWHQL4PObFpFsL3nq:-MKwWHQL4PObFpFsL3nr:bsqhrez) ([raw file](https://github.com/oscarlab/graphene/blob/cc770ed00bb0cee1dd08de36562499f53aac5df5/LibOS/shim/test/ltp/ltp.cfg#L713)):*
> ```INI
> # 1. fsync() on a pipe returns EROFS, not EINVAL
> # 2. fsync() on a socket returns EROFS, not EINVAL
> # 5. fsync() on a fifo returns EROFS,not EINVAL
> ```

space before `not`
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2391 at r3](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKwYDxr4BDovsTr5Y2y:-MKwYDxr4BDovsTr5Y2z:bn63dc2) ([raw file](https://github.com/oscarlab/graphene/blob/cc770ed00bb0cee1dd08de36562499f53aac5df5/LibOS/shim/test/ltp/ltp.cfg#L2391)):*
> ```INI
> skip = yes
> 
> # this test fails on Glibc 2.31; see https://github.com/linux-test-project/ltp/issues/646
> ```

This was fixed in the new LTP, see https://github.com/oscarlab/graphene-tests/pull/76#issuecomment-603943123.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 713 at r3](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKwWHQL4PObFpFsL3nq:-ML7RqK98JNkfupZPSTl:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/cc770ed00bb0cee1dd08de36562499f53aac5df5/LibOS/shim/test/ltp/ltp.cfg#L713)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

space before `not`
</blockquote></details>

Fixed.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2391 at r3](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKwYDxr4BDovsTr5Y2y:-ML7R5X30C0qIjqCmYPi:b-jt7jac) ([raw file](https://github.com/oscarlab/graphene/blob/cc770ed00bb0cee1dd08de36562499f53aac5df5/LibOS/shim/test/ltp/ltp.cfg#L2391)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This was fixed in the new LTP, see https://github.com/oscarlab/graphene-tests/pull/76#issuecomment-603943123.
</blockquote></details>

I see, but it still fails on `clock_settime()` syscall returning ENOSYS. And it looks like we don't implement neither that nor `settimeofday()`?

I updated the comments for these two tests (`settimerofday02` also tries asking for `CAP_SYS_TIME` capability).

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 2391 at r3](https://reviewable.io/reviews/oscarlab/graphene/1907#-MKwYDxr4BDovsTr5Y2y:-ML7aE7k2a-Vssa0Sjut:b-phvcr2) ([raw file](https://github.com/oscarlab/graphene/blob/cc770ed00bb0cee1dd08de36562499f53aac5df5/LibOS/shim/test/ltp/ltp.cfg#L2391)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I see, but it still fails on `clock_settime()` syscall returning ENOSYS. And it looks like we don't implement neither that nor `settimeofday()`?

I updated the comments for these two tests (`settimerofday02` also tries asking for `CAP_SYS_TIME` capability).
</blockquote></details>

Yes, we don't implement `clock_settime()` and `settimeofday()` unfortunately.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test failed, known issue)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1907)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

___
*[Jenkinsfiles/Linux, line 155 at r5](https://reviewable.io/reviews/oscarlab/graphene/1907#-MLEiPIr-GBrecfFL8ob:-MLEiPIr-GBrecfFL8oc:b-rqjf21) ([raw file](https://github.com/oscarlab/graphene/blob/8a381fab5c087cf8388a4c9311c888a5562ad3de/Jenkinsfiles/Linux#L155)):*
> ```
>                            git -C LibOS/shim/test/ltp/src checkout -- utils/ffsb-6.0-rc2/config.h.in utils/ffsb-6.0-rc2/configure
> 
>                            ./Scripts/gitignore-test
> ```

Oops, @woju just noticed that we removed too much... Let's re-add this line after merging #1858.

**Pull request merged**
