### PR TITLE
initialize rflags according to sysv x86-64 abi

### PR DESCRIPTION
**Pull request by yamahata**
Please fill in the following form before submitting this PR and ensure that your code follows our [coding style guideline](../blob/master/CODESTYLE.md).

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)
initialize rflags on function entry where necessary according to sysv x86-64 abi.

## How to test this PR? (if applicable)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/643)

### CODE REVIEW

**Comment by mkow** [comment]
Retest Jenkins-Debug please

**Comment by mkow** [comment]
Retest Jenkins-SGX please

**Comment by mkow** [comment]
Retest Jenkins-Debug please

**Comment by yamahata** [comment]
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/643)_ status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)
> 
> _[Pal/src/host/Linux-SGX/enclave_entry.S, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/643#-LdsiqMl9X8DEY2PP_pj:-LdsiqMl9X8DEY2PP_pk:bh9l1d) ([raw file](https://github.com/oscarlab/graphene/blob/c29bcc8c5be671508db4070492ee98afec3f7d94/Pal/src/host/Linux-SGX/enclave_entry.S#L21)):_
> 
> > ```
> > 
> > 	# x86-64 sysv abi requires %rFLAGS.DF = 0 on entry to function call.
> > 	cld
> > ```
> 
> AFAICS there are 3 cases where we call or return to C functions without setting flags:
> 
> 1. handle_ecall
> 2. _DkHandleExternalEvent in return_from_ocall
> 3. _DkExceptionHandler
> 
> This covers 1 and 2. But for 3 we need to clear it in SGX_GPR_RFLAGS. Also 2 would be broken after a naive merge with #640.
> 
> I would move the cld above the call to the C function (handle_ecall/_DkHandleExternalEvent). (And of course fix case 3)

Good catch.
#659

**Pull request merged**
