### PR TITLE
[Examples] Add SQLite

### PR DESCRIPTION
**Pull request by pwmarcz**
As requested by @dimakuv. This is on top of #2481 (fcntl locks), because it fails without these.

## Description of the changes 

A very simple example for `sqlite`. Wraps the Ubuntu executable.

## How to test this PR? 

There is a simple sanity check (`make regression`).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVp2-J3_ARQi_2dvWx:-MdVp2-K6bCII6I_TSIV:be162ul) (no related file):*
There is no README for SQLite. Please add some minimal `README.md` file. Please mention that this uses the system-installed SQLite3 version.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVpLc229uFKAwaWDKD:-MdVpLc229uFKAwaWDKE:bvwwc4x) (no related file):*
I tested it manually and looked at the outputs of our Jenkins. Looks good!

---
___
*[Examples/sqlite/Makefile, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVntJo2djssg28L0Fn:-MdVntJp1Xnix1eofUVx:b7yewtu) ([raw file](https://github.com/oscarlab/graphene/blob/2f056160df8d6e2a3badabae4dd78ff635b652a7/Examples/sqlite/Makefile#L23)):*
> ```Makefile
> all: sqlite3.manifest
> ifeq ($(SGX),1)
> all: sqlite3.manifest.sgx sqlite3.sig sqlite3.token
> ```

Technically only the `.token` file can be listed here, since all other files are dependencies for it. Not blocking though, it's good for readability.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVp2-J3_ARQi_2dvWx:-MdX7kd99CDaJkoMUhX0:b86jq9g) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no README for SQLite. Please add some minimal `README.md` file. Please mention that this uses the system-installed SQLite3 version.
</blockquote></details>

I added a README similar to other projects, and wrote a section about limitations of our locks.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVpLc229uFKAwaWDKD:-MdX7qcyC5rJjmVgj7ed:b9v7vwa) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tested it manually and looked at the outputs of our Jenkins. Looks good!
</blockquote></details>

Thanks for testing!

---
___
*[Examples/sqlite/Makefile, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdVntJo2djssg28L0Fn:-MdX4iiT8WtvXI_cnSXv:b-q6sc29) ([raw file](https://github.com/oscarlab/graphene/blob/2f056160df8d6e2a3badabae4dd78ff635b652a7/Examples/sqlite/Makefile#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically only the `.token` file can be listed here, since all other files are dependencies for it. Not blocking though, it's good for readability.
</blockquote></details>

Looks like we're pretty consistent with this:

```
graphene/Examples $ git grep 'all.*token'
apache/Makefile:all: httpd.manifest.sgx httpd.sig httpd.token
bash/Makefile:all: bash.manifest.sgx bash.sig bash.token
blender/Makefile:all: blender.manifest.sgx blender.sig blender.token
busybox/Makefile:all: busybox.manifest.sgx busybox.sig busybox.token
capnproto/Makefile:all: addressbook.manifest.sgx addressbook.sig addressbook.token
curl/Makefile:all: curl.manifest.sgx curl.sig curl.token
gcc/Makefile:all: gcc.manifest.sgx gcc.sig gcc.token
lighttpd/Makefile:all: lighttpd.manifest.sgx lighttpd.sig lighttpd.token
memcached/Makefile:all: memcached.manifest.sgx memcached.sig memcached.token
nginx/Makefile:all: nginx.manifest.sgx nginx.sig nginx.token
nodejs-express-server/Makefile:all: nodejs.manifest.sgx nodejs.sig nodejs.token
nodejs/Makefile:all: nodejs.manifest.sgx nodejs.sig nodejs.token
python/Makefile:all: python.manifest.sgx python.sig python.token
pytorch/Makefile:all: pytorch.manifest.sgx pytorch.sig pytorch.token
r/Makefile:all: R.manifest.sgx R.sig R.token
redis/Makefile:all: redis-server.manifest.sgx redis-server.sig redis-server.token
tensorflow-lite/Makefile:all: label_image.manifest.sgx label_image.sig label_image.token
```

So I'd rather leave it, at least until we have a better build-system for the examples.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Examples/sqlite/README.md, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdXDB7D8TVvDl0EviP_:-MdXDB7D8TVvDl0EviPa:b-e9ismq) ([raw file](https://github.com/oscarlab/graphene/blob/5a97bf712674cdfcc7aa99ec3b0746dd2dd75cec/Examples/sqlite/README.md#L1)):*
> ```Markdown
> # Bash example
> ```

`Bash`?
___
*[Examples/sqlite/README.md, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdXDHyI-G7I1NW7gVZN:-MdXDHyI-G7I1NW7gVZO:beyumwm) ([raw file](https://github.com/oscarlab/graphene/blob/5a97bf712674cdfcc7aa99ec3b0746dd2dd75cec/Examples/sqlite/README.md#L25)):*
> ```Markdown
> # Running SQLite with Graphene
> 
> Here's an example of running Bash scripts under Graphene:
> ```

`Bash scripts`?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/sqlite/README.md, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdXDB7D8TVvDl0EviP_:-Mdbb1JG-jhbJCFyddA7:bpolvqf) ([raw file](https://github.com/oscarlab/graphene/blob/5a97bf712674cdfcc7aa99ec3b0746dd2dd75cec/Examples/sqlite/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Bash`?
</blockquote></details>

Oops, I copied it and didn't replace everything, sorry. Fixed.
___
*[Examples/sqlite/README.md, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/2493#-MdXDHyI-G7I1NW7gVZN:-Mdbb8P62iBR7PoSI5hJ:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/5a97bf712674cdfcc7aa99ec3b0746dd2dd75cec/Examples/sqlite/README.md#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Bash scripts`?
</blockquote></details>

Fixed.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: 14 of 31 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-Mdc_GVdBP90t5C7ezb1:-Mdc_GVe2d1xG6-awLYi:bykfdzj) (no related file):*
Files from your PR crept into this one. Please rebase to the latest master to fix it.

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: 14 of 31 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-Mdc_GVdBP90t5C7ezb1:-MdcalaD8Aaeyu6Vu_IK:b-4m1l96) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Files from your PR crept into this one. Please rebase to the latest master to fix it.
</blockquote></details>

Interesting, so that happens when you do PR to a PR... Sorry for the mess, I see the rest of the files landed in "Reverted" now.

---

**Review by dimakuv — APPROVED** [review]
> Reviewed 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeKR6Tm9I4V7_U3kl2J:b-j007sz) (no related file):*
I think we've reached the limit of maintainable examples, we shouldn't add more. It sometimes takes a few hours to do a simple change because you need to fix and test 20 different examples afterwards.
So, if we think SQLite is worth of inclusion, then I'd remove curl and merge nodejs examples to make room for it.

@dimakuv, @boryspoplawski, @pwmarcz: Any thoughts?

---
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTLqW7O0GoO48wd8k:-MeKTLqW7O0GoO48wd8l:bd6bfvw) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/.ci/lib/stage-test-sgx.jenkinsfile#L133)):*
> ```
>     timeout(time: 5, unit: 'MINUTES') {
>         sh '''
>             # test SGX remote attestation only on Ubuntu 18.04 to keep internet requests to minimum
> ```

btw., @dimakuv: Unrelated to the PR, but I think this should be bumped to 20.04. Or maybe this problem is no longer present and we can test this everywhere?
___
*[Examples/sqlite/.gitignore, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTr0MA2or8ccU096L:-MeKTr0MA2or8ccU096M:bbhv9yz) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/.gitignore#L1)):*
> ```ignore
> OUTPUT
> ```

Should be `/OUTPUT`
___
*[Examples/sqlite/Makefile, line 36 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKUmTs-2INiU2jS1Ka:-MeKUmTs-2INiU2jS1Kb:bavf8uc) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/Makefile#L36)):*
> ```Makefile
> 
> # Generating the SGX-specific manifest (*.manifest.sgx), the enclave signature,
> # and the token for enclave initialization.
> ```

I'd drop this comment, other places are not commented like this + I don't like this copy-pasting from other examples, all of them diverge too quickly :)
___
*[Examples/sqlite/README.md, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKWt9H7ajn87BDXH64:-MeKWt9H7ajn87BDXH65:b-1t4vc0) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/README.md#L50)):*
> ```Markdown
> but only within a **single Graphene instance**. In other words, a multi-process
> Graphene application is OK, but multiple Graphene instances should not access
> the same database file concurrently.
> ```

I'm not sure if this is worth mentioning, this problem is only in test setups. In production setups you _have to_ mount this as protected (or in tmpfs), and you don't have such issues at all then. And I think this is what should be mentioned (that specifying the database as "allowed" is for testing only).

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeMjE8PCiAvaJ89e34e:bjjpm22) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we've reached the limit of maintainable examples, we shouldn't add more. It sometimes takes a few hours to do a simple change because you need to fix and test 20 different examples afterwards.
So, if we think SQLite is worth of inclusion, then I'd remove curl and merge nodejs examples to make room for it.

@dimakuv, @boryspoplawski, @pwmarcz: Any thoughts?
</blockquote></details>

I've never had any problems with examples, when changing in Graphene stuff. What changes other than manifest syntax/options affect examples?

---
___
*[Examples/sqlite/README.md, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKWt9H7ajn87BDXH64:-MeMk5vLB45QMLNkxH_p:b-t3x5qf) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/README.md#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if this is worth mentioning, this problem is only in test setups. In production setups you _have to_ mount this as protected (or in tmpfs), and you don't have such issues at all then. And I think this is what should be mentioned (that specifying the database as "allowed" is for testing only).
</blockquote></details>

I think this comment should stay, because people will be testing stuff with allowed files. But I also agree that we should mention that allowed files are for testing purposes only.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeOSsDe0a2XTVlTvVBK:b-n0sghv) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've never had any problems with examples, when changing in Graphene stuff. What changes other than manifest syntax/options affect examples?
</blockquote></details>

It's time to discuss this with everyone and agree on some sane policy. I would prefer the following:
- We have a minimal set of examples in this repo -- only those that are easy to download & build & check in our Jenkins CI.
- We have a set of all other (big-ish) examples in another repo -- it will be linked as a sub-module.
- All the rest of examples (which we don't consider important) are dumped in graphene-contrib repo.

Here is my take on our minimal set of examples:
1. Bash
2. Blender
3. Busybox
4. lighttpd
5. memcached
6. nginx
7. python (but with venv or something!)
8. ra-tls-mbedtls
9. ra-tls-secret-prov
10. redis
11. SQLite

(I don't mind dropping Bash from here)

The "extended" examples that go in a separate repo:
1. Apache (??? or drop it?)
2. Curl
3. GCC
4. nodejs
5. OpenVINO
6. PyTorch
7. R
8. TensorFlow-Lite

(The planned Java, TensorFlow, Google Go examples should also go into this "extended" repo.)

The examples to remove completely or to move to graphene-contrib:
1. Apache (???)
2. Capnproto
3. nodejs-express-server

---
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTLqW7O0GoO48wd8k:-MeOPsWG-nn0JSZ-IfiT:b-b36f0b) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/.ci/lib/stage-test-sgx.jenkinsfile#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

btw., @dimakuv: Unrelated to the PR, but I think this should be bumped to 20.04. Or maybe this problem is no longer present and we can test this everywhere?
</blockquote></details>

There was no real problem. `ra-tls-secret-prov` and `ra-tls-mbedtls` (above, you didn't mark it) examples simply use the EPID remote attestation, so they sent TLS requests to the Intel Attestation Service (IAS).

When implementing these CI tests, I simply saw no reason to test these minimalistic examples in both 16.04 and 18.04, and chose to add them only to 18.04. This has the additional benefit of sending only 2 requests to IAS instead of 4 on each CI trigger. (IAS, at least at that time, was known to throttle requests.)

So yes, if you want to, we can:
- Move these two examples from 18.04 to 20.04
- Add these two examples to 20.04 additionally

Whatever you prefer.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MePxPrgDk6ZT1kgyx-V:b-c38tc3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's time to discuss this with everyone and agree on some sane policy. I would prefer the following:
- We have a minimal set of examples in this repo -- only those that are easy to download & build & check in our Jenkins CI.
- We have a set of all other (big-ish) examples in another repo -- it will be linked as a sub-module.
- All the rest of examples (which we don't consider important) are dumped in graphene-contrib repo.

Here is my take on our minimal set of examples:
1. Bash
2. Blender
3. Busybox
4. lighttpd
5. memcached
6. nginx
7. python (but with venv or something!)
8. ra-tls-mbedtls
9. ra-tls-secret-prov
10. redis
11. SQLite

(I don't mind dropping Bash from here)

The "extended" examples that go in a separate repo:
1. Apache (??? or drop it?)
2. Curl
3. GCC
4. nodejs
5. OpenVINO
6. PyTorch
7. R
8. TensorFlow-Lite

(The planned Java, TensorFlow, Google Go examples should also go into this "extended" repo.)

The examples to remove completely or to move to graphene-contrib:
1. Apache (???)
2. Capnproto
3. nodejs-express-server
</blockquote></details>

I would keep only 1 of {Bash, Busybox} in the minimal set.
On the Apache topic: I would keep it at least until the actual release happens. If we get some feedback about need for sysv semaphores, then we can reimplement them and restore Apache example, otherwise I would say we can remove it.

---

**Review by mkow — COMMENTED** [review]
> Reviewed 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeSKlhfE9QY7pbh9Mn_:b-96r8rm) (no related file):*
> I've never had any problems with examples, when changing in Graphene stuff.

I think it just was usually me doing changes in these areas, that's why you've never had problems with this.

> What changes other than manifest syntax/options affect examples?

In theory only these, but in practice we e.g. often had copy-pasted bugs in their Makefiles.

> We have a minimal set of examples in this repo -- only those that are easy to download & build & check in our Jenkins CI.

+1

> We have a set of all other (big-ish) examples in another repo -- it will be linked as a sub-module.

No submodules please, they are unmaintainable. I'd just move such examples to graphene-contrib and update them every release.

> I would keep only 1 of {Bash, Busybox} in the minimal set.

+1, I'd leave Bash because it contains more black magic inside and happened to trigger bugs in Graphene in the past.

Also, I'd add Go to the examples tested in CI, as it exercises a lot of weird things related to signal handling.

---
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTLqW7O0GoO48wd8k:-MeSN7aP0X7geHDhjJAH:b-kjtem0) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/.ci/lib/stage-test-sgx.jenkinsfile#L133)):*
> IAS, at least at that time, was known to throttle requests

Is this still the case? If so, then we can just bump this to 20.04, if not then test on both Ubuntus.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeTfjD55ewWUWX8vTyd:bi189th) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I've never had any problems with examples, when changing in Graphene stuff.

I think it just was usually me doing changes in these areas, that's why you've never had problems with this.

> What changes other than manifest syntax/options affect examples?

In theory only these, but in practice we e.g. often had copy-pasted bugs in their Makefiles.

> We have a minimal set of examples in this repo -- only those that are easy to download & build & check in our Jenkins CI.

+1

> We have a set of all other (big-ish) examples in another repo -- it will be linked as a sub-module.

No submodules please, they are unmaintainable. I'd just move such examples to graphene-contrib and update them every release.

> I would keep only 1 of {Bash, Busybox} in the minimal set.

+1, I'd leave Bash because it contains more black magic inside and happened to trigger bugs in Graphene in the past.

Also, I'd add Go to the examples tested in CI, as it exercises a lot of weird things related to signal handling.
</blockquote></details>

The problems with Bash and Go is that they are not "download & build" kinds of examples. On the other hand, it is true that Bash and Go are quite helpful in debugging corner cases. And it also looks like both Bash and Go don't require any modifications to manifest files on different OS distros.

So yes, I'm also happy to keep Bash and Go in our curated Examples list.

But I would also keep Busybox. It's very helpful to e.g. peek inside Graphene FS. And much more lightweight to work with than Bash.

No submodules it is :)

---

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTLqW7O0GoO48wd8k:-MeTtkDt-N9fP5GeP-nK:b-nwy0r5) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/.ci/lib/stage-test-sgx.jenkinsfile#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> IAS, at least at that time, was known to throttle requests

Is this still the case? If so, then we can just bump this to 20.04, if not then test on both Ubuntus.
</blockquote></details>

Here you go: https://github.com/oscarlab/graphene/pull/2534

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTLqW7O0GoO48wd8k:-Me_ruQ28Nzx_c9ReKiE:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/.ci/lib/stage-test-sgx.jenkinsfile#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here you go: https://github.com/oscarlab/graphene/pull/2534
</blockquote></details>

Thanks!

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-MeeR6F47mBXvZfrDkAg:b-w1q59n) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The problems with Bash and Go is that they are not "download & build" kinds of examples. On the other hand, it is true that Bash and Go are quite helpful in debugging corner cases. And it also looks like both Bash and Go don't require any modifications to manifest files on different OS distros.

So yes, I'm also happy to keep Bash and Go in our curated Examples list.

But I would also keep Busybox. It's very helpful to e.g. peek inside Graphene FS. And much more lightweight to work with than Bash.

No submodules it is :)
</blockquote></details>

Used this discussion in this meta-issue on repo migration: https://github.com/oscarlab/graphene/issues/2558

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-Mez-RJO4eXJ_jr8811H:b749pto) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Used this discussion in this meta-issue on repo migration: https://github.com/oscarlab/graphene/issues/2558
</blockquote></details>

I think a large part of the problem is too much boilerplate. For instance, some Makefiles and manifests contain very detailed comments that look like they belong to Graphene documentation. Ideally, the boilerplate should be minimal, and most code/comments should be there only because they're needed for this one example.

I agree with keeping the examples in the same repo. They act as another layer as sanity checks for Graphene, and also we should improve the process of building them first: it will be even harder to keep a separate repo in sync.

No strong opinions about the set of examples, but as a developer, I use Busybox and Python often.

---
___
*[Examples/sqlite/.gitignore, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKTr0MA2or8ccU096L:-MeyxqmSCyyqdL-qH6XY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/.gitignore#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be `/OUTPUT`
</blockquote></details>

Done.
___
*[Examples/sqlite/Makefile, line 36 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKUmTs-2INiU2jS1Ka:-MeyxwZSC61rV4DKNLLT:b-zdc86q) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/Makefile#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop this comment, other places are not commented like this + I don't like this copy-pasting from other examples, all of them diverge too quickly :)
</blockquote></details>

OK, removed. But I copied this file from `bash` example :)
___
*[Examples/sqlite/README.md, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKWt9H7ajn87BDXH64:-Mez-CDKBfjmY2gta8CD:bvoqwds) ([raw file](https://github.com/oscarlab/graphene/blob/9c5e1f198f4be0d5c6144d32221ee3674abd8f98/Examples/sqlite/README.md#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this comment should stay, because people will be testing stuff with allowed files. But I also agree that we should mention that allowed files are for testing purposes only.
</blockquote></details>

I added a paragraph about this.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2493#-MeKR6Tm9I4V7_U3kl2I:-Mf0FaNK3ZJxdOWQ56gW:b-vzo4ot) (no related file):*
> I think a large part of the problem is too much boilerplate. For instance, some Makefiles and manifests contain very detailed comments that look like they belong to Graphene documentation. Ideally, the boilerplate should be minimal, and most code/comments should be there only because they're needed for this one example.

Yup, definitely this ^
But there's also some overhead we can't easily skip, which is per-example setup commands, configuration, building options, etc. Also, our examples don't even have a common interface currently (not all of them work with just `cd some-example && make check`).
And lastly, there's no single command to test them all, like we have with PAL/LibOS regression.

---

**Review by mkow — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2493)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
