### PR TITLE
LTP fixes

### PR DESCRIPTION
**Pull request by pwmarcz**
## Description of the changes 

This fixes some low-hanging fruit in LTP tests.

Fixes https://github.com/oscarlab/graphene/issues/1932.

## How to test this PR? 

The tests should still pass; the relevant LTP tests are unskipped.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLREHyXBIhr8nG3DqJC:-MLREHyXBIhr8nG3DqJD:bwcgfvi) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_sleep.c#L29)):*
> ```C
>         return -EFAULT;
> 
>     if (!(0 <= rqtp->tv_sec && 0 <= rqtp->tv_nsec && rqtp->tv_nsec < 1000000000L))
> ```

Nitpick, but I would prefer to reverse the condition in the first member:
`if (!(rqtp->tv_sec >= 0 && 0 <= rqtp->tv_nsec && rqtp->tv_nsec < 1000000000L))`
___
*[LibOS/shim/src/sys/shim_time.c, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLREVs53b7CZ6FXgqrT:-MLREVs53b7CZ6FXgqrU:b-ra0pc1) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_time.c#L81)):*
> ```C
> 
>     if (tp) {
>         if (test_user_memory(tp, sizeof(*tp), true))
> ```

Can we also add the comment about the last arg: `, /*write=*/true`
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLRFInJ9ZxMDkc6Xx4b:-MLRFInK33B2TLna91MH:bbjfqbk) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_wrappers.c#L24)):*
> ```C
>     for (int i = 0; i < vlen; i++) {
>         if (vec[i].iov_base) {
>             if (vec[i].iov_base + vec[i].iov_len < vec[i].iov_base)
> ```

Is this a check for int overflow? We should use `if (!access_ok(iov_base, iov_len))` here.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLRHAQk411niD8K5vyE:-MLRHAQk411niD8K5vyF:b-29f2m8) (no related file):*
What about fixing https://github.com/oscarlab/graphene/issues/1931? Is it too complicated for this PR?

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: 8 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLRHAQk411niD8K5vyE:-MLScrYA7deunMKLuOVq:b-6cumbq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about fixing https://github.com/oscarlab/graphene/issues/1931? Is it too complicated for this PR?
</blockquote></details>

I could update the length condition as described in the issue, but the test (`sendmmsg01`) still fails, and it looks like the underlying Linux syscall returns `EINVAL`, I haven't debugged exactly why yet. I want to investigate further, so I'd rather leave it out of this PR.

---
___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLREHyXBIhr8nG3DqJC:-MLSb35FDocvUnIGRlmT:b-b9poqk) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_sleep.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nitpick, but I would prefer to reverse the condition in the first member:
`if (!(rqtp->tv_sec >= 0 && 0 <= rqtp->tv_nsec && rqtp->tv_nsec < 1000000000L))`
</blockquote></details>

Makes sense. I like `lower <= x && x < upper` style range comparisons, but the first condition is not a part of a range. Updated.
___
*[LibOS/shim/src/sys/shim_time.c, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLREVs53b7CZ6FXgqrT:-MLSbOXJ086CCBh-VwJp:bm14u3x) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_time.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we also add the comment about the last arg: `, /*write=*/true`
</blockquote></details>

OK. Added in all `test_user_memory` invocations in this file.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLRFInJ9ZxMDkc6Xx4b:-MLScVOd9tLHGydmvClh:bmaos43) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_wrappers.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a check for int overflow? We should use `if (!access_ok(iov_base, iov_len))` here.
</blockquote></details>

Yes, looks like it. I used `access_ok` here and in the `writev` function as well.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_fcntl.c, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLSqxBX9kYjXww13C4-:-MLSqxBX9kYjXww13C40:b-re3hfb) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_fcntl.c#L64)):*
> ```C
>                 vfd++;
> 
>             ret = set_new_fd_handle_by_fd(vfd, hdl, flags, handle_map);
> ```

The new version looks racy - what if that fd was allocated in the meantime?
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLSrHy30DnzGMEyeIY4:-MLSrHy30DnzGMEyeIY5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_fcntl.c#L83)):*
> ```C
>                 vfd++;
> 
>             ret = set_new_fd_handle_by_fd(vfd, hdl, flags, handle_map);
> ```

ditto
___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLREHyXBIhr8nG3DqJC:-MLSrvWHB9_51QMBuedB:b-vdqokb) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_sleep.c#L29)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Makes sense. I like `lower <= x && x < upper` style range comparisons, but the first condition is not a part of a range. Updated.
</blockquote></details>

+1, I also like this style of range comparison :)
___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLStFdn88wss2xxIGyq:-MLStFdn88wss2xxIGyr:bk21j4t) ([raw file](https://github.com/oscarlab/graphene/blob/1909567842e33394ef5287f9fdf75c5c323da529/LibOS/shim/src/sys/shim_sleep.c#L29)):*
> ```C
>         return -EFAULT;
> 
>     if (!(rqtp->tv_sec >= 0 && 0 <= rqtp->tv_nsec && rqtp->tv_nsec < 1000000000L))
> ```

Linux slightly differs here: it has a cast `(unsigned long)ts->tv_nsec >= NSEC_PER_SEC` (for some unknown reason `tv_nsec` is signed).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: 9 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_fcntl.c, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLSqxBX9kYjXww13C4-:-MLT9uQ61MwpcdC487IJ:bldjhfs) ([raw file](https://github.com/oscarlab/graphene/blob/3bad0d871a9b3b5fe17d1fc9ef5793dfda996c0f/LibOS/shim/src/sys/shim_fcntl.c#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The new version looks racy - what if that fd was allocated in the meantime?
</blockquote></details>

Okay, right, that needs to happen under a lock.

I refactored the `set_new_fd_handle*` functions, there was quite a bit of duplication between them, so hopefully the situation is improved now.
___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLStFdn88wss2xxIGyq:-MLTAxXo83IwfUTr1xcK:b-m3qkks) ([raw file](https://github.com/oscarlab/graphene/blob/1909567842e33394ef5287f9fdf75c5c323da529/LibOS/shim/src/sys/shim_sleep.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Linux slightly differs here: it has a cast `(unsigned long)ts->tv_nsec >= NSEC_PER_SEC` (for some unknown reason `tv_nsec` is signed).
</blockquote></details>

Do you think that's better though? Seems a bit too clever, and I just checked that it compiles the same.

As for `NSEC_PER_SEC`... I played with it a bit, but this code also deals with milliseconds, so we would need `MSEC_PER_SEC` and so on. Until this is only a single function, I don't think it will make the code more readable.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`sigsuspend01` LTP test failed)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`truncate02` LTP test failed)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_sleep.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1945#-MLStFdn88wss2xxIGyq:-MLhOBj78F_F19WfZRoS:bbx6sr2) ([raw file](https://github.com/oscarlab/graphene/blob/1909567842e33394ef5287f9fdf75c5c323da529/LibOS/shim/src/sys/shim_sleep.c#L29)):*
> Do you think that's better though? Seems a bit too clever, and I just checked that it compiles the same.

Ah, sorry, I misread your code, it's correct and checking the same thing as the kernel.

a.d. `NSEC_PER_SEC` - no need for this, I was only talking about the cast :)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`select04` LTP test failed)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 2 files at r7, 1 of 2 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 2 files at r7, 1 of 2 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1945)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
