### PR TITLE
[LibOS] Add dummy lseek emulation for /dev/{zero,random,null}

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Some apps (e.g., Python Dill module) perform a dummy `lseek()` on these `/dev/` files.

## How to test this PR? 

Added more sub-tests in `dev` LibOS regression test.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/dev/null.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyosWh54RNh5GjPlyX:-MRyosWh54RNh5GjPlyY:bvdh698) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/null.c#L27)):*
> ```C
> }
> 
> static off_t dev_null_seek(struct shim_handle* hdl, off_t offset, int wence) {
> ```

`wence` -> `whence`
___
*[LibOS/shim/src/fs/dev/random.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyouZz7rHt6nDhFCaz:-MRyouZz7rHt6nDhFCb-:bvdh698) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/random.c#L30)):*
> ```C
> }
> 
> static off_t dev_random_seek(struct shim_handle* hdl, off_t offset, int wence) {
> ```

`wence` -> `whence`
___
*[LibOS/shim/src/fs/dev/zero.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyoy-b5orb7sYGCtvU:-MRyoy-b5orb7sYGCtvV:bvdh698) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/zero.c#L26)):*
> ```C
> }
> 
> static off_t dev_zero_seek(struct shim_handle* hdl, off_t offset, int wence) {
> ```

`wence` -> `whence`
___
*[LibOS/shim/test/regression/dev.c, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyprJbBdI43eSTKudw:-MRyprJbBdI43eSTKudx:b-py0wms) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L7)):*
> ```C
> #include <string.h>
> #include <unistd.h>
> ```

Unrelated to the PR, but why is this test listing my whole _host_ `/dev` under `===== Contents of /dev`? I don't see `/dev` being mounted to the host in the manifest...
___
*[LibOS/shim/test/regression/dev.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRypbko0B6-q8DRBNvf:-MRypbko0B6-q8DRBNvg:bvs6vtx) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L76)):*
> ```C
>     }
> 
>     printf("Four bytes from /dev/urandom: %x:%x:%x:%x\n", buf[0], buf[1], buf[2], buf[3]);
> ```

While we're here, could you fix the `char` -> `unsigned` conversion bug?

```
Four bytes from /dev/urandom: ffffff9b:ffffffa1:68:ffffffd9
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: 1 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/dev/null.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyosWh54RNh5GjPlyX:-MRyrz8s3MHfA04xC9fA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/null.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`wence` -> `whence`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/dev/random.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyouZz7rHt6nDhFCaz:-MRyrzmZ8lFViXRyGxEi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/random.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`wence` -> `whence`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/dev/zero.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyoy-b5orb7sYGCtvU:-MRys-Lv03PogLxjaqnU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/zero.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`wence` -> `whence`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/dev.c, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyprJbBdI43eSTKudw:-MRys4fP7KTkhoJw7iAr:b-tyapwk) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unrelated to the PR, but why is this test listing my whole _host_ `/dev` under `===== Contents of /dev`? I don't see `/dev` being mounted to the host in the manifest...
</blockquote></details>

What do you mean, your *host /dev*? Under Graphene, it correctly shows only the LibOS-emulated devices:
```
dimakuv@mehlow-prequal01:~/dev-graphene/LibOS/shim/test/regression$ ./pal_loader ./dev
WARNING: Using insecure argv source. Don't use this configuration in production!
===== Contents of /dev
/dev/.
/dev/null
/dev/zero
/dev/random
/dev/urandom
/dev/stdin
/dev/stdout
/dev/stderr
/dev/attestation
===== Read from /dev/urandom
Four bytes from /dev/urandom: ffffff8d:60:5a:18
===== Write to /dev/null
TEST OK!
```

If you run `./dev`, then of course it prints the host devices (since you're not running under Graphene). What am I misunderstanding?
___
*[LibOS/shim/test/regression/dev.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRypbko0B6-q8DRBNvf:-MRytLIF3haA1avezjHq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, could you fix the `char` -> `unsigned` conversion bug?

```
Four bytes from /dev/urandom: ffffff9b:ffffffa1:68:ffffffd9
```
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/dev/null.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyosWh54RNh5GjPlyX:-MRyvilD1uAmT1mtGpXq:b9ozhml) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/null.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Seems this typo is widespread in our repo, but we can fix it in a separate PR (or here, whichever you prefer).
___
*[LibOS/shim/test/regression/dev.c, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyprJbBdI43eSTKudw:-MRyvvZn7FCrwPnKe3Od:b-lrym9j) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean, your *host /dev*? Under Graphene, it correctly shows only the LibOS-emulated devices:
```
dimakuv@mehlow-prequal01:~/dev-graphene/LibOS/shim/test/regression$ ./pal_loader ./dev
WARNING: Using insecure argv source. Don't use this configuration in production!
===== Contents of /dev
/dev/.
/dev/null
/dev/zero
/dev/random
/dev/urandom
/dev/stdin
/dev/stdout
/dev/stderr
/dev/attestation
===== Read from /dev/urandom
Four bytes from /dev/urandom: ffffff8d:60:5a:18
===== Write to /dev/null
TEST OK!
```

If you run `./dev`, then of course it prints the host devices (since you're not running under Graphene). What am I misunderstanding?
</blockquote></details>

:facepalm:
I was running both and looked and the from log, sorry :)
___
*[LibOS/shim/test/regression/dev.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRypbko0B6-q8DRBNvf:-MRyw9KW3p0yn5JwV5VI:b-isxz57) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

kinda nitpicky, but could you drop the trailing space from the printf above and shift it to a leading one in the loop? we wouldn't print a trailing space this way ;)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/dev/null.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRyosWh54RNh5GjPlyX:-MRyxhSq9FtHY_OmGUdz:b2pognx) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/src/fs/dev/null.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems this typo is widespread in our repo, but we can fix it in a separate PR (or here, whichever you prefer).
</blockquote></details>

Yes, this typo is in a few places in Graphene.
___
*[LibOS/shim/test/regression/dev.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2122#-MRypbko0B6-q8DRBNvf:-MRyy4xS8A4VT131bDvz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3e98350417f0884c3ed303f38ed6653320a9f51e/LibOS/shim/test/regression/dev.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

kinda nitpicky, but could you drop the trailing space from the printf above and shift it to a leading one in the loop? we wouldn't print a trailing space this way ;)
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2122)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please; `semop01` LTP test failed with an interesting log:
```
returncode=2

ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:72: TINFO: Testing variant: semop: syscall
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:59: TPASS: semaphore values are correct
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:59: TPASS: semaphore values are correct
ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:72: TINFO: Testing variant: semtimedop: syscall with old kernel spec
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:59: TPASS: semaphore values are correct
ltp/src/testcases/kernel/syscalls/ipc/semop/semop01.c:59: TPASS: semaphore values are correct
ltp/src/lib/tst_test.c:1295: TINFO: If you are running on slow machine, try exporting LTP_TIMEOUT_MUL > 1
ltp/src/lib/tst_test.c:1296: TBROK: Test killed! (timeout?)
```

Looks like a timeout issue (and/or slow machine).

**Pull request merged**
