### PR TITLE
Fix Bash scripts and remove unused ones

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

I got annoyed by the warning spam in our CI logs from `shellcheck`, now they're clean :) I also removed some unused/redundant scripts (instead of fixing them), I don't think anyone used them in the past 5 years.

## How to test this PR? 

CI should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (Apache example failed with `apr_socket_recv: Connection refused (111)`, can't reproduce locally, probably caused by a random lag which caused the server to not be ready on time)

**Review by yamahata — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[.ci/prfilter, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHT-ks2xY17j2TKj4B:-MHHT-kt4toGRu4-Llfk:b-jn7zjg) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/.ci/prfilter#L41)):*
> ```
>     'Tools',
> 
>     # for shellcheck - currently empty, yay! :)
> ```

If so, go to Jenkinsfiles and remove the double invocation of shellcheck.
It should just say `./.ci/run-shellcheck`, not `|| :` and remove the second line with `prfilter`.
___
*[Examples/bash/scripts/bash_test.sh, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHSeXw9thubeibX_-L:-MHHSeXw9thubeibX_-M:b-z3l3ow) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/Examples/bash/scripts/bash_test.sh#L4)):*
> ```Shell
> 
> times=$1
> [ "$times" -gt 0 ] 2>/dev/null || times=300
> ```

I'd prefer `test "$times" -gt 0 2>/dev/null || ...`, because `[` command is confusing for many people.
___
*[Pal/src/host/Linux-SGX/debugger/gdb, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHSYyj0K0GAqZswhIr:-MHHSYyn9nO5DpIUKpGN:b-gsrty7) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/Pal/src/host/Linux-SGX/debugger/gdb#L1)):*
> ```
> #!/bin/bash
> ```

While we're at it, `#!/usr/bin/env bash`

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: 12 of 23 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju and @yamahata)

___
*[.ci/prfilter, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHT-ks2xY17j2TKj4B:-MHHkes_0h_PyFOJA2sz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/.ci/prfilter#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If so, go to Jenkinsfiles and remove the double invocation of shellcheck.
It should just say `./.ci/run-shellcheck`, not `|| :` and remove the second line with `prfilter`.
</blockquote></details>

Done.
___
*[Examples/bash/scripts/bash_test.sh, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHSeXw9thubeibX_-L:-MHHkgEK8rybyVvfos4Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/Examples/bash/scripts/bash_test.sh#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd prefer `test "$times" -gt 0 2>/dev/null || ...`, because `[` command is confusing for many people.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/debugger/gdb, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHSYyj0K0GAqZswhIr:-MHHkhi9Bf_nEPWDslYb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/Pal/src/host/Linux-SGX/debugger/gdb#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

While we're at it, `#!/usr/bin/env bash`
</blockquote></details>

Done.

**Review by woju — DISMISSED** [review]
> Reviewed 2 of 14 files at r1, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: 22 of 23 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[Examples/bash/scripts/bash_test.sh, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/1811#-MHHSeXw9thubeibX_-L:-MHHmcpMAUiWMjbisT6e:buwnz0r) ([raw file](https://github.com/oscarlab/graphene/blob/307e9fb1fbd5773f1d442c42964c455cf818c567/Examples/bash/scripts/bash_test.sh#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reverted back to `[`, shellcheck didn't like mixing `test` and `2>/dev/null`.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (`apps.LTP.fdatasync01` timed out, known issue)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 10 of 11 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1811)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
