### PR TITLE
[Docs] Correct a path to libsecret_prov_attest.so in pytorch tutorial

### PR DESCRIPTION
**Pull request by RodgerZhu**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2455)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2455)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2455#-McO3wXg8DHBooxWdKL_:-McO3wXh0iMbuOYP2sUR:beboguk) (no related file):*
I'll fix the commit message (remove `index.rst`) during rebase.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2455)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @RodgerZhu)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2455)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2455#-McO3wXg8DHBooxWdKL_:-MdIsAO-80U2p4HkKmtT:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll fix the commit message (remove `index.rst`) during rebase.
</blockquote></details>

Done.

---

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2455)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
