### PR TITLE
[Docs] Update the main readme

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Kudos for @monavij and @donporter for refreshing the text!

## How to test this PR? 

Use GitHub's rich diff to check if it renders correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)

### CODE REVIEW

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[README.rst, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2300#-MXlSen81-v86ctLBozj:-MXlSen81-v86ctLBozk:bt8taub) ([raw file](https://github.com/oscarlab/graphene/blob/4af9afc03a4c5bf24193c94d9a7844071efea7ed/README.rst#L28)):*
> ```reStructuredText
> different OSes, and process migration.
> 
> Graphene supports native, unmodified Linux applications binaries on any
> ```

"applications binaries" -> "application binaries"? Or just "binaries"?
___
*[README.rst, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2300#-MXlU-ZiAJmWN40X0HnZ:-MXlU-ZiAJmWN40X0Hn_:bdxcbj6) ([raw file](https://github.com/oscarlab/graphene/blob/4af9afc03a4c5bf24193c94d9a7844071efea7ed/README.rst#L60)):*
> ```reStructuredText
> 
> Graphene is ready to be deployed in cloud environments with full support for
> automatic container integration.
> ```

Maybe mention GSC by name in this sentence? There is a link below, but this would make it more obvious what you're referring to.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[README.rst, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2300#-MXlSen81-v86ctLBozj:-MXmeMOe5GoZKEqQekUB:bdthx1b) ([raw file](https://github.com/oscarlab/graphene/blob/4af9afc03a4c5bf24193c94d9a7844071efea7ed/README.rst#L28)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

"applications binaries" -> "application binaries"? Or just "binaries"?
</blockquote></details>

I like the shortened "binaries", done.
___
*[README.rst, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2300#-MXlU-ZiAJmWN40X0HnZ:-MXmeaW95cxB0zMuA5tn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4af9afc03a4c5bf24193c94d9a7844071efea7ed/README.rst#L60)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe mention GSC by name in this sentence? There is a link below, but this would make it more obvious what you're referring to.
</blockquote></details>

Done.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[README.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2300#-MY4OkbuAGScYvGXtP9H:-MY4OkbuAGScYvGXtP9I:bpg0phb) ([raw file](https://github.com/oscarlab/graphene/blob/953bd07fc286d31d9c89ed9994670ae3a902ca7b/README.rst#L84)):*
> ```reStructuredText
> - `The Graphene Shielded Containers (GSC) tool
>   <https://graphene.readthedocs.io/en/latest/manpages/gsc.html>`__
> - `Performance tuning & analysis of applications in Graphene-SGX
> ```

We don't really use `Graphene-SGX` anymore. I think the better wording is `Performance tuning & analysis of SGX applications in Graphene`.

Also, I would move this entry to be the very last one, because this is the only one that depends on Intel SGX (even "remote attestation" section can be applicable to non-SGX variants).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[README.rst, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2300#-MY4P9-Z42WpYxc3EP9V:-MY4P9-Z42WpYxc3EP9W:b-gpwm06) ([raw file](https://github.com/oscarlab/graphene/blob/953bd07fc286d31d9c89ed9994670ae3a902ca7b/README.rst#L59)):*
> ```reStructuredText
> 
> Graphene is ready to be deployed in cloud environments with full support for
> automatic container integration, using Graphene Shielded Containers.
> ```

I would add `...Containers (GSC)` -- we almost always just say GSC instead of the long name, so makes sense to introduce the abbreviation here.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[README.rst, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2300#-MY4P9-Z42WpYxc3EP9V:-MY52N8XBgQiu7GGk8n2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/953bd07fc286d31d9c89ed9994670ae3a902ca7b/README.rst#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add `...Containers (GSC)` -- we almost always just say GSC instead of the long name, so makes sense to introduce the abbreviation here.
</blockquote></details>

Done.
___
*[README.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2300#-MY4OkbuAGScYvGXtP9H:-MY52VT1EAABD8_ZAnXo:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/953bd07fc286d31d9c89ed9994670ae3a902ca7b/README.rst#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't really use `Graphene-SGX` anymore. I think the better wording is `Performance tuning & analysis of SGX applications in Graphene`.

Also, I would move this entry to be the very last one, because this is the only one that depends on Intel SGX (even "remote attestation" section can be applicable to non-SGX variants).
</blockquote></details>

Right. Fixed.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2300)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
