### PR TITLE
[Pal/Linux-SGX] Trivial fixes

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Bug fix

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1037)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by jiazhang0** [comment]
I see all tests are passed so I run a force-push for final review.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
