### PR TITLE
[Pal/regression] Move `Pal/crt_init` dir under `Pal/regression`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The `crt_init` directory contains the `user_start.S` file which is needed only for PAL regression tests (they use the default linker script which expects the `_start` symbol, but PAL regression tests only have `main` so `user_start.S` serves as the glue code). Move this dir under `Pal/regression` to de-clutter our directory hierarchy.

NOTE: I was actually moving `Pal/lib` out of `Pal` (since it is the "common helper library" for both LibOS and PAL), but as a side job decided to also move this one.

## How to test this PR? 

PAL regression tests must still succeed.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2352#-MZwjVarCcz9XX7Pe-EF:-MZwjVas2MZyLQMhclFR:b-dxo00x) (no related file):*
@yamahata Could you take a look at this simple PR? You touched this last.

@woju Not sure if this plays into your Meson work. Please take a look.

---

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by woju** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2352#-MZwjVarCcz9XX7Pe-EF:-MZxGDoC5nn4MhRuL8zN:b-y6e1q7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@yamahata Could you take a look at this simple PR? You touched this last.

@woju Not sure if this plays into your Meson work. Please take a look.
</blockquote></details>

Thanks for notification. I haven't touched this one yet, I have no idea. Will keep in mind.

---

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @yamahata)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @yamahata)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2352)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)

**Pull request merged**
