### PR TITLE
More clang fixes

### PR DESCRIPTION
**Pull request by pwmarcz**
See #1794.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)

### CODE REVIEW

**Review by yamahata — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/Makefile.am, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGiM8YvCg5V1kUEC6lA:-MGiM8YwC2IHv-1A_sl7:baod46u) ([raw file](https://github.com/oscarlab/graphene/blob/cb14379e1d341a3ca519187edd52070837587594/Pal/src/host/Linux-SGX/Makefile.am#L8)):*
> ```Makefile
> CFLAGS += -Wextra $(call cc-option,-Wnull-dereference)
> 
> ifeq ($(CC),gcc)
> ```

this is duplicatedas the aboce does cc-option

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/Makefile.am, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGiM8YvCg5V1kUEC6lA:-MGlw95a-cq6BmxlUkD_:bag6chw) ([raw file](https://github.com/oscarlab/graphene/blob/cb14379e1d341a3ca519187edd52070837587594/Pal/src/host/Linux-SGX/Makefile.am#L8)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

this is duplicatedas the aboce does cc-option
</blockquote></details>

A leftover from previous version. Removed.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

**Review by yamahata — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 5 files at r7, 1 of 1 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGo-82ICTV4DNLUackj:-MGo-82ICTV4DNLUackk:b9l2k38) (no related file):*
FYI: Building on SGX was failing:
```
In file included from db_process.c:22:0:
db_process.c: In function 'generate_sign_data':
../../../include/lib/assert.h:14:23: error: static assertion failed: "`array` must be a char array"
 #define static_assert _Static_assert
                       ^
pal_linux.h:331:42: note: in definition of macro 'SGX_DBG'
     do { if ((class) & DBG_LEVEL) printf(fmt); } while (0)
                                          ^
../../../include/lib/hex.h:55:5: note: in expansion of macro 'static_assert'
     static_assert(IS_CHAR_ARRAY(array), "`array` must be a char array"); \
     ^
../../../include/lib/hex.h:64:6: note: in expansion of macro 'BYTES2HEXSTR'
     (BYTES2HEXSTR(array, __alloca(sizeof(array) * 2 + 1), sizeof(array) * 2 + 1))
      ^
db_process.c:189:13: note: in expansion of macro 'ALLOCA_BYTES2HEXSTR'
             ALLOCA_BYTES2HEXSTR(data.eid_mac));
             ^
```

Seems this trick has problems with uint8_t arrays which is used here: https://github.com/oscarlab/graphene/blob/e854488d077b7963a0129f9a6010fc6f3b5bae59/Pal/src/host/Linux-SGX/db_process.c#L189

I fixed this, let's run Jenkins now.

---

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGo-82ICTV4DNLUackj:-MGoAaOGEecsTm1QWajs:bbucfay) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: Building on SGX was failing:
```
In file included from db_process.c:22:0:
db_process.c: In function 'generate_sign_data':
../../../include/lib/assert.h:14:23: error: static assertion failed: "`array` must be a char array"
 #define static_assert _Static_assert
                       ^
pal_linux.h:331:42: note: in definition of macro 'SGX_DBG'
     do { if ((class) & DBG_LEVEL) printf(fmt); } while (0)
                                          ^
../../../include/lib/hex.h:55:5: note: in expansion of macro 'static_assert'
     static_assert(IS_CHAR_ARRAY(array), "`array` must be a char array"); \
     ^
../../../include/lib/hex.h:64:6: note: in expansion of macro 'BYTES2HEXSTR'
     (BYTES2HEXSTR(array, __alloca(sizeof(array) * 2 + 1), sizeof(array) * 2 + 1))
      ^
db_process.c:189:13: note: in expansion of macro 'ALLOCA_BYTES2HEXSTR'
             ALLOCA_BYTES2HEXSTR(data.eid_mac));
             ^
```

Seems this trick has problems with uint8_t arrays which is used here: https://github.com/oscarlab/graphene/blob/e854488d077b7963a0129f9a6010fc6f3b5bae59/Pal/src/host/Linux-SGX/db_process.c#L189

I fixed this, let's run Jenkins now.
</blockquote></details>

Seems there are more issues:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 12, in <module>
    from pal_sgx_sign import main # pylint: disable=import-error,wrong-import-position
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 13, in <module>
    import generated_offsets as offs # pylint: disable=import-error,wrong-import-position
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/generated_offsets.py", line 3
    SGX_FLAGS_DEBUG = $2
                      ^
SyntaxError: invalid syntax
```

Please take a look ;)

---

**Review by yamahata — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Scripts/Makefile.rules, line 73 at r9](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGoNNAc9FP1JYa8Y1zJ:-MGoNNAc9FP1JYa8Y1zK:b-v35mvw) ([raw file](https://github.com/oscarlab/graphene/blob/9b4877c4052a8c76e63474d8c3f6d88fee2aa44e/Scripts/Makefile.rules#L73)):*
> ```
> 	 echo "\# DO NOT MODIFY. THIS FILE WAS AUTO-GENERATED."; \
> 	 echo ""; \
> 	 awk '/\.ascii "GENERATED_INTEGER/{print $$3 " = " $$4}' $^) > $@
> ```

This line also needs fix.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGo-82ICTV4DNLUackj:-MGs1pteCG1InWQpwwc6:b-bonl8r) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems there are more issues:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 12, in <module>
    from pal_sgx_sign import main # pylint: disable=import-error,wrong-import-position
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 13, in <module>
    import generated_offsets as offs # pylint: disable=import-error,wrong-import-position
  File "/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX/generated_offsets.py", line 3
    SGX_FLAGS_DEBUG = $2
                      ^
SyntaxError: invalid syntax
```

Please take a look ;)
</blockquote></details>

This should work now, see below.

---
___
*[Pal/src/host/Linux-SGX/Makefile.am, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGiM8YvCg5V1kUEC6lA:-MGlxHQl9zhTndec3mVr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb14379e1d341a3ca519187edd52070837587594/Pal/src/host/Linux-SGX/Makefile.am#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

A leftover from previous version. Removed.
</blockquote></details>

Done.
___
*[Scripts/Makefile.rules, line 73 at r9](https://reviewable.io/reviews/oscarlab/graphene/1801#-MGoNNAc9FP1JYa8Y1zJ:-MGs1Jeo6UwuBeppDuc0:b-n6g8nl) ([raw file](https://github.com/oscarlab/graphene/blob/9b4877c4052a8c76e63474d8c3f6d88fee2aa44e/Scripts/Makefile.rules#L73)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

This line also needs fix.
</blockquote></details>

Right. That would also explain the failure @mkow mentioned. Fixed.

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by yamahata — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1801)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
