### PR TITLE
[LibOS] Remove types from syscalls debug printing

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See the commit messages.
This is split from #2071 

## How to test this PR? 
Run some apps with `debug = inline` in manifest

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: 0 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_internal.h, line 123 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsqW_4AXws1tdHtSNe:-MQsqW_4AXws1tdHtSNf:b-bq47ay) ([raw file](https://github.com/oscarlab/graphene/blob/a3968920606734717f85024e0819863d5cfad009/LibOS/shim/include/shim_internal.h#L123)):*
> ```objc
>     r func(PROTO_ARGS_##n(args));
> 
> #define PARSE_SYSCALL1(name, ...) \
> ```

Do not get used to changes in this file, I'm removing all these macros in a follow up PR
___
*[LibOS/shim/src/shim_parser.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsqdz2CNHwTr1wfOYx:-MQsqdz2CNHwTr1wfOYy:bjuk0cb) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L70)):*
> ```C
>     void (*parser[7])(va_list*);
> } syscall_parser_table[LIBOS_SYSCALL_BOUND] = {
>     [__NR_read]     = {.slow = 1, .name = "read", .parser = {&parse_long_arg, &parse_integer_arg, &parse_pointer_arg, &parse_pointer_arg}},
> ```

I'll fix alignment once this solution is accepted as mergable.
___
*[LibOS/shim/src/shim_parser.c, line 1352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsrgc64u0fCVPyxrrS:-MQsrgc64u0fCVPyxrrT:b8jpsuv) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L1352)):*
> ```C
> }
> 
> static void parse_long_arg(va_list* ap) {
> ```

Note that this parser is kinda heuristics, but it's only used to print signed arguments (e.g. `long`). Unsigned types are always printed as hexadecimal using `parse_pointer_arg` (if they are `unsigned long` or `size_t`) or `parse_integer_arg` (only `unsigned int`).
I personally found this combination most useful when debugging, let me know what you think.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt2LQ653WY3og2GQ9-:-MQt2LQ653WY3og2GQ90:b-dipu0u) (no related file):*
> Fixes places missed by commit a3968920606734717f85024e0819863d5cfad009

Please use the commit oneliner instead of the hash, we'll be dropping these 600MB from the history someday and the hashes will change.

---
___
*[LibOS/shim/src/shim_parser.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt5_Jn3RB9QJGA168Y:-MQt5_Jn3RB9QJGA168Z:b-wbiizo) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L66)):*
> ```C
> 
> struct parser_table {
>     int slow;
> ```

While we're here, could you change this to `bool`, entries to `true`/`false` and add a comment what's the meaning of this field?
___
*[LibOS/shim/src/shim_parser.c, line 1344 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt6wL16tYO6fET_uBi:-MQt6wL16tYO6fET_uBj:bufvc91) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1344)):*
> ```C
>     } else {
>         /* invalid memory region, print arg as ptr not string */
>         PRINTF("\"(invalid-addr %p)\"", arg);
> ```

maybe without `"`? wouldn't look like a user string containing such text
___
*[LibOS/shim/src/shim_parser.c, line 1355 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt7Cx65kttQeN5O-EG:-MQt7Cx65kttQeN5O-EH:br235o7) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1355)):*
> ```C
>     long x = va_arg(*ap, long);
>     if (x >= 0) {
>         PRINTF("0x%lx", x);
> ```

please cast to `unsigned long`, otherwise will throw a warning if we add proper argument checks to `PRINTF` (using GCC "format" attributes)
___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQtCNHU8DaGZY4u88CA:b-wtzn2u) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
> ```C
>     }
> 
>     PUTS(") ...");
> ```

Could you drop the space before "..."? Looks ugly in the log.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: 4 of 5 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt2LQ653WY3og2GQ9-:-MQtWmM31DDqJK4QT7nT:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Fixes places missed by commit a3968920606734717f85024e0819863d5cfad009

Please use the commit oneliner instead of the hash, we'll be dropping these 600MB from the history someday and the hashes will change.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/shim_parser.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsqdz2CNHwTr1wfOYx:-MQtYh4EBnPH8JY5B6gh:b-4jnc7u) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll fix alignment once this solution is accepted as mergable.
</blockquote></details>

Btw, this table was auto-generated.
___
*[LibOS/shim/src/shim_parser.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt5_Jn3RB9QJGA168Y:-MQtYgMpEePmOg2VOhTl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, could you change this to `bool`, entries to `true`/`false` and add a comment what's the meaning of this field?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_parser.c, line 1344 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt6wL16tYO6fET_uBi:-MQtYuMf2yVArTRQP1cc:b2931e1) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1344)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

maybe without `"`? wouldn't look like a user string containing such text
</blockquote></details>

Done. (tho I did not introduce this function)
___
*[LibOS/shim/src/shim_parser.c, line 1355 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt7Cx65kttQeN5O-EG:-MQtZQe1Cmo-ddz1yZEg:b-sfk41t) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1355)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please cast to `unsigned long`, otherwise will throw a warning if we add proper argument checks to `PRINTF` (using GCC "format" attributes)
</blockquote></details>

No it would not, it doesn't warn about signedness, only about sizes and pointers.
Done, as it's good change anyway.
___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQtZRxT685w2EOtk-EF:b9q8z52) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you drop the space before "..."? Looks ugly in the log.
</blockquote></details>

Imo it looks better with the space

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_parser.c, line 1352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsrgc64u0fCVPyxrrS:-MQt6VlZ-nQb36-_5FTR:bb6ywmx) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L1352)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Note that this parser is kinda heuristics, but it's only used to print signed arguments (e.g. `long`). Unsigned types are always printed as hexadecimal using `parse_pointer_arg` (if they are `unsigned long` or `size_t`) or `parse_integer_arg` (only `unsigned int`).
I personally found this combination most useful when debugging, let me know what you think.
</blockquote></details>

LGTM
___
*[LibOS/shim/src/shim_parser.c, line 1355 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQt7Cx65kttQeN5O-EG:-MQtarjoDkTwULU6b97k:b9a5a3e) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1355)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No it would not, it doesn't warn about signedness, only about sizes and pointers.
Done, as it's good change anyway.
</blockquote></details>

Interesting, I always thought that it also checks the signedness.
___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQtaxKR5NxJcZLIzy_S:bv7cmf) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo it looks better with the space
</blockquote></details>

But you don't put a space before punctuation, even if the last word is a function description (i.e., it it was a single period then you wouldn't write `Some sentence with some_func(asdf) .`).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_parser.c, line 1352 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsrgc64u0fCVPyxrrS:-MQurfen1-FmR699_kOZ:b-hfghm4) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L1352)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Sounds good
___
*[LibOS/shim/src/shim_parser.c, line 100 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutv-uEkKmnYnwzq6O:-MQutv-uEkKmnYnwzq6P:b5hud3b) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L100)):*
> ```C
>     [__NR_select]         = {.slow = true, .name = "select", .parser = {&parse_long_arg, &parse_integer_arg, &parse_pointer_arg, &parse_pointer_arg, &parse_pointer_arg, &parse_pointer_arg}},
>     [__NR_sched_yield] = {.slow = false, .name = "sched_yield", .parser = {&parse_long_arg}},
>     [__NR_mremap]      = {.slow = false, .name = "mremap", .parser = {NULL}},
> ```

What is the logic here (and below in all such cases)? Why not have the parsers?
___
*[LibOS/shim/src/shim_parser.c, line 1433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQustp-2YXZFHsH39Vu:-MQustp-2YXZFHsH39Vv:b-4szoaq) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L1433)):*
> ```C
>     va_arg(ap, long);
> 
>     int i = 0;
> ```

This line is not needed, please move this into the for loop
___
*[LibOS/shim/src/shim_parser.c, line 1460 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutRVcBl6cWOP2mIgX:-MQutRVcBl6cWOP2mIgY:b-5vf8vz) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L1460)):*
> ```C
>         PUTS(" = ");
>         /* Return value is passed as the first argument, restart the list. */
>         va_start(ap, sysno);
> ```

Why do you need to skip the first argument above and restart the list here? Why not memorize that `long retval = va_arg(ap, long);` above and use it here?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/shim_parser.c, line 100 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutv-uEkKmnYnwzq6O:-MQvnRPx6nFGg0mZBe9C:b-yke9ga) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the logic here (and below in all such cases)? Why not have the parsers?
</blockquote></details>

I assume that's because Borys didn't want to write the rules for all possible syscalls ;) So, for some we lack printing of the args (which I'm fine with).

**Review by stefanberger — COMMENTED** [review]
Thanks for the split-off! :-)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077#-:-MQwFZDl2nZH3RO_6APx:by5z82b)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: 4 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQwexL-3g-aiXTYFWKx:b5hrs8z) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you don't put a space before punctuation, even if the last word is a function description (i.e., it it was a single period then you wouldn't write `Some sentence with some_func(asdf) .`).
</blockquote></details>

I don't treat this `...` as punctuation, but more like visual marker, think of a line in a table, same as the `----------` at the begining (you don't start sentences with these either, yet we have them).
___
*[LibOS/shim/src/shim_parser.c, line 100 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutv-uEkKmnYnwzq6O:-MQweQSB2K4p46kuo5os:b-v4g1ay) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I assume that's because Borys didn't want to write the rules for all possible syscalls ;) So, for some we lack printing of the args (which I'm fine with).
</blockquote></details>

This are either not-implemented syscalls or these that had no parsers before. But I think it's mostly the first case.
Yes, my parser used old file + syscall table (`shim_table.h` or something like that)
___
*[LibOS/shim/src/shim_parser.c, line 1433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQustp-2YXZFHsH39Vu:-MQwgLep5SouuckDS6ux:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L1433)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line is not needed, please move this into the for loop
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_parser.c, line 1460 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutRVcBl6cWOP2mIgX:-MQwgNWa49adU6VjEd1O:b-tbj29h) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L1460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need to skip the first argument above and restart the list here? Why not memorize that `long retval = va_arg(ap, long);` above and use it here?
</blockquote></details>

Because these parser/printing function require `va_list*` as an argument. There is possible room for improvement in this whole file, I just did the least amount of work needed to make it work (while removing types from arguments).

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 100 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutv-uEkKmnYnwzq6O:-MQwiZaE0rgwWnV-ys4U:b-by5pv1) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This are either not-implemented syscalls or these that had no parsers before. But I think it's mostly the first case.
Yes, my parser used old file + syscall table (`shim_table.h` or something like that)
</blockquote></details>

OK. I mean, we could implement the parsers for them (we have their signatures), but I understand that it's more work for you :) Resolving.
___
*[LibOS/shim/src/shim_parser.c, line 1460 at r3](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQutRVcBl6cWOP2mIgX:-MQwitBzA4XP3BTR8RXE:bn0j4h4) ([raw file](https://github.com/oscarlab/graphene/blob/d138946ac314ab6321aa65b2bf9a6377d64a7b2d/LibOS/shim/src/shim_parser.c#L1460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because these parser/printing function require `va_list*` as an argument. There is possible room for improvement in this whole file, I just did the least amount of work needed to make it work (while removing types from arguments).
</blockquote></details>

Ah, true. My bad. Resolving.

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (random enclave initialization failure - unrelated - no idea why, aesmd hiccup?)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (same issue again, internal problems with Jenkins)

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQy28JU8bAni-4KG6eq:bco5n5z) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't treat this `...` as punctuation, but more like visual marker, think of a line in a table, same as the `----------` at the begining (you don't start sentences with these either, yet we have them).
</blockquote></details>

Yeah, but triple period looks totally like a punctuation here, but with ugly spacing ;)
Let's maybe leave the decision to @dimakuv.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MQzp6-e3LPNKWywty2z:bxmlolb) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but triple period looks totally like a punctuation here, but with ugly spacing ;)
Let's maybe leave the decision to @dimakuv.
</blockquote></details>

I don't see any problem with this visual marker. I like Borys's way of printing it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_parser.c, line 1410 at r2](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQtCNHU8DaGZY4u88C9:-MR0PvAKABMbwoek7cX8:by2kp9h) ([raw file](https://github.com/oscarlab/graphene/blob/2ee849567634e5862c1e56c2c8f6b9a266f39f3c/LibOS/shim/src/shim_parser.c#L1410)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see any problem with this visual marker. I like Borys's way of printing it.
</blockquote></details>

Ok, resolving then.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2077#-MQsqdz2CNHwTr1wfOYx:-MR0hwDGEqjKETqLS450:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/52cc7c28b210638ea846fcadf970bb342a48b679/LibOS/shim/src/shim_parser.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Btw, this table was auto-generated.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2077)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
