### PR TITLE
[Pal/Linux-SGX] Fix sgx allow file creation

### PR DESCRIPTION
**Pull request by jiazhang0**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1118)

### CODE REVIEW

**Comment by jiazhang0** [comment]
Run a force-push to get rid of conflict. By the way, add a regression test.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by jiazhang0** [comment]
Updated and squashed with a force-push.

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`waitpid03` failed)

**Pull request merged**
