### PR TITLE
LTP tweaks

### PR DESCRIPTION
**Pull request by pwmarcz**
I ran into several issues while running the LTP tests manually. This PR contains mostly tweaks so that it's easier to run LTP locally and analyze the results.

## How to test this PR? 

Jenkins should still pass LTP.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/1899#-MJnY5-9AlM4RkXnzQMV:-MJnY5-BCPV8p21LqItz:b-p2dtoe) ([raw file](https://github.com/oscarlab/graphene/blob/d7d401a02bf74397d2497b1d82151795139ce9fd/LibOS/shim/test/ltp/runltp_xml.py#L560)):*
> ```Python
>         self.xml[:] = sorted(self.xml, key=lambda test: test.get('name'))
> 
>     def validate_config(self):
> ```

I wanted to avoid validating the config and instead I put some validation (alphabetical order of sections) in `contrib/conf_lint.py`. I'm not opposed to bringing validation to runltp_xml.py, but then I'd like to also move here (or replicate) conf_lint.py.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: 2 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/1899#-MJnY5-9AlM4RkXnzQMV:-MK-4CWN24pQc3yfOGJP:b-7hr1yj) ([raw file](https://github.com/oscarlab/graphene/blob/d7d401a02bf74397d2497b1d82151795139ce9fd/LibOS/shim/test/ltp/runltp_xml.py#L560)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I wanted to avoid validating the config and instead I put some validation (alphabetical order of sections) in `contrib/conf_lint.py`. I'm not opposed to bringing validation to runltp_xml.py, but then I'd like to also move here (or replicate) conf_lint.py.
</blockquote></details>

Keeping that check in `conf_lint.py` sounds good, I moved it there.

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1899#-MK-_S75AMMJemfBtzoV:-MK-_S767HHnWTPz0lQs:b-8yps7h) (no related file):*
Hmm, Jenkins-Debug-18.04 failed on apps.LTP.clone03, @dimakuv @boryspoplawski: is this a known issue?
See https://leeroy.cs.unc.edu/job/graphene-debug-18.04/3762/testReport/junit/apps/LTP/clone03/.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1899#-MK-_S75AMMJemfBtzoV:-MK-bYFPCgP77m-3x2YS:b-2oxud2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, Jenkins-Debug-18.04 failed on apps.LTP.clone03, @dimakuv @boryspoplawski: is this a known issue?
See https://leeroy.cs.unc.edu/job/graphene-debug-18.04/3762/testReport/junit/apps/LTP/clone03/.
</blockquote></details>

From what I can tell this test uses `clone` to spawn a new process, for which it receives `SIGCHLD` signal. The issue is it reads from pipe in a blocking mode and completely ignores valid errors, like `EINTR`. LTP <3

---

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (see the comment above).

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1899#-MK-_S75AMMJemfBtzoV:-MK-uhPR4EDRiyWq2O30:b-v8wwyi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From what I can tell this test uses `clone` to spawn a new process, for which it receives `SIGCHLD` signal. The issue is it reads from pipe in a blocking mode and completely ignores valid errors, like `EINTR`. LTP <3
</blockquote></details>

Yeah, looks like a known issue, see Borys's reply.

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1899#-MK-_S75AMMJemfBtzoV:-MK-vivY2uonqrFpltfQ:bf3esmj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, looks like a known issue, see Borys's reply.
</blockquote></details>

Sorry, I was too fast too judge - that test does not set handler for `SIGCHLD`, to this should not happen ...

---

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1899#-MK-_S75AMMJemfBtzoV:-MK00zi11uC8iaGT_8xW:bci3o5f) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sorry, I was too fast too judge - that test does not set handler for `SIGCHLD`, to this should not happen ...
</blockquote></details>

Ok, this is Graphene issue unrelated to this PR, unblocking.
https://github.com/oscarlab/graphene/issues/1904

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1899)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
