### PR TITLE
Simplifying the flaky memory availability test for PAL

### PR DESCRIPTION
**Pull request by chiache**
The "Get Memory Available Quota" test in the PAL regression tests is unstable because it is affected by the OS. This patch removes the test and adds a simpler test that only verifies the range of memory quota.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/225)

### CODE REVIEW

**Comment by donporter** [comment]
I think the change is fine, although I am curious if you can explain a bit more what "is affected by the OS" means, and what the remaining test is actually testing for.

**Comment by chiache** [comment]
DkMemoryAvailableQuota() returns the remaining free memory in the host. This tests assumes that after accessing 1000 pages, the free memory should reduce by 4MB, or at least 80% of it. This test is flaky because it is heavily affected by the paging of the host OS. In most of the case, this test should pass, but in very rare cases, the host OS may act differently, causing the test to be flaky.

**Comment by donporter** [comment]
Would it make sense to just show that it reduces by at least a given amount, and accept that it can be more?

**Comment by chiache** [comment]
Yes, that's exactly what the test is doing, and for most of the time, it works.

**Comment by chiache** [comment]
Let's put a hold on this for a while. If the same test fails again, we can revive this PR.

**Comment by chiache** [comment]
Test this please.

**Comment by chiache** [comment]
test this please

**Pull request merged**
