### PR TITLE
[Pal/include] Remove not needed host_endian.h

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

`host_endian.h` is not needed.

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2042)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2042)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2042)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2042)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (kill11 timed out, known issue (CC: @dimakuv))

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2042)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
