### PR TITLE
Python tool for querying IAS API v4 (graphene-ias-query)

### LINKED ISSUE #22: Deprecate IAS API v3 and `ias_request` tool
IAS API v3 (which is currently used by attestation utilities in `/Pal/**/Linux-SGX/tools/*`) is undocumented as of this writing. The documentation describes only v4 API: https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf.

The `ias_request` tool needs not to be written in C, I wrote `graphene-ias-query` in Python as a wrapper of a simple library (`graphenelibos.ias`). When `graphene-ias-query` reaches functional parity with `ias_request`, the latter might be removed.

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

Forked from #2258.

This is a quick tool for querying IAS API v4. The existing tools use v3 API only.

Fixes: https://github.com/gramineproject/gramine/issues/22

## How to test this PR? 

The tool lacks tests, because it's complicated to provoke every possible IAS response. It would require multiple carefully setup boxen, each with it's own bespoke set of problems. Please review thoroughly.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2268)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2268)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[python/graphenelibos/ias.py, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2268#-MW_rpsW3NY62CJtVG5E:-MW_rpsW3NY62CJtVG5F:b-pwei8f) ([raw file](https://github.com/oscarlab/graphene/blob/8eef460debaec3c0603e3887c18fcfed94d6202b/python/graphenelibos/ias.py#L113)):*
> ```
> the FILE
> ```

Not just `FILE`? It functions as a proper name here I think.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2268)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2268#-MWcLxtH2z1PZ_8j3T_C:-MWcLxtH2z1PZ_8j3T_D:b39waie) ([raw file](https://github.com/oscarlab/graphene/blob/8eef460debaec3c0603e3887c18fcfed94d6202b/Documentation/conf.py#L154)):*
> ```Python
>     ('manpages/ias_request', 'ias_request', 'Submit Intel Attestation Service v3 request', [author], 1),
>     ('manpages/verify_ias_report', 'verify_ias_report', 'Verify Intel Attestation Service report', [author], 1),
>     ('manpages/graphene-ias-query', 'graphene-ias-query', 'Query Intel Attestation Service API v4', [author], 1),
> ```

Here we have `Query Intel Attestation Service API v4`. But below we have `Submit Intel Attestation Service APIv4 request`. Can we use the same (I prefer the latter)?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2268)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2268#-MWcLxtH2z1PZ_8j3T_C:-MWdJYGD2omcHe0OU7fP:bniwxue) ([raw file](https://github.com/oscarlab/graphene/blob/8eef460debaec3c0603e3887c18fcfed94d6202b/Documentation/conf.py#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we have `Query Intel Attestation Service API v4`. But below we have `Submit Intel Attestation Service APIv4 request`. Can we use the same (I prefer the latter)?
</blockquote></details>

Sure. I'll change that again when/if the tool will get feature parity with `verify_ias_request`.
___
*[python/graphenelibos/ias.py, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2268#-MW_rpsW3NY62CJtVG5E:-MWddHpM7uPsGsNz0xmr:b-kybin2) ([raw file](https://github.com/oscarlab/graphene/blob/8eef460debaec3c0603e3887c18fcfed94d6202b/python/graphenelibos/ias.py#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> the FILE
> ```

Not just `FILE`? It functions as a proper name here I think.
</blockquote></details>

This refers to `@click.argument(..., metavar='FILE', ...)` above. The docstring is used as a description in `--help`:

```
% ./graphene-ias-query --help
Usage: graphene-ias-query [OPTIONS] FILE

  Send an SGX quote from the FILE to the Intel Attestation Service and get
  the SGX attestation report back.

Options:
  --key TEXT                 API key (Ocp-Apim-Subscription-Key header).
                             [required]
  --format [raw|hex|base64]  Input format of the quote file.  [default: raw]
  --nonce TEXT               nonce (nonce JSON field).
  --version                  Show the version and exit.
  --help                     Show this message and exit.

```

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2268)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[python/graphenelibos/ias.py, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2268#-MW_rpsW3NY62CJtVG5E:-MWe0QZE41wZJizw_Ji2:buzlt50) ([raw file](https://github.com/oscarlab/graphene/blob/8eef460debaec3c0603e3887c18fcfed94d6202b/python/graphenelibos/ias.py#L113)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This refers to `@click.argument(..., metavar='FILE', ...)` above. The docstring is used as a description in `--help`:

```
% ./graphene-ias-query --help
Usage: graphene-ias-query [OPTIONS] FILE

  Send an SGX quote from the FILE to the Intel Attestation Service and get
  the SGX attestation report back.

Options:
  --key TEXT                 API key (Ocp-Apim-Subscription-Key header).
                             [required]
  --format [raw|hex|base64]  Input format of the quote file.  [default: raw]
  --nonce TEXT               nonce (nonce JSON field).
  --version                  Show the version and exit.
  --help                     Show this message and exit.

```
</blockquote></details>

Yeah, I know, but what I mean is that `FILE` is a variable name. AFAIK you wouldn't say "from the `g_asdf_qwer` variable" but just "from `g_asdf_qwer` variable" (because it's a proper name).

**Pull request closed without merging**
