### PR TITLE
[Examples] Merge python-simple and python-scipy

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

These two examples were largely identical, let's just merge them. Also, I'm dropping the fibonacci test, didn't look interesting and we already have a bunch of other tests for Python.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Examples/python-simple/scripts/benchrun.py, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_US5JE0AI21nyV9Sop:-M_US5JE0AI21nyV9Soq:b-9y0dr2) ([raw file](https://github.com/oscarlab/graphene/blob/af38491bedacc6ad0cd668a86c11e7265e3a7a48/Examples/python-simple/scripts/benchrun.py#L1)):*
> ```Python
> """
> ```

This script was never used by anything, right?
___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_USEbXAvqNSLQzkCbH:by00ye5) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
> ```Makefile
> .PHONY: test-4-%
> test-4-%: gsc-%-python3
> 	docker run $(addprefix -e , $(ENV_VARS)) $(DEVICES_VOLUMES) $(addsuffix $(IMAGE_SUFFIX), gsc-$*-python3) -c 'import os;os.system("ls")' 2>&1 | tee out
> ```

Did you check if this test still works in GSC?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Examples/python-simple/scripts/benchrun.py, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_US5JE0AI21nyV9Sop:-M_UuCYf9gxGdFSM7d4r:b-n7ozjp) ([raw file](https://github.com/oscarlab/graphene/blob/af38491bedacc6ad0cd668a86c11e7265e3a7a48/Examples/python-simple/scripts/benchrun.py#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This script was never used by anything, right?
</blockquote></details>

Yup, I didn't find any usages.
___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_UuJ1bDUJe1LL2h4HA:bn9nmin) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you check if this test still works in GSC?
</blockquote></details>

Hmm, not really, and seems the GSC pipeline is still disabled. Do you maybe have it set up and could test the changes? I had some troubles running GSC in my setup but never have found time to debug it.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_W4y5Q8pgAvfyNgXSN:bphdhom) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, not really, and seems the GSC pipeline is still disabled. Do you maybe have it set up and could test the changes? I had some troubles running GSC in my setup but never have found time to debug it.
</blockquote></details>

Blocking this before I test on GSC locally. Probably not before Friday...

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vahldiek)

___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_W6SWsEBXz7cO-g8Fj:bisslmr) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking this before I test on GSC locally. Probably not before Friday...
</blockquote></details>

@vahldiek: Maybe you would have a moment to test it?

**Comment by vahldiek** [comment]
___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_WLskdEhzD499TUZZP:b-h8x0ly) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vahldiek: Maybe you would have a moment to test it?
</blockquote></details>

Is this patch time sensitive? I haven't updated my GSC machine in weeks.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_XemW62ec4z2TZpxJ1:b-qm0q14) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Is this patch time sensitive? I haven't updated my GSC machine in weeks.
</blockquote></details>

Not a priority, just want to finish this before @woju starts rewriting examples to use Meson.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_eSpRE8jeNnVxjHEOQ:-M_eSpRF8SezrBymHUwJ:b4chzzx) (no related file):*
I tested this PR locally with GSC. It fails because GSC test scripts still contain a ref to `python-scipy`:
```
~/graphene/Tools/gsc$ grep -rI python-scipy
test/ubuntu18.04-numpy.dockerfile:COPY python-scipy/ /graphene/Examples
```

Please fix this.

---
___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_e_xwo56jzL-Frlv6Z:b-lf2inc) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not a priority, just want to finish this before @woju starts rewriting examples to use Meson.
</blockquote></details>

@mkow I tested everything locally. Apart from the bug with `python-scipy` (see top-level comment), everything works.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: 25 of 26 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_eSpRE8jeNnVxjHEOQ:-M_edqvM1yOVS_74Jsu9:bmbukkq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tested this PR locally with GSC. It fails because GSC test scripts still contain a ref to `python-scipy`:
```
~/graphene/Tools/gsc$ grep -rI python-scipy
test/ubuntu18.04-numpy.dockerfile:COPY python-scipy/ /graphene/Examples
```

Please fix this.
</blockquote></details>

Huh, seems I failed at grepping. Thanks for finding this!

---
___
*[Tools/gsc/test/Makefile, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_USEbXAvqNSLQzkCbG:-M_edxjj-RJFCMGMTPIV:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/211d78c8a1fa6a0f4aadd9fc13475b55c7e22bcb/Tools/gsc/test/Makefile#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I tested everything locally. Apart from the bug with `python-scipy` (see top-level comment), everything works.
</blockquote></details>

Thanks!

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-20.04-apps please (Jenkins worker failure)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Examples/python/scripts/dummy-web-server.py, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_gBwpD3I1FEWzhrk-m:-M_gBwpD3I1FEWzhrk-n:b34xboj) ([raw file](https://github.com/oscarlab/graphene/blob/b222822d9093911fb310c7318e08eeb08d3af27b/Examples/python/scripts/dummy-web-server.py#L21)):*
> ```Python
> 
>     port = int(argv[1])
>     srv = HTTPServer(('', port), DummyRequestHandler)
> ```

Shouldn't we bind to localhost?
___
*[Examples/python/scripts/test-scipy.py, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_gCKoI7__ZyaDZUldF:-M_gCKoI7__ZyaDZUldG:b3c0co6) ([raw file](https://github.com/oscarlab/graphene/blob/b222822d9093911fb310c7318e08eeb08d3af27b/Examples/python/scripts/test-scipy.py#L6)):*
> ```Python
> 
> setup = """\
> import numpy;
> ```

If you add newlines then also remove `;` please.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: 24 of 26 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Examples/python/scripts/dummy-web-server.py, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_gBwpD3I1FEWzhrk-m:-M_gFGSECfc7H_dZDkSI:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/b222822d9093911fb310c7318e08eeb08d3af27b/Examples/python/scripts/dummy-web-server.py#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we bind to localhost?
</blockquote></details>

Fixed.
___
*[Examples/python/scripts/test-scipy.py, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2369#-M_gCKoI7__ZyaDZUldF:-M_gFIyt56FpQ7ntdPyT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b222822d9093911fb310c7318e08eeb08d3af27b/Examples/python/scripts/test-scipy.py#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you add newlines then also remove `;` please.
</blockquote></details>

Done.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2369)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
