### PR TITLE
[Docs] Add tiny changes to Attestation document

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Just a couple tiny fixes for the Attestation document. People from Intel asked me to fix these bugs.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2271)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2271)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2271)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2271)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2271)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by woju** [comment]
Jenkins, test this please

**Comment by woju** [comment]
Jenkins test Jenkins-20.04 please
Jenkins test Jenkins-Debug-20.04 please
Jenkins test Jenkins-SGX-20.04 please
Jenkins test Jenkins-SGX-20.04-apps please

**Pull request merged**
