### PR TITLE
[Docs] Improve QuickStart guide

### LINKED ISSUE #2623: Meson not recognizing different values for -Ddirect and -Dsgx when run back-to-back and build dir already exists
## Description of the problem
If you follow the steps in the Quick Start Guide for non-SGX https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-without-sgx-support (`-Ddirect=enabled -Dsgx=disabled`) followed by the steps in the Quick Start Guide for SGX https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support (`-Ddirect=enabled -Dsgx=enabled`)  the SGX relevant libraries are not installed. Essentially the meson and ninja build commands for SGX are ignored and it says `nothing to do` and simply re-installs the libraries for graphene-direct.

The only way out of this is to delete the build folder and then run the meson, ninja build and install commands again with both -Ddirect and -Dsgx enabled.

## Steps to reproduce

1. Run the steps in Quick Start Guide for Graphene non-SGX.
2. Run the steps in Quick Start Guide for Graphene SGX.

## Expected results
After the commands for SGX are run, all Graphene SGX libs should be installed at relevant places.

## Actual results
Graphene SGX libs are not installed.

### LINKED ISSUE #2627: Quick Start Guide missing documentation for installation of meson python3-jinja2 python3-click
## Description of the problem
Quick Start Guide for SGX and Non-SGX do not specify the meson, python3-jinja2, python3-click which are used by Graphene, without which users will see error during the build/install or test execution steps. 

https://graphene.readthedocs.io/en/latest/quickstart.html

These seem to be present in the Building guide: https://graphene.readthedocs.io/en/latest/building.html#common-dependencies

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Add missing dependencies (Ubuntu-specific) and add a note on Meson reconfiguration after the first `meson build`.

Fixes #2627.
Fixes #2623.

## How to test this PR? 

Read the docs.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)

### CODE REVIEW

**Comment by dimakuv** [comment]
@jinengandhi-intel Looks good to you?

**Comment by jinengandhi-intel** [comment]
Yes looks good to me. Thanks.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Documentation/quickstart.rst, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgQOKYJ6VRdeQPOP6zc:-MgQOKYJ6VRdeQPOP6zd:b-e7tq80) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L94)):*
> ```reStructuredText
>   *not* have any effect. Instead, to change the build configuration, use ``meson
>   configure``. For example, if you built with ``meson build -Dsgx=disabled``
>   first and now want to enable SGX, type ``meson configure build -Dsgx=enabled``.
> ```

FYI, this is sometimes not enough: after some major changes in Meson setup (changing default CFLAGS? @woju might remember more), `meson configure` did not update everything, and I had to remove the build directory completely.

I'm not sure what the exact conditions are, and this seems like a rare case, so probably it's not worth mentioning here for now. Just something to keep in mind.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Documentation/quickstart.rst, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgQOKYJ6VRdeQPOP6zc:-MgQdy03-AZ6HX8jn5K5:b34lyv2) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L94)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

FYI, this is sometimes not enough: after some major changes in Meson setup (changing default CFLAGS? @woju might remember more), `meson configure` did not update everything, and I had to remove the build directory completely.

I'm not sure what the exact conditions are, and this seems like a rare case, so probably it's not worth mentioning here for now. Just something to keep in mind.
</blockquote></details>

The note as written holds true if you don't change `meson.build` files, which I think is a good assumption for `quickstart.rst`.

I think you're talking about editing `meson.build` to change `default_options` (and `c_args` therein). Yes, the options in configured directory don't change, because `default_options` are for next time when you'll be creating build directory. A builddir has fixed options which won't change without `meson configure`.

What's more problematic is that the instructions pretty much direct user to configure a builddir twice, once for graphene-direct, once for graphene-sgx. User should choose one or another, and if user wishes to build both PALs, builddir should be configured once for both. (Building twice in separate builddirs might or might not work, because LibOS would be built and installed twice).

Maybe we should rewrite quickstart to describe only building both PALs, and if for some reason user didn't want to build one, that should be described in `building.rst`.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Documentation/quickstart.rst, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgXQPpRDtvJaM1acxRe:-MgXQPpRDtvJaM1acxRf:b-u8r1yk) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L60)):*
> ```reStructuredText
>           python3 python3-click python3-jinja2 wget
>       sudo apt-get install -y libcurl4-openssl-dev libprotobuf-c-dev \
>           protobuf-c-compiler python3-pip python3-protobuf
> ```

I'd merge this into just a single invocation.
___
*[Documentation/quickstart.rst, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgXQimv-wizXbzSdIxw:-MgXQimv-wizXbzSdIxx:bhrm1gp) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L91)):*
> ```reStructuredText
>   ``/usr/local/bin`` is in your path (in ``PATH`` environment variable).
> 
> - If you invoked ``meson build`` once, the next invocation of this command will
> ```

What do you think about using `meson build/` or `meson setup build/` instead? Should be less confusing for users.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Documentation/quickstart.rst, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgXQPpRDtvJaM1acxRe:-MgdeSoL3WiViX9511xB:busvxav) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd merge this into just a single invocation.
</blockquote></details>

Done. I also went through all dependency-installation snippets in our Docs, and fixed alphabetic sorting and missing dependencies. Also, changed to use `apt-get` everywhere (instead of the moniker `apt`).
___
*[Documentation/quickstart.rst, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgXQimv-wizXbzSdIxw:-MgdeGIODtY0_dgIYwE0:bytkbea) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you think about using `meson build/` or `meson setup build/` instead? Should be less confusing for users.
</blockquote></details>

Done. `meson setup build/` was chosen, as a more readable counterpart to `meson configure build/`.

Also, changed `ninja` to also use `build/`.
___
*[Documentation/quickstart.rst, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgQOKYJ6VRdeQPOP6zc:-MgdeMxH57Jw2Pi70KNG:b-v4m6qu) ([raw file](https://github.com/oscarlab/graphene/blob/d9c8dbad38db05b775f63c734e11c06952d1aa8a/Documentation/quickstart.rst#L94)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The note as written holds true if you don't change `meson.build` files, which I think is a good assumption for `quickstart.rst`.

I think you're talking about editing `meson.build` to change `default_options` (and `c_args` therein). Yes, the options in configured directory don't change, because `default_options` are for next time when you'll be creating build directory. A builddir has fixed options which won't change without `meson configure`.

What's more problematic is that the instructions pretty much direct user to configure a builddir twice, once for graphene-direct, once for graphene-sgx. User should choose one or another, and if user wishes to build both PALs, builddir should be configured once for both. (Building twice in separate builddirs might or might not work, because LibOS would be built and installed twice).

Maybe we should rewrite quickstart to describe only building both PALs, and if for some reason user didn't want to build one, that should be described in `building.rst`.
</blockquote></details>

I'm not sure I understood Woju's comment, but sounds like something out of scope of this PR.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgowE1mEOXnCXGTz5P0:-MgowE1n1XMYgWFnPh2o:b-hxy9xd) (no related file):*
Could you also fix up:
- `.ci/lib/stage-build-nosgx.jenkinsfile` (x4)
- `.ci/lib/stage-build-sgx.jenkinsfile` (x4)
- `Runtime/pal_loader` (hmm, why do we still have this file in the repo?)

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: 7 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgowE1mEOXnCXGTz5P0:-Mgp4ZEi8g9NzjBdJOl9:b-l6wsqt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also fix up:
- `.ci/lib/stage-build-nosgx.jenkinsfile` (x4)
- `.ci/lib/stage-build-sgx.jenkinsfile` (x4)
- `Runtime/pal_loader` (hmm, why do we still have this file in the repo?)
</blockquote></details>

Done. Fixed up only `.ci/` files because I didn't find anything wrong with `Runtime/pal-loader`. What was the deal with this file?

(I think we still have this file to support "old" way of running Graphene; not sure if anyone uses it, and it's completely untested.)

---

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2629#-MgowE1mEOXnCXGTz5P0:-MgpVBAjBYJmw3ih2KD8:b-6l3v24) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Fixed up only `.ci/` files because I didn't find anything wrong with `Runtime/pal-loader`. What was the deal with this file?

(I think we still have this file to support "old" way of running Graphene; not sure if anyone uses it, and it's completely untested.)
</blockquote></details>

Ah, wait, `pal_loader` is fine, my grep matched too much and I didn't notice (it matched "./meson.build").

---

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
