### PR TITLE
Fix a malloc race during start-up. 

### PR DESCRIPTION
**Pull request by donporter**
The vma code (e.g., shim_do_mmap) has the invariant that address ranges are allocated by first reserving the vma space (using get_unmapped_vma()).  __system_malloc() violates this invariant when vmas_initialized is true, instead calling DkVirtualMemoryAlloc and then creating the vma using bkeep_mmap.

This patch adjusts __system_malloc() to follow the same synchronization convention as shim_do_mmap.

This should address issues #100 and #13.  I believe that both bugs were caused by the IPC helper thread allocating its stack (via __system_malloc()) and getting the same address range as part of libc.

### CODE REVIEW

**Comment by donporter** [comment]
Re-run with tip of this branch (12/2)
Only going to test SGX, as Jenkins _should_ be able to auto-run the Linux host tests (needs a kick from @neilbd )

---
- [x] Describe the testing setup:
  - [x] **Code version:** branch malloc-race
  - [x] **Linux kernel version:** 4.4.0-98-generic
  - [x] **Ubuntu version:** 16.04.03 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@cdf563
  - [x] **SGX driver version:** 01org/linux-sgx-driver@e3e42d4
---
- [x] **PAL**
  - [ ] **Linux host**
    - [ ] **Compilation:** passed
    - [ ] **Regression tests:** all passed
  - [x] **Linux+SGX host**
    - [x] **Compilation:** passed
    - [ ] **Regression tests:** 
---
- [x] **Library OS**
    - [x] **Compilation:** passed
    - [ ] **Linux host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** 
    - [ ] **Linux-SGX host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** Not fully supported yet
---
- [ ] **Applications**
    - [x] **Linux host**
      - [ ] **LMBench:** 
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** 
      - [ ] **Apache:** 
      - [ ] **Python:** 
    - [ ] **Linux-SGX host**
      - [ ] **LMBench:** lat_proc shell gets a segmentation fault.  lat_tcp, bw_tcp 127.0.0.1 gets permission denied messages in connect; bw_pipe has an occasional failure with the signal queue overflowing (same problems observed on master), an occasional vma assertion blows.  - generally, pretty flaky on SGX, but not necessarily different than master.
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** Fails with memory allocation issue (same on master)
      - [ ] **Apache:**
      - [ ] **Python:**

**Comment by donporter** [comment]
Test this please

**Comment by neilbd** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://leeroy.cs.unc.edu/job/graphene-debug/7/

**Comment by neilbd** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://leeroy.cs.unc.edu/job/graphene/154/

**Comment by neilbd** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://leeroy.cs.unc.edu/job/graphene-debug/8/

**Comment by neilbd** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://leeroy.cs.unc.edu/job/graphene/155/

**Comment by donporter** [comment]
Test this please.

**Comment by neilbd** [comment]
test this please

**Comment by mkow** [comment]
Indeed, it looks like this patch fixed the issue :) I'll also do more tests on other samples tomorrow and let you know if the problem is fixed.

**Comment by mkow** [comment]
Hi guys,

Any progress on merging this issue? From my side it seems that it fixed the issue, I was not able trigger it again.

**Comment by mkow** [comment]
Eh, seems that this bug is still not fixed: I just got another crash (log below) when using code from the commit c911f02 in SGX mode.
The bug seems to be very rare now though (I needed thousands of runs of my multithreaded program).

```
[    1] vma overlapped at 0x1a98d000-0x1b98d000
[    1] vma overlapped at 0x1ffff000-0x20000000
[    1] search interpreter: /lib/ld-linux-x86-64.so.2
[    1] chroot_seek: 0 0
[    1] chroot_seek: =0
[    1] bkeep_mmap: 0x1ba6c000-0x1ba70000
[    1] chroot_seek: 0 0
[    1] chroot_seek: =0
[    1] chroot_seek: 64 0
[    1] chroot_seek: =64
[    1] find unmapped vma between 0x10000-0x1ba7f000
[    1] get unmapped: 0x1a769000-0x1a98c000
[    1] bkeep_mmap: 0x1a769000-0x1a98c000
[    1] bkeep_mprotect: 0x1a78a000-0x1a989000
[    1] bkeep_mmap: 0x1a769000-0x1a78a000
[    1] bkeep_mmap: 0x1a989000-0x1a98c000
[    1] bkeep_mmap: 0x1a989000-0x1a98c000
[    1] bkeep_mmap: 0x1ba6b000-0x1ba6c000
[    1] add a library for gdb: file:/[snip]/graphene/Runtime/ld-linux-x86-64.so.2
[    1] shim process initialized
[    1] current heap 0x10000-0x1ba7f000 is not enough for allocating 536870912 bytes
[    1] ---- shim_brk(0x0) = 0x0
[    1] current heap 0x10000-0x1ba7f000 is not enough for allocating 536870912 bytes
[    1] ---- shim_brk(0x0) = 0x0
[    1] ---- shim_uname(0x1b98c1c5) = 0
[P7805] set tcb to 0x1ffd9a40
[P7805] ipc helper thread started
[    1] ---- shim_mmap(0x0,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0) ...
[    1] find unmapped vma between 0x10000-0x1ba7f000
[    1] get unmapped: 0x1ba6a000-0x1ba6b000
[P7805] bkeep_mmap: 0x1ba66000-0x1ba6b000
[    1] bkeep_mmap: 0x1ba6a000-0x1ba6b000
[P7805] allocated stack at 0x1ba67000 (size = 16384)
[    1] bkeep_mprotect: 0x1ba6a000-0x1ba6b000
[P7805] listen to process 0 on port 0x1ba760b0 (handle 0x1bfaeb20, type 0002)
[    1] Check vma flag failure: vma flags 20000022, checked flags 22
[P7805] listen to process 0 on port 0x1ba76038 (handle 0x1bfadf60, type 0001)
bug() bookkeep/shim_vma.c:258
[    1] teminating the whole process
[    1] deleting port 0x1ba760b0 (handle 0x1bfaeb20) for process 0
[    1] deleting port 0x1ba76038 (handle 0x1bfadf60) for process 0
[    1] set ipc helper restart
[    1] process 3551267805 successfully terminated
```

**Pull request merged**
