### PR TITLE
Allow skipping LTP tests by fnmatch

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

From now you can write * into section names in ltp.cfg, but such
sections can only contain "skip".

This was requested by @pwmarcz while porting to new LTP release.

## How to test this PR? 

Totally untested.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1885)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
I guess we're not supposed to merge this PR, it was just to share code with Paweł and test the change on Jenkins?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1885#-:-MJXA_SzA9m8VjorLJfp:b-tkcvn8)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by pwmarcz** [comment]
>I guess we're not supposed to merge this PR, it was just to share code with Paweł and test the change on Jenkins?

Yeah. I will have a working version along with the LTP upgrade PR.

**Comment by woju** [comment]
Why not, after fixing the missing import. :)

**Comment by pwmarcz** [comment]
Well, alright, here's what I'm using: https://github.com/oscarlab/graphene/pull/1886

Unfortunately I don't have push access to this repo, so I had to create a new PR.

**Pull request closed without merging**
