### PR TITLE
[LibOS] Refactor and simplify ioctl() emulation

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR refactors the `ioctl()` emulation. Basically, removes a lot of dummy code.

## How to test this PR? 

No change in logic, all tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)

### CODE REVIEW

**Comment by woju** [comment]
sorry, scipt barfed, retrying...

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_ioctl.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1990#-MMr8OQUErYBj0oSWjW8:-MMr8OQUErYBj0oSWjW9:b-xcwf1c) ([raw file](https://github.com/oscarlab/graphene/blob/68cdc090f2392656ce7bb1c425a7837e935d9323/LibOS/shim/src/sys/shim_ioctl.c#L39)):*
> ```C
>     int ret;
>     switch (cmd) {
>         case TIOCGPGRP:
> ```

Shouldn't we support this only for TTY FDs?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_ioctl.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1990#-MMr8OQUErYBj0oSWjW8:-MMrAyo4BJhujgUUzq0L:b-37x7ek) ([raw file](https://github.com/oscarlab/graphene/blob/68cdc090f2392656ce7bb1c425a7837e935d9323/LibOS/shim/src/sys/shim_ioctl.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we support this only for TTY FDs?
</blockquote></details>

Done. Yes, we should according to https://man7.org/linux/man-pages/man3/tcgetpgrp.3.html.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1990)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
