### PR TITLE
Update LTP tests to the upstream version

### PR DESCRIPTION
**Pull request by chiache**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/839)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`sigpending02` failed)

**Comment by mkow** [comment]
Jenkins, retest this please (3/15; success)

**Comment by dimakuv** [comment]
Jenkins, retest this please (4/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (5/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (6/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (7/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (8/15; `bw_unix` from Jenkins-SGX failed)

**Comment by mkow** [comment]
Jenkins, retest this please (9/15; `futex_wait03,1` from Jenkins failed)

**Comment by mkow** [comment]
Jenkins, retest this please (10/15; `Private mmap beyond file range (after fork)` from Jenkins-SGX failed)

**Comment by mkow** [comment]
Jenkins, retest this please (11/15; success)

**Comment by dimakuv** [comment]
Jenkins, retest this please (12/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (13/15; success)

**Comment by mkow** [comment]
Jenkins, retest this please (14/15; success)

**Pull request merged**
