### PR TITLE
[Docs] Update README.rst after publishing v1.2rc1

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Time to refresh the readme :)

## How to test this PR? 

Check "Rich diff" on GitHub to see if its renderer works fine with this.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2523)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2523)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2523)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2523)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2523)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
