### PR TITLE
[LibOS] Some IPC changes

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
For details please refer to commit messages. All changes are loosely connected - it's all preparation for removing `shim_ipc_info`.

## How to test this PR? 
As usual.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_handle.h, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZOMTn3M-hlWLqNbLk:-MWZOMTn3M-hlWLqNbLl:boxlgcn) ([raw file](https://github.com/oscarlab/graphene/blob/68a1995078efe4f5a8c25b34e2c1f2bc6cf3dbc4/LibOS/shim/include/shim_handle.h#L230)):*
> ```objc
>     unsigned long msqkey; /* msg queue key from user */
>     IDTYPE msqid;         /* msg queue identifier */
>     bool owned;           /* owned by current process */
> ```

So, doesn't this mean that `owned` is also redundant?
___
*[LibOS/shim/src/shim_init.c, line 505 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZPysk1q7Vd0raZdt0:-MWZPysl7dLOTMK_8Jxs:b-1ii8wm) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/shim_init.c#L505)):*
> ```C
> }
> 
> int vmid_to_uri(IDTYPE vmid, char* uri, size_t uri_len) {
> ```

Shouldn't this be moved somewhere else? E.g. to shim_ipc.c, or something like this.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 798 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZWzU48LaT6yj8xDIo:-MWZWzU5-s2RWiUgkwH4:bakft73) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/ipc/shim_ipc_ranges.c#L798)):*
> ```C
>     struct ipc_ns_offered* answers = __alloca(sizeof(struct ipc_ns_offered) * maxanswers);
> 
> retry:
> ```

While we're here, could you change this into a loop? I can't look at these gotos spread all over the place.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 9 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_handle.h, line 253 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZigk2CCswRnxprd8o:-MWZigk3DbMCbTBL4k1u:bdk3y4f) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/include/shim_handle.h#L253)):*
> ```objc
>     unsigned long semkey;
>     IDTYPE semid;
>     bool owned;
> ```

Same question as Michal's here.
___
*[LibOS/shim/include/shim_ipc.h, line 81 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZjJoG3NH7FV1gJwfd:-MWZjJoG3NH7FV1gJwfe:b-afu4x1) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L81)):*
> ```objc
>     struct shim_ipc_port* port;
>     struct shim_qstr uri;
>     LIST_TYPE(shim_ipc_info) hlist;
> ```

I'm afraid to ask, but was there any reason in having a list of `shim_ipc_info` objects?
___
*[LibOS/shim/include/shim_ipc.h, line 220 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZiybjCUycJpY6VCaJ:-MWZiybjCUycJpY6VCaK:br39ya) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L220)):*
> ```objc
> } __attribute__((packed));
> 
> int ipc_answer_send(struct shim_ipc_port* port, IDTYPE dest, size_t answers_cnt,
> ```

Why did you remove this one? Or the other way: why did you remove this but left `ipc_answer_callback()`?
___
*[LibOS/shim/include/shim_ipc.h, line 322 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZj5Ip0ZFdU-Y1mBRI:-MWZj5Ip0ZFdU-Y1mBRJ:b-h5ljg1) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L322)):*
> ```objc
> int ipc_sysv_movres_send(struct sysv_client* client, IDTYPE owner, const char* uri, IDTYPE resid,
>                          enum sysv_type type);
> int ipc_sysv_movres_callback(struct shim_ipc_msg* msg, struct shim_ipc_port* port);
> ```

Why did you remove these `movres` functions but kept `struct shim_ipc_sysv_movres`?
___
*[LibOS/shim/src/shim_init.c, line 505 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZPysk1q7Vd0raZdt0:-MWZjYFr7o0i13fr2PyW:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/shim_init.c#L505)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this be moved somewhere else? E.g. to shim_ipc.c, or something like this.
</blockquote></details>

+1
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 129 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZhk9l6PQbbC1diSR0:-MWZhk9l6PQbbC1diSR1:bu9t98f) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/ipc/shim_ipc_helper.c#L129)):*
> ```C
>     }
> 
>     log_debug("Reconnecting IPC port %s\n", uri);
> ```

Can we have a better message here? `Connecting to the leader process using IPC port %s`.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 798 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZWzU48LaT6yj8xDIo:-MWZkbqM01pu9NiFvfrj:bew29gu) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/ipc/shim_ipc_ranges.c#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, could you change this into a loop? I can't look at these gotos spread all over the place.
</blockquote></details>

I have a feeling Borys will burn all this stuff in a next PR :)
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 573 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZjzoC8UeqoORR9_lR:-MWZjzoC8UeqoORR9_lS:b-8w6kp7) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_ranges.c#L573)):*
> ```C
>     memcpy(msgin->uri, qstrgetstr(&g_process_ipc_info.self->uri), len + 1);
> 
>     log_debug("ipc send to %u: IPC_MSG_LEASE(%s)\n", leader, msgin->uri);
> ```

Do you know the reason why this `LEASE` message previously had `uri` and why you were able to remove it now?
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 656 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZk9aX2NTgsQTye19K:-MWZk9aX2NTgsQTye19L:b-w49t71) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_ranges.c#L656)):*
> ```C
>     msgin->tenant = tenant;
>     msgin->idx    = idx;
>     memcpy(msgin->uri, uri, len + 1);
> ```

Do you know the reason why this `SUBLEASE` message previously had `uri` and why you were able to remove it now?
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 741 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkK3f6uR3eB3zB9SS:-MWZkK3f6uR3eB3zB9ST:b-8wqllv) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/ipc/shim_ipc_ranges.c#L741)):*
> ```C
> 
>     return 0;
> }
> ```

Now you made these functions static, and the only user seems to be the `QUERY` message callback. Do you know what these actually do? Do we really need `ANSWER` messages if we only use them internally as `QUERY` helpers?
___
*[LibOS/shim/src/ipc/shim_ipc_sysv.c, line 224 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkljU4Z_tC38JbPBO:-MWZkljU4Z_tC38JbPBP:brl1sae) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_sysv.c#L224)):*
> ```C
> }
> 
> int ipc_sysv_movres_send(struct sysv_client* client, IDTYPE owner, const char* uri, IDTYPE resid,
> ```

Why were you able to remove these?
___
*[LibOS/shim/src/sys/shim_msgget.c, line 610 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkqTo3RJ93vVYFZRx:-MWZkqTo3RJ93vVYFZRy:b-7syh4g) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/sys/shim_msgget.c#L610)):*
> ```C
>     if (!msgq->owned) {
>         if (src) {
>             ret = -ECONNREFUSED;
> ```

What is happening here?
___
*[LibOS/shim/src/sys/shim_semget.c, line 619 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZktGsCZTm7znsEKyq:-MWZktGsCZTm7znsEKyr:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/sys/shim_semget.c#L619)):*
> ```C
>     if (!sem->owned) {
>         if (client) {
>             ret = -ECONNREFUSED;
> ```

ditto

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: 12 of 14 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_handle.h, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZOMTn3M-hlWLqNbLk:-MW_M9ZD9W0-rHhZfQ5s:bgyqxjv) ([raw file](https://github.com/oscarlab/graphene/blob/68a1995078efe4f5a8c25b34e2c1f2bc6cf3dbc4/LibOS/shim/include/shim_handle.h#L230)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, doesn't this mean that `owned` is also redundant?
</blockquote></details>

Probably yes, I'll check.
I just didn't want to go too hard on the sysv ipc thingies, they seem to be heavily broken, so I start removing all unused + broken code, they will just disappear. That would be a good thing, but Apache uses them, how it does not collapse is beyond my ability to understand.

Update: no, it's actively used in the code. I believe the owner is identified by querying leases/subleases/ranges (whatever it's called) for the sysv msg key.
___
*[LibOS/shim/include/shim_handle.h, line 253 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZigk2CCswRnxprd8o:-MW_TfZW2l2rRHOX0Clp:bnb75vv) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/include/shim_handle.h#L253)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same question as Michal's here.
</blockquote></details>

ditto (just change msg to sem)
___
*[LibOS/shim/include/shim_ipc.h, line 81 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZjJoG3NH7FV1gJwfd:-MW_MHSd8HksVRAuT5gV:bn0ww3n) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm afraid to ask, but was there any reason in having a list of `shim_ipc_info` objects?
</blockquote></details>

Maybe someday there was, who knows? Definitely not in the current state of the codebase.
___
*[LibOS/shim/include/shim_ipc.h, line 220 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZiybjCUycJpY6VCaJ:-MW_MadpA2KtLbqB35ao:b-4faje3) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this one? Or the other way: why did you remove this but left `ipc_answer_callback()`?
</blockquote></details>

Because this function turned out to be `static` but callbacks are used by the ipc helper thread, so they need to be extern.
___
*[LibOS/shim/include/shim_ipc.h, line 322 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZj5Ip0ZFdU-Y1mBRI:-MW_NRlJ3oQ_CHTUPslg:b-x7wmj7) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/include/shim_ipc.h#L322)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove these `movres` functions but kept `struct shim_ipc_sysv_movres`?
</blockquote></details>

Good catch, just missed it. Removed.
___
*[LibOS/shim/src/shim_init.c, line 505 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZPysk1q7Vd0raZdt0:-MW_NfEw19OmTgf3j5IE:bqokh4y) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/shim_init.c#L505)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Well, it fit together with `create_pipe` so I added it here...
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 129 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZhk9l6PQbbC1diSR0:-MW_OaQK95NMX1I-bi74:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/ipc/shim_ipc_helper.c#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we have a better message here? `Connecting to the leader process using IPC port %s`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 798 at r2](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZWzU48LaT6yj8xDIo:-MW_RZbY9PBXip_2jMPM:begle3n) ([raw file](https://github.com/oscarlab/graphene/blob/ef54b22af583de01fc5f56c7f408323698803531/LibOS/shim/src/ipc/shim_ipc_ranges.c#L798)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have a feeling Borys will burn all this stuff in a next PR :)
</blockquote></details>

Yeah, not in the next PR but I want to get rid/rewrite all of the ranges code.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 573 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZjzoC8UeqoORR9_lR:-MW_P304Bxl_7PCa1D7D:b-jter0s) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_ranges.c#L573)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you know the reason why this `LEASE` message previously had `uri` and why you were able to remove it now?
</blockquote></details>

Afaik there was no explicit assumption that `uri` is connected to `vmid`, but in practice it was just `str(vmid)`. Anyway, now `uri` of process IPC handle is always created from `vmid`.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 656 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZk9aX2NTgsQTye19K:-MW_PyRO-1Uq7bVzi4pg:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_ranges.c#L656)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you know the reason why this `SUBLEASE` message previously had `uri` and why you were able to remove it now?
</blockquote></details>

ditto
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 741 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkK3f6uR3eB3zB9SS:-MW_QjA3B26AGl7QJUzp:bafat72) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/ipc/shim_ipc_ranges.c#L741)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you made these functions static, and the only user seems to be the `QUERY` message callback. Do you know what these actually do? Do we really need `ANSWER` messages if we only use them internally as `QUERY` helpers?
</blockquote></details>

Only one is `static`, callback is used by ipc helper thread.
They send back an `answer` to a `query` (i.e. a separate ipc message, possibly with an ack), I think the idea was that the `answer` can be generic, but in practice it's not.
We cannot remove them without further changes to IPC code.
___
*[LibOS/shim/src/ipc/shim_ipc_sysv.c, line 224 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkljU4Z_tC38JbPBO:-MW_RnsY9yGcqdLp3Wis:b-84rhlp) ([raw file](https://github.com/oscarlab/graphene/blob/f54d9f1c97abe4de99074f44e181f2e424df9209/LibOS/shim/src/ipc/shim_ipc_sysv.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why were you able to remove these?
</blockquote></details>

Because nothing called them. TBH I did not dig deeper, if it was up to me I would purge every file with sysv in it.
___
*[LibOS/shim/src/sys/shim_msgget.c, line 610 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZkqTo3RJ93vVYFZRx:-MW_S8MbDYT8tT1MdI_i:b-7hkodx) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/sys/shim_msgget.c#L610)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is happening here?
</blockquote></details>

No idea, I've just removed dead code.
___
*[LibOS/shim/src/sys/shim_semget.c, line 619 at r3](https://reviewable.io/reviews/oscarlab/graphene/2263#-MWZktGsCZTm7znsEKyq:-MW_SKIo8uwFH91_N4qW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/e806c40e323e1494d6a0c17ce8b4dd21eaee3517/LibOS/shim/src/sys/shim_semget.c#L619)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 9 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`semop1` LTP test timed out, interesting)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 13 files at r6, 9 of 9 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2263)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
