### PR TITLE
[LibOS] Split `shim_ipc_pid.c` into two files

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
I will reuse this file name in another PR, but with different content.
I've split the change to make review easier.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2447)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2447)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2447)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2447)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2447)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
