### PR TITLE
Updated README with latest instructions

### PR DESCRIPTION
**Pull request by Kushg02**
At the request of rainfld, I have updated the README to ease the setup, installation, and use of Graphene

## Affected components

- [x] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Updated README at request of rainfld to make the installation of graphene easier

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/834)

### CODE REVIEW

**Comment by Kushg02** [comment]
> > ```gfm
> >     4. Inside of this document, leave everything the same except for the sgx.trusted_children and sgx.trusted_files, adding whatever dependencies and files are necessary for your executable. 
> >      5. run `make && make SGX=1 && make SGX_RUN=1`
> >      6. then run `sudo SGX=1 ./yourfile.manifest`
> > ```
> 
> sudo? I dont think graphene requires sudo, does it?
> 
> _[README.md, line 266 at r1](https://reviewable.io/reviews/oscarlab/graphene/834#-LjwmbQ8BRTUPF4h5Tgt:-LjwmbQ8BRTUPF4h5Tgu:b22qgxw) ([raw file](https://github.com/oscarlab/graphene/blob/75b1a42bde776a118b43807e1aad752c38aee396/README.md#L266)):_
> 
> > ```gfm
> >     1) cd into graphene root 
> >     2) run `sudo make SGX=1 clean` 
> >     3) run `sudo make && make SGX=1 && make SGX_RUN=1`  
> > ```
> 
> Remove sudo

Occasionally make without sudo (ie: the first time), there are permission denied errors.

**Comment by dimakuv** [comment]
Retest this please

**Comment by Kushg02** [comment]
___
*[README.md, line 220 at r8](https://reviewable.io/reviews/oscarlab/graphene/834#-Lk73UPv72M0Oq3BAPv6:-Lk9p_xqBkwwN5ZSQpw3:b-jspaou) ([raw file](https://github.com/oscarlab/graphene/blob/fa53ec4d6649bc58388ae260b15b9a5c9c213c40/README.md#L220)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

General comment: I'm not sure if the steps listed below are the way of setting up your own binary in Graphene which we'd like to encourage. Any production-like setup should manually run pal-sgx-sign, pal_loader etc, not just place the binaries in test directory and use our Makefiles (which are intended only for our test suite).
</blockquote></details>

Understood. My coworker and I weren't attempting to create a production-like setup and we found this to be the most effective solution for our testing needs. If you would like I can either remove this section for now or keep it until we document a better solution.

**Comment by dimakuv** [comment]
We will re-write the README completely in the near future, so closing this PR.

**Pull request closed without merging**
