### PR TITLE
Misc fixes, including using size_t for sizes

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

As usual, a bunch of fixes for things which annoyed me recently enough to create a PR. If some of the changes will turn out to be controversial, a can split this into smaller PRs.

## How to test this PR? 

No functional changes, except that some functions will properly support big buffers now.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/include/lib/slabmgr.h, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7-pR9lu4U3oHXOFs:-MUD7-pS1LFDePRCk-lv:b-so4z4) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/include/lib/slabmgr.h#L67)):*
> ```objc
>  * be a multiple of 16 bytes. TODO: Add compile time assertion that this
>  * invariant is respected. */
> #define AREA_PADDING 12
> ```

This padding doesn't make sense now. Probably this whole 16B alignment requirement is not needed anyway (otherwise Graphene would fail), but we should either remove or change it.

My gut feeling is that this alignment requirement is not needed at all.
___
*[Pal/src/host/Linux/db_sockets.c, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7cLE9V3GJ-kamRa4:-MUD7cLE9V3GJ-kamRa5:bb71nyg) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/src/host/Linux/db_sockets.c#L174)):*
> ```C
>     if ((size_t)len >= buf_size)
>         return -PAL_ERROR_TOOLONG;
>     
> ```

Oops
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7t6O0u-G1KP71xq0:-MUD7t6O0u-G1KP71xq1:bbgk6ab) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/src/host/Linux-SGX/sgx_graphene.c#L37)):*
> ```C
> 
> static int vfdprintf(int fd, const char* fmt, va_list ap) {
>     struct printbuf b;
> ```

Why not rename to `buf` here as well?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: 20 of 23 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/include/lib/slabmgr.h, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7-pR9lu4U3oHXOFs:-MUDgG4o9GGRKb7zzBmM:b-tqo61m) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/include/lib/slabmgr.h#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This padding doesn't make sense now. Probably this whole 16B alignment requirement is not needed anyway (otherwise Graphene would fail), but we should either remove or change it.

My gut feeling is that this alignment requirement is not needed at all.
</blockquote></details>

I think the 16B-alignment is required, otherwise internal malloc may return unaligned objects, breaking assumptions of the compiler.
But good catch that we need to fix this after changing types. Check now.
___
*[Pal/src/host/Linux/db_sockets.c, line 174 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7cLE9V3GJ-kamRa4:-MUEf_aM3mHswboi7cMO:biahewh) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/src/host/Linux/db_sockets.c#L174)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops
</blockquote></details>

Oops indeed.
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUD7t6O0u-G1KP71xq0:-MUEftfQBZ0gTDcYwZ5y:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2b09fc303d62217cbd2c458c4a290a8610eb30e/Pal/src/host/Linux-SGX/sgx_graphene.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not rename to `buf` here as well?
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`sendfile05` LTP test failed).

There is an interesting error message on `sendfile05`. Graphene IPC subsystem is at fault:
```
assert failed ipc/shim_ipc_ranges.c:706 !qstrempty(&g_process_ipc_info.ns->uri)
[P22994:T2:sendfile05_64] Sending IPC process-exit notification failed: -3
```

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEqgOn9HTnPOIhJcvp:-MUEqgOn9HTnPOIhJcvq:bqvzpk4) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L138)):*
> ```C
>         return bytes;
>     *output_size = (size_t)bytes;
>     return *output_size == buf_size ? -ENAMETOOLONG : 0;
> ```

Shouldn't this be `>=`? `snprintf` returns the needed size (excluding the ending `\0`).
___
*[LibOS/shim/src/sys/shim_socket.c, line 167 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEr4dA44qcycz9cVPn:-MUEr4dA44qcycz9cVPo:b-65mdz1) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L167)):*
> ```C
>         return len;
>     if (output_size)
>         *output_size = (size_t)len;
> ```

We need to handle the case of `len >= buf_size` here.
___
*[LibOS/shim/src/sys/shim_socket.c, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEpgpQ6ugAleqz96HD:-MUEpgpQ6ugAleqz96HE:b-iibyj8) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L204)):*
> ```C
>                 if (ret < 0)
>                     return ret;
>                 buf[bytes + addr_len] = ':';
> ```

Issue already present, but I think it could be the case that `bytes + addr_len == buf_size`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 242 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFGN7eDHM85a6HfPyg:-MUFGN7f4MUg9spuihlj:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L242)):*
> ```C
>                 if (ret < 0)
>                     return ret;
>                 buf[bytes + addr_len] = ':';
> ```

ditto
___
*[Pal/include/lib/slabmgr.h, line 217 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHZ7L2eYsgNAOQAd8:-MUFHZ7MDmgcJbyoBhg9:brpig71) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L217)):*
> ```objc
> 
>     void* addr = (void*)mgr + sizeof(SLAB_MGR_TYPE);
>     for (int i = 0; i < SLAB_LEVEL; i++) {
> ```

Please change to unsigned or size_t, while we are here
___
*[Pal/include/lib/slabmgr.h, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHhm973xO2ifWs-cE:-MUFHhm973xO2ifWs-cF:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L238)):*
> ```objc
>     void* addr = (void*)mgr + sizeof(SLAB_MGR_TYPE);
>     SLAB_AREA area, tmp, n;
>     for (int i = 0; i < SLAB_LEVEL; i++) {
> ```

ditto
___
*[Pal/include/lib/slabmgr.h, line 298 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHiZN2rc5UEpp9lY9:-MUFHiZN2rc5UEpp9lYA:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L298)):*
> ```objc
>     int level = -1;
> 
>     for (int i = 0; i < SLAB_LEVEL; i++)
> ```

ditto
___
*[Pal/lib/stdlib/printfmt.c, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFJnSfA1hn7b7GgNn_:-MUFJnSg5MYyaN1xOphL:b2ni78k) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/Pal/lib/stdlib/printfmt.c#L56)):*
> ```C
> void vfprintfmt(int (*_fputch)(void*, int, void*), void* f, void* putdat, const char* fmt,
>                 va_list ap) {
>     register const char* p;
> ```

lol
___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUFK4iVBxTmNjCnyJbL:bxvo0fi) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
> ```C
> 
>     while (1) {
>         while ((ch = (unsigned char)*(fmt++)) != '%') {
> ```

Why do we need this cast?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: 18 of 23 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/sys/shim_socket.c, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEqgOn9HTnPOIhJcvp:-MUFnfsmB1bQb17fXM7E:by0chcb) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `>=`? `snprintf` returns the needed size (excluding the ending `\0`).
</blockquote></details>

Wow, nice catch. It was like this before, I just refactored it without really thinking about the check :) Fixed.
___
*[LibOS/shim/src/sys/shim_socket.c, line 167 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEr4dA44qcycz9cVPn:-MUFohxr4EpP0988RTWP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L167)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to handle the case of `len >= buf_size` here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEpgpQ6ugAleqz96HD:-MUFol5-3jdLBRb0WQPL:b-t36w8s) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Issue already present, but I think it could be the case that `bytes + addr_len == buf_size`.
</blockquote></details>

Actually, this case works - the returned value from `inet_translate_addr()` is length, not size, so we still have one byte available in the buffer. And the next call will get `buf_size == 0`, and error out. But the argument name I used was wrong, fixed.
___
*[LibOS/shim/src/sys/shim_socket.c, line 242 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFGN7eDHM85a6HfPyg:-MUFxE0L0g6TIbZ0FOmY:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L242)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/include/lib/slabmgr.h, line 217 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHZ7L2eYsgNAOQAd8:-MUFy9xLDzpNL4FiScUT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to unsigned or size_t, while we are here
</blockquote></details>

Done.
___
*[Pal/include/lib/slabmgr.h, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHhm973xO2ifWs-cE:-MUFyAIuBdu1STcw8pMJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L238)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/include/lib/slabmgr.h, line 298 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFHiZN2rc5UEpp9lY9:-MUFyRZL7t00OediW11E:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/include/lib/slabmgr.h#L298)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/lib/stdlib/printfmt.c, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFJnSfA1hn7b7GgNn_:-MUFySpx2DUusjQ9MXZg:bb7s9mg) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/Pal/lib/stdlib/printfmt.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

lol
</blockquote></details>

yeah
___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUFyWWeD19KEUQa3jP4:b7upe6z) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this cast?
</blockquote></details>

Because `ch` is `int` and we don't want to sign-extend it. And it's an `int` probably because `_fputch()` takes `int`. I stopped at this point and didn't follow further.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEpgpQ6ugAleqz96HD:-MUGSYbV0K4sxOq_h-73:b74w2ru) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, this case works - the returned value from `inet_translate_addr()` is length, not size, so we still have one byte available in the buffer. And the next call will get `buf_size == 0`, and error out. But the argument name I used was wrong, fixed.
</blockquote></details>

I don't like this, it's just shifting the check into the next function call. Please either add a explicit check or at least a comment, that the next function call needs at least 1 byte space and will error out on 0.
___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUGUutiDQ8yeI3bdq9O:b-l09d4y) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
> and we don't want to sign-extend it. 

Why not?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 168 at r4](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUGWO9c9y1tM8dMOKOe:-MUGWO9c9y1tM8dMOKOf:b-i0tqig) ([raw file](https://github.com/oscarlab/graphene/blob/8b0d9f68b436db0755414ebefbb66b4b88bbd973/LibOS/shim/src/sys/shim_socket.c#L168)):*
> ```C
>     if (output_len)
>         *output_len = (size_t)len;
>     return *output_len >= buf_size ? -ENAMETOOLONG : 0;
> ```

`output_len` might be NULL and you dereference it here...
Actually, please unify the interface, either disallow or allow NULL everywhere (now this function is special in that regard).

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_socket.c, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUEpgpQ6ugAleqz96HD:-MUiKbvn6BRvpbiUVjna:b-f8sf1p) ([raw file](https://github.com/oscarlab/graphene/blob/7d4c300cc37b7dbff2bb0426c95f3561f8dd0688/LibOS/shim/src/sys/shim_socket.c#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this, it's just shifting the check into the next function call. Please either add a explicit check or at least a comment, that the next function call needs at least 1 byte space and will error out on 0.
</blockquote></details>

Added a comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 168 at r4](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUGWO9c9y1tM8dMOKOe:-MUhwmhg3cjUS0f49ks8:b-aj53ns) ([raw file](https://github.com/oscarlab/graphene/blob/8b0d9f68b436db0755414ebefbb66b4b88bbd973/LibOS/shim/src/sys/shim_socket.c#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`output_len` might be NULL and you dereference it here...
Actually, please unify the interface, either disallow or allow NULL everywhere (now this function is special in that regard).
</blockquote></details>

Oops. I added this change right before pushing and forgot to retest, sorry. I unified the interface everywhere.
___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUiLI9s2PxKWcs0h5-W:b-htf1wd) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> and we don't want to sign-extend it. 

Why not?
</blockquote></details>

I expect fputch to get values in range 0-255, not -128-127. At least that's what sounds intuitive.

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUiQXAa3lHUq5AQjTjB:br67j3l) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I expect fputch to get values in range 0-255, not -128-127. At least that's what sounds intuitive.
</blockquote></details>

In most (popular?) implementations `char` is actually signed. Also, `_fputch` can cast either to `signed char` or `unsigned char` and obtain what it needs from the int, regardless whether it's sign extended or not.
Anyway, it's not really important, unblocking.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUiqY686s-NL5c5sfJx:b2shwuu) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In most (popular?) implementations `char` is actually signed. Also, `_fputch` can cast either to `signed char` or `unsigned char` and obtain what it needs from the int, regardless whether it's sign extended or not.
Anyway, it's not really important, unblocking.
</blockquote></details>

If it took `char` as an argument, then yeah, but passing e.g. `-1` to printing function in `int` argument seems very unintuitive (and this callback here is not from the standard).

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 4 of 5 files at r4, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2181)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/lib/stdlib/printfmt.c, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2181#-MUFK4iU829oNRWizBOx:-MUj9aju1Mf3MASB3zfU:b-5o0nbc) ([raw file](https://github.com/oscarlab/graphene/blob/2cf4140c700c3b9be43584e7bef79ea53d8a8938/Pal/lib/stdlib/printfmt.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If it took `char` as an argument, then yeah, but passing e.g. `-1` to printing function in `int` argument seems very unintuitive (and this callback here is not from the standard).
</blockquote></details>

I don't see a difference between passing, `-1` as int or char...

**Pull request merged**
