### PR TITLE
[*/regression] Migrate to Python 3

### PR DESCRIPTION
**Pull request by HW42**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)

[*/regression] Migrate to Python 3

## How to test this PR? (if applicable)

Run regression tests.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/605)

### CODE REVIEW

**Comment by mkow** [comment]
For bookkeeping: this partially fixes #609.

**Comment by donporter** [comment]
This is failing in Jenkins because our environment doesn't include python3.  Please add a line here:

https://github.com/oscarlab/graphene/blob/483cde8ab73e603067fa27862530bbfb0d67f594/Jenkinsfiles/ubuntu-16.04.dockerfile#L18

that adds 'python3-minimal' and it should probably work.

**Comment by donporter** [comment]
Shared object regression.  Should work next time.

**Comment by donporter** [comment]
@HW42 Can you resolve the conflicts with master, and squash down to an appropriate number of commits?

**Comment by donporter** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
