### PR TITLE
[LibOS] Add Glibc 2.34 and make it default

### PR DESCRIPTION
**Pull request by jurobystricky**
Add support for Glibc version 2.34.

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>

## Description of the changes 
Add support for glibc.2.34 rather than applying CVE patch(es) to Glibc-2.33

## How to test this PR? 
Run the LibOS regression test suite:
<pre>
$ cd graphene
$ openssl genrsa -3 -out ./Pal/src/host/Linux-SGX/signer/enclave-key.pem 3072
$ ISGX_DRIVER_PATH="" make SGX=1 -j$(nproc)
$ make -j$(nproc)
$ meson build --buildtype=release -Ddirect=enabled -Dsgx=enabled
$ ninja -C build
$ sudo ninja -C build install
$ cd LibOS/shim/test/regression
$ make SGX=1 regression
</pre>
Expected result: No failed tests. Something like this:
<pre>
========================================================== 103 passed, 4 skipped in 147.10 seconds ==========================================================
</pre>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)

### CODE REVIEW

**Review by woju — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jurobystricky)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi926Pe3xQVrby3v2WK):*
please remove these trailing blanks
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92Fz61gwLZXnww7xr):*
`Completely purge` -> `And completely purge`
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92LpH7urhqUlK1T8Q):*
ditto
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92aO46R8bduxD3Er6):*
This should not be indented

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jurobystricky)

___
*[.ci/linux-direct-ubuntu18.04-gcc-glibc231.jenkinsfile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiBv6xg0MI4VQE5-tJY:-MiBv6xh3_M4WrHMjL_j:b-xzibx9) ([raw file](https://github.com/oscarlab/graphene/blob/398727edcee3f8e29c050d2cfdcc7a79d7387e5d/.ci/linux-direct-ubuntu18.04-gcc-glibc231.jenkinsfile#L1)):*
> ```
> node('nonsgx_slave') {
> ```

Name of this file does not match now.
Update: actually, this file can be completely removed now.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jurobystricky)

___
*[LibOS/glibc-patches/glibc-2.34.patch, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiBy5LQD6J2MQeRXglt:-MiBy5LQD6J2MQeRXglu:b-kf8ntj) ([raw file](https://github.com/oscarlab/graphene/blob/0b4943e00ed73a0e1117a0d17c22e56675610eba/LibOS/glibc-patches/glibc-2.34.patch#L2)):*
> ```Diff
> diff --git a/Makerules b/Makerules
> index 596fa68376..66458e36dd 100644
> ```

Please generate the diff with full hashes.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @jurobystricky)

___
*[LibOS/glibc-patches/glibc-2.34.patch, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiBy5LQD6J2MQeRXglt:-MiLmqI75wMLwRGbwbqA:b-n5bixj) ([raw file](https://github.com/oscarlab/graphene/blob/0b4943e00ed73a0e1117a0d17c22e56675610eba/LibOS/glibc-patches/glibc-2.34.patch#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please generate the diff with full hashes.
</blockquote></details>

Yes, please. To generate with full hashes, do `git diff --full-index`

**Review by jurobystricky — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @jurobystricky, and @mkow)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi926Pe3xQVrby3v2WK):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove these trailing blanks
</blockquote></details>

Will remove any trailing blanks from the commit message.
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92Fz61gwLZXnww7xr):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Completely purge` -> `And completely purge`
</blockquote></details>

Will do
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92LpH7urhqUlK1T8Q):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Will remove trailing blanks
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92aO46R8bduxD3Er6):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should not be indented
</blockquote></details>

Not sure how that happened. Will fix.
___
*[.ci/linux-direct-ubuntu18.04-gcc-glibc231.jenkinsfile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiBv6xg0MI4VQE5-tJY:-MiMXWUd77ex_l2-PG9h:b-uczylh) ([raw file](https://github.com/oscarlab/graphene/blob/398727edcee3f8e29c050d2cfdcc7a79d7387e5d/.ci/linux-direct-ubuntu18.04-gcc-glibc231.jenkinsfile#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Name of this file does not match now.
Update: actually, this file can be completely removed now.
</blockquote></details>

OK, I will remove the file .ci/linux-direct-ubuntu18.04-gcc-glibc231.jenkinsfile.
___
*[LibOS/glibc-patches/glibc-2.34.patch, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiBy5LQD6J2MQeRXglt:-MiMXKMQ1rq13oPsWtBA:b-z2hnro) ([raw file](https://github.com/oscarlab/graphene/blob/0b4943e00ed73a0e1117a0d17c22e56675610eba/LibOS/glibc-patches/glibc-2.34.patch#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please. To generate with full hashes, do `git diff --full-index`
</blockquote></details>

No problem. Will do.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jurobystricky, and @mkow)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92aO46R8bduxD3Er6):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Not sure how that happened. Will fix.
</blockquote></details>

I don't think it was indented in the first place. Probably that's just how Reviewable shows commit messages?

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 7 unresolved discussions (waiting on @jurobystricky and @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, 4 unresolved discussions (waiting on @jurobystricky)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2656#-MiNpTpF5Wt1tsM9Ku8e:-MiNpTpG5qQQO1Fj7tEY:bv9puwy) (no related file):*
@jurobystricky, FYI: If you start a comment with "Will do" on Reviewable it automatically puts you into "Working on this" disposition. You never switched yourself to the resolving disposition, so there's a bunch of discussion where you are blocking.
You can either change your disposition there manually or reply with something like "Done"  (it automatically changes your disposition on this particular thread to "resolving").

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2656#-Mi92aO46R8bduxD3Er6):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think it was indented in the first place. Probably that's just how Reviewable shows commit messages?
</blockquote></details>

Ah, I think I know what happened. Someone at Reviewable silently pushed a change to the commit diff file generation to format the text nicer, but this caused a non-empty diff if a PR was already in review before this change (because older commit summaries was generated with the old formatting). So, nothing on our side to fix.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`apps.LTP.writev07` timed out, known issue)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (now `apps.LTP.fcntl14` timed out...)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2656)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
