### PR TITLE
Allowing application to access the files under current directory without specifying filenames in "allowed_files"

### PR DESCRIPTION
**Pull request by rainfld**
The PR addresses the issue reported at https://github.com/oscarlab/graphene/issues/82

It is to add a feature that allows the application can access the files under the current working directory without specifying the file name with “allowed_files”. This is to handle the cases where some of the applications are dumping logs and other data to the newly generated files under the current directory. There is no way to know their names before the application is running. 

The user could allow the application to access all the files under the current directory by adding the following line in the manifest 

file:sgx.allowed_files.conf = file:.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/176)

### CODE REVIEW

**Comment by chiache** [comment]
Thanks for the patch. The patch makes sense to me and could have been a very useful feature. However, I am slightly worried about the security implication of bypassing security checks in CWD.

The reason that I have hesitated to allow "`file:`" as a target of `sgx.allowed_files` is that this rule can open the door to accessing literally every files under the CWD, even one that mismatches with one of the known checksums. Besides, a lazy user may just use "`file:`" to bypass all checks, even though they shouldn't. Of course, in that case, the user is responsible for his/her wrongdoing, but I wonder if we should open this Pandora's box at all.

Please feel free to dispute the points. I would prefer a full discussion before accepting this patch.

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
So is what you actually need the ability to create a file under a given directory from SGX?  And this is not currently allowed, right?

I'd rather apply least privilege principle here.  Can we just have an option like, allow creation of a new allowed file that does not exist?

**Comment by chiache** [comment]
That's not the problem. Creating new files in a directory whitelisted as "allowed files" is already permitted. What's in question is whether we should allow assigning the whole CWD (a.k.a., "file:") to a whitelisting rule, similar to a DMZ.

**Comment by donporter** [comment]
Right, but the motivating problem is creation of files for which it is hard to predict the name.

I think the solution proposed is overly permissive; I'm wondering if we can address the problem with a more precise rule.

**Comment by dimakuv** [comment]
I agree with @chiache that allowing CWD is plain dangerous.

@rainfld, what is the particular application that creates files under the current directory? Are there options to dump new files under a subdir? Well-behaved applications usually allow to change the default directory for logs/dumps.

**Comment by rainfld** [comment]
The motivation of this PR has already been address in the PR https://github.com/oscarlab/graphene/pull/182

I think we can close this unless there is a usage requiring this change.

**Comment by rainfld** [comment]
The problem this PR tries to address has already been resolved by https://github.com/oscarlab/graphene/pull/182

Close this for now. If we see any potential usages for this feature, re-open in future.

**Pull request closed without merging**
