### PR TITLE
refactoring pal signer

### PR DESCRIPTION
**Pull request by yamahata**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/984)

### CODE REVIEW

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. jenkins aborted.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins please. LTP sigpending02,1 failure

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`sigpending02` failed, haven't seen this error in a while)

**Pull request merged**
