### PR TITLE
[LibOS/PAL] Memory corruption fixes

### LINKED ISSUE #431: Intermittent memory corruption during shared_object regression test
The Shim regression tests shared_object has an intermittent memory corruption that manifests as a hang.

This can typically be reproduced on the Linux host - with or without DEBUG=1.  Commit 478130abe388e79ac6c089871b88d7c0358ea806 (master at the time).

The easiest way is to just run as many as 40 times in gdb: 
```
gdb --args ~/path/to/graphene/Runtime/pal-Linux ./shared_object
```

The particular corruption varies, but this one is most common:

```
(gdb) r
Starting program: /playpen/porter/github/graphene8/Runtime/pal-Linux ./shared_object

Program received signal SIGTRAP, Trace/breakpoint trap.
__check_pending_event () at db_exception.c:260
260	    assert(tcb);
(gdb) bt
#0  __check_pending_event () at db_exception.c:260
#1  0x00007f81829d3343 in DkVirtualMemoryAlloc (addr=<optimized out>, size=262144, alloc_type=<optimized out>, prot=<optimized out>) at db_memory.c:57
#2  0x00007f8182785355 in init_brk_region (brk_region=0x7f8182bd4000) at sys/shim_brk.c:120
#3  0x00007f818274324a in init_brk_from_executable (exec=0x7f80829aa708) at elf/shim_rtld.c:1529
#4  0x00007f81827431a6 in init_loader () at elf/shim_rtld.c:1507
#5  0x00007f8182746da0 in shim_init (argc=1, args=0x7ffd388a82b8, return_stack=0x7ffd388a82a8) at shim_init.c:767
#6  0x00007f8182779a76 in shim_start () from ../../../../Runtime/libsysdb.so
#7  0x00007ffd388a82b0 in ?? ()
#8  0x0000000000000001 in ?? ()
#9  0x00007f8182beb1f0 in mem_pool ()
#10 0x0000000000000000 in ?? ()
(gdb) q
```

The particular assertion that is getting blown is that the pal tcb appears to be 0; I verified that, for some strange reason, the gs register is set to zero.

This is as far as I got before timing out, but this is causing some intermittent jenkins issues.

### LINKED ISSUE #665: [Pal/Linux] _DkGetAvailableUserAddressRange() returns incorrect address range
Debug vma dump:
```
[0x7f7dadd60000-0x7f7dadd71000] prot=00000003 flags=00000022 offset=0 (internal) comment=slab
[0x7f7dadd71000-0x7f7dadd73000] prot=00000003 flags=00000022 offset=0 (internal) comment=vma
[0x7f7ead897000-0x7f7eada98040] prot=00000000 flags=00000022 offset=0 (unmapped) comment=exec
[0x7f7eada99000-0x7f7eadd73000] prot=00000001 flags=00000022 offset=0 (internal) comment=LibOS
...
[     1] @ USER range: 0x10000-0x7f7dadd73000
```

This line seems to be the culprit:
`*end   = (PAL_PTR) end_addr - USER_ADDRESS_RESERVED;`

`USER_ADDRESS_RESERVED` is the offset by which the end address is wrong.

### PR DESCRIPTION
**Pull request by omeg**
## Affected components

- [ ] README and global configuration
- [x] Linux PAL
- [ ] SGX PAL
- [x] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
This PR addresses several memory corruption issues (#431).
We prevent LibOS from being overwritten by adding its memory range to the vma bookkeeping.
We prevent PAL from being overwritten by properly respecting the user memory range during initial brk allocation.

Fixes #431, fixes #665.

## How to test this PR? 
Run the regression and LTP tests.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/716)

### CODE REVIEW

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by mkow** [comment]
@omeg Please fix warnings showing up on SGX (we build on Jenkins with `WERROR=1` specified to make).

Example warning: (there are more of them)
```
enclave_framework.c: In function 'load_trusted_file':
../../../lib/api.h:45:10: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       _a < _b ? _a : _b; })
          ^
enclave_framework.c:318:33: note: in expansion of macro 'MIN'
         uint64_t mapping_size = MIN(tf->size - offset, TRUSTED_STUB_SIZE);
```

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by donporter** [comment]
Not sure if you can see the Jenkins logs: 


Basic Bootstrapping:
[92m[Success       ][0m Basic Bootstrapping
[92m[Success       ][0m One Argument Given
[92m[Success       ][0m Five Arguments Given
[93m[Fail          ][0m 2 page child binary
Makefile:61: recipe for target 'regression' failed
make: *** [regression] Error 255

**Comment by mkow** [comment]
Retest Jenkins please

**Comment by mkow** [comment]
Retest Jenkins-Debug please

**Comment by mkow** [comment]
Retest Jenkins-Debug please.
I also couldn't reproduce this failure outside of Jenkins. Let's see if it reliably fails there.

**Comment by omeg** [comment]
Retest Jenkins-Debug please

**Comment by dimakuv** [comment]
Retest Jenkins please

**Pull request merged**
