### PR TITLE
[LTP] Enable running LTP on Fedora

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

This PR enables running LTP on Fedora. (also using #1470)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1617)

### CODE REVIEW

**Comment by stefanberger** [comment]
I have to remove a couple of directories from ltp to be able to compile it on F31. There's a separate PR for this already.

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
