### PR TITLE
Misc fixes around Linux access mode flags

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Please check each commit for description. Commit-by-commit review suggested.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: 0 of 33 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Pal/include/pal/pal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifeTKF8SrLxSPB66HW:-MifeTKF8SrLxSPB66HX:b797jv2) ([raw file](https://github.com/oscarlab/graphene/blob/e1f715ed0d878778aa4ceb89e070e8d0b2ca5cdb/Pal/include/pal/pal.h#L76)):*
> ```objc
> 
> #define SET_HANDLE_TYPE(handle, T) init_handle_hdr(HANDLE_HDR(handle), PAL_TYPE_##T)
> #define IS_HANDLE_TYPE(handle, T)  (HANDLE_HDR(handle)->type == PAL_TYPE_##T)
> ```

Since we're touching this, can we please remove these two macros? In a separate commit or merged into the last commit in this series.

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, 27 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifbhJe0LEI8XeMVwdi):*
>once it's supported

Do we want to support it, btw? I asked about append in PAL some time ago (for things like multiple processes logging to a file) and the response (by @dimakuv? I'm not 100% sure) was that we want writes to be at absolute offsets and ideally, file offsets should be synchronized using IPC. (But having attempted that, I think append in PAL would be much more practical).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, 27 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_flags_conv.h, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifrimIEK5Sz6NpOwOC:-MifrimIEK5Sz6NpOwOD:b-b327rn) ([raw file](https://github.com/oscarlab/graphene/blob/99e12bd95125be90f0ace370f9e905e332de3241/LibOS/shim/include/shim_flags_conv.h#L4)):*
> ```objc
> /* Copyright (C) 2020 Invisible Things Lab
>  *                    Michał Kowalczyk <mkow@invisiblethingslab.com>
>  * Copyright (C) 2021 Invisible Things Lab
> ```

Should be Intel ;)
___
*[LibOS/shim/include/shim_flags_conv.h, line 50 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifvsA18Z1xD7mFgUAY:-MifvsA18Z1xD7mFgUAZ:bvjsi12) ([raw file](https://github.com/oscarlab/graphene/blob/d249a7fb82208f49e9685f8d1ed5c91daff87ed9/LibOS/shim/include/shim_flags_conv.h#L50)):*
> ```objc
>     }
>     if (access & O_APPEND) {
>         /* Currently PAL does not support appending. */
> ```

Shouldn't we `BUG()`/exit with error here?
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-Mifw-VFCqEY8naLTkYA:-Mifw-VFCqEY8naLTkYB:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d249a7fb82208f49e9685f8d1ed5c91daff87ed9/Pal/include/host/Linux-common/pal_flags_conv.h#L4)):*
> ```objc
> /* Copyright (C) 2020 Invisible Things Lab
>  *                    Michał Kowalczyk <mkow@invisiblethingslab.com>
>  * Copyright (C) 2021 Invisible Things Lab
> ```

ditto

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: 7 of 33 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifbhJe0LEI8XeMVwdi):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>once it's supported

Do we want to support it, btw? I asked about append in PAL some time ago (for things like multiple processes logging to a file) and the response (by @dimakuv? I'm not 100% sure) was that we want writes to be at absolute offsets and ideally, file offsets should be synchronized using IPC. (But having attempted that, I think append in PAL would be much more practical).
</blockquote></details>

I'll reword this at rebase (to "if it's ever supported").
___
*[LibOS/shim/include/shim_flags_conv.h, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifrimIEK5Sz6NpOwOC:-MigW_Js5noGwzRMaO2z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99e12bd95125be90f0ace370f9e905e332de3241/LibOS/shim/include/shim_flags_conv.h#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be Intel ;)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_flags_conv.h, line 50 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifvsA18Z1xD7mFgUAY:-MigXJWA-uhpIFcDNxy1:b-p3h786) ([raw file](https://github.com/oscarlab/graphene/blob/d249a7fb82208f49e9685f8d1ed5c91daff87ed9/LibOS/shim/include/shim_flags_conv.h#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we `BUG()`/exit with error here?
</blockquote></details>

Cannot. We never check if `O_APPEND` is set, and it kind of works for 1 process, so this would probably break some workloads.
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-Mifw-VFCqEY8naLTkYA:-MigWZUw9Asbsy5KV9BF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d249a7fb82208f49e9685f8d1ed5c91daff87ed9/Pal/include/host/Linux-common/pal_flags_conv.h#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifeTKF8SrLxSPB66HW:-MigVz7J9Q3xJ8r7PHje:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e1f715ed0d878778aa4ceb89e070e8d0b2ca5cdb/Pal/include/pal/pal.h#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're touching this, can we please remove these two macros? In a separate commit or merged into the last commit in this series.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_pipes.c, line 395 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MisYNFJ2rDI__fgHVB8:-MisYNFKCkn2VcuTZvZc:b-icvip1) ([raw file](https://github.com/oscarlab/graphene/blob/9de59b2721371466c6dcfeaf090a501467592696/Pal/src/host/Linux/db_pipes.c#L395)):*
> ```C
>     attr->handle_type  = HANDLE_HDR(handle)->type;
>     attr->nonblocking  = HANDLE_HDR(handle)->type == PAL_TYPE_PIPEPRV ? handle->pipeprv.nonblocking
>                                                          : handle->pipe.nonblocking;
> ```

this is wrongly aligned now
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 498 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MisZGSvCtAPLO47A18h:-MisZGSvCtAPLO47A18i:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/9de59b2721371466c6dcfeaf090a501467592696/Pal/src/host/Linux-SGX/db_pipes.c#L498)):*
> ```C
>     attr->handle_type  = HANDLE_HDR(handle)->type;
>     attr->nonblocking  = HANDLE_HDR(handle)->type == PAL_TYPE_PIPEPRV ? handle->pipeprv.nonblocking
>                                                          : handle->pipe.nonblocking;
> ```

ditto

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3, 3 of 27 files at r4, 24 of 24 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifbhJe0LEI8XeMVwdi):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll reword this at rebase (to "if it's ever supported").
</blockquote></details>

Yes, I wanted to have writes at absolute offsets and sync these offsets among processes. But @pwmarcz has much more experience with writing to files now, so if he thinks that `PAL_ACCESS_APPEND` is wanted, we should implement it.
___
*[-- commits, line 27 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MiuBkZ32i62sumPoaAD):*
Please add a commit message body here with `Also remove SET_HANDLE_TYPE and IS_HANDLE_TYPE macros for readability.`
___
*[Pal/include/pal/pal.h, line 113 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MiuCVWG2NZtqXjh_FZX:-MiuCVWG2NZtqXjh_FZY:b69rye7) ([raw file](https://github.com/oscarlab/graphene/blob/9de59b2721371466c6dcfeaf090a501467592696/Pal/include/pal/pal.h#L113)):*
> ```objc
> #define PAL_IDX_POISON         ((PAL_IDX)-1) /* PAL identifier poison value */
> #define PAL_GET_TYPE(h)        (HANDLE_HDR(h)->type)
> #define UNKNOWN_HANDLE(handle) (PAL_GET_TYPE(handle) >= PAL_HANDLE_TYPE_BOUND)
> ```

BTW, in the future we should also remove these redundant macros `PAL_GET_TYPE` and `UNKNOWN_HANDLE`.
___
*[Pal/src/db_events.c, line 16 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MiuCecm64prmaHnb7st:-MiuCecm64prmaHnb7su:b7z9cod) ([raw file](https://github.com/oscarlab/graphene/blob/9de59b2721371466c6dcfeaf090a501467592696/Pal/src/db_events.c#L16)):*
> ```C
> 
> void DkEventSet(PAL_HANDLE handle) {
>     assert(handle && HANDLE_HDR(handle)->type == PAL_TYPE_EVENT);
> ```

Hurray, I can grep again! I hated these magic "concatenate strings" macros.

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 24 of 24 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 12 files at r10, 4 of 6 files at r11, 27 of 27 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2674#-MifbhJe0LEI8XeMVwdi):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I wanted to have writes at absolute offsets and sync these offsets among processes. But @pwmarcz has much more experience with writing to files now, so if he thinks that `PAL_ACCESS_APPEND` is wanted, we should implement it.
</blockquote></details>

Done at rebase.
___
*[-- commits, line 27 at r8](https://reviewable.io/reviews/oscarlab/graphene/2674#-MiuBkZ32i62sumPoaAD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a commit message body here with `Also remove SET_HANDLE_TYPE and IS_HANDLE_TYPE macros for readability.`
</blockquote></details>

I did this at rebase, but with a small tweak :]

**Review by pwmarcz — APPROVED** [review]
> Reviewed 2 of 12 files at r10, 4 of 6 files at r11, 27 of 27 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2674)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
