### PR TITLE
LibOS: Remove unnecessary asm from test case

### PR DESCRIPTION
**Pull request by stefanberger**
Remove unnecessary asm from test case

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)

### CODE REVIEW

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1955#-MLjCpy26DJaMR0NnrcQ:-MLjCpy38Mp_Do9E8rqa:bxz0g2u) ([raw file](https://github.com/oscarlab/graphene/blob/367946d3992eec40d0d1fa67f774ea85e3a0b7d5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L31)):*
> ```C
> 
>     while (iterations != 0)
>         iterations--;
> ```

This now results in the following code:
```
00000000004015c0 <dowork>:
static void* dowork(void* args) {
  4015c0:       48 83 ec 18             sub    $0x18,%rsp
    volatile uint64_t iterations = *(uint64_t*)args;
  4015c4:       48 8b 07                mov    (%rdi),%rax
  4015c7:       48 89 44 24 08          mov    %rax,0x8(%rsp)
    while (iterations != 0)
  4015cc:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015d1:       48 85 c0                test   %rax,%rax
  4015d4:       74 22                   je     4015f8 <dowork+0x38>
  4015d6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  4015dd:       00 00 00 
        iterations--;
  4015e0:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015e5:       48 83 e8 01             sub    $0x1,%rax
  4015e9:       48 89 44 24 08          mov    %rax,0x8(%rsp)
    while (iterations != 0)
  4015ee:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015f3:       48 85 c0                test   %rax,%rax
  4015f6:       75 e8                   jne    4015e0 <dowork+0x20>

```

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1955#-MLjCpy26DJaMR0NnrcQ:-MLjSt5b4Cuh-bKiUwRW:b1g7r0m) ([raw file](https://github.com/oscarlab/graphene/blob/367946d3992eec40d0d1fa67f774ea85e3a0b7d5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L31)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This now results in the following code:
```
00000000004015c0 <dowork>:
static void* dowork(void* args) {
  4015c0:       48 83 ec 18             sub    $0x18,%rsp
    volatile uint64_t iterations = *(uint64_t*)args;
  4015c4:       48 8b 07                mov    (%rdi),%rax
  4015c7:       48 89 44 24 08          mov    %rax,0x8(%rsp)
    while (iterations != 0)
  4015cc:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015d1:       48 85 c0                test   %rax,%rax
  4015d4:       74 22                   je     4015f8 <dowork+0x38>
  4015d6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  4015dd:       00 00 00 
        iterations--;
  4015e0:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015e5:       48 83 e8 01             sub    $0x1,%rax
  4015e9:       48 89 44 24 08          mov    %rax,0x8(%rsp)
    while (iterations != 0)
  4015ee:       48 8b 44 24 08          mov    0x8(%rsp),%rax
  4015f3:       48 85 c0                test   %rax,%rax
  4015f6:       75 e8                   jne    4015e0 <dowork+0x20>

```
</blockquote></details>

I think it doesn't need to result in the loop being actually emitted, but this is just for manual debugging, so I'm fine with doing this with a simple volatile loop.

@stefanberger You inserted this comment as blocking, please change your disposition :)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

**Comment by boryspoplawski** [comment]
Jenkins test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955#-:-MLlA5NZ137k12ocDWsy:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1955)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
