### PR TITLE
[CI] Add back gitignore-test to all configurations

### PR DESCRIPTION
**Pull request by pwmarcz**
Removed by mistake in abe3d77552cd8b0579d4687cd93c860188d4d2f1.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1971#-MMGWRe39mSiFeAvOOu_:-MMGWRe39mSiFeAvOOua:b-7jb2dg) (no related file):*
In the commit message, could you change the commit hash to commit one-liner? We still need to edit the commit history at some point to drop those binary blobs which take 700MB :/ (which will change all the hashes)

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1971#-MMGWRe39mSiFeAvOOu_:-MMGf1NX2wtPQ89F1vQi:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In the commit message, could you change the commit hash to commit one-liner? We still need to edit the commit history at some point to drop those binary blobs which take 700MB :/ (which will change all the hashes)
</blockquote></details>

Done.

---

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @woju)

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test failed)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1971#-MMK6Riq6ypTfNek4MvT:-MMK6Riq6ypTfNek4MvU:b1e7myt) (no related file):*
Oops, we merged something in the meantime that gitignore-test complains about:
```
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? LibOS/shim/test/regression/pthread_set_get_affinity
?? LibOS/shim/test/regression/sched_set_get_affinity
```

@pwmarcz Could you amend this PR to git-ignore these files? (Add them in `LibOS/shim/test/regression/.gitignore`)

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1971#-MMK6Riq6ypTfNek4MvT:-MMKgjA7EXJJfBYUx0ds:bdnmc99) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, we merged something in the meantime that gitignore-test complains about:
```
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? LibOS/shim/test/regression/pthread_set_get_affinity
?? LibOS/shim/test/regression/sched_set_get_affinity
```

@pwmarcz Could you amend this PR to git-ignore these files? (Add them in `LibOS/shim/test/regression/.gitignore`)
</blockquote></details>

Done, let's see if Jenkins passes now.

---

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (`poll_closed_fd` LibOS test failed; IIUC, this will be fixed by Borys's #1949)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (poll_closed_fd LibOS test failed; IIUC, this will be fixed by Borys's #1949б second time already...)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1971)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
