### PR TITLE
[CI] Test the build of graphene-ipc module

### PR DESCRIPTION
**Pull request by donporter**
Build the graphene IPC kernel module in Jenkins, to curb risk of bitrot.

## Affected components

- [ ] README and global configuration
- [X] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? (if applicable)

Run Jenkins

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/703)

### CODE REVIEW

**Comment by donporter** [comment]
Jenkins, please retest SGX.  gcc hit the checkpoint address conflict bug

**Comment by donporter** [comment]
Jenkins, please retest Jenkins-SGX. gcc hit the checkpoint address conflict bug

**Comment by donporter** [comment]
Jenkins, retest Jenkins-SGX please (gcc hit the checkpoint address conflict bug)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (the pipeline info was garbage collected)

**Pull request merged**
