### PR TITLE
[LibOS] Add EPOLLET implementation

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Description of implementation in the code.

## How to test this PR? 
Added a new test. ~Currently does not work due to #1717~ Added an if to work even with that bug.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2338)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2338)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_handle.h, line 319 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzQhm-0Cqm5dKdojO:-MZkzQhm-0Cqm5dKdojP:b9673o) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_handle.h#L319)):*
> ```objc
>     bool is_dir;
>     bool needs_et_poll_in;
>     bool needs_et_poll_out;
> ```

Maybe moves these two under `epolls` field? And add a comment like `/* mark handle as edge-triggered-epoll-ready for read */` and `/* ... for write */`
___
*[LibOS/shim/include/shim_internal.h, line 387 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkyvJb1BkZaPPmS0ml:-MZkyvJb1BkZaPPmS0mm:b-ki7k2e) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L387)):*
> ```objc
>  * \param ret return value from last operation
>  * \param in `true` if last operation was of input type (e.g. `read`)
>  * \param was_partial `true` if last operation was did not fill the whole buffer
> ```

Typo: remove `was`
___
*[LibOS/shim/include/shim_internal.h, line 393 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkz6NrBX_xdrdzpwyF:-MZkz6NrBX_xdrdzpwyG:b4wq8gg) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L393)):*
> ```objc
>  * operation, \p in should indicate if that was an input operation (e.g. `read` or `accept`) or
>  * output (e.g. `write`), \p was_partial - if that operation was done partially (e.g. `read` did not
>  * fill the while buffer).
> ```

`while` -> `whole`
___
*[LibOS/shim/include/shim_internal.h, line 399 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzFf08P4YsLuMZB5r:-MZkzFf08P4YsLuMZB5s:b-2ahqky) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L399)):*
> ```objc
>  * Linux. Due to this we have a "hacky" approach: if a handle is successfully waited for on some
>  * epoll instance using `EPOLLET` semantics, it's marked as not epollet-ready and then is not
>  * included in further `EPOLLET` waits. To mark it back as epollet-ready, a operation must be
> ```

`a operation` -> `an operation`
___
*[LibOS/shim/include/shim_internal.h, line 400 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzJua9mc4gU7RJjeb:-MZkzJua9mc4gU7RJjec:buo50hc) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L400)):*
> ```objc
>  * epoll instance using `EPOLLET` semantics, it's marked as not epollet-ready and then is not
>  * included in further `EPOLLET` waits. To mark it back as epollet-ready, a operation must be
>  * observed, which either returns `-EAGAIN` (non-blocking operation which cannot be compleated atm)
> ```

`completed`
___
*[LibOS/shim/src/sys/shim_socket.c, line 1137 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl1KPY6gaJY_YzB59W:-MZl1KPZC4PCSgIkZHPv:b-pknn9j) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/src/sys/shim_socket.c#L1137)):*
> ```C
>         ret = DkStreamWrite(pal_hdl, 0, &this_size, bufs[i].iov_base, uri);
>         ret = ret == -PAL_ERROR_STREAMEXIST ? -ECONNABORTED : pal_to_unix_errno(ret);
>         maybe_epoll_et_trigger(hdl, ret, /*in=*/false, !ret ? this_size < bufs[i].iov_len : false);
> ```

Non-blocking, for consistency: `!ret` -> `ret == 0`
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl2WNq8PCVJ7SY3uAf:-MZl2WNq8PCVJ7SY3uAg:b-lqpue9) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/test/regression/epoll_epollet.c#L14)):*
> ```C
>         errx(1, "invalid arguments count");
>     }
>     int expected_events = EPOLLIN;
> ```

This should be `uint32_t`
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl2Zwf3uulyKMzxC9E:-MZl2Zwf3uulyKMzxC9F:bghh1wf) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/test/regression/epoll_epollet.c#L46)):*
> ```C
> 
>     memset(&event, '\0', sizeof(event));
>     if (epoll_wait(efd, &event, 1, 10) != 1) {
> ```

Why this timeout of `10` ms?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2338)* status: 8 of 11 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_handle.h, line 319 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzQhm-0Cqm5dKdojO:-MZnsP6K7alswPbERBjy:bcsd3ow) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_handle.h#L319)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe moves these two under `epolls` field? And add a comment like `/* mark handle as edge-triggered-epoll-ready for read */` and `/* ... for write */`
</blockquote></details>

I moved them here to reduce the size of this struct, but I guess that's not really important.
Done.
___
*[LibOS/shim/include/shim_internal.h, line 387 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkyvJb1BkZaPPmS0ml:-MZnxbSSDWQcNzGry8L0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L387)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: remove `was`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 393 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkz6NrBX_xdrdzpwyF:-MZnxefDAFu5VSBaVJDw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L393)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`while` -> `whole`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 399 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzFf08P4YsLuMZB5r:-MZnxknACXyj895pS21I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L399)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`a operation` -> `an operation`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 400 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZkzJua9mc4gU7RJjeb:-MZnxn--9woQMyUlBHn8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/include/shim_internal.h#L400)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`completed`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1137 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl1KPY6gaJY_YzB59W:-MZnyphp1T3D5DT-UiJg:bafbyxf) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/src/sys/shim_socket.c#L1137)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Non-blocking, for consistency: `!ret` -> `ret == 0`
</blockquote></details>

I did it this way to avoid lane wrapping.
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl2WNq8PCVJ7SY3uAf:-MZnzDeDCMwjQlOT-MNd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/test/regression/epoll_epollet.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be `uint32_t`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2338#-MZl2Zwf3uulyKMzxC9E:-MZnziL7Bk_rPxAHYwrB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0063341d8cc6bd9786116dedca995ea3e6bd8b24/LibOS/shim/test/regression/epoll_epollet.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this timeout of `10` ms?
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2338)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
