### PR TITLE
PAL: Compile DkSegmentRegister only on x86_64 and adapt test case

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Compile the DkSegmentRegister function only on x86_64 and adapt a test case looking for this symbol.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1619)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (untar of cJON failed? either broken download or smth with hard drive...)

**Pull request merged**
