### PR TITLE
Stricten manifest size-str parsing

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

And additionally remove some now-outdated warnings.

## How to test this PR? 

Try putting invalid entries in the manifest and check if/how parsing fails.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`apps.LTP.sendfile09` timed out, known issue)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[common/src/string/atoi.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MhsWIGS1BFFUak66KLB:-MhxGpmF9YEpM9PajBQH:bt79afr) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/common/src/string/atoi.c#L135)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can we switch to `str_to_ulong` here? It would catch more undesirable inputs such as `""`, `"   123"`, or `"-1"`.

I guess one problem is it doesn't support arbitrary base, but I'm not sure if we want to support that? (e.g. `0x1000M` or `010G`)
</blockquote></details>

Ok, I started implementing the change, but I'll need to wait for #2657 to have the `OVERFLOWS` macro (because the types here don't match).

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[common/src/string/atoi.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MhsWIGS1BFFUak66KLB:-MiN5ywcBHADvIgIpTju:b-g74l9f) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/common/src/string/atoi.c#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I started implementing the change, but I'll need to wait for #2657 to have the `OVERFLOWS` macro (because the types here don't match).
</blockquote></details>

@mkow #2657 was merged, you can rebase your PR.
___
*[LibOS/shim/src/shim_init.c, line 295 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN65jF6s2l_sJY9AcB:-MiN65jF6s2l_sJY9AcC:b-6h7lsj) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/LibOS/shim/src/shim_init.c#L295)):*
> ```C
>                              &stack_size);
>     if (ret < 0) {
>         log_error("Cannot parse \'sys.stack.size\'");
> ```

You can also remove `\` before `'`
___
*[LibOS/shim/src/sys/shim_brk.c, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6E51BHXiYvro1xh_:-MiN6E51BHXiYvro1xha:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/LibOS/shim/src/sys/shim_brk.c#L51)):*
> ```C
>                              &brk_max_size);
>     if (ret < 0) {
>         log_error("Cannot parse \'sys.brk.max_size\'");
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_main.c, line 704 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6F9s6tKnnzpMX5z_:-MiN6F9s6tKnnzpMX5za:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/db_main.c#L704)):*
> ```C
>                              /*defaultval=*/0, &g_pal_internal_mem_size);
>     if (ret < 0) {
>         log_error("Cannot parse \'loader.pal_internal_mem_size\'");
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 493 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6Fxj4q7e7x-SBOAK:-MiN6Fxj4q7e7x-SBOAL:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/db_misc.c#L493)):*
> ```C
>     ret = toml_string_in(g_pal_state.manifest_root, "sgx.ra_client_spid", &ra_client_spid_str);
>     if (ret < 0) {
>         log_error("Cannot parse \'sgx.ra_client_spid\'");
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 867 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6Gh97Qn-98ywsEES:-MiN6Gh97Qn-98ywsEET:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/enclave_framework.c#L867)):*
> ```C
>                          &file_check_policy_str);
>     if (ret < 0) {
>         log_error("Cannot parse \'sgx.file_check_policy\'");
> ```

ditto

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 6 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: 3 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[common/src/string/atoi.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MhsWIGS1BFFUak66KLB:-MiOA7bc75HAIejeKEmR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/common/src/string/atoi.c#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow #2657 was merged, you can rebase your PR.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 295 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN65jF6s2l_sJY9AcB:-MiOCsBc18cdPD-Zo67i:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/LibOS/shim/src/shim_init.c#L295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can also remove `\` before `'`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_brk.c, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6E51BHXiYvro1xh_:-MiOCwaa7y5fo3Gs5I6t:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/LibOS/shim/src/sys/shim_brk.c#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 704 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6F9s6tKnnzpMX5z_:-MiOD3WM8rjY7ceJyTpZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/db_main.c#L704)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 493 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6Fxj4q7e7x-SBOAK:-MiOD96M8ymq7fqFIoJW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/db_misc.c#L493)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 867 at r1](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiN6Gh97Qn-98ywsEES:-MiODHIA4RvQdnKGdbkM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cb8ea8c8a8d724b84d77307806dd93f133de4f95/Pal/src/host/Linux-SGX/enclave_framework.c#L867)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 349 at r2](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiOQmKg5oJGQMXsFRP3:-MiOQmKh0uHkWV-OdCmf:b-6m4hwl) ([raw file](https://github.com/oscarlab/graphene/blob/285959557f31c824e37c7f44321b761f90daf790/common/include/api.h#L349)):*
> ```objc
>  * \param str A string containing a non-negative number. The string may end with "G"/"g" suffix
>  *            denoting value in GBs, "M"/"m" for MBs, or "K"/"k" for KBs.
>  * \param str A string containing a non-negative number. The string may end with "G"/"g" suffix
> ```

Same param is described twice.

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @pwmarcz)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: 13 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[common/include/api.h, line 349 at r2](https://reviewable.io/reviews/oscarlab/graphene/2659#-MiOQmKg5oJGQMXsFRP3:-MiQGw29DbJ1PKvo9X_g:b-834n6i) ([raw file](https://github.com/oscarlab/graphene/blob/285959557f31c824e37c7f44321b761f90daf790/common/include/api.h#L349)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Same param is described twice.
</blockquote></details>

Oops.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 10 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2659)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
