### PR TITLE
[Docs] Update documentation on Protected Files and the PF wrap key

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR was split from #2328. Contains only simple changes to documentation.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/attestation.rst, line 189 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMF5RU53j63IG5eCUl:-MdMF5RU53j63IG5eCUm:b-c7ufqy) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L189)):*
> ```reStructuredText
> DCAP based quote verification).
> 
> The ``/dev/attestation`` pseudo-filesystem also exposes the pseudo-file to set
> ```

`the pseudo-file` -> `a pseudo-file`
___
*[Documentation/attestation.rst, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMEyGA3tDfPx9zsy-s:-MdMEyGA3tDfPx9zsy-t:b-cdq8wd) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L194)):*
> ```reStructuredText
> - ``/dev/attestation/protected_files_key`` pseudo-file can be opened for write
>   access. Typically, it is opened before the actual application runs and filled
>   with they 128-bit key obtained from a remote secret provisioning service.
> ```

`with they 128-bit` -> `with a 128-bit`
___
*[Documentation/attestation.rst, line 406 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMFUdcAgOXpgok8wwH:-MdMFUdcAgOXpgok8wwI:bgil155) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L406)):*
> ```reStructuredText
>   variable is checked only if ``SECRET_PROVISION_CONSTRUCTOR`` is set. The
>   library puts the provisioned key into ``/dev/attestation/protected_files_key``
>   so that Graphene recognizes the provisioned protected-files master key.
> ```

`so that Graphene recognizes the provisioned protected-files master key` -> `so that Graphene recognizes it`

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/attestation.rst, line 189 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMF5RU53j63IG5eCUl:-MdMTaWE6Chxo1n9rNYj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L189)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`the pseudo-file` -> `a pseudo-file`
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMEyGA3tDfPx9zsy-s:-MdMTedb-WUUsgl1yjI2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`with they 128-bit` -> `with a 128-bit`
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 406 at r1](https://reviewable.io/reviews/oscarlab/graphene/2482#-MdMFUdcAgOXpgok8wwH:-MdMTkggCJH7Qg1vu6aR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57bca03c612cba4c745d42e6a3cf60677f39d4a7/Documentation/attestation.rst#L406)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`so that Graphene recognizes the provisioned protected-files master key` -> `so that Graphene recognizes it`
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2482)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
