### PR TITLE
[LibOS] Add simple implementation of `msync` syscall

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
`libundwind` sometimes uses `msync` syscall during unwinding frames to check if a memory address is valid.

## How to test this PR? 
New regression test added (which fails on current master),

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 9 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/bootstrap_cpp.cpp, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8UwpI3hwc2-OFR4xv:-MX8UwpJ4WnLFT_QylYT:b-l84hpq) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.cpp#L4)):*
> ```cpp
> 
> extern "C" void f2() {
>     throw std::runtime_error("test runtime error");
> ```

you should include `<stdexcept>` for this
___
*[LibOS/shim/test/regression/bootstrap_cpp.cpp, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8V9eF82n2V0vb-rIT:-MX8V9eF82n2V0vb-rIU:bz86oni) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.cpp#L7)):*
> ```cpp
> }
> 
> extern "C" void f1();
> ```

Could you explain in the comment what this assembly is testing?
___
*[LibOS/shim/test/regression/bootstrap_cpp.manifest.template, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8VOn6-aWWz3aCdGlO:-MX8VOn78E3Yb9gMIDz7:bugg1dg) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.manifest.template#L6)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib:$(ARCH_LIBDIR):/usr/$(ARCH_LIBDIR)"
> loader.env.LD_PRELOAD = "libunwind.so"
> ```

Please explain this in a comment so that we never accidentally drop this as not needed (I think the test will still "work" if you drop this line?).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/bootstrap_cpp.cpp, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8UwpI3hwc2-OFR4xv:-MX8nSyx04Uil6tonTrN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.cpp#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

you should include `<stdexcept>` for this
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/bootstrap_cpp.cpp, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8V9eF82n2V0vb-rIT:-MX8oQNn5K95WwgbyEHH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.cpp#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain in the comment what this assembly is testing?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/bootstrap_cpp.manifest.template, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2286#-MX8VOn6-aWWz3aCdGlO:-MX8okqjDvea0y-EhrI5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf7a1ecbfe59506c6c4dadfb977e4dafaace03c6/LibOS/shim/test/regression/bootstrap_cpp.manifest.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please explain this in a comment so that we never accidentally drop this as not needed (I think the test will still "work" if you drop this line?).
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by yamahata — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 3 of 9 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 3 of 9 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2286#-MXBZ0WD5XtxiX-Y3CMI:-MXBZ0WD5XtxiX-Y3CMJ:b6hmmuv) (no related file):*
Jenkins-SGX job failed with:
```
self = <test_libos.TC_01_Bootstrap testMethod=test_110_basic_bootstrapping_cpp>
E   AssertionError: timeout (20 s) expired
```

Please check locally that there is no intermittent failure of this test. Maybe just incrementing the timeout suffices?

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2286#-MXBZ0WD5XtxiX-Y3CMI:-MXDhcmx9geqgMqJJvqW:b-2g8d2e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins-SGX job failed with:
```
self = <test_libos.TC_01_Bootstrap testMethod=test_110_basic_bootstrapping_cpp>
E   AssertionError: timeout (20 s) expired
```

Please check locally that there is no intermittent failure of this test. Maybe just incrementing the timeout suffices?
</blockquote></details>

Yeah, seen that, didn't have time to debug earlier.

The issue was lack of `sgx.nonpie_binary` in manifest (on ubunutu16.04 it was non-pie).

---

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (SIGPWR, known IPC issue)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins please (`apps.LTP.kill11` failed, known issue)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2286)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (`exit_group` from LibOS regression timedout, unrelated to this PR)

**Pull request merged**
