### PR TITLE
[LibOS] Remove libsysdb_debug.so

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This shared library was built, but never used anywhere and nobody even knew what is it for.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2031)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2031)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2031)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (unrelated Jenkins restart)

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2031)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-apps please (unrelated Jenkins restart)

**Pull request merged**
