### PR TITLE
[Makefile.rule, Pal/Linux-SGX]: pythonize dependency calculation of manifest

### PR DESCRIPTION
**Pull request by yamahata**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/945)

### CODE REVIEW

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please.

**Comment by yamahata** [comment]
Jenkins, retest this please.
(failure to download glibc source code)

**Comment by yamahata** [comment]
Jenkins, retest this please. lighttpd connection refused.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. (libos regression 201 fork_and_exec faild with self.assertIn('child exited with status: 0', stdout)
No clue left. it works for me locally.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. (libos regression 201 fork_and_exec)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (the slave machine couldn't fetch graphene-tests submodule due to not-main-repo reference)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (the slave machine couldn't fetch graphene-tests submodule due to not-main-repo reference, again...)

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. failure to checkout ltp submodule.

**Comment by dimakuv** [comment]
@yamahata All Jenkins pipelines failed. Could you debug this issue?

**Comment by yamahata** [comment]
Jenkins, retest this please.

**Comment by yamahata** [comment]
Jenkins, retest Jenkins-SGX please. test_libos.TC_30_Syscall.test_52_large_mmap failed

**Comment by dimakuv** [comment]
Oh, this error is because we updated the hash for the merged oscarlab/graphene-tests#36 in this PR. But we forgot to rebase it to the merged https://github.com/oscarlab/graphene/commit/ee3619df4f230f524d27896cc0df84428d5c3a93 which adds Jenkins deps. Sorry for this confusion.

**Pull request merged**
