### PR TITLE
Make the Skeleton PAL buildable again

### PR DESCRIPTION
**Pull request by woachk**
This makes the Skeleton PAL buildable on macOS for the OS-dependent part.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/257)

### CODE REVIEW

**Comment by donporter** [comment]
Very cool!  Thanks for the fixes.  

I assume you are testing this on OS X?

I'd recommend we add something to CI once this is merged to test the build, both on Linux and OS X.

**Comment by donporter** [comment]
Ok to test.

**Comment by woachk** [comment]
@donporter yeah, I'm personally testing on macOS.

PAL on Linux, Linux-SGX and FreeBSD uses ```int _DkCreatePhysicalMemoryChannel (PAL_HANDLE * handle, unsigned long * key)```, with unsigned long*, as does Pal/src/pal_internal.h, which is why the change was done, maybe transitioning those to PAL_NUM* would be a valid choice too. :)

**Comment by donporter** [comment]
Got it.  I'll do a separate PR to normalize this.

**Comment by donporter** [comment]
@woachk I'd like to get this PR landed.  Can I trouble you to rebase onto current master (and drop my merge of master into your branch)?  If CI doesn't pass, I'll take a more careful look at what is going wrong.

**Comment by donporter** [comment]
@woachk Can you resolve the conflict with master that has come up?  I can also do this for you, but I'd rather not "steal" your credit.  Thanks!

**Comment by woachk** [comment]
@donporter Yeah I will.

**Comment by woachk** [comment]
@donporter done.

**Comment by donporter** [comment]
lat_proc exec failure (again).  I'll go ahead and rebase this to master.

**Pull request merged**
