### PR TITLE
[GSC] Fix link to AKS guide in cloud deployment documentation

### PR DESCRIPTION
**Pull request by vahldiek**
## Description of the changes 

We used the wrong link to an AKS guide in our documentation for cloud deployments. This PR changes the link to the correct version.

## How to test this PR? 

Usual Jenkins tests. It is only a documentation change, no source code changes.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1836)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1836)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, test this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1836)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by donporter — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1836)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (Jenkins again failed with `make[1]: write error: stdout
Makefile:13: recipe for target 'distclean' failed`, no idea what's this)

**Pull request merged**
