### PR TITLE
[Pal/Linux-SGX] Remove too noisy deprecation warning from signing tools

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

Unfortunately this warning was triggered too often (including when building tests) and it's not terribly important, so let's just drop it.

## How to test this PR? 

Build regression tests and look at the cleaner logs :)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2011)

### CODE REVIEW

**Review by woju — DISMISSED** [review]
I'll revert this as soon as I'll have working tests from installed graphene.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2011#-:-MNewIeK8H6e2vKMj552:b-60ayxw)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
Since Woju approve approved this PR, I'm also approving.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2011#-:-MNh87rzBG8alcWVRano:b7w3tqw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2011)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2011)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
