### PR TITLE
make Shim test benchmark work

### PR DESCRIPTION
**Pull request by yamahata**
This patch series makes shim/test/benchmark build and run.
+ some minor trivial cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/273)

### CODE REVIEW

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
I'm going to hand this one off to @chiache , as this looks primarily like a build issue.

Would it make sense to add any of these to CI, so they stay fixed?

**Comment by yamahata** [comment]
Hi, I can't see the jenkins failure log because it requires login.
Is the result closed or public?

**Comment by donporter** [comment]
We can give you access to see the logs if needed.

**Comment by donporter** [comment]
@yamahata Please go ahead and squash this PR into one commit, if you don't mind.

**Comment by donporter** [comment]
This CI failure is on a test that current master should have addressed.  I'll rebase and we can try again.

**Comment by donporter** [comment]
@yamahata Please go ahead and squash this into one commit.

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by mkow** [comment]
Retest this please

**Comment by chiache** [comment]
test this please.

**Pull request merged**
