### PR TITLE
PAL: Use executables-x86_64 for x86_64-specific executables

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

Use executables-x86_64 for x86_64-specific executables

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1677)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins failed with:
```
I../../protected-files -DCRYPTO_USE_MBEDTLS -D_POSIX_C_SOURCE=200809L -fPIC   -c -o cJSON.o cJSON.c
cJSON.c:58:10: fatal error: cJSON.h: No such file or directory
 #include "cJSON.h"
          ^~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'cJSON.o' failed
```

I thought we fixed this...

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please

**Pull request merged**
