### PR TITLE
LibOS: Compile and run bootstrap_cpp only on x86_64

### PR DESCRIPTION
**Pull request by stefanberger**
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)

### CODE REVIEW

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXczmLA0WkCGYVdmP7s:bpc6861) (no related file):*
Not blocking, but don't you want to add ppc asm to that test? It basically calls another function saving a caller-saved register on stack. Caveat: needs a proper cfi. The purpose of this test is to test c++ unwinding routines, which did some unexpected things (at least on x64).

---

**Comment by boryspoplawski** [comment]
Jenkins, test this please

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXd0SXM0Jz2oyoc3EZu:-MXd0SXN0_fn9Ctzv2Sk:bqbohff) (no related file):*
TODO: update commit message at rebase (`[LibOS]` tag)

---

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXdnVce1oUtjd7Mj0_g:b-e98xzv) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking, but don't you want to add ppc asm to that test? It basically calls another function saving a caller-saved register on stack. Caveat: needs a proper cfi. The purpose of this test is to test c++ unwinding routines, which did some unexpected things (at least on x64).
</blockquote></details>

+1 (if you have time for this, Stefan)

---

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXgXj-366F0Fkjno4Sl:big0gfo) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 (if you have time for this, Stefan)
</blockquote></details>

This would have to live in my branch...

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXgZmOD8o8xJUDnmdBl:b-lrius5) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This would have to live in my branch...
</blockquote></details>

Since this are tests, not the core, I'm fine with keeping it here (if you want to submit such a patch, of course).
cc @mkow @dimakuv 

---

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXiYIwk7rRQMY-8mjFP:b-pcmzun) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since this are tests, not the core, I'm fine with keeping it here (if you want to submit such a patch, of course).
cc @mkow @dimakuv 
</blockquote></details>

Same here, I think it's ok to merge it here. But I'd leave the final decision to Stefan :)

---

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXip1qv5gh9-TXmW61D:bfmgzts) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Same here, I think it's ok to merge it here. But I'd leave the final decision to Stefan :)
</blockquote></details>

Let me defer this. I think we would need to discuss whether, when, and how to merge the ppc64 port in general. I don't want to hold up your development with it if ppc64 was to break on Travis, which I think should run as part of every PR then as well.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXczmL9B5ioHukiNcdU:-MXlKXeh14RfvCKNfich:b-11hobw) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Let me defer this. I think we would need to discuss whether, when, and how to merge the ppc64 port in general. I don't want to hold up your development with it if ppc64 was to break on Travis, which I think should run as part of every PR then as well.
</blockquote></details>

Alright 

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2295#-MXd0SXM0Jz2oyoc3EZu:-MXlVNxq6GRovpn2cRl1:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: update commit message at rebase (`[LibOS]` tag)
</blockquote></details>

Done.

---

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2295)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
