### PR TITLE
Remove trailing blanks

### PR DESCRIPTION
**Pull request by mkow**
## Affected components

- [X] README and global configuration
- [X] Linux PAL
- [X] SGX PAL
- [X] FreeBSD PAL
- [X] Common PAL code
- [X] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)
This is the first patch in a series of patches cleaning up and unifying the formatting of our codebase, which will be finished with a patch that enables and enforces `clang-format` checks on Jenkins (see #539).

After we merge this PR we should stop accepting trailing blanks in reviews (though it won't yet be enforced in CI).

I tried to change only files which are part of our codebase and was already adapted by us, so e.g. shim/test/apps directory is mostly skipped.

## How to test this PR? (if applicable)
Run `grep -Ir '[[:blank:]]$' .` and see if there are any more occurrences that I should also include.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/664)

### CODE REVIEW

**Comment by mkow** [comment]
> I believe you generated this patch by the command, not by hand.

Not by hand, but also not by a single command. I just opened&saved all the files in sublime-text with `trim_trailing_white_space_on_save` set to true. So it was something like `subl **/*.{c,h,py,md,S,sh}` + "Save All".

I was too lazy to fight with `sed` ;) In the future clang-format will ensure proper formatting, which also includes clearing trailing blanks.

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by dimakuv** [comment]
Retest Jenkins-SGX please

**Comment by mkow** [comment]
Retest Jenkins-Debug please

**Pull request merged**
