### PR TITLE
[LibOS, Pal/{Linux,Linux-SGX}] Remove DkObjectsWaitAny()

### PR DESCRIPTION
**Pull request by dimakuv**
## Affected components

- [ ] README and global configuration
- [x] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Now Graphene supports an improved version of `DkObjectsWaitAny()` with correct polling semantics -- `DkObjectsWaitEvents()`. This makes `DkObjectsWaitAny()` obsolete. This commit removes `DkObjectsWaitAny()` and replaces it with:
- `DkSynchronizationObjectWait()` to wait on a single synchronization object like mutex or event.
- `DkStreamsWaitEvents()` to wait on stream-like objects (this is the renamed `DkObjectsWaitEvents()`).

The corresponding tests are fixed to use the new PAL interfaces. Also, IPC helper and Async helper threads are significantly refactored to make better use of `DkStreamsWaitEvents()`.

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1244)

### CODE REVIEW

**Comment by dimakuv** [comment]
**I want to test this PR at least 5 times -- it changed a lot of interfaces. Need to be sure I didn't introduce non-deterministic failures.**

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX please (`exec` LibOS test failed)

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run 1/5: all tests passed)

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run 2/5: all tests passed)

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run 3/5: Jenkins-SGX failed on `vfork_and_exec`)

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run 4/5: Jenkins failed due to "no space left on device", David fixed this)

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run 5/5: Jenkins-Debug-18.04 failed on `multi_pthread` LibOS test with timeout)

**Comment by dimakuv** [comment]
Hurray, doing several runs and observing non-deterministic failures bore fruit, and I found a bug: forgot to acquire a lock in the async helper thread. Now I'll do another 5 runs to check if there are no more bugs in this PR.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX please (Out-of-memory on `large-mmap`, looks like Jenkins' machine issue)

**Comment by mkow** [comment]
Jenkins, retest Jenkins please (`apps.LTP.setrlimit02` timed out, seems unrelated)

**Pull request merged**
