### PR TITLE
[CI] Enable pylint unconditionally, fix violations

### PR DESCRIPTION
**Pull request by pwmarcz**
Pylint output was filtered so that many files with existing pylint
violations were allowed to stay broken.

I made sure all files pass pylint, but whitelisted some rules that
we commonly disable:

* missing docstrings: most of the code is tests/internal anyway
* invalid-name: too many violations, and we commonly use one- or
  two-character names (like "a, b" or "t1, t2") which is
  disallowed by this rule; we could tweak it and then fix
  remaining violations such as camel-case or lowercase constants
* fixme: we leave TODOs as a matter of practice, same as in C
* high-level style rules like too-few-* and too-many-*,
  no-self-use

Hopefully that will make using pylint less annoying, while also
catching serious issues (such as unused variables or imports).

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[.ci/run-pylint, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMGhfcHBaGwVHc9Mv2U:-MMGhfcI2RYK34rYP5ma:b9axrkn) ([raw file](https://github.com/oscarlab/graphene/blob/129c3d74144ad112b115309a913ae85dadabaa66/.ci/run-pylint#L21)):*
> ```
>     -and -not -path ./LibOS/shim/test/ltp/install/\* \
>     -and -not -path ./Examples/pytorch/\* \
>     -and -not -path ./Pal/src/host/Linux-SGX/\* \
> ```

Why excluding this whole directory?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[.ci/run-pylint, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMGhfcHBaGwVHc9Mv2U:-MMGnJo4CSMH_rrAFreU:b83xvxl) ([raw file](https://github.com/oscarlab/graphene/blob/129c3d74144ad112b115309a913ae85dadabaa66/.ci/run-pylint#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why excluding this whole directory?
</blockquote></details>

That was supposed to be `sgx-driver/` (since it's a submodule). Fixed.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[.ci/run-pylint, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMGhfcHBaGwVHc9Mv2U:-MMGtt2PEUH7ggk3WOY7:b-xxgbj7) ([raw file](https://github.com/oscarlab/graphene/blob/129c3d74144ad112b115309a913ae85dadabaa66/.ci/run-pylint#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That was supposed to be `sgx-driver/` (since it's a submodule). Fixed.
</blockquote></details>

Ah. Makes more sense now :)
___
*[.ci/run-pylint, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMGtwMV-RDi9YmBHRWY:-MMGtwMW5lqIBVmkOlA_:botekto) ([raw file](https://github.com/oscarlab/graphene/blob/486d32aa2331cf00847e530aa615bc7098cfa8e1/.ci/run-pylint#L21)):*
> ```
>     -and -not -path ./LibOS/shim/test/ltp/install/\* \
>     -and -not -path ./Examples/pytorch/\* \
>     -and -not -path ./Pal/src/host/Linux-SGX/sgx-driver\* \
> ```

Hmm, missing slash after `sgx-driver`? Or was this on purpose?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[.ci/run-pylint, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMGtwMV-RDi9YmBHRWY:-MMGuytn0juXL2Cs_vsZ:bj3eoea) ([raw file](https://github.com/oscarlab/graphene/blob/486d32aa2331cf00847e530aa615bc7098cfa8e1/.ci/run-pylint#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, missing slash after `sgx-driver`? Or was this on purpose?
</blockquote></details>

Fixed, thanks.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by yamahata — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[.ci/lib/stage-lint.jenkinsfile, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMHqP6DBNAVh7psXwqm:-MMHqP6DBNAVh7psXwqn:bjv7xvx) ([raw file](https://github.com/oscarlab/graphene/blob/024f8514246f73a48ee795df113168c8d017b1dc/.ci/lib/stage-lint.jenkinsfile#L6)):*
> ```
>         then
>             ./.ci/run-pylint -f text || :
>             ./.ci/run-pylint -f json | ./.ci/prfilter
> ```

Just remove this line and also remove `|| :` from the previous one. Now there is no need to run `pylint` twice. When we used `prfilter`, I wanted to show all errors, but fail the build only on the one accepted by `prfilter`.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: 16 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @woju, and @yamahata)

___
*[.ci/lib/stage-lint.jenkinsfile, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMHqP6DBNAVh7psXwqm:-MMKhReZB7XxZ26TeMc5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/024f8514246f73a48ee795df113168c8d017b1dc/.ci/lib/stage-lint.jenkinsfile#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Just remove this line and also remove `|| :` from the previous one. Now there is no need to run `pylint` twice. When we used `prfilter`, I wanted to show all errors, but fail the build only on the one accepted by `prfilter`.
</blockquote></details>

Done.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by pwmarcz** [comment]
Looks like I made a mistake refactoring one of the tests, let's see now.

**Comment by pwmarcz** [comment]
Looks like the Pylint version that is under Ubuntu 18 has a different opinion about the code. Not fun...

Anyway, now Pylint should pass on Jenkins.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Tools/gsc/gsc.py, line 15 at r6](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMMAgxSCAvkgv1J9cAE:-MMMAgxSCAvkgv1J9cAF:b-1pbb7e) ([raw file](https://github.com/oscarlab/graphene/blob/4ede2a5901ccec8fe7e6c09d5bd30c33617c9566/Tools/gsc/gsc.py#L15)):*
> ```Python
> import jinja2
> import docker  # pylint: disable=import-error
> import yaml    # pylint: disable=import-error
> ```

Are these still needed after updating `known-third-party`?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Tools/gsc/gsc.py, line 15 at r6](https://reviewable.io/reviews/oscarlab/graphene/1972#-MMMAgxSCAvkgv1J9cAE:-MMMDIqIDKIQTxMXOTOO:b-z5678f) ([raw file](https://github.com/oscarlab/graphene/blob/4ede2a5901ccec8fe7e6c09d5bd30c33617c9566/Tools/gsc/gsc.py#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are these still needed after updating `known-third-party`?
</blockquote></details>

From my experiments, yes - `known-third-party` is only about import order, and Pylint still complains about not being able to find these libraries.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 5 of 5 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1972)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (LTP.select04 timed out)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (a lot of timeouts on LTP.truncate*, known issue)

**Pull request merged**
