### PR TITLE
[Examples] Update Memcached to run on Ubuntu 18.04 and build correctly

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Tried Memcached on Ubuntu 18.04 and found out it doesn't build correctly. Updated everything.

Also removed "unset environment variables" from the manifest because this is done by default in modern Graphene.

## How to test this PR? 

This PR adds Memcached to our Jenkins CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1807#-MGraZgA-IdPw1huOQrU:-MGraZgB60WKGeBWl3uy:b-phnac) (no related file):*
> Run Memcached manually. I'm not sure why we don't have it in the CI. I could add if needed.

How long does it run? If it's not too slow we should add it.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: 1 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1807#-MGraZgA-IdPw1huOQrU:-MI-CV5f9Jlxpfmm24HG:bcv1re7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Run Memcached manually. I'm not sure why we don't have it in the CI. I could add if needed.

How long does it run? If it's not too slow we should add it.
</blockquote></details>

Done. I added a very basic test, takes no longer than couple seconds.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: 0 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1807#-MGraZgA-IdPw1huOQrU:-MI-ciqf4ukBAkscEg2Z:b-166o6x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I added a very basic test, takes no longer than couple seconds.
</blockquote></details>

Done. Verified our Jenkins logs -- everything works as expected.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Jenkinsfiles/Linux-SGX-apps, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/1807#-MI03w4g7EbjPLAIPzy5:-MI03w4i2LM6vSPBpxdy:b-p1bz2o) ([raw file](https://github.com/oscarlab/graphene/blob/4e8cc32b283db73a5193c65cc01bb825def5a48d/Jenkinsfiles/Linux-SGX-apps#L84)):*
> ```
>                                 make SGX=1 start-graphene-server &
>                                 sleep 30
>                                 memcslap --servers=127.0.0.1 --concurrency=8
> ```

I don't know this tool, does it actually verify the results or only stress tests the server? I mean, will we detect any problems using it?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: 5 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Jenkinsfiles/Linux-SGX-apps, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/1807#-MI03w4g7EbjPLAIPzy5:-MI3C7M66g9UJokIrIQ8:b-2hlbmt) ([raw file](https://github.com/oscarlab/graphene/blob/4e8cc32b283db73a5193c65cc01bb825def5a48d/Jenkinsfiles/Linux-SGX-apps#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't know this tool, does it actually verify the results or only stress tests the server? I mean, will we detect any problems using it?
</blockquote></details>

It doesn't verify results (I don't see any options for that). The tool is crappy, but it's the only one we can easily install and use. So I added another tool `memcached-tool` (part of memcached build), and this tool tests at least most important cases: it fails if it can't connect to the Memcached server and it outputs less than 2 lines if Memcached server is empty.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: 5 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Jenkinsfiles/Linux-SGX-apps, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/1807#-MI03w4g7EbjPLAIPzy5:-MI3ClOf5tcAgKKzHqVy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e8cc32b283db73a5193c65cc01bb825def5a48d/Jenkinsfiles/Linux-SGX-apps#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It doesn't verify results (I don't see any options for that). The tool is crappy, but it's the only one we can easily install and use. So I added another tool `memcached-tool` (part of memcached build), and this tool tests at least most important cases: it fails if it can't connect to the Memcached server and it outputs less than 2 lines if Memcached server is empty.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`kill03` LTP test failed, known issue)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`kill01` LTP test failed, known)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test failed, known, and I'm very unlucky)

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1807)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (@dimakuv yup, you're very unlucky :) this time waitpid03 timed out)

**Pull request merged**
