### PR TITLE
[PAL/PAL-SGX] Convert futexes to ints

### LINKED ISSUE #1485: Futex variables are 32 bit (int) on Linux but ours are 64 bit
The mutex_handle in https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux/pal_host.h#L39 defines a 64 bit variable that is later on used as the futex variable and also used in cmpxchg here https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux/db_mutex.c#L108 . Futex variables are 32 bit on Linux (int) though [http://man7.org/linux/man-pages/man2/futex.2.html] the cmpxchg works on 64 bit. I think we should fix this by changing the variable to be int32_t or int32_t * and having cmpxchg works on 32 bit variables or by introducing cmpxchg32.

Comments?

### PR DESCRIPTION
**Pull request by stefanberger**
## Description of the changes 

This PR converts futexes from int64_t to int's.

Fixes #1485.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1574)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
