### PR TITLE
[Pal+ LibOS] Move more x86_64 specific header files

### PR DESCRIPTION
**Pull request by stefanberger**
Move more x86_64 specific header files into their architecture specific directories. Also enable some functions that are not x86_64 specific by dropping the `#ifdef __x86_64__` around them.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1488)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`apps.LTP.open08`, `apps.LTP.socket02` and `apps.LTP.syscall01` timed out; known issue: #1297)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (`test_libos.TC_30_Syscall.test_052_large_mmap` failed, known issue)

**Pull request merged**
