### PR TITLE
[LibOS] Remove unused functions in shim_internal.h and shim_init.c

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Removed:
- `message_confirm` - not used anywhere (and probably won't ever be),
- `SYS_PRINTF` - this was just synonym of `debug` or `warn` (depending
   on the context),
- all other functions that were used only by the two above.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1898)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1898)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/shim_init.c, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1898#-MJmIFX74ZBeL5H1_Kq8:-MJmIFX74ZBeL5H1_Kq9:b-9329mk) ([raw file](https://github.com/oscarlab/graphene/blob/4e26fe7e3280a66130000769ea48477bc8da6ade/LibOS/shim/src/shim_init.c#L56)):*
> ```C
> }
> 
> void warn(const char* format, ...) {
> ```

`warn` is actually also exported in PAL API, so this was not used anywhere.

**Review by mkow — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1898)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (`apps.LTP.fork11` timed out, known issue)

**Review by yamahata — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1898)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (fork11 failed again)

**Pull request merged**
