### PR TITLE
[LibOS] Fix `shim_ipc_info` leak

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This PR has one caveat: it makes pids reusable i.e. they might not be
growing (Graphene might reuse old, freed pids).

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN43J0o5yEWONJyTDT2:-MN43J0o5yEWONJyTDT3:bh9rvxy) (no related file):*
Is reuse of pids acceptable? @dimakuv @mkow @yamahata   

---
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 275 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN438ef-N9IIX4QDDIh:-MN438eg0W5eq-YL0ZJM:bx0r6x5) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/ipc/shim_ipc_ranges.c#L275)):*
> ```C
>     struct subrange* s = *ptr;
>     *ptr = NULL;
>     put_ipc_info_in_list(s->owner);
> ```

Please kill me

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN43J0o5yEWONJyTDT2:-MN4A5pu91Ku9Gn9vSLi:bb77ufg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is reuse of pids acceptable? @dimakuv @mkow @yamahata   
</blockquote></details>

Yes.

---
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 275 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN438ef-N9IIX4QDDIh:-MN4AAbu5GJAi4N4zwVl:b6nl9ak) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/ipc/shim_ipc_ranges.c#L275)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please kill me
</blockquote></details>

This looks like a separate memory leak, right? So there were two sources of leaks of `shim_ipc_info` objects, both fixed in this PR?
___
*[LibOS/shim/src/sys/shim_clone.c, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4AzSDDurNKucn97ud:-MN4AzSDDurNKucn97ue:brttwar) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/sys/shim_clone.c#L372)):*
> ```C
>          * should free it. */
>         assert(__atomic_load_n(&thread->ref_count.counter, __ATOMIC_RELAXED) == 1);
>         /* We do not want to release `tid` now, we will do this one the child process dies. This
> ```

`one` -> `once`
___
*[LibOS/shim/src/sys/shim_clone.c, line 374 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4B4pcCrF0kM1MZ6c9:-MN4B4pcCrF0kM1MZ6cA:b4gjq1a) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/sys/shim_clone.c#L374)):*
> ```C
>         /* We do not want to release `tid` now, we will do this one the child process dies. This
>          * makes little sense (as in theory we've passed the ownership of this id to the child), but
>          * IPC code is a mess, so that's what we have to do. */
> ```

I don't understand the last sentence. We passed the ownership to the child, but the child cannot release the tid (stored in the parent process), so by dying, it kinda gives the ownership back to the parent process, and now the parent can release tid. It's subtle but I think that's the explanation.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 275 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN438ef-N9IIX4QDDIh:-MN4C5ol1acpyiTL8y0-:bx50f77) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/ipc/shim_ipc_ranges.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks like a separate memory leak, right? So there were two sources of leaks of `shim_ipc_info` objects, both fixed in this PR?
</blockquote></details>

Yes, this did not delete the object, since the last reference was on list.
___
*[LibOS/shim/src/sys/shim_clone.c, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4AzSDDurNKucn97ud:-MN4CN4-1go2Z4Z200e0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/sys/shim_clone.c#L372)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`one` -> `once`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_clone.c, line 374 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4B4pcCrF0kM1MZ6c9:-MN4CR9QCc_zpaHwE3KR:bsn1fvh) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/sys/shim_clone.c#L374)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the last sentence. We passed the ownership to the child, but the child cannot release the tid (stored in the parent process), so by dying, it kinda gives the ownership back to the parent process, and now the parent can release tid. It's subtle but I think that's the explanation.
</blockquote></details>

No, when a thread dies (including the last thread in a process) it releases its own tid. We (as a parent) should not be doing it (also we have no knowledge of individual threads in the child).

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 374 at r1](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4B4pcCrF0kM1MZ6c9:-MN4EAy_-VtPOmGAQPbr:bsvxalv) ([raw file](https://github.com/oscarlab/graphene/blob/75f88c79f5254f5ce80f7f109d025954ebed9d29/LibOS/shim/src/sys/shim_clone.c#L374)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, when a thread dies (including the last thread in a process) it releases its own tid. We (as a parent) should not be doing it (also we have no knowledge of individual threads in the child).
</blockquote></details>

There should be one single owner of a given `tid` and it should release it when appropriate (by release I mean inform IPC leader that it's free and up for usage).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN43J0o5yEWONJyTDT2:-MN4RovWDZvbjaXclOz0:b-vrc8si) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Yes. This may happen on Linux if you get an unlucky race with other processes, so apps should not assume anything about it.

---
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 80 at r2](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4SHAcB7K1Yc3iA9Xa:-MN4SHAcB7K1Yc3iA9Xb:b-n7dh1t) ([raw file](https://github.com/oscarlab/graphene/blob/13c2e6f41885215516d71686c909f80d574ac333/LibOS/shim/src/bookkeep/shim_process.c#L80)):*
> ```C
>     assert(LIST_EMPTY(child, list));
> 
>     /* DOES THIS WORK LOL */
> ```

I guess this will be answered by @dimakuv tomorrow :)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX-18.04-apps please (unrelated jenkins failure)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 80 at r2](https://reviewable.io/reviews/oscarlab/graphene/1999#-MN4SHAcB7K1Yc3iA9Xa:-MNNU-h5CnliPkUEtgFn:b920dkf) ([raw file](https://github.com/oscarlab/graphene/blob/13c2e6f41885215516d71686c909f80d574ac333/LibOS/shim/src/bookkeep/shim_process.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this will be answered by @dimakuv tomorrow :)
</blockquote></details>

This fixes one 40B leak, but there are additional 40KB of leaked data...

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1999)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
