### PR TITLE
[LibOS] Update PAL_ERROR_ENDOFSTREAM error code handling for DkStreamRead()

### LINKED ISSUE #2078: [LibOS] fork() returns positive pid when child process fails to receive checkpoint
## Description of the problem
When very big enclave calls fork, sometimes it fail during sending/receiving checkpoint.

Using commit several months ago, the thread which calls fork() prints log `failed sending checkpoint (ret = -22)` and `return from shim_vfork(...) = -22`. Child process prints log `failed restoring checkpoint at vma (-22)`.

Now  child process prints log `failed restoring checkpoint at vma (-22)` but parent doesn't print any error log, fork() also return positive pid.

The case is 32G enclave running Java. Java uses Processbuilder(), it calls fork() then execve(). Here is a snap of log by `egrep "vfork|execve|checkpoint"`
```
[P2875:T2:java] ---- start time: 9481 ms shim_vfork() ... vfork
[P2875:T2:java] vfork was called by the application, implemented as an alias to fork in Graphene
[P2875:T2:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2875:T2:java] complete checkpointing data
[P2875:T2:java] checkpoint of 661152 bytes created
[P2931:java] checkpoint mapped at 0xfdffa0000-0xfe00416a0
[P2931:java] read checkpoint of 661152 bytes from parent
[P2931:java] restored memory from checkpoint
[P2931:java] restoring checkpoint at 0xfdffa0000 rebased from 0xfdffa0000
[P2931:T37:java] successfully restored checkpoint at 0xfdffa0000 - 0xfe00416a0
[P2875:T2:java] ---- end time: 113284 ms return from shim_vfork(...) = 37
[P2931:T37:java] ---- start time: 0 ms shim_execve("//setsid",[setsid,bash,-c,echo $$,],[LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu:/usr//lib/x86_64-linux-gnu:/opt/jdk8:/opt/jdk8/lib/amd64/jli,PATH=/:/opt/jdk8/bin:/usr/sbin:/usr/bin:/sbin:/bin,]) ... execv[P2931:T37:java] e
[P2931:T37:java] execve() in a new process
[P2931:T37:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2931:T37:java] complete checkpointing data
[P2931:T37:java] checkpoint of 27432 bytes created
[P2933:setsid] checkpoint mapped at 0xb26f000-0xb275b28
[P2933:setsid] read checkpoint of 27432 bytes from parent
[P2933:setsid] restored memory from checkpoint
[P2933:setsid] restoring checkpoint at 0x0b26f000 rebased from 0xfe03df000
[P2931:T37:setsid] successfully restored checkpoint at 0x0b26f000 - 0x0b275b28
[P2931:T37:java] Temporary process 2931 is exiting after emulating execve (by forking new process to replace this one); will wait for forked process to exit...
[P2875:T73:java] ---- start time: 391583 ms shim_vfork() ... vfork
[P2875:T73:java] vfork was called by the application, implemented as an alias to fork in Graphene
[P2875:T73:java] allocating checkpoint store (size = 67108864, reserve = 33554432)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2758 -> 0xfdff21268 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2a58 -> 0xfdff21bc8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff2158 -> 0xfdff222f0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3058 -> 0xfdff22a18 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff34d8 -> 0xfdff23140 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3958 -> 0xfdff23868 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff3dd8 -> 0xfdff23f90 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff4258 -> 0xfdff246b8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff46d8 -> 0xfdff24de0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5ff4b58 -> 0xfdff25740 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f290d8 -> 0xfdff25e68 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f29558 -> 0xfdff26590 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f299d8 -> 0xfdff26cb8 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f29e58 -> 0xfdff273e0 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2a2d8 -> 0xfdff27b08 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2a758 -> 0xfdff28230 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2bad8 -> 0xfdff29b20 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2bf58 -> 0xfdff2a248 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2c3d8 -> 0xfdff2a970 (base = 0xfdfe54000)
[P2875:T73:java] checkpoint epoll: 0xfe5f2c858 -> 0xfdff2b098 (base = 0xfdfe54000)
[P2875:T73:java] complete checkpointing data
[P2875:T73:java] checkpoint of 958080 bytes created
[P3013:java] checkpoint mapped at 0xfdfe54000-0xfdff3de80
[P3013:java] read checkpoint of 958080 bytes from parent
[P3013:java] restored memory from checkpoint
[P3013:java] restoring checkpoint at 0xfdfe54000 rebased from 0xfdfe54000
[P3013:java] failed restoring checkpoint at vma (-22)
[P3013:java] Error during shim_init() in receive_checkpoint_and_restore (-22)
[P2875:T73:java] ---- end time: 519935 ms return from shim_vfork(...) = 74
```
First successful fork from `[P2875:T2:java]` created `[P2931:java]`, whose pid is 37.
Second failed fork from `[P2875:T73:java]` created `[P3013:java]`. It failed to receive checkpoint, but parent still returns 74.

I also added more log to catch this error. It come from `read_exact` in shim_checkpoint.c. `read` over socket returns EINVAL.

I also added time stamp to track fork time. I can send you the full log if necessary.

### PR DESCRIPTION
**Pull request by llly**
## Description of the changes 
`DkStreamRead()` returns `PAL_STREAM_ERROR` with `pal_errno` `PAL_ERROR_ENDOFSTREAM` when read 0 byte from stream.

There are two different use cases:

1. Caller wants to read exact number of bytes from stream. If stream is empty, there is something wrong. It's usually used for protocol.
2. Caller wants to read any number of bytes from stream. If stream is empty, reading is done.

After all DkStreamRead() got reviewed , In this PR,  PAL_ERROR_ENDOFSTREAM is mapped to error code EPERM for case 1, PAL_ERROR_ENDOFSTREAM is mapped to successful 0 for case 2.

fixes #2078 #2131

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2137)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2137)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb5s5_6EuVLgKCsgGI:-MSb5s5_6EuVLgKCsgGJ:bys6yfr) (no related file):*
Can you also add the test in `tcp_msg_peek.c`, similar to what you did in https://github.com/oscarlab/graphene/issues/2131? And please also add a corresponding check in `test_libos.py` for this test.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb88_O3U2EsR45H7bT:-MSb88_O3U2EsR45H7bU:b-woal3h) (no related file):*
I'm fine with this PR, but our logic of `PAL_STREAM_ERROR`, `PAL_NATIVE_ERRNO` and `PAL_ERRNO` grew to become a real mess. We'll need to come up with a better error mapping & error handling scheme, all these if-then-elses are very ugly.

---
___
*[LibOS/shim/src/shim_checkpoint.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb52hF8blj-AJsL0dD:-MSb52hF8blj-AJsL0dE:b-nmxh66) ([raw file](https://github.com/oscarlab/graphene/blob/0bb60fd9de4ac86c838d61d72e5482283e23b2a7/LibOS/shim/src/shim_checkpoint.c#L225)):*
> ```C
>                 return -EPERM;
>             }
>             int err = PAL_ERRNO();
> ```

Can we replace the added lines with this:
```
int err = PAL_NATIVE_ERRNO() == PAL_ERROR_ENDOFSTREAM ? EPERM : PAL_ERRNO();
```

This is the same, but easier to read and similar to other places in this PR.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 574 at r1](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb4nAKDFLw4KPN7bGA:-MSb4nAL5T0qpB76j56R:b-mptbz3) ([raw file](https://github.com/oscarlab/graphene/blob/0bb60fd9de4ac86c838d61d72e5482283e23b2a7/LibOS/shim/src/ipc/shim_ipc_helper.c#L574)):*
> ```C
>                 if (PAL_NATIVE_ERRNO() == PAL_ERROR_ENDOFSTREAM) {
>                     err = EPERM;
>                 }
> ```

That's a bit ugly. Can you replace these lines with:
```
int err = PAL_NATIVE_ERRNO() == PAL_ERROR_ENDOFSTREAM ? EPERM : PAL_ERRNO();
```

**Review by llly — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2137)* status: 1 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb5s5_6EuVLgKCsgGI:-MSjqz2p2ZVBrcWxy802:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you also add the test in `tcp_msg_peek.c`, similar to what you did in https://github.com/oscarlab/graphene/issues/2131? And please also add a corresponding check in `test_libos.py` for this test.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/shim_checkpoint.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb52hF8blj-AJsL0dD:-MSjr-TK87-7rK41AJX7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0bb60fd9de4ac86c838d61d72e5482283e23b2a7/LibOS/shim/src/shim_checkpoint.c#L225)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we replace the added lines with this:
```
int err = PAL_NATIVE_ERRNO() == PAL_ERROR_ENDOFSTREAM ? EPERM : PAL_ERRNO();
```

This is the same, but easier to read and similar to other places in this PR.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 574 at r1](https://reviewable.io/reviews/oscarlab/graphene/2137#-MSb4nAKDFLw4KPN7bGA:-MSjr0CG6NVXNLSVzDRu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0bb60fd9de4ac86c838d61d72e5482283e23b2a7/LibOS/shim/src/ipc/shim_ipc_helper.c#L574)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a bit ugly. Can you replace these lines with:
```
int err = PAL_NATIVE_ERRNO() == PAL_ERROR_ENDOFSTREAM ? EPERM : PAL_ERRNO();
```
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2137)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2137)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Pull request closed without merging**
