### PR TITLE
[LibOS] test/apps: Tensorflow label image example

### PR DESCRIPTION
**Pull request by thomasknauth**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Matching PR for [shim/test/apps #22](https://github.com/oscarlab/graphene-tests/pull/22)

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/949)

### CODE REVIEW

**Comment by dcowhig** [comment]
Retest this please

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dcowhig** [comment]
Retest this please

**Comment by mkow** [comment]
Jenkins, test this please

**Pull request merged**
