### PR TITLE
Fix warnings in LibOS with -Wsign-compare

### PR DESCRIPTION
**Pull request by chiache**
Signed-off-by: Chia-Che Tsai <chiache@tamu.edu>

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Enabling -WSign-compare as the compile option in `LibOS/shim/src` and fixing all the related warnings.

## How to test this PR? 

Just run the regression tests.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/741)

### CODE REVIEW

**Comment by chiache** [comment]
Retest this please

**Comment by chiache** [comment]
Retest this again.

**Comment by chiache** [comment]
Retest this please

**Comment by dimakuv** [comment]
One of the latest commits ("Memory corruption fixes") has a signed-unsigned cast which is an error in your PR. Please fix it.
```
[ sys/shim_brk.o ]
In file included from ../include/shim_utils.h:28:0,
                 from sys/shim_brk.c:24:
sys/shim_brk.c: In function 'init_brk_region':
../../../Pal/lib/api.h:42:10: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       _a < _b ? _a : _b; })
          ^
sys/shim_brk.c:98:25: note: in expansion of macro 'MIN'
                 rand %= MIN(0x2000000, PAL_CB(user_address.end) - brk_region - brk_max_size);
                         ^
../../../Pal/lib/api.h:42:20: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
       _a < _b ? _a : _b; })
                    ^
sys/shim_brk.c:98:25: note: in expansion of macro 'MIN'
                 rand %= MIN(0x2000000, PAL_CB(user_address.end) - brk_region - brk_max_size);
                         ^
cc1: all warnings being treated as errors
Makefile:116: recipe for target 'sys/shim_brk.o' failed
```

**Pull request merged**
