### PR TITLE
[Pal/Linux-SGX] Allow enclave sizes greater than 32GB

### LINKED ISSUE #1856: Graphene-SGX limits maximum enclave size to 32G only
## Description of the problem
Current implementation of Graphene-SGX doesn't allow enclave size larger than 32G. 
sgx.enclave_size = 64G in manifest file, throws an error. 

## Steps to reproduce
1.  cd graphene/Examples/redis    or any other Example code
2.  sudo vim redis-server.manifest.template
3.  sgx.enclave_size = 64G  and save
4.  sudo make SGX=1
5.  sudo SGX=1 ./pal_loader redis-server
error: pal-Linux-SGX: assert failed sgx_framework.c:134 IS_ALIGNED(secs->base, secs->size)

## Expected results
sgx.enclave_size = 64G  should work

## Actual results
sgx.enclave_size = 64G
gives  error 
pal-Linux-SGX: assert failed sgx_framework.c:134 IS_ALIGNED(secs->base, secs->size)

## Workaround
Inside Pal/src/host/Linux-SGX/pal_linux_defs.h change the ENCLAVE_HIGH_ADDRESS as follows

Original value 
#define ENCLAVE_HIGH_ADDRESS   0x800000000  //32G

New value 
#define ENCLAVE_HIGH_ADDRESS   0x1000000000 //64G

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, Graphene had unnecessarily restrictive logic to handle PIE and non-PIE executables.

Non-PIE executables must be accommodated in an enclave that spans address 0x400000, so enclaves for non-PIE
must have base address of 0x0 and heap base of not 0x0. PIE executables have no restrictions on available addresses, so enclaves for PIE may have any base address (but aligned to enclave size due to SGX HW quirk) and heap base can start at enclave base.

Previously, for PIE executables Graphene chose enclave base = `ENCLAVE_HIGH_ADDRESS` = 32GB; this led to impossibility of creating enclaves of sizes greater than 32GB (due to the aforementioned SGX HW quirk).

This PR refactors all this logic and removes the hard-coded `ENCLAVE_HIGH_ADDRESS`. Instead, PIE executables have enclave base address same as enclave size (i.e., a 64GB enclave starts at address 64GB).

Fixes #1856.

## How to test this PR? 

No new tests. Try 64GB enclaves. Also, add `sgx.static_address = 0` and `sgx.static_address = 1` to say Redis or Memcached and observe debug logs.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZrxi42BSpmyocAWSh:-MIZxYmr6ZyUJsGNVvE2:bdimyjs) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L280)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why isn't this logic exactly the same as in the signer script? I don't see the check for the executable's memory segments here (the case where executable is non-PIE, but the manifest doesn't contain `sgx.static_address`).
</blockquote></details>

because signer script generates .manifesr.sgx with sgx.static_address = 1.

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZza7SAyB9-Y4WTOE-:-MIZza7SAyB9-Y4WTOE0:bkovc3f) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L272)):*
> ```C
>      * (we choose it same as enclave_size), and heap can start immediately at this base address */
>     enclave->baseaddr = enclave->size;
>     enclave_heap_min  = 0;
> ```

Just a suggestion,  It could be flexible to define "0" as a constant.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MI_0CJMCr-pwdoqL2g-:-MI_0CJMCr-pwdoqL2g0:bb3lv3t) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L276)):*
> ```C
>     if (get_config(enclave->config, "sgx.static_address", cfgbuf, sizeof(cfgbuf)) > 0
>             && cfgbuf[0] == '1') {
>         /* executable is static, i.e. it is non-PIE: enclave base address must be zero to cover
> ```

How about auto detecting the kind of executable when loading it.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MI_-eRT7-IJjT6KLKtE:-MI_-eRT7-IJjT6KLKtF:by7pksg) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L279)):*
> ```C
>          * code segment loaded at 0x400000, and heap cannot start at zero (OS will not allow) */
>         enclave->baseaddr = 0;
>         enclave_heap_min  = DEFAULT_HEAP_MIN;
> ```

There are 2 whitespaces right before the "="

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZrxi42BSpmyocAWSh:-MI_4yb-2fYN2bqCpEoY:bccp0fr) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L280)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

because signer script generates .manifesr.sgx with sgx.static_address = 1.
</blockquote></details>

Ah, I see. Thanks.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZqsJI2apnGKRVH1IK:-MIcK3983BoCq3TTiyuo:b-oa06ii) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L272)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

can we move this to `else` branch? This "assume" part of the sentence wouldn't be necessary and the logic will be more intuitive.
</blockquote></details>

Done. Same for the Python script.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZza7SAyB9-Y4WTOE-:-MIcLdp61KNPEZTGazNn:bj8hzaq) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L272)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Just a suggestion,  It could be flexible to define "0" as a constant.
</blockquote></details>

Done. I did it for the enclave base address (where it makes sense and analogous to `DEFAULT_HEAP_MIN`) but not for the "heap starts at offset 0x0" where I believe it doesn't help to have a constant.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MI_0CJMCr-pwdoqL2g-:-MIcLuIg1tt3dtq4Xxq8:b-eysavg) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L276)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

How about auto detecting the kind of executable when loading it.
</blockquote></details>

It is already done during our Python-script signing (see .py changes). I don't see a need to double-check the manifest.sgx file here, while loading the executable.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MI_-eRT7-IJjT6KLKtE:-MIcJ8nRBsxQxrl5C0uu:b1a35wo) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L279)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

There are 2 whitespaces right before the "="
</blockquote></details>

This is the way our C formatting works -- to make both variable assignments "aligned on each other". (Interestingly, there is a different enforced rule for Python -- every assignment must have only 1 space.)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/1863#-MIZrxi42BSpmyocAWSh:-MIcJLZV5LXfqmyTXFZs:b-bsemmb) ([raw file](https://github.com/oscarlab/graphene/blob/9eeb9290ae2545f3304c8f550cbe7b65665188d1/Pal/src/host/Linux-SGX/sgx_main.c#L280)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I see. Thanks.
</blockquote></details>

Yes, the signer script generates the final `manifest.sgx` file and *always* adds `sgx.static_address`. If this option is not added by our signer script, then something went wrong (or the app developer really knows what he's doing).

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1863)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
