### PR TITLE
[PAL+LibOS] x86_64 conditional builds  issues

### PR DESCRIPTION
**Pull request by stefanberger**
This PR addresses several x86_64 conditional build issues, such as building certain files and setting compile time flags.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1523)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`python-scipy-insecure` example failed, seems unrelated)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`fork11` LTP failed)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Pull request merged**
