### PR TITLE
[LibOS] Deliver signal to only one thread

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Previously Graphene delivered each signal to all threads instead of
one. This was additionally abused to quit the application. Now each
signal is delivered to only one arbitrary thread. This commit
additionally cleans the signal and exiting code.

## How to test this PR? 
Added new test.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1510)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, test Jenkins-Debug-18.04 please (mbedcrypto download failed)

**Comment by boryspoplawski** [comment]
Jenkins, test Jenkins-Debug-18.04 please (ltp:fork11 failed, it received a SIGPIPE on writing to a pipe with remote end dead; in `proc_write` called by `broadcast_ipc` to announce that this process is exiting; this seems unrelated to the patch; I was able to trigger it even in gdb on ubuntu16, but I don't have time to debug it now)

**Comment by boryspoplawski** [comment]
The above error is unrelated and I was able to trigger it on current master (see issue #1534)

**Comment by boryspoplawski** [comment]
Somethings wrong with `exec_same` now, debugging in progress ...

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins please (fork11 failed, known issue)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`fork11` failed)

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-SGX please (sighandler_reset timedout, I'm running it 100 times, locally, probably too low timeout set)

**Comment by boryspoplawski** [comment]
Jenkins, test this please (3/5, sighandler_reset still in debug)

**Comment by boryspoplawski** [comment]
Jenkins, test this please (4/5, sighandler_reset still in debug)

**Comment by mkow** [comment]
Jenkins, test this please (5/5, sighandler_reset still in debug)

**Comment by boryspoplawski** [comment]
Managed to trigger sighandler_reset issue on current master.

**Pull request merged**
