### PR TITLE
[LibOS] Split header from IPC messages

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This is a split of from a follow-up PR, which reworks IPC message responses.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWAC-vCPihNxPttvUD:-MbWAC-vCPihNxPttvUE:b-utjrzb) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc.c#L185)):*
> ```C
>     msg->header.size = get_ipc_msg_size(size);
>     msg->header.seq = 0;
>     msg->header.code = code;
> ```

You stripped `packed` attribute from the struct, so now padding may be uninitialized. I know that we're in the same security boundary, but I don't like the idea of sending uninitialized memory between processes...
I'd feel better with `packed` being restored, plus probably having static_asserts for fields alignment? I don't think there's any other solution for this in C.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWB1Ua4ZCinIMNSpWy:-MbWB1Ua4ZCinIMNSpWz:b-tdoqoy) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc_pid.c#L51)):*
> ```C
>         .sender = sender,
>         .type = type,
>         .id = target,
> ```

Why the target field is called `id`? Or maybe it's actually an ID, but then, why assigning `target` to it?
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 115 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWBZRr6j7e__FzC8Dv:-MbWBZRr6j7e__FzC8Dw:b-wkpaa2) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc_pid.c#L115)):*
> ```C
>         case KILL_ALL:
>             if (!g_process_ipc_ids.leader_vmid) {
>                 size_t total_msg_size    = get_ipc_msg_size(sizeof(*msgin));
> ```

please dealign `=`

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWAC-vCPihNxPttvUD:-MbX2WF07YaQk56kyz8r:b-h2tqfd) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You stripped `packed` attribute from the struct, so now padding may be uninitialized. I know that we're in the same security boundary, but I don't like the idea of sending uninitialized memory between processes...
I'd feel better with `packed` being restored, plus probably having static_asserts for fields alignment? I don't think there's any other solution for this in C.
</blockquote></details>

That was intentional - we are sending these struct only between instances of the same binary, so there are no compatibility issues.
As for security aspect: yes, as you noted we are not crossing any security boundaries, so I didn't care. Why does that bother you? Anyway, nif that's truly a problem, then I would rather add a `memset` here, than add packed attribute. It's annoying to deal with, especially in arch/compiler dependent types (like `size_t`) and in this case adds nothing (well, except for lack of non-initialized padding, if there is any).
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWB1Ua4ZCinIMNSpWy:-MbX3Rif73JCy6ypbvNW:b-ora29v) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc_pid.c#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why the target field is called `id`? Or maybe it's actually an ID, but then, why assigning `target` to it?
</blockquote></details>

No idea. I only moved this code up and made that struct local and then copied into the message. I did not touch anything else and I do not plan to (in this PR).
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 115 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWBZRr6j7e__FzC8Dv:-MbX3rYs85W51Ghjobfv:bjqnd6j) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc_pid.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please dealign `=`
</blockquote></details>

Why only here? I mean, this is just copy paste from above, we have that alignment in many places. I personally do not like it, but it was easier to leave it there, since most of the changes was just moving code around.
Update: actually this is new code so it makes sense :)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWAC-vCPihNxPttvUD:-MbYacyM2pTRjiqaHyS8:bu060vf) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc.c#L185)):*
Ok, but then please at least please put a comment somewhere explaining that this is a conscious decision and why it's acceptable.

> I would rather add a `memset` here, than add packed attribute

That still won't help, would be too easy for C. AFAIK writing to any field in a struct may un-zero the padding, e.g. when you write to a `char` field followed by large padding it's legal for the compiler to emit a 64-bit write (with some garbage in upper bytes).
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 115 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWBZRr6j7e__FzC8Dv:-MbYlkzL1fcsZbqZO0L7:butx64x) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc_pid.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why only here? I mean, this is just copy paste from above, we have that alignment in many places. I personally do not like it, but it was easier to leave it there, since most of the changes was just moving code around.
Update: actually this is new code so it makes sense :)
</blockquote></details>

Yup, I tried to only complain about the places you actually wrote/modified significantly ;)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 107 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_NyJP3c6gCv_4HqX0:-Mb_NyJP3c6gCv_4HqX1:bevuscd) ([raw file](https://github.com/oscarlab/graphene/blob/bd60bd0a42f0f29fd084d3ed3f50da64447b8595/LibOS/shim/include/shim_ipc.h#L107)):*
> ```objc
>     unsigned char code;
>     size_t size;
>     IDTYPE src, dst;
> ```

Do I understand correctly that you removed these redundant fields because:
- `src` is already known when the IPC message is received by the IPC worker thread,
- `dst` is obvious -- it is myself as a process

And because in PAL we assume a trusted and correct communication channel (UNIX sockets in Linux PAL, TLS-protected sockets in Linux-SGX), there is no need to duplicate this src/dest information. Is this right?
___
*[LibOS/shim/include/shim_ipc.h, line 119 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Mpd_9DRZuPcZha9C:-Mb_MpdaAeuHtx-jO4WX:b-j0hib6) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/include/shim_ipc.h#L119)):*
> ```objc
>  * - `semret_callback` in `LibOS/shim/src/ipc/shim_ipc_sysv.c`.
>  */
> static_assert(offsetof(struct shim_ipc_msg, data) % 8 == 0, "Currently proper alignmant is required");
> ```

Typo: `alignment`
___
*[LibOS/shim/include/shim_ipc.h, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_NE9nDkrXsoDffuhB:-Mb_NE9nDkrXsoDffuhC:b-kilpoa) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/include/shim_ipc.h#L175)):*
> ```objc
>  *
>  * \param msg received message
>  * \param src vmid of the process which sent \p msg
> ```

Please add description for the new argument `seq`, and in general fix this comment
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWAC-vCPihNxPttvUD:-Mb_QaUK27bc092cp893:b-gs2gvd) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc.c#L185)):*
> AFAIK writing to any field in a struct may un-zero the padding, e.g. when you write to a char field followed by large padding it's legal for the compiler to emit a 64-bit write (with some garbage in upper bytes).

Holy crap if this is true!

> Ok, but then please at least please put a comment somewhere explaining that this is a conscious decision and why it's acceptable.

+1.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Punl0XljiB6iGN9b:-Mb_Punl0XljiB6iGN9c:bfbn5ti) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc.c#L48)):*
> ```C
>     struct shim_ipc_msg_with_ack* a = container_of(_a, struct shim_ipc_msg_with_ack, node);
>     struct shim_ipc_msg_with_ack* b = container_of(_b, struct shim_ipc_msg_with_ack, node);
>     return a->msg.header.seq <= b->msg.header.seq;
> ```

Now that we don't have a destination, but we still have a global tree of messages `g_msg_with_ack_tree`, why does this comparison work correctly? It may check unrelated messages, and then there will be unnecessary stalls... Or is this scenario considered impossible?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_QzHZ9s6x1uH0dUWG:-Mb_QzHZ9s6x1uH0dUWH:b-tmiepo) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc.c#L192)):*
> ```C
>     msg->thread = NULL;
>     msg->retval = 0;
>     msg->private = NULL;
> ```

Don't we need to initialize the `node` field somehow?
___
*[LibOS/shim/src/ipc/shim_ipc_sysv.c, line 244 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Slx_3GmanbAyKjXb:-Mb_Slx_3GmanbAyKjXc:bxvbg0m) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_sysv.c#L244)):*
> ```C
>         .msgid = msgid,
>         .msgtype = msgtype,
>         .size = size,
> ```

This was not in the previous code. It was a bug?

UPDATE: Ok, right after this function there is a corresponding callback function. And it used to calculate the size from other sizes. Now you explicitly send it.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Tck2BaeqZlndXW8Z:-Mb_Tck2BaeqZlndXW8_:bhhvgjw) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_worker.c#L175)):*
> ```C
>     /* Try to get more bytes that strictly required in case there are more messages waiting.
>      * `0x40` as a random estimation of "couple of ints" + message header size to get it if
>      * possible. */
> ```

`to get it` sounds ambiguous. I liked the previous wording `to get the next message header`.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 218 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_UFPf80d9T10QlKD_:-Mb_UFPf80d9T10QlKDa:b-xcz6ab) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_worker.c#L218)):*
> ```C
> 
>         unsigned char msg_code = buf.msg_header.code;
>         unsigned long seq = buf.msg_header.seq;
> ```

Can we rename to `msg_seq` for uniformity?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: 6 of 8 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 107 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_NyJP3c6gCv_4HqX0:-MbaZ4DcAxMBV8R9dty1:bd1vqdq) ([raw file](https://github.com/oscarlab/graphene/blob/bd60bd0a42f0f29fd084d3ed3f50da64447b8595/LibOS/shim/include/shim_ipc.h#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do I understand correctly that you removed these redundant fields because:
- `src` is already known when the IPC message is received by the IPC worker thread,
- `dst` is obvious -- it is myself as a process

And because in PAL we assume a trusted and correct communication channel (UNIX sockets in Linux PAL, TLS-protected sockets in Linux-SGX), there is no need to duplicate this src/dest information. Is this right?
</blockquote></details>

Trust and correctness have nothing to do with these: if we did not assume trusted connection sending `src` and `dst` inline would help.
Other than that: yes, we already know them. We would need them if we wanted to pass messages through some process, but we do not do that atm (and we can add these if needed).
___
*[LibOS/shim/include/shim_ipc.h, line 119 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Mpd_9DRZuPcZha9C:-MbaZi7P2-AL6U1Dv5gx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/include/shim_ipc.h#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `alignment`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_NE9nDkrXsoDffuhB:-Mba_ERfAFloMxOpZKu2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/include/shim_ipc.h#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add description for the new argument `seq`, and in general fix this comment
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2424#-MbWAC-vCPihNxPttvUD:-MbaPmwSBqE4BgkBUwqq:bp9bljm) ([raw file](https://github.com/oscarlab/graphene/blob/2ed762735444806b453e3cd8b548814c76add2c4/LibOS/shim/src/ipc/shim_ipc.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> AFAIK writing to any field in a struct may un-zero the padding, e.g. when you write to a char field followed by large padding it's legal for the compiler to emit a 64-bit write (with some garbage in upper bytes).

Holy crap if this is true!

> Ok, but then please at least please put a comment somewhere explaining that this is a conscious decision and why it's acceptable.

+1.
</blockquote></details>

Damn, sorry for confusion, I already forgot what I was doing:
the long term goal is to remove `shim_ipc_msg` and have packed on `ipc_msg_header`.
Added a comment in `.h`
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Punl0XljiB6iGN9b:-Mba_Hi0E5oTy9S-_38J:bw3nmtt) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we don't have a destination, but we still have a global tree of messages `g_msg_with_ack_tree`, why does this comparison work correctly? It may check unrelated messages, and then there will be unnecessary stalls... Or is this scenario considered impossible?
</blockquote></details>

These messages are only outgoing (i.e. only these that the current process sends) and sequence numbers are not shared between messages (i.e. we have only 1 global atomic counter).
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_QzHZ9s6x1uH0dUWG:-Mba_V9wEeob9yP2wvZj:b5ikwvz) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we need to initialize the `node` field somehow?
</blockquote></details>

Why would we? It always follows from context, whether an object is on tree or not (and for that exact reason there are no function to check it or even initialize a tree node explicitly).
___
*[LibOS/shim/src/ipc/shim_ipc_sysv.c, line 244 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Slx_3GmanbAyKjXb:-Mba_xV88Sq4syx9fU1z:bmwtcq4) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_sysv.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was not in the previous code. It was a bug?

UPDATE: Ok, right after this function there is a corresponding callback function. And it used to calculate the size from other sizes. Now you explicitly send it.
</blockquote></details>

That's correct.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 175 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_Tck2BaeqZlndXW8Z:-MbaaFio2EM5jZsznwxC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_worker.c#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to get it` sounds ambiguous. I liked the previous wording `to get the next message header`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 218 at r2](https://reviewable.io/reviews/oscarlab/graphene/2424#-Mb_UFPf80d9T10QlKD_:-MbaaUO10IFJ9i6nfkHY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/518745e6af2a5c25d1caf8ae57700f27586d1357/LibOS/shim/src/ipc/shim_ipc_worker.c#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to `msg_seq` for uniformity?
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2424)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
