### PR TITLE
[Examples,Docs] Fix pytorch download-model instructions

### PR DESCRIPTION
**Pull request by CAPTAIN320**
corrected command to download the pretrained model

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320)

___
*[Examples/pytorch/README.md, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpQxLL2AEIyRmqreNt:-MdpQxLMC_sPSUu6bEOJ:b220ile) ([raw file](https://github.com/oscarlab/graphene/blob/780b512832097c46977364535f02b10c66c2d379/Examples/pytorch/README.md#L28)):*
> ```Markdown
>   their dependencies (usually in $HOME/.local). WARNING: This downloads several hundred megabytes of
>   data!
> - `python3 download-pretrained-model.py` to download and save the pre-trained model.
> ```

How is this different from what we currently have? What problem does this change solve?

Note that the `make download_model` command should do exactly the same as the your Python command: https://github.com/oscarlab/graphene/blob/2dc94fc698a0e61b056828561dd376d094938de6/Examples/pytorch/Makefile#L54

**Comment by CAPTAIN320** [comment]
___
*[Examples/pytorch/README.md, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpQxLL2AEIyRmqreNt:-MdpRltZESOg6je8fnvs:b-1b5vhz) ([raw file](https://github.com/oscarlab/graphene/blob/780b512832097c46977364535f02b10c66c2d379/Examples/pytorch/README.md#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is this different from what we currently have? What problem does this change solve?

Note that the `make download_model` command should do exactly the same as the your Python command: https://github.com/oscarlab/graphene/blob/2dc94fc698a0e61b056828561dd376d094938de6/Examples/pytorch/Makefile#L54
</blockquote></details>

When I tried using the previous command, I got a file not found erroe.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320)

___
*[Examples/pytorch/README.md, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpQxLL2AEIyRmqreNt:-MdpU68R1USij7y9LT1e:bw3bsc8) ([raw file](https://github.com/oscarlab/graphene/blob/780b512832097c46977364535f02b10c66c2d379/Examples/pytorch/README.md#L28)):*
<details><summary><i>Previously, CAPTAIN320 (Yaqub Mahmoud) wrote…</i></summary><blockquote>

When I tried using the previous command, I got a file not found erroe.
</blockquote></details>

Really? Could you copy-paste the output here? I don't see how this is possible...

**Comment by CAPTAIN320** [comment]
___
*[Examples/pytorch/README.md, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpQxLL2AEIyRmqreNt:-MdpVqRhDa6TYUSES4iv:b-4lilzh) ([raw file](https://github.com/oscarlab/graphene/blob/780b512832097c46977364535f02b10c66c2d379/Examples/pytorch/README.md#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Really? Could you copy-paste the output here? I don't see how this is possible...
</blockquote></details>

It is a command not found

(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$ ls
alexnet-pretrained.pt         input.jpg          pytorch.manifest           pytorch.sig
classes.txt                   Makefile           pytorch.manifest.sgx       pytorch.token
download-pretrained-model.py  pytorchexample.py  pytorch.manifest.template  README.md
(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$ make download_model
download-pretrained-model.py
make: download-pretrained-model.py: Command not found
Makefile:54: recipe for target 'download_model' failed
make: *** [download_model] Error 127
(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpXviS7565PN9YqAAH:-MdpXviS7565PN9YqAAI:b7kw9be) (no related file):*
@captain320 Could you also remove these lines from the Makefile then:
https://github.com/oscarlab/graphene/blob/6c5c8fbf15da58d508df3099548e328ef655805d/Examples/pytorch/Makefile#L52-L55

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpY7S42Jy2MR9T7tDy:-MdpY7S42Jy2MR9T7tDz:b-z48ijh) (no related file):*
@captain320 Could you also fix the lines in the tutorial doc in the same way: https://github.com/oscarlab/graphene/blob/d9304f5b2dce520339e16c5f4f13cb1a435f5cad/Documentation/tutorials/pytorch/index.rst#executing-native-pytorch

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpYDxI3MHrdr5QXGmk:-MdpYDxI3MHrdr5QXGml:b-k45dtv) (no related file):*
@captain320 Please add a signoff to your commit message? You can simply do `git commit --amend --signoff` (and make sure that the signoff line contains your name and email address as you want to see them in public) and then `git commit push --force-with-lease`

---
___
*[Examples/pytorch/README.md, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpQxLL2AEIyRmqreNt:-MdpXNK-EDCg0B9jAIDm:bhb0zzb) ([raw file](https://github.com/oscarlab/graphene/blob/780b512832097c46977364535f02b10c66c2d379/Examples/pytorch/README.md#L28)):*
<details><summary><i>Previously, CAPTAIN320 (Yaqub Mahmoud) wrote…</i></summary><blockquote>

It is a command not found

(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$ ls
alexnet-pretrained.pt         input.jpg          pytorch.manifest           pytorch.sig
classes.txt                   Makefile           pytorch.manifest.sgx       pytorch.token
download-pretrained-model.py  pytorchexample.py  pytorch.manifest.template  README.md
(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$ make download_model
download-pretrained-model.py
make: download-pretrained-model.py: Command not found
Makefile:54: recipe for target 'download_model' failed
make: *** [download_model] Error 127
(cosmix) captain@plab-pc1:~/github/graphene/Examples/pytorch$

</blockquote></details>

That's because for some reason `PYTHONEXEC` env var is not set in your current terminal session.

UPDATE: Oops, apparently we removed `PYTHONEXEC` envvar from Graphene alltogether at some point: https://github.com/oscarlab/graphene/search?q=PYTHONEXEC. Indeed, Graphene doesn't set `PYTHONEXEC` anymore.

Given this, the fix sounds legit.

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpYDxI3MHrdr5QXGmk:-MdpcABe4nGZwfKQR5jE:b-eerd35) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@captain320 Please add a signoff to your commit message? You can simply do `git commit --amend --signoff` (and make sure that the signoff line contains your name and email address as you want to see them in public) and then `git commit push --force-with-lease`
</blockquote></details>

Okay, I will do all that and commit.

---

**Comment by CAPTAIN320** [comment]
@dimakuv Should I update this line too?

https://github.com/oscarlab/graphene/blob/3175206bc6cc5d8a262a7fc270ee14972909d3a3/Documentation/tutorials/pytorch/index.rst#L412-L416

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpXviS7565PN9YqAAH:-MdpxGeM57mQmEJ7ppmA:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@captain320 Could you also remove these lines from the Makefile then:
https://github.com/oscarlab/graphene/blob/6c5c8fbf15da58d508df3099548e328ef655805d/Examples/pytorch/Makefile#L52-L55
</blockquote></details>

Done.

---

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpY7S42Jy2MR9T7tDy:-MdpxHZ011R0cWov5Bcv:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@captain320 Could you also fix the lines in the tutorial doc in the same way: https://github.com/oscarlab/graphene/blob/d9304f5b2dce520339e16c5f4f13cb1a435f5cad/Documentation/tutorials/pytorch/index.rst#executing-native-pytorch
</blockquote></details>

Done.

---

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpYDxI3MHrdr5QXGmk:-MdpxI2z6dLtxDQProRO:b-896fix) (no related file):*
<details><summary><i>Previously, CAPTAIN320 (Yaqub Mahmoud) wrote…</i></summary><blockquote>

Okay, I will do all that and commit.
</blockquote></details>

Done.

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
Yes, please update this line too.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502#-:-Mdpz2Bo4ugKeTWNoTVa:b-mps0yt)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpYDxI3MHrdr5QXGmk:-Mdpyjz904mDcCtLf2G_:b-24brw5) (no related file):*
> Signed-off-by: CAPTAIN320

Are you sure you want this nickname to be "set in stone" once this PR lands in mainline Graphene? I would recommend to replace it with your actual name.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpY7S42Jy2MR9T7tDy:-MdpzHoz7eYKZcQ6fDVn:besf8ch) (no related file):*
<details><summary><i>Previously, CAPTAIN320 (Yaqub Mahmoud) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Only partially done. There are two places like that. Please fix the second place as well (in the same file).

---

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpYDxI3MHrdr5QXGmk:-MdquYg1Cj1N_0NIB2fd:b-1ohnif) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Signed-off-by: CAPTAIN320

Are you sure you want this nickname to be "set in stone" once this PR lands in mainline Graphene? I would recommend to replace it with your actual name.
</blockquote></details>

I have used my full name. Thank you!

---

**Comment by CAPTAIN320** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdpY7S42Jy2MR9T7tDy:-MdquiNFCMAX0TvM7UAA:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Only partially done. There are two places like that. Please fix the second place as well (in the same file).
</blockquote></details>

Done.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320 and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-Mdr5HR46yRDcQT5rJ7K:-Mdr5HR46yRDcQT5rJ7L:b-7zherm) (no related file):*
There's still one occurrence in `Documentation/tutorials/pytorch/index.rst` left, could you fix also that one?

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320 and @mkow)

___
*[Documentation/tutorials/pytorch/index.rst, line 415 at r3](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdrOGs83ikiEnVR2C9H:-MdrOGs83ikiEnVR2C9I:bravonc) ([raw file](https://github.com/oscarlab/graphene/blob/fd05c6c2bec80a3b4774aefe7d035663ae826099/Documentation/tutorials/pytorch/index.rst#L415)):*
> ```reStructuredText
> under our new directory::
> 
>    python3 download-pretrained-model.py 
> ```

Almost there, but now you have a trailing space :) Please remove it.

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @CAPTAIN320)

**Comment by CAPTAIN320** [comment]
___
*[Documentation/tutorials/pytorch/index.rst, line 415 at r3](https://reviewable.io/reviews/oscarlab/graphene/2502#-MdrOGs83ikiEnVR2C9H:-MdtYYGBBcjvhMJ-HU4m:bpeq2mg) ([raw file](https://github.com/oscarlab/graphene/blob/fd05c6c2bec80a3b4774aefe7d035663ae826099/Documentation/tutorials/pytorch/index.rst#L415)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Almost there, but now you have a trailing space :) Please remove it.
</blockquote></details>

Oh, sorry about that. It has been removed.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2502#-MduRvY15RqVsNkMvgqy:-MduRvY2-TLyDhzzAsO_:b-3e3eco) (no related file):*
Thanks for the PR! I'm approving now.

---

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2502)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
