### PR TITLE
[Pal/Linux-SGX] Replace SHA256 with HKDF-SHA256 in key derivations

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Pipe session shared key and process session shared key were previously generated using SHA256 as a Key Derivation Function HKDF). However, it is recommended to use HKDF-SHA256 as a KDF.

~~Should be rebased on top of #2380.~~

## How to test this PR? 

All tests must pass. You can use GDB to verify that the new HKDF-SHA256 works as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)

### CODE REVIEW

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: 0 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmpYBL85qJQE6NaF3A:-MbmpYBL85qJQE6NaF3B:b-gi47it) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L43)):*
> ```C
>                               /*salt_size=*/0, (uint8_t*)name->str, sizeof(name->str),
>                               (uint8_t*)session_key, sizeof(*session_key));
>     if (ret < 0) {
> ```

We could simply `return lib_HKDF_SHA256()` if we think logging doesn't add much value.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-Mbmq9lN-O80-JrOx14M:-Mbmq9lO-_VW6TKkd7Mv:b-tgsm40) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L45)):*
> ```C
>     if (ret < 0) {
>         log_error("Failed to derive the pre-shared key for pipe %s: %d\n", name->str, ret);
>         return ret;
> ```

If logging adds value, we can remove this and replace `return 0` with `return ret`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 941 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmrafY-TXgAQ2l567f:-MbmrafY-TXgAQ2l567g:bou6ooz) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L941)):*
> ```C
>     assert(agreesz > 0 && agreesz <= sizeof(agree));
> 
>     ret = lib_HKDF_SHA256(agree, agreesz, /*salt=*/NULL, /*salt_size=*/0, /*info=*/NULL,
> ```

I felt the comment to be useful while reading the code :).
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 949 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmsRmqDClwvKygxX2a:-MbmsRmqDClwvKygxX2b:bhd6n1h) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L949)):*
> ```C
> 
>     log_debug("Key exchange succeeded: %s\n", ALLOCA_BYTES2HEXSTR(*key));
>     ret = 0;
> ```

This seems redundant as `lib_HKDF_SHA256()` would return 0 or a negative PAL error right?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: 0 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmpYBL85qJQE6NaF3A:-Mc9PUtB9FCGSQKOZZf6:biygl67) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L43)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We could simply `return lib_HKDF_SHA256()` if we think logging doesn't add much value.
</blockquote></details>

I think we should keep this log message.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-Mbmq9lN-O80-JrOx14M:-Mc9PZr737sdNn3phmw6:b-pecbfw) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L45)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If logging adds value, we can remove this and replace `return 0` with `return ret`
</blockquote></details>

I prefer to have an explicit `return ret` in error-condition paths.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 941 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmrafY-TXgAQ2l567f:-Mc9PgNsBlY1ciJRlcso:b11519n) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L941)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I felt the comment to be useful while reading the code :).
</blockquote></details>

I don't know what kind of comment to add here. We want to derive a final key `key` from initial key material `agree`. For this we use HKDF function.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 949 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmsRmqDClwvKygxX2a:-Mc9Pv_H9_emf6yBYOLp:b-2kwx7v) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L949)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This seems redundant as `lib_HKDF_SHA256()` would return 0 or a negative PAL error right?
</blockquote></details>

Hm, I would prefer to keep this explicit zero-out.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 13 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: all files reviewed, 4 unresolved discussions (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmpYBL85qJQE6NaF3A:-McG-iow23POlHNdaALe:b-j223nw) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we should keep this log message.
</blockquote></details>

+1 to simplifying, I don't think this can ever fail in practice. But I'm not blocking.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmpYBL85qJQE6NaF3A:-McITeUn8ZT1HmV9jEz5:biszvjl) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to simplifying, I don't think this can ever fail in practice. But I'm not blocking.
</blockquote></details>

Done. Since two people request this, this makes sense to simplify then.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-Mbmq9lN-O80-JrOx14M:-McITjGM-7Gm9NTLPFpR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/db_pipes.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I prefer to have an explicit `return ret` in error-condition paths.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 949 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmsRmqDClwvKygxX2a:-McITlTj9bO5D6TSONiR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L949)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I would prefer to keep this explicit zero-out.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: all files reviewed, 1 unresolved discussion (waiting on @vijaydhanraj)

**Review by dimakuv — COMMENTED** [review]
> Dismissed @vijaydhanraj from a discussion.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 949 at r1](https://reviewable.io/reviews/oscarlab/graphene/2410#-MbmsRmqDClwvKygxX2a:-McJXQdj9BlqhZtnl-Oq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/feca715308d3935e4f4a896a0fb8706cc24b7574/Pal/src/host/Linux-SGX/enclave_framework.c#L949)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2410)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
