### PR TITLE
More clang fixes

### PR DESCRIPTION
**Pull request by pwmarcz**
See https://github.com/oscarlab/graphene/issues/1794.

After these changes, and fixing the alignment problem discussed in above issue, this should be ready to be tested on Jenkins. Once I have Jenkins access, I want to prepare a Jenkinsfile that uses Clang and runs all the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, test this please

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/src/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC5cx-DKID-Rgl9R8K:-MHC5cx-DKID-Rgl9R8L:b-urt093) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/LibOS/shim/src/Makefile#L21)):*
> ```Makefile
> CFLAGS += -Wextra
> 
> CFLAGS += -Wno-gnu-alignof-expression
> ```

Could you add a comment explaining why we need this extra option?
___
*[Pal/regression/Exception.c, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6LH7EKtzFDsND1li:-MHC6LH83LS8AePc7xDf:b-hq1ceq) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception.c#L126)):*
> ```C
>             "divq %%rbx\n"
>             "nop\n"
>             ::: "rax", "rbx");
> ```

this code also clobbers `rdx` and `rflags` ("cc" in GCC asm syntax)
___
*[Pal/regression/Exception.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6Zth1sjqZZWc7WfG:-MHC6Zti-hD5tf5srAt8:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception.c#L135)):*
> ```C
>             "divq %%rbx\n"
>             "nop\n"
>             ::: "rax", "rbx");
> ```

ditto
___
*[Pal/regression/Exception2.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6e9d2WJ3Wn_wz8ph:-MHC6e9d2WJ3Wn_wz8pi:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception2.c#L28)):*
> ```C
>             "divq %%rbx\n"
>             "nop\n"
>             ::: "rax", "rbx");
> ```

ditto

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/src/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC5cx-DKID-Rgl9R8K:-MHC7mppBXro56GKlXK_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/LibOS/shim/src/Makefile#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment explaining why we need this extra option?
</blockquote></details>

Done.
___
*[Pal/regression/Exception.c, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6LH7EKtzFDsND1li:-MHC7stB2Ovu4Xd2TKyq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception.c#L126)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this code also clobbers `rdx` and `rflags` ("cc" in GCC asm syntax)
</blockquote></details>

Done.
___
*[Pal/regression/Exception.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6Zth1sjqZZWc7WfG:-MHC7thO1U4ePLqUBAf6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception.c#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/regression/Exception2.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC6e9d2WJ3Wn_wz8ph:-MHC8Mkb432s0vzJxeVB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/Pal/regression/Exception2.c#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by yamahata — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: 3 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/regression/Exception.c, line 120 at r2](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCK4uY-2jNCRvN-EDP:-MHCK4u_7CK3beIGOZeG:bstixjt) ([raw file](https://github.com/oscarlab/graphene/blob/a4b8715e0ab4fe95fa9b0dfa641dafcc88dcc676/Pal/regression/Exception.c#L120)):*
> ```C
> 
>     DkSetExceptionHandler(handler1, PAL_EVENT_ARITHMETIC_ERROR);
>     __asm__ volatile (
> ```

Is this due to optimization of -O2? or even with -O0?
if -O0 works, we can specify optimization to this function by function attribute of  optimize(“O0”).

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCRwZH4-d80hRXMphV:-MHCRwZH4-d80hRXMphW:b-6utweb) (no related file):*
Could you wrap all three inline assemblies in `#ifdef __x86_64__` + `#error` for other cases?

---
___
*[LibOS/shim/src/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC5cx-DKID-Rgl9R8K:-MHCRR8rEyww_Wa3NVh4:bck2jhl) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/LibOS/shim/src/Makefile#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This macro itself is not causing the issue (it doesn't use alignof), the problem is that some callsites use `alignof` on expressions instead of types when using it, and C11 unfortunately doesn't support such constructions. Could you clarify this in the comment?
___
*[Pal/regression/Exception.c, line 120 at r2](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCK4uY-2jNCRvN-EDP:-MHCRjTc-oVXN6bI3dZl:b-8tp2ru) ([raw file](https://github.com/oscarlab/graphene/blob/a4b8715e0ab4fe95fa9b0dfa641dafcc88dcc676/Pal/regression/Exception.c#L120)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Is this due to optimization of -O2? or even with -O0?
if -O0 works, we can specify optimization to this function by function attribute of  optimize(“O0”).
</blockquote></details>

The previous code is just UB in C, division by 0 is illegal. We need to write this in assembly.
Also, it's a miracle that this `while (*(unsigned char *) context->rip != 0x90) context->rip++;` actually worked, any 0x90 byte emitted by the compiler in between would break it ;)

**Review by yamahata — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCRwZH4-d80hRXMphV:-MHCtcg6AixQVSj00BD7:b-mbcz3x) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you wrap all three inline assemblies in `#ifdef __x86_64__` + `#error` for other cases?
</blockquote></details>

Exception.c and Exception2.c are compiled only when x86-64. Please refer to  executables-x86_64 in Pal/regression/Makefile.

---
___
*[Pal/regression/Exception.c, line 120 at r2](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCK4uY-2jNCRvN-EDP:-MHCsrf37Be64SIt9I_j:beainqu) ([raw file](https://github.com/oscarlab/graphene/blob/a4b8715e0ab4fe95fa9b0dfa641dafcc88dcc676/Pal/regression/Exception.c#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The previous code is just UB in C, division by 0 is illegal. We need to write this in assembly.
Also, it's a miracle that this `while (*(unsigned char *) context->rip != 0x90) context->rip++;` actually worked, any 0x90 byte emitted by the compiler in between would break it ;)
</blockquote></details>

got it.
Hmm, UBsan should have be enabled.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCRwZH4-d80hRXMphV:-MHD9rjp-kEcVmqDD3Il:b26hi82) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Exception.c and Exception2.c are compiled only when x86-64. Please refer to  executables-x86_64 in Pal/regression/Makefile.
</blockquote></details>

Ah, sorry, I forgot about this. Resolving then.

---
___
*[Pal/regression/Exception.c, line 120 at r2](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHCK4uY-2jNCRvN-EDP:-MHD9zlK8QdbMnth4_HZ:b3ecfjf) ([raw file](https://github.com/oscarlab/graphene/blob/a4b8715e0ab4fe95fa9b0dfa641dafcc88dcc676/Pal/regression/Exception.c#L120)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

got it.
Hmm, UBsan should have be enabled.
</blockquote></details>

I think it's runtime-only, so you'd actually need to run code with it being enabled, but after you do this it should detect this, I guess.
Or maybe they assume that `div` will throw an exception on x86 and that's enough already, and it's only our quirk that we silence it?

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1815#-MHC5cx-DKID-Rgl9R8K:-MHFl4I21fXCZHq-Z6aP:bqqp5h2) ([raw file](https://github.com/oscarlab/graphene/blob/a0a58162ec5baf7ab75ab6198dcd9e0184ea30f7/LibOS/shim/src/Makefile#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This macro itself is not causing the issue (it doesn't use alignof), the problem is that some callsites use `alignof` on expressions instead of types when using it, and C11 unfortunately doesn't support such constructions. Could you clarify this in the comment?
</blockquote></details>

OK, I reworded the comment.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by yamahata — DISMISSED** [review]
> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by woju — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1815)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
