### PR TITLE
Miscellaneous Bug fixes

### PR DESCRIPTION
**Pull request by donporter**
Although the unit tests still don't all pass with master or this branch, I believe this branch is, in general, more stable and functional than the current master.

I propose we checkpoint the current state of debugging before merging in some bigger changes.

### CODE REVIEW

**Comment by chiache** [comment]
- [x] **Code review:** no problem spotted

- [x] Describe the testing setup:
  - [x] **Code version:** 3bc014c merged with d922504 (needed the latest driver change)
  - [x] **Linux kernel version:** 4.4.0-21-generic
  - [x] **Ubuntu version:** 16.04.02 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@268b206
  - [x] **SGX driver version:** 01org/linux-sgx-driver@cd51638

- [ ] **Testing:**
  - [ ] **PAL**
    - [x] **Linux host:**
      - [x] **Compilation:** passed
      - [x] **Regression tests:** all passed
    - [x] **Linux+SGX host:**
      - [x] **Compilation:** passed
      - [x] **Regression tests:** all passed

  - [ ] **Library OS**
      - [x] **Compilation:** passed
      - [x] **Linux host:**
        - [x] **Regression tests:** all passed
        - [ ] **LTP tests:**
      - [x] **Linux-SGX host:**
        - [ ] **Regression tests:**
        - [ ] **LTP tests:**

  - [ ] **Applications**

**Comment by chiache** [comment]
The recent versions of LTP have been deleting test cases for some reasons I am not familiar with. To make our regression more stable, I suggest we lock the version of LTP.

**Comment by donporter** [comment]
Is there a PR for 27d5e01 (or can you make one)?  It would be good to keep these base tests working on master before merging more PRs.  Thanks!

**Comment by donporter** [comment]
Let's not merge until I look at the LTP regression; the futex bug looks legit.

**Comment by chiache** [comment]
f55be97 should fix the compilation issue of e6b3821.

All the previously passed LTP tests are passing now, plus a whole bunch of new tests that used to be considered failing because of output passing issues or preparation failures. For the new passed test list, see 2fd334d.

**Pull request merged**
