### PR TITLE
[Docs] Add link to graphene-contrib docs and improve Building

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Small changes to our Building doc + link to https://graphene-contrib.readthedocs.io/en/latest/

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUsrjWCNivPnkrb5TM:-McUsrjXDyeeLbEwoEsZ:b-7gqe66) (no related file):*
> improve Building

"improve building.rst"

---
___
*[Documentation/building.rst, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUuReB584kbGuGdkEf:-McUuReB584kbGuGdkEg:bo7bjfx) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/building.rst#L25)):*
> ```
> 21.04
> ```

Who's testing this one? We don't have it in CI.
___
*[Documentation/building.rst, line 215 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McVGDQkABJO7hz2lgfX:-McVGDQkABJO7hz2lgfY:b-lq0e46) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/building.rst#L215)):*
> ```
> up to date security mitigations.
> ```

Not really true, old kernels only get backports for security fixes, not mitigations.
___
*[Documentation/index.rst, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUu1u4Er0GVnyNz9xX:-McUu1u4Er0GVnyNz9xY:b5fv28q) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/index.rst#L20)):*
> ```
> Documentation
> ```

I'd say "External documentation" or "External resources" instead.
___
*[Documentation/index.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUtH77E48aqOIajWUs:-McUtH7808n7qvrrGAHy:bxha98a) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/index.rst#L23)):*
> ```
> This website contains documentation for the core Graphene functionality. To
> check external contributions, please visit
> ```

Hmm, I don't like how this is written, we basically cover similar components here and there. The only difference is that this is the official and well-reviewed one, and the other is more random and "no warranty included" :)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUsrjWCNivPnkrb5TM:-MchUI9E7e_aKFxQXQg3:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> improve Building

"improve building.rst"
</blockquote></details>

Done.

---
___
*[Documentation/building.rst, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUuReB584kbGuGdkEf:-MchUQAM-Xl6YrPc8DOZ:b-dv6s6i) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/building.rst#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> 21.04
> ```

Who's testing this one? We don't have it in CI.
</blockquote></details>

Done. Yes, let's just mention those versions we have in CI.
___
*[Documentation/building.rst, line 215 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McVGDQkABJO7hz2lgfX:-MchUdTABmiVmB69xMRz:bduaett) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/building.rst#L215)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> up to date security mitigations.
> ```

Not really true, old kernels only get backports for security fixes, not mitigations.
</blockquote></details>

Done. Simply removed this phrase, because it is not relevant here.
___
*[Documentation/index.rst, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUu1u4Er0GVnyNz9xX:-MchUq4pA0-GpSd4nb2Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/index.rst#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Documentation
> ```

I'd say "External documentation" or "External resources" instead.
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2460#-McUtH77E48aqOIajWUs:-MchWJTVDXQVVmXDZJQ_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4757f4acf5626930e60ee8439448274a638bc199/Documentation/index.rst#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> This website contains documentation for the core Graphene functionality. To
> check external contributions, please visit
> ```

Hmm, I don't like how this is written, we basically cover similar components here and there. The only difference is that this is the official and well-reviewed one, and the other is more random and "no warranty included" :)
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2460#-MchXj1t4ijMz6HbuxVv:-MchXj1t4ijMz6HbuxVw:b-i6y6zr) ([raw file](https://github.com/oscarlab/graphene/blob/7a65eaafbbf26b29b151162b86a26ac188c733fb/Documentation/manifest-syntax.rst#L85)):*
> ```reStructuredText
> at that path. For example:
> 
> ::
> ```

FYI: Noticed that it is currently rendered incorrectly, so fixed in this PR.

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Documentation/manifest-syntax.rst, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2460#-MchXj1t4ijMz6HbuxVv:-Mci7gVIAQr1GzZ-Y5ov:bif18ue) ([raw file](https://github.com/oscarlab/graphene/blob/7a65eaafbbf26b29b151162b86a26ac188c733fb/Documentation/manifest-syntax.rst#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Noticed that it is currently rendered incorrectly, so fixed in this PR.
</blockquote></details>

Already fixed in #2454, but I think your fix is better.

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: 2 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2460#-MchXj1t4ijMz6HbuxVv:-MdHFRid2xnv_0DGP05d:b-7xxxmm) ([raw file](https://github.com/oscarlab/graphene/blob/7a65eaafbbf26b29b151162b86a26ac188c733fb/Documentation/manifest-syntax.rst#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Already fixed in #2454, but I think your fix is better.
</blockquote></details>

Rebased on top of your 2454.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2460)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
