### PR TITLE
[LibOS] Check return values of init_brk*() calls

### PR DESCRIPTION
**Pull request by omeg**
Please fill in the following form before submitting this PR and ensure that your code follows our [coding style guideline](../blob/master/CODESTYLE.md).

## Affected components

- [ ] README and global configuration
- [X] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)
- Properly check return values of `init_brk_from_executable()` and `init_brk_region()` calls.
- This is related to https://github.com/oscarlab/graphene/issues/431

## How to test this PR? (if applicable)
Run regression  tests.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/619)

### CODE REVIEW

**Comment by dimakuv** [comment]
Retest this please

**Comment by dimakuv** [comment]
Retest this please

**Comment by dimakuv** [comment]
This PR fails every time on Graphene-SGX's LibOS `shared_object` regression test. @omeg, can you look into this?

**Comment by mkow** [comment]
Retest this please

**Comment by omeg** [comment]
It seems that early `brk` initialization logic in `init_brk_from_executable()` is flawed and always fails for small executables like `shared_object` (which is essentially a "hello world" program). This worked before because glibc does explicit `brk` initialization on startup which succeeds. I'm working on comprehensive fix for #431 which should also fix this, but still have some work to do so let's postpone this PR for now.

**Comment by omeg** [comment]
This change was incorporated in PR #716.

**Pull request closed without merging**
