### PR TITLE
[Pal] Introduce EINTR-safe {read,write}_all wrappers

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

I triggered this bug when implementing directory support in trusted files.

## How to test this PR? 

Generate a huge manifest and try Bash example with iteration count 100.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux/db_streams.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbMp6j3tdqb1llLXOS:-MVbMp6kAPiZ5QkHmCou:b-fil3es) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/db_streams.c#L84)):*
> ```C
> 
> void _DkPrintConsole(const void* buf, size_t size) {
>     write_all(2 /*stderr*/, buf, size);
> ```

Could you change the order to: `/*stderr*/2`?
___
*[Pal/src/host/Linux/pal_linux_error.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbORAt2ZJWKtsWyK3m:-MVbORAt2ZJWKtsWyK3n:bcohu8v) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/pal_linux_error.h#L13)):*
> ```objc
>     switch (unix_errno) {
>         case ENOENT:
>             return -PAL_ERROR_STREAMNOTEXIST;
> ```

This is definitely not positive :)
___
*[Pal/src/host/Linux/pal_linux_error.h, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOTsw0B_AY1GmpZC3:-MVbOTsw0B_AY1GmpZC4:b-fpuune) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/pal_linux_error.h#L50)):*
> ```objc
>  * \brief Translate UNIX error code into PAL error code.
>  *
>  * The sign of the error code is preserved.
> ```

It's inverted :)
___
*[Pal/src/host/Linux-common/file_utils.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbD-_U25DPeAmhQsIt:-MVbD-_V3hrRIJ_zpS2O:b-5fsgs2) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L18)):*
> ```C
>     size_t bytes_read = 0;
>     while (bytes_read < size) {
>         int ret = INLINE_SYSCALL(read, 3, fd, buf + bytes_read, size - bytes_read);
> ```

Please use `ssize_t` or `long`
___
*[Pal/src/host/Linux-common/file_utils.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbD9ZU7pmO45-qoCnG:-MVbD9ZU7pmO45-qoCnH:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L34)):*
> ```C
>     size_t bytes_written = 0;
>     while (bytes_written < size) {
>         int ret = INLINE_SYSCALL(write, 3, fd, buf + bytes_written, size - bytes_written);
> ```

ditto
___
*[Pal/src/host/Linux-common/file_utils.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbFjaWDdhxXu6qt6Uw:-MVbFjaX1Hzei1xGx4Hf:b-153klw) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L38)):*
> ```C
>             if (ret == -EINTR)
>                 continue;
>             return ret;
> ```

Please either handle `0` here to treat it as impossible and change condition to `< 0`.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 428 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOgJKCXjjMaiyNetH:-MVbOgJKCXjjMaiyNetI:bmip6bl) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/db_streams.c#L428)):*
> ```C
>     ssize_t ret = ocall_write(g_log_fd, buf, size);
>     if (ret < 0 || (size_t)ret != size) {
>         return IS_ERR(ret) ? unix_to_pal_error(ret) : -PAL_ERROR_INTERRUPTED;
> ```

Please unify error checking (preferably to `ret < 0`)
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOtG44CiCbw8dkCZm:-MVbOtG44CiCbw8dkCZn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/pal_linux_error.h#L13)):*
> ```objc
>     switch (unix_errno) {
>         case ENOENT:
>             return -PAL_ERROR_STREAMNOTEXIST;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOtu_12SBMZqwjbY_:-MVbOtu_12SBMZqwjbYa:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/pal_linux_error.h#L50)):*
> ```objc
>  * \brief Translate UNIX error code into PAL error code.
>  *
>  * The sign of the error code is preserved.
> ```

ditto

**Review by mkow — COMMENTED** [review]
FYI: I force-pushed to fix commit message (Borys complained about it on priv).

> Reviewed 1 of 16 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232#-:-MVbV_BZ1ysAlPlAPknL:b-viv93p)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVcIdHl359FZvfqu-e2:-MVcIdHm0X6pNoroXF3X:b-w08nlh) (no related file):*
FYI: This PR depends on #2234 (I decided to split-off the error handling changes).

---
___
*[Pal/src/host/Linux/db_streams.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbMp6j3tdqb1llLXOS:-MVbQ7wU6ZT2gYLd9tki:b-vnbrvp) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/db_streams.c#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you change the order to: `/*stderr*/2`?
</blockquote></details>

this was on purpose, to not look like a named arg
___
*[Pal/src/host/Linux/pal_linux_error.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbORAt2ZJWKtsWyK3m:-MVbQLr10QSRJ2wnbn5J:b9ou74h) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/pal_linux_error.h#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is definitely not positive :)
</blockquote></details>

Ooops. Fixed (in #2234, and reverted from here).
___
*[Pal/src/host/Linux/pal_linux_error.h, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOTsw0B_AY1GmpZC3:-MVbR-tD4dSXKQ4rjSXZ:bwi4576) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/pal_linux_error.h#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's inverted :)
</blockquote></details>

Not anymore!
___
*[Pal/src/host/Linux-common/file_utils.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbD-_U25DPeAmhQsIt:-MVbRMYw3l6bzAQy1qNo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `ssize_t` or `long`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/file_utils.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbD9ZU7pmO45-qoCnG:-MVbRMzl-RHYltWauMJt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/file_utils.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbFjaWDdhxXu6qt6Uw:-MVbRuWN2xkOiW2iFTFx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-common/file_utils.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please either handle `0` here to treat it as impossible and change condition to `< 0`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 428 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOgJKCXjjMaiyNetH:-MVbT4mGA4ORBZkDfe5J:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/db_streams.c#L428)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please unify error checking (preferably to `ret < 0`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOtG44CiCbw8dkCZm:-MVbT61b1lIvtdK8NK1Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/pal_linux_error.h#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbOtu_12SBMZqwjbY_:-MVbT6U5DwKnUhnqRbDB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux-SGX/pal_linux_error.h#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: 7 of 20 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVcIdHl359FZvfqu-e2:-MVrfJaD9uyqo_MR0_Yp:b-g2ywk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: This PR depends on #2234 (I decided to split-off the error handling changes).
</blockquote></details>

Not anymore, merged and rebased on top of it.

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_streams.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbMp6j3tdqb1llLXOS:-MVrhumtB6hhznhjkzyI:b6kdbwo) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/db_streams.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this was on purpose, to not look like a named arg
</blockquote></details>

Well, to looks ugly to me and I would remove it completely then.
Not important and was already here, so unblocking.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_streams.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2232#-MVbMp6j3tdqb1llLXOS:-MVrm2ml5btetwhNiE9r:b-w3uz5l) ([raw file](https://github.com/oscarlab/graphene/blob/462f87aecdd759dd140aa094b82c6c243b5c6d42/Pal/src/host/Linux/db_streams.c#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, to looks ugly to me and I would remove it completely then.
Not important and was already here, so unblocking.
</blockquote></details>

I prefer the current version. Removing would leave that "2" as a standalone, unexplained constant, and shifting the comment before it would make it look like "stderr" was the name of this argument.

**Review by yamahata — DISMISSED** [review]
> Reviewed 5 of 16 files at r1, 2 of 5 files at r2, 13 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2232)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (`apps.LTP.fork06` failed - unrelated to this PR, but Borys is looking at it)

**Comment by boryspoplawski** [comment]
#2241 for the fork issue (hopefully)

**Pull request merged**
