### PR TITLE
[Pal/lib] Fix data race on memory allocation in slab memory manager

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Slab memory manager logic uses enlarge_slab_mgr() (renamed to more accurate maybe_enlarge_slab_mgr()) to allocate a new chunk of memory for its slab objects. For allocation itself, slab manager must release the lock before system malloc and then re-acquire it. At this point other threads may allocate memory for the same slab level. Also, system malloc may fail to allocate large memory region, and slab logic will fall back to allocating smaller memory region. These two issues were not properly handled; this commit fixes these bugs.

Interestingly, this fix is exactly the same as in Isaku's #1347.

Closes #1347 (with my current PR, we'll merge all bug fixes that Isaku introduced in that PR).

## How to test this PR? 

This bug was detected and debugged on a large application running with >160 threads. Here is a backtrace that gives some insight into where it happened (when LibOS tried to allocate a new internal "async event" object during thread 137 destruction, and several threads collided on enlarging a new slab-allocator area):
```
(gdb) bt
#0  slab_alloc (mgr=0x7e345d000, size=56) at ../../../Pal/include/lib/slabmgr.h:344
#1  0x00000007f3480cf8 in malloc (size=56) at shim_malloc.c:92
#2  0x00000007f34770d6 in install_async_event (object=0x0, time=0, callback=0x7f349e258 <cleanup_thread>, arg=0x7de93d020) at shim_async.c:67
#3  0x00000007f34d5d16 in thread_exit (error_code=0, term_signal=0) at sys/shim_exit.c:132
#4  0x00000007f34d5fc9 in shim_do_exit (error_code=0) at sys/shim_exit.c:231
#5  0x00000007f3487e6d in __shim_exit (__arg1=0) at shim_syscalls.c:230
#6  0x00000007f34951d5 in syscalldb () at syscallas-x86_64.S:71
#7  0x00000007e167fad1 in start_thread ()
```

Unfortunately, I don't know how to reproduce this data race on a small example.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)

### CODE REVIEW

**Comment by dimakuv** [comment]
> Interestingly, this fix is exactly the same as in Isaku's #1347.

I now have a rule "If there is a complex bug, first check if Isaku already fixed it, but we didn't merge his fix".

Also, debugging SGX enclaves with GDB is a very pleasant experience now thanks to Pawel.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/include/lib/slabmgr.h, line 296 at r1](https://reviewable.io/reviews/oscarlab/graphene/1935#-MLDTGSR2WX_DqYS8HJA:-MLDTGSR2WX_DqYS8HJB:bx0wkfu) ([raw file](https://github.com/oscarlab/graphene/blob/eeda995edc49dced1d702dbf54135c336cb91096/Pal/include/lib/slabmgr.h#L296)):*
> ```objc
>      * list for later use. */
>     LISTP_ADD(area, &mgr->area_list[level], __list);
>     if (mgr->size[level] == size) /* check if the size has changed */
> ```

Bug number 1: `size` may change if a large-size allocation failed above (size is halved after each failed allocation), and then we don't end up in `__set_free_slab_area()` which is wrong.
___
*[Pal/include/lib/slabmgr.h, line 299 at r1](https://reviewable.io/reviews/oscarlab/graphene/1935#-MLDT_kx7W7skNpmvWAF:-MLDT_kx7W7skNpmvWAG:b-e7t2dv) ([raw file](https://github.com/oscarlab/graphene/blob/eeda995edc49dced1d702dbf54135c336cb91096/Pal/include/lib/slabmgr.h#L299)):*
> ```objc
>         __set_free_slab_area(area, mgr, level);
> 
>     return 0;
> ```

Bug number 2: there was no `while` loop. There is a data race when our thread was de-scheduled, and other threads enlarged `mgr->addr[level]` and also these other threads consumed all this enlarged memory. Then, when our thread is scheduled again, `mgr->size[level]` is of course different (other threads bumped it), and our thread doesn't end up in `__set_free_slab_area()`. But since other threads consumed all enlarged memory, `mgr->addr[level]` points past the allowed memory area. But our thread simply `return 0`, and the caller `slab_alloc()` incorrectly puts an object past the allowed memory area.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test failed, unrelated)

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: all files reviewed, 2 unresolved discussions

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1935)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
