### PR TITLE
[LibOS] Remove native/ and benchmark/ tests

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Applications under native/ and benchmark/ cannot be built after commit "Introduce one, central manifest, zero-config children and constant MRENCLAVE". Simply remove them, nobody uses them.

~~Depends on #2092. Needs to be rebased on top of it.~~

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: 0 of 67 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MR4fHzL22JGZtvbcLoG:-MR4fHzL22JGZtvbcLoH:b-20795n) (no related file):*
I got tired of these, and now they also don't even start (because of the missing `libos.entrypoint` in their manifests).

Nobody tests them, nobody cares about them, let's just remove them finally. We wanted to cherry-pick good ones to move under `regression/`, but let's just burn them finally. I don't think anyone will volunteer to find "good ones" amount them.

---

**Review by yamahata — DISMISSED** [review]
> Reviewed 67 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MR4fHzL22JGZtvbcLoG:-MR64p4B5ZzRq4H2R7tA:b-7j984c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I got tired of these, and now they also don't even start (because of the missing `libos.entrypoint` in their manifests).

Nobody tests them, nobody cares about them, let's just remove them finally. We wanted to cherry-pick good ones to move under `regression/`, but let's just burn them finally. I don't think anyone will volunteer to find "good ones" amount them.
</blockquote></details>

On the other hand some are known not to work due to bugs in Graphene, which should be debugged and fixed, e.g. https://github.com/oscarlab/graphene/issues/62

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MR4fHzL22JGZtvbcLoG:-MRJQNIIAwlSY9oxWupp:b-k9c6b0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On the other hand some are known not to work due to bugs in Graphene, which should be debugged and fixed, e.g. https://github.com/oscarlab/graphene/issues/62
</blockquote></details>

I just tested `exec_fork` from #62, it works on the latest master.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 67 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MRKjQZU7wB1OhJqO5s9:-MRKjQZVDBlT8RkYrH3a:b-uroxif) (no related file):*
> [LibOS] Remove native/ and benchmark/ tests
> 
> Applications under native/ and benchmark/ cannot be built after commit
> "Introduce one, central manifest, zero-config children and constant
> MRENCLAVE".

The explanation in the commit message doesn't justify/explain why we just remove them instead of fixing, please elaborate (as you did here, in Review).

---

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 67 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MR4fHzL22JGZtvbcLoG:-MRLXjOj5bTs-C0BHJnt:baui33g) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just tested `exec_fork` from #62, it works on the latest master.
</blockquote></details>

Hm, I thought I've tested it recently and it did not ... Well it does now :)

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MR4fHzL22JGZtvbcLoG:-MRLx8-m9rSeCSpvOorO:b-wtym) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, I thought I've tested it recently and it did not ... Well it does now :)
</blockquote></details>

I guess the latest changes by Borys and Michal on the `execve` behavior fixed whatever happened there.

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2093#-MRKjQZU7wB1OhJqO5s9:-MRLzdxQ2JIV6PxMUbI6:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [LibOS] Remove native/ and benchmark/ tests
> 
> Applications under native/ and benchmark/ cannot be built after commit
> "Introduce one, central manifest, zero-config children and constant
> MRENCLAVE".

The explanation in the commit message doesn't justify/explain why we just remove them instead of fixing, please elaborate (as you did here, in Review).
</blockquote></details>

Done.

---

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2093)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (weird failure, the log just ends in the middle of running `httpd`, shows exit code 111 and nothing more - despite this pipeline having debug log enabled)

**Pull request merged**
