### PR TITLE
Reformat C sources, final iteration

### LINKED ISSUE #539: Format existing code according to code style
I'm sure this already planned but I didn't find a ticket for it.

Automatic reformatting is very useful to get consistent code style without much work and discussions. But due to the big amount of not yet reformatted code the `make format` target is not very helpful at the moment (too many unrelated changes to filter out).

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes

We have quite a low number of open PRs at the moment and a lot of intensive development ahead, so I decided this is a good time to finish the reformatting efforts, this time without the conflict-detection script (as used in older iterations, see #856). It may be a bit disruptive, but we probably won't have a better time to do this. Also, I skipped some changes to not conflict with open PRs which will be merged soon and include these reformats already.

Ad the changes itself:
* I ran `make format` on the whole repo and reviewed the diff. Unfortunately a lot of changes needed to be manually reverted or fixed up because of clang-format bugs (it seems to work much better for C++ than C).
* Our headers are mess, trying to sort includes blew up the builds in a lot of funny ways. I corrected what I could and skipped + commented places where I gave up. One huge issue is that we should have our own headers with kernel constants and structs and not take it from the host system during build (we're emulating a particular kernel version after all, not the one on the build machine).
* Some clang-format changes didn't increase readability, but I kept them if the result was neutral in my opinion, to make our codebase more clang-format compatible in case we decide to run clang-format as part of our CI checks in the future.

As noted in the previous PRs, so far clang-format integration is definitely not ready to be enabled as part of CI or for commit pre-hooks. I'll file all found bugs to the developers and we'll see.

Closes #539.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1806)

### CODE REVIEW

**Review by mkow — COMMENTED** [review]
> Reviewed 271 of 273 files at r1, 4 of 4 files at r2, 81 of 81 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1806)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/include/arch/x86_64/Linux/ucontext.h, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/1806#-MGt0nKgCxMNFVZDGaCg:-MGt0nKh0_xpugcfbsBV:buo5lcc) ([raw file](https://github.com/oscarlab/graphene/blob/810c6666d44f40b390a182dcc87c75ff64af8ea4/Pal/include/arch/x86_64/Linux/ucontext.h#L26)):*
> ```objc
> 
> /* We need the signal context definitions even if they are not used
>    included in <signal.h>.  */
> ```

FYI: I don't understand this comment, both on English and on technical level. I didn't have enough courage and energy to touch this.

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 273 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1806)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1806)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 200 of 273 files at r1, 2 of 4 files at r2, 81 of 81 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1806)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
