### PR TITLE
[Doc] Adjust language in the readme

### PR DESCRIPTION
**Pull request by donporter**
## Description of the changes 

Adjust language in the readme to be more clear about the state of the project, per last team discussion.

## How to test this PR? 

N/A

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1808)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1808)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[README.rst, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/1808#-MGriqvbCi82u6PMh3tM:-MGriqvbCi82u6PMh3tN:bfrcq7b) ([raw file](https://github.com/oscarlab/graphene/blob/f2419405721eb6340c0278cdafcbdc7a84c21650/README.rst#L48)):*
> ```
> link here
> ```

Seems it's not here :)
___
*[README.rst, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/1808#-MGrjRnT8siz9oeWn5oL:-MGrjRnUE1uccJphKbVh:b-a49vy8) ([raw file](https://github.com/oscarlab/graphene/blob/f2419405721eb6340c0278cdafcbdc7a84c21650/README.rst#L48)):*
> ```
> roughly by fall of 2021
> ```
Isn't this missing "the"?

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1808)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

___
*[README.rst, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/1808#-MGriqvbCi82u6PMh3tM:-MGtkwdn7GqaHJlfYhwb:bh0k8uq) ([raw file](https://github.com/oscarlab/graphene/blob/f2419405721eb6340c0278cdafcbdc7a84c21650/README.rst#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> link here
> ```

Seems it's not here :)
</blockquote></details>

Oops.  That is embarrassing.  Since the link is in the next paragraph, I just took it out.
___
*[README.rst, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/1808#-MGrjRnT8siz9oeWn5oL:-MGtl1LY8NZ5CBD4xZlX:b-m9h18d) ([raw file](https://github.com/oscarlab/graphene/blob/f2419405721eb6340c0278cdafcbdc7a84c21650/README.rst#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> roughly by fall of 2021
> ```
Isn't this missing "the"?
</blockquote></details>

This is a case (at least in American English) where dropping the article is idiomatically accepted (although usually without the "of").  But happy to add "the".

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1808)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[README.rst, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/1808#-MGrjRnT8siz9oeWn5oL:-MGuU-DKBX0mzIVTT-B2:bx0uwwt) ([raw file](https://github.com/oscarlab/graphene/blob/f2419405721eb6340c0278cdafcbdc7a84c21650/README.rst#L48)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

This is a case (at least in American English) where dropping the article is idiomatically accepted (although usually without the "of").  But happy to add "the".
</blockquote></details>

Didn't know this, thanks for the explanation!

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1808)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
