### PR TITLE
DO NOT REVIEW!!! - Rework signal handling - WIP

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
This PR completely reworks signal handling and (as a side effect) syscall emulation in LibOS.
More info in commit message and appropriate places in code.

Please point me to places in the code that need more comments/explanation.

Closes #1218

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071)* status: 0 of 77 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQivxqn0i699QvGcj1B:-MQivxqn0i699QvGcj1C:b-kpol7e) (no related file):*
There is (at least) one known issue: I don't know how to handle a case, where we are executing a blocking syscall (e.g. `read`) and a signal comes after we enter LibOS, but before we do actual blocking host syscall. In such case we will just block and handle the signal only when returning to the user app (which can take arbitrarily long, since `read` can block indefinitely.
I see only one solution: just say that signals can arrive anytime and ignore the problem :) There is one caveat tho: we would need to change the way `time_to_die` is handled - probably introduce something like old preemption counter and check it every time we reach `0` (i.e. when we give up last lock). Generally speaking - doable.

---
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 285 at r1](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQix8ppChR8O1DESOx-:-MQix8ppChR8O1DESOx0:b1gf12p) ([raw file](https://github.com/oscarlab/graphene/blob/a7dee5022303e67e694bfb203326c8a3b8c9b11e/Pal/src/host/Linux-SGX/db_exception.c#L285)):*
> ```C
> /* TODO: shouldn't this function ignore sync events???
>  * actually what is the point of this function? */
> noreturn void _DkHandleExternalEvent(PAL_NUM event, sgx_cpu_context_t* uc,
> ```

Summon @dimakuv @yamahata

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071)* status: 0 of 77 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/shim_parser.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQj3xFIBxc5Z3MAvudC:-MQj3xFIBxc5Z3MAvudD:b-6ubwew) ([raw file](https://github.com/oscarlab/graphene/blob/4ceec99bf6f5c744a78bbe2b5854bb487342ec32/LibOS/shim/src/shim_parser.c#L70)):*
> ```C
>     const char* name;
>     void (*parser[7])(va_list*);
> } syscall_parser_table[LIBOS_SYSCALL_BOUND] = {
> ```

I'll fix alignment issues here, once this solution is accepted as mergeable.

**Review by stefanberger — COMMENTED** [review]
The perfect storm ... I wished this was broken up into multiple smaller patches that each work and can be re-based upon easier...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071#-:-MQmTRyq7DazLlLiNeEz:by5gs5r)* status: 0 of 78 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by stefanberger — COMMENTED** [review]
> Reviewed 12 of 77 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071)* status: 13 of 80 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_parser.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQj3xFIBxc5Z3MAvudC:-MQmp9ND7a3wNhsUUMck:bdz5pys) ([raw file](https://github.com/oscarlab/graphene/blob/4ceec99bf6f5c744a78bbe2b5854bb487342ec32/LibOS/shim/src/shim_parser.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll fix alignment issues here, once this solution is accepted as mergeable.
</blockquote></details>

Cannot split this off?

**Review by stefanberger — COMMENTED** [review]
> Reviewed 6 of 77 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071)* status: 19 of 80 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_dup.c, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQmrpRG8AqMhZiKqKYj:-MQmrpRG8AqMhZiKqKYk:bu401d2) ([raw file](https://github.com/oscarlab/graphene/blob/0222019b109904ffa78cdabbfb0d9ed10827ec7b/LibOS/shim/src/sys/shim_dup.c#L19)):*
> ```C
> #include "shim_utils.h"
> 
> long shim_do_dup(unsigned int fd) {
> ```

would be nice if we could split this type of change off

**Review by stefanberger — COMMENTED** [review]
Even if the mere changes in function return type, like changed from `int` to `long` could be split off, that would help.

Which file contains the arch-specific interface?

> Reviewed 25 of 77 files at r1, 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071#-:-MQmtaqD2HiBw-ZSeCwx:b9xpssr)* status: 46 of 80 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by stefanberger — COMMENTED** [review]
@boryspoplawski I could give this a try.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071#-:-MQn7I5p0JycJwEtDNP9:b-oxw21t)* status: 46 of 80 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — COMMENTED** [review]
Does function definition changes collide with our fork changes? I thought they are the same ...
But yeah, this change is self-contained and can be split.

`shim_syscalls.c` contains new syscall entry point, arch specific wrapper (syscalldb) just calls it (no more direct calling function from syscall table)
`shim_context-x86.c` contains all x86 specific context manipulations.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071#-:-MQnj1o86_ivt0yLOJED:b-xyqgmy)* status: 46 of 80 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)

___
*[LibOS/shim/src/shim_parser.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/2071#-MQj3xFIBxc5Z3MAvudC:-MQnl5Vf7f29CVOTqnv0:b-hoc7cb) ([raw file](https://github.com/oscarlab/graphene/blob/4ceec99bf6f5c744a78bbe2b5854bb487342ec32/LibOS/shim/src/shim_parser.c#L70)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Cannot split this off?
</blockquote></details>

Probably not, but maybe I could change rest of the code only a bit with some workarounds to split this.

**Review by boryspoplawski — COMMENTED** [review]
Ok, I'm closing this PR, I'll try to split as much as I can (probably with some temporary workarounds to fit changes in smaller PRs).

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2071#-:-MQnl_yg9QpJHHmVYiXP:bbcqcje)* status: 46 of 80 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)

**Pull request closed without merging**
