### PR TITLE
Fixes for issues found by Klocwork

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

See commit messages for the details.

## How to test this PR? 

Read the fixes carefully, almost all of them are on error paths.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB2b60-FMDB-sZwH8T:-McB2b60-FMDB-sZwH8U:b9gvxzj) (no related file):*
Commit messages:
1st: I would elaborate e.g. that it's already used before
2nd: I would add "return value" somewhere (and probably move 2nd part to the commit body, e.g. "This commit also fixes some resource leaks related to missing `free` on error return paths")
3rd: `better to not rely on` -> `better not to rely on`
4th: this one is really vague, like I have no idea what it talks about (without checking diff)

I would also put all symbol names in commit messages inside ``, but not blocking on this.

---
___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McB64O69sigdMLO8hlm:b-bcu1ra) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
> ```C
> static struct link_map* map_elf_object_by_handle(PAL_HANDLE handle, enum object_type type,
>                                                  void* fbp, size_t fbp_len, bool do_copy_dyn) {
>     struct link_map* l = new_elf_object(_DkStreamRealpath(handle), type);
> ```

Please add an assert then.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 457 at r3](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB1aAH5nNkhMAnHwPb:-McB1aAH5nNkhMAnHwPc:b-9fg61d) ([raw file](https://github.com/oscarlab/graphene/blob/63ab85ec0bc9e15d1ce503002db63496f09506ab/Pal/src/host/Linux-SGX/db_misc.c#L457)):*
> ```C
>     int ret;
>     bool is_epid;
>     sgx_spid_t spid;
> ```

Why not just ` = { 0 };` here?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 149 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB45YHEelkRsfqz2UP:-McB45YHEelkRsfqz2UQ:b27tost) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L149)):*
> ```C
>     if (!ms) {
>         // We can't really recover from here. Should be unreachable without the host doing malicious
>         // things.
> ```

Please use `/* */` for multi-line comments.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 150 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB4IXu7JvyNcXUgmgu:-McB4IXu7JvyNcXUgmgv:bk7g9ma) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L150)):*
> ```C
>         // We can't really recover from here. Should be unreachable without the host doing malicious
>         // things.
>         while (1) {}
> ```

This is UB.
We have a function for such things: `die_or_inf_loop` (would also need `cpu.h` include).
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McB0L-h2DDCI9ApP9yl:b-2n8j1g) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
> ```C
>     char memdev_path[40];
>     uint64_t flags;
>     long int sc_ret;
> ```

Could you pick a better name? I have no idea what `sc` means...
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 220 at r7](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB5KVJ14qjNeZws3U5:-McB5KVJ14qjNeZws3U6:bj7hy6y) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L220)):*
> ```C
>     }
> 
>     if (path && strlen(path) > PATH_MAX_SIZE - 1) {
> ```

Why this check is redundant? Is it part of the interface? If so please add an `assert`.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB6CUw3t3hEEclv_dW:-McB6CUy3e2TU9tN8XYW:b9o0xny) (no related file):*
2 SGX pipelines failed, please check :)

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: 14 of 17 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB2b60-FMDB-sZwH8T:-McBcIxl5-zsCJyhp7RS:bk5odft) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Commit messages:
1st: I would elaborate e.g. that it's already used before
2nd: I would add "return value" somewhere (and probably move 2nd part to the commit body, e.g. "This commit also fixes some resource leaks related to missing `free` on error return paths")
3rd: `better to not rely on` -> `better not to rely on`
4th: this one is really vague, like I have no idea what it talks about (without checking diff)

I would also put all symbol names in commit messages inside ``, but not blocking on this.
</blockquote></details>

Will do at rebase.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB6CUw3t3hEEclv_dW:-McBkioz3CyOkBiSwKix:b-wnfc40) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

2 SGX pipelines failed, please check :)
</blockquote></details>

Fixed (see the reverted change in PF).

---
___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McBZD_u-LrrwKaxnepz:b1d52z9) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add an assert then.
</blockquote></details>

Why? Why not to also assert `fbp != NULL`? Or that `type` is a valid enum value?
`NULL` is an invalid value for a pointer unless the function documentation clearly says that you can use it as a magic value. Especially that this function has "by handle" in its name, passing NULL as handle doesn't make any sense.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 457 at r3](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB1aAH5nNkhMAnHwPb:-McBc1fH5Ps46cO4RI-l:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/63ab85ec0bc9e15d1ce503002db63496f09506ab/Pal/src/host/Linux-SGX/db_misc.c#L457)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not just ` = { 0 };` here?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 149 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB45YHEelkRsfqz2UP:-McBaowu6UYSpjk7CzUy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L149)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `/* */` for multi-line comments.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 150 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB4IXu7JvyNcXUgmgu:-McB_ssQE4MgPau_IaUW:btiada6) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is UB.
We have a function for such things: `die_or_inf_loop` (would also need `cpu.h` include).
</blockquote></details>

Not in C11, if the condition is constant then it's well defined.
Anyways, switched to `die_or_inf_loop()` for better name.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McBayr85pS7SSr0SmeJ:b-1gbc9l) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you pick a better name? I have no idea what `sc` means...
</blockquote></details>

Syscall. Any better ideas?
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 220 at r7](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB5KVJ14qjNeZws3U5:-McBbDNeAR6bUNqCZqmT:b-qf1rf) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L220)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this check is redundant? Is it part of the interface? If so please add an `assert`.
</blockquote></details>

I reverted this commit, turns out that this argument is not actually the `path` to open, but the path to validate with the path written inside the protected file header. So, it's optional, but only if `create == false`, in the other case it's mandatory... (and that's where the static checker got confused)

Anyways, seems there's no bug, just an obscure and undocumented interface :/ We need to clean this up at some point.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McE65AS3FXL91fkL4bW:bdbgt7k) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
Because the old code clearly (but incorrectly) handled such case and printed `cannot stat shared object`, so this means that there are possible cases of `handle == NULL` (from shared objects, for whatever reason). Maybe `_DkStreamRealpath` handles `NULL` as well and this check was needed? For some reason the old version accounted for it and you've changes the interface - that a good candidate for an assert to me.
> unless the function documentation clearly says that you can use it as a magic value. 

So please point me to the documentation of this function and it's interface (no, the string above is not enough).
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 150 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB4IXu7JvyNcXUgmgu:-McE2ZnS5qTTwl0pN88t:beonl41) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L150)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not in C11, if the condition is constant then it's well defined.
Anyways, switched to `die_or_inf_loop()` for better name.
</blockquote></details>

TIL
You did not add `cpu.h` include, please do.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McE79mcBR5Y2dNl4n09:bvja9q6) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Syscall. Any better ideas?
</blockquote></details>

I would just revert the old version and reuse `ret` or, more preferably, use different variable on each call site, e.g. `tcs_flags`.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 220 at r7](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB5KVJ14qjNeZws3U5:-McE3O465pJlvi8SmPf4:b-rwrg1c) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L220)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I reverted this commit, turns out that this argument is not actually the `path` to open, but the path to validate with the path written inside the protected file header. So, it's optional, but only if `create == false`, in the other case it's mandatory... (and that's where the static checker got confused)

Anyways, seems there's no bug, just an obscure and undocumented interface :/ We need to clean this up at some point.
</blockquote></details>

I see it's used in `DEBUG_PF`, so maybe that's why it got confused (`%s` handles `NULL` pointers, tho I'm not sure if this is mandated somewhere).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: 15 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McE89Pm4Kya8yyZp8Lo:be7id8a) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
> Because the old code clearly (but incorrectly) handled such case and printed `cannot stat shared object`, so this means that there are possible cases of `handle == NULL` (from shared objects, for whatever reason).

Nah, this was dead code, I checked the callsites and none of them seem to allow this.

> So please point me to the documentation of this function and it's interface (no, the string above is not enough).

There's none, and this is the problem, not missing asserts. If you really want I can try to document this, but this code will hopefully be deleted soon anyways.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 150 at r6](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB4IXu7JvyNcXUgmgu:-McE92OPD67fOguwwQ2I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ef7f5e271bcdb0e48e3c3f80dbdce37c90b22e1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TIL
You did not add `cpu.h` include, please do.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McE94gC7tpSqlo_cH2G:b-sotwwh) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would just revert the old version and reuse `ret` or, more preferably, use different variable on each call site, e.g. `tcs_flags`.
</blockquote></details>

But the problem is that `ret` had wrong type, that's why I added another variable, for syscall/libc APIs retvals.
`tcs_flags`? In which line this makes sense?

Anyways, changed to use separate vars in each place.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 220 at r7](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB5KVJ14qjNeZws3U5:-McECBDS362PXrbcJy8a:b9pcorj) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L220)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I see it's used in `DEBUG_PF`, so maybe that's why it got confused (`%s` handles `NULL` pointers, tho I'm not sure if this is mandated somewhere).
</blockquote></details>

Not really, it's because of `ipf_init_new_file()` which internally assumes `path != NULL` and the code path leading to it is seemingly allowing `NULL`.

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McEVPq4CZh05foCpkKU:b-635tt8) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Because the old code clearly (but incorrectly) handled such case and printed `cannot stat shared object`, so this means that there are possible cases of `handle == NULL` (from shared objects, for whatever reason).

Nah, this was dead code, I checked the callsites and none of them seem to allow this.

> So please point me to the documentation of this function and it's interface (no, the string above is not enough).

There's none, and this is the problem, not missing asserts. If you really want I can try to document this, but this code will hopefully be deleted soon anyways.
</blockquote></details>

Sometimes asserts are a good way of documenting interface (well, good addition to normal docs).
Resolving only because it's `rtld.c`
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McEVmWg5uAU1eo2MkKf:bolad01) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
> But the problem is that ret had wrong type, that's why I added another variable, for syscall/libc APIs retvals.

It was `long`, so what was wrong? That we collapsed it to `int`  on return? Since it held `0` and error codes it was fine, but the current version is better.

>  tcs_flags? In which line this makes sense?

nvm, I thought it's read using `PTRACE_PEEKDATA`, but it's actually `pread`
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 436 at r13](https://reviewable.io/reviews/oscarlab/graphene/2441#-McEWahW5BV9ExMPdxQp:-McEWahW5BV9ExMPdxQq:b-7ywf08) ([raw file](https://github.com/oscarlab/graphene/blob/7f5b96d67c3862b074e4ae09d208e3c66a6eb8b5/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L436)):*
> ```C
> 
>         ssize_t bytes_read = pread(fd, &flags, sizeof(flags), (off_t)flags_addr);
>         if (bytes_read < sizeof(flags)) {
> ```

Hmm, shouldn't this generate a compiler warning? (signed vs unsigned comparison)
(existing issue, not blocking)
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 449 at r13](https://reviewable.io/reviews/oscarlab/graphene/2441#-McEWgJfAdxi2j8RhWFY:-McEWgJfAdxi2j8RhWFZ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7f5b96d67c3862b074e4ae09d208e3c66a6eb8b5/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L449)):*
> ```C
> 
>         ssize_t bytes_written = pwrite(fd, &flags, sizeof(flags), (off_t)flags_addr);
>         if (bytes_written < sizeof(flags)) {
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: 16 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/db_rtld.c, line 123 at r8](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB64O69sigdMLO8hll:-McE_kk1CdDsgGP9WV9M:b587frj) ([raw file](https://github.com/oscarlab/graphene/blob/d63e9aea0bfdbca2ded032c5cfff4f0ac5e07424/Pal/src/db_rtld.c#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sometimes asserts are a good way of documenting interface (well, good addition to normal docs).
Resolving only because it's `rtld.c`
</blockquote></details>

I agree, but we should default to some sane assumptions to not need to start every function with a long list of asserts. E.g.:

- That if an arg is an enum, then the only valid values are the ones defined in its declaration.
- That pointers have to be valid.
- `char*` arrays are NULL terminated.

... and so on.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB0L-g-8iyU9gTXXfv:-McEaUQSA4KioWEdA4MP:b-ukq044) ([raw file](https://github.com/oscarlab/graphene/blob/4c1a8e453a314e63f52b110a841fe06bdac10b4c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L377)):*
> That we collapsed it to int  on return? Since it held 0 and error codes it was fine, but the current version is better.

Yup, I don't like this silent downcasting, I hope that someday we'll be able to turn on warnings about casting which can lose data.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 436 at r13](https://reviewable.io/reviews/oscarlab/graphene/2441#-McEWahW5BV9ExMPdxQp:-McEao3dBti5OaIjPZK8:bqb3efo) ([raw file](https://github.com/oscarlab/graphene/blob/7f5b96d67c3862b074e4ae09d208e3c66a6eb8b5/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L436)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, shouldn't this generate a compiler warning? (signed vs unsigned comparison)
(existing issue, not blocking)
</blockquote></details>

I think it should, but maybe it behaves differently when one of the sides is compile-time constant. Dunno. Anyways, this whole file is terrible and needs a rewrite.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 449 at r13](https://reviewable.io/reviews/oscarlab/graphene/2441#-McEWgJfAdxi2j8RhWFY:-McEb7hEAbhcCc5uutRn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f5b96d67c3862b074e4ae09d208e3c66a6eb8b5/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 10 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_streams.c, line 551 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFB6a89OlQVDa0822O:-McFB6a9ClObclD6zja5:b-awccen) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/db_streams.c#L551)):*
> ```C
> 
>     ret = hops->rename(hdl, type, uri);
> out:
> ```

Is this just a cosmetic change? What is the guidance for such places then?
___
*[Pal/src/host/Linux/db_threading.c, line 121 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFBg8LEg8CrnQCMze5:-McFBg8MA0JAKGv1P8XF:b-jgd01z) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/host/Linux/db_threading.c#L121)):*
> ```C
> /*
>  * Creates an internal thread inside the current process. The arguments callback and param specify
>  * the starting function and parameters.
> ```

The `Creates an internal thread` is weird. What does it mean "internal"? It's just a thread, but there is some PAL metadata created with the thread. I would remove this first sentence. But not blocking.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 97 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFC6Uh2BO0-EyPi3NX:-McFC6Uj4hmdP5v7kPZz:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/host/Linux-SGX/db_threading.c#L97)):*
> ```C
> /*
>  * Creates an internal thread inside the current process. The arguments callback and param specify
>  * the starting function and parameters.
> ```

ditto

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: 15 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/db_streams.c, line 551 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFB6a89OlQVDa0822O:-McFc76o9qbz2PPJdG78:b-z5681) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/db_streams.c#L551)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this just a cosmetic change? What is the guidance for such places then?
</blockquote></details>

Yeah, I was just going through `parse_stream_uri()` callsites and reshuffling them a bit. This place is just cosmetic and I'm not attached to it, but the rule here was that `type` is quite obscurely allocated and it's easy to forget to free it, so I converted this to a single-return+goto.
___
*[Pal/src/host/Linux/db_threading.c, line 121 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFBg8LEg8CrnQCMze5:-McFdPvk50HhjlPXs8So:b-65mftn) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/host/Linux/db_threading.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `Creates an internal thread` is weird. What does it mean "internal"? It's just a thread, but there is some PAL metadata created with the thread. I would remove this first sentence. But not blocking.
</blockquote></details>

I have no clue. I'll just drop this whole comment, it's useless. The part about being internal is probably just wrong and the part explaining that "callback" argument is the callback and "param" is its param is not too helpful either.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 97 at r14](https://reviewable.io/reviews/oscarlab/graphene/2441#-McFC6Uh2BO0-EyPi3NX:-McFiO_ZC3eiAkXo-yz7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5e7c08fa8f99ebbbd9f0c5d278c3e30ef0197a4b/Pal/src/host/Linux-SGX/db_threading.c#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: 1 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2441#-McB2b60-FMDB-sZwH8T:-McJqRTLEgx8-VyuMPnS:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will do at rebase.
</blockquote></details>

Done.

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 16 of 16 files at r16, 10 of 10 files at r17, 1 of 1 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2441)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
