### PR TITLE
[PAL, LibOS] Move PAGE_SIZE to cpu.h and use it in LibOS test case

### PR DESCRIPTION
**Pull request by stefanberger**
This PR moves the PAGE_SIZE to cpu.h and uses it in a test case to make this test case work on other architectures as well.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)

### CODE REVIEW

**Comment by stefanberger** [comment]
This is better than what I am currently using on ppc64: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20210113/LibOS/shim/test/regression/mmap_file.c

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/test/regression/mmap_file.c, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQyXFdpEi3btx8LExva:-MQyXFdpEi3btx8LExvb:bjukmy1) ([raw file](https://github.com/oscarlab/graphene/blob/ed1f4b871198cb58a169b6eb75b1c0c1e54ed384/LibOS/shim/test/regression/mmap_file.c#L10)):*
> ```C
> #include <unistd.h>
> 
> #include "cpu.h"
> ```

LibOS regression tests shouldn't depend on LibOS/PAL headers, they are standalone, Linux binaries (but yeah, some of them already have violated this).

Anyways, yes, this test was incorrect. Or at least I think so, because `PAGE_SIZE` is not an official API - usermode apps should get the page size using `sysconf(_SC_PAGESIZE)`. Could you fix it this way then?

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/mmap_file.c, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQyXFdpEi3btx8LExva:-MQydJdG174KKvCYH95-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ed1f4b871198cb58a169b6eb75b1c0c1e54ed384/LibOS/shim/test/regression/mmap_file.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

LibOS regression tests shouldn't depend on LibOS/PAL headers, they are standalone, Linux binaries (but yeah, some of them already have violated this).

Anyways, yes, this test was incorrect. Or at least I think so, because `PAGE_SIZE` is not an official API - usermode apps should get the page size using `sysconf(_SC_PAGESIZE)`. Could you fix it this way then?
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/test/regression/mmap_file.c, line 34 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQypfLj02w0teZoKBWj:-MQypfLk-mct_B-ZTj0X:bswdiyx) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L34)):*
> ```C
>     }
> 
>     long page_size = sysconf(_SC_PAGESIZE);
> ```

Please check the return value for errors

**Review by yamahata — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/test/regression/mmap_file.c, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzptuG5YqxrHyldNvO:-MQzptuG5YqxrHyldNvP:b-fzftlp) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L20)):*
> ```C
>     int rv;
> 
>     /* Initalization: create a 1025-byte file */
> ```

Can we remove this useless comment?
___
*[LibOS/shim/test/regression/mmap_file.c, line 34 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQypfLj02w0teZoKBWj:-MQzpoa8BqfT4hYHzHKG:b-5ohvvt) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please check the return value for errors
</blockquote></details>

+1, please add `if (page_size < 0) ...`
___
*[LibOS/shim/test/regression/mmap_file.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzq-y52edqDeYSEg-4:-MQzq-y52edqDeYSEg-5:b-inynph) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L37)):*
> ```C
> 
>     volatile unsigned char* a =
>         mmap(NULL, 9162, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FILE, fileno(fp), 0);
> ```

Shouldn't we change this `9162`? I don't know where this constant come from, but from other code, it just should be more than 1 page? Maybe just replace with `page_size * 2`?
___
*[LibOS/shim/test/regression/mmap_file.c, line 43 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzqAkN1eKVEj_yyxoi:-MQzqAkN1eKVEj_yyxoj:b-qiltp4) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L43)):*
> ```C
>     }
> 
>     a[1023] = 0xff;
> ```

Maybe we should also replace `1023` with smth like `page_size / 4 - 1`? I really don't understand what this test even tries to do.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/mmap_file.c, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzptuG5YqxrHyldNvO:-MR-so7I7aN_t7JY9RpV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove this useless comment?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/mmap_file.c, line 34 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQypfLj02w0teZoKBWj:-MR-sopF-uz6ftWKucUF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, please add `if (page_size < 0) ...`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/mmap_file.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzq-y52edqDeYSEg-4:-MR-tKL_AUZmIrUjBKLy:bt40yki) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we change this `9162`? I don't know where this constant come from, but from other code, it just should be more than 1 page? Maybe just replace with `page_size * 2`?
</blockquote></details>

This test creates a 1024 byte file. So this number I think has nothing to do wit page_size.
___
*[LibOS/shim/test/regression/mmap_file.c, line 43 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzqAkN1eKVEj_yyxoi:-MR-tWD4EgoNZtsw3_Kd:b6na8w5) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should also replace `1023` with smth like `page_size / 4 - 1`? I really don't understand what this test even tries to do.
</blockquote></details>

I think this here has nothing to do with page_size, either. It's just the last byte of the file.

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/test/regression/mmap_file.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzq-y52edqDeYSEg-4:-MR-vG9N1wVEceOGw61Q:b-xd02ze) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L37)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This test creates a 1024 byte file. So this number I think has nothing to do wit page_size.
</blockquote></details>

On 2nd thought, why not. Using quarter_page now...

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/test/regression/mmap_file.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzq-y52edqDeYSEg-4:-MR-vRwj3y08ezh4znl9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L37)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

On 2nd thought, why not. Using quarter_page now...
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/mmap_file.c, line 43 at r3](https://reviewable.io/reviews/oscarlab/graphene/2080#-MQzqAkN1eKVEj_yyxoi:-MR-vTeK1gjfX4iMrk4R:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d7691dfd38376d9db70841b6991e1623665c0132/LibOS/shim/test/regression/mmap_file.c#L43)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I think this here has nothing to do with page_size, either. It's just the last byte of the file.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by stefanberger — COMMENTED** [review]
Looks like we have lots of failed tests...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080#-:-MR0aB6e2_iEBEjkazum:bd5h9uv)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
@stefanberger UNC admins are installing more HW for CI and everything is quite unstable. Let's try again ;)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080#-:-MR0oerN4vu53k8YLAXF:b-cychot)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, retest this please (Jenkins internal problems, probably due to adding more workers)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2080)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
