### PR TITLE
Check architecture in seccomp filters

### PR DESCRIPTION
**Pull request by mkow**
Without the checks a malicious application can circumvent the filter by
issuing a 32-bit syscall using either "int 0x80" instruction or by switching cs
segment to a 32-bit one and using "sysenter". This works because syscall
numbers differ between 32- and 64-bit x86.

### CODE REVIEW

**Comment by chiache** [comment]
Thanks for the patch! I believe this fix could actually be quite helpful. We are currently working on a new version of the SECCOMP filter and reference monitor (see https://github.com/oscarlab/graphene/blob/rm-module/Pal/src/security/Linux/filter.c). It would be a good idea to merge this patch.

**Comment by donporter** [comment]
Do I understand this change correctly that it basically just squashes any 32-bit syscalls?  That seems reasonable, since we currently don't support 32-bit code on Graphene.

**Comment by mkow** [comment]
> Do I understand this change correctly that it basically just squashes any 32-bit syscalls?

Yes, it kills processes which try to use them. You may change this behavior (if you prefer to) by modifying this line:
https://github.com/oscarlab/graphene/pull/89/files#diff-c2295390e22f1f1b8924d37febb025fcR38

@chiache: Yup, you should also patch the new code, it has the same problem.

**Comment by chiache** [comment]
Merged into #139.

**Pull request closed without merging**
