### PR TITLE
[Pal/SGX] Sanitize `ocall_gettime` return value

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Now on each `ocall_gettime` we compare the returned value with the one returned in a previous call and bail out if it's smaller.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1351 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-MeaeIj7BkCRGiKxarxh:-MeaeIj85chu7Z-XhlLh:b4bqzrs) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1351)):*
> ```C
> 
>     /* Last seen time value. This guards against time rewinding in one thread and, to some extent,
>      * between threads. */
> ```

How exactly is it possible to rewind time between threads in current implementation? (in a way that is different than just one thread getting swapped out for a long time and later working on a stale return value, which can also happen on normal Linux)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1351 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-MeaeIj7BkCRGiKxarxh:-MeaiBf3EYcE3ThyxOBT:b-oa9qb7) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How exactly is it possible to rewind time between threads in current implementation? (in a way that is different than just one thread getting swapped out for a long time and later working on a stale return value, which can also happen on normal Linux)
</blockquote></details>

That should be the only case, that's why `to same extent`.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1351 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-MeaeIj7BkCRGiKxarxh:-MeasKNmCeUnP9bCdInI:basqwfo) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1351)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That should be the only case, that's why `to same extent`.
</blockquote></details>

Ok, but the way you wrote this comment it sounds like the code fails to guard against some cases it should. But if they can also happen on vanilla Linux, then that's not an issue. I mean, by reading it I thought that there was a potential security issue here.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1361 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-Med9l_t9Ut-EiuQ45Va:-Med9l_t9Ut-EiuQ45Vb:b-cmek74) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1361)):*
> ```C
>         uint64_t microsec = READ_ONCE(ms->ms_microsec);
>         if (microsec < last_microsec_before_ocall) {
>             /* Probably a mallicious host. */
> ```

Typo: `malicious` (only one `l`)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1351 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-MeaeIj7BkCRGiKxarxh:-MedRotJ-Ybrc4P3AbQ1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but the way you wrote this comment it sounds like the code fails to guard against some cases it should. But if they can also happen on vanilla Linux, then that's not an issue. I mean, by reading it I thought that there was a potential security issue here.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1361 at r1](https://reviewable.io/reviews/oscarlab/graphene/2554#-Med9l_t9Ut-EiuQ45Va:-MedR_6_7nlTTjYFkGha:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fffbb0a1782a365c4cbdeb5a9dad28cc4337b3d8/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1361)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `malicious` (only one `l`)
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2554)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04 please (`test_022_poll_closed_fd` failed with `read error: Permission denied`, unrelated)

**Pull request merged**
