### PR TITLE
[Examples] Change to OpenVINO 2020.3 LTS

### LINKED ISSUE #1823: OpenVINO LTS and model zoo
## Description of the problem
Glad to see that openvino example has been upgraded to 2020.4. But, this version is not a LTS version, which means it will be replaced by future release 4-5 months later.

1. Change to [2020.3LTS](https://software.intel.com/content/www/us/en/develop/articles/openvino-2020-3-lts-relnotes.html) maybe a better idea. 

2. model zoo is released according to openvino version. Need to change to the same version with openvino.

### PR DESCRIPTION
**Pull request by qiyuangong**
## Description of the changes 
Fixes #1823, change OpenVINO and model zoo to recent LTS (2020.3).

Others:
* Fix build on 2020 (Remove OMP option. Solve tbb related build error related to opencv).
* Fix build path (bin and build are changed to openvino root dir since 2020).
* Fix tbb related trusted files.
* Modify document.

## How to test this PR? 
No changes on OpenVINO example workflow. Can be tested with Jenkins auto-test if available.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)

### CODE REVIEW

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[Examples/openvino/openvino.manifest.template, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHlPO-n5hxni3HID8mX:-MHlPO-oDgTqNiMXh1D2:b-wtornl) ([raw file](https://github.com/oscarlab/graphene/blob/ca9fd1fae588e5a45ffb9b1894389d2e4ea658ad/Examples/openvino/openvino.manifest.template#L111)):*
> ```
> sgx.trusted_files.libHeteroPlugin                         = file:$(OPENVINO_DIR)/bin/intel64/$(OPENVINO_BUILD)/lib/libHeteroPlugin.so
> sgx.trusted_files.libMultiDevicePlugin                    = file:$(OPENVINO_DIR)/bin/intel64/$(OPENVINO_BUILD)/lib/libMultiDevicePlugin.so
> sgx.trusted_filesbinference_engine_preproc		  = file:$(OPENVINO_DIR)/bin/intel64/$(OPENVINO_BUILD)/lib/libinference_engine_preproc.so
> ```

Please remove the TAB characters.

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[Examples/openvino/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHlQ_d074uRU_sR_3wz:-MHlQ_d074uRU_sR_3x-:b-9ckob9) ([raw file](https://github.com/oscarlab/graphene/blob/ca9fd1fae588e5a45ffb9b1894389d2e4ea658ad/Examples/openvino/Makefile#L27)):*
> ```Makefile
> ifeq ($(DEBUG),1)
> GRAPHENE_DEBUG = inline
> OPENVINO_BUILD = Release
> ```

If DEBUG==1, then the build should be in debug mode as well.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @qiyuangong)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHhMU5T56I87VBRXqoS:-MHhMU5T56I87VBRXqoT:b-gi7opa) (no related file):*
Please add "Fixes #1823" to the description of the PR.

---

**Comment by mkow** [comment]
Jenkins, test this please

**Review by qiyuangong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHhMU5T56I87VBRXqoS:-MHnmJAw4LDFu9MBuk1k:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add "Fixes #1823" to the description of the PR.
</blockquote></details>

Done.

---
___
*[Examples/openvino/openvino.manifest.template, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHlPO-n5hxni3HID8mX:-MHnmKJt0grgwapEVlaf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ca9fd1fae588e5a45ffb9b1894389d2e4ea658ad/Examples/openvino/openvino.manifest.template#L111)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Please remove the TAB characters.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @qiyuangong)

___
*[Examples/openvino/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHpznNFClULWqgvQilq:-MHpznNGD7SpiUNslpty:b9djbyg) ([raw file](https://github.com/oscarlab/graphene/blob/0c07cc52187d48a4a6d1b8b854b3263cccc767b6/Examples/openvino/Makefile#L14)):*
> ```
> by changing OPENVINO_COMMIT MODEL_COMMIT
> ```

please insert "and" between them + end the sentence with a period

**Review by qiyuangong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Examples/openvino/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHpznNFClULWqgvQilq:-MHq5LDG6qQa--4WaEQN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0c07cc52187d48a4a6d1b8b854b3263cccc767b6/Examples/openvino/Makefile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> by changing OPENVINO_COMMIT MODEL_COMMIT
> ```

please insert "and" between them + end the sentence with a period
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Examples/openvino/Makefile, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHpznNFClULWqgvQilq:-MHq6aw-50jV-LS0rQUT:bst8iy8) ([raw file](https://github.com/oscarlab/graphene/blob/0c07cc52187d48a4a6d1b8b854b3263cccc767b6/Examples/openvino/Makefile#L14)):*
<details><summary><i>Previously, qiyuangong (Qiyuan Gong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I also asked about a period at the end, but I won't block on this.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHv3I88-gkjGG1S6bEF:-MHv3I88-gkjGG1S6bEG:bytxhx8) (no related file):*
Please don't use merge commits in the future (we'll need to delete them anyway) and instead use `git rebase` if you need to update the base of the PR (but this is generally discouraged during review). See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.

---

**Review by qiyuangong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHv3I88-gkjGG1S6bEF:-MHvWzoxBVvxJCV_vO0-:b-wtqes1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't use merge commits in the future (we'll need to delete them anyway) and instead use `git rebase` if you need to update the base of the PR (but this is generally discouraged during review). See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.
</blockquote></details>

My fault. :) Have reset branch with rebase. 

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by vijaydhanraj** [comment]
Hi @qiyuangong, looks like  2020.3.LTS version doesn't seem to take into account hyperthreading and ends up scheduling threads on all logical processors. 2020.4 or the version present in the repo did take into account hyperthreading and scheduled on just one HT sibling. Due to this, 2020.3.LTS version's native openvino latency drop by ~2.2x and throughtput drops by ~8%.

Is my observation true? If so, are there switches to enable topology aware scheduling of openvino threads with this version?

**Comment by qiyuangong** [comment]
> Hi @qiyuangong, I ran the openvino benchmark_app and it looks like 2020.3.LTS version doesn't seem to take into account hyperthreading and ends up scheduling threads on all logical processors. 2020.4 or the version present in the repo did take into account hyperthreading and scheduled on just one HT sibling(full core). Due to this, 2020.3.LTS version's native openvino latency drops by ~2.2x and throughtput drops by ~8%.
> 
> Have you noticed this at your end? If so, are there switches to enable topology aware scheduling of openvino threads with this version?

No. We haven't evaluate OpenVINO 2020.4 yet. Because it's a quarter release (2020.5 is on the way), not LTS. We didn't want to impact our applications or customers frequently.

According to our previous benchmark (2018, 2019 & 2020.2) with HT on and off (Xeon server), OpenVINO's overall performance doesn't change too much. We also tried binding to phiciall core  when HT is on with OMP topology (I'm not sure how to do this in TBB).

In my knowledge, this performance change may be caused by other reasons, such as inference engine detailed implementations (OMP->TBB, model format, computation layer changes). Actually, you can observe performance improvement (or sometimes drop on some models) on different OpenVINO version.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @qiyuangong)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHzvlCE7i9E0DibOScf:-MHzvlCE7i9E0DibOScg:b28w59j) (no related file):*
I am happy with this PR. It is reasonable to have an LTS version of OpenVINO as an example. But I'd like to block until @vijaydhanraj explicitly says that this change is fine. Vijay, apart from removing OpenMP backend (which we could re-add as a separate build option for this example later, when a new LTS version is released), is there something that this PR changes significantly or breaks?

---

**Review by qiyuangong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1833#-MHzvlCE7i9E0DibOScf:-MI-PFQN5naJywJRBiIs:bgml0c1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am happy with this PR. It is reasonable to have an LTS version of OpenVINO as an example. But I'd like to block until @vijaydhanraj explicitly says that this change is fine. Vijay, apart from removing OpenMP backend (which we could re-add as a separate build option for this example later, when a new LTS version is released), is there something that this PR changes significantly or breaks?
</blockquote></details>

OpenMP backend is removed by this PR because OpenMP building option is actually broken on OpenVINO 2020 (https://github.com/openvinotoolkit/openvino/issues/396 ). I suspect root cause is that provided OpenCV libs are built with TBB. You will see lots of building error related to TBB. :(

An hotfix is disabling OpenCV with `-DENABLE_OPENCV=OFF`. But, that option will remove `benchmark_app` and other end2end scripts from bin, making it hard to use.

---

**Comment by vijaydhanraj** [comment]
Hi @dimakuv, the PR is fine but the only issue I see is that this version lowers the performance threshold for the native case as it doesn't seem to automatically take advantage of CPU topology. I did run the patch from @qiyuangong on the Intel Xeon platform and as you can see, there is a very little performance gap between native and graphene.

```
**2020.3.LTS**
Benchmark_app(latency, ms): | Native | Graphene |
Average of 5 runs:          | 356.4  | 380.566  |
% diff vs native:                    |  6.78    |
```
```
**2020.4:**
Benchmark_app(latency, ms) | Native | Graphene  |
Average:                   | 160.63 | 376.84    |
% diff:                             | 134.61    |
```

We know that this isn't true as with the topology-aware 2020.4 version, the native performance can be improved by ~2x. So I would prefer to have 2020.4 version to validate against our new sys-fs implementation for CPU topology to address, https://github.com/oscarlab/graphene/issues/1783.

@qiyuangong: Do you know when there will be the next LTS version? Also, once the above issue is fixed, we plan to switch to TBB instead of OMP. Given this, do you see any major issues with the 2020.4 version?

**Review by dimakuv — COMMENTED** [review]
Hm, that's too bad. Now we have two groups of users of OpenVINO, and they need two different versions of OpenVINO: one LTS (for stability and usability) and one latest (for performance and testing).

@mkow @yamahata Do we want to have two explicit versions of OpenVINO in our Examples? We could simply have two directories `openvino-lts/` and `openvino-latest/`. From what I see, the two versions are quite different so it will be too cumbersome to introduce a build-time flag to choose which one to build.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833#-:-MI37X9IE0438iEsSGtD:b-hicrcm)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

**Comment by mkow** [comment]
> @mkow @yamahata Do we want to have two explicit versions of OpenVINO in our Examples? We could simply have two directories openvino-lts/ and openvino-latest/. From what I see, the two versions are quite different so it will be too cumbersome to introduce a build-time flag to choose which one to build.

I'm against supporting two versions, we already spend too much of our time on maintenance of our examples. Same for CI builds, they already take really long. I'd prefer to leave the current 2020.4 release and wait for the next LTS (assuming it will be released not too far in the future) and then update.

**Review by qiyuangong — COMMENTED** [review]
@vijaydhanraj According to LTS policy (https://software.intel.com/content/www/us/en/develop/articles/openvino-long-term-support-release.html), next LTS will be available in 2021. Current LTS is released in 2020 Jun. 

2020.4 is not our target version, so we don't fully evaluate it. We only observe a small issue in model zoo during our test. 

@dimakuv is right. Not just us, some of our customers are also confused about OpenVINO's version and performance. For now, I think we should first focus on example fix and OMP option, then discuss about version. 

Most changes in this PR focus on example fix. Current OpenVINO example is not able to pass building unless libtbb-dev is installed. But, that building is not correct. Because TBB is only required by OpenCV libs (downloaded from provided site) not OpenVINO. That means we are using 2 threads modules (TBB and OMP) in one application (see more details with `ldd benchmark_app`). Also, build and bin path are not correct since 2020.

In my view, change to TBB maybe a good idea. Because it is main threading module for OpenVINO since 2020, and is fully tested by CI and customers/developers. In contract, OMP becomes less important for OpenVINO. Some OMP related building issues are still kept unfixed since 2020.1. 

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1833#-:-MI4ktbT2nAv5-4aJAta:b-sq53f5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

**Comment by vijaydhanraj** [comment]
@qiyuangong, so the main concern is using OMP right, and I do agree we should use TBB. But with TBB and 2020.4 we did run into an issue, https://github.com/oscarlab/graphene/issues/1783 (please see pt.2 under actual results) and so switched to OMP. Please note, this is just a temporary workaround until the issue is fixed.

The only reason I am hesitant with 2020.3.LTS is that it doesn't seem to do topology-aware thread scheduling which is needed to evaluate some of the new features we are implementing.

**Comment by qiyuangong** [comment]
@vijaydhanraj 
In that case, I suggest blocking this PR until #1783 is fixed.

This PR can be kept here for people who want to test TBB based 2020.3 or 2020.4.

**Comment by vijaydhanraj** [comment]
yes sounds good to me, thanks @qiyuangong for your PR.
@dimakuv and @mkow is this fine?

**Comment by mkow** [comment]
Sounds good to me.

**Comment by dimakuv** [comment]
Good to me. This PR is blocked for now then.

**Comment by dimakuv** [comment]
@qiyuangong We just merged https://github.com/oscarlab/graphene/pull/1975. Do we still want to keep this PR?

**Comment by qiyuangong** [comment]
@dimakuv Do we need this PR anymore?

**Comment by dimakuv** [comment]
@qiyuangong  From my perspective, we don't need this PR anymore. We now have the default OpenVINO version with the TBB backend.

The only question is: our repo version of OpenVINO is 2020.4 which is not LTS. And your PR was left open exactly because 2020.3 is the LTS version. So you wanted to keep it open for people who need the LTS version. But if this is not a big problem any more, I suggest to close this PR.

**Comment by qiyuangong** [comment]
> @qiyuangong From my perspective, we don't need this PR anymore. We now have the default OpenVINO version with the TBB backend.
> 
> The only question is: our repo version of OpenVINO is 2020.4 which is not LTS. And your PR was left open exactly because 2020.3 is the LTS version. So you wanted to keep it open for people who need the LTS version. But if this is not a big problem any more, I suggest to close this PR.

OK. Let's close it first. If anyone need LTS version, we can redirect them to this PR.
PR Closed

**Pull request closed without merging**
