### PR TITLE
Deprecating .packed directories

### PR DESCRIPTION
**Pull request by chiache**
.packed directories are originally created for testing on non-Linux platforms. The usage is mostly obsolete right now, and the binaries are completely out-dated. A better strategy would be to create a hook in the github to release binary packages.

### CODE REVIEW

**Comment by chiache** [comment]
No need to test because this patch does not contain any code change.

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
I'd still like to understand why Jenkins is failing.  I'd like to get to where these reports are reliably useful.

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Test this please

**Pull request merged**
