### PR TITLE
[LibOS] Rename fs_base to tls_base to be more generic

### PR DESCRIPTION
**Pull request by stefanberger**
This PR now renames fs_base to tls_base to be more generic.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, test this please

**Review by yamahata — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2045)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
