### PR TITLE
[Pal/Linux-SGX] Refactor `init_trusted_files()`

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This function is split into several functions: initializing trusted files, initializing allowed files, and registering one file with
normalized path. This commit is in preparation for SGX allowed/trusted/protected files to be specified in TOML arrays.

## How to test this PR? 

Jenkins.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6m6_h9l762lmJrAIY:-Mg6m6_h9l762lmJrAIZ:bdeagp8) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L684)):*
> ```C
> 
>     ssize_t toml_trusted_files_cnt = toml_table_nkval(toml_trusted_files);
>     if (toml_trusted_files_cnt <= 0)
> ```

I think we should differentiate here between no entries (`toml_trusted_files_cnt == 0`) and an error (`toml_trusted_files_cnt < 0`), otherwise we silence errors.

OTOH, right now `toml_table_nkval()` can't return an error (it always succeeds), but the return value looks like it could, so just to be on the safe side if the tomlc99 implementation changes in the future I'd properly check it.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 724 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6nGOAE9imwMpkJ0h2:-Mg6nGOAE9imwMpkJ0h3:b-djcnok) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L724)):*
> ```C
>             free(toml_trusted_file_str);
>             free(toml_trusted_checksum_str);
>             free(toml_trusted_checksum_key);
> ```

Could we have one common return? These repeated `free()`s looks bad.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 761 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6ne2r3pLXL3cy-WiH:-Mg6ne2r3pLXL3cy-WiI:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L761)):*
> ```C
> 
>     ssize_t toml_allowed_files_cnt = toml_table_nkval(toml_allowed_files);
>     if (toml_allowed_files_cnt <= 0)
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 797 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6npl00DCBaCPFurxM:-Mg6npl00DCBaCPFurxN:bxrkz32) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L797)):*
> ```C
>     int ret;
> 
>     /* first try legacy manifest syntax with TOML tables, i.e. `sgx.trusted_files.key = "file"` */
> ```

Shouldn't we emit a warning if the now-deprecated syntax is used? And also convert all our examples to use it. Or maybe you plan to do this in a separate PR? If so, I'm a bit afraid we may forget to add this warning when converting examples.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 803 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6lk3w1jucinx9Ms-S:-Mg6lk3x9-HX9Iro9eP2:bsbqqsf) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L803)):*
> ```C
>         ret = init_trusted_files_from_toml_array();
>         if (ret == -PAL_ERROR_NOTDEFINED) {
>             log_debug("No trusted files were found in the manifest");
> ```

Should we really print anything here? It's a perfectly valid case and I'm not sure if there's any value in printing this.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6omhr9_2nB4LDhsxg:-Mg6omhr9_2nB4LDhsxh:byr40sw) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/pal_linux.h#L101)):*
> ```objc
> 
> enum {
>     FILE_CHECK_POLICY_STRICT = 0,
> ```

Why do you add this zero at the beginning?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: 1 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6m6_h9l762lmJrAIY:-MgA1bW6BCQkru9PPsvf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L684)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we should differentiate here between no entries (`toml_trusted_files_cnt == 0`) and an error (`toml_trusted_files_cnt < 0`), otherwise we silence errors.

OTOH, right now `toml_table_nkval()` can't return an error (it always succeeds), but the return value looks like it could, so just to be on the safe side if the tomlc99 implementation changes in the future I'd properly check it.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 724 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6nGOAE9imwMpkJ0h2:-MgA5k4k2gJOape3B-Rc:bdsyot4) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L724)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we have one common return? These repeated `free()`s looks bad.
</blockquote></details>

Done. Same for `init_allowed_files_from_table_table`, even though it was not strictly needed there -- just for uniformity.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 761 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6ne2r3pLXL3cy-WiH:-MgA1k1I6F6Uqp9cIJAB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L761)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 797 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6npl00DCBaCPFurxM:-MgA34Xp9ZkWfIsrTrVl:b-am4nkn) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L797)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we emit a warning if the now-deprecated syntax is used? And also convert all our examples to use it. Or maybe you plan to do this in a separate PR? If so, I'm a bit afraid we may forget to add this warning when converting examples.
</blockquote></details>

Done. Currently under `ifdef 0`. In the next PR (which actually adds TOML arrays) I'll enable it.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 803 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6lk3w1jucinx9Ms-S:-MgA3PjYE5fU0oN11ABd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/enclave_framework.c#L803)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should we really print anything here? It's a perfectly valid case and I'm not sure if there's any value in printing this.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2607#-Mg6omhr9_2nB4LDhsxg:-MgA3cRx3oV2zsHmwXDp:bg6sq7e) ([raw file](https://github.com/oscarlab/graphene/blob/48d9558e778b9192456ba3a443f28bedcbad3891/Pal/src/host/Linux-SGX/pal_linux.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do you add this zero at the beginning?
</blockquote></details>

Done. That wasn't me, I just moved these lines around. But I removed it now.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 740 at r2](https://reviewable.io/reviews/oscarlab/graphene/2607#-MgQu26xDicHhYagDWvJ:-MgdoJdw2bNGgMaEijTP:b-5e7jbu) ([raw file](https://github.com/oscarlab/graphene/blob/6e3d5da61974c84b28bc2a55372fefbf94d3914d/Pal/src/host/Linux-SGX/enclave_framework.c#L740)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

hmm, why is this block needed?
</blockquote></details>

Done.

Because we have a loop here where we re-use these strings (re-allocate them). And if we wouldn't NULLify them here, and some error would happen in the middle of the loop, we would `goto out` and may end up in a double-free bug.

But since it's confusing, I refactored this code a bit.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 797 at r2](https://reviewable.io/reviews/oscarlab/graphene/2607#-MgQuZEJDMgbQZC9y64F:-MgdqHtcBek4TyuqMGXQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e3d5da61974c84b28bc2a55372fefbf94d3914d/Pal/src/host/Linux-SGX/enclave_framework.c#L797)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (`sendfile09` LTP test timed out on `slave-constantine`, I have a feeling that this Jenkins worker is sloooow, this is not the first time tests timeout on this machine).

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 740 at r2](https://reviewable.io/reviews/oscarlab/graphene/2607#-MgQu26xDicHhYagDWvJ:-Mgoso9u0iHJJfJ338uG:b-5gm3nm) ([raw file](https://github.com/oscarlab/graphene/blob/6e3d5da61974c84b28bc2a55372fefbf94d3914d/Pal/src/host/Linux-SGX/enclave_framework.c#L740)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Because we have a loop here where we re-use these strings (re-allocate them). And if we wouldn't NULLify them here, and some error would happen in the middle of the loop, we would `goto out` and may end up in a double-free bug.

But since it's confusing, I refactored this code a bit.
</blockquote></details>

Oh, I missed that this is a loop, thought it's an end of an `if` :)
I'm fine with the old version then. One thing I don't like in the new one is that it has a non-obvious assumption that `toml_trusted_files_cnt > 0`, otherwise you `free()` uninitialized variables. It can't happen here because we check it, but the reason for checking it is unrelated and it will be easy to violate this when refactoring in the future.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2607)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
