### PR TITLE
Fix names and types used for memory sizes

### LINKED ISSUE #152: size_t should be used for memory sizes (instead of int)
A lot of current code uses `int` instead of `size_t` for storing in-memory object sizes, which is too small to hold anything bigger than 2GB (and will silently overflow when trying to do so). It will also trigger tons of warnings if you ever decide to use some static code checkers, obfuscating their output.

This issue already caused some problems in the past (e.g. https://github.com/oscarlab/graphene/pull/136), so it may be a good idea to fix this in the whole codebase someday. I'll check if there's any way to enable GCC warnings for this kind of issues (only for size_t, not for every data losing conversion) so you could easily prevent them in the future.

I saw that there were some recent fixes by @chiache to this kind of problems, thanks!

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Finally fixes #152. I omitted some places in FS, which Paweł is now rewriting, to avoid conflicts.

## How to test this PR? 

Just review + CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Documentation/devel/coding-style.rst, line 141 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF3lmS829y-ON7-byC:-McF3lmS829y-ON7-byD:b5og24) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Documentation/devel/coding-style.rst#L141)):*
> ```reStructuredText
>    #. "size" always means size in bytes, "count" means the number of elements
>       (e.g. in an array) and "length" means the length of a C-string
>       (excluding terminating NULL).
> ```

Except in mbedTLS functions :) mbedTLS for some reason like to use "length" for everything, including sizes.
___
*[LibOS/shim/include/shim_table.h, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF48yx04RSK9KUJE6J:-McF48yx04RSK9KUJE6K:bc58v1i) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/include/shim_table.h#L44)):*
> ```objc
> long shim_do_pread64(int fd, char* buf, size_t count, loff_t pos);
> long shim_do_pwrite64(int fd, char* buf, size_t count, loff_t pos);
> long shim_do_readv(unsigned long fd, const struct iovec* vec, unsigned long vlen);
> ```

Btw, why does Linux use `unsigned long fd`? Quick googling didn't find a rationale.
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5P-_9_n-qlKzsMGG:-McF5P-_9_n-qlKzsMGH:by6ycc2) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/test/regression/bootstrap.c#L30)):*
> ```C
>     }
> 
>     size_t chunk_size = argv[argc - 1] + strlen(argv[argc - 1]) - argv[0];
> ```

This will be move readable like this:
```
size_t chunk_size = argv[argc - 1] - argv[0] + strlen(argv[argc - 1]) + 1;
if (sizes_sum != chunk_size) {
```
___
*[Pal/include/pal_internal.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5fCc3_3GZm5nIQGY:-McF5fCc3_3GZm5nIQGZ:b-7tr24o) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Pal/include/pal_internal.h#L105)):*
> ```objc
> #define HANDLE_SIZE(type) (sizeof(*_h))
> 
> static inline size_t handle_size(PAL_HANDLE handle) {
> ```

Wow this function is useless.
___
*[Pal/regression/File.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF68rgDXstXKqbBK7y:-McF68rh6zjjh4Pb3Nlu:bjroiut) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Pal/regression/File.c#L12)):*
> ```C
> char hex_buf[BUF_SIZE * 2 + 1];
> 
> static void print_hex(char* fmt, const void* data, size_t size) {
> ```

Isn't it `len`?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: 21 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/coding-style.rst, line 141 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF3lmS829y-ON7-byC:-McFBOCtCj4kUAy9mf-e:b-p16zv2) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Except in mbedTLS functions :) mbedTLS for some reason like to use "length" for everything, including sizes.
</blockquote></details>

Yeah, and they also use `int`s for sizes :) But it's not our code, so we can't do much about it :(
___
*[LibOS/shim/include/shim_table.h, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF48yx04RSK9KUJE6J:-McFBZHf4Cg2secg92EB:bucrhwz) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/include/shim_table.h#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, why does Linux use `unsigned long fd`? Quick googling didn't find a rationale.
</blockquote></details>

No idea, I guess some random legacy reasons. As you can see, all types in syscall arguments are completely random and inconsistent.
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5P-_9_n-qlKzsMGG:-McFMrUH1F9oUC9OTCkU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/test/regression/bootstrap.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will be move readable like this:
```
size_t chunk_size = argv[argc - 1] - argv[0] + strlen(argv[argc - 1]) + 1;
if (sizes_sum != chunk_size) {
```
</blockquote></details>

Done.
___
*[Pal/include/pal_internal.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5fCc3_3GZm5nIQGY:-McFMtUB4frrErJrvU6m:bb77ufg) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Pal/include/pal_internal.h#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wow this function is useless.
</blockquote></details>

Yes.
___
*[Pal/regression/File.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF68rgDXstXKqbBK7y:-McFMyhZ68shmnvi4WDU:b-5vdf3b) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Pal/regression/File.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it `len`?
</blockquote></details>

Nah, it doesn't print a C-string, but a blob of binary data.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McKEoBwEPqnsGT1GqlL:b770q0i) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
> ```reStructuredText
>    #. "size" always means size in bytes, "count" means the number of elements
>       (e.g. in an array) and "length" means the length of a C-string
>       (excluding terminating NULL).
> ```

What's wrong with using "length" for arrays (denoting the number of elements in that array)?
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McKHLMBADZPw0r8Dgz0:bcmn612) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
> ```C
>         return -EINVAL;
> 
>     for (unsigned long i = 0; i < vlen; i++) {
> ```

Don't we use `size_t` for array index iterators?
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHONs2coAcQ-YMr4q:-McKHONs2coAcQ-YMr4r:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L44)):*
> ```C
>     ssize_t bytes = 0;
> 
>     for (unsigned long i = 0; i < vlen; i++) {
> ```

ditto
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHTEa7ZIRhn9-ukF8:-McKHTEa7ZIRhn9-ukF9:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L85)):*
> ```C
>         return -EINVAL;
> 
>     for (unsigned long i = 0; i < vlen; i++) {
> ```

ditto
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 107 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHTwbA9N-oxruC2Ft:-McKHTwbA9N-oxruC2Fu:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L107)):*
> ```C
>     ssize_t bytes = 0;
> 
>     for (unsigned long i = 0; i < vlen; i++) {
> ```

ditto
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5P-_9_n-qlKzsMGG:-McKIWk5-XwyGoBZRb49:b-by4ia) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/test/regression/bootstrap.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IMO `+1` should be after `strlen`, so that it's clear it accounts for the null byte at the end.
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKIyHq1HWJl5mC8vKL:-McKIyHq1HWJl5mC8vKM:bixs01l) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/test/regression/bootstrap.c#L30)):*
> ```C
>     }
> 
>     size_t chunk_size = argv[argc - 1] + strlen(argv[argc - 1]) - argv[0] + 1;
> ```

While we are here, could you add a `if (argc == 0) fail();` at the beginning (maybe after printf or argc)?
___
*[Pal/include/pal_internal.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5fCc3_3GZm5nIQGY:-McKJVtn3pPdqZ41y62V:bu7cggy) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/Pal/include/pal_internal.h#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

I guess the idea was that `PAL_HANDLE` would only describe a header and the content would be dynamically allocated based on handle type, in which case this function would be needed. Currently we have one big union in there.
Just guessing.
___
*[Pal/src/db_rtld.c, line 493 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKK4KBCTQAmdv7cYMd:-McKK4KBCTQAmdv7cYMe:b-z8ftdd) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Pal/src/db_rtld.c#L493)):*
> ```C
> 
>     /* if e_phoff + maplength is smaller than the data read */
>     if (ehdr->e_phoff + maplength <= (size_t)size) {
> ```

Cast not needed anymore.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: 20 of 22 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McKMH6-5fu6jVbdHJta:b2er5zj) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's wrong with using "length" for arrays (denoting the number of elements in that array)?
</blockquote></details>

Nothing, but I like the idea of reserving "length" for C-strings. If you want we can loosen this convention.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McKNm453-swCvHZx5y2:b-m7ms8j) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we use `size_t` for array index iterators?
</blockquote></details>

We usually do, but here the limit is `ulong`, so I wanted to use matching type and don't need to think about relation between `size_t` and `ulong`.
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2445#-McF5P-_9_n-qlKzsMGG:-McKT5Si21PYRD4TO-jE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2fa9f8842c223ee3155d1af8b021cbbf3c3ab722/LibOS/shim/test/regression/bootstrap.c#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO `+1` should be after `strlen`, so that it's clear it accounts for the null byte at the end.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/bootstrap.c, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKIyHq1HWJl5mC8vKL:-McKTbb7B3Lr1IeO5DSr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/test/regression/bootstrap.c#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

While we are here, could you add a `if (argc == 0) fail();` at the beginning (maybe after printf or argc)?
</blockquote></details>

Done.
___
*[Pal/src/db_rtld.c, line 493 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKK4KBCTQAmdv7cYMd:-McKU91h5VMddcmlcxOF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Pal/src/db_rtld.c#L493)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Cast not needed anymore.
</blockquote></details>

Done.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McKWOBg2l67umkfq_1n:b6nwzev) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nothing, but I like the idea of reserving "length" for C-strings. If you want we can loosen this convention.
</blockquote></details>

Yea, I don't like the idea of explicitly forbidding it.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McKW_fdD2Fj0KjNyu-B:buznbjz) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We usually do, but here the limit is `ulong`, so I wanted to use matching type and don't need to think about relation between `size_t` and `ulong`.
</blockquote></details>

Why do you need to think about such relation? We iterate over an array, so `size_t` is fine to use by definition.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: 21 of 22 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McLfUghBXUtmXfHvh6Y:b-r4xfu1) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yea, I don't like the idea of explicitly forbidding it.
</blockquote></details>

Any idea how to add this without an additional sentence? And to not be confusing w.r.t. C-strings, which are also arrays...
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McLfhx73TUe70_VN45I:b-79jvwd) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do you need to think about such relation? We iterate over an array, so `size_t` is fine to use by definition.
</blockquote></details>

It should, but maaaybe `unsigned long` could be larger than `size_t`, whatever it would mean, and I just prefer to not have to think whether it's fine when reading this code ;) Anyways, if you insist I can change this.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHONs2coAcQ-YMr4q:-McLgPMK3ET8JAwyZzYv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHTEa7ZIRhn9-ukF8:-McLgPlf29RfytMrKUi7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 107 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHTwbA9N-oxruC2Ft:-McLgQEh2ZUjrdNhCA8d:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McMYul96ILP6FupucZp:bcj8riv) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any idea how to add this without an additional sentence? And to not be confusing w.r.t. C-strings, which are also arrays...
</blockquote></details>

`"size" always means size in bytes, "length" (or "count") means the number of elements (e.g. in an array, or characters in C-string, excluding the terminating null byte).`
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McMevHK6OtT047uxVcy:brk0vfk) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It should, but maaaybe `unsigned long` could be larger than `size_t`, whatever it would mean, and I just prefer to not have to think whether it's fine when reading this code ;) Anyways, if you insist I can change this.
</blockquote></details>

Again, if `unsigned long` was larger than `size_t` it wouldnt matter at all. We use that to iterate over array, so by definition all indices have to fit in `size_t`.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/devel/coding-style.rst, line 141 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKEoBuArWrFEF79pDa:-McP2MFF0Zk7KPkqNNQH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/Documentation/devel/coding-style.rst#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`"size" always means size in bytes, "length" (or "count") means the number of elements (e.g. in an array, or characters in C-string, excluding the terminating null byte).`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McP2NRO075Ua_br-c-b:b-dty4io) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Again, if `unsigned long` was larger than `size_t` it wouldnt matter at all. We use that to iterate over array, so by definition all indices have to fit in `size_t`.
</blockquote></details>

Not really, this is a syscall argument, so it may be incorrect and we need to handle this. But we already do this incorrectly right above, so probably this iteration doesn't matter.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McQ_J2V6CPF-9pBLA2c:bn14cq8) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not really, this is a syscall argument, so it may be incorrect and we need to handle this. But we already do this incorrectly right above, so probably this iteration doesn't matter.
</blockquote></details>

`i` is not a syscall argument.
Oh, I get it now: you mean that `vlen` might be greater than a `SIZE_T_MAX`. Yes that should be validated earlier (and is, but as you noted, incorrectly).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: 14 of 22 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McRIR6h-63S8SkAL18P:b-lzo8yu) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`i` is not a syscall argument.
Oh, I get it now: you mean that `vlen` might be greater than a `SIZE_T_MAX`. Yes that should be validated earlier (and is, but as you noted, incorrectly).
</blockquote></details>

Yup. Somewhere in this function we'll have the `size_t` vs `ulong` problem.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sys/shim_wrappers.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2445#-McKHLMBADZPw0r8Dgz-:-McRJcsIC9T7aYobrewl:b8yej17) ([raw file](https://github.com/oscarlab/graphene/blob/69c44e10f8f5eaa8cf130b12f880c7249e60f6dd/LibOS/shim/src/sys/shim_wrappers.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup. Somewhere in this function we'll have the `size_t` vs `ulong` problem.
</blockquote></details>

It would be enough to check for overflow on `sizeof () * vlen`, because `is_user_memory_readable` will take care of rest.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2445)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
For the record: `apps.LTP.fsync02` timed out on Jenkins-Debug-20.04 once, but it seems unrelated (other LTPs are also timing out from time to time on other pipelines).

**Pull request merged**
