### PR TITLE
[CI] Turn on LTP for SGX

### PR DESCRIPTION
**Pull request by donporter**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [X] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Just for testing right now, turn on LTP on SGX.

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/861)

### CODE REVIEW

**Comment by dimakuv** [comment]
@donporter #896 reworks the whole LTP infrastructure and additionally tests SGX. I guess your PR is now obsolete, and #896 will incorporate your findings from this PR.

**Comment by donporter** [comment]
If @woju can get a stable baseline, great.  This is definitely just work in progress, and I still haven't hit a stable set of tests to even run.

**Comment by donporter** [comment]
Note that #896 doesn't enable LTP for SGX, so I don't know that this is really obsolete.  I have been testing locally more than in Jenkins, so I don't necessarily need the PR right now, but I wouldn't call this mission accomplished.

**Comment by woju** [comment]
On Thu, Oct 24, 2019 at 04:58:08AM -0700, Don Porter wrote:
> Note that #896 doesn't enable LTP for SGX, so I don't know that this is
> really obsolete.  I have been testing locally more than in Jenkins, so
> I don't necessarily need the PR right now, but I wouldn't call this mission
> accomplished.

It did, but it happened not to be a good idea: #1094.

You're right that the mission is not accomplished, because there is some
instability that causes the testsuite to randomly fail. Right now I'm running
some statistics on what testcases fail most often and I'll disable them. After
that, I'm going to reenable SGX.

**Comment by dimakuv** [comment]
There were no development on this front for a while, and our Jenkins infrastructure changes drastically, so let's close this PR. We are well aware of this issue (LTP is not currently tested on SGX), so we'll re-create this PR later, when we're ready.

**Comment by mkow** [comment]
> we'll re-create this PR later, when we're ready.

Or never, LTP on SGX is not a priority currently and making it work looks quite hard (because of shared memory used by LTP's setup routines).

**Pull request closed without merging**
