### PR TITLE
Update Azure confidential compute VM deployment description

### PR DESCRIPTION
**Pull request by vahldiek**
## Description of the changes 

This PR updates the description of cloud deployments in Azure confidential compute VMs, due to a recent update in their kernel and SGX driver.

## How to test this PR? 

Jenkens should test the document generation.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/1860#-MIVzDw18uqiEfDi5oN_:-MIVzDw18uqiEfDi5oNa:b-uy66kw) ([raw file](https://github.com/oscarlab/graphene/blob/7a0926033044bd90c43e95ae1c07e980217a033e/Documentation/cloud-deployment.rst#L34)):*
> ```reStructuredText
> Graphene requires FSGSBASE support to be enabled in the kernel. If it is not
> enabled in the Azure-provided VM, please refer to `Building Graphene
> <https://graphene.readthedocs.io/en/latest/building.html#install-the-linux-kernel-patched-with-fsgsbase>`__
> ```

This should be a relative link, but I'm not sure what's the syntax for them, you'll need to read the docs ;)

**Review by vahldiek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/cloud-deployment.rst, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/1860#-MIVzDw18uqiEfDi5oN_:-MIW0rxnB08Nb63X280v:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a0926033044bd90c43e95ae1c07e980217a033e/Documentation/cloud-deployment.rst#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be a relative link, but I'm not sure what's the syntax for them, you'll need to read the docs ;)
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Jenkins, test Docs-18.04 please

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1860)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
