### PR TITLE
[LibOS] Remove dynamic linking

### LINKED ISSUE #1408: [LibOS] Elf relocations do not work correctly for small base addresses
## Description of the problem:
If a binary will be relocated to a small address and some of its segments have offsets bigger than base address, they won't be relocated:
https://github.com/oscarlab/graphene/blob/fe123b7f94115d821fd046b6127a0c4cefc8f85e/LibOS/shim/src/elf/rel.h#L20-L22
For example, lets take `Runtime/ld-linux-x86-64.so.2` and:
- due to aslr base address is randomized to `0x1d8000`
- this elf has 2 LOAD segments - the second is to be loaded at offset `0x224000` from the first
Now since `0x224000 > 0x1d8000` this segment will be loaded at address `0x224000` instead of `0x1d8000 + 0x224000 = 0x3fc000` due to bugged code linked above.

## Steps to reproduce:
Run a small binary (eg. just `int main(void) { return 0; }`) with SGX and this patch (probably need to be applied manually - offsets in file might differ):
```
diff --git a/LibOS/shim/src/bookkeep/shim_vma.c b/LibOS/shim/src/bookkeep/shim_vma.c
index 48aab28..9a35d55 100644
--- a/LibOS/shim/src/bookkeep/shim_vma.c
+++ b/LibOS/shim/src/bookkeep/shim_vma.c
@@ -380,6 +380,7 @@ int init_vma(void) {
         goto out;
     }
     current_heap_top -= ALLOC_ALIGN_DOWN(rand % addr_rand_size);
+    current_heap_top = (void*)0x2bb4000;
 #endif

```

### PR DESCRIPTION
**Pull request by pwmarcz**
Fixes #1408 (ELF relocations do not work correctly for small base addresses).

## Description of the changes 

After this change, LibOS will no longer perform dynamic linking. The ELF loading code executes load commands and passes control to interpreter (ld.so), which handles necessary relocations and loading additional libraries. In this way, the code resembles what Linux kernel does when executing a new program.

Before, dynamic linking was necessary for making LibOS entry point (syscalldb function) available for applications. However, that meant duplicating the work already done by ld.so, and introduced a lot of unnecessary complexity. After changing LibOS entry API to use the GS register, it's possible to omit dynamic linking entirely.

The main function (__load_elf_object()) still needs cleanup and possibly rewrite from scratch. However, this change prepares ground for that rewrite.

Summary of changes:

- Remove dynamic relocation step (DO_DYNAMIC_RELOCATE()).
- Don't call __load_elf_object() again for ELFs reported via register_library(). We only need to notify GDB about the
  library.
- Remove fields related to dynamic linking from link_map (dynamic section address, hashes, etc.), and setup for these fields.
- need_interp(): To check if we need an interpreter, check only if the binary requests one (PT_INTERP), instead of traversing the dynamic section (before, we ignored dynamic dependencies on LibOS itself, but now there shouldn't be any).
- RELOCATE(): always adjust addresses, instead of checking if they're already inside the mapped range. I think the previous behaviour was a workaround to make repeated relocations work.

## How to test this PR? 

The current tests should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTf-uW03gmjEe-tO7IV:-MTf-uW03gmjEe-tO7IW:b-3vs51v) ([raw file](https://github.com/oscarlab/graphene/blob/1b15a0fac843caacb88e82a89f5dcbd3127b46b5/LibOS/shim/src/elf/shim_rtld.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

I think we can now move this file to `LibOS/shim/src/` and remove the `elf` subdir. But this can be done in another PR (with other changes to `shim_rtld` code).
___
*[LibOS/shim/src/elf/shim_rtld.c, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTf-Of04SKOo-cu5sF5:-MTf-Of04SKOo-cu5sF6:bokhsor) ([raw file](https://github.com/oscarlab/graphene/blob/1b15a0fac843caacb88e82a89f5dcbd3127b46b5/LibOS/shim/src/elf/shim_rtld.c#L9)):*
> ```C
>  * optimization of execve.
>  * Most of the source code was imported from GNU C library.
>  */
> ```

Do you need to modify this comment? The comment seems to be generally correct, so your call.

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: 9 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTf-uW03gmjEe-tO7IV:-MTfV_vXDzrnIpvzBHjm:b8w3o3t) ([raw file](https://github.com/oscarlab/graphene/blob/1b15a0fac843caacb88e82a89f5dcbd3127b46b5/LibOS/shim/src/elf/shim_rtld.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we can now move this file to `LibOS/shim/src/` and remove the `elf` subdir. But this can be done in another PR (with other changes to `shim_rtld` code).
</blockquote></details>

I'll keep that in mind during next step, thanks.
___
*[LibOS/shim/src/elf/shim_rtld.c, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTf-Of04SKOo-cu5sF5:-MTfVchD4PqMi--l9agb:b-2mtj8w) ([raw file](https://github.com/oscarlab/graphene/blob/1b15a0fac843caacb88e82a89f5dcbd3127b46b5/LibOS/shim/src/elf/shim_rtld.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you need to modify this comment? The comment seems to be generally correct, so your call.
</blockquote></details>

Yes, it seems to still describe the code, more or less. I'll change it after making more changes to this file (or rewriting it).

**Review by mkow — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTfuHia74AaO6NsYjbD:-MTfuHia74AaO6NsYjbE:by54qtf) (no related file):*
Could you also revert #1410 (rest of it)?

---
___
*[LibOS/shim/src/elf/shim_rtld.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTftAHV2eJBSND45FQK:-MTftAHV2eJBSND45FQL:b-kp92q7) ([raw file](https://github.com/oscarlab/graphene/blob/e700b9d50b45708080ccb04b5e81a98c6019811c/LibOS/shim/src/elf/shim_rtld.c#L200)):*
> ```C
>                segments are mapped in.  We record the addresses it says
>                verbatim, and later correct for the run-time load address.  */
>             case PT_DYNAMIC:
> ```

Why not delete the whole `case`, including the comment?

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-Debug please (spurious signal 9, known issue, broken IPC)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTfuHia74AaO6NsYjbD:-MTfxNUj-2ycJkc3l2aZ:brdenoo) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you also revert #1410 (rest of it)?
</blockquote></details>

@boryspoplawski But there seems to be no sense in those deleted lines `sys.brk.size = 32M` and `sys.stack.size = 4M`. Why should we revert them (and thus adding useless manifest options)?

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTfuHia74AaO6NsYjbD:-MTfy75SBHmI_yC5X6kz:bqw4g3h) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski But there seems to be no sense in those deleted lines `sys.brk.size = 32M` and `sys.stack.size = 4M`. Why should we revert them (and thus adding useless manifest options)?
</blockquote></details>

Wouldn't it test some non-default options? Why there is no sense in those lines?

---

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTfuHia74AaO6NsYjbD:-MTfzwR65QcOvWO3YIz9:bl9t0u1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wouldn't it test some non-default options? Why there is no sense in those lines?
</blockquote></details>

Yes, that's true. But if we want to test non-default options, then we must put the comment with smth like `# these options are not required; added here only for testing`.

There is no sense in these lines -- I meant that those lines were apparently a copy-paste from somewhere. They don't have any functional meaning for these tests.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTfuHia74AaO6NsYjbD:-MTg-eZD8I0j-qh4LBh1:bwzwlhy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, that's true. But if we want to test non-default options, then we must put the comment with smth like `# these options are not required; added here only for testing`.

There is no sense in these lines -- I meant that those lines were apparently a copy-paste from somewhere. They don't have any functional meaning for these tests.
</blockquote></details>

All right.

---

**Review by yamahata — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: 9 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2161#-MTftAHV2eJBSND45FQK:-MTjYJR39P7EZ3cq5KhB:b-d9dshy) ([raw file](https://github.com/oscarlab/graphene/blob/e700b9d50b45708080ccb04b5e81a98c6019811c/LibOS/shim/src/elf/shim_rtld.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not delete the whole `case`, including the comment?
</blockquote></details>

The comment seems to be for all the cases. I deleted this case and moved the comment outside of switch.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2161)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX-gsc please (some network issues at UNC?)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-gsc please (internet connectivity issues)

**Pull request merged**
