### PR TITLE
[LibOS] Rename `async helper` to `async worker`

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
To be consistent with recent IPC worker rename.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: 0 of 30 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DONTMERGE" and "TODO" found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2318#-MYctskG7wKosWz9z6MS:-MYctskG7wKosWz9z6MT:b-kecad6) (no related file):*
Grepping for `async helper` (case insensitive) also shows some mentions in `db_threading.c`, `shim_thread.c`, `enclave_entry.S`.

---
___
*[LibOS/shim/include/shim_utils.h, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2318#-MYcuALy23tQaryyA7MW:-MYcuALz9mgZJty_I2Jq:b-byduti) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_utils.h#L163)):*
> ```objc
> 
> /* Asynchronous event support */
> int init_async(void);
> ```

We have `init_async()` but `init_ipc_worker`. I suggest to rename this to `init_async_worker` for uniformity.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: 0 of 30 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DONTMERGE" and "TODO" found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2318#-M_KDjIIC_Tai2oxGMR3:-M_KDjIIC_Tai2oxGMR4:b-7zrkio) (no related file):*
@boryspoplawski The IPC Rework PR was merged, can you rebase this one?

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: 0 of 33 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2318#-MYctskG7wKosWz9z6MS:-M_KgG_h1yGwTXxTRMeA:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Grepping for `async helper` (case insensitive) also shows some mentions in `db_threading.c`, `shim_thread.c`, `enclave_entry.S`.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2318#-M_KDjIIC_Tai2oxGMR3:-M_KfO-y6zHm7efb2sQo:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski The IPC Rework PR was merged, can you rebase this one?
</blockquote></details>

Done.

---
___
*[LibOS/shim/include/shim_utils.h, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2318#-MYcuALy23tQaryyA7MW:-M_KfPws0bNueKWRY2RD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_utils.h#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have `init_async()` but `init_ipc_worker`. I suggest to rename this to `init_async_worker` for uniformity.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: 27 of 33 files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 7 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: 27 of 33 files reviewed, all discussions resolved

**Comment by boryspoplawski** [comment]
Jenkins, retest Jenkins-18.04 please (`kill11` failed - known issue, `writev07` failed - unrelated - recently we've started to observe tests seemingly succeeding but then timing out)

**Review by mkow — APPROVED** [review]
> Reviewed 6 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2318)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
