### PR TITLE
[Pal/Linux-SGX] Use hard-coded SSA frame size equal to 4 pages

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, the SGX-signing Python script had a hard-coded value of **1 page**. However, the Linux-SGX runtime calculated the SSA frame size based on the information from CPUID and XFRM.

The SSA frame size is a total of XSAVE area size + GPRs + MISC region, and on feature-rich CPUs may exceed 1 page. Thus, the SSA frame size in the SIGSTRUCT (during SGX signing) and in the SECS (during runtime) may mismatch on such CPUs, and `EINIT` instruction fails with `SGX_INVALID_MEASUREMENT`.

This PR simply hard-codes SSA frame size to overapproximated value of 4 pages. Note that on the most feature-rich CPUs to date (with PKRU and the whole feature set of AVX-512), the XSAVE area is slightly less than 3 pages. So 4 pages looks enough for several years to come.

## How to test this PR? 

All tests must pass. Try on some new AVX512-enabled CPUs.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2139#-MShKcg25Qcib749NR1F:-MShKcg25Qcib749NR1G:bpnubye) ([raw file](https://github.com/oscarlab/graphene/blob/e0f6ac91166934abc7974d1d30c10570668c0098/Pal/src/host/Linux-SGX/sgx_framework.c#L102)):*
> ```C
> }
> 
> static size_t get_ssaframesize(uint64_t xfrm) {
> ```

FYI: This was the complicated logic to figure out the SSA frame size based on the XSAVE area size on this machine and the enabled XFRM bits for the SGX enclave. I don't think this code was totally correct but I didn't analyze it deeply. I simply removed it and hard-coded `4 pages` -- we don't care than much about enclave memory to save on SSA pages.
___
*[python/graphenelibos/sgx_sign.py, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2139#-MShKYeX6EVWQTeIDvwY:-MShKYeX6EVWQTeIDvwZ:b169jg3) ([raw file](https://github.com/oscarlab/graphene/blob/e0f6ac91166934abc7974d1d30c10570668c0098/python/graphenelibos/sgx_sign.py#L25)):*
> ```Python
> ARCHITECTURE = 'amd64'
> 
> SSAFRAMESIZE = offs.PAGESIZE
> ```

FYI: This was the old hard-coded value of `1 page`.

**Review by yamahata — DISMISSED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2139#-MSk0IW0-D__4dtnuz0e:-MSk0IW0-D__4dtnuz0f:b-c5ivld) (no related file):*
Hmm, do I see correctly, that this PR allocates 6 more pages per TCS? (comparing to current master)
Could you ensure that this doesn't visibly change performance on huge workloads? It's around 3MB for 128 threads.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2139#-MSk0IW0-D__4dtnuz0e:-MSlLtL414F4onDpai2b:b-1tn8gy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, do I see correctly, that this PR allocates 6 more pages per TCS? (comparing to current master)
Could you ensure that this doesn't visibly change performance on huge workloads? It's around 3MB for 128 threads.
</blockquote></details>

Yes, your understanding and calculations are correct.

We don't have many embarrassingly parallel examples in Graphene (even OpenVINO example is not well parallelizable), so I used Blender for checking on a 64-core machine. I had to modify Blender run script a bit to run on all cores instead of only 4 threads. Plus I increased the enclave size from 2GB to 4GB (otherwise saw mmap failures; this is because I went from 64 enclave threads to 256 enclave threads in the manifest, Blender creates many helper threads for whatever reason).

So here are some median results:
```
# on current master
Fra:1 Mem:19.95M (0.00M, Peak 175.01M) | Time:00:03.07 | Sce: Scene Ve:0 Fa:0 La:0
 Time: 00:03.38 (Saving: 00:00.31)

# on this PR
Fra:1 Mem:19.95M (0.00M, Peak 184.70M) | Time:00:02.97 | Sce: Scene Ve:0 Fa:0 La:0
 Time: 00:03.24 (Saving: 00:00.27)
```

So looks legit to me (even slightly better performance for this PR, but looks like a fluke -- I took the median run of 5 runs, Blender has some variation from run to run).

---

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2139#-MSk0IW0-D__4dtnuz0e:-MT1I6hq593AuyumpA-K:bkhvu8l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, your understanding and calculations are correct.

We don't have many embarrassingly parallel examples in Graphene (even OpenVINO example is not well parallelizable), so I used Blender for checking on a 64-core machine. I had to modify Blender run script a bit to run on all cores instead of only 4 threads. Plus I increased the enclave size from 2GB to 4GB (otherwise saw mmap failures; this is because I went from 64 enclave threads to 256 enclave threads in the manifest, Blender creates many helper threads for whatever reason).

So here are some median results:
```
# on current master
Fra:1 Mem:19.95M (0.00M, Peak 175.01M) | Time:00:03.07 | Sce: Scene Ve:0 Fa:0 La:0
 Time: 00:03.38 (Saving: 00:00.31)

# on this PR
Fra:1 Mem:19.95M (0.00M, Peak 184.70M) | Time:00:02.97 | Sce: Scene Ve:0 Fa:0 La:0
 Time: 00:03.24 (Saving: 00:00.27)
```

So looks legit to me (even slightly better performance for this PR, but looks like a fluke -- I took the median run of 5 runs, Blender has some variation from run to run).
</blockquote></details>

Thanks for testing this, seems we can merge this change :)

---

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2139)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
