### PR TITLE
Fix make clean

### PR DESCRIPTION
**Pull request by HW42**
## Affected components

- [x] README and global configuration
- [x] Linux PAL
- [x] SGX PAL
- [ ] FreeBSD PAL
- [x] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

Fix make clean. There were a bunch of files which weren't cleaned up. This also adds a test to CI to check for such error in the future.

Depends on
https://github.com/oscarlab/graphene-sgx-driver/pull/6
https://github.com/oscarlab/graphene-tests/pull/31

## How to test this PR? 

See included test.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/950)

### CODE REVIEW

**Comment by dcowhig** [comment]
Retest this please

**Comment by HW42** [comment]
Force pushed fixed version. Jenkins doesn't suceed because it has trouble to check out the submodules correctly.

**Comment by dimakuv** [comment]
Jenkins, test this please (some unrelated networking issue)

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by dimakuv** [comment]
Jenkins, test Jenkins please (`sigpending02` failed)

**Pull request merged**
