### PR TITLE
[Pal] Add poor-man's deallocation in slab's memory management

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

The PAL slab memory allocator is used for internal PAL memory objects, in particular, for parsing the manifest. The allocator mostly allocates from a 64MB static array. Previously, the allocator dind't free memory at all. This led to PAL using too much memory (especially in GSC where manifests are huge). This commit adds a couple simple tricks to allow for freeing memory in typical cases (especially realloc).

## How to test this PR? 

All tests must pass. I haven't noticed regression in performance. And I see much lower peak memory utilization (in my TOML manifest experiments).

```
# without this PR, using TOML parser; 1000 manifest keys
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 4084  # BAD

# without this PR, using TOML parser; 2000 manifest keys
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 15996 # REALLY BAD


# with this PR, using TOML parser; 1000 manifest keys
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 3272

# with this PR, using TOML parser; 2000 manifest keys
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 3328
```

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
As long as this quick hack works for graphene usage pattern, I'm fine with it.
(If not, full fledged slab allocator would be needed.)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922#-:-MKeaxhd9z5omyWpw60M:b-7k24k)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — COMMENTED** [review]
Yes, exactly, it is a quick hack. But we'll need to change the PAL allocator in the future (looking at @boryspoplawski).

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922#-:-MKedAUT-Vhtcw9qWmZz:b-u21i71)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1922#-MKedKaq0JI9-SjLrHrJ:-MKedKaq0JI9-SjLrHrK:blaxhy5) (no related file):*
FYI: I also tested this with TOML manifest syntax, GSC and Python3 latest Docker image. Without this patch, GSC-Python3 complained about `need more PAL memory`, now it works.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/slab.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1922#-MKimlgi24pIIt6epFjF:-MKimlgj8oAVBhNx3T8V:bc6cr95) ([raw file](https://github.com/oscarlab/graphene/blob/f347181f91dadddf1ae714885cd26b0f02982bc5/Pal/src/slab.c#L27)):*
> ```C
> static void* g_mem_pool_end = &g_mem_pool[POOL_SIZE];
> static void* g_bottom = g_mem_pool;
> static void* g_top    = &g_mem_pool[POOL_SIZE];
> ```

I don't like top/bottom naming, it's not obvious which one is which (if you think about address values then "top" will be the highest, but if you look at memory layout "visually" then "top" is actually at the lowest addresses). I think low/high is harder to interpret incorrectly.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/slab.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1922#-MKimlgi24pIIt6epFjF:-MKiyV28Da32LIPlCeoz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f347181f91dadddf1ae714885cd26b0f02982bc5/Pal/src/slab.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like top/bottom naming, it's not obvious which one is which (if you think about address values then "top" will be the highest, but if you look at memory layout "visually" then "top" is actually at the lowest addresses). I think low/high is harder to interpret incorrectly.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (Memcached failed to download)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`truncate01` and `writev07` LTP tests failed, should be unrelated?)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1922)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
