### PR TITLE
[LibOS] Add Glibc 2.31

### LINKED ISSUE #623: Consider deprecating the `glibc.heap_size` option
This ugly hack for glibc heap (arena) allocation logic should be abolished or at least rewritten. I will try to propose a better design within the next few weeks.

https://github.com/oscarlab/graphene/blob/0849296a02565b89b43559768f8688a19cfc9185/LibOS/glibc-2.19.patch#L681-L726

### PR DESCRIPTION
**Pull request by dimakuv**
## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] Common PAL code
- [x] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

This PR adds Glibc 2.31 and performs some cleanup/reorganization of old patches. Plus, this PR adds a couple of quick fixes to syscall emulation, since Glibc 2.31 code uncovered a couple corner cases in our LibOS.

Patch cleanup commits include:
- [LibOS] Remove malloc-arena-size patch; consolidate liblibos patch.
- [LibOS] Remove useless glibc_option() Glibc callback.

LibOS fixes' commits include:
- [LibOS] Add clock_nanosleep() syscall emulation
- [LibOS] Check if timeout argument is given in semtimedop()

The final commit adds Glibc 2.31. It is now the **default** on Ubuntu 18.04. However, the "old" Glibc 2.27 is used on Ubuntu 16.04 because 16.04 doesn't ship with GCC 6.0 (required by Glibc 2.31).

Closes #623.

Corresponding PR is https://github.com/oscarlab/graphene-tests/pull/76.

## How to test this PR? 

All Jenkins tests must work.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1369)

### CODE REVIEW

**Comment by dimakuv** [comment]
I am expecting Jenkins on Ubuntu 16.04 to fail because I changed default Glibc to 2.31. This Glibc requires GCC 6.0 to build whereas Ubuntu 16.04 by default ships with GCC 5.4. So Glibc 2.31 build process must complain about bad GCC version.

I think the best way to deal with this is to build Graphene on Ubuntu 16.04 with GLIBC_VERSION=2.23 (i.e., change Jenkinsfiles). And continue with the default Glibc 2.31 which works fine on Ubuntu 18.04 and higher.

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`multi_pthread` LibOS test timed out, cannot reproduce on local system, seems like a fluke)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug please (`stat01` timed out)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`exit_group` timed out)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-SGX please (`test_libos.TC_01_Bootstrap.test_401_exit_group` timed out)

**Pull request merged**
