### PR TITLE
[LibOS] Add Glibc 2.33 (Ubuntu 21.04) and drop 2.27 (Ubuntu 16.04)

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

We dropped support for Ubuntu 16.04 which used Glibc 2.27. Now let's remove all mentions/files for Glibc 2.27.

Also, let's add support for Glibc 2.33 which is used in Ubuntu 21.04.

Glibc 2.33 becomes the default C standard library (it is built by default).

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYoPiSC4aFhrEk0UC7G:b-bljhs6) (no related file):*
Summoning @pwmarcz since he was the last one twiddling with Glibc patches.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoQ0_S0eF5mRXALncp:-MYoQ0_S0eF5mRXALncq:btrary6) (no related file):*
Also summoning @woju.

---

**Comment by dimakuv** [comment]
Jenkins, retest this please (just making sure)

**Review by mkow — DISMISSED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv)

___
*[LibOS/glibc-patches/glibc-2.33.patch, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoqz_L9tc7XFTkMVEm:-MYoqz_L9tc7XFTkMVEn:b-i7y1og) ([raw file](https://github.com/oscarlab/graphene/blob/5b5acaeeb27c7439a65fbc801295e227071df1c6/LibOS/glibc-patches/glibc-2.33.patch#L17)):*
> ```Diff
> index 5d666b1b0c7ba82c7f62609393e8682c0fa66c0e..add41c5e6aca0ee65a6ae1ea8582be3eb4520f00 100644
> --- a/elf/Makefile
> +++ b/elf/Makefile
> ```

Offtopic: This is upstream issue. volunteer?
I don't see good reason to keep it graphene-local.

**Review by pwmarcz — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYorUgv0NtZ5TpiyJUL:b-1r4cml) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Summoning @pwmarcz since he was the last one twiddling with Glibc patches.
</blockquote></details>

Just in case: glibc 2.27 is the default in Ubuntu 18, are we okay with dropping it?

Other than that, LGTM, I don't see anything new here compared to previous patches.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYovDgQCfuDLRD27an4:b5vab08) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Just in case: glibc 2.27 is the default in Ubuntu 18, are we okay with dropping it?

Other than that, LGTM, I don't see anything new here compared to previous patches.
</blockquote></details>

I was loose in my language. We (historically) use Glibc 2.31 in Graphene for Ubuntu 18.04 Jenkins tests, and we used Glibc 2.27 for Ubuntu 16.04 Jenkins tests. The stock Ubuntu 18.04 actually comes with 2.27, and stock Ubuntu 16.04 comes with 2.23. So Graphene kinda uses "next version of Glibc" always (for no particularly good reason, simply because it works).

I'm now not sure if this is a good strategy... @mkow @woju @boryspoplawski @yamahata What do you think? Should we go in lock-step with Ubuntus? Or giving other repos support coming soon, this "tie Glibc version to Ubuntu version" logic makes no sense?

---
___
*[LibOS/glibc-patches/glibc-2.33.patch, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoqz_L9tc7XFTkMVEm:-MYox0cqD_mNJKa4Xkdc:b-ccr0pc) ([raw file](https://github.com/oscarlab/graphene/blob/5b5acaeeb27c7439a65fbc801295e227071df1c6/LibOS/glibc-patches/glibc-2.33.patch#L17)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Offtopic: This is upstream issue. volunteer?
I don't see good reason to keep it graphene-local.
</blockquote></details>

Yes, it would be good to submit this bug fix to the Glibc upstream. Just need a volunteer :)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYoxnOQ2wVYvxMufJiQ:b-p6mfek) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was loose in my language. We (historically) use Glibc 2.31 in Graphene for Ubuntu 18.04 Jenkins tests, and we used Glibc 2.27 for Ubuntu 16.04 Jenkins tests. The stock Ubuntu 18.04 actually comes with 2.27, and stock Ubuntu 16.04 comes with 2.23. So Graphene kinda uses "next version of Glibc" always (for no particularly good reason, simply because it works).

I'm now not sure if this is a good strategy... @mkow @woju @boryspoplawski @yamahata What do you think? Should we go in lock-step with Ubuntus? Or giving other repos support coming soon, this "tie Glibc version to Ubuntu version" logic makes no sense?
</blockquote></details>

I would still keep 2.27 just because it's popular (due to being default in Ubuntu18.04).
Otoh we don't have capacity to test all versions and just building takes a lot of Jenkins time without much value/gains, so I guess we can drop it. Besides glibc should be backward compatible.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv, @mkow, @woju, and @yamahata)

___
*[LibOS/glibc-patches/glibc-2.33.patch, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoqz_L9tc7XFTkMVEm:-MYoynO9DdB_dDKqkYvF:b-v6bci5) ([raw file](https://github.com/oscarlab/graphene/blob/5b5acaeeb27c7439a65fbc801295e227071df1c6/LibOS/glibc-patches/glibc-2.33.patch#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it would be good to submit this bug fix to the Glibc upstream. Just need a volunteer :)
</blockquote></details>

I can try to upstream it, but we will still need to keep it here for a long time (as we are tied to a specific version, so even backporting the patch won't work).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYqWTIq4D0aO0nFpfvz:b-ojj5q3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would still keep 2.27 just because it's popular (due to being default in Ubuntu18.04).
Otoh we don't have capacity to test all versions and just building takes a lot of Jenkins time without much value/gains, so I guess we can drop it. Besides glibc should be backward compatible.
</blockquote></details>

Actually, the reason why we kept the 2.27 was that this is the newest which built on 16.04 - newer ones required newer GCC. From my side I'd be fine with supporting only the newest glibc - less bugs and security issues to worry about, and it's backward compatible, so all apps should work.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYsS6Yv9_HwJhcf8SGT:bwdp55q) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, the reason why we kept the 2.27 was that this is the newest which built on 16.04 - newer ones required newer GCC. From my side I'd be fine with supporting only the newest glibc - less bugs and security issues to worry about, and it's backward compatible, so all apps should work.
</blockquote></details>

I would like to also hear @woju opinion on this.

But for now, I'm going with a compromise: keeping 2.27 patches and removing the build of older GCC versions. (So in our Jenkins, we currently only build & test the latest 2.33).

---
___
*[LibOS/glibc-patches/glibc-2.33.patch, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoqz_L9tc7XFTkMVEm:-MYsSK8IBShZMg1oNHS2:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/5b5acaeeb27c7439a65fbc801295e227071df1c6/LibOS/glibc-patches/glibc-2.33.patch#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I can try to upstream it, but we will still need to keep it here for a long time (as we are tied to a specific version, so even backporting the patch won't work).
</blockquote></details>

Thanks!

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

___
*[.ci/lib/config-ubuntu18.04.jenkinsfile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYsUkjg8ESVOXLjzc1X:-MYsUkjg8ESVOXLjzc1Y:b-q0ni7j) ([raw file](https://github.com/oscarlab/graphene/blob/fd0c0a26ca5afecaf92cceec816cdfaf2b521d0c/.ci/lib/config-ubuntu18.04.jenkinsfile#L1)):*
> ```
> env.GLIBC_VERSION = '2.33'
> ```

Blocking myself: must change also `config-ubuntu20.04` file in the same way after #2272 is merged.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYt9psMC1uR6Itrgjn6:b-wpjzi1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would like to also hear @woju opinion on this.

But for now, I'm going with a compromise: keeping 2.27 patches and removing the build of older GCC versions. (So in our Jenkins, we currently only build & test the latest 2.33).
</blockquote></details>

I'm not sure if this is a good idea, if we support it then it seems like using it is fine, while it isn't - it's really old and probably vulnerable (not even mentioning normal bugs...).

---

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYtGN6L061SqxvBZoaV:bix4a0k) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if this is a good idea, if we support it then it seems like using it is fine, while it isn't - it's really old and probably vulnerable (not even mentioning normal bugs...).
</blockquote></details>

Yeah, I didn't think about it before, but Ubuntu's glibc 2.27 is probably pretty different from the upstream one and has security fixes backported? (see http://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.27-3ubuntu1.2/changelog)

Also, we still have patches for glibc 2.31 (which, going by that, we should also discourage people from using), so maybe two versions is enough.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYtJWIl6Nmqw59-m0bE:b-uszg9b) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, I didn't think about it before, but Ubuntu's glibc 2.27 is probably pretty different from the upstream one and has security fixes backported? (see http://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.27-3ubuntu1.2/changelog)

Also, we still have patches for glibc 2.31 (which, going by that, we should also discourage people from using), so maybe two versions is enough.
</blockquote></details>

Yup, I think they backport patches themselves (which our old glibc will be missing).

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYv_4ybDX9zYBqVGT82:bmvioex) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I think they backport patches themselves (which our old glibc will be missing).
</blockquote></details>

@dimakuv I don't have any great proposal here. I'd ask around our downstream users which glibc version do they really use, if they care and if they had problems with glibc versions. What is even the point of testing multiple glibcs if no-one uses them?

I don't think there's much we can gain from different versions+different distros, because we need to settle on a single version (+set of patches), because we'd prefer to have the same runtime directory. So yeah, we can go and see what they're doing, but I doubt there will be anything we could use there. A reasonable default would be to just follow new versions (they're releasing every 6 months) + security patches if we think they're important enough to break manifest signatures.

Then, if it turns out it would be hard/impossible to compile and package exact same runtime directories for different distros we could think about supplying different versions on different distros (forcing developers to provide different manifests) -- then it would be convenient to base the runtime package on whatever distro is already doing.

A disadvantage to "follow master" approach is that historically there were situations where updating glibc broke something (the most visible, recent one was between Ubuntu 18.04 and Ubuntu 20.04: on 18.04 all software was automatically linked against libm, and suddenly on 20.04 you needed to add -lm at compile time, so nearly all software compiled on Ubuntu 18.04 was crashing on 20.04, because acosf symbol was missing at loading time). But again, is this a problem which our users care about? I just don't know. I haven't spoken to them about this.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoQ0_S0eF5mRXALncp:-MYvjG_10fAz3BVYBuvP:b-b4cahq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also summoning @woju.
</blockquote></details>

Hi, answered in other thread.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYxioZfEEsDUfBCB-Np:b-y85pbu) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@dimakuv I don't have any great proposal here. I'd ask around our downstream users which glibc version do they really use, if they care and if they had problems with glibc versions. What is even the point of testing multiple glibcs if no-one uses them?

I don't think there's much we can gain from different versions+different distros, because we need to settle on a single version (+set of patches), because we'd prefer to have the same runtime directory. So yeah, we can go and see what they're doing, but I doubt there will be anything we could use there. A reasonable default would be to just follow new versions (they're releasing every 6 months) + security patches if we think they're important enough to break manifest signatures.

Then, if it turns out it would be hard/impossible to compile and package exact same runtime directories for different distros we could think about supplying different versions on different distros (forcing developers to provide different manifests) -- then it would be convenient to base the runtime package on whatever distro is already doing.

A disadvantage to "follow master" approach is that historically there were situations where updating glibc broke something (the most visible, recent one was between Ubuntu 18.04 and Ubuntu 20.04: on 18.04 all software was automatically linked against libm, and suddenly on 20.04 you needed to add -lm at compile time, so nearly all software compiled on Ubuntu 18.04 was crashing on 20.04, because acosf symbol was missing at loading time). But again, is this a problem which our users care about? I just don't know. I haven't spoken to them about this.
</blockquote></details>

OK, so it's unclear if keeping Glibc 2.27 and 2.31 versions is good/bad.

I suggest to go ahead and merge this PR, and decide later whether we want to keep these legacy Glibcs (who knows, maybe some weird OS distro works only with one of these versions and not with 2.33). We can always remove these later.

For now, all Jenkins pipelines and all local builds default to the latest 2.33.

Note: I rebased to the latest master to test Ubuntu 20.04 which was merged in the meantime.

---
___
*[.ci/lib/config-ubuntu18.04.jenkinsfile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYsUkjg8ESVOXLjzc1X:-MYxi9Ew9Zi3pAWNLgYm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fd0c0a26ca5afecaf92cceec816cdfaf2b521d0c/.ci/lib/config-ubuntu18.04.jenkinsfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: must change also `config-ubuntu20.04` file in the same way after #2272 is merged.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYypkfO69lozkV7EiZb:bfq390l) (no related file):*
> OK, so it's unclear if keeping Glibc 2.27 and 2.31 versions is good/bad.

Is it, actually? What are the arguments to keep 2.27 except that in theory there may come some users wanting it? (but we don't know about any at the moment, it's purely theoretical)
For me keeping old, buggy and vulnerable versions of software sounds like a very bad idea. E.g. users may think that they should use the same version as they have in their distro (but their distro backported security fixes) and switch this config, leading to them using vulnerable glibc.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYyxWsR309qJ8bd7J3J:b-3k3h7l) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> OK, so it's unclear if keeping Glibc 2.27 and 2.31 versions is good/bad.

Is it, actually? What are the arguments to keep 2.27 except that in theory there may come some users wanting it? (but we don't know about any at the moment, it's purely theoretical)
For me keeping old, buggy and vulnerable versions of software sounds like a very bad idea. E.g. users may think that they should use the same version as they have in their distro (but their distro backported security fixes) and switch this config, leading to them using vulnerable glibc.
</blockquote></details>

@mkow By this logic, shouldn't we remove **both 2.27 and 2.31**? And keep only the newest 2.33?

I don't have a strong opinion on this, so I'll let @mkow and @boryspoplawski find the compromise solution :)

---

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MYyy85E0OZC_YWwfPQ5:bb18ksn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow By this logic, shouldn't we remove **both 2.27 and 2.31**? And keep only the newest 2.33?

I don't have a strong opinion on this, so I'll let @mkow and @boryspoplawski find the compromise solution :)
</blockquote></details>

I'd gladly remove 2.31 also :) But it's not as old as 2.27, so the danger is not the same. 2.27 is 3 years old, and 2.31 is only one year old.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZ-9qlwDC9bq7RUuIJr:b-5zco75) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd gladly remove 2.31 also :) But it's not as old as 2.27, so the danger is not the same. 2.27 is 3 years old, and 2.31 is only one year old.
</blockquote></details>

The only reason I can see to keep older versions it to get more syscalls coverage (there are definitely some differences in what syscalls glibc calls and how/with what parameteres/in what combination).
But since we do not test them anyway (just build), I see no reason to keep them. Let's not do that in this PR tho.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 4 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZ4TXkPCCwC1blav2yI:b-5j01dj) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only reason I can see to keep older versions it to get more syscalls coverage (there are definitely some differences in what syscalls glibc calls and how/with what parameteres/in what combination).
But since we do not test them anyway (just build), I see no reason to keep them. Let's not do that in this PR tho.
</blockquote></details>

@boryspoplawski Do you mean that you would like to keep 2.27 in this PR (i.e., **not** remove it in this PR)?

@mkow Do you want me to remove 2.27 from this PR?

---

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZ4UbCL17RMZxTIDnVX:bsn5jm9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Do you mean that you would like to keep 2.27 in this PR (i.e., **not** remove it in this PR)?

@mkow Do you want me to remove 2.27 from this PR?
</blockquote></details>

No, I meant let's remove everything, but let's keep this PR as it is (i.e. only remove 2.27 here).

Update: oh, I see you discarded the removal? Anyway I'm for removing everything. Whether it happens in this or another PR seems irrelevant to me (but please use different commits).

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZ5WyEBC0YFqE58Eh7s:btejsgi) (no related file):*
> @mkow Do you want me to remove 2.27 from this PR?

I'm for removing it here. Ad 2.31: I'm less radical, as it's much more recent, so we can keep it for some time if you want :)

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 5 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZCI-w_-5hb09FuFOkI:b-zhgbmj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> @mkow Do you want me to remove 2.27 from this PR?

I'm for removing it here. Ad 2.31: I'm less radical, as it's much more recent, so we can keep it for some time if you want :)
</blockquote></details>

Done. I removed 2.27 but still kept 2.31. In a separate commit. Also rebased (because of that Ubuntu 20.04 bug with vDSO).

---

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-20.04-apps please (`python-simple` failed, unclear why, probably need to debug this)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 5 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @yamahata)

___
*[Examples/curl/curl.manifest.template, line 22 at r4](https://reviewable.io/reviews/oscarlab/graphene/2325#-MZEYatb97k0DpX_SWig:-MZEYatb97k0DpX_SWih:bp6jcox) ([raw file](https://github.com/oscarlab/graphene/blob/50ebe966db9995b752f95951d48390074d29dac6/Examples/curl/curl.manifest.template#L22)):*
> ```
> # paths must be taken from fs.mount.xxx.path, not fs.mount.xxx.uri).
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"
> loader.env.HOME = "{{ home }}"
> ```

FYI: Apparently, new Curl versions fail if they don't find `$HOME`. See https://github.com/curl/curl/issues/6200

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-20.04 please (`getrlimit03 ` LTP test failed with `TBROK: Test killed by SIGPWR!`)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 5 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2325#-MYoPiSC4aFhrEk0UC7F:-MZHun2m5Egj3y9TEjai:b-99jwhq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I removed 2.27 but still kept 2.31. In a separate commit. Also rebased (because of that Ubuntu 20.04 bug with vDSO).
</blockquote></details>

I fixed all the detected bugs (see separate commits) and rebased again. This PR is ready for final review. @mkow @boryspoplawski @pwmarcz @yamahata .

---

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 7 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[LibOS/Makefile, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/2325#-MZIsbUG4UqeOY844QfJ:-MZIsbUG4UqeOY844QfK:b5zdi9t) ([raw file](https://github.com/oscarlab/graphene/blob/61a77adb6926e76da1a2d5c8bae6b203da05f2b4/LibOS/Makefile#L43)):*
> ```
>   \
> ```

nitpick: double space (please fix when rebasing)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/Makefile, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/2325#-MZIsbUG4UqeOY844QfJ:-MZJ87sOBwidWj1VD71Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61a77adb6926e76da1a2d5c8bae6b203da05f2b4/LibOS/Makefile#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>   \
> ```

nitpick: double space (please fix when rebasing)
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by pwmarcz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2325)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
