### PR TITLE
[LibOS] Another series of code moves

### PR DESCRIPTION
**Pull request by stefanberger**
This is another series of code moves of x86_64-specific code out of common files into x86_64-specific files.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1541)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, test this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
