### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by chiache**
## Affected components

- [x] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 

The PR adds a code of conduct for the project. The code of conduct is needed for the project proposal to the Confidential Computing Consortium (CCC): https://github.com/confidential-computing/governance/blob/master/project-progression-template.md. I adapted this code of conduct from the contributor covenant (version 2): https://www.contributor-covenant.org/

## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/1335)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PTYuY8rZJWHVx75l4:-M0PTYuY8rZJWHVx75l5:b-szgxw8) (no related file):*
Thanks for this PR!

We may want to change it to the RST format, but since we have some other MD-formatted files anyway, I'm not blocking on this.

---
___
*[CODE_OF_CONDUCT.md, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PSqnw1mVUaotABsz_:-M0PSqnx-ze0LvKblpyj:b6ry59v) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L26)):*
> ```Markdown
>   and learning from the experience
> * Focusing on what is best not just for us as individuals, but for the overall
>   community
> ```

Dot at the end.
___
*[CODE_OF_CONDUCT.md, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PSsPIDlnlftfT_5Dy:-M0PSsPIDlnlftfT_5Dz:b6ry59v) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L37)):*
> ```Markdown
>   address, without their explicit permission
> * Other conduct which could reasonably be considered inappropriate in a
>   professional setting
> ```

Dot at the end.
___
*[CODE_OF_CONDUCT.md, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PSocf0cZw6qOJzfxh:-M0PSocf0cZw6qOJzfxi:bkx5k5y) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L43)):*
> ```Markdown
> Community leaders are responsible for clarifying and enforcing our standards of
> acceptable behavior and will take appropriate and fair corrective action in
> esponse to any behavior that they deem inappropriate, threatening, offensive, or
> ```

`esponse` -> `response`

**Review by yamahata — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M0QDqnq3fA7VtmT24sl:bqma57r) (no related file):*
I can see the difference (including formatting) from https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md 

Is there any reason to change it?
If there is no strong reason, we should simply just import it from the original as is. (including file name. i.e. code_of_conduct.md instead of CODE_OF_CONDUCT.md)

---

**Review by yamahata — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M0QEUP81wwi0Ufz3l4Q:beoc6gb) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I can see the difference (including formatting) from https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md 

Is there any reason to change it?
If there is no strong reason, we should simply just import it from the original as is. (including file name. i.e. code_of_conduct.md instead of CODE_OF_CONDUCT.md)

</blockquote></details>

Regarding to the contents itself, I think it's reasonable.

---

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PTYuY8rZJWHVx75l4:-M1DHbxK4NtBqRQ62bCb:b-vqslui) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for this PR!

We may want to change it to the RST format, but since we have some other MD-formatted files anyway, I'm not blocking on this.
</blockquote></details>

This won't be the case after merging #1273, so I'd prefer to have it in reST

---
___
*[CODE_OF_CONDUCT.md, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PSqnw1mVUaotABsz_:-M1DJqxH-xbwI7ERb9gS:bdzps1u) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Dot at the end.
</blockquote></details>

I guess this was intended, none of the sentences on this list have dots nor commas. Not sure which version is more valid in English.
___
*[CODE_OF_CONDUCT.md, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M1DJAuZ9Ll4r6_wRNlA:-M1DJAuZ9Ll4r6_wRNlB:b-c0jnqc) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L63)):*
> ```Markdown
> Instances of abusive, harassing, or otherwise unacceptable behavior may be
> reported to the community leaders responsible for enforcement at
> [support@grapheneproject.io]. All complaints will be reviewed and investigated
> ```

This isn't a good point of contact for such issues, it's publicly archived.

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @dimakuv)

___
*[CODE_OF_CONDUCT.md, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M28V2579uxqGm3b7q-A:-M28V2579uxqGm3b7q-B:b-ldw023) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L20)):*
> ```Markdown
> community include:
> 
> * Demonstrating empathy and kindness toward other people
> ```

I don't think the empathy is a standard. There are people not capable of "demonstrating empathy" through no fault of their own (https://en.wikipedia.org/wiki/Empathy#Impairment, https://en.wikipedia.org/wiki/Autism_spectrum#Communication_skills) and they are no less welcome in the community.

Also, most of the people working on Graphene are not native English speakers, they are not accustomed to social norms in English-speaking countries (yes, they are different in different countries), and they should not be judged against them.
___
*[CODE_OF_CONDUCT.md, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M28NJfY-l3vsT4TdpGZ:-M28NJfY-l3vsT4TdpG_:bd5rtc) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L67)):*
> ```Markdown
> 
> All community leaders are obligated to respect the privacy and security of the
> reporter of any incident.
> ```

Community leaders also have obligations to the accused, sometimes even for legal reasons like labour laws. In most countries, in employment relationship, you cannot censure someone without justifying the action, and this cannot be a general reason of "violating CoC/community standards" (or, even worse, vague accusations of "toxicity" or "concern", which unfortunately were thrown around as part of CoC-related disputes in several high profile software projects). You'd have to point to a particular message/commit/quote or whatever caused the action, which depending on context, might reveal the reporter's identity.

Now the particulars very much depends on particular country and legal system, so I can't give example, but there are situations where maintainers will face choice between:
- effectively naming the accuser to the accused
- expose themselves to legal liability
- take no action against the accused.

Irrespective of all legal problems, the accused must have a possibility to respond to accusations before any final action is taken. This is simply a question of fairness, and it also might conflict with absolute protection of reporter's identity. Not to mention the situation when the accusations turn out to be false: then the reporter could be requested to make a public apology (which I'd argue would be a poor choice, because the censure should not public for an act that also wasn't public, but it is still an enumerated possibility).

I think this is ultimately reporter's choice.
___
*[CODE_OF_CONDUCT.md, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1335#-M28Wdgw6OHSYNxEX-to:-M28WdgxCTXX9lXgY8iI:b-ret7jw) ([raw file](https://github.com/oscarlab/graphene/blob/501976f93888aa17a1d0af52b0a4e3729425cb79/CODE_OF_CONDUCT.md#L72)):*
> ```Markdown
> 
> Community leaders will follow these Community Impact Guidelines in determining
> the consequences for any action they deem in violation of this Code of Conduct:
> ```

I'd add a note that the choice of action is a sole decision of maintainers (i.e. not of the reporter and especially not of Twitter). Also, the maintainers could use some good judgement about how to announce the action to the general public, to not accidentally defame the guilty (not to repeat the the mistake of StackOverflow).

**Comment by monavij** [comment]
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)_ status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M0QDqnq3fA7VtmT24sl:bqma57r) (no related file):_
> I can see the difference (including formatting) from https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md
> 
> Is there any reason to change it?
> If there is no strong reason, we should simply just import it from the original as is. (including file name. i.e. code_of_conduct.md instead of CODE_OF_CONDUCT.md)

I agree with Isaku. Why is there any need to chnage it and why don't we just import the original?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M2YUwS43abj8DQXNKSQ:b-1ivv77) (no related file):*
<details><summary><i>Previously, monavij wrote…</i></summary><blockquote>

I agree with Isaku. Why is there any need to chnage it and why don't we just import the original? 
</blockquote></details>

For one, because contributor covenant is not the only CoC template available. This template is not perfect, I posted a couple of problems below. One of good alternatives is from Ubuntu: https://ubuntu.com/community/code-of-conduct (it would need adaptation anyway, because it has references to Ubuntu-specific project bodies). Another good one, if minimal, is from PostgreSQL: https://www.postgresql.org/about/policies/coc/ (also in need of editing the Committee part). But neither of those are perfect too.

Another reason is, the author of this particular template is highly controversial and some people prefer not to work with that individual.

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M2Zd1HM3YrJIkmDjEp0:b4afjc) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For one, because contributor covenant is not the only CoC template available. This template is not perfect, I posted a couple of problems below. One of good alternatives is from Ubuntu: https://ubuntu.com/community/code-of-conduct (it would need adaptation anyway, because it has references to Ubuntu-specific project bodies). Another good one, if minimal, is from PostgreSQL: https://www.postgresql.org/about/policies/coc/ (also in need of editing the Committee part). But neither of those are perfect too.

Another reason is, the author of this particular template is highly controversial and some people prefer not to work with that individual.
</blockquote></details>

+1 to PostgreSQL CoC. But seems like no other SGX-related project has a Code of Conduct document in their GitHub repos, so this PR is really low priority.

---

**Comment by monavij** [comment]
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)_ status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, and @yamahata)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M2Zd1HM3YrJIkmDjEp0:b4afjc) (no related file):_
> 
> Previously, woju (Wojtek Porczyk) wrote…
> > For one, because contributor covenant is not the only CoC template available. This template is not perfect, I posted a couple of problems below. One of good alternatives is from Ubuntu: https://ubuntu.com/community/code-of-conduct (it would need adaptation anyway, because it has references to Ubuntu-specific project bodies). Another good one, if minimal, is from PostgreSQL: https://www.postgresql.org/about/policies/coc/ (also in need of editing the Committee part). But neither of those are perfect too.
> > Another reason is, the author of this particular template is highly controversial and some people prefer not to work with that individual.
> 
> +1 to PostgreSQL CoC. But seems like no other SGX-related project has a Code of Conduct document in their GitHub repos, so this PR is really low priority.

Let's just stick with  https://www.contributor-covenant.org/ version 2 as the baseline, as all the CCC projects are currently using CC2.0. @woju - can you please propose updated language for the three points you raised?  We think the points you raised are valid concerns and CC2.0 can be improved to address the concerns you raised.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1335)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0PTYuY8rZJWHVx75l4:-M37pGGm7MdY2urbCC15:b-8tvwj9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This won't be the case after merging #1273, so I'd prefer to have it in reST
</blockquote></details>

#1273 was merged, so definitely need to change this PR to reST.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1335#-M0QDqnq3fA7VtmT24sk:-M37pLUU2Rk4Ilc7TBHs:b-fifclp) (no related file):*
<details><summary><i>Previously, monavij wrote…</i></summary><blockquote>

Let's just stick with  https://www.contributor-covenant.org/ version 2 as the baseline, as all the CCC projects are currently using CC2.0. @woju - can you please propose updated language for the three points you raised?  We think the points you raised are valid concerns and CC2.0 can be improved to address the concerns you raised.   
</blockquote></details>

I'm also reverting my vote in favor of the current (CC 2.0) text. Most major companies and open-source projects adopted this, and so I don't see a need to have our own version if the current one works well for others. Also, having our home-brewed version means unnecessary questions and *not* having a badge form GitHub :)

---

**Comment by dimakuv** [comment]
This PR was moved to https://github.com/gramineproject/gramine/pull/195.

**Pull request closed without merging**
