### PR TITLE
[Linux PAL] Ensure the usage of alternative stack for host exception handling

### LINKED ISSUE #486: [Pal/Linux] Signals are not delivered on altstack because SA_ONSTACK is not used
PR #281 introduces alternate signal stack context to handle signals (only for Linux PAL).

The alternate signal stack is malloced for each thread right after the TCB object and [sigaltstack is called](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux/db_threading.c#L63) to install this alternate stack.

However, for a signal to be delivered on the alternate stack, its signal handler must be registered via `sigaction()` and contain `struct sigaction sa = {..., .sa_flags = SA_ONSTACK}`. Otherwise, the signal is delivered to the normal stack context. [See this](https://www.gnu.org/software/libc/manual/html_node/Flags-for-Sigaction.html#Flags-for-Sigaction).

**Fix**: all (?) signals in `Pal/src/host/Linux/db_exception.c` must be registered with the flag `SA_ONSTACK` set.

### PR DESCRIPTION
**Pull request by chiache**
Please fill in the following form before submitting this PR and ensure that your code follows our [coding style guideline](../blob/master/CODESTYLE.md).

## Affected components

- [ ] README and global configuration
- [x] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes (reasons and measures)

Fixes #486.

The new host exception handling scheme in the Linux PAL is supposed to use an alternate stack to prevent mixing the PAL exception handler frame with LibOS/application frames. The previous implementation is not using the assigned alternate stack because `SA_ONSTACK` is not given as a flag to the `sigaction` system call. This PR adds the `SA_ONSTACK` flag.

This PR also fixes another issue with alternate stack assignment. The stack pointer given to the `sigaltstack` system call, i.e.,`ss.ss_sp`, should point to the bottom of the stack instead of the top.

A regression test is added for the Linux PAL only to check if the alternate stack is ever used.

## How to test this PR? (if applicable)

Running the `Exception` test in the PAL regression test directory. A good output should look like this:
```
$ ../../Runtime/pal_loader Exception
stack in main: 0x7ffc29766618
Div-by-Zero Exception Handler 1: 0x40043d, rip = 0x40043d
stack in handler: 0x7ffc29765e40
Div-by-Zero Exception Handler 2: 0x40046a, rip = 0x40046a
stack in handler: 0x7ffc29765e40
Memory Fault Exception Handler: 0x1000, rip = 0x400484
stack in handler: 0x7ffc29765e40
```

The stack pointer in the main function should not be on the same page with the stack pointers inside the handlers.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/527)

### CODE REVIEW

**Comment by dcowhig** [comment]
Retest this please

**Comment by dcowhig** [comment]
Retest this please

**Comment by dcowhig** [comment]
Retest this please

**Comment by dcowhig** [comment]
Retest this please

**Comment by dimakuv** [comment]
@chiache should have another look at this.

**Comment by mkow** [comment]
@yamahata @HW42 @dimakuv Is this PR still relevant? There was a bunch of changes in exception handling recently, so this may have already been covered by one of those PRs.

**Pull request closed without merging**
