### PR TITLE
Pulling in the new lmbench repo

### PR DESCRIPTION
**Pull request by bpjain**
Pulling lmbench for CI to pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/323)

### CODE REVIEW

**Comment by bpjain** [comment]
:lgtm: The only change requested for the URL is fixed in commit  3579f2a.

**Comment by bpjain** [comment]
___
*[.gitmodules, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/323#-LSXFx7m5MnvUu_sUoFt:-LSn0xtdCRFC1givSWTP:bepuwoz) ([raw file](https://github.com/oscarlab/graphene/blob/869a28be748224b2916c441d445e12f45a6a9329/.gitmodules#L9)):*
<details><summary><i>Previously, bpjain wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Chia-che, does the new commit resolve your issue?

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
The tcp/udp issues are somewhat consistent.  I'd like Bhushan to review for whether this is a legit regression before we move forward.

**Comment by bpjain** [comment]
I ran the failing lmbench test (lat_udp) on my machine manually. I was using plain graphene, not SGX. I am seeing the same "Recv timed out" message but pal_loader returns 0 on my machine, whereas, the Jenkins log shows a return of 1 from pal_loader with the same message "Recv timed out". Either way, this seems like a legit regression.

**Pull request closed without merging**
