### PR TITLE
[LibOS] Update for path lookup functions

### PR DESCRIPTION
**Pull request by pwmarcz**
Applying feedback left by @boryspoplawski in #2333 (after we merged it). It's mostly TODOs for various corner cases, and one fix to how we count references.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)

### CODE REVIEW

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_fs.h, line 414 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bliN7MoR9SdDow48:-M_1bliN7MoR9SdDow49:b-riqhy3) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/include/shim_fs.h#L414)):*
>man for open(2) states that When both O_CREAT and O_DIRECTORY are specified in flags and the file specified by pathname does not exist, open() will create a regular file (i.e., O_DIRECTORY is ignored). Is that not the case on newer kernel? Because if it is, we might need to emulate it...

You're right, I just tried that out on 5.11 and it still works that way (creates a file and fails with `ENOTDIR`).

I don't have a good idea how to fix it without making a major change like splitting this function into smaller ones. Adding a TODO for now.
___
*[LibOS/shim/src/fs/shim_namei.c, line 203 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1cDEc9PlEDlpTLjOe:-M_1cDEc9PlEDlpTLjOf:b-xfrsii) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L203)):*
>This seems incorrect: we do not get this dentry and then unlock g_process.fs_lock. What if another thread changes cwd and this dentry is destroyed?

>Maybe change this to set dent directly and just add an else clause at the end to handle start != NULL case (and just do dent = start there)?

Right. Nothing else should delete a dentry while `g_dcache_lock` is held, but it's bad to depend on it. Your suggested fix looks good.
___
*[LibOS/shim/src/fs/shim_namei.c, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1c65R5SUoNRH1Scw1:-M_1c65R5SUoNRH1Scw2:br37k78) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L230)):*
>If path == "/" and !(flags & LOOKUP_DIRECTORY) this will still succeed and return root dentry.

Lack of `LOOKUP_DIRECTORY` does not mean "require a non-directory".

I get how this loop is flawed, though - it works mostly because `"/"` is special, and `""` is not allowed. It would be better to check the last component after the loop.

I will probably return to that when working on mounts - this code will need to traverse from mountpoint (in outer filesystem) to mount root (in mounted filesystem).
___
*[LibOS/shim/src/fs/shim_namei.c, line 336 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1c07T9pxCd6TA8b2W:-M_1c07T9pxCd6TA8b2X:b2i7o8y) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L336)):*
>NP: _path_lookupat?

I preferred to do it this way because it's (slightly) easier to read: you don't need to follow two layers of indirection, only one. On the other hand, the `/*link_depth=*/0` part is a (slight) duplication, and if calling `do_path_lookupat` involved more complicated setup, I would call `_path_lookupat` here.

Is there a strong reason to do it the other way?
___
*[LibOS/shim/src/fs/shim_namei.c, line 473 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1beTj7MveKbL7s0mg:-M_1beTj7MveKbL7s0mh:b-uvthze) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L473)):*
>I guess we do not support O_PATH?

We don't, and maybe the comment should reflect that (and also, the flags should be validated in `open`...). I added a comment about `O_PATH` here, and added a `TODO` regarding the validation.
___
*[LibOS/shim/src/fs/shim_namei.c, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bsBY-a8Wl6hZd2QV:-M_1bsBY-a8Wl6hZd2QW:b-ftzati) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L638)):*
>How can we have access to only part of directory?

This is `-EACCES` as returned from underlying filesystem, it actually happens in practice (since Graphene might not have access to some files).

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 414 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bliN7MoR9SdDow48:-M_29o7eDnVW2brThNCw:bq4qe1g) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/include/shim_fs.h#L414)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>man for open(2) states that When both O_CREAT and O_DIRECTORY are specified in flags and the file specified by pathname does not exist, open() will create a regular file (i.e., O_DIRECTORY is ignored). Is that not the case on newer kernel? Because if it is, we might need to emulate it...

You're right, I just tried that out on 5.11 and it still works that way (creates a file and fails with `ENOTDIR`).

I don't have a good idea how to fix it without making a major change like splitting this function into smaller ones. Adding a TODO for now.
</blockquote></details>

I guess we could also ignore it? `man` states it's a bug, so nobody should rely on it anyway.
___
*[LibOS/shim/src/fs/shim_namei.c, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1c65R5SUoNRH1Scw1:-M_2BjFk4HdDcNSSBnv-:b-mce5fo) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L230)):*
> Lack of LOOKUP_DIRECTORY does not mean "require a non-directory".

Ah, right.
___
*[LibOS/shim/src/fs/shim_namei.c, line 336 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1c07T9pxCd6TA8b2W:-M_2BttJEiUIGqQXWLSd:b-vybkv8) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L336)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>NP: _path_lookupat?

I preferred to do it this way because it's (slightly) easier to read: you don't need to follow two layers of indirection, only one. On the other hand, the `/*link_depth=*/0` part is a (slight) duplication, and if calling `do_path_lookupat` involved more complicated setup, I would call `_path_lookupat` here.

Is there a strong reason to do it the other way?
</blockquote></details>

I've just read the comment that `path_lookup` is just a wrapper around `_path_lookup` and was surprised to see its not :)
___
*[LibOS/shim/src/fs/shim_namei.c, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bsBY-a8Wl6hZd2QV:-M_2DkG585xkMyjPgPC_:bcax0pz) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L638)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>How can we have access to only part of directory?

This is `-EACCES` as returned from underlying filesystem, it actually happens in practice (since Graphene might not have access to some files).
</blockquote></details>

I thought it's supposed to list a content of a directory, in which case we need access to the directory itself, not the files inside it. When exactly it can happen?

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 5 unresolved discussions (waiting on @pwmarcz)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 5 unresolved discussions (waiting on @pwmarcz)

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 414 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bliN7MoR9SdDow48:-M_53OXB8Wm4NtuQx4W5:bu728ce) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/include/shim_fs.h#L414)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess we could also ignore it? `man` states it's a bug, so nobody should rely on it anyway.
</blockquote></details>

OK, but since we already spent some time on that, I'm leaving a comment here.
___
*[LibOS/shim/src/fs/shim_namei.c, line 336 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1c07T9pxCd6TA8b2W:-M_54qmH6AGcn-wYydJx:b-it5djf) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L336)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've just read the comment that `path_lookup` is just a wrapper around `_path_lookup` and was surprised to see its not :)
</blockquote></details>

I'll update the comments since I'm here anyway.
___
*[LibOS/shim/src/fs/shim_namei.c, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bsBY-a8Wl6hZd2QV:-M_55mJq6PMGHpndLOfa:b-ywimki) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L638)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought it's supposed to list a content of a directory, in which case we need access to the directory itself, not the files inside it. When exactly it can happen?
</blockquote></details>

I remember I removed this special treatment of EACCES and it failed some test, I can't find it now...

Anyway, one case (which I just replicated) is when you have a symlink on a host system pointing somewhere inaccessible. We do not expose these symlinks to Graphene as symlinks, but pretend they are the target file (long story, but mounting the binaries in `Runtime/...` depends on it).

So if you try to list a directory containing such symlinks, we will call `lookup_dentry` for all of them, which translates to `stat` on the underlying filesystem, which fails with EACCES. Without this line, that causes listing the directory to fail.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bsBY-a8Wl6hZd2QV:-M_5Fqph49WbBT8PDBWZ:bwxvdju) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L638)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I remember I removed this special treatment of EACCES and it failed some test, I can't find it now...

Anyway, one case (which I just replicated) is when you have a symlink on a host system pointing somewhere inaccessible. We do not expose these symlinks to Graphene as symlinks, but pretend they are the target file (long story, but mounting the binaries in `Runtime/...` depends on it).

So if you try to list a directory containing such symlinks, we will call `lookup_dentry` for all of them, which translates to `stat` on the underlying filesystem, which fails with EACCES. Without this line, that causes listing the directory to fail.
</blockquote></details>

Alright, then please add a quick note (just one sentence with this example).

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/shim_namei.c, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_1bsBY-a8Wl6hZd2QV:-M_5Jy4eA4LwqCJGE-TO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c071efde27839e33d22193e18b8bfefa86d12a4e/LibOS/shim/src/fs/shim_namei.c#L638)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Alright, then please add a quick note (just one sentence with this example).
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 329 at r3](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_5da8IB2b1Cbjk5Cse:-M_5da8JDUDIf5vGFx2g:b1n2m68) ([raw file](https://github.com/oscarlab/graphene/blob/dcfec5bd7328e868f1ac19e9019a258af089130e/LibOS/shim/include/shim_fs.h#L329)):*
> ```objc
>  * \param[out] found pointer to retrieved dentry
>  *
>  * The caller should hold `g_dcache_lock`. If you do not already need to hold `g_dcache_lock`, use
> ```

`need to hold`? Probably you meant `If you do not yet hold ...`

**Review by pwmarcz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 329 at r3](https://reviewable.io/reviews/oscarlab/graphene/2354#-M_5da8IB2b1Cbjk5Cse:-M_5iAIqBs5y2anIoI3i:b-xka76g) ([raw file](https://github.com/oscarlab/graphene/blob/dcfec5bd7328e868f1ac19e9019a258af089130e/LibOS/shim/include/shim_fs.h#L329)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`need to hold`? Probably you meant `If you do not yet hold ...`
</blockquote></details>

I meant that, as in, "If you don't need this lock for other reasons, use `path_lookupat` instead of taking lock manually". But yes, without "need to" this is simpler and gets the point across. Fixed.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-18.04 please (`apps.LTP.kill11` timed out, known issue)

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2354)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Pull request merged**
