### PR TITLE
[CI] Enable parallelism when building tests

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

#1695 was merged, we should be able now to enable parallel builds for all tests (at least I hope...). This makes the biggest difference for LTP and signing manifests for SGX.

Closes #1687.

## How to test this PR? 

CI + verify logs on Jenkins if everything looks fine.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1703)

### CODE REVIEW

**Comment by mkow** [comment]
FYI: this PR is not ready for review yet. I was too fast to click "Publish" and forgot to switch to "Draft" mode, seems I can't change it now.

**Comment by mkow** [comment]
Jenkins, retest this please (Jenkins was restarted after an update and the jobs got killed)

**Comment by mkow** [comment]
Jenkins, retest this please (let's try again...)

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (kill01 from LTP timed out)

**Comment by mkow** [comment]
Ok, Jenkins passed, should be ready for review now.

**Comment by dimakuv** [comment]
I am not good with Makefiles, but everything looks legit.

**Comment by dimakuv** [comment]
Jenkins, retest this please (previous run was successful, just want to test a bit more before merge)

**Comment by mkow** [comment]
Jenkins, retest this please (let's do one more run to be sure)

**Pull request merged**
