### PR TITLE
[python] Remove support for running from repo

### PR DESCRIPTION
**Pull request by woju**
Recently one of the developers cut himself on this sharp edge.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pwmarcz)

**Review by pwmarcz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: 14 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2400#-Mai-cEh2W_YaYzKr_UV:-Mai-cEh2W_YaYzKr_UW:bpeennj) (no related file):*
The "sharp edge" for me was trying to run regression tests, and invoking `graphene-manifest` from the repo (because I had `graphene/python` in PATH in ` .bashrc`). 

I'm trying to reproduce it now. When I run `make all` in `LibOS/shim/test/regression`, it generates manifests with:

```loader.preload = "file:@PKGLIBDIR@/libsysdb.so"```

I would expect to see an error message instead. if I saw something like this, I would still have no idea what I did wrong.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: 14 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2400#-Mai-cEh2W_YaYzKr_UV:-Mai8kKUDjON7NP55bTG:bmxypfg) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The "sharp edge" for me was trying to run regression tests, and invoking `graphene-manifest` from the repo (because I had `graphene/python` in PATH in ` .bashrc`). 

I'm trying to reproduce it now. When I run `make all` in `LibOS/shim/test/regression`, it generates manifests with:

```loader.preload = "file:@PKGLIBDIR@/libsysdb.so"```

I would expect to see an error message instead. if I saw something like this, I would still have no idea what I did wrong.
</blockquote></details>

Try now, you shouldn't be able to `import graphenelibos` and `graphene-manifest` should break in `ImportError`

---

**Comment by woju** [comment]
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2400#-Mai-cEh2W_YaYzKr_UV:-Mai9B5dCwcnwCzCeq2X:b-slg6md) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Try now, you shouldn't be able to `import graphenelibos` and `graphene-manifest` should break in `ImportError`
</blockquote></details>

Oops, not yet, push failed for pylint.

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: 14 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2400#-Mai-cEh2W_YaYzKr_UV:-MaiAeq817VzYFhiMI92:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oops, not yet, push failed for pylint.
</blockquote></details>

Done.

---

**Review by pwmarcz — DISMISSED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2400)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
