### PR TITLE
[LibOS] Fix a memory leak in __map_elf_object() about variable pointer l

### PR DESCRIPTION
**Pull request by bigdata-memory**
pointer l was assigned by new_elf_object, which utilizes malloc to allocate memory buffer.
in the branch of call_lose, before returning NULL, allocated memory buffer l should be released to prevent resource leakage

Signed-off-by: Gary <gang1.wang@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/352)

### CODE REVIEW

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/elf/shim_rtld.c, line 386 at r1](https://reviewable.io/reviews/oscarlab/graphene/352#-LT4d5I43BVXud3ujYPz:-LTOW9Cr4GPFm03kPtqE:b-umstsj) ([raw file](https://github.com/oscarlab/graphene/blob/9f04c97cac83affc3c5d2355beeec83ef4ddc40a/LibOS/shim/src/elf/shim_rtld.c#L386)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Should we only free this if remap is false?
</blockquote></details>

Yes, you are right that it should be freed only in case of remap is false, Let me correct this, Thanks.

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/elf/shim_rtld.c, line 386 at r2](https://reviewable.io/reviews/oscarlab/graphene/352#-LTV1hY66sFSl3KCB7Rk:-LThpT4z8tbi77MtOZbA:bj3eoea) ([raw file](https://github.com/oscarlab/graphene/blob/97bfe7371ea405b8ef21591775b19462cc457f7a/LibOS/shim/src/elf/shim_rtld.c#L386)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for this `if`, `free()` is guaranteed to be a no-op for `NULL`.
</blockquote></details>

Fixed, thanks.

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/elf/shim_rtld.c, line 386 at r1](https://reviewable.io/reviews/oscarlab/graphene/352#-LT4d5I43BVXud3ujYPz:-LThpW0YEJUW7pGBYk_z:bj3eoea) ([raw file](https://github.com/oscarlab/graphene/blob/9f04c97cac83affc3c5d2355beeec83ef4ddc40a/LibOS/shim/src/elf/shim_rtld.c#L386)):*
<details><summary><i>Previously, bigdata-memory (Wang, Gang) wrote…</i></summary><blockquote>

Yes, you are right that it should be freed only in case of remap is false, Let me correct this, Thanks.
</blockquote></details>

Fixed, thanks.

**Comment by bigdata-memory** [comment]
___
*[LibOS/shim/src/elf/shim_rtld.c, line 369 at r2](https://reviewable.io/reviews/oscarlab/graphene/352#-LTV0t4TCjbzXSztDdmh:-LThppuT3vk58MDL9UjB:biuohqo) ([raw file](https://github.com/oscarlab/graphene/blob/97bfe7371ea405b8ef21591775b19462cc457f7a/LibOS/shim/src/elf/shim_rtld.c#L369)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the rationale behind this change? This seem to change a lot when `remap != NULL`. Also, it's not described in the commit message.
</blockquote></details>

Added a NULL to this true branch to explicitly initialize the variable l and looks not changed the logic of this expression, thanks.

**Comment by bigdata-memory** [comment]
@mkow @donporter  all change requests have been responded, please review, thanks.

**Comment by mkow** [comment]
Test this please

**Comment by mkow** [comment]
Retest Jenkins-Debug please

**Pull request merged**
