### PR TITLE
Fix a bug in shrink vma

### PR DESCRIPTION
**Pull request by hanjae**
Untainted VMAs with `PROT_NONE` become marked as unmapped in `__shrink_vmas()`, and possibly reused by another `mmap` request.
Developers will track pages they mapped, so we shouldn't reclaim it in os even though they are in `PROT_NONE`.
This commit fixes the issue #13.

### CODE REVIEW

**Comment by donporter** [comment]
Hi @hanjae can you write a unit test (under LibOS/shim/test/regression) that captures this case?  It should fail on current master, but pass with your fix.

Also, would you mind running the full set of tests with a set of checkboxes (similar to the comment in PR #94 )?  Just to make sure we don't break anything .  A few cases don't work currently, and you can email me directly if you have questions about how to run any of them.  

I would also like the Travis test to pass, although I'm not sure I understand the first failure; I restarted it in case of flakiness.

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Test this please.

**Comment by donporter** [comment]
This PR does seem to have some regressions around fork; please keep working on this and nudge me once it passes the CI tests.

**Comment by hanjae** [comment]
Test this please

**Comment by donporter** [comment]
@hanjae can you merge master onto your branch?  The jenkins job definition for SGX is out of date.

**Comment by hanjae** [comment]
@donporter I already merged master. Jenkins seems not working correctly for SGX right now.

**Comment by hanjae** [comment]
Test this please

**Comment by donporter** [comment]
So it is - should be running now, but will take a minute to catch up.

**Comment by donporter** [comment]
Test this please.

**Comment by hanjae** [comment]
Test this please

**Comment by chiache** [comment]
The issue is resolved by #183.

**Pull request closed without merging**
