### PR TITLE
Move architecture specific files to designated directories

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
All architecture specific files can now be found in arch/arch_name directories e.g. `arch/x86_64`.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: 0 of 22 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVKIe1i1t0LWMv75WlU:-MVKIe1j-mWe7NXRpp2M:b-cs6d5g) (no related file):*
@stefanberger you might be interested in this change

---
___
*[LibOS/shim/src/Makefile, line 193 at r1](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVKK37I-_NxLSO-4DJ8:-MVKK37I-_NxLSO-4DJ9:b1n056k) ([raw file](https://github.com/oscarlab/graphene/blob/f4d745cbf1d3d41a8883f916bab85234c6681b3c/LibOS/shim/src/Makefile#L193)):*
> ```Makefile
> 	$(call cmd,cpp_s_S)
> 
> arch/$(ARCH)/asm-offsets.h: asm-offsets.h
> ```

Ugly, but no idea how to make it better (without rewriting our makefiles).
___
*[Pal/src/host/Linux/Makefile.am, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVKJsL9Cxb4Cw0DFDoG:-MVKJsL9Cxb4Cw0DFDoH:b-26twu8) ([raw file](https://github.com/oscarlab/graphene/blob/9d46988bf19b63f42739b84d1f08a477a599e487/Pal/src/host/Linux/Makefile.am#L2)):*
> ```Makefile
> # Add host-specific compilation rules here
> SEC_DIR = security/$(PAL_HOST)
> ```

Unrelated change (just removed some random old thing).

**Review by mkow — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVM2qF_8-WtE0lG3HS5:-MVM2qF_8-WtE0lG3HS6:b-6813r3) (no related file):*
What about vDSO path: https://github.com/oscarlab/graphene/tree/borys/create_arch_specific_dirs/LibOS/shim/src/vdso/arch/x86_64? Should we move it under your newly created https://github.com/oscarlab/graphene/tree/borys/create_arch_specific_dirs/LibOS/shim/src/arch/x86_64?

---
___
*[LibOS/shim/src/Makefile, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVM1YDv8MQvlfe-QBYp:-MVM1YDw2pP5Zh2CpNON:b-oncirz) ([raw file](https://github.com/oscarlab/graphene/blob/82aaf6d03d8394a0c650fe01c4f95921c390e754/LibOS/shim/src/Makefile#L194)):*
> ```Makefile
> 
> arch/$(ARCH)/asm-offsets.h: asm-offsets.h
> 	ln -fs ../../$^ arch/$(ARCH)/asm-offsets.h
> ```

Why not `$@`?

**Review by stefanberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVKIe1i1t0LWMv75WlU:-MVM9Hfm2DCefhb7j__t:b-f4jpg8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger you might be interested in this change
</blockquote></details>

Thanks. looks good to me.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: 22 of 23 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVM2qF_8-WtE0lG3HS5:-MVMMlWK4Qhe8duqgRSO:bcvjca2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about vDSO path: https://github.com/oscarlab/graphene/tree/borys/create_arch_specific_dirs/LibOS/shim/src/vdso/arch/x86_64? Should we move it under your newly created https://github.com/oscarlab/graphene/tree/borys/create_arch_specific_dirs/LibOS/shim/src/arch/x86_64?
</blockquote></details>

I think it's fine now: VDSO is a distinct object from LibOS (imo it should be moved out of LibOS directory). Also it seems to have a common files (.S tho, no idea how it works).

---
___
*[LibOS/shim/src/Makefile, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/2220#-MVM1YDv8MQvlfe-QBYp:-MVMN1R5AebW_O6v67Za:b-4z3p86) ([raw file](https://github.com/oscarlab/graphene/blob/82aaf6d03d8394a0c650fe01c4f95921c390e754/LibOS/shim/src/Makefile#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `$@`?
</blockquote></details>

I wanted to make sure that if somebody moves it, they also notice they need to change amount of `../` in this line (currently they would need to both change target in makefile rule and target in symlink, which hopefully makes them notice they also need to change `../`).

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2220)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
