### PR TITLE
[Pal/Linux-SGX] Do not call redundant ocall_mmap_untrusted() on file_map()

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, Linux-SGX PAL turned out to call `ocall_mmap_untrusted()` twice: first during `file_open()` and then during `file_map()`. This hurts performance and not needed, so this PR removes one mmap.

Co-authored-by: Isaku Yamahata <isaku.yamahata@gmail.com>

Closes #1324 (this PR corresponds to the last commit of that series; the first commit there is already fixed on master, the second and third commits are unneeded optimizations).

## How to test this PR? 

All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)

### CODE REVIEW

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQ9b4XyEJkNrAH1DIRs:b-xarf5x) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
> ```C
>         uint64_t total_size     = aligned_end - aligned_offset;
> 
>         uint64_t total_bytes = 0;
> ```

Memory sizes should be in `size_t` and we need to somehow handle `total_size > SIZE_T_MAX` (e.g. for 32-bit compatibility).
Failing early and otherwise using `size_t` is IMO fine, we just need to ensure that we explicitly fail for too big files.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9byCsBNFkMnbzvdjp:-MQ9byCt710SSX-O0AzQ:bide90u) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
> ```C
>         uint64_t total_size     = aligned_end - aligned_offset;
> 
>         uint64_t total_bytes = 0;
> ```

`total_bytes` -> `bytes_read` (`total_bytes` and `total_size` sound synonymously)
___
*[Pal/src/host/Linux-SGX/db_files.c, line 468 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9bmyvB_Ik05Oe3zeJ:-MQ9bmyvB_Ik05Oe3zeK:b-spmto7) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L468)):*
> ```C
>         while (total_bytes < total_size) {
>             uint64_t read_size = total_size - total_bytes < MAX_READ_SIZE ?
>                                  total_size - total_bytes : MAX_READ_SIZE;
> ```

Why is this weird limit needed?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 484 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9dJcUChdzOXEbLlv6:-MQ9dJcUChdzOXEbLlv7:b5s9z3c) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L484)):*
> ```C
> 
>         if (total_size - total_bytes > 0) {
>             /* file ended before all requested memory was filled -- remaining memory is zeroed */
> ```

`is zeroed` -> `has to be zeroed`
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9WXyb8om_u4GUJjrd:-MQ9WXyb8om_u4GUJjre:b42879c) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/pal_linux_defs.h#L24)):*
> ```objc
> 
> #define TRUSTED_STUB_SIZE (PRESET_PAGESIZE * 4UL)
> #define MAX_READ_SIZE     (PRESET_PAGESIZE * 32768UL)
> ```

Where does this value come from? Also, why not in hex?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9byCsBNFkMnbzvdjp:-MQBkbRF6aEGTCGzS6e8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`total_bytes` -> `bytes_read` (`total_bytes` and `total_size` sound synonymously)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQBkck29z875OhhLj1g:biprevd) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Memory sizes should be in `size_t` and we need to somehow handle `total_size > SIZE_T_MAX` (e.g. for 32-bit compatibility).
Failing early and otherwise using `size_t` is IMO fine, we just need to ensure that we explicitly fail for too big files.
</blockquote></details>

OK. I changed here to `size_t` and `off_t`, but I don't understand the comment regarding `SIZE_T_MAX` (did you mean `SIZE_MAX`? what's the point of checking if it will always be true?).

Also note that all this file logic uses `uint64_t` and I didn't want to touch other places that do this in this PR...
___
*[Pal/src/host/Linux-SGX/db_files.c, line 468 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9bmyvB_Ik05Oe3zeJ:-MQBkM0SEqh28jp6uOpj:b-7qyuqo) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L468)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this weird limit needed?
</blockquote></details>

See explanation in other file.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 484 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9dJcUChdzOXEbLlv6:-MQBkQHg8KsJkSUGCJ-Y:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L484)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`is zeroed` -> `has to be zeroed`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9WXyb8om_u4GUJjrd:-MQBjSwX9fbgQujBEBY2:b-i4ouq9) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/pal_linux_defs.h#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where does this value come from? Also, why not in hex?
</blockquote></details>

Done. The value was chosen rather arbitrarily.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQCP4sgEbJxVaAMpIfl:bd3kk8m) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. I changed here to `size_t` and `off_t`, but I don't understand the comment regarding `SIZE_T_MAX` (did you mean `SIZE_MAX`? what's the point of checking if it will always be true?).

Also note that all this file logic uses `uint64_t` and I didn't want to touch other places that do this in this PR...
</blockquote></details>

What I mean is that the file size may not fit into `size_t` (that's why we have a separate type for it, `off_t` or `uint64_t`) and yup, I mean `SIZE_MAX` (that `SIZE_T_MAX` was more like a pseudocode, I didn't remember the correct constant name :) ).
So, you should check if aligned-up file size exceeds this value and if so, we are unable to map it to memory.
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9WXyb8om_u4GUJjrd:-MQCQqyM24e7NC5R0_ed:b-ry9pxa) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/pal_linux_defs.h#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. The value was chosen rather arbitrarily.
</blockquote></details>

Can we move this constant to the implementation then? It seems to be an implementation detail of one function, so it would be good to have it (plus the explanation comment) close to the code.
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQCRHmQ1lUdYKoDkfWR:-MQCRHmQ1lUdYKoDkfWS:b29xzsr) ([raw file](https://github.com/oscarlab/graphene/blob/2fc9636a8f41aa6df75d02e556d3ca1bb3bd3fe9/Pal/src/host/Linux-SGX/pal_linux_defs.h#L26)):*
> ```objc
> 
> /* this macro is used to emulate mmap() via read() in chunks of 128MB (mmapped files may be many
>  * GBs in size, and a single read could fail with -ENOMEM, so we cap to reasonably small size) */
> ```

technical nitpicking: read can't fail with -ENOMEM, I guess it would be rather success (but slow due to swapping) or OOM killer triggered?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQDqcqZ1VzQmcT9pgA9:buzqcjm) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I mean is that the file size may not fit into `size_t` (that's why we have a separate type for it, `off_t` or `uint64_t`) and yup, I mean `SIZE_MAX` (that `SIZE_T_MAX` was more like a pseudocode, I didn't remember the correct constant name :) ).
So, you should check if aligned-up file size exceeds this value and if so, we are unable to map it to memory.
</blockquote></details>

Still don't understand. Any variable of type `size_t` is always less than `SIZE_MAX` (by definition). What am I missing?
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9WXyb8om_u4GUJjrd:-MQDrIjy9P9WHAyRZwIK:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/pal_linux_defs.h#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we move this constant to the implementation then? It seems to be an implementation detail of one function, so it would be good to have it (plus the explanation comment) close to the code.
</blockquote></details>

Done
___
*[Pal/src/host/Linux-SGX/pal_linux_defs.h, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQCRHmQ1lUdYKoDkfWR:-MQDrK6T9j52QXzOAPgo:b5s5mdb) ([raw file](https://github.com/oscarlab/graphene/blob/2fc9636a8f41aa6df75d02e556d3ca1bb3bd3fe9/Pal/src/host/Linux-SGX/pal_linux_defs.h#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

technical nitpicking: read can't fail with -ENOMEM, I guess it would be rather success (but slow due to swapping) or OOM killer triggered?
</blockquote></details>

I meant a `pread()` OCALL which internally uses `mmap()` because it needs to allocate in untrusted memory. I've observed both the OOM killer and `-ENOMEM`. I rephrased a bit to make it clear it's about OCALLs.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQDtG6n8xJV1zXIz8d1:b-n5dcf7) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still don't understand. Any variable of type `size_t` is always less than `SIZE_MAX` (by definition). What am I missing?
</blockquote></details>

But `total_size`/`total` is a file size, not a memory buffer size, so it should be `off_t`, not `size_t` (on some systems (e.g. 32-bit x86 Linux) you can have files bigger than a memory pointer can address).

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 465 at r1](https://reviewable.io/reviews/oscarlab/graphene/2048#-MQ9b4Xx2kAdU5VhFLK1:-MQGmgdzBlmIWpQSi3um:b-d0snnj) ([raw file](https://github.com/oscarlab/graphene/blob/6dd1825b735c989d057704e3512736a1c03c7689/Pal/src/host/Linux-SGX/db_files.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But `total_size`/`total` is a file size, not a memory buffer size, so it should be `off_t`, not `size_t` (on some systems (e.g. 32-bit x86 Linux) you can have files bigger than a memory pointer can address).
</blockquote></details>

Done. Now I got it, `size_t` is for memory objects, `off_t` is for files, and their limits may be different. Check my new version.

TBH, I want to significantly refactor all this logic around trusted/protected/allowed files. The code is really bad, and types are all mixed. One day...

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2048)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
