### PR TITLE
Porting PAL GIPC module to Linux 4.11~4.15

### PR DESCRIPTION
**Pull request by chiache**
This PR fixes the portability issues on Linux 4.11~4.15, due to 4 major changes:
(1) Adding a new argument `uf` to `do_mmap()`: https://elixir.bootlin.com/linux/v4.11/source/include/linux/mm.h#L2110
(2) Changing 4-level page table to 5-level: https://elixir.bootlin.com/linux/v4.11/source/include/asm-generic/5level-fixup.h#L12
(3) Renaming `SLAB_DESTROY_BY_RCU` to `SLAB_TYPESAFE_BY_RCU` (Linux 4.12+)
(4) `signal_pending()` moved to `linux/sched/signal.h`.

### CODE REVIEW

**Comment by donporter** [comment]
Test this please

**Comment by chiache** [comment]
I am not sure why, but GIPC still significantly improves the performance on the kernel I am testing (Linux 4.13.0).

Without GIPC:
```
Process fork+exit median=3934.5000 [mean=3928.0000 +/-48.3615] microseconds
var: 4711.611111 sd: 68.641176 runs: 10
```
With GIPC:
```
Process fork+exit median=437.0826 [mean=435.0810 +/-4.1415] microseconds
var: 34.553086 sd: 5.878187 runs: 10
```

I am still trying to figure out if this is specific to kernel version or Graphene version.

**Comment by donporter** [comment]
Fair enough.

**Comment by donporter** [comment]
The CI failure for SGX is a little interesting (normal is recv01 again).  I don't think this is your fault, but might be an interesting bug to peek at if you have a second.

Compile bzip2.c:
./gcc.manifest test_files/bzip2.c -o test_files/bzip2
WARNING: no physical memory support, process creation will be slow.
WARNING: no physical memory support, process creation will be slow.
WARNING: no physical memory support, process creation will be slow.
assert failed ipc/shim_ipc_nsimpl.h:1026 !qstrempty(&leader->uri) (value:0)
Cancelling nested steps due to timeout
Sending interrupt signal to process

**Pull request merged**
