### PR TITLE
[LibOS] Remove create_{dir,file,handle}() and refactor create_pipe()

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Just a bit of refactoring. This code annoyed me too much.

## How to test this PR? 

All tests must work.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-apps please (landed on dying Jenkins worker)

**Review by yamahata — COMMENTED** [review]
Great simplification.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929#-:-MKpPVum2GXSMJ0_0TFu:bpe5o3v)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_init.c, line 574 at r1](https://reviewable.io/reviews/oscarlab/graphene/1929#-MKpWayX4_OKKxtaDBqj:-MKpWayX4_OKKxtaDBqk:b-ki1l1q) ([raw file](https://github.com/oscarlab/graphene/blob/6c0ea8a962b4a4c4d832b9b6ed45e2271f44dd5c/LibOS/shim/src/shim_init.c#L574)):*
> ```C
>     assert(size);
> 
> retry:
> ```

Why not a loop?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/shim_init.c, line 574 at r1](https://reviewable.io/reviews/oscarlab/graphene/1929#-MKpWayX4_OKKxtaDBqj:-MKsznAW0MM8AzrD2hEO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6c0ea8a962b4a4c4d832b9b6ed45e2271f44dd5c/LibOS/shim/src/shim_init.c#L574)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not a loop?
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1929)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
