### PR TITLE
[Pal/Linux-SGX] Rename "checksum" to "hash" and "stub" to "chunk"

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, the code interchangeably used "checksum" and "hash" when referring to SHA-256 hashes, as well as "stub" and "chunk" when referring to file chunks (16KB blocks of a file). This PR unifies the naming to more correct "hash" and "chunk" everywhere. Note that the `sgx.trusted_checksum` manifest syntax is kept for now because we don't want to break old manifests.

This is one more little step to refactoring Linux-SGX files handling.

## How to test this PR? 

N/A.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2345)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2345)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-18.04 please (`killall` LibOS test failed with `child 2 killed by a wrong signal (30)`)

**Review by yamahata — DISMISSED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2345)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2345)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2345)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
