### PR TITLE
[Pal] Make Graphene UNIX socket paths unique

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Check each commit message for details.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_pipes.c, line 224 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9FsQ-1EaccpkJuP3Y:-Me9FsQ-1EaccpkJuP3Z:b705moo) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux/db_pipes.c#L224)):*
> ```C
>  *
>  * - `type` is URI_TYPE_PIPE_SRV: create `pipesrv` handle (intermediate listening socket) with
>  *                                name in the form of "/graphene/<instance_id>/<uri>". Caller is
> ```

You sure you want to drop `@` from here? It denotes the abstract socket, and you don't explicitly mention it here. So may be confusing for future readers.
___
*[Pal/src/host/Linux/db_pipes.c, line 228 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Fzed1t3MlaRntMFR:-Me9Fzed1t3MlaRntMFS:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux/db_pipes.c#L228)):*
> ```C
>  *
>  * - `type` is URI_TYPE_PIPE: create `pipe` handle (connecting socket) with name in the form of
>  *                            "/graphene/<instance_id>/<uri>".
> ```

ditto
___
*[Pal/src/host/Linux-common/graphene_unix_socket_addr.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9FIpyBVH0DbV85dHc:-Me9FIpyBVH0DbV85dHd:b-4dvnp2) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-common/graphene_unix_socket_addr.c#L16)):*
> ```C
> 
>     /* We use abstract UNIX sockets, which start with a nullbyte and actually look at the whole path
>      * (even after the nullbyte). */
> ```

I don't understand this `even after the nullbyte`. Why do you need this additional explanation? The Linux logic is basically "if first byte is nullbyte, then jump over it and start parsing the path after it". Is this what you're trying to convey in this comment?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Gbrf146kq9G0VDZM:-Me9Gbrf146kq9G0VDZN:bo506ia) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_main.c#L665)):*
> ```C
>     PAL_HANDLE parent = NULL;
>     uint64_t instance_id = 0;
>     if (g_pal_sec.stream_fd != PAL_IDX_POISON) {
> ```

`stream_fd` is a very non-obvious way to identify parent vs child. Can we rename this field to e.g. `parent_stream_fd` or at least add a comment on this field?
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 291 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9GvCi0fJ0QmUsK9nG:-Me9GvCi0fJ0QmUsK9nH:b5eliuu) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_pipes.c#L291)):*
> ```C
>  *
>  * - `type` is URI_TYPE_PIPE_SRV: create `pipesrv` handle (intermediate listening socket) with
>  *                                name in the form of "/graphene/<instance_id>/<uri>". Caller is
> ```

ditto (dropped `@`)
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 295 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9GxMf9qIuQ7Lk7P1p:-Me9GxMg1ttZC9OuSz3w:b5eliuu) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_pipes.c#L295)):*
> ```C
>  *
>  * - `type` is URI_TYPE_PIPE: create `pipe` handle (connecting socket) with name in the form of
>  *                            "/graphene/<instance_id>/<uri>".
> ```

ditto (dropped `@`)
___
*[Pal/src/host/Linux-SGX/db_process.c, line 205 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9HSdwDR3VHPSNPBfo:-Me9HSdwDR3VHPSNPBfp:b-t9di2p) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_process.c#L205)):*
> ```C
> failed:
>     free(child);
>     return ret < 0 ? ret : -PAL_ERROR_DENIED;
> ```

Oops, what a blunder :(

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 22 of 23 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_pipes.c, line 224 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9FsQ-1EaccpkJuP3Y:-MeBEHDq6qhgTxzksx3a:b-y6i8uu) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux/db_pipes.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You sure you want to drop `@` from here? It denotes the abstract socket, and you don't explicitly mention it here. So may be confusing for future readers.
</blockquote></details>

`@` is supposed to be a nullbyte and I dislike this convention (since you cannot distinguish it from a normal `@`). If we want to document that this is an abstract UNIX socket, I would just add it to the text.
TBH I'm considering dropping this name from here as I see no reason for it to be documented in a public interface.
Which one would you prefer (I'm in favor of just dropping and maybe redirecting to the specific function for details)?
___
*[Pal/src/host/Linux-common/graphene_unix_socket_addr.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9FIpyBVH0DbV85dHc:-MeBBtkC4U6KHnTbujiW:bs193a9) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-common/graphene_unix_socket_addr.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this `even after the nullbyte`. Why do you need this additional explanation? The Linux logic is basically "if first byte is nullbyte, then jump over it and start parsing the path after it". Is this what you're trying to convey in this comment?
</blockquote></details>

No. What I wanted to say is that if you have: `"\x00xxx/yyy\x00zzz\x00random_data_filling_the_rest_of_the_buffer"` the actual UNIX socket name is not `"xxx/yyy"` (as one could expect), but `"xxx/yyy\x00zzz\x00random_data_filling_the_rest_of_the_buffer"`.
I see the comment was super confusing, expanded it a bit.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Gbrf146kq9G0VDZM:-MeBEsW99vw21BoBxwtw:btresic) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_main.c#L665)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`stream_fd` is a very non-obvious way to identify parent vs child. Can we rename this field to e.g. `parent_stream_fd` or at least add a comment on this field?
</blockquote></details>

I've found no other way and keeping `ppid` just for this one line seemed superfluous. I would rather not change the name, since it's used in many other places (including function arguments and local variables). I can add a comment, but here or in header with this field definition?
___
*[Pal/src/host/Linux-SGX/db_process.c, line 205 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9HSdwDR3VHPSNPBfo:-MeBFUUT3jHoLrsauY_-:bbx8u4) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_process.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, what a blunder :(
</blockquote></details>

Yes, this was probably a security issue.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeL40hcArpxG9lxzhTf:-MeL40hd5NjECvYB06dT:bw9wng) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/include/host/Linux-common/linux_utils.h#L27)):*
> ```
> id
> ```

ID of what? Could you say that in the parameter name?
___
*[Pal/src/db_main.c, line 278 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeL5tUEC-EnBD_k8Rwh:-MeL4LFSDy3Xqk7ZEsAA:bw0zjws) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/db_main.c#L278)):*
> ```C
>     if (!instance_id) {
>         assert(!parent_process);
>         if (_DkRandomBitsRead(&instance_id, sizeof(instance_id)) < 0) {
> ```

Hmm, what happens if an attacker guessed this ID? It seems infeasible, but not by a big margin, so I'd like to know how dangerous it is. Or maybe this is irrelevant to security and just to not need to globally synchronize all Graphene instances? (I think it's the latter because host already knows it, but want to ensure)
___
*[Pal/src/host/Linux-common/graphene_unix_socket_addr.c, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLGEtU4jFLxmYXF5ml:-MeLGEtVCrg1i-Uztunv:b-okzzrz) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-common/graphene_unix_socket_addr.c#L11)):*
> ```C
> #include "linux_utils.h"
> 
> int get_graphene_unix_socket_addr(uint64_t id, const char* name, struct sockaddr_un* addr) {
> ```

`addr` -> `out_addr`
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 283 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLINBBEREYC1a7ksNq:-MeLIKlJDnfrTctuZX6X:b-lu7wbu) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-SGX/sgx_enclave.c#L283)):*
> ```C
>     ret = sgx_create_process(ms->ms_nargs, ms->ms_args, &ms->ms_stream_fd,
>                              g_pal_enclave.raw_manifest_data);
>     return ret < 0 ? ret : 0;
> ```

Can we change the return semantic of `sgx_create_process()` to just return -error|0 as the rest of our codebase does? The returned pid isn't used anywhere. We would need this `if` then.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 18 of 23 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeM18mY3-hY_OiGIUBh:-MeM18mY3-hY_OiGIUBi:b-r3lv5s) (no related file):*
TODO: debug Jenkins-SGX-18.04 failure, could not reproduce locally.

---
___
*[Pal/include/host/Linux-common/linux_utils.h, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeL40hcArpxG9lxzhTf:-MeLtlEl33yvSygENpXs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/include/host/Linux-common/linux_utils.h#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> id
> ```

ID of what? Could you say that in the parameter name?
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 278 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeL5tUEC-EnBD_k8Rwh:-MeLtmgEAhCWtY5zhTc5:b-ktg6o6) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/db_main.c#L278)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, what happens if an attacker guessed this ID? It seems infeasible, but not by a big margin, so I'd like to know how dangerous it is. Or maybe this is irrelevant to security and just to not need to globally synchronize all Graphene instances? (I think it's the latter because host already knows it, but want to ensure)
</blockquote></details>

The malicious host knows the ID of each instance. In theory we probably could use host provided ID, but this way it's easier:
- no need to sanitize/check it,
- each process knows for 100% which instance it's part of, since it's sent securely (tho there is no real need for it, at least for now),
- we don't have to have some special way for synchronizations (as you noted) it would probably be complicated - this is just super easy get random.
___
*[Pal/src/host/Linux/db_pipes.c, line 224 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9FsQ-1EaccpkJuP3Y:-MeM-u7z-pX7eBwIw_f5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux/db_pipes.c#L224)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`@` is supposed to be a nullbyte and I dislike this convention (since you cannot distinguish it from a normal `@`). If we want to document that this is an abstract UNIX socket, I would just add it to the text.
TBH I'm considering dropping this name from here as I see no reason for it to be documented in a public interface.
Which one would you prefer (I'm in favor of just dropping and maybe redirecting to the specific function for details)?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_pipes.c, line 228 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Fzed1t3MlaRntMFR:-MeM-uW16u9sxtVefrM-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux/db_pipes.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/graphene_unix_socket_addr.c, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLGEtU4jFLxmYXF5ml:-MeLv9WhDA1jPdwX8YMo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-common/graphene_unix_socket_addr.c#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`addr` -> `out_addr`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 291 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9GvCi0fJ0QmUsK9nG:-MeM0JtG1uZeO850KHzx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_pipes.c#L291)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (dropped `@`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 295 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9GxMf9qIuQ7Lk7P1p:-MeM0JhL0GjGOCgqWDWx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_pipes.c#L295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (dropped `@`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 283 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLINBBEREYC1a7ksNq:-MeLxkD51z8J_S0BEKn0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-SGX/sgx_enclave.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we change the return semantic of `sgx_create_process()` to just return -error|0 as the rest of our codebase does? The returned pid isn't used anywhere. We would need this `if` then.
</blockquote></details>

Done.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 18 of 23 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 86 at r3](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeMMvG90rWo1yHnwvEY:-MeMMvG90rWo1yHnwvEZ:b2nh8oq) ([raw file](https://github.com/oscarlab/graphene/blob/da8c020c9ce4da1b96ad723f7014762663893088/Pal/src/host/Linux-SGX/sgx_process.c#L86)):*
> ```C
>     ret = block_async_signals(true);
>     if (ret < 0) {
>         ret = -ret;
> ```

???

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (previous was all good)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 283 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLINBBEREYC1a7ksNq:-MeMO3o_780eMjzbPwPY:babib6h) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-SGX/sgx_enclave.c#L283)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about the second part?
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 86 at r3](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeMMvG90rWo1yHnwvEY:-MeMO9ti0GufigI8vB6k:b2ni78k) ([raw file](https://github.com/oscarlab/graphene/blob/da8c020c9ce4da1b96ad723f7014762663893088/Pal/src/host/Linux-SGX/sgx_process.c#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

???
</blockquote></details>

lol

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 22 of 23 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 283 at r2](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeLINBBEREYC1a7ksNq:-MeMfGcLB9hCtm5niGed:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/dc75b0fc8bf04068d6d43affa829ef4999462150/Pal/src/host/Linux-SGX/sgx_enclave.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about the second part?
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 276 at r4](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeMgizTBG_cxYF4xNZZ:-MeMgizU453UzeaT39yX:beb1e4n) ([raw file](https://github.com/oscarlab/graphene/blob/81503076bbf8b0a395ec44804ab10ac9b4f32a15/Pal/src/host/Linux-SGX/sgx_enclave.c#L276)):*
> ```C
> 
> static long sgx_ocall_create_process(void* pms) {
>     long ret;
> ```

unused now, I guess that's why Jenkins failed

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 22 of 23 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 276 at r4](https://reviewable.io/reviews/oscarlab/graphene/2525#-MeMgizTBG_cxYF4xNZZ:-MeMhM3-6Sb6axu_NELp:b2nih0v) ([raw file](https://github.com/oscarlab/graphene/blob/81503076bbf8b0a395ec44804ab10ac9b4f32a15/Pal/src/host/Linux-SGX/sgx_enclave.c#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

unused now, I guess that's why Jenkins failed
</blockquote></details>

yup

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Gbrf146kq9G0VDZM:-MeOOouj5NdgvdoPKS60:bdhqrq6) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_main.c#L665)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've found no other way and keeping `ppid` just for this one line seemed superfluous. I would rather not change the name, since it's used in many other places (including function arguments and local variables). I can add a comment, but here or in header with this field definition?
</blockquote></details>

In the header, please.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: 22 of 23 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2525#-Me9Gbrf146kq9G0VDZM:-MePwXF800FXlqwFeLNy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fab3be4ae2961e0cdd75b3a8eb498dc5ee496db7/Pal/src/host/Linux-SGX/db_main.c#L665)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the header, please.
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2525)* status: all files reviewed, 1 unresolved discussion

**Comment by boryspoplawski** [comment]
The Jenkins failure seen in this PR was #2532 and was unrelated to this PR.

**Pull request merged**
