### PR TITLE
[python] Compile protobuf from source

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

Remove generated aesm_pb2.py, regenerate it on each compilation.

## How to test this PR? 
As usual, compile and run tests.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2043)

### CODE REVIEW

**Comment by woju** [comment]
This will currently fail, because this break legacy stub `pal_sgx_get_token.py`. I'll ask for merging this after converting tests to run from installed graphene.

**Review by dimakuv — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2043)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Comment by mkow** [comment]
Closing, will be re-done in the new repo.

**Comment by mkow** [comment]
Also, I created an issue to not forget about this: https://github.com/gramineproject/gramine/issues/155.

**Pull request closed without merging**
