### PR TITLE
Improve testing of GSC

### PR DESCRIPTION
**Pull request by vahldiek**
# Description of the changes 

Changed GSC Jenkins tests to include testing of Linux PAL integration of GSC and the use of trusted arguments.

## How to test this PR? 

Run GSC Jenkins pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1755)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test Jenkins-SGX-gsc please

**Comment by bigdata-memory** [comment]
___
*[Tools/gsc/test/ubuntu18.04-python3-trusted-args.dockerfile, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/1755#-METoAI-5wWZBSvlWCu2:-METoAI-5wWZBSvlWCu3:bvc5w7b) ([raw file](https://github.com/oscarlab/graphene/blob/02354747a4ec8b97e0bfb6fa7a7feb9cfb9a97a8/Tools/gsc/test/ubuntu18.04-python3-trusted-args.dockerfile#L7)):*
> ```Dockerfile
> RUN apt-get install -y python3
> 
> CMD ["python3", "-c", "print('HelloWorld!')"]
> ```

I think it could be better to specify the full path of Python3 in CMD statement.
In addition, some use cases specify the python3 in Entrypoint statement, so one more test case is helpful

**Review by vahldiek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1755)* status: 2 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Jenkinsfiles/Linux-SGX-gsc, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/1755#-MEP_iUt6TVypKO3voYV:-MFpNYEo5pdyL5fSUiw8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/02354747a4ec8b97e0bfb6fa7a7feb9cfb9a97a8/Jenkinsfiles/Linux-SGX-gsc#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[Jenkinsfiles/Linux-SGX-gsc, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/1755#-MEP_nzM0EzWYat4udtZ:-MFpNajc74ds4v7vcEcU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/02354747a4ec8b97e0bfb6fa7a7feb9cfb9a97a8/Jenkinsfiles/Linux-SGX-gsc#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you test Linux PAL first? I suppose it's much faster, so if there's something very wrong with a PR our CI will fail sooner.
</blockquote></details>

Done.
___
*[Jenkinsfiles/Linux-SGX-gsc, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene/1755#-MEPa82t6t9WcxDU-vHb:-MFpNeAL1K9ylob7qXOF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/02354747a4ec8b97e0bfb6fa7a7feb9cfb9a97a8/Jenkinsfiles/Linux-SGX-gsc#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment while we're here
</blockquote></details>

Done.
___
*[Tools/gsc/templates/apploader.template, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/1755#-MEPaf220X7ysD9eZp_W:-MFpYSZw93bgopc8-xap:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/02354747a4ec8b97e0bfb6fa7a7feb9cfb9a97a8/Tools/gsc/templates/apploader.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if `GSC_PAL` is `Linux-SGX`? Seems this `if` silently assumes that `SGX` PAL is the default. Would be much cleaner to explicitly set `GSC_PAL` to `Linux-SGX` if it's empty.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1755)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1755)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
