### PR TITLE
[LibOS] Correctly set/unset PAL handles for IPC objects on exec()

### LINKED ISSUE #1390: [Examples] R is broken
## Description of the problem:

R doesn't run as is (due to `trusted_files.libstdc++` -- plus signs are not allowed in manifests). Even after fixing this issue manually, R segfaults on one of the examples.

Need to update its Makefile and manifest and fix all found bugs.

## Steps to reproduce:

Go to `Examples/r` and try `make SGX=1` and then `SGX=1 ./pal_loader R.manifest --slave --vanilla -f scripts/sample.r`.

### LINKED ISSUE #1724: Memory corruption in IPC subsystem
## Description of the problem

Graphene's IPC subsystem doesn't care too much about ownership of objects, which are freely passed to functions and saved in various structures. This sometimes leads to memory corruptions - one of which is triggered by our R example.

## Steps to reproduce

Check out https://github.com/mkow/graphene/tree/mkow/r-debugging (this branch has additional debugging info printed), then:

```Bash
cd Examples/r
make SGX=1 DEBUG=1
SGX=1 ./pal_loader R.manifest --slave --vanilla -f scripts/sample.r
```

## Expected results

All handles appearing in the log are valid.

## Actual results

```
[33:sh] Adding port (handle 0x83bafd52a:pal_type_pipesrv) for process 947 (type 0002)
[33:sh] Adding port (handle 0x83bad9df0:pal_type_process) for process 941 (type 0011)
...
[33:sh] __free_ipc_info:122 DkObjectClose(0x83bafd52a:pal_type_pipesrv)
[33:sh] __free_ipc_info:122 DkObjectClose(0x83bad9df0:pal_type_process)
...
[P947:sh] Listening to process 941 on port 0x83aaef0a0 (handle 0x83bad9df0:<unknown>, type 0011)
[P947:sh] Listening to process 947 on port 0x83aaef048 (handle 0x83bafd52a:<unknown>, type 0002)
```

0x83bad9df0 and 0x83bafd52a are dangling pointers, as one can see from the log.

## Bug analysis

This particular bug is probably caused by total lack of object ownership notion around `shim_ipc_info` and `shim_ipc_port` structures, specifically, `add_ipc_port_by_id()` seems to take ownership over its `hdl` argument, but this isn't documented anywhere and different callsites behave differently when using it. Most likely this PAL handle ends up also in a different structure, which gets freed while a corresponding `shim_ipc_port` still lives and is used.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, when Graphene migrated process metadata to a new host-OS process on `exec()` syscalls, the logic simply copied IPC information from the parent to the child via new object `shim_process* process`, including PAL handles for "self" and "parent" communication pipes. However, Graphene's LibOS doesn't have a notion of refcounts for corresponding PAL handles, so the copied PAL handles were still freed when freeing the not-used-anymore `process` object.

This PR fixes this by explicitly copying the PAL handles' pointers before migration and clearing them after migration. This PR also contains tiny bug fixes in the R example.

Fixes #1724. Fixes #1390.

## How to test this PR? 

Run R example manually.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 244 at r1](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGePYJz164-0EoJuNMy:-MGePYK-7trdimEWFzQC:b-co8ist) ([raw file](https://github.com/oscarlab/graphene/blob/3ac7b9684abc52b38e0c0376fc08cf3eb61eca1d/LibOS/shim/src/ipc/shim_ipc.c#L244)):*
> ```C
>     return new_process;
> 
> fail:
> ```

FYI: That's just a little refactoring I did.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGeTuAz696We9Sup2C4:-MGeTuB--T8EC3Pr3OY2:bbeq8wd) (no related file):*
Can we add R to CI now? Is it stable?

---

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGeTuAz696We9Sup2C4:-MGezaX74nmdpMSV_1KD:bami121) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we add R to CI now? Is it stable?
</blockquote></details>

Done. It is stable.

---

**Review by yamahata — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGixCw31C8eklsmCKJQ:-MGixCw31C8eklsmCKJR:b2pahby) (no related file):*
It also fixes #1390, could you add this to the description?

---
___
*[Examples/r/Makefile, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGj1Gnm0YVQJkLsExy_:-MGj1Gnm0YVQJkLsExya:bjh3q8k) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/Examples/r/Makefile#L128)):*
> ```
> OUTPUT*
> ```

Why the wildcard?
___
*[LibOS/shim/src/shim_checkpoint.c, line 705 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGjJybI5cuN9y4NnAy8:-MGjJybJ6WAm8lM7zQhR:b-re205x) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/LibOS/shim/src/shim_checkpoint.c#L705)):*
> ```C
>         /* execve case: child process "replaces" this current process: no need to notify the leader
>          * or establish IPC, the only thing to do is revert self/parent PAL handles' pointers */
>         process->self->pal_handle   = NULL;
> ```

weird alignment

**Review by bigdata-memory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Examples/r/Makefile, line 124 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGje06lEIaMfdpFwpb0:-MGje06lEIaMfdpFwpb1:b-5tqlhd) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/Examples/r/Makefile#L124)):*
> ```Makefile
> 	./pal_loader R.manifest --slave --vanilla -f scripts/sample.r > OUTPUT 2> /dev/null
> 	@grep -q "success" OUTPUT && echo "[ Success 1/1 ]"
> 	@rm OUTPUT
> ```

Using $(RM) instead of raw command

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`waitpid03` LTP test failed, known problem)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: 11 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGixCw31C8eklsmCKJQ:-MGkcMP35yGjVIrf5hF0:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It also fixes #1390, could you add this to the description?
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGkehUn359iW4xm3bnQ:-MGkehUo4i4b7JP2L2ff:byr0lno) (no related file):*
FYI: I checked outputs of Jenkins, R is correctly run and tested.

---
___
*[Examples/r/Makefile, line 124 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGje06lEIaMfdpFwpb0:-MGkf-WL4NIfB-_N8nk5:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/Examples/r/Makefile#L124)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Using $(RM) instead of raw command
</blockquote></details>

Done
___
*[Examples/r/Makefile, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGj1Gnm0YVQJkLsExy_:-MGkf0R4AduX0Tra7cWx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/Examples/r/Makefile#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> OUTPUT*
> ```

Why the wildcard?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 705 at r2](https://reviewable.io/reviews/oscarlab/graphene/1799#-MGjJybI5cuN9y4NnAy8:-MGkfDyPEWgqcHLce7Il:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9cc93f371ae412c538faad651b43af4fe37a9bdd/LibOS/shim/src/shim_checkpoint.c#L705)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

weird alignment
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1799)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
