### PR TITLE
python modules in python/, and install them

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 

This is part of switching to meson, which is still optional for running from repo, but needed to install. #760

Python scripts are gathered in `/python` (#895) and are installed into system python's `dist-packages`. They are barely usable from where they are and for this they need significant mangling of `sys.path`, which is undocumented and unsupported.

The tools are renamed `graphene-sgx-sign` and `graphene-sgx-get-token`, although previous incarnation, `Linux-SGX/signer/pal-*`, still works and is what is still used in CI. Right now I'm afraid of disabling this, because people probably still rely on that and this would also mean that `make SGX=1 sgx-tokens` mechanisation would have to be reworked. So this will have to done another time. For now I added DeprecationWarning.

## How to test this PR? 

1) jenkins
2) try to install using meson, test `graphene-sgx-sign` and `graphene-sgx-get-token` as usual

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-ML41J921uDQHL5Szf93:-ML41J921uDQHL5Szf94:b-b7728g) (no related file):*
Please don't use "grapheneos" name, it should be "libos", not "os" (there exists a Graphene which is an operating system).

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: 2 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-ML41J921uDQHL5Szf93:-ML9cMhy-UrhVIoeHdeY:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't use "grapheneos" name, it should be "libos", not "os" (there exists a Graphene which is an operating system).
</blockquote></details>

Done.

---

**Review by mkow — DISMISSED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by yamahata — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-MLCIn0U4qNTpQzg40Ay:-MLCH92k71u36oizWC7m:b-f829sd) (no related file):*
Please fix Jenkins failures:
```
+ + ./.ci/run-pylint -f json
./.ci/prfilter
Using config file /home/jenkins/workspace/graphene-18.04/.pylintrc
Unable to create directory /leeroy/.pylint.d
Unable to create file /leeroy/.pylint.d/test-numpy1.stats: [Errno 2] No such file or directory: '/leeroy/.pylint.d/test-numpy1.stats'
MESSAGES AFFECTING THIS PR:
Pal/src/host/Linux-SGX/signer/pal-sgx-sign +12:30: no-member: Instance of 'PurePath' has no 'resolve' member
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token +12:30: no-member: Instance of 'PurePath' has no 'resolve' member
```

---

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-MLCIn0U4qNTpQzg40Ay:-MLDz9R6BxYUwt6MQ30L:bn7qexb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix Jenkins failures:
```
+ + ./.ci/run-pylint -f json
./.ci/prfilter
Using config file /home/jenkins/workspace/graphene-18.04/.pylintrc
Unable to create directory /leeroy/.pylint.d
Unable to create file /leeroy/.pylint.d/test-numpy1.stats: [Errno 2] No such file or directory: '/leeroy/.pylint.d/test-numpy1.stats'
MESSAGES AFFECTING THIS PR:
Pal/src/host/Linux-SGX/signer/pal-sgx-sign +12:30: no-member: Instance of 'PurePath' has no 'resolve' member
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token +12:30: no-member: Instance of 'PurePath' has no 'resolve' member
```
</blockquote></details>

This is fake, but affecting multiple PRs, so I created #1936 to be merged before this.

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[python/graphenelibos/sgx_get_token.py, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMz4CSuAhkO38Y899d-:-MMz4CSvALgd9ZGzHWhw:b-67td9o) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/python/graphenelibos/sgx_get_token.py#L27)):*
> ```Python
>         offs.SGX_XFRM_AVX:      "avx",
>         offs.SGX_XFRM_AVX512:   "avx512f",
>         offs.SGX_XFRM_MPX:      "mpx",
> ```

This will silently conflict with changes in my pending PR: https://github.com/oscarlab/graphene/pull/1983
___
*[python/graphenelibos/sgx_sign.py, line 167 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMz4dsiBy65uHcbn3wn:-MMz4dsiBy65uHcbn3wo:b-67td9o) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/python/graphenelibos/sgx_sign.py#L167)):*
> ```Python
>         'require_avx': 'XFRM_AVX',
>         'require_avx512': 'XFRM_AVX512',
>         'require_mpx': 'XFRM_MPX',
> ```

This will silently conflict with changes in my pending PR: https://github.com/oscarlab/graphene/pull/1983

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMzSYhS6LHCcge_DmQj:-MMzSYhS6LHCcge_DmQk:b-6e8l7i) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/.ci/lib/stage-clean-check.jenkinsfile#L18)):*
> ```
>         make -C LibOS/shim/test/ltp clean
>         # LTP's make clean is broken, see https://github.com/linux-test-project/ltp/issues/559
>         rm -rf /tmp/*/LibOS/shim/test/ltp/src
> ```

`rm -rf /tmp/graphene*.clean-check.clean/LibOS/shim/test/ltp/src` in the old version looked safer (but I see that only one copy used this more restrictive wildcard previously)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMzSYhS6LHCcge_DmQj:-MMzer1jBXx7suTk_yba:bme48hn) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/.ci/lib/stage-clean-check.jenkinsfile#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`rm -rf /tmp/graphene*.clean-check.clean/LibOS/shim/test/ltp/src` in the old version looked safer (but I see that only one copy used this more restrictive wildcard previously)
</blockquote></details>

In principle, `graphene*` depends on job name in jenkins (or at least on our helper, which chooses name based on job name). Would you like `*.clean-check.clean` instead?
___
*[python/graphenelibos/sgx_get_token.py, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMz4CSuAhkO38Y899d-:-MMzfBPm8O_rrfWNoOj5:b2nhysk) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/python/graphenelibos/sgx_get_token.py#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will silently conflict with changes in my pending PR: https://github.com/oscarlab/graphene/pull/1983
</blockquote></details>

ack
___
*[python/graphenelibos/sgx_sign.py, line 167 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMz4dsiBy65uHcbn3wn:-MMzfE1S5pLQNZZlFqMO:b2nhysk) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/python/graphenelibos/sgx_sign.py#L167)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will silently conflict with changes in my pending PR: https://github.com/oscarlab/graphene/pull/1983
</blockquote></details>

ack

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMzSYhS6LHCcge_DmQj:-MN-2Ys9DHVlVTsWmvHZ:b-bjg5qg) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/.ci/lib/stage-clean-check.jenkinsfile#L18)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

In principle, `graphene*` depends on job name in jenkins (or at least on our helper, which chooses name based on job name). Would you like `*.clean-check.clean` instead?
</blockquote></details>

Yup, sounds good.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: 31 of 32 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/1909#-MMzSYhS6LHCcge_DmQj:-MN-3IojEtHSTZ_gSF5t:buk5arf) ([raw file](https://github.com/oscarlab/graphene/blob/3009476970541d140133390368cfec3b3b21266c/.ci/lib/stage-clean-check.jenkinsfile#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, sounds good.
</blockquote></details>

Done.

(sorry for line shifting, but I grouped the overrides together, because the first time I overlooked one of those)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-MN-86QeE1PMrhYqsjFm:-MN-86QeE1PMrhYqsjFn:bv068p1) (no related file):*
Don't merge yet, we're fixing GSC problems with Anjo.

---

**Review by yamahata — DISMISSED** [review]
> Reviewed 22 of 23 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: 20 of 38 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1909#-MN-86QeE1PMrhYqsjFm:-MN8ix7_CJITFzlm2qdC:b6h3ulr) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Don't merge yet, we're fixing GSC problems with Anjo.
</blockquote></details>

Should be fixed.

---

**Review by mkow — APPROVED** [review]
> Reviewed 13 of 13 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by mkow — APPROVED** [review]
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1909)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
