### PR TITLE
Fix kernel warning with CONFIG_DEBUG_VM on

### PR DESCRIPTION
**Pull request by woachk**
Botched totally the other request so this is it made again...

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/269)

### CODE REVIEW

**Comment by donporter** [comment]
Ok to test

**Comment by chiache** [comment]
This patch looks harmless to me, but I am not sure what exactly is the rationale. Would you mind adding some more explanation to the PR description?

**Comment by woachk** [comment]
@chiache line 93 of https://github.com/torvalds/linux/blob/master/mm/slab_common.c

**Comment by donporter** [comment]
I know I had already approved, but is there a good reason not to use underscores "_" vs just smashing the words together?

**Comment by woachk** [comment]
@donporter - and _ are safe to use

**Pull request merged**
