### PR TITLE
[Pal/Linux-SGX] tools: add ECDSA signing algo to RA-TLS certs

### LINKED ISSUE #2266: Enable configurable signing algorithm in RA-TLS (currently forced to use RSA)
This is a feature request to support ECDSA in addition to RSA as the choice of signing algorithm used by RA-TLS. From https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h, it appears that currently the certs are forced to be RSA based certs. It would be great if ECDSA based RA-TLS certs can be supported. 

I would further request to permit the ECDSA curve choice as a configuration parameter.

In our application, we use components such as the Microsoft Confidential Consortium Framework (CCF) blockchain, which currently only supports ECDSA based client certs for mTLS. 

Thanks
Prakash

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, RA-TLS generated only RSA keypairs (and signed self-signed RA-TLS X.509 certificates with these RSA keys). This PR adds the ability to choose between RSA and ECDSA (four popular curves are currently supported for ECDSA: SECP256K1, SECP256R1, SECP384R1, SECP521R1). A new envvar for RA-TLS is added to choose signing algo: `RA_TLS_CERT_SIGNATURE_ALGO`.

Fixes #2266.

## How to test this PR? 

I added `loader.env.RA_TLS_CERT_SIGNATURE_ALGO = "ECDSA_SECP256K1"` to two examples: `ra-tls-mbedtls` and `ra-tls-secret-prov`.

Without this PR (or without this new envvar), `ra-tls-mbedtls` example prints something like this:
```
<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256</p>
```

With this PR (and with this new envvar etting), it prints something like this:
```
<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256</p>
```

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2314)

### CODE REVIEW

**Review by vijaydhanraj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2314)* status: 0 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2dsiI8VWyxx3SdyiZ:-Mb2dsiI8VWyxx3Sdyi_:bkq2dc0) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L163)):*
> ```C
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(pk, pk_der, PUB_KEY_SIZE_MAX);
>     if (pk_der_size_byte <= 0)
> ```

Based on the previous code (`RSA keypair`) it looks like we expected exactly `RSA_PUB_3072_KEY_DER_LEN` bytes to be written but now the condition is relaxed. Is this expected or should we handle this differently for RSA and ECDSA?

Found this table from https://crypto.stackexchange.com/questions/87715/what-is-the-public-key-length-of-rsa-and-ed25519
```
The 'standard' RSA sizes with e=65537 represented as SubjectPublicKeyInfo in DER and base64 are:

modulus bits	DER bytes	base64 chars
512	         30+64=94	128
768	         30+96=126	168
1024	         34+128=162	216
1536	         34+192=226	304
2048	         38+256=294	392
3072	         38+384=422	564
4096	         38+512=546	736
```

If you have some other links, pls do share. Will be helpful to understand.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2if6VAQ6Co7NLN1w8:-Mb2if6VAQ6Co7NLN1w9:bwcgu42) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L183)):*
> ```C
>     }
> 
>     if (!strcmp(key_algo, RA_TLS_CERT_SIGNATURE_ALGO_RSA)) {
> ```

Since the public key setup `mbedtls_pk_setup` is common between the algos, would it be better to pull out of `if..else` construct? This is just a suggestion, fine with current implementation as well.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2dyLUESrBlru_D7OP:-Mb2dyLUESrBlru_D7OQ:b-g9kyag) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L192)):*
> ```C
> 
>         ret = mbedtls_rsa_gen_key((mbedtls_rsa_context*)pk->pk_ctx, mbedtls_ctr_drbg_random,
>                                   ctr_drbg, RSA_PUB_3072_KEY_LEN, RSA_PUB_EXPONENT);
> ```

should we rename `ctr_drbg` -> `ctx_drbg` or `ctx_ctr_drbg` as this is represents the RNG context?
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2eqPD-_FzdZqSp6jM:-Mb2eqPD-_FzdZqSp6jN:b-i8gdex) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L217)):*
> ```C
> 
>         ret = mbedtls_ecp_gen_key(elliptic_curve_group_id, mbedtls_pk_ec(*pk),
>                                   mbedtls_ctr_drbg_random, ctr_drbg);
> ```

ditto and all other references as well
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2aKVg37kke2GpYYQh:-Mb2aKVg37kke2GpYYQi:b9ztg6e) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L154)):*
> ```C
>     /* below function writes data at the end of the buffer */
>     int pk_der_size_byte = mbedtls_pk_write_pubkey_der(&crt->pk, pk_der, PUB_KEY_SIZE_MAX);
>     if (pk_der_size_byte <= 0)
> ```

pls refer to earlier comment.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2314)* status: 0 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2dsiI8VWyxx3SdyiZ:-Mb5vP1pEVEEkq3rL_f2:btortxd) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L163)):*
> Is this expected or should we handle this differently for RSA and ECDSA?

This is expected. There is generally no reason to double-check the returned size of `mbedtls_pk_write_pubkey_der()`. The function is expected to behave correctly (and thus return a correct size) or fail (in this case the return value is zero or negative). I would say that the previous check (`pk_der_size_byte != RSA_PUB_3072_KEY_DER_LEN`) was an overkill.

> If you have some other links, pls do share. Will be helpful to understand.

I don't have any specific links.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2if6VAQ6Co7NLN1w8:-Mb5w7beDp4ASlhewCt5:bo6b6bk) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L183)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Since the public key setup `mbedtls_pk_setup` is common between the algos, would it be better to pull out of `if..else` construct? This is just a suggestion, fine with current implementation as well.
</blockquote></details>

I don't know, I kinda like that code for each of the algos is completely self-contained. So I would prefer to leave it as-is.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2dyLUESrBlru_D7OP:-Mb5wEFV4pKN3BzF7l79:bo2y2iu) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L192)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

should we rename `ctr_drbg` -> `ctx_drbg` or `ctx_ctr_drbg` as this is represents the RNG context?
</blockquote></details>

`crt_drbg` is an mbedTLS name by convention, I didn't want to modify it. The reasoning is: if a person who knows mbedTLS well looks at this code, she will easily map her previous experience to this code.

**Review by vijaydhanraj — COMMENTED** [review]
Thanks, @dimakuv, looks good to me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2314#-:-Mb7dKTH-QcQm0jaGdBt:bhdkmpr)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2dsiI8VWyxx3SdyiZ:-Mb7dDOEB8B0g7arw1_e:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Is this expected or should we handle this differently for RSA and ECDSA?

This is expected. There is generally no reason to double-check the returned size of `mbedtls_pk_write_pubkey_der()`. The function is expected to behave correctly (and thus return a correct size) or fail (in this case the return value is zero or negative). I would say that the previous check (`pk_der_size_byte != RSA_PUB_3072_KEY_DER_LEN`) was an overkill.

> If you have some other links, pls do share. Will be helpful to understand.

I don't have any specific links.
</blockquote></details>

OK.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/2314#-Mb2if6VAQ6Co7NLN1w8:-Mb7dFMc6c94jhPkgG-o:bp72gxf) ([raw file](https://github.com/oscarlab/graphene/blob/12372e08fea0c3f27682cd78d328754031d4a891/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't know, I kinda like that code for each of the algos is completely self-contained. So I would prefer to leave it as-is.
</blockquote></details>

sounds fair.

**Comment by dimakuv** [comment]
This PR should be re-created in the new Gramine repo. Closing it here.

**Pull request closed without merging**
