### PR TITLE
[LibOS] Do not remove IPC connection on errors

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
If an error occurred while sending an IPC message, the connection was removed (which could happen twice due to buggy implementation).
Now in such case the connection is not removed, but the error is saved and any further writes to that connection will immediately return the saved error.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)

### CODE REVIEW

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdOODow3Z7shCjEnNL8:-MdOODow3Z7shCjEnNL9:b-cagpf2) (no related file):*
Doesn't it mean that the comment on line https://github.com/oscarlab/graphene/blob/205cbe0123978b7b178c413a172b0be38658ef55/LibOS/shim/src/ipc/shim_ipc_worker.c#L84 is outdated with this PR? I talk about `other than a failure to send...`

---
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 215 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdONXhy-7RxVZ6lOBk5:-MdONXhy-7RxVZ6lOBk6:b-xdqka4) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L215)):*
> ```C
>     if (conn->seen_error) {
>         ret = conn->seen_error;
>         log_debug("%s: returning previously seen error: %d\n", __func__, ret);
> ```

This should be changed (`\n` removed) after 2486 is merged.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 221 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdOOPeJ-vHGzCqWRypM:-MdOOPeJ-vHGzCqWRypN:bhdyvdc) ([raw file](https://github.com/oscarlab/graphene/blob/205cbe0123978b7b178c413a172b0be38658ef55/LibOS/shim/src/ipc/shim_ipc.c#L221)):*
> ```C
>         log_error("Failed to send IPC msg to %u: %d\n", conn->vmid, ret);
>         unlock(&conn->lock);
>         remove_ipc_connection(conn);
> ```

So we now rely solely on `disconnect_callbacks()` to do the connection cleanup? Can it lead to memory leaks?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdOODow3Z7shCjEnNL8:-MdOSdBSC3dHLvvojbn5:byhuodp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Doesn't it mean that the comment on line https://github.com/oscarlab/graphene/blob/205cbe0123978b7b178c413a172b0be38658ef55/LibOS/shim/src/ipc/shim_ipc_worker.c#L84 is outdated with this PR? I talk about `other than a failure to send...`
</blockquote></details>

Well, technically it's still correct, we still detect such errors and it does not say that we remove the connection on failed sends...
If you have some idea how to phrase that better please let me know.

---
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 215 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdONXhy-7RxVZ6lOBk5:-MdOTA9T3r9p0gXWJyVb:bqhalzv) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be changed (`\n` removed) after 2486 is merged.
</blockquote></details>

Which will happen most likely soon, so:
TODO: at rebase.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 221 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdOOPeJ-vHGzCqWRypM:-MdOTHZR-C08rLYN54Ig:b-ec85gm) ([raw file](https://github.com/oscarlab/graphene/blob/205cbe0123978b7b178c413a172b0be38658ef55/LibOS/shim/src/ipc/shim_ipc.c#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So we now rely solely on `disconnect_callbacks()` to do the connection cleanup? Can it lead to memory leaks?
</blockquote></details>

We always did. This code block triggered only because there was a failure and remote process died, it does not trigger in a normal case.

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdP0mxa5R1TKuLttEND:-MdP0mxa5R1TKuLttENE:bolcsso) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L29)):*
> ```C
>     struct avl_tree_node node;
>     IDTYPE vmid;
>     int seen_error;
> ```

Maybe a better name would be `last_error`? Not blocking though.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdP0mxa5R1TKuLttEND:-MdPBMsWB2EhfVTtBoCo:b-ifvmvx) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe a better name would be `last_error`? Not blocking though.
</blockquote></details>

I don't particularly like the current name either, but `last_error` would hint than there could be more than one error (which is not true).

**Comment by boryspoplawski** [comment]
Jenkins, retest this please (just making sure)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdP0mxa5R1TKuLttEND:-MdPCNQ033GHKzZU2PHH:b-xia6g7) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't particularly like the current name either, but `last_error` would hint than there could be more than one error (which is not true).
</blockquote></details>

It's not a "public" field (at least as much as something can be private in C), so `last_error` wouldn't be confusing to me - it's just a field used inside the implementation of IPC operations and they can have "stop on error" semantics which checks "the last error which was seen". There just won't be any chance to create other errors and that's known to the users of this field.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdOODow3Z7shCjEnNL8:-MdQzg9-8AMfMeIMouii:bnui0b4) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, technically it's still correct, we still detect such errors and it does not say that we remove the connection on failed sends...
If you have some idea how to phrase that better please let me know.
</blockquote></details>

OK, since it's correct, unblocking.

---

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 215 at r1](https://reviewable.io/reviews/oscarlab/graphene/2487#-MdONXhy-7RxVZ6lOBk5:-MdRdEev4dYaSZrdOGo4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/01bf5341342a858aadb056e34f9b43ac10f34bb2/LibOS/shim/src/ipc/shim_ipc.c#L215)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Which will happen most likely soon, so:
TODO: at rebase.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2487)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
