### PR TITLE
[LibOS,Pal] Emulate SIGPIPE via creating and sending this signal on EPIPE

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Previously, Graphene simply forwarded SIGPIPE generated by the host to LibOS/app. Unfortunately, SIGPIPE generation is a process-wide feature and there is no portable way to restrict it only to a subset of pipes, UNIX domain sockets, etc. This led to sporadic Graphene failures because Graphene's internal use of pipes and sockets may result in an unexpected (to application) SIGPIPE.

This commit removes the forwarding of SIGPIPE. Instead, PALs explicitly ignore SIGPIPE. This forces the host to return EPIPE error code, which is checked only on a subset of LibOS handles (the ones created by the app), and if required, LibOS generates a SIGPIPE for the application.

While adding this logic, the whole PAL exception code was refactored, both in Linux and Linux-SGX. 

Fixes https://github.com/oscarlab/graphene/issues/1534.

## How to test this PR? 

Tests for SIGPIPE are now enabled for both Linux and Linux-SGX PALs. In particular, `sighandler_sigpipe` LibOS regression test.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1542)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, test this please (additional run 1/N to be sure)

**Comment by dimakuv** [comment]
Jenkins, test this please (additional run 2/N to be sure)

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 2/5; previous run was successful)

**Comment by mkow** [comment]
Jenkins, retest this please (run 3/5; previous run was successful)

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 4/5; previous run was successful)

**Comment by dimakuv** [comment]
Jenkins, retest this please (run 5/5; previous run was successful)

**Pull request merged**
