### PR TITLE
Use SPDX IDs for licenses in source files

### PR DESCRIPTION
**Pull request by mkow**
Please verify that I didn't accidentally drop anyone's copyright or picked a wrong SPDX id.

Depends on https://github.com/oscarlab/graphene-sgx-driver/pull/21.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1566)

### CODE REVIEW

**Comment by mkow** [comment]
Jenkins, retest Jenkins-Debug please (`fork11` failed, known issue)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (`kill03` LTP test failed, interesting)

**Comment by mkow** [comment]
Jenkins, retest Jenkins please (`kill03` test timed out again, this gets even more interesting...)

**Comment by mkow** [comment]
FYI: I wasn't able to reproduce the `kill03` failures neither or master nor on this branch, I guess this is just that old and rare timeout on LTP.

**Pull request merged**
