### PR TITLE
[Pal/Linux-SGX] Fix EGETKEY usage to enhance security

### PR DESCRIPTION
**Pull request by llly**
Most fields of KEYREQUEST structure are 0s when retrieving Seal key as `g_enclave_key`. Seal keys are always the same in different programs and different instances on a hardware platform. The EGETKEY usage is incorrect.

Currently `g_enclave_key` is only used when loading and verifying trusted file. Leaking the key or sharing same key between different signer(AKA private key) is a security issue.

members KEYREQUEST structure in this PR:
1. key_name: SEAL_KEY //Seal key
2. key_policy: KEYPOLICY_MRSIGNER //enclave signed by same signer can verify each other.
3. isv_svn: //isv_svn from report, which comes from manifest
4. cpu_svn: //cpu_svn  from report which comes from SGX secs
5. attribute_mask: //Set the bits which have no security implications to 0 for sealed data migration
6. key_id: //random number to retrieve different key in different instance.
7. config_svn: //config_svn from report which comes from SGX secs

Reference:
` EGETKEY—Retrieves a Cryptographic Key` section in [architectures-software-developer](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf)

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2000)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2000)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNhK6YB2vUL5hB4F6o:-MNNhK6YB2vUL5hB4F6p:b-b58ng6) (no related file):*
Thanks, good PR!

Currently `g_enclave_key` (the only user of this func) is rather useless, but I agree we must harden this function now, for future-proof.

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNeiyf2jeih5ahtwbD:-MNNeiyf2jeih5ahtwbE:bsc6wu5) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L185)):*
> ```C
> }
> 
> int init_enclave_key(void) {
> ```

Could you add a top-level comment here? Smth like this:
```
/* Let SGX generate an enclave-specific seal key via EGETKEY(SEAL_KEY). Key derivation material
 * includes security-relevant bits of the enclave ATTRIBUTES data struct (e.g., DEBUG bit to prevent
 * secret migration between debug and production enclaves), MRSIGNER key policy (to allow secret
 * migration between different enclaves of the same author/signer), CPU & ISV & CONFIG SVNs (to
 * prevent secret migration to older vulnerable versions of the enclave). Currently the derivation
 * material also includes random KEYID which makes this seal key non-reproducible even by other
 * enclaves from the same signer. */
```

Please also re-wrap this comment to 100 char limit. And add/reword whatever you feel is necessary.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNc0Qi9xFq_n9yV7_9:-MNNc0QjDeylE0qlZvg2:b-z5qaz6) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L192)):*
> ```C
>     #define FLAGS_NON_SECURITY_BITS (0xFFFFFFFFFFFFC0ULL | SGX_FLAGS_MODE64BIT | \
>         SGX_FLAGS_PROVISION_KEY | SGX_FLAGS_LICENSE_KEY)
>     #define TSEAL_DEFAULT_FLAGSMASK (~FLAGS_NON_SECURITY_BITS)
> ```

This is a bit contrived, cannot we revert it?

I would prefer to specify the security bits:
```
keyrequest.attribute_mask.flags = SGX_FLAGS_INITIALIZED | SGX_FLAGS_DEBUG | SGX_FLAGS_RESERVED_BIT3;
```

(we'll need to add `SGX_FLAGS_RESERVED_BIT3` to the list in `sgx_arch.h`.)

I guess you made it "non_security" for the future. Maybe your version is better, but I'd like to hear your reasoning.

By the way, `SGX_FLAGS_INITIALIZED` and `SGX_FLAGS_DEBUG` are **always** set by EGETKEY logic.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 207 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNdYSqC-kuWic5YCL5:-MNNdYSr-Cob8l14NK5e:bvju9dm) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L207)):*
> ```C
>     int ret = sgx_get_report(&tmp_target_info, &tmp_report_data, &tmp_report);
>     if (ret) {
>         SGX_DBG(DBG_E, "Can't get report\n");
> ```

Please change to `"Failed to get enclave report\n"`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 212 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNdeJHBXrz9NsJnsab:-MNNdeJI8jO7vq9GdVNa:bbg7fd4) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L212)):*
> ```C
> 
>     memcpy(&(keyrequest.cpu_svn), &(tmp_report.body.cpu_svn), sizeof(sgx_cpu_svn_t));
>     memcpy(&(keyrequest.isv_svn), &(tmp_report.body.isv_svn), sizeof(sgx_isv_svn_t));
> ```

In these two lines: no need for `(` and `)`.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 213 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNe7GU56g4Lik4jrBZ:-MNNe7GU56g4Lik4jrB_:b6m5zjm) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L213)):*
> ```C
>     memcpy(&(keyrequest.cpu_svn), &(tmp_report.body.cpu_svn), sizeof(sgx_cpu_svn_t));
>     memcpy(&(keyrequest.isv_svn), &(tmp_report.body.isv_svn), sizeof(sgx_isv_svn_t));
>     keyrequest.config_svn = tmp_report.body.config_svn;
> ```

Please change to `memset(&keyrequest.config_svn, ...)` just like in the other two lines.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 216 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNge1TAYbEZK-P2q11:-MNNge1TAYbEZK-P2q12:b-n6h7v6) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L216)):*
> ```C
> 
>     // Get a random number to populate the key_id of the key_request
>     ret = _DkRandomBitsRead(&keyrequest.key_id, sizeof(keyrequest.key_id));
> ```

Is this what you want? We throw random bytes in the mix, so all other preparations (attributes mask, MRSIGNER policy, SVNs) are useless -- this key will be unique **only** to this enclave and won't be reproducible by any other enclave, even with the same signer.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 223 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNeRTNB46E7PkKlsqn:-MNNeRTNB46E7PkKlsqo:b4d7d28) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L223)):*
> ```C
>     ret = sgx_getkey(&keyrequest, &g_enclave_key);
>     if (ret) {
>         SGX_DBG(DBG_E, "Can't get seal key\n");
> ```

Please change to `"Failed to get seal key\n"`

**Review by llly — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2000)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNeiyf2jeih5ahtwbD:-MNRluMIEWoY2nzL7bpU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a top-level comment here? Smth like this:
```
/* Let SGX generate an enclave-specific seal key via EGETKEY(SEAL_KEY). Key derivation material
 * includes security-relevant bits of the enclave ATTRIBUTES data struct (e.g., DEBUG bit to prevent
 * secret migration between debug and production enclaves), MRSIGNER key policy (to allow secret
 * migration between different enclaves of the same author/signer), CPU & ISV & CONFIG SVNs (to
 * prevent secret migration to older vulnerable versions of the enclave). Currently the derivation
 * material also includes random KEYID which makes this seal key non-reproducible even by other
 * enclaves from the same signer. */
```

Please also re-wrap this comment to 100 char limit. And add/reword whatever you feel is necessary.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNc0Qi9xFq_n9yV7_9:-MNRlqxc8tkg1leTxc12:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a bit contrived, cannot we revert it?

I would prefer to specify the security bits:
```
keyrequest.attribute_mask.flags = SGX_FLAGS_INITIALIZED | SGX_FLAGS_DEBUG | SGX_FLAGS_RESERVED_BIT3;
```

(we'll need to add `SGX_FLAGS_RESERVED_BIT3` to the list in `sgx_arch.h`.)

I guess you made it "non_security" for the future. Maybe your version is better, but I'd like to hear your reasoning.

By the way, `SGX_FLAGS_INITIALIZED` and `SGX_FLAGS_DEBUG` are **always** set by EGETKEY logic.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 207 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNdYSqC-kuWic5YCL5:-MNRlv_i-mFRq_6MOoXW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to `"Failed to get enclave report\n"`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 212 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNdeJHBXrz9NsJnsab:-MNRlwPG5Qise0gZnFPm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In these two lines: no need for `(` and `)`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 213 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNe7GU56g4Lik4jrBZ:-MNRlx6JBy0bkB3m-Yer:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L213)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to `memset(&keyrequest.config_svn, ...)` just like in the other two lines.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 216 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNge1TAYbEZK-P2q11:-MNR5LKh21w-cfJ_OiYL:b-xiiq06) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L216)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this what you want? We throw random bytes in the mix, so all other preparations (attributes mask, MRSIGNER policy, SVNs) are useless -- this key will be unique **only** to this enclave and won't be reproducible by any other enclave, even with the same signer.
</blockquote></details>

Yes. That's what I want. Same generated key for different enclave or instance is not a good idea. If a signer signed several enclaves and one of them has security issue that leaks the enclave key,  other enclaves are impacted.
Currently `keyrequest` is discarded, enclaves can exchange `keyrequest` via non-security channel  to reproduce enclave key if needed.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 223 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNeRTNB46E7PkKlsqn:-MNRm2SS1B7MJJekNHjJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to `"Failed to get seal key\n"`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2000)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 216 at r1](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNNge1TAYbEZK-P2q11:-MNSmyhtDN9Gnr2mHA7l:bwvlthd) ([raw file](https://github.com/oscarlab/graphene/blob/f2892a4ef05c1310e8e62155718320d630d9a00b/Pal/src/host/Linux-SGX/enclave_framework.c#L216)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Yes. That's what I want. Same generated key for different enclave or instance is not a good idea. If a signer signed several enclaves and one of them has security issue that leaks the enclave key,  other enclaves are impacted.
Currently `keyrequest` is discarded, enclaves can exchange `keyrequest` via non-security channel  to reproduce enclave key if needed.
</blockquote></details>

OK, agreed.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 198 at r2](https://reviewable.io/reviews/oscarlab/graphene/2000#-MNSmgYX6-4FtGUqQxPI:-MNSmgYY35NzpWuznin7:b-8u1z6c) ([raw file](https://github.com/oscarlab/graphene/blob/dabf919c1a725e2053ee30ffdd47be1c4b4be976/Pal/src/host/Linux-SGX/enclave_framework.c#L198)):*
> ```C
> 
>     keyrequest.attribute_mask.flags = SGX_FLAGS_INITIALIZED | SGX_FLAGS_DEBUG | \
> 				      SGX_FLAGS_RESERVED_BIT3;
> ```

Please replace tabs with spaces and indent accordingly.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2000)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Comment by dimakuv** [comment]
Jenkins, test this please

**Comment by dimakuv** [comment]
Though this PR is correct in that `g_enclave_key` is insecure, I'm closing it since my future PR will remove `g_enclave_key` completely. See https://github.com/oscarlab/graphene/issues/2326.

**Pull request closed without merging**
