### PR TITLE
[LibOS] Increase internal stack size

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
See commits messages.

## How to test this PR? 
Normal test suite + overflow repro from @mkow

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUzoYuzDBp4K4PxBYl5:-MUzoYv0EFHtXnpzeLOg:b-pi630v) (no related file):*
FYI: I cherry-picked these two commits onto the repro commit and it stopped crashing.

---
___
*[LibOS/shim/src/fs/chroot/fs.c, line 145 at r1](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUzliFn3CP7daajfB1l:-MUzliFoDXxnm12el3r6:bpfs2ug) ([raw file](https://github.com/oscarlab/graphene/blob/44c40f43e5a882badf283d60e28e2b0f2d706240/LibOS/shim/src/fs/chroot/fs.c#L145)):*
> ```C
> 
>     struct shim_file_data* data = FILE_DENTRY_DATA(dent);
>     char* uri = malloc(URI_MAX_SIZE);
> ```

Could you instead change `concat_uri` to `alloc_concat_uri` and make it use `alloc_concat3`? We wouldn't need to overallocate nor have this hardcoded limit, and the code should actually get simpler.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 389 at r1](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUznTSCEoIhnxGhtaML:-MUznTSCEoIhnxGhtaMM:b-n7tbox) ([raw file](https://github.com/oscarlab/graphene/blob/44c40f43e5a882badf283d60e28e2b0f2d706240/Pal/src/host/Linux-SGX/enclave_framework.c#L389)):*
> ```C
>     free(uri);
>     free(normpath);
>     /* Sanity checks */
> ```

checks?

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: 3 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUzoYuzDBp4K4PxBYl5:-MUzyvlA8cLimhHd8EBs:b-9n79bd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: I cherry-picked these two commits onto the repro commit and it stopped crashing.
</blockquote></details>

Yeah, I've done the same before submitting this PR.

---
___
*[LibOS/shim/src/fs/chroot/fs.c, line 145 at r1](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUzliFn3CP7daajfB1l:-MUzz-_J5x9jO4Tgg-FD:b3802c0) ([raw file](https://github.com/oscarlab/graphene/blob/44c40f43e5a882badf283d60e28e2b0f2d706240/LibOS/shim/src/fs/chroot/fs.c#L145)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you instead change `concat_uri` to `alloc_concat_uri` and make it use `alloc_concat3`? We wouldn't need to overallocate nor have this hardcoded limit, and the code should actually get simpler.
</blockquote></details>

Done.
But I'm not sure if this was worth it.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 389 at r1](https://reviewable.io/reviews/oscarlab/graphene/2209#-MUznTSCEoIhnxGhtaML:-MUzz2_51KyIkB9gdOgn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/44c40f43e5a882badf283d60e28e2b0f2d706240/Pal/src/host/Linux-SGX/enclave_framework.c#L389)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

checks?
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV-4yFL52fC9_9jhdYM:b-tyuk4i) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
> ```C
>     size_t prefix_len = strlen(prefix);
>     size_t alloc_len = prefix_len + root_len + 1 + path_len + 1;
>     if (alloc_len > URI_MAX_SIZE) {
> ```

Do we need this check anymore? This max size is IMO just for placed which aren't written well enough to support arbitrary lengths, I think there's no need to add this limitation here.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV-ETcmDrwZwjTtEatZ:b-vhejut) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we need this check anymore? This max size is IMO just for placed which aren't written well enough to support arbitrary lengths, I think there's no need to add this limitation here.
</blockquote></details>

No idea, I've just preserved the old semantics. I don't want to dig and check that no code paths depend on it.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV-GfT-3KQdSMRNwEVI:b-okwl3a) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea, I've just preserved the old semantics. I don't want to dig and check that no code paths depend on it.
</blockquote></details>

How can something depend on this? Every such place should have proper checks (I mean, if it copies it to a limited stack buffer, etc).
I'd just drop it and don't preserve this ugliness in newly-refactored code. We should be slowly getting rid of it completly and don't limit the URI lengths anywhere.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV-PXHr8v1aYugCZhPU:b2qy36r) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How can something depend on this? Every such place should have proper checks (I mean, if it copies it to a limited stack buffer, etc).
I'd just drop it and don't preserve this ugliness in newly-refactored code. We should be slowly getting rid of it completly and don't limit the URI lengths anywhere.
</blockquote></details>

I don't know, something like strcpy to a fixed sized buffer, because it knew string coming from this function can not have more than X bytes?

**Review by dimakuv — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by yamahata — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV2EtRnALKJies4JoDQ:-MV2EtRnALKJies4JoDR:bpnd68a) (no related file):*
Do we want to add gcc option -Wstack-usage=1024 or something?

---

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV2GbR43iLNgtMjKXUa:b-sn4yw8) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't know, something like strcpy to a fixed sized buffer, because it knew string coming from this function can not have more than X bytes?
</blockquote></details>

I checked it briefly and:
* qstr has additional length limit (no idea why), so it will fail right afterwards anyways,
* I check how host_uri is used and it looked fine.

I'd really prefer to not add this artificial limitation in new code.

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV2EtRnALKJies4JoDQ:-MV2KQ_74tENY5UDzr2z:b-dfmiph) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Do we want to add gcc option -Wstack-usage=1024 or something?
</blockquote></details>

We have multiple stacks, not sure if it's worth handling it as gcc options...

---
___
*[LibOS/shim/src/fs/chroot/fs.c, line 105 at r2](https://reviewable.io/reviews/oscarlab/graphene/2209#-MV-4yFL52fC9_9jhdYL:-MV2KX_t2tIJ1V2q5yh8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09e3d44f32a2426513c6baed5f7a83d6cf2bf41b/LibOS/shim/src/fs/chroot/fs.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I checked it briefly and:
* qstr has additional length limit (no idea why), so it will fail right afterwards anyways,
* I check how host_uri is used and it looked fine.

I'd really prefer to not add this artificial limitation in new code.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)

**Review by yamahata — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2209)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
