### PR TITLE
Migrate unit tests to jenkins

### PR DESCRIPTION
**Pull request by donporter**
This patch migrates unit tests on the Linux host from Travis to Jenkins, which should make for more reliable unit testing.  This also runs the unit tests on both the normal and Debug builds for the Linux host.  Linux-SGX coming soon.

Finally, this also extends the .gitignore files to better ignore generated output from the unit tests.

### CODE REVIEW

**Comment by donporter** [comment]
Test this please

**Comment by neilbd** [comment]
test this please

**Comment by neilbd** [comment]
test this please

**Comment by neilbd** [comment]
Jenkins-Debug failed because the debug Jenkinsfile saw an error when running the Python test code. That means the file is working for the first few tests! Do you want me to merge the file, or do you want to fix the other issue first?

**Comment by donporter** [comment]
Let's get these Jenkins jobs passing before we merge.

**Pull request merged**
