### PR TITLE
Enable --std=c11 in the compiler options for PALs

### PR DESCRIPTION
**Pull request by chiache**
I plan to roll out the patches for C11 incrementally. This PR specifically deals with the issues of making the Linux and SGX PAL code C11-compliant.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/289)

### CODE REVIEW

**Comment by chiache** [comment]
Test this please.

**Comment by donporter** [comment]
Is this CI failure legit?  I don't see this unit test failing very often.

**Comment by chiache** [comment]
Test this please

**Comment by mkow** [comment]
Retest this please

**Pull request merged**
