### PR TITLE
[LibOS] test/ltp: Enable more tests

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

I noticed that some LTPs are actually working or don't require extended timeout.

## How to test this PR? 

CI.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1845)

### CODE REVIEW

**Review by dimakuv — DISMISSED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1845)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1845)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1845)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1845)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
